export const  almocosDisney = [
// MainStreet
{
  nome: "Tony’s Town Square Restaurant",
  regiao: "MainStreet",
  tipo: "Classico",
  acesso: "Logo após a entrada principal do parque, ao lado do Town Square Theater",
  precoMedio: 36,
  destaque: "Italiano clássico em ambiente elegante, com massas e almôndegas ao estilo 'A Dama e o Vagabundo'.",
  latitude: 28.4184,
  longitude: -81.5819,
},
{
  nome: "Main Street Bakery",
  regiao: "MainStreet",
  tipo: "Tematico",
  acesso: "Ao longo da Main Street, próximo à loja Emporium",
  precoMedio: 14,
  destaque: "Padaria/Starbucks do parque com cafés, cinnamon rolls e lanches rápidos.",
  latitude: 28.4186,
  longitude: -81.5821,
},
{
  nome: "Casey’s Corner",
  regiao: "MainStreet",
  tipo: "Conforto",
  acesso: "No fim da Main Street, virando à esquerda antes do castelo",
  precoMedio: 17,
  destaque: "Hot dogs clássicos com batatas fritas e opções como chili e cheddar.",
  latitude: 28.4187,
  longitude: -81.5824,
},
{
  nome: "Plaza Ice Cream Parlor",
  regiao: "MainStreet",
  tipo: "Economico",
  acesso: "Ao lado do Casey’s Corner, com vista para o castelo",
  precoMedio: 10,
  destaque: "Sundaes e milkshakes tradicionais em serviço rápido.",
  latitude: 28.4188,
  longitude: -81.5825,
},
{
  nome: "The Plaza Restaurant",
  regiao: "MainStreet",
  tipo: "Saudavel",
  acesso: "Ao lado do Plaza Ice Cream, em frente ao hub central",
  precoMedio: 20,
  destaque: "Cardápio leve com saladas, sanduíches e opções vegetarianas.",
  latitude: 28.4189,
  longitude: -81.5826,
},

// Adventureland
{
  nome: "Skipper Canteen",
  regiao: "Adventureland",
  tipo: "Classico",
  acesso: "Ao lado da atração Jungle Cruise",
  precoMedio: 35,
  destaque: "Culinária internacional com toques asiáticos e africanos em ambiente de exploração.",
  latitude: 28.4181,
  longitude: -81.5843,
},
{
  nome: "Tortuga Tavern",
  regiao: "Adventureland",
  tipo: "Tematico",
  acesso: "Em frente à atração Pirates of the Caribbean",
  precoMedio: 19,
  destaque: "Pratos rápidos inspirados no Caribe em um espaço temático de piratas (opera sazonalmente).",
  latitude: 28.4180,
  longitude: -81.5841,
},
{
  nome: "Sunshine Tree Terrace",
  regiao: "Adventureland",
  tipo: "Conforto",
  acesso: "Ao lado da atração The Magic Carpets of Aladdin",
  precoMedio: 11,
  destaque: "Swirls e bebidas cítricas; o sabor de laranja é o clássico da casa.",
  latitude: 28.4178,
  longitude: -81.5839,
},
{
  nome: "Aloha Isle",
  regiao: "Adventureland",
  tipo: "Economico",
  acesso: "Em frente à Tiki Room",
  precoMedio: 9,
  destaque: "Ponto tradicional de Dole Whip de abacaxi, inclusive em float com suco.",
  latitude: 28.4177,
  longitude: -81.5840,
},
{
  nome: "Adventureland Spring Roll Cart",
  regiao: "Adventureland",
  tipo: "Saudavel",
  acesso: "Na entrada de Adventureland, à direita da ponte que vem do hub",
  precoMedio: 12,
  destaque: "Carrinho dos famosos rolinhos primavera do parque; lanche rápido para beliscar.",
  latitude: 28.4183,
  longitude: -81.5831,
},

// Frontierland
{
  nome: "Pecos Bill Tall Tale Inn and Cafe",
  regiao: "Frontierland",
  tipo: "Classico",
  acesso: "Ao lado da antiga área da Splash Mountain (próximo a Tiana’s Bayou Adventure)",
  precoMedio: 25,
  destaque: "Tex-Mex casual com bowls, nachos e burritos em ambiente de velho oeste.",
  latitude: 28.4174,
  longitude: -81.5853,
},
{
  nome: "Westward Ho",
  regiao: "Frontierland",
  tipo: "Tematico",
  acesso: "Em frente à Country Bear Jamboree",
  precoMedio: 14,
  destaque: "Quiosque de snacks rápidos estilo faroeste, ideal para uma pausa curta.",
  latitude: 28.4175,
  longitude: -81.5851,
},
{
  nome: "Golden Oak Outpost",
  regiao: "Frontierland",
  tipo: "Conforto",
  acesso: "Perto da passagem para Adventureland, na curva da Frontierland Road",
  precoMedio: 12,
  destaque: "Tenders, batatas e frituras de balcão em serviço rápido.",
  latitude: 28.4171,
  longitude: -81.5846,
},
{
  nome: "Frontierland Churro Cart",
  regiao: "Frontierland",
  tipo: "Economico",
  acesso: "Próximo à entrada da Tom Sawyer Island",
  precoMedio: 8,
  destaque: "Carrinho de churros com açúcar e canela; lanche clássico do parque.",
  latitude: 28.4173,
  longitude: -81.5850,
},
{
  nome: "Aunt Polly’s Dockside Inn",
  regiao: "Frontierland",
  tipo: "Saudavel",
  acesso: "Na Tom Sawyer Island (opera sazonalmente; acesso por balsa)",
  precoMedio: 15,
  destaque: "Sanduíches, limonadas e itens leves em ambiente tranquilo na ilha.",
  latitude: 28.4179,
  longitude: -81.5866,
},

// LibertySquare
{
  nome: "Liberty Tree Tavern",
  regiao: "LibertySquare",
  tipo: "Classico",
  acesso: "2 min a pé da Haunted Mansion",
  precoMedio: 39,
  destaque: "Refeição ao estilo colonial com assados, purês e acompanhamentos servidos à vontade.",
  latitude: 28.4190,
  longitude: -81.5834,
},
{
  nome: "The Diamond Horseshoe",
  regiao: "LibertySquare",
  tipo: "Tematico",
  acesso: "Próximo à entrada da Liberty Square",
  precoMedio: 42,
  destaque: "Saloon temático com carnes e defumados, atmosfera de show clássico.",
  latitude: 28.4191,
  longitude: -81.5838,
},
{
  nome: "Columbia Harbour House",
  regiao: "LibertySquare",
  tipo: "Conforto",
  acesso: "Na esquina entre Liberty Square e Fantasyland, em frente à ponte",
  precoMedio: 17,
  destaque: "Peixes, camarão e sanduíches; o salão do segundo andar costuma ser mais tranquilo.",
  latitude: 28.4196,
  longitude: -81.5830,
},
{
  nome: "Sleepy Hollow",
  regiao: "LibertySquare",
  tipo: "Economico",
  acesso: "Ao lado da ponte para o hub do castelo",
  precoMedio: 12,
  destaque: "Waffles recheados, funnel cakes e bebidas; ótimo para um lanche rápido.",
  latitude: 28.4187,
  longitude: -81.5829,
},
{
  nome: "Liberty Square Market",
  regiao: "LibertySquare",
  tipo: "Saudavel",
  acesso: "Ao lado do Liberty Square Riverboat",
  precoMedio: 10,
  destaque: "Frutas frescas, snacks leves e bebidas geladas em quiosque aberto.",
  latitude: 28.4193,
  longitude: -81.5832,
},
// Fantasyland
{
  nome: "Cinderella’s Royal Table",
  regiao: "Fantasyland",
  tipo: "Classico",
  acesso: "Dentro do Castelo da Cinderela",
  precoMedio: 38,
  destaque: "Almoço com toque real em ambiente icônico; pratos americanos em serviço de mesa.",
  latitude: 28.4194,
  longitude: -81.5812,
},
{
  nome: "Be Our Guest Restaurant",
  regiao: "Fantasyland",
  tipo: "Tematico",
  acesso: "2 min a pé do Seven Dwarfs Mine Train",
  precoMedio: 48,
  destaque: "Sala de jantar do castelo da Fera com culinária francesa/americana em atmosfera imersiva.",
  latitude: 28.4203,
  longitude: -81.5806,
},
{
  nome: "Gaston’s Tavern",
  regiao: "Fantasyland",
  tipo: "Conforto",
  acesso: "2 min a pé de Under the Sea – Journey of The Little Mermaid",
  precoMedio: 21,
  destaque: "Lanches rústicos, pretzels gigantes e a LeFou’s Brew para uma pausa rápida.",
  latitude: 28.4211,
  longitude: -81.5809,
},
{
  nome: "The Friar’s Nook",
  regiao: "Fantasyland",
  tipo: "Economico",
  acesso: "1 min a pé do Prince Charming Regal Carrousel",
  precoMedio: 13,
  destaque: "Mac and cheese e sanduíches rápidos em quiosque central da área.",
  latitude: 28.4199,
  longitude: -81.5817,
},
{
  nome: "Pinocchio Village Haus",
  regiao: "Fantasyland",
  tipo: "Saudavel",
  acesso: "Ao lado do it’s a small world",
  precoMedio: 18,
  destaque: "Flatbreads, saladas e vista para o canal do it’s a small world no salão superior.",
  latitude: 28.4195,
  longitude: -81.5820,
},

// Tomorrowland
{
  nome: "Cosmic Ray’s Starlight Café",
  regiao: "Tomorrowland",
  tipo: "Classico",
  acesso: "Em frente à atração Buzz Lightyear’s Space Ranger Spin",
  precoMedio: 24,
  destaque: "Clássicos de quick service com o show do Sonny Eclipse no palco principal.",
  latitude: 28.4199,
  longitude: -81.5792,
},
{
  nome: "The Lunching Pad",
  regiao: "Tomorrowland",
  tipo: "Tematico",
  acesso: "Na base do Astro Orbiter (Tomorrowland Transit Authority PeopleMover)",
  precoMedio: 16,
  destaque: "Snacks em clima espacial, hot dogs e pretzels recheados para comer em movimento.",
  latitude: 28.4201,
  longitude: -81.5793,
},
{
  nome: "Auntie Gravity’s Galactic Goodies",
  regiao: "Tomorrowland",
  tipo: "Conforto",
  acesso: "No coração de Tomorrowland, em frente ao Merchant of Venus",
  precoMedio: 12,
  destaque: "Sorvetes soft, sundaes e smoothies para refrescar entre atrações.",
  latitude: 28.4207,
  longitude: -81.5791,
},
{
  nome: "Cool Ship",
  regiao: "Tomorrowland",
  tipo: "Economico",
  acesso: "Caminho para a Space Mountain, próximo ao Cool Scanner",
  precoMedio: 9,
  destaque: "Quiosque com churros e bebidas geladas; parada rápida e barata.",
  latitude: 28.4200,
  longitude: -81.5783,
},
{
  nome: "Energy Bytes",
  regiao: "Tomorrowland",
  tipo: "Saudavel",
  acesso: "Ao lado da entrada de TRON Lightcycle / Run",
  precoMedio: 15,
  destaque: "Bowls, bites e bebidas geladas em quiosque moderno junto à TRON.",
  latitude: 28.4209,
  longitude: -81.5776,
},
// Echo Lake (Disney's Hollywood Studios)
{
  nome: "Hollywood & Vine",
  regiao: "Echo Lake",
  tipo: "Classico",
  acesso: "Praça principal de Echo Lake, perto do 50's Prime Time Café",
  precoMedio: 42,
  destaque: "Buffet de culinária americana com personagens em alguns períodos do dia.",
  latitude: 28.3574,
  longitude: -81.5581,
},
{
  nome: "50's Prime Time Café",
  regiao: "Echo Lake",
  tipo: "Tematico",
  acesso: "Atrás do Echo Lake, perto do Indiana Jones Epic Stunt Spectacular",
  precoMedio: 37,
  destaque: "Restaurante retrô dos anos 50, com equipes brincando de 'mãe' e 'tios' na mesa.",
  latitude: 28.3578,
  longitude: -81.5590,
},
{
  nome: "Backlot Express",
  regiao: "Echo Lake",
  tipo: "Conforto",
  acesso: "Ao lado da atração Star Tours",
  precoMedio: 18,
  destaque: "Hambúrgueres, sanduíches e porções em espaço amplo com temática de bastidores.",
  latitude: 28.3580,
  longitude: -81.5588,
},
{
  nome: "Dockside Diner",
  regiao: "Echo Lake",
  tipo: "Saudavel",
  acesso: "Beira do lago Echo Lake, no barco estilizado",
  precoMedio: 15,
  destaque: "Lanches rápidos e sanduíches frios; opções mais leves para uma pausa curta.",
  latitude: 28.3579,
  longitude: -81.5589,
},
{
  nome: "Epic Eats",
  regiao: "Echo Lake",
  tipo: "Economico",
  acesso: "Próximo ao teatro do Indiana Jones Epic Stunt Spectacular",
  precoMedio: 11,
  destaque: "Quiosque de sobremesas e snacks, prático entre atrações.",
  latitude: 28.3577,
  longitude: -81.5591,
},

// Grand Avenue (Disney's Hollywood Studios)
{
  nome: "Mama Melrose’s Ristorante Italiano",
  regiao: "Grand Avenue",
  tipo: "Classico",
  acesso: "No fim da Grand Avenue, próximo ao Muppet*Vision 3D",
  precoMedio: 34,
  destaque: "Massas e pratos italianos em ambiente aconchegante de trattoria.",
  latitude: 28.3575,
  longitude: -81.5602,
},
{
  nome: "BaseLine Tap House",
  regiao: "Grand Avenue",
  tipo: "Tematico",
  acesso: "Metade da Grand Avenue, esquina para o pátio",
  precoMedio: 20,
  destaque: "Bar californiano com chopes artesanais e petiscos como pretzel gigante.",
  latitude: 28.3576,
  longitude: -81.5600,
},
{
  nome: "PizzeRizzo",
  regiao: "Grand Avenue",
  tipo: "Conforto",
  acesso: "Ao lado do Muppet*Vision 3D",
  precoMedio: 16,
  destaque: "Pizzas e saladas em serviço rápido, com salão amplo e climatizado.",
  latitude: 28.3578,
  longitude: -81.5604,
},
{
  nome: "Grand Avenue Popcorn Cart",
  regiao: "Grand Avenue",
  tipo: "Economico",
  acesso: "Calçada principal da Grand Avenue",
  precoMedio: 9,
  destaque: "Carrinho de pipoca e bebidas geladas para um lanche rápido.",
  latitude: 28.3577,
  longitude: -81.5601,
},
{
  nome: "Muppets Courtyard Gelato Cart",
  regiao: "Grand Avenue",
  tipo: "Saudavel",
  acesso: "Pátio dos Muppets, ao lado da entrada do Muppet*Vision 3D",
  precoMedio: 12,
  destaque: "Opções leves como sorbets e garrafinhas de água; parada prática entre atrações.",
  latitude: 28.3579,
  longitude: -81.5605,
},

// Star Wars: Galaxy’s Edge (Disney's Hollywood Studios)
{
  nome: "Docking Bay 7 Food and Cargo",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Classico",
  acesso: "Setor central de Batuu, atrás da Millennium Falcon",
  precoMedio: 29,
  destaque: "Pratos inspirados em planetas da galáxia com apresentação imersiva.",
  latitude: 28.3584,
  longitude: -81.5615,
},
{
  nome: "Oga’s Cantina",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Tematico",
  acesso: "Ao lado do mercado Black Spire Outpost",
  precoMedio: 35,
  destaque: "Bar temático com coquetéis exclusivos e trilha do DJ R-3X.",
  latitude: 28.3585,
  longitude: -81.5616,
},
{
  nome: "Ronto Roasters",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Conforto",
  acesso: "Corredor do mercado, em frente ao Droid Depot",
  precoMedio: 14,
  destaque: "Wraps grelhados e carnes defumadas para comer em movimento.",
  latitude: 28.3586,
  longitude: -81.5614,
},
{
  nome: "Kat Saka’s Kettle",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Economico",
  acesso: "Mercado Black Spire Outpost",
  precoMedio: 9,
  destaque: "Pipocas doces tipo Outpost Mix e bebidas; parada rápida no mercado.",
  latitude: 28.3587,
  longitude: -81.5613,
},
{
  nome: "Milk Stand",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Saudavel",
  acesso: "Caminho entre o mercado e a Millennium Falcon",
  precoMedio: 8,
  destaque: "Leite azul e verde em versões geladas; opção leve e refrescante.",
  latitude: 28.3588,
  longitude: -81.5612,
},

// Toy Story Land (Disney's Hollywood Studios)
{
  nome: "Roundup Rodeo BBQ",
  regiao: "Toy Story Land",
  tipo: "Classico",
  acesso: "Entrada à direita após passar por Woody, perto da Slinky Dog Dash",
  precoMedio: 45,
  destaque: "Churrasco estilo família em restaurante temático de brinquedos.",
  latitude: 28.3590,
  longitude: -81.5620,
},
{
  nome: "Woody’s Lunch Box",
  regiao: "Toy Story Land",
  tipo: "Conforto",
  acesso: "Ao lado da atração Slinky Dog Dash",
  precoMedio: 19,
  destaque: "Grilled cheese, soup tomato e tartes; cardápio de lanches caprichados.",
  latitude: 28.3591,
  longitude: -81.5621,
},
{
  nome: "Joffrey’s Coffee & Tea Company – Toy Story Land",
  regiao: "Toy Story Land",
  tipo: "Tematico",
  acesso: "Próximo ao acesso para a área de Alien Swirling Saucers",
  precoMedio: 12,
  destaque: "Cafés, donuts e bebidas especiais com decoração temática.",
  latitude: 28.3592,
  longitude: -81.5622,
},
{
  nome: "Market by Toy Story Land (Snack Cart)",
  regiao: "Toy Story Land",
  tipo: "Economico",
  acesso: "Corredor central, próximo ao PhotoPass com Woody e Jessie",
  precoMedio: 10,
  destaque: "Carrinho de snacks com pretzels, pipoca e bebidas.",
  latitude: 28.3593,
  longitude: -81.5623,
},
{
  nome: "Ice Cream Cart – Toy Story Land",
  regiao: "Toy Story Land",
  tipo: "Saudavel",
  acesso: "Entre Alien Swirling Saucers e a saída para Animation Courtyard",
  precoMedio: 13,
  destaque: "Picolés, frutas embaladas e água gelada; opção leve e rápida.",
  latitude: 28.3594,
  longitude: -81.5624,
},

// Animation Courtyard (Disney's Hollywood Studios)
{
  nome: "Joffrey’s Coffee & Tea Company – Animation Courtyard",
  regiao: "Animation Courtyard",
  tipo: "Classico",
  acesso: "Perto da entrada do Disney Junior Dance Party",
  precoMedio: 12,
  destaque: "Cafés, chás e doces clássicos para começar o dia.",
  latitude: 28.3568,
  longitude: -81.5598,
},
{
  nome: "Market – Animation Courtyard (Snack Cart)",
  regiao: "Animation Courtyard",
  tipo: "Tematico",
  acesso: "Calçada principal do Animation Courtyard",
  precoMedio: 11,
  destaque: "Snacks temáticos e bebidas geladas em carrinho sazonal.",
  latitude: 28.3566,
  longitude: -81.5596,
},
{
  nome: "Cartoon Treats (Ice Cream Cart)",
  regiao: "Animation Courtyard",
  tipo: "Conforto",
  acesso: "Próximo ao Walt Disney Presents",
  precoMedio: 10,
  destaque: "Sorvetes e sundaes individuais para refrescar no calor.",
  latitude: 28.3565,
  longitude: -81.5595,
},
{
  nome: "Courtyard Popcorn Cart",
  regiao: "Animation Courtyard",
  tipo: "Economico",
  acesso: "Ao lado do Walt Disney Presents",
  precoMedio: 9,
  destaque: "Pipoca e refil de bebidas; parada rápida entre atrações.",
  latitude: 28.3567,
  longitude: -81.5597,
},
{
  nome: "Fresh Sketch Greens (Grab & Go)",
  regiao: "Animation Courtyard",
  tipo: "Saudavel",
  acesso: "Entre a loja Disney Junior e o Playhouse Disney",
  precoMedio: 14,
  destaque: "Frutas, wraps leves e snacks embalados.",
  latitude: 28.3564,
  longitude: -81.5594,
},

// Sunset Boulevard (Disney's Hollywood Studios)
{
  nome: "Rosie’s All-American Café",
  regiao: "Sunset Boulevard",
  tipo: "Classico",
  acesso: "Praça de alimentação antes da Rock ‘n’ Roller Coaster",
  precoMedio: 24,
  destaque: "Hambúrgueres, saladas e combos americanos em pátio aberto.",
  latitude: 28.3556,
  longitude: -81.5599,
},
{
  nome: "Fairfax Fare",
  regiao: "Sunset Boulevard",
  tipo: "Tematico",
  acesso: "Conjunto Sunset Ranch Market, lado esquerdo",
  precoMedio: 18,
  destaque: "Cardápio inspirado em sabores latinos e bowls variados.",
  latitude: 28.3557,
  longitude: -81.5598,
},
{
  nome: "Hollywood Scoops",
  regiao: "Sunset Boulevard",
  tipo: "Conforto",
  acesso: "Em frente à The Twilight Zone Tower of Terror",
  precoMedio: 13,
  destaque: "Sorvetes e sobremesas geladas em porções generosas.",
  latitude: 28.3555,
  longitude: -81.5600,
},
{
  nome: "Catalina Eddie’s",
  regiao: "Sunset Boulevard",
  tipo: "Economico",
  acesso: "Praça Sunset Ranch Market, lado direito",
  precoMedio: 12,
  destaque: "Fatias de pizza, saladas e bebidas em serviço rápido.",
  latitude: 28.3559,
  longitude: -81.5602,
},
{
  nome: "Anaheim Produce",
  regiao: "Sunset Boulevard",
  tipo: "Saudavel",
  acesso: "Calçada principal de Sunset Boulevard",
  precoMedio: 11,
  destaque: "Frutas, snacks leves e bebidas refrescantes.",
  latitude: 28.3558,
  longitude: -81.5601,
},

// Oasis (Disney's Animal Kingdom)
{
  nome: "Rainforest Café (Entrada do Parque)",
  regiao: "Oasis",
  tipo: "Tematico",
  acesso: "Na entrada principal do parque, antes dos portões",
  precoMedio: 37,
  destaque: "Ambiente de floresta tropical com cardápio variado e porções fartas.",
  latitude: 28.3598,
  longitude: -81.5912,
},
{
  nome: "The Feeding Ground (Snack Cart)",
  regiao: "Oasis",
  tipo: "Classico",
  acesso: "Caminho principal da Oasis, após os portões",
  precoMedio: 10,
  destaque: "Snacks tradicionais e bebidas para um começo rápido de dia.",
  latitude: 28.3597,
  longitude: -81.5911,
},
{
  nome: "Oasis Ice Cream Cart",
  regiao: "Oasis",
  tipo: "Conforto",
  acesso: "À esquerda do mapa do parque, após a entrada",
  precoMedio: 12,
  destaque: "Picolés, sorvetes e refrigerantes para se refrescar.",
  latitude: 28.3599,
  longitude: -81.5910,
},
{
  nome: "Oasis Fruit Market (Cart)",
  regiao: "Oasis",
  tipo: "Saudavel",
  acesso: "Corredor à direita, próximo à ponte para Discovery Island",
  precoMedio: 13,
  destaque: "Frutas frescas, wraps leves e água gelada.",
  latitude: 28.3596,
  longitude: -81.5913,
},
{
  nome: "Garden Gate Gifts Grab & Go",
  regiao: "Oasis",
  tipo: "Economico",
  acesso: "Ao lado da loja Garden Gate Gifts",
  precoMedio: 9,
  destaque: "Itens práticos para levar, como chips, cookies e bebidas.",
  latitude: 28.3595,
  longitude: -81.5914,
},

// Discovery Island (Disney's Animal Kingdom)
{
  nome: "Flame Tree Barbecue",
  regiao: "Discovery Island",
  tipo: "Classico",
  acesso: "Beira do lago, próximo à ponte para Asia",
  precoMedio: 26,
  destaque: "Carnes defumadas, porções bem servidas e pátios com vista.",
  latitude: 28.3608,
  longitude: -81.5902,
},
{
  nome: "Terra Treats",
  regiao: "Discovery Island",
  tipo: "Tematico",
  acesso: "Calçada principal rumo ao Tree of Life",
  precoMedio: 12,
  destaque: "Lanches sazonais e pizzas individuais com sabores rotativos.",
  latitude: 28.3614,
  longitude: -81.5905,
},
{
  nome: "Creature Comforts (Starbucks)",
  regiao: "Discovery Island",
  tipo: "Conforto",
  acesso: "Entre as lojas principais, caminho para Africa",
  precoMedio: 15,
  destaque: "Cafés, bolos e bebidas especiais em ambiente climatizado.",
  latitude: 28.3610,
  longitude: -81.5900,
},
{
  nome: "Pizzafari",
  regiao: "Discovery Island",
  tipo: "Economico",
  acesso: "Próximo ao caminho para Pandora – The World of Avatar",
  precoMedio: 14,
  destaque: "Pizzas individuais, saladas e áreas internas temáticas.",
  latitude: 28.3612,
  longitude: -81.5903,
},
{
  nome: "Isle of Java",
  regiao: "Discovery Island",
  tipo: "Saudavel",
  acesso: "Margem do lago, caminho para a ponte de Asia",
  precoMedio: 11,
  destaque: "Cafés e opções leves para levar, prática para o início do dia.",
  latitude: 28.3613,
  longitude: -81.5904,
},

// Pandora – The World of Avatar
{
  nome: "Satu’li Canteen",
  regiao: "Pandora",
  tipo: "Classico",
  acesso: "Ao lado da atração Avatar Flight of Passage",
  precoMedio: 30,
  destaque: "Bowls inspirados em Pandora com carnes, vegetais e batata-doce roxa servidos em tigelas artesanais.",
  latitude: 28.3595,
  longitude: -81.5886,
},
{
  nome: "Pongu Pongu",
  regiao: "Pandora",
  tipo: "Tematico",
  acesso: "Ao lado da entrada de Na’vi River Journey",
  precoMedio: 13,
  destaque: "Quiosque colorido com bebidas exóticas e o clássico rolinho doce Pongu Lumpia de abacaxi com cream cheese.",
  latitude: 28.3594,
  longitude: -81.5888,
},
{
  nome: "Windtraders Snacks",
  regiao: "Pandora",
  tipo: "Conforto",
  acesso: "Próximo à loja Windtraders, na saída de Flight of Passage",
  precoMedio: 15,
  destaque: "Lanches rápidos e doces temáticos da área; opção prática entre atrações.",
  latitude: 28.3596,
  longitude: -81.5887,
},
{
  nome: "Pongu Cooler Cart",
  regiao: "Pandora",
  tipo: "Economico",
  acesso: "Entre Pongu Pongu e a ponte de entrada de Pandora",
  precoMedio: 10,
  destaque: "Bebidas geladas, refrigerantes e águas; ótimo para refrescar antes das filas.",
  latitude: 28.3597,
  longitude: -81.5885,
},
{
  nome: "Na’vi Greens",
  regiao: "Pandora",
  tipo: "Saudavel",
  acesso: "Atrás do Satu’li Canteen, próximo ao jardim bio-luminescente",
  precoMedio: 14,
  destaque: "Saladas e bowls leves com proteínas magras e frutas tropicais; menu refrescante e nutritivo.",
  latitude: 28.3598,
  longitude: -81.5884,
},

// Africa
{
  nome: "Harambe Market",
  regiao: "Africa",
  tipo: "Classico",
  acesso: "Ao lado da entrada da atração Kilimanjaro Safaris",
  precoMedio: 24,
  destaque: "Estações ao ar livre com pratos africanos de rua, como linguiça grelhada com arroz picante.",
  latitude: 28.3588,
  longitude: -81.5932,
},
{
  nome: "Tusker House Restaurant",
  regiao: "Africa",
  tipo: "Tematico",
  acesso: "Próximo à Harambe Market e ao Safari",
  precoMedio: 46,
  destaque: "Buffet africano com personagens Disney em ambiente de mercado colonial.",
  latitude: 28.3590,
  longitude: -81.5930,
},
{
  nome: "Tamu Tamu Refreshments",
  regiao: "Africa",
  tipo: "Conforto",
  acesso: "Beco de Harambe, perto do Harambe Theatre",
  precoMedio: 14,
  destaque: "Sobremesas e snacks gelados como o Dole Whip e brownies tropicais.",
  latitude: 28.3591,
  longitude: -81.5929,
},
{
  nome: "Mahindi",
  regiao: "Africa",
  tipo: "Economico",
  acesso: "Ao lado da ponte que liga Africa à Asia",
  precoMedio: 10,
  destaque: "Carrinho de pipoca e bebidas; lanche rápido e tradicional do parque.",
  latitude: 28.3592,
  longitude: -81.5933,
},
{
  nome: "Harambe Fruit Market",
  regiao: "Africa",
  tipo: "Saudavel",
  acesso: "Em frente à saída da Kilimanjaro Safaris",
  precoMedio: 10,
  destaque: "Frutas frescas, wraps e sucos naturais; ótima opção saudável durante o calor.",
  latitude: 28.3589,
  longitude: -81.5931,
},

// Asia
{
  nome: "Yak & Yeti Restaurant",
  regiao: "Asia",
  tipo: "Classico",
  acesso: "Entre Kali River Rapids e Maharajah Jungle Trek",
  precoMedio: 32,
  destaque: "Culinária pan-asiática com serviço de mesa e ambiente temático com decoração detalhada.",
  latitude: 28.3580,
  longitude: -81.5915,
},
{
  nome: "Royal Anandapur Tea Company (Joffrey’s)",
  regiao: "Asia",
  tipo: "Tematico",
  acesso: "Na praça central de Anandapur, perto da ponte para Africa",
  precoMedio: 9,
  destaque: "Cafés, chás gelados e lattes especiais em um quiosque com charme oriental.",
  latitude: 28.3582,
  longitude: -81.5917,
},
{
  nome: "Anandapur Ice Cream Truck",
  regiao: "Asia",
  tipo: "Conforto",
  acesso: "Em frente à atração Expedition Everest",
  precoMedio: 9,
  destaque: "Caminhão retrô servindo sorvetes e sundaes refrescantes; ideal no calor.",
  latitude: 28.3579,
  longitude: -81.5916,
},
{
  nome: "Mr. Kamal’s",
  regiao: "Asia",
  tipo: "Economico",
  acesso: "Caminho entre Asia e Africa, próximo ao teatro UP! A Great Bird Adventure",
  precoMedio: 11,
  destaque: "Batatas fritas temperadas e wraps com molhos exóticos; parada rápida entre áreas.",
  latitude: 28.3578,
  longitude: -81.5913,
},
{
  nome: "Yak & Yeti Local Food Cafes",
  regiao: "Asia",
  tipo: "Saudavel",
  acesso: "Ao lado do Yak & Yeti Restaurant",
  precoMedio: 15,
  destaque: "Quick service pan-asiático com bowls e saladas; pratos equilibrados e bem temperados.",
  latitude: 28.3581,
  longitude: -81.5914,
},

// DinoLand U.S.A.
{
  nome: "Restaurantosaurus",
  regiao: "DinoLand U.S.A.",
  tipo: "Classico",
  acesso: "Ao lado da atração DINOSAUR",
  precoMedio: 22,
  destaque: "Hambúrgueres e batatas waffle em restaurante divertido com tema de paleontologia.",
  latitude: 28.3570,
  longitude: -81.5890,
},
{
  nome: "Restaurantosaurus Lounge",
  regiao: "DinoLand U.S.A.",
  tipo: "Tematico",
  acesso: "Anexo ao Restaurantosaurus (funcionamento sazonal)",
  precoMedio: 18,
  destaque: "Drinks e petiscos em lounge aconchegante com decoração do Dino Institute.",
  latitude: 28.3571,
  longitude: -81.5891,
},
{
  nome: "Trilo-Bites",
  regiao: "DinoLand U.S.A.",
  tipo: "Conforto",
  acesso: "Perto da entrada da ponte de Discovery Island",
  precoMedio: 10,
  destaque: "Snacks fritos e bebidas geladas, incluindo o famoso Buffalo Chicken Chips.",
  latitude: 28.3569,
  longitude: -81.5889,
},
{
  nome: "Dino-Bite Snacks",
  regiao: "DinoLand U.S.A.",
  tipo: "Economico",
  acesso: "Próximo à loja Chester & Hester’s Dinosaur Treasures",
  precoMedio: 9,
  destaque: "Sorvetes e cookies recheados; ótimo para sobremesa após o almoço.",
  latitude: 28.3568,
  longitude: -81.5888,
},
{
  nome: "The Dino Diner",
  regiao: "DinoLand U.S.A.",
  tipo: "Saudavel",
  acesso: "Ao lado do Fossil Fun Games",
  precoMedio: 15,
  destaque: "Wraps e snacks rápidos em carrinho retrô vermelho; opção leve e prática.",
  latitude: 28.3567,
  longitude: -81.5887,
},


  ];