export const  almocosDisney = [
// MainStreet
{
  nome: "Tony’s Town Square Restaurant",
  regiao: "MainStreet",
  tipo: ["Classico", "Americano"],
    acesso: "Logo após a entrada principal do parque, ao lado do Town Square Theater",
  precoMedio: 36,
  destaque: "Culinária italiana clássica com ambiente elegante. Não deixe de experimentar o espaguete com almôndegas estilo 'A Dama e o Vagabundo'.",
  latitude: 28.4184,
  longitude: -81.5819,
},
{
  nome: "Main Street Bakery",
  regiao: "MainStreet",
  tipo: "Tematico",
  acesso: "Ao longo da Main Street, próximo à loja Emporium",
  precoMedio: 14,
  destaque: "Doces, cafés e lanches em estilo Starbucks. Não deixe de pedir o cinnamon roll quente com cobertura de açúcar.",
  latitude: 28.4186,
  longitude: -81.5821,
},
{
  nome: "Casey’s Corner",
  regiao: "MainStreet",
  tipo: "Conforto",
  acesso: "No fim da Main Street, virando à esquerda antes do castelo",
  precoMedio: 17,
  destaque: "Cachorros-quentes clássicos com batatas fritas. Não deixe de experimentar o hot dog com chili e queijo cheddar.",
  latitude: 28.4187,
  longitude: -81.5824,
},
{
  nome: "Plaza Ice Cream Parlor",
  regiao: "MainStreet",
  tipo: "Economico",
  acesso: "Ao lado do Casey’s Corner, com vista para o castelo",
  precoMedio: 10,
  destaque: "Sorvetes artesanais e milkshakes variados. Não deixe de provar o sundae com cookie e calda quente.",
  latitude: 28.4188,
  longitude: -81.5825,
},
{
  nome: "The Plaza Restaurant",
  regiao: "MainStreet",
  tipo: "Saudavel",
  acesso: "Ao lado do Plaza Ice Cream, em frente ao hub central",
  precoMedio: 20,
  destaque: "Opções leves como saladas e pratos vegetarianos. Não deixe de experimentar a salada com morangos e nozes caramelizadas.",
  latitude: 28.4189,
  longitude: -81.5826,
},

// Adventureland
{
  nome: "Skipper Canteen",
  regiao: "Adventureland",
  tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atração Jungle Cruise",
  precoMedio: 35,
  destaque: "Culinária internacional em ambiente de exploração. Não deixe de experimentar o frango ao curry tailandês.",
  latitude: 28.4181,
  longitude: -81.5843,
},
{
  nome: "Tortuga Tavern",
  regiao: "Adventureland",
  tipo: "Tematico",
  acesso: "Em frente à atração Pirates of the Caribbean",
  precoMedio: 19,
  destaque: "Pratos rápidos com inspiração caribenha. Não deixe de pedir os nachos com carne e guacamole.",
  latitude: 28.4180,
  longitude: -81.5841,
},
{
  nome: "Sunshine Tree Terrace",
  regiao: "Adventureland",
  tipo: "Conforto",
  acesso: "Ao lado da atração The Magic Carpets of Aladdin",
  precoMedio: 11,
  destaque: "Sobremesas geladas e sucos tropicais. Não deixe de experimentar o sorvete Dole Whip de laranja.",
  latitude: 28.4178,
  longitude: -81.5839,
},
{
  nome: "Aloha Isle",
  regiao: "Adventureland",
  tipo: "Economico",
  acesso: "Em frente à Tiki Room",
  precoMedio: 9,
  destaque: "Clássico ponto de Dole Whip. Não deixe de provar a versão de abacaxi com suco natural.",
  latitude: 28.4177,
  longitude: -81.5840,
},
{
  nome: "Tiki Snacks",
  regiao: "Adventureland",
  tipo: "Saudavel",
  acesso: "Ao lado do Aloha Isle, próximo à ponte de Frontierland",
  precoMedio: 13,
  destaque: "Snacks leves como frutas frescas e wraps frios. Não deixe de experimentar a salada de manga com pepino.",
  latitude: 28.4176,
  longitude: -81.5838,
},

// Frontierland
{
  nome: "Pecos Bill Tall Tale Inn and Cafe",
  regiao: "Frontierland",
  tipo: ["Classico", "Americano"],
    acesso: "Ao lado da Splash Mountain",
  precoMedio: 25,
  destaque: "Culinária Tex-Mex em estilo rústico. Não deixe de experimentar o burrito de carne com arroz temperado.",
  latitude: 28.4174,
  longitude: -81.5853,
},
{
  nome: "Westward Ho",
  regiao: "Frontierland",
  tipo: "Tematico",
  acesso: "Em frente à Country Bear Jamboree",
  precoMedio: 14,
  destaque: "Snacks rápidos com tema de velho oeste. Não deixe de provar o milho grelhado com manteiga.",
  latitude: 28.4175,
  longitude: -81.5851,
},
{
  nome: "Frontier Snacks",
  regiao: "Frontierland",
  tipo: "Conforto",
  acesso: "Perto da entrada da Tom Sawyer Island",
  precoMedio: 16,
  destaque: "Churros e pretzels tradicionais. Não deixe de experimentar o churro com recheio de doce de leite.",
  latitude: 28.4173,
  longitude: -81.5850,
},
{
  nome: "Country Cookin’",
  regiao: "Frontierland",
  tipo: "Economico",
  acesso: "Nos fundos do Pecos Bill, próximo ao bebedouro",
  precoMedio: 12,
  destaque: "Frango frito e acompanhamentos típicos. Não deixe de experimentar a coxa com molho barbecue.",
  latitude: 28.4172,
  longitude: -81.5849,
},
{
  nome: "Prairie Greens",
  regiao: "Frontierland",
  tipo: "Saudavel",
  acesso: "Próximo ao trilho do trem de Frontierland",
  precoMedio: 18,
  destaque: "Saladas e wraps com ingredientes frescos. Não deixe de provar o wrap de peru com rúcula e tomate seco.",
  latitude: 28.4171,
  longitude: -81.5848,
},

// LibertySquare
{
  nome: "Liberty Tree Tavern",
  regiao: "LibertySquare",
  tipo: ["Classico", "Americano"],
    acesso: "2 min a pé da Haunted Mansion",
  precoMedio: 39,
  destaque: "Pratos coloniais servidos à vontade. Não deixe de experimentar o assado de carne com molho caseiro.",
  latitude: 28.4190,
  longitude: -81.5834,
},
{
  nome: "Liberty Comfort Kitchen",
  regiao: "LibertySquare",
  tipo: "Conforto",
  acesso: "Próximo ao Hall of Presidents, ao lado do Columbia Harbour House",
  precoMedio: 19,
  destaque: "Pratos reconfortantes como meatloaf americano, purê de batata e legumes. Não deixe de experimentar o clássico mac and cheese com bacon crocante.",
  latitude: 28.4197,
  longitude: -81.5832,
},

{
  nome: "The Diamond Horseshoe",
  regiao: "LibertySquare",
  tipo: "Tematico",
  acesso: "Próximo à entrada da Liberty Square",
  precoMedio: 42,
  destaque: "Ambiente de salão do velho oeste com carnes grelhadas. Não deixe de pedir o brisket defumado com milho.",
  latitude: 28.4191,
  longitude: -81.5838,
},

{
  nome: "Liberty Snacks",
  regiao: "LibertySquare",
  tipo: "Economico",
  acesso: "Próximo ao Liberty Square Riverboat",
  precoMedio: 12,
  destaque: "Snacks rápidos e porções econômicas. Não deixe de comer o pretzel recheado com queijo.",
  latitude: 28.4193,
  longitude: -81.5831,
},
{
  nome: "Revolution Greens",
  regiao: "LibertySquare",
  tipo: "Saudavel",
  acesso: "Atrás do Liberty Tree Tavern",
  precoMedio: 19,
  destaque: "Saladas frescas e bowls naturais. Não deixe de experimentar a salada de grão-de-bico com azeite cítrico.",
  latitude: 28.4192,
  longitude: -81.5835,
},

// Fantasyland
{
  nome: "The Royal Table Lunch",
  regiao: "Fantasyland",
  tipo: "Classico",
  acesso: "Dentro do Castelo da Cinderela",
  precoMedio: 38,
  destaque: "Almoço com pratos americanos em ambiente real. Não deixe de experimentar o frango grelhado com legumes e molho de ervas.",
  latitude: 28.4194,
  longitude: -81.5812,
},
{
  nome: "Be Our Guest Restaurant",
  regiao: "Fantasyland",
  tipo: "Tematico",
  acesso: "2 min a pé do Seven Dwarfs Mine Train",
  precoMedio: 48,
  destaque: "Ambiente inspirado no castelo da Fera. Não deixe de pedir o filet mignon com purê trufado.",
  latitude: 28.4203,
  longitude: -81.5805,
},
{
  nome: "Gaston’s Tavern Lunch",
  regiao: "Fantasyland",
  tipo: "Conforto",
  acesso: "2 min a pé de Under the Sea – Journey of The Little Mermaid",
  precoMedio: 21,
  destaque: "Sanduíches e sopas em ambiente rústico. Não deixe de experimentar o sanduíche de peru com queijo suíço.",
  latitude: 28.4211,
  longitude: -81.5809,
},
{
  nome: "Friar’s Nook",
  regiao: "Fantasyland",
  tipo: "Economico",
  acesso: "1 min a pé do Prince Charming Regal Carrousel",
  precoMedio: 13,
  destaque: "Mac and cheese com diversas coberturas. Não deixe de comer o mac and cheese com bacon crocante.",
  latitude: 28.4198,
  longitude: -81.5817,
},
{
  nome: "Pinocchio Village Haus",
  regiao: "Fantasyland",
  tipo: "Saudavel",
  acesso: "Ao lado do It’s a Small World",
  precoMedio: 18,
  destaque: "Flatbreads e saladas leves. Não deixe de experimentar o flatbread vegetariano com legumes grelhados.",
  latitude: 28.4195,
  longitude: -81.5820,
},

// Tomorrowland
{
  nome: "Cosmic Ray’s Starlight Café",
  regiao: "Tomorrowland",
  tipo: ["Classico", "Americano"],
    acesso: "Em frente à atração Buzz Lightyear",
  precoMedio: 24,
  destaque: "Lanches clássicos com show alienígena. Não deixe de experimentar o hambúrguer duplo com onion rings.",
  latitude: 28.4200,
  longitude: -81.5792,
},
{
  nome: "The Lunching Pad",
  regiao: "Tomorrowland",
  tipo: "Tematico",
  acesso: "Na base da atração Astro Orbiter",
  precoMedio: 16,
  destaque: "Snacks rápidos com tema espacial. Não deixe de pedir o pretzel recheado com cream cheese de jalapeño.",
  latitude: 28.4201,
  longitude: -81.5793,
},
{
  nome: "Tomorrow Bites",
  regiao: "Tomorrowland",
  tipo: "Conforto",
  acesso: "Ao lado da entrada da Space Mountain",
  precoMedio: 14,
  destaque: "Lanches e batatas fritas para todos os gostos. Não deixe de provar os nuggets com batata smile.",
  latitude: 28.4202,
  longitude: -81.5794,
},
{
  nome: "Galaxy Snacks",
  regiao: "Tomorrowland",
  tipo: "Economico",
  acesso: "Atrás do Tomorrowland Speedway",
  precoMedio: 11,
  destaque: "Snacks e bebidas rápidas. Não deixe de experimentar o wrap de queijo com tomate seco.",
  latitude: 28.4203,
  longitude: -81.5795,
},
{
  nome: "Orbital Greens",
  regiao: "Tomorrowland",
  tipo: "Saudavel",
  acesso: "Ao lado do Space Ranger Spin",
  precoMedio: 17,
  destaque: "Bowls saudáveis e sucos naturais. Não deixe de pedir o bowl de quinoa com abacate e frango grelhado.",
  latitude: 28.4204,
  longitude: -81.5796,
},
// World Showcase
{
  nome: "Les Chefs de France",
  regiao: "World Showcase",
  tipo: ["Classico", "Americano"],
    acesso: "Pavilhão da França – em frente à entrada da atração Remy’s Ratatouille Adventure",
  precoMedio: 39,
  destaque: "Culinária francesa tradicional com pratos refinados. Não deixe de experimentar o entrecôte grelhado com batatas gratinadas.",
  latitude: 28.3705,
  longitude: -81.5502,
},
{
  nome: "Teppan Edo",
  regiao: "World Showcase",
  tipo: "Tematico",
  acesso: "Pavilhão do Japão – segundo andar, acima da loja Mitsukoshi",
  precoMedio: 45,
  destaque: "Chapas japonesas com preparo ao vivo na mesa. Não deixe de pedir o filet mignon grelhado com legumes frescos.",
  latitude: 28.3701,
  longitude: -81.5489,
},
{
  nome: "Via Napoli Ristorante e Pizzeria",
  regiao: "World Showcase",
  tipo: "Conforto",
  acesso: "Pavilhão da Itália – nos fundos, próximo à fonte central",
  precoMedio: 28,
  destaque: "Pizzas autênticas assadas em forno à lenha. Não deixe de experimentar a pizza Margherita tradicional.",
  latitude: 28.3704,
  longitude: -81.5513,
},
{
  nome: "La Cantina de San Angel",
  regiao: "World Showcase",
  tipo: "Economico",
  acesso: "Pavilhão do México – na beira do lago, ao lado da pirâmide",
  precoMedio: 15,
  destaque: "Tacos e nachos em estilo fast casual. Não deixe de experimentar o combo de tacos com guacamole.",
  latitude: 28.3711,
  longitude: -81.5475,
},
{
  nome: "Tangierine Café",
  regiao: "World Showcase",
  tipo: "Saudavel",
  acesso: "Pavilhão do Marrocos – em frente à entrada da Fez House",
  precoMedio: 19,
  destaque: "Pratos mediterrâneos frescos e leves. Não deixe de provar o couscous com legumes grelhados e molho de limão.",
  latitude: 28.3708,
  longitude: -81.5493,
},

// World Discovery
{
  nome: "Space 220 Restaurant",
  regiao: "World Discovery",
  tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atração Mission: SPACE – acesso com elevador espacial simulado",
  precoMedio: 55,
  destaque: "Experiência gastronômica em ambiente de estação espacial. Não deixe de experimentar o frango grelhado com batatas ao alho.",
  latitude: 28.3735,
  longitude: -81.5480,
},
{
  nome: "Connections Eatery",
  regiao: "World Discovery",
  tipo: "Tematico",
  acesso: "Em frente à Guardians of the Galaxy: Cosmic Rewind",
  precoMedio: 26,
  destaque: "Ambiente moderno com comidas internacionais. Não deixe de pedir o hambúrguer gourmet com molho especial da casa.",
  latitude: 28.3742,
  longitude: -81.5485,
},
{
  nome: "Test Track Snacks",
  regiao: "World Discovery",
  tipo: "Conforto",
  acesso: "Ao lado da saída da atração Test Track",
  precoMedio: 14,
  destaque: "Snacks rápidos com bebidas energéticas. Não deixe de experimentar o wrap de frango picante com cheddar.",
  latitude: 28.3751,
  longitude: -81.5483,
},
{
  nome: "Launch Fuel Bites",
  regiao: "World Discovery",
  tipo: "Economico",
  acesso: "Próximo à entrada do Mission: SPACE",
  precoMedio: 11,
  destaque: "Snacks práticos e sanduíches embalados. Não deixe de experimentar o sanduíche frio com pasta de atum.",
  latitude: 28.3733,
  longitude: -81.5478,
},
{
  nome: "Nova Greens",
  regiao: "World Discovery",
  tipo: "Saudavel",
  acesso: "Área lateral da Cosmic Rewind",
  precoMedio: 17,
  destaque: "Saladas e bowls com proteína magra. Não deixe de provar o bowl de salmão com arroz de couve-flor.",
  latitude: 28.3748,
  longitude: -81.5477,
},

// World Celebration
{
  nome: "Connections Café",
  regiao: "World Celebration",
  tipo: ["Classico", "Americano"],
    acesso: "Próximo ao Creations Shop, centro do parque",
  precoMedio: 22,
  destaque: "Pratos variados em espaço moderno e amplo. Não deixe de experimentar o sanduíche de frango grelhado com pesto.",
  latitude: 28.3741,
  longitude: -81.5487,
},
{
  nome: "EPCOT Brew House",
  regiao: "World Celebration",
  tipo: "Tematico",
  acesso: "Ao lado do Connections Café",
  precoMedio: 20,
  destaque: "Cervejas artesanais e petiscos de pub. Não deixe de pedir o combo de mini hambúrgueres com molho barbecue.",
  latitude: 28.3743,
  longitude: -81.5488,
},
{
  nome: "Garden Snacks",
  regiao: "World Celebration",
  tipo: "Conforto",
  acesso: "Em frente ao centro interativo Dreamers Point",
  precoMedio: 13,
  destaque: "Snacks e sobremesas geladas. Não deixe de provar o cookie recheado com sorvete de baunilha.",
  latitude: 28.3745,
  longitude: -81.5486,
},
{
  nome: "Central Eats",
  regiao: "World Celebration",
  tipo: "Economico",
  acesso: "Corredor central, perto da entrada do World Showcase",
  precoMedio: 10,
  destaque: "Opções rápidas e econômicas. Não deixe de experimentar o hot dog com molho de queijo cheddar.",
  latitude: 28.3740,
  longitude: -81.5489,
},
{
  nome: "Fresh Start Salads",
  regiao: "World Celebration",
  tipo: "Saudavel",
  acesso: "Ao lado da área do Creations Shop",
  precoMedio: 16,
  destaque: "Saladas frescas com proteínas opcionais. Não deixe de provar a salada de frango com molho cítrico.",
  latitude: 28.3746,
  longitude: -81.5484,
},

// World Nature
{
  nome: "The Land Grill",
  regiao: "World Nature",
  tipo: ["Classico", "Americano"],
    acesso: "Dentro do pavilhão The Land – andar inferior",
  precoMedio: 30,
  destaque: "Pratos variados com ingredientes frescos da própria estufa. Não deixe de experimentar o frango assado com legumes do Living with the Land.",
  latitude: 28.3724,
  longitude: -81.5472,
},
{
  nome: "Coral Reef Restaurant",
  regiao: "World Nature",
  tipo: "Tematico",
  acesso: "Ao lado da atração The Seas with Nemo & Friends",
  precoMedio: 42,
  destaque: "Ambiente subaquático com vista para aquário gigante. Não deixe de pedir o filé de salmão grelhado com risoto de limão.",
  latitude: 28.3720,
  longitude: -81.5469,
},
{
  nome: "Nature Eats",
  regiao: "World Nature",
  tipo: "Conforto",
  acesso: "Saída do pavilhão The Land",
  precoMedio: 18,
  destaque: "Lanches reconfortantes e sobremesas frutadas. Não deixe de experimentar a tortinha de maçã com canela.",
  latitude: 28.3726,
  longitude: -81.5470,
},
{
  nome: "Harvest Snacks",
  regiao: "World Nature",
  tipo: "Economico",
  acesso: "Entre The Land e The Seas",
  precoMedio: 12,
  destaque: "Snacks naturais e sucos prensados. Não deixe de experimentar o wrap de cenoura com hummus.",
  latitude: 28.3725,
  longitude: -81.5471,
},
{
  nome: "Green Bowl Express",
  regiao: "World Nature",
  tipo: "Saudavel",
  acesso: "Entrada do pavilhão The Land",
  precoMedio: 17,
  destaque: "Bowls veganos e sucos naturais. Não deixe de provar o bowl de quinoa com manga e rúcula.",
  latitude: 28.3723,
  longitude: -81.5473,
},
// Hollywood Boulevard
{
  nome: "The Trolley Car Café",
  regiao: "Hollywood Boulevard",
  tipo: "Economico",
  acesso: "Ao lado da entrada principal, perto da loja Mickey’s of Hollywood",
  precoMedio: 12,
  destaque: "Cafés especiais e doces rápidos. Não deixe de experimentar o carrot cake cookie recheado.",
  latitude: 28.3571,
  longitude: -81.5582,
},
{
  nome: "Hollywood & Vine",
  regiao: "Hollywood Boulevard",
  tipo: ["Classico", "Americano"],
    acesso: "Próximo ao centro da praça principal",
  precoMedio: 42,
  destaque: "Buffet com culinária americana tradicional. Não deixe de experimentar o assado de carne com purê e legumes.",
  latitude: 28.3574,
  longitude: -81.5581,
},
{
  nome: "Studio Stars Cafe",
  regiao: "Hollywood Boulevard",
  tipo: "Tematico",
  acesso: "Próximo ao Hollywood & Vine, com decoração dos anos dourados de Hollywood",
  precoMedio: 19,
  destaque: "Pratos temáticos homenageando astros do cinema. Não deixe de experimentar o burger Golden Age.",
  latitude: 28.3572,
  longitude: -81.5583,
},
{
  nome: "Boulevard Comforts",
  regiao: "Hollywood Boulevard",
  tipo: "Conforto",
  acesso: "Ao lado da loja Mickey’s of Hollywood",
  precoMedio: 14,
  destaque: "Comida caseira estilo americano. Não deixe de experimentar o ensopado de carne com pão de alho.",
  latitude: 28.3573,
  longitude: -81.5584,
},
{
  nome: "Hollywood Greens",
  regiao: "Hollywood Boulevard",
  tipo: "Saudavel",
  acesso: "Atrás do Hollywood & Vine",
  precoMedio: 15,
  destaque: "Wraps, saladas e bowls saudáveis para uma refeição leve. Não deixe de provar o wrap de frango Caesar.",
  latitude: 28.3574,
  longitude: -81.5585,
},


// Echo Lake
{
  nome: "50's Prime Time Café",
  regiao: "Echo Lake",
  tipo: "Tematico",
  acesso: "Atrás do Echo Lake, perto do Indiana Jones Epic Stunt Spectacular",
  precoMedio: 37,
  destaque: "Restaurante retrô com clima dos anos 50. Não deixe de pedir o frango frito caseiro com purê de batata.",
  latitude: 28.3578,
  longitude: -81.5590,
},
{
  nome: "Lake Quick Bites",
  regiao: "Echo Lake",
  tipo: "Economico",
  acesso: "Próximo ao Indiana Jones Epic Stunt Spectacular",
  precoMedio: 11,
  destaque: "Sanduíches rápidos e snacks acessíveis. Não deixe de experimentar o sanduíche de peito de peru com chips.",
  latitude: 28.3577,
  longitude: -81.5589,
},

{
  nome: "Backlot Express",
  regiao: "Echo Lake",
  tipo: "Conforto",
  acesso: "Ao lado da atração Star Tours",
  precoMedio: 18,
  destaque: "Sanduíches e hambúrgueres rápidos com espaço temático. Não deixe de experimentar o cheeseburger com molho barbecue.",
  latitude: 28.3580,
  longitude: -81.5588,
},
{
  nome: "Echo Snacks",
  regiao: "Echo Lake",
  tipo: "Saudavel",
  acesso: "Em frente ao Echo Lake, ao lado do Lago",
  precoMedio: 14,
  destaque: "Frutas frescas, wraps e smoothies. Não deixe de provar o wrap de frango com espinafre.",
  latitude: 28.3581,
  longitude: -81.5591,
},
{
  nome: "Echo Diner",
  regiao: "Echo Lake",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente à entrada da atração Indiana Jones Epic Stunt Spectacular",
  precoMedio: 22,
  destaque: "Clássicos americanos como hambúrguer, cheeseburger, onion rings e milkshake. Não deixe de experimentar o cheeseburger artesanal com batata frita.",
  latitude: 28.3577,
  longitude: -81.5592,
},

// Grand Avenue
{
  nome: "Mama Melrose’s Ristorante Italiano",
  regiao: "Grand Avenue",
  tipo: ["Classico", "Americano"],
    acesso: "No fim da Grand Avenue, próximo à atração Muppet*Vision 3D",
  precoMedio: 34,
  destaque: "Comida italiana clássica em ambiente aconchegante. Não deixe de experimentar o penne com molho quatro queijos.",
  latitude: 28.3575,
  longitude: -81.5602,
},
{
  nome: "Muppet Theatre Tavern",
  regiao: "Grand Avenue",
  tipo: "Tematico",
  acesso: "Ao lado do PizzeRizzo, ambiente inspirado nos Muppets",
  precoMedio: 18,
  destaque: "Pratos temáticos com apresentações teatrais dos Muppets. Não deixe de experimentar o sanduíche Swedish Chef.",
  latitude: 28.3578,
  longitude: -81.5604,
},
{
  nome: "Backlot Comfort",
  regiao: "Grand Avenue",
  tipo: "Conforto",
  acesso: "Perto da saída do Muppet*Vision 3D",
  precoMedio: 15,
  destaque: "Comidas confortáveis, como macarrão com queijo e mini almôndegas. Não deixe de experimentar a sopa de tomate artesanal.",
  latitude: 28.3579,
  longitude: -81.5605,
},
{
  nome: "Green Stage Bowls",
  regiao: "Grand Avenue",
  tipo: "Saudavel",
  acesso: "Atrás do Muppet Courtyard",
  precoMedio: 14,
  destaque: "Bowls saudáveis com legumes frescos e proteína leve. Não deixe de provar o bowl de frango grelhado com legumes.",
  latitude: 28.3580,
  longitude: -81.5606,
},

{
  nome: "Rizzo Snacks",
  regiao: "Grand Avenue",
  tipo: "Economico",
  acesso: "Atrás do PizzeRizzo",
  precoMedio: 10,
  destaque: "Snacks rápidos como pretzels e cookies. Não deixe de experimentar o pretzel recheado de cheddar.",
  latitude: 28.3577,
  longitude: -81.5601,
},

// Star Wars: Galaxy’s Edge
{
  nome: "Docking Bay 7 Food and Cargo",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: ["Classico", "Americano"],
    acesso: "Atrás da Millennium Falcon",
  precoMedio: 29,
  destaque: "Pratos exóticos inspirados na galáxia Star Wars. Não deixe de experimentar o frango grelhado de Endor com arroz cítrico.",
  latitude: 28.3584,
  longitude: -81.5615,
},
{
  nome: "Oga’s Cantina",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Tematico",
  acesso: "Ao lado do mercado Black Spire Outpost",
  precoMedio: 35,
  destaque: "Bar temático com coquetéis especiais. Não deixe de pedir o Fuzzy Tauntaun com espuma vibrante.",
  latitude: 28.3585,
  longitude: -81.5616,
},
{
  nome: "Ronto Roasters",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Conforto",
  acesso: "Em frente à loja Droid Depot",
  precoMedio: 14,
  destaque: "Sanduíches grelhados com carne defumada. Não deixe de experimentar o Ronto Wrap clássico.",
  latitude: 28.3586,
  longitude: -81.5614,
},
{
  nome: "Black Spire Outpost Snacks",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Economico",
  acesso: "Mercado Black Spire Outpost",
  precoMedio: 12,
  destaque: "Snacks galácticos rápidos e acessíveis. Não deixe de experimentar o Batuu Popcorn Mix.",
  latitude: 28.3587,
  longitude: -81.5613,
},
{
  nome: "Star Wars Greens",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Saudavel",
  acesso: "Atrás da Millennium Falcon",
  precoMedio: 15,
  destaque: "Saladas e bowls de uma galáxia distante. Não deixe de experimentar a salada de algas de Endor.",
  latitude: 28.3588,
  longitude: -81.5612,
},


// Toy Story Land
{
  nome: "Woody’s Lunch Box",
  regiao: "Toy Story Land",
  tipo: "Conforto",
  acesso: "Ao lado da atração Slinky Dog Dash",
  precoMedio: 19,
  destaque: "Pratos inspirados em lanches infantis. Não deixe de experimentar o grilled cheese com sopa de tomate.",
  latitude: 28.3591,
  longitude: -81.5621,
},
{
  nome: "Toy Story Grill",
  regiao: "Toy Story Land",
  tipo: ["Classico", "Americano"],
  acesso: "Próximo ao Woody’s Lunch Box",
  precoMedio: 20,
  destaque: "Lanches clássicos e grelhados para toda família. Não deixe de experimentar o cheeseburger do Woody.",
  latitude: 28.3594,
  longitude: -81.5624,
},
{
  nome: "Andy's Diner",
  regiao: "Toy Story Land",
  tipo: "Tematico",
  acesso: "Entre as atrações Alien Swirling Saucers e Slinky Dog Dash",
  precoMedio: 18,
  destaque: "Refeições temáticas inspiradas nos brinquedos de Andy. Não deixe de provar o macarrão ao molho de queijo derretido.",
  latitude: 28.3595,
  longitude: -81.5625,
},

{
  nome: "Toy Box Treats",
  regiao: "Toy Story Land",
  tipo: "Economico",
  acesso: "Perto do Alien Swirling Saucers",
  precoMedio: 11,
  destaque: "Doces coloridos e bebidas refrescantes. Não deixe de provar o sundae de morango com chantilly.",
  latitude: 28.3592,
  longitude: -81.5622,
},
{
  nome: "Green Army Snacks",
  regiao: "Toy Story Land",
  tipo: "Saudavel",
  acesso: "Atrás da parada do Green Army Patrol",
  precoMedio: 13,
  destaque: "Snacks naturais e frutas embaladas. Não deixe de experimentar o mix de castanhas e frutas secas.",
  latitude: 28.3593,
  longitude: -81.5623,
},

// Animation Courtyard
{
  nome: "Animators Café",
  regiao: "Animation Courtyard",
  tipo: ["Classico", "Americano"],
    acesso: "Perto da entrada do Disney Junior Dance Party",
  precoMedio: 26,
  destaque: "Pratos clássicos em ambiente inspirado em animações. Não deixe de experimentar o frango com purê e legumes grelhados.",
  latitude: 28.3568,
  longitude: -81.5598,
},
{
  nome: "Animation Diner",
  regiao: "Animation Courtyard",
  tipo: "Tematico",
  acesso: "Ao lado do Animators Café, ambiente decorado com desenhos clássicos Disney",
  precoMedio: 23,
  destaque: "Pratos temáticos inspirados nos filmes da Disney. Não deixe de experimentar o Mickey Waffle Sandwich.",
  latitude: 28.3566,
  longitude: -81.5596,
},
{
  nome: "Cartoon Comforts",
  regiao: "Animation Courtyard",
  tipo: "Conforto",
  acesso: "Próximo ao Walt Disney Presents",
  precoMedio: 16,
  destaque: "Comidas reconfortantes para toda a família. Não deixe de experimentar o purê de batata com frango empanado.",
  latitude: 28.3565,
  longitude: -81.5595,
},
{
  nome: "Fresh Sketch Greens",
  regiao: "Animation Courtyard",
  tipo: "Saudavel",
  acesso: "Entre a loja Disney Junior e o Playhouse Disney",
  precoMedio: 15,
  destaque: "Saladas frescas, wraps leves e bowls coloridos. Não deixe de experimentar o bowl vegano de quinoa com manga.",
  latitude: 28.3564,
  longitude: -81.5594,
},

{
  nome: "Courtyard Snacks",
  regiao: "Animation Courtyard",
  tipo: "Economico",
  acesso: "Ao lado do Walt Disney Presents",
  precoMedio: 9,
  destaque: "Snacks rápidos e bebidas. Não deixe de provar o cookie recheado de Nutella.",
  latitude: 28.3567,
  longitude: -81.5597,
},

// Sunset Boulevard
{
  nome: "Hollywood Scoops",
  regiao: "Sunset Boulevard",
  tipo: "Conforto",
  acesso: "Em frente à The Twilight Zone Tower of Terror",
  precoMedio: 13,
  destaque: "Sorvetes artesanais e sobremesas geladas. Não deixe de experimentar o sundae com brownie quente.",
  latitude: 28.3555,
  longitude: -81.5600,
},
{
  nome: "Twilight Snacks",
  regiao: "Sunset Boulevard",
  tipo: "Tematico",
  acesso: "Próximo à Tower of Terror, decoração inspirada na era dourada de Hollywood",
  precoMedio: 19,
  destaque: "Pratos temáticos de terror e mistério. Não deixe de experimentar o sanduíche 'Sombra da Noite'.",
  latitude: 28.3558,
  longitude: -81.5601,
},
{
  nome: "Boulevard Quick Eats",
  regiao: "Sunset Boulevard",
  tipo: "Economico",
  acesso: "Ao lado da Rock ‘n’ Roller Coaster",
  precoMedio: 11,
  destaque: "Snacks rápidos antes de pegar a montanha-russa. Não deixe de experimentar o pão de queijo americano.",
  latitude: 28.3559,
  longitude: -81.5602,
},

{
  nome: "Rosie’s All-American Café",
  regiao: "Sunset Boulevard",
  tipo: ["Classico", "Americano"],
    acesso: "Ao lado da Rock ‘n’ Roller Coaster",
  precoMedio: 24,
  destaque: "Comida americana tradicional com hambúrgueres e saladas. Não deixe de pedir o hambúrguer com bacon e batatas fritas.",
  latitude: 28.3556,
  longitude: -81.5599,
},
{
  nome: "Sunset Ranch Market",
  regiao: "Sunset Boulevard",
  tipo: "Saudavel",
  acesso: "Conjunto de quiosques ao lado da Sunset Blvd",
  precoMedio: 17,
  destaque: "Saladas, frutas e wraps frescos. Não deixe de experimentar o wrap vegetariano com molho de iogurte.",
  latitude: 28.3557,
  longitude: -81.5598,
},
// Oasis
{
  nome: "Rainforest Café",
  regiao: "Oasis",
  tipo: "Tematico",
  acesso: "Na entrada principal do parque, antes dos portões",
  precoMedio: 37,
  destaque: "Restaurante temático com floresta tropical e sons da natureza. Não deixe de experimentar o combo de frutos do mar com arroz de coco.",
  latitude: 28.3598,
  longitude: -81.5912,
},
{
  nome: "Explorer's Grill",
  regiao: "Oasis",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente ao lago central da Oasis, com mesas ao ar livre",
  precoMedio: 22,
  destaque: "Grelhados clássicos americanos, hambúrgueres e saladas. Não deixe de experimentar o cheeseburger artesanal com batata frita rústica.",
  latitude: 28.3595,
  longitude: -81.5914,
},
{
  nome: "Oasis Comfort Kitchen",
  regiao: "Oasis",
  tipo: "Conforto",
  acesso: "Ao lado da loja Garden Gate Gifts",
  precoMedio: 14,
  destaque: "Pratos reconfortantes como frango grelhado, arroz e legumes frescos. Não deixe de experimentar o mac and cheese com crosta de parmesão.",
  latitude: 28.3596,
  longitude: -81.5913,
},
{
  nome: "Oasis Snacks",
  regiao: "Oasis",
  tipo: "Economico",
  acesso: "Logo após os portões, à esquerda, próximo ao mapa do parque",
  precoMedio: 11,
  destaque: "Snacks rápidos e bebidas geladas. Não deixe de experimentar o sorvete de manga com cobertura de maracujá.",
  latitude: 28.3599,
  longitude: -81.5910,
},
{
  nome: "Tropical Roots Café",
  regiao: "Oasis",
  tipo: "Saudavel",
  acesso: "Próximo à ponte de acesso à Discovery Island",
  precoMedio: 13,
  destaque: "Smoothies naturais, wraps leves e frutas frescas. Não deixe de experimentar o smoothie de manga com gengibre e hortelã.",
  latitude: 28.3597,
  longitude: -81.5911,
},

// Discovery Island
{
  nome: "Flame Tree Barbecue",
  regiao: "Discovery Island",
  tipo: ["Classico", "Americano"],
    acesso: "Com vista para o lago, próximo à ponte para Asia",
  precoMedio: 26,
  destaque: "Carnes defumadas ao estilo churrasco americano. Não deixe de experimentar o prato de costela com molho barbecue doce e picante.",
  latitude: 28.3608,
  longitude: -81.5902,
},
{
  nome: "Discovery Feast",
  regiao: "Discovery Island",
  tipo: "Tematico",
  acesso: "Ao lado da Flame Tree Barbecue, com decoração de fauna e flora local",
  precoMedio: 22,
  destaque: "Pratos temáticos inspirados na natureza. Não deixe de experimentar o peixe grelhado com legumes locais.",
  latitude: 28.3614,
  longitude: -81.5905,
},

{
  nome: "Creature Comforts",
  regiao: "Discovery Island",
  tipo: "Conforto",
  acesso: "Entre as lojas principais, próximo ao caminho para Africa",
  precoMedio: 15,
  destaque: "Cafés, bolos e bebidas em estilo Starbucks. Não deixe de experimentar o muffin de banana com crumble de canela.",
  latitude: 28.3610,
  longitude: -81.5900,
},
{
  nome: "Island Eats",
  regiao: "Discovery Island",
  tipo: "Economico",
  acesso: "Perto do Tree of Life Garden",
  precoMedio: 13,
  destaque: "Snacks e refeições rápidas em área sombreada. Não deixe de experimentar os nachos com carne moída e molho agridoce.",
  latitude: 28.3612,
  longitude: -81.5903,
},
{
  nome: "Discovery Greens",
  regiao: "Discovery Island",
  tipo: "Saudavel",
  acesso: "Atrás da loja Island Mercantile",
  precoMedio: 17,
  destaque: "Bowls e wraps com ingredientes frescos. Não deixe de provar o bowl de quinoa com frango grelhado e vegetais salteados.",
  latitude: 28.3613,
  longitude: -81.5904,
},

// Pandora – The World of Avatar
{
  nome: "Satu’li Canteen",
 regiao: "Pandora",
   tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atração Flight of Passage",
  precoMedio: 30,
  destaque: "Comida inspirada em Pandora com apresentação artística. Não deixe de experimentar o bowl de carne grelhada com batata doce roxa.",
  latitude: 28.3595,
  longitude: -81.5886,
},
{
  nome: "Pongu Pongu",
 regiao: "Pandora",
   tipo: "Tematico",
  acesso: "Ao lado da entrada de Na’vi River Journey",
  precoMedio: 13,
  destaque: "Bebidas exóticas e doces coloridos. Não deixe de pedir o Pongu Lumpia – rolinho de abacaxi e cream cheese.",
  latitude: 28.3594,
  longitude: -81.5888,
},
{
  nome: "Avatar Comfort Eats",
 regiao: "Pandora",
   tipo: "Conforto",
  acesso: "Próximo à ponte de entrada de Pandora, em quiosque com vista para o rio",
  precoMedio: 15,
  destaque: "Snacks reconfortantes, como muffins de banana, cookies temáticos e wraps. Não deixe de experimentar o wrap quente de frango com molho de ervas.",
  latitude: 28.3593,
  longitude: -81.5887,
},
{
  nome: "Pandora Quick Snacks",
 regiao: "Pandora",
   tipo: "Economico",
  acesso: "Ao lado do quiosque de souvenirs Windtraders",
  precoMedio: 10,
  destaque: "Snacks e bebidas geladas para recarregar rápido. Não deixe de provar o sanduíche frio com mix de folhas e peito de peru.",
  latitude: 28.3596,
  longitude: -81.5885,
},
{
  nome: "Na'vi Greens",
 regiao: "Pandora",
   tipo: "Saudavel",
  acesso: "Atrás do Satu’li Canteen, próximo ao jardim bio-luminescente",
  precoMedio: 14,
  destaque: "Saladas, bowls naturais e sucos energizantes. Não deixe de experimentar o bowl de quinoa com frutas tropicais e castanhas.",
  latitude: 28.3597,
  longitude: -81.5884,
},


// Africa
{
  nome: "Tusker House Restaurant",
  regiao: "Africa",
  tipo: "Tematico",
  acesso: "Próximo à Harambe Market e Safari",
  precoMedio: 46,
  destaque: "Buffet africano com personagens Disney. Não deixe de experimentar o frango com molho de amendoim e arroz jollof.",
  latitude: 28.3590,
  longitude: -81.5930,
},
{
  nome: "Savannah Eats",
  regiao: "Africa",
  tipo: "Economico",
  acesso: "Ao lado do Harambe Market",
  precoMedio: 12,
  destaque: "Snacks e pratos rápidos para um almoço rápido. Não deixe de experimentar a samosa de vegetais.",
  latitude: 28.3592,
  longitude: -81.5933,
},

{
  nome: "Harambe Market",
  regiao: "Africa",
  tipo: ["Classico", "Americano"],
    acesso: "Ao lado da entrada da atração Kilimanjaro Safaris",
  precoMedio: 24,
  destaque: "Comida de rua africana servida em estações ao ar livre. Não deixe de pedir a linguiça grelhada com molho picante e arroz.",
  latitude: 28.3588,
  longitude: -81.5932,
},
{
  nome: "Zuri’s Sweets Shop",
  regiao: "Africa",
  tipo: "Conforto",
  acesso: "Ao lado do Harambe Fruit Market",
  precoMedio: 14,
  destaque: "Doces africanos, bolos e chocolates artesanais. Não deixe de experimentar o brownie de chocolate com pimenta rosa.",
  latitude: 28.3591,
  longitude: -81.5929,
},
{
  nome: "Harambe Fruit Market",
  regiao: "Africa",
  tipo: "Saudavel",
  acesso: "Em frente à saída da Kilimanjaro Safaris",
  precoMedio: 10,
  destaque: "Frutas frescas e sucos naturais. Não deixe de provar a salada de frutas com limão e hortelã.",
  latitude: 28.3589,
  longitude: -81.5931,
},

// Asia
{
  nome: "Yak & Yeti Restaurant",
  regiao: "Asia",
  tipo: ["Classico", "Americano"],
    acesso: "Entre Kali River Rapids e Maharajah Jungle Trek",
  precoMedio: 32,
  destaque: "Pratos asiáticos variados em ambiente temático. Não deixe de experimentar o arroz frito com camarão e vegetais.",
  latitude: 28.3580,
  longitude: -81.5915,
},
{
  nome: "Asian Flavors",
  regiao: "Asia",
  tipo: "Tematico",
  acesso: "Ao lado do Yak & Yeti Restaurant, decoração asiática",
  precoMedio: 20,
  destaque: "Comida temática de países asiáticos. Não deixe de experimentar o curry tailandês de camarão.",
  latitude: 28.3582,
  longitude: -81.5917,
},

{
  nome: "Anandapur Ice Cream Truck",
  regiao: "Asia",
  tipo: "Conforto",
  acesso: "Em frente à atração Expedition Everest",
  precoMedio: 9,
  destaque: "Sorvetes refrescantes em caminhão temático. Não deixe de experimentar o sorvete de coco com calda de frutas vermelhas.",
  latitude: 28.3579,
  longitude: -81.5916,
},
{
  nome: "Yak & Yeti Local Foods Café",
  regiao: "Asia",
  tipo: "Economico",
  acesso: "Ao lado do Yak & Yeti Restaurant",
  precoMedio: 15,
  destaque: "Pratos asiáticos rápidos como noodles e arroz. Não deixe de pedir o frango teriyaki com arroz frito.",
  latitude: 28.3581,
  longitude: -81.5914,
},
{
  nome: "Asia Greens",
  regiao: "Asia",
  tipo: "Saudavel",
  acesso: "Próximo ao caminho para o teatro do UP! A Great Bird Adventure",
  precoMedio: 16,
  destaque: "Saladas e wraps com sabores orientais. Não deixe de experimentar a salada de pepino com molho agridoce.",
  latitude: 28.3578,
  longitude: -81.5913,
},

// DinoLand U.S.A.
{
  nome: "Restaurantosaurus",
  regiao: "DinoLand U.S.A.",
  tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atração DINOSAUR",
  precoMedio: 22,
  destaque: "Lanches clássicos americanos com ambiente de escavação. Não deixe de experimentar o hambúrguer com batata waffle.",
  latitude: 28.3570,
  longitude: -81.5890,
},

{
  nome: "DinoLand Cafe",
  regiao: "DinoLand U.S.A.",
  tipo: "Tematico",
  acesso: "Ao lado do Restaurantosaurus, decoração jurássica",
  precoMedio: 18,
  destaque: "Pratos temáticos do tempo dos dinossauros. Não deixe de experimentar o frango crocante do T-Rex.",
  latitude: 28.3571,
  longitude: -81.5891,
},

{
  nome: "Trilo-Bites",
  regiao: "DinoLand U.S.A.",
  tipo: "Conforto",
  acesso: "Perto da entrada da ponte de Discovery Island",
  precoMedio: 10,
  destaque: "Snacks fritos e bebidas geladas. Não deixe de experimentar as loaded chips com cheddar derretido.",
  latitude: 28.3569,
  longitude: -81.5889,
},
{
  nome: "Dino Diner",
  regiao: "DinoLand U.S.A.",
  tipo: "Economico",
  acesso: "Ao lado do Fossil Fun Games",
  precoMedio: 9,
  destaque: "Cachorros-quentes e salgados rápidos. Não deixe de provar o corn dog crocante com molho ranch.",
  latitude: 28.3568,
  longitude: -81.5888,
},
{
  nome: "Dino Greens",
  regiao: "DinoLand U.S.A.",
  tipo: "Saudavel",
  acesso: "Próximo à área de recreação The Boneyard",
  precoMedio: 15,
  destaque: "Wraps e snacks naturais com toque jurássico. Não deixe de experimentar o wrap de atum com rúcula.",
  latitude: 28.3567,
  longitude: -81.5887,
},


  ];