export const  almocosDisney = [
// MainStreet
{
  nome: "Tonyâ€™s Town Square Restaurant",
  regiao: "MainStreet",
  tipo: ["Classico", "Americano"],
    acesso: "Logo apÃ³s a entrada principal do parque, ao lado do Town Square Theater",
  precoMedio: 36,
  destaque: "CulinÃ¡ria italiana clÃ¡ssica com ambiente elegante. NÃ£o deixe de experimentar o espaguete com almÃ´ndegas estilo 'A Dama e o Vagabundo'.",
  latitude: 28.4184,
  longitude: -81.5819,
},
{
  nome: "Main Street Bakery",
  regiao: "MainStreet",
  tipo: "Tematico",
  acesso: "Ao longo da Main Street, prÃ³ximo Ã  loja Emporium",
  precoMedio: 14,
  destaque: "Doces, cafÃ©s e lanches em estilo Starbucks. NÃ£o deixe de pedir o cinnamon roll quente com cobertura de aÃ§Ãºcar.",
  latitude: 28.4186,
  longitude: -81.5821,
},
{
  nome: "Caseyâ€™s Corner",
  regiao: "MainStreet",
  tipo: "Conforto",
  acesso: "No fim da Main Street, virando Ã  esquerda antes do castelo",
  precoMedio: 17,
  destaque: "Cachorros-quentes clÃ¡ssicos com batatas fritas. NÃ£o deixe de experimentar o hot dog com chili e queijo cheddar.",
  latitude: 28.4187,
  longitude: -81.5824,
},
{
  nome: "Plaza Ice Cream Parlor",
  regiao: "MainStreet",
  tipo: "Economico",
  acesso: "Ao lado do Caseyâ€™s Corner, com vista para o castelo",
  precoMedio: 10,
  destaque: "Sorvetes artesanais e milkshakes variados. NÃ£o deixe de provar o sundae com cookie e calda quente.",
  latitude: 28.4188,
  longitude: -81.5825,
},
{
  nome: "The Plaza Restaurant",
  regiao: "MainStreet",
  tipo: "Saudavel",
  acesso: "Ao lado do Plaza Ice Cream, em frente ao hub central",
  precoMedio: 20,
  destaque: "OpÃ§Ãµes leves como saladas e pratos vegetarianos. NÃ£o deixe de experimentar a salada com morangos e nozes caramelizadas.",
  latitude: 28.4189,
  longitude: -81.5826,
},

// Adventureland
{
  nome: "Skipper Canteen",
  regiao: "Adventureland",
  tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atraÃ§Ã£o Jungle Cruise",
  precoMedio: 35,
  destaque: "CulinÃ¡ria internacional em ambiente de exploraÃ§Ã£o. NÃ£o deixe de experimentar o frango ao curry tailandÃªs.",
  latitude: 28.4181,
  longitude: -81.5843,
},
{
  nome: "Tortuga Tavern",
  regiao: "Adventureland",
  tipo: "Tematico",
  acesso: "Em frente Ã  atraÃ§Ã£o Pirates of the Caribbean",
  precoMedio: 19,
  destaque: "Pratos rÃ¡pidos com inspiraÃ§Ã£o caribenha. NÃ£o deixe de pedir os nachos com carne e guacamole.",
  latitude: 28.4180,
  longitude: -81.5841,
},
{
  nome: "Sunshine Tree Terrace",
  regiao: "Adventureland",
  tipo: "Conforto",
  acesso: "Ao lado da atraÃ§Ã£o The Magic Carpets of Aladdin",
  precoMedio: 11,
  destaque: "Sobremesas geladas e sucos tropicais. NÃ£o deixe de experimentar o sorvete Dole Whip de laranja.",
  latitude: 28.4178,
  longitude: -81.5839,
},
{
  nome: "Aloha Isle",
  regiao: "Adventureland",
  tipo: "Economico",
  acesso: "Em frente Ã  Tiki Room",
  precoMedio: 9,
  destaque: "ClÃ¡ssico ponto de Dole Whip. NÃ£o deixe de provar a versÃ£o de abacaxi com suco natural.",
  latitude: 28.4177,
  longitude: -81.5840,
},
{
  nome: "Tiki Snacks",
  regiao: "Adventureland",
  tipo: "Saudavel",
  acesso: "Ao lado do Aloha Isle, prÃ³ximo Ã  ponte de Frontierland",
  precoMedio: 13,
  destaque: "Snacks leves como frutas frescas e wraps frios. NÃ£o deixe de experimentar a salada de manga com pepino.",
  latitude: 28.4176,
  longitude: -81.5838,
},

// Frontierland
{
  nome: "Pecos Bill Tall Tale Inn and Cafe",
  regiao: "Frontierland",
  tipo: ["Classico", "Americano"],
    acesso: "Ao lado da Splash Mountain",
  precoMedio: 25,
  destaque: "CulinÃ¡ria Tex-Mex em estilo rÃºstico. NÃ£o deixe de experimentar o burrito de carne com arroz temperado.",
  latitude: 28.4174,
  longitude: -81.5853,
},
{
  nome: "Westward Ho",
  regiao: "Frontierland",
  tipo: "Tematico",
  acesso: "Em frente Ã  Country Bear Jamboree",
  precoMedio: 14,
  destaque: "Snacks rÃ¡pidos com tema de velho oeste. NÃ£o deixe de provar o milho grelhado com manteiga.",
  latitude: 28.4175,
  longitude: -81.5851,
},
{
  nome: "Frontier Snacks",
  regiao: "Frontierland",
  tipo: "Conforto",
  acesso: "Perto da entrada da Tom Sawyer Island",
  precoMedio: 16,
  destaque: "Churros e pretzels tradicionais. NÃ£o deixe de experimentar o churro com recheio de doce de leite.",
  latitude: 28.4173,
  longitude: -81.5850,
},
{
  nome: "Country Cookinâ€™",
  regiao: "Frontierland",
  tipo: "Economico",
  acesso: "Nos fundos do Pecos Bill, prÃ³ximo ao bebedouro",
  precoMedio: 12,
  destaque: "Frango frito e acompanhamentos tÃ­picos. NÃ£o deixe de experimentar a coxa com molho barbecue.",
  latitude: 28.4172,
  longitude: -81.5849,
},
{
  nome: "Prairie Greens",
  regiao: "Frontierland",
  tipo: "Saudavel",
  acesso: "PrÃ³ximo ao trilho do trem de Frontierland",
  precoMedio: 18,
  destaque: "Saladas e wraps com ingredientes frescos. NÃ£o deixe de provar o wrap de peru com rÃºcula e tomate seco.",
  latitude: 28.4171,
  longitude: -81.5848,
},

// LibertySquare
{
  nome: "Liberty Tree Tavern",
  regiao: "LibertySquare",
  tipo: ["Classico", "Americano"],
    acesso: "2 min a pÃ© da Haunted Mansion",
  precoMedio: 39,
  destaque: "Pratos coloniais servidos Ã  vontade. NÃ£o deixe de experimentar o assado de carne com molho caseiro.",
  latitude: 28.4190,
  longitude: -81.5834,
},
{
  nome: "Liberty Comfort Kitchen",
  regiao: "LibertySquare",
  tipo: "Conforto",
  acesso: "PrÃ³ximo ao Hall of Presidents, ao lado do Columbia Harbour House",
  precoMedio: 19,
  destaque: "Pratos reconfortantes como meatloaf americano, purÃª de batata e legumes. NÃ£o deixe de experimentar o clÃ¡ssico mac and cheese com bacon crocante.",
  latitude: 28.4197,
  longitude: -81.5832,
},

{
  nome: "The Diamond Horseshoe",
  regiao: "LibertySquare",
  tipo: "Tematico",
  acesso: "PrÃ³ximo Ã  entrada da Liberty Square",
  precoMedio: 42,
  destaque: "Ambiente de salÃ£o do velho oeste com carnes grelhadas. NÃ£o deixe de pedir o brisket defumado com milho.",
  latitude: 28.4191,
  longitude: -81.5838,
},

{
  nome: "Liberty Snacks",
  regiao: "LibertySquare",
  tipo: "Economico",
  acesso: "PrÃ³ximo ao Liberty Square Riverboat",
  precoMedio: 12,
  destaque: "Snacks rÃ¡pidos e porÃ§Ãµes econÃ´micas. NÃ£o deixe de comer o pretzel recheado com queijo.",
  latitude: 28.4193,
  longitude: -81.5831,
},
{
  nome: "Revolution Greens",
  regiao: "LibertySquare",
  tipo: "Saudavel",
  acesso: "AtrÃ¡s do Liberty Tree Tavern",
  precoMedio: 19,
  destaque: "Saladas frescas e bowls naturais. NÃ£o deixe de experimentar a salada de grÃ£o-de-bico com azeite cÃ­trico.",
  latitude: 28.4192,
  longitude: -81.5835,
},

// Fantasyland
{
  nome: "The Royal Table Lunch",
  regiao: "Fantasyland",
  tipo: "Classico",
  acesso: "Dentro do Castelo da Cinderela",
  precoMedio: 38,
  destaque: "AlmoÃ§o com pratos americanos em ambiente real. NÃ£o deixe de experimentar o frango grelhado com legumes e molho de ervas.",
  latitude: 28.4194,
  longitude: -81.5812,
},
{
  nome: "Be Our Guest Restaurant",
  regiao: "Fantasyland",
  tipo: "Tematico",
  acesso: "2 min a pÃ© do Seven Dwarfs Mine Train",
  precoMedio: 48,
  destaque: "Ambiente inspirado no castelo da Fera. NÃ£o deixe de pedir o filet mignon com purÃª trufado.",
  latitude: 28.4203,
  longitude: -81.5805,
},
{
  nome: "Gastonâ€™s Tavern Lunch",
  regiao: "Fantasyland",
  tipo: "Conforto",
  acesso: "2 min a pÃ© de Under the Sea â€“ Journey of The Little Mermaid",
  precoMedio: 21,
  destaque: "SanduÃ­ches e sopas em ambiente rÃºstico. NÃ£o deixe de experimentar o sanduÃ­che de peru com queijo suÃ­Ã§o.",
  latitude: 28.4211,
  longitude: -81.5809,
},
{
  nome: "Friarâ€™s Nook",
  regiao: "Fantasyland",
  tipo: "Economico",
  acesso: "1 min a pÃ© do Prince Charming Regal Carrousel",
  precoMedio: 13,
  destaque: "Mac and cheese com diversas coberturas. NÃ£o deixe de comer o mac and cheese com bacon crocante.",
  latitude: 28.4198,
  longitude: -81.5817,
},
{
  nome: "Pinocchio Village Haus",
  regiao: "Fantasyland",
  tipo: "Saudavel",
  acesso: "Ao lado do Itâ€™s a Small World",
  precoMedio: 18,
  destaque: "Flatbreads e saladas leves. NÃ£o deixe de experimentar o flatbread vegetariano com legumes grelhados.",
  latitude: 28.4195,
  longitude: -81.5820,
},

// Tomorrowland
{
  nome: "Cosmic Rayâ€™s Starlight CafÃ©",
  regiao: "Tomorrowland",
  tipo: ["Classico", "Americano"],
    acesso: "Em frente Ã  atraÃ§Ã£o Buzz Lightyear",
  precoMedio: 24,
  destaque: "Lanches clÃ¡ssicos com show alienÃ­gena. NÃ£o deixe de experimentar o hambÃºrguer duplo com onion rings.",
  latitude: 28.4200,
  longitude: -81.5792,
},
{
  nome: "The Lunching Pad",
  regiao: "Tomorrowland",
  tipo: "Tematico",
  acesso: "Na base da atraÃ§Ã£o Astro Orbiter",
  precoMedio: 16,
  destaque: "Snacks rÃ¡pidos com tema espacial. NÃ£o deixe de pedir o pretzel recheado com cream cheese de jalapeÃ±o.",
  latitude: 28.4201,
  longitude: -81.5793,
},
{
  nome: "Tomorrow Bites",
  regiao: "Tomorrowland",
  tipo: "Conforto",
  acesso: "Ao lado da entrada da Space Mountain",
  precoMedio: 14,
  destaque: "Lanches e batatas fritas para todos os gostos. NÃ£o deixe de provar os nuggets com batata smile.",
  latitude: 28.4202,
  longitude: -81.5794,
},
{
  nome: "Galaxy Snacks",
  regiao: "Tomorrowland",
  tipo: "Economico",
  acesso: "AtrÃ¡s do Tomorrowland Speedway",
  precoMedio: 11,
  destaque: "Snacks e bebidas rÃ¡pidas. NÃ£o deixe de experimentar o wrap de queijo com tomate seco.",
  latitude: 28.4203,
  longitude: -81.5795,
},
{
  nome: "Orbital Greens",
  regiao: "Tomorrowland",
  tipo: "Saudavel",
  acesso: "Ao lado do Space Ranger Spin",
  precoMedio: 17,
  destaque: "Bowls saudÃ¡veis e sucos naturais. NÃ£o deixe de pedir o bowl de quinoa com abacate e frango grelhado.",
  latitude: 28.4204,
  longitude: -81.5796,
},
// World Showcase
{
  nome: "Les Chefs de France",
  regiao: "World Showcase",
  tipo: ["Classico", "Americano"],
    acesso: "PavilhÃ£o da FranÃ§a â€“ em frente Ã  entrada da atraÃ§Ã£o Remyâ€™s Ratatouille Adventure",
  precoMedio: 39,
  destaque: "CulinÃ¡ria francesa tradicional com pratos refinados. NÃ£o deixe de experimentar o entrecÃ´te grelhado com batatas gratinadas.",
  latitude: 28.3705,
  longitude: -81.5502,
},
{
  nome: "Teppan Edo",
  regiao: "World Showcase",
  tipo: "Tematico",
  acesso: "PavilhÃ£o do JapÃ£o â€“ segundo andar, acima da loja Mitsukoshi",
  precoMedio: 45,
  destaque: "Chapas japonesas com preparo ao vivo na mesa. NÃ£o deixe de pedir o filet mignon grelhado com legumes frescos.",
  latitude: 28.3701,
  longitude: -81.5489,
},
{
  nome: "Via Napoli Ristorante e Pizzeria",
  regiao: "World Showcase",
  tipo: "Conforto",
  acesso: "PavilhÃ£o da ItÃ¡lia â€“ nos fundos, prÃ³ximo Ã  fonte central",
  precoMedio: 28,
  destaque: "Pizzas autÃªnticas assadas em forno Ã  lenha. NÃ£o deixe de experimentar a pizza Margherita tradicional.",
  latitude: 28.3704,
  longitude: -81.5513,
},
{
  nome: "La Cantina de San Angel",
  regiao: "World Showcase",
  tipo: "Economico",
  acesso: "PavilhÃ£o do MÃ©xico â€“ na beira do lago, ao lado da pirÃ¢mide",
  precoMedio: 15,
  destaque: "Tacos e nachos em estilo fast casual. NÃ£o deixe de experimentar o combo de tacos com guacamole.",
  latitude: 28.3711,
  longitude: -81.5475,
},
{
  nome: "Tangierine CafÃ©",
  regiao: "World Showcase",
  tipo: "Saudavel",
  acesso: "PavilhÃ£o do Marrocos â€“ em frente Ã  entrada da Fez House",
  precoMedio: 19,
  destaque: "Pratos mediterrÃ¢neos frescos e leves. NÃ£o deixe de provar o couscous com legumes grelhados e molho de limÃ£o.",
  latitude: 28.3708,
  longitude: -81.5493,
},

// World Discovery
{
  nome: "Space 220 Restaurant",
  regiao: "World Discovery",
  tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atraÃ§Ã£o Mission: SPACE â€“ acesso com elevador espacial simulado",
  precoMedio: 55,
  destaque: "ExperiÃªncia gastronÃ´mica em ambiente de estaÃ§Ã£o espacial. NÃ£o deixe de experimentar o frango grelhado com batatas ao alho.",
  latitude: 28.3735,
  longitude: -81.5480,
},
{
  nome: "Connections Eatery",
  regiao: "World Discovery",
  tipo: "Tematico",
  acesso: "Em frente Ã  Guardians of the Galaxy: Cosmic Rewind",
  precoMedio: 26,
  destaque: "Ambiente moderno com comidas internacionais. NÃ£o deixe de pedir o hambÃºrguer gourmet com molho especial da casa.",
  latitude: 28.3742,
  longitude: -81.5485,
},
{
  nome: "Test Track Snacks",
  regiao: "World Discovery",
  tipo: "Conforto",
  acesso: "Ao lado da saÃ­da da atraÃ§Ã£o Test Track",
  precoMedio: 14,
  destaque: "Snacks rÃ¡pidos com bebidas energÃ©ticas. NÃ£o deixe de experimentar o wrap de frango picante com cheddar.",
  latitude: 28.3751,
  longitude: -81.5483,
},
{
  nome: "Launch Fuel Bites",
  regiao: "World Discovery",
  tipo: "Economico",
  acesso: "PrÃ³ximo Ã  entrada do Mission: SPACE",
  precoMedio: 11,
  destaque: "Snacks prÃ¡ticos e sanduÃ­ches embalados. NÃ£o deixe de experimentar o sanduÃ­che frio com pasta de atum.",
  latitude: 28.3733,
  longitude: -81.5478,
},
{
  nome: "Nova Greens",
  regiao: "World Discovery",
  tipo: "Saudavel",
  acesso: "Ãrea lateral da Cosmic Rewind",
  precoMedio: 17,
  destaque: "Saladas e bowls com proteÃ­na magra. NÃ£o deixe de provar o bowl de salmÃ£o com arroz de couve-flor.",
  latitude: 28.3748,
  longitude: -81.5477,
},

// World Celebration
{
  nome: "Connections CafÃ©",
  regiao: "World Celebration",
  tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo ao Creations Shop, centro do parque",
  precoMedio: 22,
  destaque: "Pratos variados em espaÃ§o moderno e amplo. NÃ£o deixe de experimentar o sanduÃ­che de frango grelhado com pesto.",
  latitude: 28.3741,
  longitude: -81.5487,
},
{
  nome: "EPCOT Brew House",
  regiao: "World Celebration",
  tipo: "Tematico",
  acesso: "Ao lado do Connections CafÃ©",
  precoMedio: 20,
  destaque: "Cervejas artesanais e petiscos de pub. NÃ£o deixe de pedir o combo de mini hambÃºrgueres com molho barbecue.",
  latitude: 28.3743,
  longitude: -81.5488,
},
{
  nome: "Garden Snacks",
  regiao: "World Celebration",
  tipo: "Conforto",
  acesso: "Em frente ao centro interativo Dreamers Point",
  precoMedio: 13,
  destaque: "Snacks e sobremesas geladas. NÃ£o deixe de provar o cookie recheado com sorvete de baunilha.",
  latitude: 28.3745,
  longitude: -81.5486,
},
{
  nome: "Central Eats",
  regiao: "World Celebration",
  tipo: "Economico",
  acesso: "Corredor central, perto da entrada do World Showcase",
  precoMedio: 10,
  destaque: "OpÃ§Ãµes rÃ¡pidas e econÃ´micas. NÃ£o deixe de experimentar o hot dog com molho de queijo cheddar.",
  latitude: 28.3740,
  longitude: -81.5489,
},
{
  nome: "Fresh Start Salads",
  regiao: "World Celebration",
  tipo: "Saudavel",
  acesso: "Ao lado da Ã¡rea do Creations Shop",
  precoMedio: 16,
  destaque: "Saladas frescas com proteÃ­nas opcionais. NÃ£o deixe de provar a salada de frango com molho cÃ­trico.",
  latitude: 28.3746,
  longitude: -81.5484,
},

// World Nature
{
  nome: "The Land Grill",
  regiao: "World Nature",
  tipo: ["Classico", "Americano"],
    acesso: "Dentro do pavilhÃ£o The Land â€“ andar inferior",
  precoMedio: 30,
  destaque: "Pratos variados com ingredientes frescos da prÃ³pria estufa. NÃ£o deixe de experimentar o frango assado com legumes do Living with the Land.",
  latitude: 28.3724,
  longitude: -81.5472,
},
{
  nome: "Coral Reef Restaurant",
  regiao: "World Nature",
  tipo: "Tematico",
  acesso: "Ao lado da atraÃ§Ã£o The Seas with Nemo & Friends",
  precoMedio: 42,
  destaque: "Ambiente subaquÃ¡tico com vista para aquÃ¡rio gigante. NÃ£o deixe de pedir o filÃ© de salmÃ£o grelhado com risoto de limÃ£o.",
  latitude: 28.3720,
  longitude: -81.5469,
},
{
  nome: "Nature Eats",
  regiao: "World Nature",
  tipo: "Conforto",
  acesso: "SaÃ­da do pavilhÃ£o The Land",
  precoMedio: 18,
  destaque: "Lanches reconfortantes e sobremesas frutadas. NÃ£o deixe de experimentar a tortinha de maÃ§Ã£ com canela.",
  latitude: 28.3726,
  longitude: -81.5470,
},
{
  nome: "Harvest Snacks",
  regiao: "World Nature",
  tipo: "Economico",
  acesso: "Entre The Land e The Seas",
  precoMedio: 12,
  destaque: "Snacks naturais e sucos prensados. NÃ£o deixe de experimentar o wrap de cenoura com hummus.",
  latitude: 28.3725,
  longitude: -81.5471,
},
{
  nome: "Green Bowl Express",
  regiao: "World Nature",
  tipo: "Saudavel",
  acesso: "Entrada do pavilhÃ£o The Land",
  precoMedio: 17,
  destaque: "Bowls veganos e sucos naturais. NÃ£o deixe de provar o bowl de quinoa com manga e rÃºcula.",
  latitude: 28.3723,
  longitude: -81.5473,
},
// Hollywood Boulevard
{
  nome: "The Trolley Car CafÃ©",
  regiao: "Hollywood Boulevard",
  tipo: "Economico",
  acesso: "Ao lado da entrada principal, perto da loja Mickeyâ€™s of Hollywood",
  precoMedio: 12,
  destaque: "CafÃ©s especiais e doces rÃ¡pidos. NÃ£o deixe de experimentar o carrot cake cookie recheado.",
  latitude: 28.3571,
  longitude: -81.5582,
},
{
  nome: "Hollywood & Vine",
  regiao: "Hollywood Boulevard",
  tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo ao centro da praÃ§a principal",
  precoMedio: 42,
  destaque: "Buffet com culinÃ¡ria americana tradicional. NÃ£o deixe de experimentar o assado de carne com purÃª e legumes.",
  latitude: 28.3574,
  longitude: -81.5581,
},
{
  nome: "Studio Stars Cafe",
  regiao: "Hollywood Boulevard",
  tipo: "Tematico",
  acesso: "PrÃ³ximo ao Hollywood & Vine, com decoraÃ§Ã£o dos anos dourados de Hollywood",
  precoMedio: 19,
  destaque: "Pratos temÃ¡ticos homenageando astros do cinema. NÃ£o deixe de experimentar o burger Golden Age.",
  latitude: 28.3572,
  longitude: -81.5583,
},
{
  nome: "Boulevard Comforts",
  regiao: "Hollywood Boulevard",
  tipo: "Conforto",
  acesso: "Ao lado da loja Mickeyâ€™s of Hollywood",
  precoMedio: 14,
  destaque: "Comida caseira estilo americano. NÃ£o deixe de experimentar o ensopado de carne com pÃ£o de alho.",
  latitude: 28.3573,
  longitude: -81.5584,
},
{
  nome: "Hollywood Greens",
  regiao: "Hollywood Boulevard",
  tipo: "Saudavel",
  acesso: "AtrÃ¡s do Hollywood & Vine",
  precoMedio: 15,
  destaque: "Wraps, saladas e bowls saudÃ¡veis para uma refeiÃ§Ã£o leve. NÃ£o deixe de provar o wrap de frango Caesar.",
  latitude: 28.3574,
  longitude: -81.5585,
},


// Echo Lake
{
  nome: "50's Prime Time CafÃ©",
  regiao: "Echo Lake",
  tipo: "Tematico",
  acesso: "AtrÃ¡s do Echo Lake, perto do Indiana Jones Epic Stunt Spectacular",
  precoMedio: 37,
  destaque: "Restaurante retrÃ´ com clima dos anos 50. NÃ£o deixe de pedir o frango frito caseiro com purÃª de batata.",
  latitude: 28.3578,
  longitude: -81.5590,
},
{
  nome: "Lake Quick Bites",
  regiao: "Echo Lake",
  tipo: "Economico",
  acesso: "PrÃ³ximo ao Indiana Jones Epic Stunt Spectacular",
  precoMedio: 11,
  destaque: "SanduÃ­ches rÃ¡pidos e snacks acessÃ­veis. NÃ£o deixe de experimentar o sanduÃ­che de peito de peru com chips.",
  latitude: 28.3577,
  longitude: -81.5589,
},

{
  nome: "Backlot Express",
  regiao: "Echo Lake",
  tipo: "Conforto",
  acesso: "Ao lado da atraÃ§Ã£o Star Tours",
  precoMedio: 18,
  destaque: "SanduÃ­ches e hambÃºrgueres rÃ¡pidos com espaÃ§o temÃ¡tico. NÃ£o deixe de experimentar o cheeseburger com molho barbecue.",
  latitude: 28.3580,
  longitude: -81.5588,
},
{
  nome: "Echo Snacks",
  regiao: "Echo Lake",
  tipo: "Saudavel",
  acesso: "Em frente ao Echo Lake, ao lado do Lago",
  precoMedio: 14,
  destaque: "Frutas frescas, wraps e smoothies. NÃ£o deixe de provar o wrap de frango com espinafre.",
  latitude: 28.3581,
  longitude: -81.5591,
},
{
  nome: "Echo Diner",
  regiao: "Echo Lake",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente Ã  entrada da atraÃ§Ã£o Indiana Jones Epic Stunt Spectacular",
  precoMedio: 22,
  destaque: "ClÃ¡ssicos americanos como hambÃºrguer, cheeseburger, onion rings e milkshake. NÃ£o deixe de experimentar o cheeseburger artesanal com batata frita.",
  latitude: 28.3577,
  longitude: -81.5592,
},

// Grand Avenue
{
  nome: "Mama Melroseâ€™s Ristorante Italiano",
  regiao: "Grand Avenue",
  tipo: ["Classico", "Americano"],
    acesso: "No fim da Grand Avenue, prÃ³ximo Ã  atraÃ§Ã£o Muppet*Vision 3D",
  precoMedio: 34,
  destaque: "Comida italiana clÃ¡ssica em ambiente aconchegante. NÃ£o deixe de experimentar o penne com molho quatro queijos.",
  latitude: 28.3575,
  longitude: -81.5602,
},
{
  nome: "Muppet Theatre Tavern",
  regiao: "Grand Avenue",
  tipo: "Tematico",
  acesso: "Ao lado do PizzeRizzo, ambiente inspirado nos Muppets",
  precoMedio: 18,
  destaque: "Pratos temÃ¡ticos com apresentaÃ§Ãµes teatrais dos Muppets. NÃ£o deixe de experimentar o sanduÃ­che Swedish Chef.",
  latitude: 28.3578,
  longitude: -81.5604,
},
{
  nome: "Backlot Comfort",
  regiao: "Grand Avenue",
  tipo: "Conforto",
  acesso: "Perto da saÃ­da do Muppet*Vision 3D",
  precoMedio: 15,
  destaque: "Comidas confortÃ¡veis, como macarrÃ£o com queijo e mini almÃ´ndegas. NÃ£o deixe de experimentar a sopa de tomate artesanal.",
  latitude: 28.3579,
  longitude: -81.5605,
},
{
  nome: "Green Stage Bowls",
  regiao: "Grand Avenue",
  tipo: "Saudavel",
  acesso: "AtrÃ¡s do Muppet Courtyard",
  precoMedio: 14,
  destaque: "Bowls saudÃ¡veis com legumes frescos e proteÃ­na leve. NÃ£o deixe de provar o bowl de frango grelhado com legumes.",
  latitude: 28.3580,
  longitude: -81.5606,
},

{
  nome: "Rizzo Snacks",
  regiao: "Grand Avenue",
  tipo: "Economico",
  acesso: "AtrÃ¡s do PizzeRizzo",
  precoMedio: 10,
  destaque: "Snacks rÃ¡pidos como pretzels e cookies. NÃ£o deixe de experimentar o pretzel recheado de cheddar.",
  latitude: 28.3577,
  longitude: -81.5601,
},

// Star Wars: Galaxyâ€™s Edge
{
  nome: "Docking Bay 7 Food and Cargo",
  regiao: "Star Wars: Galaxyâ€™s Edge",
  tipo: ["Classico", "Americano"],
    acesso: "AtrÃ¡s da Millennium Falcon",
  precoMedio: 29,
  destaque: "Pratos exÃ³ticos inspirados na galÃ¡xia Star Wars. NÃ£o deixe de experimentar o frango grelhado de Endor com arroz cÃ­trico.",
  latitude: 28.3584,
  longitude: -81.5615,
},
{
  nome: "Ogaâ€™s Cantina",
  regiao: "Star Wars: Galaxyâ€™s Edge",
  tipo: "Tematico",
  acesso: "Ao lado do mercado Black Spire Outpost",
  precoMedio: 35,
  destaque: "Bar temÃ¡tico com coquetÃ©is especiais. NÃ£o deixe de pedir o Fuzzy Tauntaun com espuma vibrante.",
  latitude: 28.3585,
  longitude: -81.5616,
},
{
  nome: "Ronto Roasters",
  regiao: "Star Wars: Galaxyâ€™s Edge",
  tipo: "Conforto",
  acesso: "Em frente Ã  loja Droid Depot",
  precoMedio: 14,
  destaque: "SanduÃ­ches grelhados com carne defumada. NÃ£o deixe de experimentar o Ronto Wrap clÃ¡ssico.",
  latitude: 28.3586,
  longitude: -81.5614,
},
{
  nome: "Black Spire Outpost Snacks",
  regiao: "Star Wars: Galaxyâ€™s Edge",
  tipo: "Economico",
  acesso: "Mercado Black Spire Outpost",
  precoMedio: 12,
  destaque: "Snacks galÃ¡cticos rÃ¡pidos e acessÃ­veis. NÃ£o deixe de experimentar o Batuu Popcorn Mix.",
  latitude: 28.3587,
  longitude: -81.5613,
},
{
  nome: "Star Wars Greens",
  regiao: "Star Wars: Galaxyâ€™s Edge",
  tipo: "Saudavel",
  acesso: "AtrÃ¡s da Millennium Falcon",
  precoMedio: 15,
  destaque: "Saladas e bowls de uma galÃ¡xia distante. NÃ£o deixe de experimentar a salada de algas de Endor.",
  latitude: 28.3588,
  longitude: -81.5612,
},


// Toy Story Land
{
  nome: "Woodyâ€™s Lunch Box",
  regiao: "Toy Story Land",
  tipo: "Conforto",
  acesso: "Ao lado da atraÃ§Ã£o Slinky Dog Dash",
  precoMedio: 19,
  destaque: "Pratos inspirados em lanches infantis. NÃ£o deixe de experimentar o grilled cheese com sopa de tomate.",
  latitude: 28.3591,
  longitude: -81.5621,
},
{
  nome: "Toy Story Grill",
  regiao: "Toy Story Land",
  tipo: ["Classico", "Americano"],
  acesso: "PrÃ³ximo ao Woodyâ€™s Lunch Box",
  precoMedio: 20,
  destaque: "Lanches clÃ¡ssicos e grelhados para toda famÃ­lia. NÃ£o deixe de experimentar o cheeseburger do Woody.",
  latitude: 28.3594,
  longitude: -81.5624,
},
{
  nome: "Andy's Diner",
  regiao: "Toy Story Land",
  tipo: "Tematico",
  acesso: "Entre as atraÃ§Ãµes Alien Swirling Saucers e Slinky Dog Dash",
  precoMedio: 18,
  destaque: "RefeiÃ§Ãµes temÃ¡ticas inspiradas nos brinquedos de Andy. NÃ£o deixe de provar o macarrÃ£o ao molho de queijo derretido.",
  latitude: 28.3595,
  longitude: -81.5625,
},

{
  nome: "Toy Box Treats",
  regiao: "Toy Story Land",
  tipo: "Economico",
  acesso: "Perto do Alien Swirling Saucers",
  precoMedio: 11,
  destaque: "Doces coloridos e bebidas refrescantes. NÃ£o deixe de provar o sundae de morango com chantilly.",
  latitude: 28.3592,
  longitude: -81.5622,
},
{
  nome: "Green Army Snacks",
  regiao: "Toy Story Land",
  tipo: "Saudavel",
  acesso: "AtrÃ¡s da parada do Green Army Patrol",
  precoMedio: 13,
  destaque: "Snacks naturais e frutas embaladas. NÃ£o deixe de experimentar o mix de castanhas e frutas secas.",
  latitude: 28.3593,
  longitude: -81.5623,
},

// Animation Courtyard
{
  nome: "Animators CafÃ©",
  regiao: "Animation Courtyard",
  tipo: ["Classico", "Americano"],
    acesso: "Perto da entrada do Disney Junior Dance Party",
  precoMedio: 26,
  destaque: "Pratos clÃ¡ssicos em ambiente inspirado em animaÃ§Ãµes. NÃ£o deixe de experimentar o frango com purÃª e legumes grelhados.",
  latitude: 28.3568,
  longitude: -81.5598,
},
{
  nome: "Animation Diner",
  regiao: "Animation Courtyard",
  tipo: "Tematico",
  acesso: "Ao lado do Animators CafÃ©, ambiente decorado com desenhos clÃ¡ssicos Disney",
  precoMedio: 23,
  destaque: "Pratos temÃ¡ticos inspirados nos filmes da Disney. NÃ£o deixe de experimentar o Mickey Waffle Sandwich.",
  latitude: 28.3566,
  longitude: -81.5596,
},
{
  nome: "Cartoon Comforts",
  regiao: "Animation Courtyard",
  tipo: "Conforto",
  acesso: "PrÃ³ximo ao Walt Disney Presents",
  precoMedio: 16,
  destaque: "Comidas reconfortantes para toda a famÃ­lia. NÃ£o deixe de experimentar o purÃª de batata com frango empanado.",
  latitude: 28.3565,
  longitude: -81.5595,
},
{
  nome: "Fresh Sketch Greens",
  regiao: "Animation Courtyard",
  tipo: "Saudavel",
  acesso: "Entre a loja Disney Junior e o Playhouse Disney",
  precoMedio: 15,
  destaque: "Saladas frescas, wraps leves e bowls coloridos. NÃ£o deixe de experimentar o bowl vegano de quinoa com manga.",
  latitude: 28.3564,
  longitude: -81.5594,
},

{
  nome: "Courtyard Snacks",
  regiao: "Animation Courtyard",
  tipo: "Economico",
  acesso: "Ao lado do Walt Disney Presents",
  precoMedio: 9,
  destaque: "Snacks rÃ¡pidos e bebidas. NÃ£o deixe de provar o cookie recheado de Nutella.",
  latitude: 28.3567,
  longitude: -81.5597,
},

// Sunset Boulevard
{
  nome: "Hollywood Scoops",
  regiao: "Sunset Boulevard",
  tipo: "Conforto",
  acesso: "Em frente Ã  The Twilight Zone Tower of Terror",
  precoMedio: 13,
  destaque: "Sorvetes artesanais e sobremesas geladas. NÃ£o deixe de experimentar o sundae com brownie quente.",
  latitude: 28.3555,
  longitude: -81.5600,
},
{
  nome: "Twilight Snacks",
  regiao: "Sunset Boulevard",
  tipo: "Tematico",
  acesso: "PrÃ³ximo Ã  Tower of Terror, decoraÃ§Ã£o inspirada na era dourada de Hollywood",
  precoMedio: 19,
  destaque: "Pratos temÃ¡ticos de terror e mistÃ©rio. NÃ£o deixe de experimentar o sanduÃ­che 'Sombra da Noite'.",
  latitude: 28.3558,
  longitude: -81.5601,
},
{
  nome: "Boulevard Quick Eats",
  regiao: "Sunset Boulevard",
  tipo: "Economico",
  acesso: "Ao lado da Rock â€˜nâ€™ Roller Coaster",
  precoMedio: 11,
  destaque: "Snacks rÃ¡pidos antes de pegar a montanha-russa. NÃ£o deixe de experimentar o pÃ£o de queijo americano.",
  latitude: 28.3559,
  longitude: -81.5602,
},

{
  nome: "Rosieâ€™s All-American CafÃ©",
  regiao: "Sunset Boulevard",
  tipo: ["Classico", "Americano"],
    acesso: "Ao lado da Rock â€˜nâ€™ Roller Coaster",
  precoMedio: 24,
  destaque: "Comida americana tradicional com hambÃºrgueres e saladas. NÃ£o deixe de pedir o hambÃºrguer com bacon e batatas fritas.",
  latitude: 28.3556,
  longitude: -81.5599,
},
{
  nome: "Sunset Ranch Market",
  regiao: "Sunset Boulevard",
  tipo: "Saudavel",
  acesso: "Conjunto de quiosques ao lado da Sunset Blvd",
  precoMedio: 17,
  destaque: "Saladas, frutas e wraps frescos. NÃ£o deixe de experimentar o wrap vegetariano com molho de iogurte.",
  latitude: 28.3557,
  longitude: -81.5598,
},
// Oasis
{
  nome: "Rainforest CafÃ©",
  regiao: "Oasis",
  tipo: "Tematico",
  acesso: "Na entrada principal do parque, antes dos portÃµes",
  precoMedio: 37,
  destaque: "Restaurante temÃ¡tico com floresta tropical e sons da natureza. NÃ£o deixe de experimentar o combo de frutos do mar com arroz de coco.",
  latitude: 28.3598,
  longitude: -81.5912,
},
{
  nome: "Explorer's Grill",
  regiao: "Oasis",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente ao lago central da Oasis, com mesas ao ar livre",
  precoMedio: 22,
  destaque: "Grelhados clÃ¡ssicos americanos, hambÃºrgueres e saladas. NÃ£o deixe de experimentar o cheeseburger artesanal com batata frita rÃºstica.",
  latitude: 28.3595,
  longitude: -81.5914,
},
{
  nome: "Oasis Comfort Kitchen",
  regiao: "Oasis",
  tipo: "Conforto",
  acesso: "Ao lado da loja Garden Gate Gifts",
  precoMedio: 14,
  destaque: "Pratos reconfortantes como frango grelhado, arroz e legumes frescos. NÃ£o deixe de experimentar o mac and cheese com crosta de parmesÃ£o.",
  latitude: 28.3596,
  longitude: -81.5913,
},
{
  nome: "Oasis Snacks",
  regiao: "Oasis",
  tipo: "Economico",
  acesso: "Logo apÃ³s os portÃµes, Ã  esquerda, prÃ³ximo ao mapa do parque",
  precoMedio: 11,
  destaque: "Snacks rÃ¡pidos e bebidas geladas. NÃ£o deixe de experimentar o sorvete de manga com cobertura de maracujÃ¡.",
  latitude: 28.3599,
  longitude: -81.5910,
},
{
  nome: "Tropical Roots CafÃ©",
  regiao: "Oasis",
  tipo: "Saudavel",
  acesso: "PrÃ³ximo Ã  ponte de acesso Ã  Discovery Island",
  precoMedio: 13,
  destaque: "Smoothies naturais, wraps leves e frutas frescas. NÃ£o deixe de experimentar o smoothie de manga com gengibre e hortelÃ£.",
  latitude: 28.3597,
  longitude: -81.5911,
},

// Discovery Island
{
  nome: "Flame Tree Barbecue",
  regiao: "Discovery Island",
  tipo: ["Classico", "Americano"],
    acesso: "Com vista para o lago, prÃ³ximo Ã  ponte para Asia",
  precoMedio: 26,
  destaque: "Carnes defumadas ao estilo churrasco americano. NÃ£o deixe de experimentar o prato de costela com molho barbecue doce e picante.",
  latitude: 28.3608,
  longitude: -81.5902,
},
{
  nome: "Discovery Feast",
  regiao: "Discovery Island",
  tipo: "Tematico",
  acesso: "Ao lado da Flame Tree Barbecue, com decoraÃ§Ã£o de fauna e flora local",
  precoMedio: 22,
  destaque: "Pratos temÃ¡ticos inspirados na natureza. NÃ£o deixe de experimentar o peixe grelhado com legumes locais.",
  latitude: 28.3614,
  longitude: -81.5905,
},

{
  nome: "Creature Comforts",
  regiao: "Discovery Island",
  tipo: "Conforto",
  acesso: "Entre as lojas principais, prÃ³ximo ao caminho para Africa",
  precoMedio: 15,
  destaque: "CafÃ©s, bolos e bebidas em estilo Starbucks. NÃ£o deixe de experimentar o muffin de banana com crumble de canela.",
  latitude: 28.3610,
  longitude: -81.5900,
},
{
  nome: "Island Eats",
  regiao: "Discovery Island",
  tipo: "Economico",
  acesso: "Perto do Tree of Life Garden",
  precoMedio: 13,
  destaque: "Snacks e refeiÃ§Ãµes rÃ¡pidas em Ã¡rea sombreada. NÃ£o deixe de experimentar os nachos com carne moÃ­da e molho agridoce.",
  latitude: 28.3612,
  longitude: -81.5903,
},
{
  nome: "Discovery Greens",
  regiao: "Discovery Island",
  tipo: "Saudavel",
  acesso: "AtrÃ¡s da loja Island Mercantile",
  precoMedio: 17,
  destaque: "Bowls e wraps com ingredientes frescos. NÃ£o deixe de provar o bowl de quinoa com frango grelhado e vegetais salteados.",
  latitude: 28.3613,
  longitude: -81.5904,
},

// Pandora â€“ The World of Avatar
{
  nome: "Satuâ€™li Canteen",
 regiao: "Pandora",
   tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atraÃ§Ã£o Flight of Passage",
  precoMedio: 30,
  destaque: "Comida inspirada em Pandora com apresentaÃ§Ã£o artÃ­stica. NÃ£o deixe de experimentar o bowl de carne grelhada com batata doce roxa.",
  latitude: 28.3595,
  longitude: -81.5886,
},
{
  nome: "Pongu Pongu",
 regiao: "Pandora",
   tipo: "Tematico",
  acesso: "Ao lado da entrada de Naâ€™vi River Journey",
  precoMedio: 13,
  destaque: "Bebidas exÃ³ticas e doces coloridos. NÃ£o deixe de pedir o Pongu Lumpia â€“ rolinho de abacaxi e cream cheese.",
  latitude: 28.3594,
  longitude: -81.5888,
},
{
  nome: "Avatar Comfort Eats",
 regiao: "Pandora",
   tipo: "Conforto",
  acesso: "PrÃ³ximo Ã  ponte de entrada de Pandora, em quiosque com vista para o rio",
  precoMedio: 15,
  destaque: "Snacks reconfortantes, como muffins de banana, cookies temÃ¡ticos e wraps. NÃ£o deixe de experimentar o wrap quente de frango com molho de ervas.",
  latitude: 28.3593,
  longitude: -81.5887,
},
{
  nome: "Pandora Quick Snacks",
 regiao: "Pandora",
   tipo: "Economico",
  acesso: "Ao lado do quiosque de souvenirs Windtraders",
  precoMedio: 10,
  destaque: "Snacks e bebidas geladas para recarregar rÃ¡pido. NÃ£o deixe de provar o sanduÃ­che frio com mix de folhas e peito de peru.",
  latitude: 28.3596,
  longitude: -81.5885,
},
{
  nome: "Na'vi Greens",
 regiao: "Pandora",
   tipo: "Saudavel",
  acesso: "AtrÃ¡s do Satuâ€™li Canteen, prÃ³ximo ao jardim bio-luminescente",
  precoMedio: 14,
  destaque: "Saladas, bowls naturais e sucos energizantes. NÃ£o deixe de experimentar o bowl de quinoa com frutas tropicais e castanhas.",
  latitude: 28.3597,
  longitude: -81.5884,
},


// Africa
{
  nome: "Tusker House Restaurant",
  regiao: "Africa",
  tipo: "Tematico",
  acesso: "PrÃ³ximo Ã  Harambe Market e Safari",
  precoMedio: 46,
  destaque: "Buffet africano com personagens Disney. NÃ£o deixe de experimentar o frango com molho de amendoim e arroz jollof.",
  latitude: 28.3590,
  longitude: -81.5930,
},
{
  nome: "Savannah Eats",
  regiao: "Africa",
  tipo: "Economico",
  acesso: "Ao lado do Harambe Market",
  precoMedio: 12,
  destaque: "Snacks e pratos rÃ¡pidos para um almoÃ§o rÃ¡pido. NÃ£o deixe de experimentar a samosa de vegetais.",
  latitude: 28.3592,
  longitude: -81.5933,
},

{
  nome: "Harambe Market",
  regiao: "Africa",
  tipo: ["Classico", "Americano"],
    acesso: "Ao lado da entrada da atraÃ§Ã£o Kilimanjaro Safaris",
  precoMedio: 24,
  destaque: "Comida de rua africana servida em estaÃ§Ãµes ao ar livre. NÃ£o deixe de pedir a linguiÃ§a grelhada com molho picante e arroz.",
  latitude: 28.3588,
  longitude: -81.5932,
},
{
  nome: "Zuriâ€™s Sweets Shop",
  regiao: "Africa",
  tipo: "Conforto",
  acesso: "Ao lado do Harambe Fruit Market",
  precoMedio: 14,
  destaque: "Doces africanos, bolos e chocolates artesanais. NÃ£o deixe de experimentar o brownie de chocolate com pimenta rosa.",
  latitude: 28.3591,
  longitude: -81.5929,
},
{
  nome: "Harambe Fruit Market",
  regiao: "Africa",
  tipo: "Saudavel",
  acesso: "Em frente Ã  saÃ­da da Kilimanjaro Safaris",
  precoMedio: 10,
  destaque: "Frutas frescas e sucos naturais. NÃ£o deixe de provar a salada de frutas com limÃ£o e hortelÃ£.",
  latitude: 28.3589,
  longitude: -81.5931,
},

// Asia
{
  nome: "Yak & Yeti Restaurant",
  regiao: "Asia",
  tipo: ["Classico", "Americano"],
    acesso: "Entre Kali River Rapids e Maharajah Jungle Trek",
  precoMedio: 32,
  destaque: "Pratos asiÃ¡ticos variados em ambiente temÃ¡tico. NÃ£o deixe de experimentar o arroz frito com camarÃ£o e vegetais.",
  latitude: 28.3580,
  longitude: -81.5915,
},
{
  nome: "Asian Flavors",
  regiao: "Asia",
  tipo: "Tematico",
  acesso: "Ao lado do Yak & Yeti Restaurant, decoraÃ§Ã£o asiÃ¡tica",
  precoMedio: 20,
  destaque: "Comida temÃ¡tica de paÃ­ses asiÃ¡ticos. NÃ£o deixe de experimentar o curry tailandÃªs de camarÃ£o.",
  latitude: 28.3582,
  longitude: -81.5917,
},

{
  nome: "Anandapur Ice Cream Truck",
  regiao: "Asia",
  tipo: "Conforto",
  acesso: "Em frente Ã  atraÃ§Ã£o Expedition Everest",
  precoMedio: 9,
  destaque: "Sorvetes refrescantes em caminhÃ£o temÃ¡tico. NÃ£o deixe de experimentar o sorvete de coco com calda de frutas vermelhas.",
  latitude: 28.3579,
  longitude: -81.5916,
},
{
  nome: "Yak & Yeti Local Foods CafÃ©",
  regiao: "Asia",
  tipo: "Economico",
  acesso: "Ao lado do Yak & Yeti Restaurant",
  precoMedio: 15,
  destaque: "Pratos asiÃ¡ticos rÃ¡pidos como noodles e arroz. NÃ£o deixe de pedir o frango teriyaki com arroz frito.",
  latitude: 28.3581,
  longitude: -81.5914,
},
{
  nome: "Asia Greens",
  regiao: "Asia",
  tipo: "Saudavel",
  acesso: "PrÃ³ximo ao caminho para o teatro do UP! A Great Bird Adventure",
  precoMedio: 16,
  destaque: "Saladas e wraps com sabores orientais. NÃ£o deixe de experimentar a salada de pepino com molho agridoce.",
  latitude: 28.3578,
  longitude: -81.5913,
},

// DinoLand U.S.A.
{
  nome: "Restaurantosaurus",
  regiao: "DinoLand U.S.A.",
  tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atraÃ§Ã£o DINOSAUR",
  precoMedio: 22,
  destaque: "Lanches clÃ¡ssicos americanos com ambiente de escavaÃ§Ã£o. NÃ£o deixe de experimentar o hambÃºrguer com batata waffle.",
  latitude: 28.3570,
  longitude: -81.5890,
},

{
  nome: "DinoLand Cafe",
  regiao: "DinoLand U.S.A.",
  tipo: "Tematico",
  acesso: "Ao lado do Restaurantosaurus, decoraÃ§Ã£o jurÃ¡ssica",
  precoMedio: 18,
  destaque: "Pratos temÃ¡ticos do tempo dos dinossauros. NÃ£o deixe de experimentar o frango crocante do T-Rex.",
  latitude: 28.3571,
  longitude: -81.5891,
},

{
  nome: "Trilo-Bites",
  regiao: "DinoLand U.S.A.",
  tipo: "Conforto",
  acesso: "Perto da entrada da ponte de Discovery Island",
  precoMedio: 10,
  destaque: "Snacks fritos e bebidas geladas. NÃ£o deixe de experimentar as loaded chips com cheddar derretido.",
  latitude: 28.3569,
  longitude: -81.5889,
},
{
  nome: "Dino Diner",
  regiao: "DinoLand U.S.A.",
  tipo: "Economico",
  acesso: "Ao lado do Fossil Fun Games",
  precoMedio: 9,
  destaque: "Cachorros-quentes e salgados rÃ¡pidos. NÃ£o deixe de provar o corn dog crocante com molho ranch.",
  latitude: 28.3568,
  longitude: -81.5888,
},
{
  nome: "Dino Greens",
  regiao: "DinoLand U.S.A.",
  tipo: "Saudavel",
  acesso: "PrÃ³ximo Ã  Ã¡rea de recreaÃ§Ã£o The Boneyard",
  precoMedio: 15,
  destaque: "Wraps e snacks naturais com toque jurÃ¡ssico. NÃ£o deixe de experimentar o wrap de atum com rÃºcula.",
  latitude: 28.3567,
  longitude: -81.5887,
},


  ];
