// src/logic/blocos/parques/Disney/CafeDisney.ts

export const cafesDisney = [

  // MainStreet
{
  nome: "Main Street Bakery",
  regiao: "MainStreet",
  tipo: "Tematico",
  acesso: "Ao lado da loja Emporium, na entrada do parque",
  precoMedio: 14,
  destaque: "O principal ponto para começar o dia, com cafés especiais e doces clássicos. Não deixe de experimentar o cinnamon roll quente com glacê de baunilha.",
  latitude: 28.4186,
  longitude: -81.5821,
},
{
  nome: "The Plaza Restaurant",
  regiao: "MainStreet",
  tipo: ["Classico", "Americano"],
  acesso: "Ao final da Main Street, com vista direta para o castelo",
  precoMedio: 20,
  destaque: "Café da manhã servido à mesa com pratos completos e vista mágica. Não deixe de pedir os waffles do Mickey com frutas e chantilly.",
  latitude: 28.4189,
  longitude: -81.5826,
},
{
  nome: "Casey’s Corner (Breakfast Menu)",
  regiao: "MainStreet",
  tipo: "Conforto",
  acesso: "Virando à esquerda antes do castelo",
  precoMedio: 13,
  destaque: "Abre cedo com opções como pão de queijo, croissants e chocolate quente. Não deixe de experimentar o cachorro-quente matinal com ovos mexidos e queijo.",
  latitude: 28.4187,
  longitude: -81.5824,
},
{
  nome: "Plaza Ice Cream Parlor (Early Hours)",
  regiao: "MainStreet",
  tipo: "Economico",
  acesso: "Ao lado do Casey’s Corner",
  precoMedio: 10,
  destaque: "Serve sorvetes e waffles de manhã durante horários de pico. Não deixe de experimentar o sundae com waffle quentinho e sorvete de baunilha.",
  latitude: 28.4188,
  longitude: -81.5825,
},
{
  nome: "Early Morning Emporium Cart",
  regiao: "MainStreet",
  tipo: "Saudavel",
  acesso: "Em frente à loja Emporium",
  precoMedio: 9,
  destaque: "Carrinho com frutas frescas, sucos e barras energéticas. Não deixe de experimentar o mix de frutas com mel orgânico.",
  latitude: 28.4185,
  longitude: -81.5820,
},

// Adventureland
{
  nome: "Aloha Isle (Early Option)",
  regiao: "Adventureland",
  tipo: "Conforto",
  acesso: "Em frente à Tiki Room",
  precoMedio: 9,
  destaque: "Para um café tropical, com Dole Whip gelado e suco natural. Não deixe de experimentar a versão de abacaxi com granola matinal.",
  latitude: 28.4177,
  longitude: -81.5840,
},
{
  nome: "Tropical Mornings Cart",
  regiao: "Adventureland",
  tipo: "Saudavel",
  acesso: "Entre The Magic Carpets of Aladdin e Swiss Family Treehouse",
  precoMedio: 10,
  destaque: "Carrinho com frutas, banana chips e água de coco. Não deixe de experimentar o bowl de frutas tropicais com chia.",
  latitude: 28.4179,
  longitude: -81.5842,
},
{
  nome: "Jungle Java Express",
  regiao: "Adventureland",
  tipo: "Tematico",
  acesso: "Ao lado da Jungle Cruise",
  precoMedio: 11,
  destaque: "Café da manhã estilo expedição com muffins, chá e café forte. Não deixe de provar o muffin de banana com canela.",
  latitude: 28.4180,
  longitude: -81.5843,
},
{
  nome: "Skipper Canteen (Breakfast Hours)",
  regiao: "Adventureland",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Jungle Cruise",
  precoMedio: 21,
  destaque: "Serve pratos matinais em estilo internacional. Não deixe de experimentar os ovos com curry suave e torradas com abacate.",
  latitude: 28.4181,
  longitude: -81.5844,
},
{
  nome: "Adventure Bites",
  regiao: "Adventureland",
  tipo: "Economico",
  acesso: "Próximo à ponte para Frontierland",
  precoMedio: 8,
  destaque: "Mini sanduíches, leite e frutas. Não deixe de experimentar o wrap frio de ovos com queijo cheddar.",
  latitude: 28.4176,
  longitude: -81.5838,
},

// Frontierland
{
  nome: "Westward Ho",
  regiao: "Frontierland",
  tipo: "Economico",
  acesso: "Em frente à Country Bear Jamboree",
  precoMedio: 10,
  destaque: "Café rápido com muffins, chocolate quente e milho cozido. Não deixe de experimentar o muffin de blueberry com café.",
  latitude: 28.4175,
  longitude: -81.5851,
},
{
  nome: "Pecos Bill (Breakfast Items)",
  regiao: "Frontierland",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Splash Mountain",
  precoMedio: 18,
  destaque: "Pratos completos estilo café sulista. Não deixe de experimentar os ovos com linguiça, hash browns e panquecas.",
  latitude: 28.4174,
  longitude: -81.5853,
},
{
  nome: "Cowpoke Café Cart",
  regiao: "Frontierland",
  tipo: "Saudavel",
  acesso: "Próximo à ponte de Adventureland",
  precoMedio: 9,
  destaque: "Barra de proteína, iogurte grego e banana. Não deixe de experimentar o parfait de frutas vermelhas.",
  latitude: 28.4173,
  longitude: -81.5850,
},
{
  nome: "Frontier Snacks",
  regiao: "Frontierland",
  tipo: "Conforto",
  acesso: "Perto da Tom Sawyer Island",
  precoMedio: 13,
  destaque: "Pretzels recheados, cookies e sucos. Não deixe de experimentar o pretzel recheado de ovos mexidos e queijo.",
  latitude: 28.4172,
  longitude: -81.5849,
},
{
  nome: "Golden Trail Morning",
  regiao: "Frontierland",
  tipo: "Tematico",
  acesso: "Próximo ao trilho do trem",
  precoMedio: 12,
  destaque: "Sanduíches no estilo cowboy, leite e panqueca enrolada. Não deixe de experimentar o rolinho de panqueca recheado com ovo e bacon.",
  latitude: 28.4171,
  longitude: -81.5848,
},

// LibertySquare
{
  nome: "Liberty Snacks",
  regiao: "LibertySquare",
  tipo: "Economico",
  acesso: "Próximo ao Liberty Square Riverboat",
  precoMedio: 12,
  destaque: "Pretzels recheados, donuts e bebidas quentes. Não deixe de experimentar o pretzel recheado com cream cheese e o chá de maçã.",
  latitude: 28.4193,
  longitude: -81.5831,
},
{
  nome: "Columbia Harbour House (Breakfast Menu)",
  regiao: "LibertySquare",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado do Hall of Presidents",
  precoMedio: 19,
  destaque: "Pratos de café da manhã colonial americano. Não deixe de experimentar os waffles com calda de maçã.",
  latitude: 28.4196,
  longitude: -81.5833,
},
{
  nome: "Liberty Tree Café",
  regiao: "LibertySquare",
  tipo: "Conforto",
  acesso: "Perto da Haunted Mansion",
  precoMedio: 14,
  destaque: "Pães doces, muffins e cappuccino cremoso. Não deixe de experimentar o muffin de maçã com canela.",
  latitude: 28.4190,
  longitude: -81.5834,
},
{
  nome: "Freedom Fruit Stand",
  regiao: "LibertySquare",
  tipo: "Saudavel",
  acesso: "Atrás da Liberty Tree Tavern",
  precoMedio: 9,
  destaque: "Bananas, maçãs, barras saudáveis e sucos. Não deixe de experimentar o combo de frutas com granola e mel.",
  latitude: 28.4192,
  longitude: -81.5835,
},
{
  nome: "Colonial Morning Cart",
  regiao: "LibertySquare",
  tipo: "Tematico",
  acesso: "Ao lado da entrada da Liberty Square",
  precoMedio: 11,
  destaque: "Bolos coloniais e bebida de especiarias. Não deixe de experimentar o bolo de milho com mel e canela.",
  latitude: 28.4191,
  longitude: -81.5838,
},

// Fantasyland
{
  nome: "Gaston’s Tavern",
  regiao: "Fantasyland",
  tipo: "Conforto",
  acesso: "Ao lado da atração Under the Sea – Journey of the Little Mermaid",
  precoMedio: 14,
  destaque: "Ambiente rústico com doces gigantes. Não deixe de provar o cinnamon roll do Gaston com calda quente.",
  latitude: 28.4211,
  longitude: -81.5809,
},
{
  nome: "The Friar’s Nook",
  regiao: "Fantasyland",
  tipo: "Economico",
  acesso: "Próximo ao Prince Charming Regal Carrousel",
  precoMedio: 13,
  destaque: "Serve cafés e mac and cheese matinal. Não deixe de experimentar o croissant com queijo derretido.",
  latitude: 28.4198,
  longitude: -81.5817,
},
{
  nome: "Pinocchio Village Haus",
  regiao: "Fantasyland",
  tipo: "Saudavel",
  acesso: "Ao lado do It’s a Small World",
  precoMedio: 18,
  destaque: "Flatbreads leves, cafés e frutas. Não deixe de experimentar o flatbread com ovos mexidos e espinafre.",
  latitude: 28.4195,
  longitude: -81.5820,
},
{
  nome: "Enchanted Café",
  regiao: "Fantasyland",
  tipo: "Tematico",
  acesso: "Entre Peter Pan’s Flight e Mickey’s PhilharMagic",
  precoMedio: 11,
  destaque: "Donuts mágicos e chocolate quente com chantilly. Não deixe de experimentar o donut em formato do Mickey com cobertura colorida.",
  latitude: 28.4196,
  longitude: -81.5816,
},
{
  nome: "Cinderella's Royal Breakfast",
  regiao: "Fantasyland",
  tipo: ["Classico", "Americano"],
  acesso: "Dentro do Castelo da Cinderela",
  precoMedio: 22,
  destaque: "Café da manhã real com ovos, bacon, waffles e frutas. Não deixe de experimentar os ovos mexidos do Mickey.",
  latitude: 28.4194,
  longitude: -81.5812,
},


// Tomorrowland
{
  nome: "The Lunching Pad",
  regiao: "Tomorrowland",
  tipo: "Economico",
  acesso: "Na base da Astro Orbiter",
  precoMedio: 11,
  destaque: "Snacks rápidos e cafés para os apressados. Não deixe de experimentar o pretzel recheado com cream cheese e o café gelado.",
  latitude: 28.4201,
  longitude: -81.5793,
},
{
  nome: "Cosmic Ray’s Starlight Café",
  regiao: "Tomorrowland",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente à Buzz Lightyear",
  precoMedio: 20,
  destaque: "Refeições rápidas em ambiente musical. Não deixe de pedir o combo de ovos mexidos, bacon e torrada.",
  latitude: 28.4200,
  longitude: -81.5792,
},
{
  nome: "Orbital Express Cart",
  regiao: "Tomorrowland",
  tipo: "Saudavel",
  acesso: "Entre a entrada da Space Mountain e o Speedway",
  precoMedio: 10,
  destaque: "Wraps frios, sucos e barras energéticas. Não deixe de experimentar o wrap de ovo com espinafre e queijo feta.",
  latitude: 28.4202,
  longitude: -81.5794,
},
{
  nome: "Tomorrow Morning Fuel",
  regiao: "Tomorrowland",
  tipo: "Tematico",
  acesso: "Ao lado do Tomorrowland Terrace",
  precoMedio: 13,
  destaque: "Lanches futuristas com cafés especiais. Não deixe de experimentar o pão doce de galáxia recheado com creme azul.",
  latitude: 28.4203,
  longitude: -81.5795,
},
{
  nome: "Starry Start Café",
  regiao: "Tomorrowland",
  tipo: "Conforto",
  acesso: "Próximo à entrada lateral do Space Ranger Spin",
  precoMedio: 12,
  destaque: "Opções matinais como panquecas e chá com limão. Não deixe de experimentar o sanduíche de ovo com bacon e queijo em pão de brioche.",
  latitude: 28.4204,
  longitude: -81.5796,
},
// World Showcase
{
  nome: "Les Halles Boulangerie-Patisserie",
  regiao: "World Showcase",
  tipo: ["Classico", "Americano"],
  acesso: "Pavilhão da França – entrada pela lateral, antes do Remy’s Ratatouille Adventure",
  precoMedio: 16,
  destaque: "Padaria francesa com doces frescos e cafés artesanais. Não deixe de experimentar o croissant de amêndoas com café au lait.",
  latitude: 28.3705,
  longitude: -81.5502,
},
{
  nome: "Kringla Bakeri Og Kafe",
  regiao: "World Showcase",
  tipo: "Tematico",
  acesso: "Pavilhão da Noruega – ao lado da loja de Frozen",
  precoMedio: 15,
  destaque: "Cafeteria norueguesa com bolos típicos e bebidas quentes. Não deixe de experimentar o School Bread com cobertura de coco.",
  latitude: 28.3707,
  longitude: -81.5490,
},
{
  nome: "Sunshine Seasons Cart – Showcase",
  regiao: "World Showcase",
  tipo: "Saudavel",
  acesso: "Pavilhão dos EUA – ao lado do American Adventure",
  precoMedio: 10,
  destaque: "Frutas frescas, iogurte e granola. Não deixe de experimentar o potinho de frutas vermelhas com mel.",
  latitude: 28.3710,
  longitude: -81.5505,
},
{
  nome: "Tangierine Café – Breakfast Corner",
  regiao: "World Showcase",
  tipo: "Conforto",
  acesso: "Pavilhão do Marrocos – entrada lateral",
  precoMedio: 12,
  destaque: "Wraps leves com toque marroquino. Não deixe de experimentar o wrap de ovos com hortelã e queijo de cabra.",
  latitude: 28.3708,
  longitude: -81.5493,
},
{
  nome: "La Cantina de San Angel (Early Hours)",
  regiao: "World Showcase",
  tipo: "Economico",
  acesso: "Pavilhão do México – na beira do lago, ao lado da pirâmide",
  precoMedio: 11,
  destaque: "Café matinal com bolos de milho e sucos tropicais. Não deixe de experimentar o pan de elote com chocolate quente.",
  latitude: 28.3711,
  longitude: -81.5475,
},

// World Discovery
{
  nome: "Connections Café",
  regiao: "World Discovery",
  tipo: "Tematico",
  acesso: "Ao lado do Creations Shop",
  precoMedio: 14,
  destaque: "Cafeteria moderna com pães e bebidas quentes. Não deixe de experimentar o pão de canela com cobertura de maple.",
  latitude: 28.3741,
  longitude: -81.5487,
},
{
  nome: "Space 220 Lounge (Breakfast Menu)",
  regiao: "World Discovery",
  tipo: ["Classico", "Americano"],
  acesso: "Entrada pela Mission: SPACE",
  precoMedio: 26,
  destaque: "Café da manhã em ambiente de estação espacial. Não deixe de experimentar os ovos mexidos com batata trufada.",
  latitude: 28.3735,
  longitude: -81.5480,
},
{
  nome: "Mission Fuel Station",
  regiao: "World Discovery",
  tipo: "Economico",
  acesso: "Entre Test Track e Mission: SPACE",
  precoMedio: 10,
  destaque: "Snacks rápidos e bebidas energéticas. Não deixe de experimentar a barra de cereal com leite e banana.",
  latitude: 28.3749,
  longitude: -81.5482,
},
{
  nome: "Nova Greens Express",
  regiao: "World Discovery",
  tipo: "Saudavel",
  acesso: "Ao lado da Guardians of the Galaxy",
  precoMedio: 12,
  destaque: "Bowls matinais com frutas, chia e granola. Não deixe de experimentar o bowl de morango com linhaça.",
  latitude: 28.3748,
  longitude: -81.5477,
},
{
  nome: "Test Track Café",
  regiao: "World Discovery",
  tipo: "Conforto",
  acesso: "Na saída da atração Test Track",
  precoMedio: 13,
  destaque: "Café americano clássico com muffin, café e bacon. Não deixe de experimentar o combo matinal com panqueca recheada.",
  latitude: 28.3751,
  longitude: -81.5483,
},

// World Celebration
{
  nome: "EPCOT Brew House",
  regiao: "World Celebration",
  tipo: "Tematico",
  acesso: "Ao lado do Connections Eatery",
  precoMedio: 15,
  destaque: "Cervejas leves, bolos e pães. Não deixe de experimentar o pão de aveia com mel e café artesanal.",
  latitude: 28.3743,
  longitude: -81.5488,
},
{
  nome: "Garden Start Snacks",
  regiao: "World Celebration",
  tipo: "Economico",
  acesso: "Em frente ao Dreamers Point",
  precoMedio: 9,
  destaque: "Snacks, barrinhas e suco natural. Não deixe de experimentar o muffin integral com banana e aveia.",
  latitude: 28.3745,
  longitude: -81.5486,
},
{
  nome: "Central Café",
  regiao: "World Celebration",
  tipo: ["Classico", "Americano"],
  acesso: "Entre o centro e a entrada do World Showcase",
  precoMedio: 18,
  destaque: "Combo tradicional de ovos, bacon e pão artesanal. Não deixe de experimentar o sanduíche de ovo no pão brioche.",
  latitude: 28.3740,
  longitude: -81.5489,
},
{
  nome: "Fresh Start Salads",
  regiao: "World Celebration",
  tipo: "Saudavel",
  acesso: "Ao lado da Creations Shop",
  precoMedio: 12,
  destaque: "Saladas de frutas e smoothies leves. Não deixe de experimentar o smoothie de manga com gengibre.",
  latitude: 28.3746,
  longitude: -81.5484,
},
{
  nome: "Inspiration Grounds",
  regiao: "World Celebration",
  tipo: "Conforto",
  acesso: "Caminho para o World Showcase",
  precoMedio: 13,
  destaque: "Waffles, suco de laranja e café com leite. Não deixe de experimentar os waffles em formato do Mickey com calda de frutas.",
  latitude: 28.3742,
  longitude: -81.5485,
},

// World Nature
{
  nome: "Sunshine Seasons",
  regiao: "World Nature",
  tipo: ["Classico", "Americano"],
  acesso: "Dentro do pavilhão The Land",
  precoMedio: 20,
  destaque: "Buffet com opções de café, pães e ovos frescos. Não deixe de experimentar o combo de ovos mexidos, batata e torrada.",
  latitude: 28.3724,
  longitude: -81.5472,
},
{
  nome: "The Land Cart",
  regiao: "World Nature",
  tipo: "Economico",
  acesso: "Entrada do pavilhão The Land",
  precoMedio: 10,
  destaque: "Bananas, sucos e muffins matinais. Não deixe de experimentar o combo com suco de maçã e muffin de mirtilo.",
  latitude: 28.3723,
  longitude: -81.5473,
},
{
  nome: "Green Bowl Express",
  regiao: "World Nature",
  tipo: "Saudavel",
  acesso: "Entre The Land e The Seas",
  precoMedio: 13,
  destaque: "Bowls frescos com chia e frutas orgânicas. Não deixe de experimentar o bowl com manga, kiwi e iogurte natural.",
  latitude: 28.3725,
  longitude: -81.5471,
},
{
  nome: "Coral Reef Early Café",
  regiao: "World Nature",
  tipo: "Tematico",
  acesso: "Ao lado da atração The Seas with Nemo & Friends",
  precoMedio: 17,
  destaque: "Ambiente subaquático com café gourmet. Não deixe de pedir o pão doce recheado de creme com cobertura crocante.",
  latitude: 28.3720,
  longitude: -81.5469,
},
{
  nome: "Nature Morning Stand",
  regiao: "World Nature",
  tipo: "Conforto",
  acesso: "Saída do The Land, próximo à subida para o The Seas",
  precoMedio: 12,
  destaque: "Wraps leves com ovos e chá verde gelado. Não deixe de experimentar o wrap de ovo com cogumelo e tomate seco.",
  latitude: 28.3726,
  longitude: -81.5470,
},
// Hollywood Boulevard
{
  nome: "The Trolley Car Café",
  regiao: "Hollywood Boulevard",
  tipo: "Tematico",
  acesso: "À direita da entrada principal do parque",
  precoMedio: 14,
  destaque: "Cafeteria no estilo Starbucks com doces e cafés fortes. Não deixe de experimentar o famoso carrot cake cookie com café gelado.",
  latitude: 28.3571,
  longitude: -81.5582,
},
{
  nome: "Hollywood & Vine (Breakfast Buffet)",
  regiao: "Hollywood Boulevard",
  tipo: ["Classico", "Americano"],
  acesso: "Perto do centro do parque, próximo à Animation Courtyard",
  precoMedio: 39,
  destaque: "Buffet com personagens Disney e pratos clássicos de café. Não deixe de experimentar os waffles do Mickey com chantilly e frutas.",
  latitude: 28.3574,
  longitude: -81.5581,
},
{
  nome: "Sunset Boulevard Cart (Early Stand)",
  regiao: "Hollywood Boulevard",
  tipo: "Economico",
  acesso: "Início da Sunset Blvd, antes da loja Legends of Hollywood",
  precoMedio: 10,
  destaque: "Carrinho com frutas, bolinhos e bebidas matinais. Não deixe de experimentar o croissant de queijo com café com leite.",
  latitude: 28.3572,
  longitude: -81.5583,
},
{
  nome: "Hollywood Morning Market",
  regiao: "Hollywood Boulevard",
  tipo: "Saudavel",
  acesso: "Perto da Mickey’s of Hollywood",
  precoMedio: 11,
  destaque: "Opções leves como iogurte com granola e smoothies. Não deixe de experimentar o copo de frutas com mel e hortelã.",
  latitude: 28.3573,
  longitude: -81.5580,
},
{
  nome: "Studio Scoops AM",
  regiao: "Hollywood Boulevard",
  tipo: "Conforto",
  acesso: "Ao lado da loja Celebrity 5 & 10",
  precoMedio: 13,
  destaque: "Sorvetes leves, waffles e café expresso. Não deixe de experimentar o sundae com waffle e frutas vermelhas.",
  latitude: 28.3570,
  longitude: -81.5584,
},

// Echo Lake
{
  nome: "Backlot Express (Breakfast Menu)",
  regiao: "Echo Lake",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da atração Star Tours",
  precoMedio: 17,
  destaque: "Combo americano com ovos, bacon e panqueca. Não deixe de experimentar o combo matinal com batata rústica e café preto.",
  latitude: 28.3580,
  longitude: -81.5588,
},
{
  nome: "Echo Lake Café Cart",
  regiao: "Echo Lake",
  tipo: "Economico",
  acesso: "Próximo ao lago, em frente ao Indiana Jones Epic Stunt Spectacular",
  precoMedio: 9,
  destaque: "Pretzels recheados, muffins e suco de laranja. Não deixe de experimentar o pretzel de cream cheese aquecido.",
  latitude: 28.3578,
  longitude: -81.5590,
},
{
  nome: "Dinosaur Gertie’s Snacks",
  regiao: "Echo Lake",
  tipo: "Conforto",
  acesso: "Dentro da escultura do dinossauro verde",
  precoMedio: 10,
  destaque: "Sorvetes e snacks matinais inusitados. Não deixe de experimentar o sorvete de baunilha com granola e banana.",
  latitude: 28.3582,
  longitude: -81.5592,
},
{
  nome: "Echo Lake Healthy Start",
  regiao: "Echo Lake",
  tipo: "Saudavel",
  acesso: "Em frente à loja Frozen Fractal Gifts",
  precoMedio: 11,
  destaque: "Wraps com ovos, frutas frescas e chás gelados. Não deixe de experimentar o wrap de clara com espinafre e queijo branco.",
  latitude: 28.3581,
  longitude: -81.5591,
},
{
  nome: "50’s Prime Time Café (Breakfast Special)",
  regiao: "Echo Lake",
  tipo: "Tematico",
  acesso: "Atrás do Echo Lake",
  precoMedio: 25,
  destaque: "Café no estilo retrô com pratos clássicos americanos. Não deixe de experimentar a panqueca com bacon caramelizado.",
  latitude: 28.3579,
  longitude: -81.5593,
},

// Grand Avenue
{
  nome: "PizzeRizzo (Early Hours)",
  regiao: "Grand Avenue",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Muppet Courtyard",
  precoMedio: 15,
  destaque: "Serve café da manhã simples com toque italiano. Não deixe de experimentar o pão italiano recheado com ovos e presunto.",
  latitude: 28.3576,
  longitude: -81.5603,
},
{
  nome: "Muppet Morning Snacks",
  regiao: "Grand Avenue",
  tipo: "Tematico",
  acesso: "Em frente à entrada da Muppet*Vision 3D",
  precoMedio: 9,
  destaque: "Cookies temáticos e bebidas matinais. Não deixe de experimentar o cookie do Kermit com chocolate e matcha.",
  latitude: 28.3577,
  longitude: -81.5601,
},
{
  nome: "Studio Start Cart",
  regiao: "Grand Avenue",
  tipo: "Economico",
  acesso: "Na lateral da Grand Avenue",
  precoMedio: 8,
  destaque: "Opções rápidas como barras, café e frutas. Não deixe de experimentar a banana com pasta de amendoim.",
  latitude: 28.3575,
  longitude: -81.5602,
},
{
  nome: "Rizzo's Wake Up",
  regiao: "Grand Avenue",
  tipo: "Saudavel",
  acesso: "Atrás do PizzeRizzo",
  precoMedio: 12,
  destaque: "Wraps frios e smoothies verdes. Não deixe de experimentar o smoothie de espinafre com abacaxi e limão.",
  latitude: 28.3574,
  longitude: -81.5600,
},
{
  nome: "Grand Cappuccino Stop",
  regiao: "Grand Avenue",
  tipo: "Conforto",
  acesso: "Entre a entrada da área Muppet e Star Wars",
  precoMedio: 13,
  destaque: "Cappuccinos, donuts e croissants. Não deixe de experimentar o croissant de queijo e presunto.",
  latitude: 28.3573,
  longitude: -81.5604,
},

// Star Wars: Galaxy’s Edge
{
  nome: "Ronto Roasters (Breakfast Wrap)",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Droid Depot",
  precoMedio: 14,
  destaque: "Wraps quentes com toque galáctico. Não deixe de experimentar o Ronto Wrap matinal com ovos, linguiça e queijo.",
  latitude: 28.3586,
  longitude: -81.5614,
},
{
  nome: "Galactic Pastries",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Conforto",
  acesso: "Próximo ao Black Spire Outpost Market",
  precoMedio: 12,
  destaque: "Doces e pães confortáveis em ambiente galáctico. Não deixe de experimentar o pão doce de baunilha com formato de planeta.",
  latitude: 28.3588,
  longitude: -81.5610,
},

{
  nome: "Milk Stand (Early Hours)",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Tematico",
  acesso: "Em frente à atração Rise of the Resistance",
  precoMedio: 9,
  destaque: "Leite azul e verde gelados ideais para começar o dia fora da Terra. Não deixe de experimentar o leite azul com essência de frutas tropicais.",
  latitude: 28.3587,
  longitude: -81.5613,
},
{
  nome: "Black Spire Fruit Stand",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Saudavel",
  acesso: "Perto da saída do mercado",
  precoMedio: 11,
  destaque: "Snacks naturais e frutas alienígenas. Não deixe de experimentar o mix de frutas com nome temático e suco concentrado.",
  latitude: 28.3584,
  longitude: -81.5615,
},
{
  nome: "Resistance Fuel Cart",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Economico",
  acesso: "Ao lado da entrada da Rise of the Resistance",
  precoMedio: 8,
  destaque: "Barras energéticas e bebidas práticas. Não deixe de experimentar a barra de proteína 'Galaxy Crunch'.",
  latitude: 28.3583,
  longitude: -81.5612,
},

// Toy Story Land
{
  nome: "Woody’s Lunch Box (Breakfast Menu)",
  regiao: "Toy Story Land",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Slinky Dog Dash",
  precoMedio: 16,
  destaque: "Café criativo com pratos infantis e saborosos. Não deixe de experimentar o breakfast bowl com ovos mexidos e queijo derretido.",
  latitude: 28.3591,
  longitude: -81.5621,
},
{
  nome: "Toy Box Treats",
  regiao: "Toy Story Land",
  tipo: "Tematico",
  acesso: "Perto do Alien Swirling Saucers",
  precoMedio: 10,
  destaque: "Doces coloridos e bebidas matinais. Não deixe de experimentar o donut do Buzz com glacê roxo e estrelas comestíveis.",
  latitude: 28.3592,
  longitude: -81.5622,
},
{
  nome: "Green Army Patrol Snacks",
  regiao: "Toy Story Land",
  tipo: "Conforto",
  acesso: "Atrás da parada do Green Army Men",
  precoMedio: 11,
  destaque: "Snacks militares como panquecas enroladas e suco. Não deixe de experimentar o enroladinho de panqueca recheado de frutas.",
  latitude: 28.3593,
  longitude: -81.5623,
},
{
  nome: "Buzz’s Morning Fuel",
  regiao: "Toy Story Land",
  tipo: "Saudavel",
  acesso: "Na entrada da área temática",
  precoMedio: 12,
  destaque: "Smoothies verdes e wraps com ovo. Não deixe de experimentar o smoothie do Buzz com abacaxi, espinafre e hortelã.",
  latitude: 28.3590,
  longitude: -81.5620,
},
{
  nome: "Andy's Fruit Stop",
  regiao: "Toy Story Land",
  tipo: "Economico",
  acesso: "Na lateral do Woody’s Lunch Box",
  precoMedio: 8,
  destaque: "Maçãs, bananas e sucos naturais. Não deixe de experimentar o copo com mix de frutas picadas.",
  latitude: 28.3589,
  longitude: -81.5619,
},

// Animation Courtyard
{
  nome: "Animators Café",
  regiao: "Animation Courtyard",
  tipo: ["Classico", "Americano"],
  acesso: "Próximo à entrada do Disney Junior Dance Party",
  precoMedio: 14,
  destaque: "Ambiente artístico com combos de café e sanduíche. Não deixe de experimentar o sanduíche de ovo com queijo e o capuccino.",
  latitude: 28.3568,
  longitude: -81.5598,
},
{
  nome: "Courtyard Snacks",
  regiao: "Animation Courtyard",
  tipo: "Economico",
  acesso: "Ao lado do Walt Disney Presents",
  precoMedio: 9,
  destaque: "Cookies, leite e cereais. Não deixe de experimentar o cookie do Mickey com gotas de chocolate.",
  latitude: 28.3567,
  longitude: -81.5597,
},
{
  nome: "Toon Start Stand",
  regiao: "Animation Courtyard",
  tipo: "Tematico",
  acesso: "Em frente à estátua do Mickey Feiticeiro",
  precoMedio: 10,
  destaque: "Mini donuts, chocolate quente e animação para crianças. Não deixe de experimentar o donut colorido com granulado mágico.",
  latitude: 28.3569,
  longitude: -81.5599,
},
{
  nome: "Morning Animation Fuel",
  regiao: "Animation Courtyard",
  tipo: "Conforto",
  acesso: "Ao lado do One Man’s Dream",
  precoMedio: 11,
  destaque: "Wraps simples e leite com achocolatado. Não deixe de experimentar o wrap de ovo com queijo cheddar.",
  latitude: 28.3566,
  longitude: -81.5596,
},
{
  nome: "Artist’s Greens",
  regiao: "Animation Courtyard",
  tipo: "Saudavel",
  acesso: "Fundos do pavilhão de animação",
  precoMedio: 12,
  destaque: "Saladas matinais com frutas e sementes. Não deixe de experimentar a salada de iogurte com granola e morango.",
  latitude: 28.3565,
  longitude: -81.5595,
},

// Sunset Boulevard
{
  nome: "Sunset Ranch Market (Breakfast Hours)",
  regiao: "Sunset Boulevard",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Rock ‘n’ Roller Coaster",
  precoMedio: 16,
  destaque: "Café estilo americano com ovos, bacon e panquecas. Não deixe de experimentar o combo de panqueca com calda de frutas vermelhas.",
  latitude: 28.3556,
  longitude: -81.5599,
},
{
  nome: "Rosie’s All-American Café (Early Menu)",
  regiao: "Sunset Boulevard",
  tipo: "Tematico",
  acesso: "Em frente ao Hollywood Scoops",
  precoMedio: 13,
  destaque: "Café com cara de diner americano dos anos 50. Não deixe de experimentar o sanduíche de café da manhã com ovo e salsicha.",
  latitude: 28.3557,
  longitude: -81.5598,
},
{
  nome: "Sunset Fruit Cart",
  regiao: "Sunset Boulevard",
  tipo: "Saudavel",
  acesso: "Na descida para a Tower of Terror",
  precoMedio: 9,
  destaque: "Frutas frescas, iogurtes e sucos naturais. Não deixe de experimentar o copo com morango, uva e melancia gelada.",
  latitude: 28.3555,
  longitude: -81.5600,
},
{
  nome: "Hollywood Scoops (Breakfast Specials)",
  regiao: "Sunset Boulevard",
  tipo: "Conforto",
  acesso: "Ao lado da Sunset Ranch Market",
  precoMedio: 12,
  destaque: "Sorvetes e waffles em porções matinais. Não deixe de experimentar o waffle com bola de sorvete e calda de morango.",
  latitude: 28.3554,
  longitude: -81.5601,
},
{
  nome: "Sunset Start Express",
  regiao: "Sunset Boulevard",
  tipo: "Economico",
  acesso: "Ao lado da loja Once Upon a Time",
  precoMedio: 10,
  destaque: "Café preto, bolos simples e cereais. Não deixe de experimentar o bolo de banana com nozes.",
  latitude: 28.3553,
  longitude: -81.5602,
},

// Oasis
{
  nome: "Rainforest Café (Breakfast Menu)",
  regiao: "Oasis",
  tipo: "Tematico",
  acesso: "Na entrada principal, antes dos portões do parque",
  precoMedio: 28,
  destaque: "Ambiente de floresta com pratos tropicais no café da manhã. Não deixe de experimentar os waffles de banana com calda de caramelo.",
  latitude: 28.3598,
  longitude: -81.5912,
},
{
  nome: "Oasis Snacks Cart",
  regiao: "Oasis",
  tipo: "Economico",
  acesso: "Logo após a entrada, à esquerda do mapa interativo",
  precoMedio: 9,
  destaque: "Snacks rápidos como frutas, muffins e sucos. Não deixe de experimentar o copo de frutas com mel e limão.",
  latitude: 28.3599,
  longitude: -81.5910,
},
{
  nome: "Tropical Roots Café",
  regiao: "Oasis",
  tipo: "Saudavel",
  acesso: "Próximo à ponte de acesso à Discovery Island",
  precoMedio: 11,
  destaque: "Smoothies naturais e wraps leves. Não deixe de experimentar o smoothie de manga com gengibre e hortelã.",
  latitude: 28.3597,
  longitude: -81.5911,
},
{
  nome: "Morning Jungle Cart",
  regiao: "Oasis",
  tipo: "Conforto",
  acesso: "Ao lado da loja Garden Gate Gifts",
  precoMedio: 10,
  destaque: "Cookies artesanais, chocolate quente e croissants. Não deixe de experimentar o croissant recheado de creme de avelã.",
  latitude: 28.3596,
  longitude: -81.5913,
},
{
  nome: "Explorer’s Start",
  regiao: "Oasis",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente ao lago central da Oasis",
  precoMedio: 14,
  destaque: "Combo de ovos, batatas e pão grelhado. Não deixe de experimentar o sanduíche quente de ovo e cheddar.",
  latitude: 28.3595,
  longitude: -81.5914,
},

// Discovery Island
{
  nome: "Creature Comforts",
  regiao: "Discovery Island",
  tipo: "Tematico",
  acesso: "Entre as principais lojas do centro da ilha",
  precoMedio: 14,
  destaque: "Café no estilo Starbucks com doces e bebidas especiais. Não deixe de experimentar o muffin de banana com crumble de canela.",
  latitude: 28.3610,
  longitude: -81.5900,
},
{
  nome: "Flame Tree Barbecue (Breakfast Items)",
  regiao: "Discovery Island",
  tipo: ["Classico", "Americano"],
  acesso: "Com vista para o lago, próximo à ponte para Asia",
  precoMedio: 18,
  destaque: "Refeições matinais ao estilo sulista. Não deixe de experimentar os ovos com linguiça e pão de milho.",
  latitude: 28.3608,
  longitude: -81.5902,
},
{
  nome: "Island Eats Stand",
  regiao: "Discovery Island",
  tipo: "Economico",
  acesso: "Próximo ao Tree of Life Garden",
  precoMedio: 9,
  destaque: "Snacks rápidos e frutas para começar o dia leve. Não deixe de experimentar o copo de uvas e maçã verde.",
  latitude: 28.3612,
  longitude: -81.5903,
},
{
  nome: "Discovery Greens",
  regiao: "Discovery Island",
  tipo: "Saudavel",
  acesso: "Atrás da loja Island Mercantile",
  precoMedio: 12,
  destaque: "Bowls, wraps e sucos verdes. Não deixe de experimentar o bowl de quinoa com kiwi e melão.",
  latitude: 28.3613,
  longitude: -81.5904,
},
{
  nome: "Nature's Morning",
  regiao: "Discovery Island",
  tipo: "Conforto",
  acesso: "Perto da ponte para Africa",
  precoMedio: 11,
  destaque: "Cookies e pães matinais em espaço sombreado. Não deixe de experimentar o pão doce de maçã com canela.",
  latitude: 28.3609,
  longitude: -81.5899,
},

// Pandora – The World of Avatar
{
  nome: "Satu’li Canteen (Breakfast Bowl)",
  regiao: "Pandora – The World of Avatar",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da atração Flight of Passage",
  precoMedio: 22,
  destaque: "Pratos inspirados em Pandora para café da manhã. Não deixe de experimentar o bowl de batata doce com ovos e molho de ervas.",
  latitude: 28.3595,
  longitude: -81.5886,
},
{
  nome: "Pongu Pongu (Early Hours)",
  regiao: "Pandora – The World of Avatar",
  tipo: "Tematico",
  acesso: "Ao lado da entrada de Na’vi River Journey",
  precoMedio: 12,
  destaque: "Bebidas exóticas e pães doces alienígenas. Não deixe de experimentar o Pongu Lumpia – rolinho de abacaxi e cream cheese.",
  latitude: 28.3594,
  longitude: -81.5888,
},
{
  nome: "Pandora Fruit Cart",
  regiao: "Pandora – The World of Avatar",
  tipo: "Saudavel",
  acesso: "Próximo à ponte de entrada em Pandora",
  precoMedio: 10,
  destaque: "Frutas alienígenas (inspiradas em Earth) e sucos naturais. Não deixe de experimentar o copo de frutas com pitaya e manga.",
  latitude: 28.3593,
  longitude: -81.5885,
},
{
  nome: "Avatar Morning Fuel",
  regiao: "Pandora – The World of Avatar",
  tipo: "Economico",
  acesso: "Ao lado do Satu’li Canteen",
  precoMedio: 9,
  destaque: "Barras, wraps frios e chá de Pandora. Não deixe de experimentar o wrap de ovo com batata-doce e queijo feta.",
  latitude: 28.3592,
  longitude: -81.5884,
},
{
  nome: "Neytiri’s Start",
  regiao: "Pandora – The World of Avatar",
  tipo: "Conforto",
  acesso: "No jardim de entrada de Pandora",
  precoMedio: 11,
  destaque: "Pães doces temáticos e bebidas azuis. Não deixe de experimentar o muffin de mirtilo com essência de flor azul.",
  latitude: 28.3591,
  longitude: -81.5883,
},

// Africa
{
  nome: "Tusker House Restaurant (Character Breakfast)",
  regiao: "Africa",
  tipo: "Tematico",
  acesso: "Perto da entrada do Kilimanjaro Safaris",
  precoMedio: 45,
  destaque: "Buffet com personagens e pratos africanos. Não deixe de experimentar o arroz jollof com ovos mexidos e banana-da-terra.",
  latitude: 28.3590,
  longitude: -81.5930,
},
{
  nome: "Harambe Fruit Market",
  regiao: "Africa",
  tipo: "Saudavel",
  acesso: "Em frente à saída da Kilimanjaro Safaris",
  precoMedio: 9,
  destaque: "Frutas frescas, barras naturais e água de coco. Não deixe de experimentar o copo com melancia, manga e laranja.",
  latitude: 28.3589,
  longitude: -81.5931,
},
{
  nome: "Zuri’s Sweets Shop (Morning Menu)",
  regiao: "Africa",
  tipo: "Conforto",
  acesso: "Ao lado do Harambe Market",
  precoMedio: 12,
  destaque: "Doces africanos, bolos e café aromático. Não deixe de experimentar o bolo de especiarias com cobertura de baunilha.",
  latitude: 28.3591,
  longitude: -81.5929,
},
{
  nome: "Harambe Market (Breakfast Bowls)",
  regiao: "Africa",
  tipo: ["Classico", "Americano"],
  acesso: "Pátio central de Harambe Market",
  precoMedio: 16,
  destaque: "Pratos completos com toque africano. Não deixe de experimentar o bowl de ovos com frango marinado e molho tanzaniano.",
  latitude: 28.3588,
  longitude: -81.5932,
},
{
  nome: "Savanna Sunrise Cart",
  regiao: "Africa",
  tipo: "Economico",
  acesso: "Próximo à ponte de acesso a Asia",
  precoMedio: 8,
  destaque: "Pães simples, chá e frutas secas. Não deixe de experimentar o pão doce de banana com gengibre.",
  latitude: 28.3587,
  longitude: -81.5933,
},

// Asia
{
  nome: "Yak & Yeti Local Foods Café (Breakfast)",
  regiao: "Asia",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado do Yak & Yeti Restaurant",
  precoMedio: 15,
  destaque: "Pratos asiáticos para começar o dia. Não deixe de experimentar o sanduíche de ovo com salsicha asiática e molho agridoce.",
  latitude: 28.3581,
  longitude: -81.5914,
},
{
  nome: "Anandapur Ice Cream Truck (Morning Sweets)",
  regiao: "Asia",
  tipo: "Conforto",
  acesso: "Em frente à Expedition Everest",
  precoMedio: 10,
  destaque: "Sorvetes e doces refrescantes. Não deixe de experimentar o sorvete de coco com calda de maracujá.",
  latitude: 28.3579,
  longitude: -81.5916,
},
{
  nome: "Asia Greens",
  regiao: "Asia",
  tipo: "Saudavel",
  acesso: "Caminho para Maharajah Jungle Trek",
  precoMedio: 11,
  destaque: "Wraps, saladas e chás com especiarias. Não deixe de experimentar o wrap de ovo com espinafre e curry leve.",
  latitude: 28.3578,
  longitude: -81.5913,
},
{
  nome: "Tea Cart Asia",
  regiao: "Asia",
  tipo: "Tematico",
  acesso: "Em frente ao templo da Jungle Trek",
  precoMedio: 9,
  destaque: "Chás asiáticos, bolinhos de arroz e pão de mel. Não deixe de experimentar o bolinho de arroz doce com recheio de ameixa.",
  latitude: 28.3577,
  longitude: -81.5917,
},
{
  nome: "Expedition Start",
  regiao: "Asia",
  tipo: "Economico",
  acesso: "Próximo à entrada da Expedition Everest",
  precoMedio: 8,
  destaque: "Snacks rápidos como muffins e frutas secas. Não deixe de experimentar o muffin de chá verde com gotas de chocolate.",
  latitude: 28.3576,
  longitude: -81.5918,
},

// DinoLand U.S.A.
{
  nome: "Restaurantosaurus (Breakfast Combo)",
  regiao: "DinoLand U.S.A.",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da atração DINOSAUR",
  precoMedio: 14,
  destaque: "Refeição completa com tema de escavação. Não deixe de experimentar o combo com ovo, bacon e batata smile.",
  latitude: 28.3570,
  longitude: -81.5890,
},
{
  nome: "Dino Diner",
  regiao: "DinoLand U.S.A.",
  tipo: "Economico",
  acesso: "Perto do Fossil Fun Games",
  precoMedio: 9,
  destaque: "Wraps matinais e sucos de fruta. Não deixe de experimentar o wrap de ovo com queijo cheddar e ketchup doce.",
  latitude: 28.3568,
  longitude: -81.5888,
},
{
  nome: "Trilo-Bites (Breakfast Menu)",
  regiao: "DinoLand U.S.A.",
  tipo: "Conforto",
  acesso: "Perto da entrada para a ponte de Discovery Island",
  precoMedio: 10,
  destaque: "Snacks fritos e cafés fortes. Não deixe de experimentar os mini churros com cobertura de açúcar e canela.",
  latitude: 28.3569,
  longitude: -81.5889,
},
{
  nome: "Dino Greens",
  regiao: "DinoLand U.S.A.",
  tipo: "Saudavel",
  acesso: "Próximo ao playground The Boneyard",
  precoMedio: 11,
  destaque: "Wraps de proteína magra e bowls com frutas. Não deixe de experimentar o bowl de iogurte com morango e castanhas.",
  latitude: 28.3567,
  longitude: -81.5887,
},
{
  nome: "Fossil Fuel Cart",
  regiao: "DinoLand U.S.A.",
  tipo: "Tematico",
  acesso: "Ao lado da entrada do Primeval Whirl",
  precoMedio: 8,
  destaque: "Cereal, leite e cookies temáticos. Não deixe de experimentar o cookie jurássico recheado com chocolate branco.",
  latitude: 28.3566,
  longitude: -81.5886,
},



  ];