// src/logic/blocos/parques/Disney/CafeDisney.ts

export const cafesDisney = [

// MainStreet
{
  nome: "Main Street Bakery",
  regiao: "MainStreet",
  tipo: "Tematico",
  acesso: "Ao lado da loja Emporium, na entrada do parque",
  precoMedio: 14,
  destaque: "O principal ponto para começar o dia, com cafés especiais e doces clássicos. Não deixe de experimentar o cinnamon roll quente com glacê de baunilha.",
  latitude: 28.4186,
  longitude: -81.5821,
},
{
  nome: "The Plaza Restaurant",
  regiao: "MainStreet",
  tipo: ["Classico", "Americano"],
  acesso: "Ao final da Main Street, com vista direta para o castelo",
  precoMedio: 20,
  destaque: "Café da manhã servido à mesa com pratos completos e vista mágica. Não deixe de pedir os waffles do Mickey com frutas e chantilly.",
  latitude: 28.4189,
  longitude: -81.5826,
},
{
  nome: "Casey’s Corner",
  regiao: "MainStreet",
  tipo: "Conforto",
  acesso: "Virando à esquerda antes do castelo",
  precoMedio: 13,
  destaque: "Hot dogs clássicos, batatas fritas e bebidas. Ideal para um lanche rápido ao longo do dia.",
  latitude: 28.4187,
  longitude: -81.5824,
},
{
  nome: "Plaza Ice Cream Parlor",
  regiao: "MainStreet",
  tipo: "Economico",
  acesso: "Ao lado do Casey’s Corner",
  precoMedio: 10,
  destaque: "Sorvetes e waffles frescos com vista para o castelo. Experimente o sundae com waffle e calda quente.",
  latitude: 28.4188,
  longitude: -81.5825,
},
{
  nome: "Main Street Refreshment Cart",
  regiao: "MainStreet",
  tipo: "Saudavel",
  acesso: "Em frente à loja Emporium",
  precoMedio: 9,
  destaque: "Carrinho com frutas frescas, sucos e snacks leves. Ideal para começar o dia de forma prática.",
  latitude: 28.4185,
  longitude: -81.5820,
},

// Adventureland
{
  nome: "Aloha Isle",
  regiao: "Adventureland",
  tipo: "Conforto",
  acesso: "Em frente à Enchanted Tiki Room",
  precoMedio: 9,
  destaque: "Famoso Dole Whip e bebidas tropicais geladas. Experimente o clássico abacaxi com sorvete.",
  latitude: 28.4177,
  longitude: -81.5840,
},
{
  nome: "Sunshine Tree Terrace",
  regiao: "Adventureland",
  tipo: "Conforto",
  acesso: "Perto da Swiss Family Treehouse, caminho para a ponte rumo à Frontierland",
  precoMedio: 6,
  destaque: "Soft-serve (Citrus Swirl e DOLE Whip), bebidas geladas e café.",
  latitude: 28.4179,
  longitude: -81.5841,
},
{
  nome: "Tortuga Tavern",
  regiao: "Adventureland",
  tipo: ["Classico", "Americano"],
  acesso: "Próximo à atração Pirates of the Caribbean",
  precoMedio: 15,
  destaque: "Restaurante sazonal com opções tex-mex e sanduíches. Experimente o sanduíche de peru com batatas fritas.",
  latitude: 28.4178,
  longitude: -81.5843,
},

// Frontierland
{
  nome: "Westward Ho",
  regiao: "Frontierland",
  tipo: "Economico",
  acesso: "Em frente à Country Bear Jamboree",
  precoMedio: 10,
  destaque: "Café rápido com muffins, chocolate quente e milho cozido. Ideal para um lanche rápido pela manhã.",
  latitude: 28.4175,
  longitude: -81.5851,
},
{
  nome: "Golden Oak Outpost",
  regiao: "Frontierland",
  tipo: "Economico",
  acesso: "No caminho entre Frontierland e Adventureland",
  precoMedio: 10,
  destaque: "Fritas waffle, frango empanado e doces sazonais. Ótimo ponto para uma pausa rápida.",
  latitude: 28.4176,
  longitude: -81.5856,
},
{
  nome: "Pecos Bill Tall Tale Inn and Café",
  regiao: "Frontierland",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Splash Mountain",
  precoMedio: 18,
  destaque: "Comida tex-mex e pratos fartos. Experimente os tacos e o bowl de arroz com frango.",
  latitude: 28.4174,
  longitude: -81.5853,
},

// LibertySquare
{
  nome: "Columbia Harbour House",
  regiao: "LibertySquare",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado do Hall of Presidents",
  precoMedio: 19,
  destaque: "Pratos de frutos do mar e sanduíches de frango. Ambiente tranquilo no segundo andar.",
  latitude: 28.4196,
  longitude: -81.5833,
},
{
  nome: "Liberty Tree Tavern",
  regiao: "LibertySquare",
  tipo: "Conforto",
  acesso: "Perto da Haunted Mansion",
  precoMedio: 14,
  destaque: "Refeições americanas tradicionais em ambiente colonial. Destaque para o bolo de maçã com sorvete.",
  latitude: 28.4190,
  longitude: -81.5834,
},
{
  nome: "Sleepy Hollow Refreshments",
  regiao: "LibertySquare",
  tipo: "Economico",
  acesso: "Ao lado da entrada de Liberty Square, perto da ponte do castelo",
  precoMedio: 12,
  destaque: "Waffles do Mickey e sanduíches de frutas. Experimente o waffle com morango e chantilly.",
  latitude: 28.4191,
  longitude: -81.5838,
},

// Fantasyland
{
  nome: "Gaston’s Tavern",
  regiao: "Fantasyland",
  tipo: "Conforto",
  acesso: "Perto da atração Under the Sea – Journey of the Little Mermaid",
  precoMedio: 14,
  destaque: "Doces gigantes e bebidas temáticas. Experimente o famoso cinnamon roll do Gaston.",
  latitude: 28.4211,
  longitude: -81.5809,
},
{
  nome: "The Friar’s Nook",
  regiao: "Fantasyland",
  tipo: "Economico",
  acesso: "Próximo ao Prince Charming Regal Carrousel",
  precoMedio: 13,
  destaque: "Snacks e café, com pratos quentes simples. Experimente o mac and cheese com bacon.",
  latitude: 28.4198,
  longitude: -81.5817,
},
{
  nome: "Pinocchio Village Haus",
  regiao: "Fantasyland",
  tipo: "Classico",
  acesso: "Ao lado da atração It’s a Small World",
  precoMedio: 18,
  destaque: "Flatbreads e pratos italianos rápidos. Experimente o flatbread caprese e o combo infantil.",
  latitude: 28.4195,
  longitude: -81.5820,
},
{
  nome: "Cheshire Café",
  regiao: "Fantasyland",
  tipo: "Tematico",
  acesso: "Perto da atração Mad Tea Party",
  precoMedio: 11,
  destaque: "Cafés e doces temáticos de Alice. Experimente o Cheshire Cat Tail e o café gelado.",
  latitude: 28.4196,
  longitude: -81.5816,
},
{
  nome: "Cinderella’s Royal Table",
  regiao: "Fantasyland",
  tipo: ["Classico", "Americano"],
  acesso: "Dentro do Castelo da Cinderela",
  precoMedio: 22,
  destaque: "Café da manhã com princesas e pratos requintados. Experimente os waffles do Mickey com frutas frescas.",
  latitude: 28.4194,
  longitude: -81.5812,
},

// Tomorrowland
{
  nome: "The Lunching Pad",
  regiao: "Tomorrowland",
  tipo: "Economico",
  acesso: "Na base da Astro Orbiter",
  precoMedio: 11,
  destaque: "Snacks rápidos e bebidas geladas para uma pausa prática. Experimente o pretzel recheado com cream cheese.",
  latitude: 28.4201,
  longitude: -81.5793,
},
{
  nome: "Cosmic Ray’s Starlight Café",
  regiao: "Tomorrowland",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente à Buzz Lightyear",
  precoMedio: 20,
  destaque: "Quick service com opções variadas (frango, hambúrgueres, bowls) ao som do Sonny Eclipse.",
  latitude: 28.4200,
  longitude: -81.5792,
},
{
  nome: "Revive by Joffrey’s Coffee & Tea Company",
  regiao: "Tomorrowland",
  tipo: "Saudavel",
  acesso: "Entre a entrada da Space Mountain e o Tomorrowland Speedway",
  precoMedio: 10,
  destaque: "Cafés, chás gelados e pastries para começar o dia com energia.",
  latitude: 28.4202,
  longitude: -81.5794,
},
{
  nome: "Energy Bytes",
  regiao: "Tomorrowland",
  tipo: "Tematico",
  acesso: "Ao lado da TRON Lightcycle / Run",
  precoMedio: 13,
  destaque: "Lanches futuristas como dumplings, bites doces e bebidas especiais.",
  latitude: 28.4206,
  longitude: -81.5786,
},
{
  nome: "Auntie Gravity’s Galactic Goodies",
  regiao: "Tomorrowland",
  tipo: "Conforto",
  acesso: "Próximo ao Space Ranger Spin",
  precoMedio: 12,
  destaque: "Shakes, sorvetes soft-serve e bebidas geladas.",
  latitude: 28.4204,
  longitude: -81.5796,
},

// World Showcase
{
  nome: "Les Halles Boulangerie-Patisserie",
  regiao: "World Showcase",
  tipo: ["Classico", "Americano"],
  acesso: "Pavilhão da França – entrada pela lateral, antes do Remy’s Ratatouille Adventure",
  precoMedio: 16,
  destaque: "Padaria francesa com doces frescos, sanduíches frios e cafés artesanais.",
  latitude: 28.3705,
  longitude: -81.5502,
},
{
  nome: "Kringla Bakeri Og Kafe",
  regiao: "World Showcase",
  tipo: "Tematico",
  acesso: "Pavilhão da Noruega – ao lado da loja de Frozen",
  precoMedio: 15,
  destaque: "Clássicos noruegueses como School Bread e cafés quentes.",
  latitude: 28.3707,
  longitude: -81.5490,
},
{
  nome: "Fife & Drum Tavern",
  regiao: "World Showcase",
  tipo: "Saudavel",
  acesso: "Pavilhão dos EUA – ao lado do American Adventure",
  precoMedio: 10,
  destaque: "Bebidas, snacks rápidos e sorvetes; parada prática no centro do World Showcase.",
  latitude: 28.3710,
  longitude: -81.5505,
},
{
  nome: "Tangierine Café",
  regiao: "World Showcase",
  tipo: "Conforto",
  acesso: "Pavilhão do Marrocos – entrada lateral",
  precoMedio: 12,
  destaque: "Pratos leves de inspiração marroquina, wraps e doces típicos.",
  latitude: 28.3708,
  longitude: -81.5493,
},
{
  nome: "La Cantina de San Angel",
  regiao: "World Showcase",
  tipo: "Economico",
  acesso: "Pavilhão do México – na beira do lago, ao lado da pirâmide",
  precoMedio: 11,
  destaque: "Quick service mexicano com tacos e nachos; ótimo para uma refeição rápida.",
  latitude: 28.3711,
  longitude: -81.5475,
},

// World Discovery
{
  nome: "Connections Café",
  regiao: "World Discovery",
  tipo: "Tematico",
  acesso: "Ao lado do Creations Shop",
  precoMedio: 14,
  destaque: "Starbucks do EPCOT com cafés especiais e pastries.",
  latitude: 28.3741,
  longitude: -81.5487,
},
{
  nome: "Space 220 Lounge",
  regiao: "World Discovery",
  tipo: ["Classico", "Americano"],
  acesso: "Entrada pela Mission: SPACE",
  precoMedio: 26,
  destaque: "Lounge temático com petiscos e coquetéis em ambiente de estação espacial.",
  latitude: 28.3735,
  longitude: -81.5480,
},
{
  nome: "Joffrey’s Coffee & Tea Company – Test Track",
  regiao: "World Discovery",
  tipo: "Economico",
  acesso: "Entre Test Track e Mission: SPACE",
  precoMedio: 10,
  destaque: "Cafés, donuts e chás gelados para recarregar as energias.",
  latitude: 28.3749,
  longitude: -81.5482,
},
{
  nome: "Refreshment Station",
  regiao: "World Discovery",
  tipo: "Saudavel",
  acesso: "Próximo ao Test Track",
  precoMedio: 12,
  destaque: "Bebidas frozen e snacks rápidos; parada refrescante.",
  latitude: 28.3750,
  longitude: -81.5481,
},
{
  nome: "Connections Eatery",
  regiao: "World Discovery",
  tipo: "Conforto",
  acesso: "Anexo ao Connections Café",
  precoMedio: 13,
  destaque: "Quick service moderno com bowls, sanduíches e sobremesas.",
  latitude: 28.3742,
  longitude: -81.5486,
},

// World Celebration
{
  nome: "Connections Eatery",
  regiao: "World Celebration",
  tipo: "Tematico",
  acesso: "Ao lado do Connections Café",
  precoMedio: 15,
  destaque: "Menu variado em espaço amplo e moderno, com vista para o hub central.",
  latitude: 28.3743,
  longitude: -81.5488,
},
{
  nome: "Club Cool",
  regiao: "World Celebration",
  tipo: "Economico",
  acesso: "Próximo ao Connections/Creations",
  precoMedio: 9,
  destaque: "Degustação de refrigerantes do mundo e bebidas geladas.",
  latitude: 28.3745,
  longitude: -81.5486,
},
{
  nome: "Connections Café",
  regiao: "World Celebration",
  tipo: ["Classico", "Americano"],
  acesso: "Integrado ao Connections Eatery",
  precoMedio: 18,
  destaque: "Cafés especiais (Starbucks) e pastries artesanais.",
  latitude: 28.3740,
  longitude: -81.5489,
},
{
  nome: "Joffrey’s Coffee & Tea Company – World Celebration",
  regiao: "World Celebration",
  tipo: "Saudavel",
  acesso: "Área central entre World Celebration e World Discovery",
  precoMedio: 12,
  destaque: "Cafés, chás e opções rápidas doces/salgadas.",
  latitude: 28.3746,
  longitude: -81.5484,
},
{
  nome: "Festival Market (sazonal)",
  regiao: "World Celebration",
  tipo: "Conforto",
  acesso: "Próximo ao Dreamers Point (quando em funcionamento)",
  precoMedio: 13,
  destaque: "Estandes sazonais dos festivais do EPCOT com snacks e bebidas temáticas.",
  latitude: 28.3742,
  longitude: -81.5485,
},

// World Nature
{
  nome: "Sunshine Seasons",
  regiao: "World Nature",
  tipo: ["Classico", "Americano"],
  acesso: "Dentro do pavilhão The Land",
  precoMedio: 20,
  destaque: "Praça de alimentação com opções variadas e saladas frescas.",
  latitude: 28.3724,
  longitude: -81.5472,
},
{
  nome: "Garden Grill Restaurant",
  regiao: "World Nature",
  tipo: "Economico",
  acesso: "No mezanino do The Land, acima do Sunshine Seasons",
  precoMedio: 10,
  destaque: "Restaurante giratório com personagens (refeições por período do dia); checar disponibilidade.",
  latitude: 28.3723,
  longitude: -81.5473,
},
{
  nome: "The Seas Snack Cart",
  regiao: "World Nature",
  tipo: "Saudavel",
  acesso: "Entre The Land e The Seas",
  precoMedio: 13,
  destaque: "Carrinho de snacks e bebidas próximo ao pavilhão The Seas.",
  latitude: 28.3725,
  longitude: -81.5471,
},
{
  nome: "Coral Reef Restaurant",
  regiao: "World Nature",
  tipo: "Tematico",
  acesso: "Ao lado da atração The Seas with Nemo & Friends",
  precoMedio: 17,
  destaque: "Restaurante com vista para o aquário; frutos do mar e pratos clássicos.",
  latitude: 28.3720,
  longitude: -81.5469,
},
{
  nome: "Joffrey’s Coffee & Tea Company – World Nature",
  regiao: "World Nature",
  tipo: "Conforto",
  acesso: "Caminho do The Land para The Seas",
  precoMedio: 12,
  destaque: "Cafés e chás gelados, além de donuts e pastries.",
  latitude: 28.3726,
  longitude: -81.5470,
},

// Hollywood Boulevard
{
  nome: "The Trolley Car Café",
  regiao: "Hollywood Boulevard",
  tipo: "Tematico",
  acesso: "À direita da entrada principal do parque",
  precoMedio: 14,
  destaque: "Starbucks do parque: cafés, pastries e o clássico carrot cake cookie.",
  latitude: 28.3571,
  longitude: -81.5582,
},
{
  nome: "Hollywood & Vine (Disney Junior Play n’ Dine – Breakfast)",
  regiao: "Hollywood Boulevard",
  tipo: ["Classico", "Americano"],
  acesso: "Perto do centro do parque, próximo à Animation Courtyard",
  precoMedio: 39,
  destaque: "Café da manhã com personagens Disney Junior (checar horários).",
  latitude: 28.3574,
  longitude: -81.5581,
},
{
  nome: "Hollywood Scoops",
  regiao: "Hollywood Boulevard",
  tipo: "Economico",
  acesso: "Início da Sunset Boulevard, próximo ao Theater of the Stars",
  precoMedio: 10,
  destaque: "Sorvetes, sundaes e waffles com bola de sorvete.",
  latitude: 28.3572,
  longitude: -81.5583,
},
{
  nome: "The Hollywood Brown Derby Lounge",
  regiao: "Hollywood Boulevard",
  tipo: "Saudavel",
  acesso: "Em frente ao The Hollywood Brown Derby",
  precoMedio: 11,
  destaque: "Lounge ao ar livre com petiscos e bebidas assinadas.",
  latitude: 28.3573,
  longitude: -81.5580,
},
{
  nome: "Market on Hollywood Boulevard",
  regiao: "Hollywood Boulevard",
  tipo: "Conforto",
  acesso: "Ao lado da loja Celebrity 5 & 10",
  precoMedio: 13,
  destaque: "Quiosque de snacks rápidos, bebidas e frutas sazonais.",
  latitude: 28.3570,
  longitude: -81.5584,
},

// Echo Lake
{
  nome: "Backlot Express",
  regiao: "Echo Lake",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da atração Star Tours",
  precoMedio: 17,
  destaque: "Quick service temático de cinema com sanduíches e bowls.",
  latitude: 28.3580,
  longitude: -81.5588,
},
{
  nome: "Epic Eats",
  regiao: "Echo Lake",
  tipo: "Economico",
  acesso: "Em frente ao Indiana Jones Epic Stunt Spectacular",
  precoMedio: 9,
  destaque: "Funnel cakes, milkshakes e bebidas geladas.",
  latitude: 28.3578,
  longitude: -81.5590,
},
{
  nome: "Dinosaur Gertie’s Ice Cream of Extinction",
  regiao: "Echo Lake",
  tipo: "Conforto",
  acesso: "Dentro da escultura do dinossauro verde",
  precoMedio: 10,
  destaque: "Sorvetes e floats; operação sazonal.",
  latitude: 28.3582,
  longitude: -81.5592,
},
{
  nome: "Dockside Diner",
  regiao: "Echo Lake",
  tipo: "Saudavel",
  acesso: "À beira do lago, barco azul",
  precoMedio: 11,
  destaque: "Hot dogs especiais, chips e bebidas; boas mesas externas.",
  latitude: 28.3581,
  longitude: -81.5591,
},
{
  nome: "50’s Prime Time Café",
  regiao: "Echo Lake",
  tipo: "Tematico",
  acesso: "Atrás do Echo Lake",
  precoMedio: 25,
  destaque: "Table service anos 50 com pratos clássicos (almoço e jantar).",
  latitude: 28.3579,
  longitude: -81.5593,
},

// Grand Avenue
{
  nome: "PizzeRizzo",
  regiao: "Grand Avenue",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Muppet Courtyard",
  precoMedio: 15,
  destaque: "Pizzas e saladas em ambiente amplo e temático.",
  latitude: 28.3576,
  longitude: -81.5603,
},
{
  nome: "BaseLine Tap House",
  regiao: "Grand Avenue",
  tipo: "Tematico",
  acesso: "Entrada da Grand Avenue (próximo ao pórtico)",
  precoMedio: 9,
  destaque: "Tap house californiana com pretzel gigante e tábua de frios.",
  latitude: 28.3577,
  longitude: -81.5601,
},
{
  nome: "Grand Avenue Market",
  regiao: "Grand Avenue",
  tipo: "Economico",
  acesso: "Na lateral da Grand Avenue",
  precoMedio: 8,
  destaque: "Quiosque de snacks, bebidas e cervejas.",
  latitude: 28.3575,
  longitude: -81.5602,
},
{
  nome: "Mama Melrose’s Ristorante Italiano",
  regiao: "Grand Avenue",
  tipo: "Saudavel",
  acesso: "Fundo da Grand Avenue",
  precoMedio: 12,
  destaque: "Table service italiano com massas e carnes (almoço e jantar).",
  latitude: 28.3574,
  longitude: -81.5600,
},
{
  nome: "Muppet*Vision 3D Cart",
  regiao: "Grand Avenue",
  tipo: "Conforto",
  acesso: "Entre a área Muppet e Grand Avenue",
  precoMedio: 13,
  destaque: "Carrinho com pipoca, bebidas e sorvetes (sazonal).",
  latitude: 28.3573,
  longitude: -81.5604,
},

// Star Wars: Galaxy’s Edge
{
  nome: "Ronto Roasters",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Droid Depot",
  precoMedio: 14,
  destaque: "Ronto Wraps e bebidas; há versões matinais em alguns dias.",
  latitude: 28.3586,
  longitude: -81.5614,
},
{
  nome: "Kat Saka’s Kettle",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Conforto",
  acesso: "Black Spire Outpost Market",
  precoMedio: 12,
  destaque: "Pipoca exótica e bebidas em cenário de mercado.",
  latitude: 28.3588,
  longitude: -81.5610,
},
{
  nome: "Milk Stand",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Tematico",
  acesso: "Próximo à entrada da Rise of the Resistance",
  precoMedio: 9,
  destaque: "Leite azul e verde gelados; opção clássica de Batuu.",
  latitude: 28.3587,
  longitude: -81.5613,
},
{
  nome: "Docking Bay 7 Food and Cargo",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Saudavel",
  acesso: "Atrás da Millennium Falcon: Smugglers Run",
  precoMedio: 11,
  destaque: "Pratos rápidos com temática galáctica; opções kids e vegetarianas.",
  latitude: 28.3584,
  longitude: -81.5615,
},
{
  nome: "Oga’s Cantina",
  regiao: "Star Wars: Galaxy’s Edge",
  tipo: "Economico",
  acesso: "Black Spire Outpost",
  precoMedio: 8,
  destaque: "Cantina com coquetéis especiais e ambiente imersivo (reserva recomendada).",
  latitude: 28.3583,
  longitude: -81.5612,
},
// Toy Story Land
{
  nome: "Woody’s Lunch Box",
  regiao: "Toy Story Land",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Slinky Dog Dash",
  precoMedio: 16,
  destaque: "Lanches criativos como totchos, sanduíches quentes e soups; opção kids e mobile order.",
  latitude: 28.3591,
  longitude: -81.5621,
},
{
  nome: "Roundup Rodeo BBQ",
  regiao: "Toy Story Land",
  tipo: "Tematico",
  acesso: "Entrada ao fundo da área, após o Alien Swirling Saucers",
  precoMedio: 35,
  destaque: "Table service em estilo ‘family-style’ com carnes defumadas, acompanhamentos e sobremesas temáticas.",
  latitude: 28.3593,
  longitude: -81.5624,
},
{
  nome: "Joffrey’s Coffee & Tea Company – Toy Story Land (próximo)",
  regiao: "Toy Story Land",
  tipo: "Conforto",
  acesso: "Kiosk mais próximo fica na transição para Pixar Place/Animation Courtyard",
  precoMedio: 10,
  destaque: "Cafés, chás gelados, donuts e pastries para uma pausa rápida.",
  latitude: 28.3588,
  longitude: -81.5618,
},

// Animation Courtyard
{
  nome: "Joffrey’s Coffee & Tea Company – Pixar Place",
  regiao: "Animation Courtyard",
  tipo: ["Classico", "Americano"],
  acesso: "Entrada de Pixar Place, perto do Meet & Greet (Edna Mode)",
  precoMedio: 14,
  destaque: "Cafés especiais, chás e donuts; ponto clássico para começar o dia.",
  latitude: 28.3569,
  longitude: -81.5599,
},
{
  nome: "Walt Disney Presents Cart",
  regiao: "Animation Courtyard",
  tipo: "Economico",
  acesso: "Ao lado do Walt Disney Presents",
  precoMedio: 9,
  destaque: "Carrinho com bebidas, pipoca e snacks rápidos.",
  latitude: 28.3567,
  longitude: -81.5597,
},

// Sunset Boulevard
{
  nome: "Fairfax Fare",
  regiao: "Sunset Boulevard",
  tipo: ["Classico", "Americano"],
  acesso: "Praça Sunset Ranch Market, em frente à Tower of Terror",
  precoMedio: 16,
  destaque: "Bowls e pratos rápidos em área coberta, boa rotatividade e mesas.",
  latitude: 28.3556,
  longitude: -81.5599,
},
{
  nome: "Rosie’s All-American Café",
  regiao: "Sunset Boulevard",
  tipo: "Tematico",
  acesso: "Praça Sunset Ranch Market, ao lado do Hollywood Scoops",
  precoMedio: 13,
  destaque: "Clássicos americanos como hambúrgueres, nuggets e saladas.",
  latitude: 28.3557,
  longitude: -81.5598,
},
{
  nome: "Anaheim Produce",
  regiao: "Sunset Boulevard",
  tipo: "Saudavel",
  acesso: "Descida para a Tower of Terror, lado esquerdo",
  precoMedio: 9,
  destaque: "Frutas frescas, sucos e snacks leves para refrescar.",
  latitude: 28.3555,
  longitude: -81.5600,
},
{
  nome: "Hollywood Scoops",
  regiao: "Sunset Boulevard",
  tipo: "Conforto",
  acesso: "Ao lado da Sunset Ranch Market",
  precoMedio: 12,
  destaque: "Sorvetes, sundaes e waffle com bola de sorvete.",
  latitude: 28.3554,
  longitude: -81.5601,
},
{
  nome: "Catalina Eddie’s",
  regiao: "Sunset Boulevard",
  tipo: "Economico",
  acesso: "Praça Sunset Ranch Market, próximo ao Theater of the Stars",
  precoMedio: 10,
  destaque: "Pizzas individuais, breadsticks e bebidas.",
  latitude: 28.3553,
  longitude: -81.5602,
},

// Oasis (Disney’s Animal Kingdom)
{
  nome: "Rainforest Café – Disney’s Animal Kingdom",
  regiao: "Oasis",
  tipo: "Tematico",
  acesso: "Na entrada principal, antes dos portões do parque",
  precoMedio: 28,
  destaque: "Ambiente de floresta com menu variado; acesso também pela área externa do parque.",
  latitude: 28.3598,
  longitude: -81.5912,
},
{
  nome: "Oasis Refreshment Cart",
  regiao: "Oasis",
  tipo: "Economico",
  acesso: "Logo após a entrada, à esquerda do mapa interativo",
  precoMedio: 9,
  destaque: "Água, refrigerantes, pipoca e snacks rápidos.",
  latitude: 28.3599,
  longitude: -81.5910,
},
{
  nome: "Tropical Roots Kiosk",
  regiao: "Oasis",
  tipo: "Saudavel",
  acesso: "Caminho em direção à ponte para Discovery Island",
  precoMedio: 11,
  destaque: "Smoothies, frutas e opções leves para começar o dia.",
  latitude: 28.3597,
  longitude: -81.5911,
},

// Discovery Island (Disney’s Animal Kingdom)
{
  nome: "Creature Comforts",
  regiao: "Discovery Island",
  tipo: "Tematico",
  acesso: "Entre as lojas do centro da ilha",
  precoMedio: 14,
  destaque: "Starbucks do parque: cafés, pastries e opções sazonais.",
  latitude: 28.3610,
  longitude: -81.5900,
},
{
  nome: "Flame Tree Barbecue",
  regiao: "Discovery Island",
  tipo: ["Classico", "Americano"],
  acesso: "Com vista para o lago, caminho para a ponte de Asia",
  precoMedio: 18,
  destaque: "Churrasco ao estilo sulista com áreas de deck sombreadas.",
  latitude: 28.3608,
  longitude: -81.5902,
},
{
  nome: "Isle of Java",
  regiao: "Discovery Island",
  tipo: "Economico",
  acesso: "Caminho para a ponte rumo à Asia (perto do Theater in the Wild)",
  precoMedio: 9,
  destaque: "Cafés, pastries e a famosa pipoca de zebra (sazonal).",
  latitude: 28.3612,
  longitude: -81.5903,
},
{
  nome: "Eight Spoon Café",
  regiao: "Discovery Island",
  tipo: "Saudavel",
  acesso: "Em frente à ponte para Asia",
  precoMedio: 12,
  destaque: "Baked mac & cheese (inclui versões com carne) e snacks rápidos.",
  latitude: 28.3613,
  longitude: -81.5904,
},
{
  nome: "Terra Treats",
  regiao: "Discovery Island",
  tipo: "Conforto",
  acesso: "Calçada do lago, sentido ponte para World Nature",
  precoMedio: 11,
  destaque: "Snacks sazonais, pizzas de fatia e bebidas geladas.",
  latitude: 28.3609,
  longitude: -81.5899,
},
// Pandora – The World of Avatar
{
  nome: "Satu’li Canteen",
  regiao: "Pandora – The World of Avatar",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da atração Flight of Passage",
  precoMedio: 22,
  destaque: "Pratos inspirados em Pandora com bowls personalizáveis, saladas e sobremesas exóticas.",
  latitude: 28.3595,
  longitude: -81.5886,
},
{
  nome: "Pongu Pongu",
  regiao: "Pandora – The World of Avatar",
  tipo: "Tematico",
  acesso: "Ao lado da entrada da Na’vi River Journey",
  precoMedio: 12,
  destaque: "Bebidas exóticas e o clássico Pongu Lumpia (rolinho de abacaxi e cream cheese).",
  latitude: 28.3594,
  longitude: -81.5888,
},
{
  nome: "Joffrey’s Coffee & Tea Company – Pandora",
  regiao: "Pandora – The World of Avatar",
  tipo: "Saudavel",
  acesso: "Próximo à ponte de entrada em Pandora",
  precoMedio: 10,
  destaque: "Cafés, chás gelados e smoothies tropicais para começar o dia em Pandora.",
  latitude: 28.3593,
  longitude: -81.5885,
},

// Africa
{
  nome: "Tusker House Restaurant",
  regiao: "Africa",
  tipo: "Tematico",
  acesso: "Perto da entrada do Kilimanjaro Safaris",
  precoMedio: 45,
  destaque: "Buffet com personagens e culinária africana; ambiente vibrante e familiar.",
  latitude: 28.3590,
  longitude: -81.5930,
},
{
  nome: "Harambe Fruit Market",
  regiao: "Africa",
  tipo: "Saudavel",
  acesso: "Em frente à saída da Kilimanjaro Safaris",
  precoMedio: 9,
  destaque: "Frutas frescas, snacks e bebidas geladas; ideal para uma pausa rápida.",
  latitude: 28.3589,
  longitude: -81.5931,
},
{
  nome: "Zuri’s Sweets Shop",
  regiao: "Africa",
  tipo: "Conforto",
  acesso: "Ao lado do Harambe Market",
  precoMedio: 12,
  destaque: "Doces, chocolates e confeitaria temática africana.",
  latitude: 28.3591,
  longitude: -81.5929,
},
{
  nome: "Harambe Market",
  regiao: "Africa",
  tipo: ["Classico", "Americano"],
  acesso: "Pátio central de Harambe Market",
  precoMedio: 16,
  destaque: "Pratos africanos e sanduíches com temperos locais; ambiente ao ar livre e animado.",
  latitude: 28.3588,
  longitude: -81.5932,
},
{
  nome: "Tamu Tamu Refreshments",
  regiao: "Africa",
  tipo: "Economico",
  acesso: "Próximo à ponte de acesso à Asia",
  precoMedio: 8,
  destaque: "Sorvetes, Dole Whip e bebidas geladas com toque tropical.",
  latitude: 28.3587,
  longitude: -81.5933,
},

// Asia
{
  nome: "Yak & Yeti Local Food Cafes",
  regiao: "Asia",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado do Yak & Yeti Restaurant",
  precoMedio: 15,
  destaque: "Quick service com pratos asiáticos e americanos; tigelas de arroz, sanduíches e sobremesas.",
  latitude: 28.3581,
  longitude: -81.5914,
},
{
  nome: "Anandapur Ice Cream Truck",
  regiao: "Asia",
  tipo: "Conforto",
  acesso: "Em frente à Expedition Everest",
  precoMedio: 10,
  destaque: "Sorvetes, floats e milkshakes em um caminhão artístico decorado.",
  latitude: 28.3579,
  longitude: -81.5916,
},
{
  nome: "Royal Anandapur Tea Company (Joffrey’s)",
  regiao: "Asia",
  tipo: "Saudavel",
  acesso: "Próximo à entrada do caminho para Maharajah Jungle Trek",
  precoMedio: 11,
  destaque: "Cafés e chás exclusivos com opções geladas e sazonais.",
  latitude: 28.3578,
  longitude: -81.5913,
},
{
  nome: "Yak & Yeti Restaurant",
  regiao: "Asia",
  tipo: "Tematico",
  acesso: "Centro da vila de Anandapur",
  precoMedio: 25,
  destaque: "Table service com pratos asiáticos e decoração rica em detalhes culturais.",
  latitude: 28.3577,
  longitude: -81.5917,
},
{
  nome: "Thirsty River Bar & Trek Snacks",
  regiao: "Asia",
  tipo: "Economico",
  acesso: "Próximo à entrada da Expedition Everest",
  precoMedio: 8,
  destaque: "Bebidas, cervejas e pequenos snacks ideais para um intervalo refrescante.",
  latitude: 28.3576,
  longitude: -81.5918,
},

// DinoLand U.S.A.
{
  nome: "Restaurantosaurus",
  regiao: "DinoLand U.S.A.",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da atração DINOSAUR",
  precoMedio: 14,
  destaque: "Refeições em ambiente temático de escavação; hambúrgueres, nuggets e saladas.",
  latitude: 28.3570,
  longitude: -81.5890,
},
{
  nome: "Dino Diner",
  regiao: "DinoLand U.S.A.",
  tipo: "Economico",
  acesso: "Perto do Fossil Fun Games",
  precoMedio: 9,
  destaque: "Wraps, hot dogs e bebidas; quiosque vintage e divertido.",
  latitude: 28.3568,
  longitude: -81.5888,
},
{
  nome: "Trilo-Bites",
  regiao: "DinoLand U.S.A.",
  tipo: "Conforto",
  acesso: "Perto da entrada para a ponte de Discovery Island",
  precoMedio: 10,
  destaque: "Snacks e bebidas geladas; experimente os Buffalo Chicken Chips.",
  latitude: 28.3569,
  longitude: -81.5889,
},
{
  nome: "Dino-Bite Snacks",
  regiao: "DinoLand U.S.A.",
  tipo: "Saudavel",
  acesso: "Ao lado da entrada do Restaurantosaurus",
  precoMedio: 11,
  destaque: "Sorvetes e cookies recheados; bom ponto para sobremesa rápida.",
  latitude: 28.3567,
  longitude: -81.5887,
},
{
  nome: "DinoLand Snacks Cart",
  regiao: "DinoLand U.S.A.",
  tipo: "Tematico",
  acesso: "Próximo ao playground The Boneyard",
  precoMedio: 8,
  destaque: "Pipoca, bebidas e sorvetes; quiosque sazonal.",
  latitude: 28.3566,
  longitude: -81.5886,
},



  ];