ï»¿// src/logic/blocos/parques/Disney/CafeDisney.ts

export const cafesDisney = [

  // MainStreet
{
  nome: "Main Street Bakery",
  regiao: "MainStreet",
  tipo: "Tematico",
  acesso: "Ao lado da loja Emporium, na entrada do parque",
  precoMedio: 14,
  destaque: "O principal ponto para comeÃƒÂ§ar o dia, com cafÃƒÂ©s especiais e doces clÃƒÂ¡ssicos. NÃƒÂ£o deixe de experimentar o cinnamon roll quente com glacÃƒÂª de baunilha.",
  latitude: 28.4186,
  longitude: -81.5821,
},
{
  nome: "The Plaza Restaurant",
  regiao: "MainStreet",
  tipo: ["Classico", "Americano"],
  acesso: "Ao final da Main Street, com vista direta para o castelo",
  precoMedio: 20,
  destaque: "CafÃƒÂ© da manhÃƒÂ£ servido ÃƒÂ  mesa com pratos completos e vista mÃƒÂ¡gica. NÃƒÂ£o deixe de pedir os waffles do Mickey com frutas e chantilly.",
  latitude: 28.4189,
  longitude: -81.5826,
},
{
  nome: "CaseyÃ¢â‚¬â„¢s Corner (Breakfast Menu)",
  regiao: "MainStreet",
  tipo: "Conforto",
  acesso: "Virando ÃƒÂ  esquerda antes do castelo",
  precoMedio: 13,
  destaque: "Abre cedo com opÃƒÂ§ÃƒÂµes como pÃƒÂ£o de queijo, croissants e chocolate quente. NÃƒÂ£o deixe de experimentar o cachorro-quente matinal com ovos mexidos e queijo.",
  latitude: 28.4187,
  longitude: -81.5824,
},
{
  nome: "Plaza Ice Cream Parlor (Early Hours)",
  regiao: "MainStreet",
  tipo: "Economico",
  acesso: "Ao lado do CaseyÃ¢â‚¬â„¢s Corner",
  precoMedio: 10,
  destaque: "Serve sorvetes e waffles de manhÃƒÂ£ durante horÃƒÂ¡rios de pico. NÃƒÂ£o deixe de experimentar o sundae com waffle quentinho e sorvete de baunilha.",
  latitude: 28.4188,
  longitude: -81.5825,
},
{
  nome: "Early Morning Emporium Cart",
  regiao: "MainStreet",
  tipo: "Saudavel",
  acesso: "Em frente ÃƒÂ  loja Emporium",
  precoMedio: 9,
  destaque: "Carrinho com frutas frescas, sucos e barras energÃƒÂ©ticas. NÃƒÂ£o deixe de experimentar o mix de frutas com mel orgÃƒÂ¢nico.",
  latitude: 28.4185,
  longitude: -81.5820,
},

// Adventureland
{
  nome: "Aloha Isle (Early Option)",
  regiao: "Adventureland",
  tipo: "Conforto",
  acesso: "Em frente ÃƒÂ  Tiki Room",
  precoMedio: 9,
  destaque: "Para um cafÃƒÂ© tropical, com Dole Whip gelado e suco natural. NÃƒÂ£o deixe de experimentar a versÃƒÂ£o de abacaxi com granola matinal.",
  latitude: 28.4177,
  longitude: -81.5840,
},
{
  nome: "Tropical Mornings Cart",
  regiao: "Adventureland",
  tipo: "Saudavel",
  acesso: "Entre The Magic Carpets of Aladdin e Swiss Family Treehouse",
  precoMedio: 10,
  destaque: "Carrinho com frutas, banana chips e ÃƒÂ¡gua de coco. NÃƒÂ£o deixe de experimentar o bowl de frutas tropicais com chia.",
  latitude: 28.4179,
  longitude: -81.5842,
},
{
  nome: "Jungle Java Express",
  regiao: "Adventureland",
  tipo: "Tematico",
  acesso: "Ao lado da Jungle Cruise",
  precoMedio: 11,
  destaque: "CafÃƒÂ© da manhÃƒÂ£ estilo expediÃƒÂ§ÃƒÂ£o com muffins, chÃƒÂ¡ e cafÃƒÂ© forte. NÃƒÂ£o deixe de provar o muffin de banana com canela.",
  latitude: 28.4180,
  longitude: -81.5843,
},
{
  nome: "Skipper Canteen (Breakfast Hours)",
  regiao: "Adventureland",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Jungle Cruise",
  precoMedio: 21,
  destaque: "Serve pratos matinais em estilo internacional. NÃƒÂ£o deixe de experimentar os ovos com curry suave e torradas com abacate.",
  latitude: 28.4181,
  longitude: -81.5844,
},
{
  nome: "Adventure Bites",
  regiao: "Adventureland",
  tipo: "Economico",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  ponte para Frontierland",
  precoMedio: 8,
  destaque: "Mini sanduÃƒÂ­ches, leite e frutas. NÃƒÂ£o deixe de experimentar o wrap frio de ovos com queijo cheddar.",
  latitude: 28.4176,
  longitude: -81.5838,
},

// Frontierland
{
  nome: "Westward Ho",
  regiao: "Frontierland",
  tipo: "Economico",
  acesso: "Em frente ÃƒÂ  Country Bear Jamboree",
  precoMedio: 10,
  destaque: "CafÃƒÂ© rÃƒÂ¡pido com muffins, chocolate quente e milho cozido. NÃƒÂ£o deixe de experimentar o muffin de blueberry com cafÃƒÂ©.",
  latitude: 28.4175,
  longitude: -81.5851,
},
{
  nome: "Pecos Bill (Breakfast Items)",
  regiao: "Frontierland",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Splash Mountain",
  precoMedio: 18,
  destaque: "Pratos completos estilo cafÃƒÂ© sulista. NÃƒÂ£o deixe de experimentar os ovos com linguiÃƒÂ§a, hash browns e panquecas.",
  latitude: 28.4174,
  longitude: -81.5853,
},
{
  nome: "Cowpoke CafÃƒÂ© Cart",
  regiao: "Frontierland",
  tipo: "Saudavel",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  ponte de Adventureland",
  precoMedio: 9,
  destaque: "Barra de proteÃƒÂ­na, iogurte grego e banana. NÃƒÂ£o deixe de experimentar o parfait de frutas vermelhas.",
  latitude: 28.4173,
  longitude: -81.5850,
},
{
  nome: "Frontier Snacks",
  regiao: "Frontierland",
  tipo: "Conforto",
  acesso: "Perto da Tom Sawyer Island",
  precoMedio: 13,
  destaque: "Pretzels recheados, cookies e sucos. NÃƒÂ£o deixe de experimentar o pretzel recheado de ovos mexidos e queijo.",
  latitude: 28.4172,
  longitude: -81.5849,
},
{
  nome: "Golden Trail Morning",
  regiao: "Frontierland",
  tipo: "Tematico",
  acesso: "PrÃƒÂ³ximo ao trilho do trem",
  precoMedio: 12,
  destaque: "SanduÃƒÂ­ches no estilo cowboy, leite e panqueca enrolada. NÃƒÂ£o deixe de experimentar o rolinho de panqueca recheado com ovo e bacon.",
  latitude: 28.4171,
  longitude: -81.5848,
},

// LibertySquare
{
  nome: "Liberty Snacks",
  regiao: "LibertySquare",
  tipo: "Economico",
  acesso: "PrÃƒÂ³ximo ao Liberty Square Riverboat",
  precoMedio: 12,
  destaque: "Pretzels recheados, donuts e bebidas quentes. NÃƒÂ£o deixe de experimentar o pretzel recheado com cream cheese e o chÃƒÂ¡ de maÃƒÂ§ÃƒÂ£.",
  latitude: 28.4193,
  longitude: -81.5831,
},
{
  nome: "Columbia Harbour House (Breakfast Menu)",
  regiao: "LibertySquare",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado do Hall of Presidents",
  precoMedio: 19,
  destaque: "Pratos de cafÃƒÂ© da manhÃƒÂ£ colonial americano. NÃƒÂ£o deixe de experimentar os waffles com calda de maÃƒÂ§ÃƒÂ£.",
  latitude: 28.4196,
  longitude: -81.5833,
},
{
  nome: "Liberty Tree CafÃƒÂ©",
  regiao: "LibertySquare",
  tipo: "Conforto",
  acesso: "Perto da Haunted Mansion",
  precoMedio: 14,
  destaque: "PÃƒÂ£es doces, muffins e cappuccino cremoso. NÃƒÂ£o deixe de experimentar o muffin de maÃƒÂ§ÃƒÂ£ com canela.",
  latitude: 28.4190,
  longitude: -81.5834,
},
{
  nome: "Freedom Fruit Stand",
  regiao: "LibertySquare",
  tipo: "Saudavel",
  acesso: "AtrÃƒÂ¡s da Liberty Tree Tavern",
  precoMedio: 9,
  destaque: "Bananas, maÃƒÂ§ÃƒÂ£s, barras saudÃƒÂ¡veis e sucos. NÃƒÂ£o deixe de experimentar o combo de frutas com granola e mel.",
  latitude: 28.4192,
  longitude: -81.5835,
},
{
  nome: "Colonial Morning Cart",
  regiao: "LibertySquare",
  tipo: "Tematico",
  acesso: "Ao lado da entrada da Liberty Square",
  precoMedio: 11,
  destaque: "Bolos coloniais e bebida de especiarias. NÃƒÂ£o deixe de experimentar o bolo de milho com mel e canela.",
  latitude: 28.4191,
  longitude: -81.5838,
},

// Fantasyland
{
  nome: "GastonÃ¢â‚¬â„¢s Tavern",
  regiao: "Fantasyland",
  tipo: "Conforto",
  acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o Under the Sea Ã¢â‚¬â€œ Journey of the Little Mermaid",
  precoMedio: 14,
  destaque: "Ambiente rÃƒÂºstico com doces gigantes. NÃƒÂ£o deixe de provar o cinnamon roll do Gaston com calda quente.",
  latitude: 28.4211,
  longitude: -81.5809,
},
{
  nome: "The FriarÃ¢â‚¬â„¢s Nook",
  regiao: "Fantasyland",
  tipo: "Economico",
  acesso: "PrÃƒÂ³ximo ao Prince Charming Regal Carrousel",
  precoMedio: 13,
  destaque: "Serve cafÃƒÂ©s e mac and cheese matinal. NÃƒÂ£o deixe de experimentar o croissant com queijo derretido.",
  latitude: 28.4198,
  longitude: -81.5817,
},
{
  nome: "Pinocchio Village Haus",
  regiao: "Fantasyland",
  tipo: "Saudavel",
  acesso: "Ao lado do ItÃ¢â‚¬â„¢s a Small World",
  precoMedio: 18,
  destaque: "Flatbreads leves, cafÃƒÂ©s e frutas. NÃƒÂ£o deixe de experimentar o flatbread com ovos mexidos e espinafre.",
  latitude: 28.4195,
  longitude: -81.5820,
},
{
  nome: "Enchanted CafÃƒÂ©",
  regiao: "Fantasyland",
  tipo: "Tematico",
  acesso: "Entre Peter PanÃ¢â‚¬â„¢s Flight e MickeyÃ¢â‚¬â„¢s PhilharMagic",
  precoMedio: 11,
  destaque: "Donuts mÃƒÂ¡gicos e chocolate quente com chantilly. NÃƒÂ£o deixe de experimentar o donut em formato do Mickey com cobertura colorida.",
  latitude: 28.4196,
  longitude: -81.5816,
},
{
  nome: "Cinderella's Royal Breakfast",
  regiao: "Fantasyland",
  tipo: ["Classico", "Americano"],
  acesso: "Dentro do Castelo da Cinderela",
  precoMedio: 22,
  destaque: "CafÃƒÂ© da manhÃƒÂ£ real com ovos, bacon, waffles e frutas. NÃƒÂ£o deixe de experimentar os ovos mexidos do Mickey.",
  latitude: 28.4194,
  longitude: -81.5812,
},


// Tomorrowland
{
  nome: "The Lunching Pad",
  regiao: "Tomorrowland",
  tipo: "Economico",
  acesso: "Na base da Astro Orbiter",
  precoMedio: 11,
  destaque: "Snacks rÃƒÂ¡pidos e cafÃƒÂ©s para os apressados. NÃƒÂ£o deixe de experimentar o pretzel recheado com cream cheese e o cafÃƒÂ© gelado.",
  latitude: 28.4201,
  longitude: -81.5793,
},
{
  nome: "Cosmic RayÃ¢â‚¬â„¢s Starlight CafÃƒÂ©",
  regiao: "Tomorrowland",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente ÃƒÂ  Buzz Lightyear",
  precoMedio: 20,
  destaque: "RefeiÃƒÂ§ÃƒÂµes rÃƒÂ¡pidas em ambiente musical. NÃƒÂ£o deixe de pedir o combo de ovos mexidos, bacon e torrada.",
  latitude: 28.4200,
  longitude: -81.5792,
},
{
  nome: "Orbital Express Cart",
  regiao: "Tomorrowland",
  tipo: "Saudavel",
  acesso: "Entre a entrada da Space Mountain e o Speedway",
  precoMedio: 10,
  destaque: "Wraps frios, sucos e barras energÃƒÂ©ticas. NÃƒÂ£o deixe de experimentar o wrap de ovo com espinafre e queijo feta.",
  latitude: 28.4202,
  longitude: -81.5794,
},
{
  nome: "Tomorrow Morning Fuel",
  regiao: "Tomorrowland",
  tipo: "Tematico",
  acesso: "Ao lado do Tomorrowland Terrace",
  precoMedio: 13,
  destaque: "Lanches futuristas com cafÃƒÂ©s especiais. NÃƒÂ£o deixe de experimentar o pÃƒÂ£o doce de galÃƒÂ¡xia recheado com creme azul.",
  latitude: 28.4203,
  longitude: -81.5795,
},
{
  nome: "Starry Start CafÃƒÂ©",
  regiao: "Tomorrowland",
  tipo: "Conforto",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada lateral do Space Ranger Spin",
  precoMedio: 12,
  destaque: "OpÃƒÂ§ÃƒÂµes matinais como panquecas e chÃƒÂ¡ com limÃƒÂ£o. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che de ovo com bacon e queijo em pÃƒÂ£o de brioche.",
  latitude: 28.4204,
  longitude: -81.5796,
},
// World Showcase
{
  nome: "Les Halles Boulangerie-Patisserie",
  regiao: "World Showcase",
  tipo: ["Classico", "Americano"],
  acesso: "PavilhÃƒÂ£o da FranÃƒÂ§a Ã¢â‚¬â€œ entrada pela lateral, antes do RemyÃ¢â‚¬â„¢s Ratatouille Adventure",
  precoMedio: 16,
  destaque: "Padaria francesa com doces frescos e cafÃƒÂ©s artesanais. NÃƒÂ£o deixe de experimentar o croissant de amÃƒÂªndoas com cafÃƒÂ© au lait.",
  latitude: 28.3705,
  longitude: -81.5502,
},
{
  nome: "Kringla Bakeri Og Kafe",
  regiao: "World Showcase",
  tipo: "Tematico",
  acesso: "PavilhÃƒÂ£o da Noruega Ã¢â‚¬â€œ ao lado da loja de Frozen",
  precoMedio: 15,
  destaque: "Cafeteria norueguesa com bolos tÃƒÂ­picos e bebidas quentes. NÃƒÂ£o deixe de experimentar o School Bread com cobertura de coco.",
  latitude: 28.3707,
  longitude: -81.5490,
},
{
  nome: "Sunshine Seasons Cart Ã¢â‚¬â€œ Showcase",
  regiao: "World Showcase",
  tipo: "Saudavel",
  acesso: "PavilhÃƒÂ£o dos EUA Ã¢â‚¬â€œ ao lado do American Adventure",
  precoMedio: 10,
  destaque: "Frutas frescas, iogurte e granola. NÃƒÂ£o deixe de experimentar o potinho de frutas vermelhas com mel.",
  latitude: 28.3710,
  longitude: -81.5505,
},
{
  nome: "Tangierine CafÃƒÂ© Ã¢â‚¬â€œ Breakfast Corner",
  regiao: "World Showcase",
  tipo: "Conforto",
  acesso: "PavilhÃƒÂ£o do Marrocos Ã¢â‚¬â€œ entrada lateral",
  precoMedio: 12,
  destaque: "Wraps leves com toque marroquino. NÃƒÂ£o deixe de experimentar o wrap de ovos com hortelÃƒÂ£ e queijo de cabra.",
  latitude: 28.3708,
  longitude: -81.5493,
},
{
  nome: "La Cantina de San Angel (Early Hours)",
  regiao: "World Showcase",
  tipo: "Economico",
  acesso: "PavilhÃƒÂ£o do MÃƒÂ©xico Ã¢â‚¬â€œ na beira do lago, ao lado da pirÃƒÂ¢mide",
  precoMedio: 11,
  destaque: "CafÃƒÂ© matinal com bolos de milho e sucos tropicais. NÃƒÂ£o deixe de experimentar o pan de elote com chocolate quente.",
  latitude: 28.3711,
  longitude: -81.5475,
},

// World Discovery
{
  nome: "Connections CafÃƒÂ©",
  regiao: "World Discovery",
  tipo: "Tematico",
  acesso: "Ao lado do Creations Shop",
  precoMedio: 14,
  destaque: "Cafeteria moderna com pÃƒÂ£es e bebidas quentes. NÃƒÂ£o deixe de experimentar o pÃƒÂ£o de canela com cobertura de maple.",
  latitude: 28.3741,
  longitude: -81.5487,
},
{
  nome: "Space 220 Lounge (Breakfast Menu)",
  regiao: "World Discovery",
  tipo: ["Classico", "Americano"],
  acesso: "Entrada pela Mission: SPACE",
  precoMedio: 26,
  destaque: "CafÃƒÂ© da manhÃƒÂ£ em ambiente de estaÃƒÂ§ÃƒÂ£o espacial. NÃƒÂ£o deixe de experimentar os ovos mexidos com batata trufada.",
  latitude: 28.3735,
  longitude: -81.5480,
},
{
  nome: "Mission Fuel Station",
  regiao: "World Discovery",
  tipo: "Economico",
  acesso: "Entre Test Track e Mission: SPACE",
  precoMedio: 10,
  destaque: "Snacks rÃƒÂ¡pidos e bebidas energÃƒÂ©ticas. NÃƒÂ£o deixe de experimentar a barra de cereal com leite e banana.",
  latitude: 28.3749,
  longitude: -81.5482,
},
{
  nome: "Nova Greens Express",
  regiao: "World Discovery",
  tipo: "Saudavel",
  acesso: "Ao lado da Guardians of the Galaxy",
  precoMedio: 12,
  destaque: "Bowls matinais com frutas, chia e granola. NÃƒÂ£o deixe de experimentar o bowl de morango com linhaÃƒÂ§a.",
  latitude: 28.3748,
  longitude: -81.5477,
},
{
  nome: "Test Track CafÃƒÂ©",
  regiao: "World Discovery",
  tipo: "Conforto",
  acesso: "Na saÃƒÂ­da da atraÃƒÂ§ÃƒÂ£o Test Track",
  precoMedio: 13,
  destaque: "CafÃƒÂ© americano clÃƒÂ¡ssico com muffin, cafÃƒÂ© e bacon. NÃƒÂ£o deixe de experimentar o combo matinal com panqueca recheada.",
  latitude: 28.3751,
  longitude: -81.5483,
},

// World Celebration
{
  nome: "EPCOT Brew House",
  regiao: "World Celebration",
  tipo: "Tematico",
  acesso: "Ao lado do Connections Eatery",
  precoMedio: 15,
  destaque: "Cervejas leves, bolos e pÃƒÂ£es. NÃƒÂ£o deixe de experimentar o pÃƒÂ£o de aveia com mel e cafÃƒÂ© artesanal.",
  latitude: 28.3743,
  longitude: -81.5488,
},
{
  nome: "Garden Start Snacks",
  regiao: "World Celebration",
  tipo: "Economico",
  acesso: "Em frente ao Dreamers Point",
  precoMedio: 9,
  destaque: "Snacks, barrinhas e suco natural. NÃƒÂ£o deixe de experimentar o muffin integral com banana e aveia.",
  latitude: 28.3745,
  longitude: -81.5486,
},
{
  nome: "Central CafÃƒÂ©",
  regiao: "World Celebration",
  tipo: ["Classico", "Americano"],
  acesso: "Entre o centro e a entrada do World Showcase",
  precoMedio: 18,
  destaque: "Combo tradicional de ovos, bacon e pÃƒÂ£o artesanal. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che de ovo no pÃƒÂ£o brioche.",
  latitude: 28.3740,
  longitude: -81.5489,
},
{
  nome: "Fresh Start Salads",
  regiao: "World Celebration",
  tipo: "Saudavel",
  acesso: "Ao lado da Creations Shop",
  precoMedio: 12,
  destaque: "Saladas de frutas e smoothies leves. NÃƒÂ£o deixe de experimentar o smoothie de manga com gengibre.",
  latitude: 28.3746,
  longitude: -81.5484,
},
{
  nome: "Inspiration Grounds",
  regiao: "World Celebration",
  tipo: "Conforto",
  acesso: "Caminho para o World Showcase",
  precoMedio: 13,
  destaque: "Waffles, suco de laranja e cafÃƒÂ© com leite. NÃƒÂ£o deixe de experimentar os waffles em formato do Mickey com calda de frutas.",
  latitude: 28.3742,
  longitude: -81.5485,
},

// World Nature
{
  nome: "Sunshine Seasons",
  regiao: "World Nature",
  tipo: ["Classico", "Americano"],
  acesso: "Dentro do pavilhÃƒÂ£o The Land",
  precoMedio: 20,
  destaque: "Buffet com opÃƒÂ§ÃƒÂµes de cafÃƒÂ©, pÃƒÂ£es e ovos frescos. NÃƒÂ£o deixe de experimentar o combo de ovos mexidos, batata e torrada.",
  latitude: 28.3724,
  longitude: -81.5472,
},
{
  nome: "The Land Cart",
  regiao: "World Nature",
  tipo: "Economico",
  acesso: "Entrada do pavilhÃƒÂ£o The Land",
  precoMedio: 10,
  destaque: "Bananas, sucos e muffins matinais. NÃƒÂ£o deixe de experimentar o combo com suco de maÃƒÂ§ÃƒÂ£ e muffin de mirtilo.",
  latitude: 28.3723,
  longitude: -81.5473,
},
{
  nome: "Green Bowl Express",
  regiao: "World Nature",
  tipo: "Saudavel",
  acesso: "Entre The Land e The Seas",
  precoMedio: 13,
  destaque: "Bowls frescos com chia e frutas orgÃƒÂ¢nicas. NÃƒÂ£o deixe de experimentar o bowl com manga, kiwi e iogurte natural.",
  latitude: 28.3725,
  longitude: -81.5471,
},
{
  nome: "Coral Reef Early CafÃƒÂ©",
  regiao: "World Nature",
  tipo: "Tematico",
  acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o The Seas with Nemo & Friends",
  precoMedio: 17,
  destaque: "Ambiente subaquÃƒÂ¡tico com cafÃƒÂ© gourmet. NÃƒÂ£o deixe de pedir o pÃƒÂ£o doce recheado de creme com cobertura crocante.",
  latitude: 28.3720,
  longitude: -81.5469,
},
{
  nome: "Nature Morning Stand",
  regiao: "World Nature",
  tipo: "Conforto",
  acesso: "SaÃƒÂ­da do The Land, prÃƒÂ³ximo ÃƒÂ  subida para o The Seas",
  precoMedio: 12,
  destaque: "Wraps leves com ovos e chÃƒÂ¡ verde gelado. NÃƒÂ£o deixe de experimentar o wrap de ovo com cogumelo e tomate seco.",
  latitude: 28.3726,
  longitude: -81.5470,
},
// Hollywood Boulevard
{
  nome: "The Trolley Car CafÃƒÂ©",
  regiao: "Hollywood Boulevard",
  tipo: "Tematico",
  acesso: "Ãƒâ‚¬ direita da entrada principal do parque",
  precoMedio: 14,
  destaque: "Cafeteria no estilo Starbucks com doces e cafÃƒÂ©s fortes. NÃƒÂ£o deixe de experimentar o famoso carrot cake cookie com cafÃƒÂ© gelado.",
  latitude: 28.3571,
  longitude: -81.5582,
},
{
  nome: "Hollywood & Vine (Breakfast Buffet)",
  regiao: "Hollywood Boulevard",
  tipo: ["Classico", "Americano"],
  acesso: "Perto do centro do parque, prÃƒÂ³ximo ÃƒÂ  Animation Courtyard",
  precoMedio: 39,
  destaque: "Buffet com personagens Disney e pratos clÃƒÂ¡ssicos de cafÃƒÂ©. NÃƒÂ£o deixe de experimentar os waffles do Mickey com chantilly e frutas.",
  latitude: 28.3574,
  longitude: -81.5581,
},
{
  nome: "Sunset Boulevard Cart (Early Stand)",
  regiao: "Hollywood Boulevard",
  tipo: "Economico",
  acesso: "InÃƒÂ­cio da Sunset Blvd, antes da loja Legends of Hollywood",
  precoMedio: 10,
  destaque: "Carrinho com frutas, bolinhos e bebidas matinais. NÃƒÂ£o deixe de experimentar o croissant de queijo com cafÃƒÂ© com leite.",
  latitude: 28.3572,
  longitude: -81.5583,
},
{
  nome: "Hollywood Morning Market",
  regiao: "Hollywood Boulevard",
  tipo: "Saudavel",
  acesso: "Perto da MickeyÃ¢â‚¬â„¢s of Hollywood",
  precoMedio: 11,
  destaque: "OpÃƒÂ§ÃƒÂµes leves como iogurte com granola e smoothies. NÃƒÂ£o deixe de experimentar o copo de frutas com mel e hortelÃƒÂ£.",
  latitude: 28.3573,
  longitude: -81.5580,
},
{
  nome: "Studio Scoops AM",
  regiao: "Hollywood Boulevard",
  tipo: "Conforto",
  acesso: "Ao lado da loja Celebrity 5 & 10",
  precoMedio: 13,
  destaque: "Sorvetes leves, waffles e cafÃƒÂ© expresso. NÃƒÂ£o deixe de experimentar o sundae com waffle e frutas vermelhas.",
  latitude: 28.3570,
  longitude: -81.5584,
},

// Echo Lake
{
  nome: "Backlot Express (Breakfast Menu)",
  regiao: "Echo Lake",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o Star Tours",
  precoMedio: 17,
  destaque: "Combo americano com ovos, bacon e panqueca. NÃƒÂ£o deixe de experimentar o combo matinal com batata rÃƒÂºstica e cafÃƒÂ© preto.",
  latitude: 28.3580,
  longitude: -81.5588,
},
{
  nome: "Echo Lake CafÃƒÂ© Cart",
  regiao: "Echo Lake",
  tipo: "Economico",
  acesso: "PrÃƒÂ³ximo ao lago, em frente ao Indiana Jones Epic Stunt Spectacular",
  precoMedio: 9,
  destaque: "Pretzels recheados, muffins e suco de laranja. NÃƒÂ£o deixe de experimentar o pretzel de cream cheese aquecido.",
  latitude: 28.3578,
  longitude: -81.5590,
},
{
  nome: "Dinosaur GertieÃ¢â‚¬â„¢s Snacks",
  regiao: "Echo Lake",
  tipo: "Conforto",
  acesso: "Dentro da escultura do dinossauro verde",
  precoMedio: 10,
  destaque: "Sorvetes e snacks matinais inusitados. NÃƒÂ£o deixe de experimentar o sorvete de baunilha com granola e banana.",
  latitude: 28.3582,
  longitude: -81.5592,
},
{
  nome: "Echo Lake Healthy Start",
  regiao: "Echo Lake",
  tipo: "Saudavel",
  acesso: "Em frente ÃƒÂ  loja Frozen Fractal Gifts",
  precoMedio: 11,
  destaque: "Wraps com ovos, frutas frescas e chÃƒÂ¡s gelados. NÃƒÂ£o deixe de experimentar o wrap de clara com espinafre e queijo branco.",
  latitude: 28.3581,
  longitude: -81.5591,
},
{
  nome: "50Ã¢â‚¬â„¢s Prime Time CafÃƒÂ© (Breakfast Special)",
  regiao: "Echo Lake",
  tipo: "Tematico",
  acesso: "AtrÃƒÂ¡s do Echo Lake",
  precoMedio: 25,
  destaque: "CafÃƒÂ© no estilo retrÃƒÂ´ com pratos clÃƒÂ¡ssicos americanos. NÃƒÂ£o deixe de experimentar a panqueca com bacon caramelizado.",
  latitude: 28.3579,
  longitude: -81.5593,
},

// Grand Avenue
{
  nome: "PizzeRizzo (Early Hours)",
  regiao: "Grand Avenue",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Muppet Courtyard",
  precoMedio: 15,
  destaque: "Serve cafÃƒÂ© da manhÃƒÂ£ simples com toque italiano. NÃƒÂ£o deixe de experimentar o pÃƒÂ£o italiano recheado com ovos e presunto.",
  latitude: 28.3576,
  longitude: -81.5603,
},
{
  nome: "Muppet Morning Snacks",
  regiao: "Grand Avenue",
  tipo: "Tematico",
  acesso: "Em frente ÃƒÂ  entrada da Muppet*Vision 3D",
  precoMedio: 9,
  destaque: "Cookies temÃƒÂ¡ticos e bebidas matinais. NÃƒÂ£o deixe de experimentar o cookie do Kermit com chocolate e matcha.",
  latitude: 28.3577,
  longitude: -81.5601,
},
{
  nome: "Studio Start Cart",
  regiao: "Grand Avenue",
  tipo: "Economico",
  acesso: "Na lateral da Grand Avenue",
  precoMedio: 8,
  destaque: "OpÃƒÂ§ÃƒÂµes rÃƒÂ¡pidas como barras, cafÃƒÂ© e frutas. NÃƒÂ£o deixe de experimentar a banana com pasta de amendoim.",
  latitude: 28.3575,
  longitude: -81.5602,
},
{
  nome: "Rizzo's Wake Up",
  regiao: "Grand Avenue",
  tipo: "Saudavel",
  acesso: "AtrÃƒÂ¡s do PizzeRizzo",
  precoMedio: 12,
  destaque: "Wraps frios e smoothies verdes. NÃƒÂ£o deixe de experimentar o smoothie de espinafre com abacaxi e limÃƒÂ£o.",
  latitude: 28.3574,
  longitude: -81.5600,
},
{
  nome: "Grand Cappuccino Stop",
  regiao: "Grand Avenue",
  tipo: "Conforto",
  acesso: "Entre a entrada da ÃƒÂ¡rea Muppet e Star Wars",
  precoMedio: 13,
  destaque: "Cappuccinos, donuts e croissants. NÃƒÂ£o deixe de experimentar o croissant de queijo e presunto.",
  latitude: 28.3573,
  longitude: -81.5604,
},

// Star Wars: GalaxyÃ¢â‚¬â„¢s Edge
{
  nome: "Ronto Roasters (Breakfast Wrap)",
  regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Droid Depot",
  precoMedio: 14,
  destaque: "Wraps quentes com toque galÃƒÂ¡ctico. NÃƒÂ£o deixe de experimentar o Ronto Wrap matinal com ovos, linguiÃƒÂ§a e queijo.",
  latitude: 28.3586,
  longitude: -81.5614,
},
{
  nome: "Galactic Pastries",
  regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
  tipo: "Conforto",
  acesso: "PrÃƒÂ³ximo ao Black Spire Outpost Market",
  precoMedio: 12,
  destaque: "Doces e pÃƒÂ£es confortÃƒÂ¡veis em ambiente galÃƒÂ¡ctico. NÃƒÂ£o deixe de experimentar o pÃƒÂ£o doce de baunilha com formato de planeta.",
  latitude: 28.3588,
  longitude: -81.5610,
},

{
  nome: "Milk Stand (Early Hours)",
  regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
  tipo: "Tematico",
  acesso: "Em frente ÃƒÂ  atraÃƒÂ§ÃƒÂ£o Rise of the Resistance",
  precoMedio: 9,
  destaque: "Leite azul e verde gelados ideais para comeÃƒÂ§ar o dia fora da Terra. NÃƒÂ£o deixe de experimentar o leite azul com essÃƒÂªncia de frutas tropicais.",
  latitude: 28.3587,
  longitude: -81.5613,
},
{
  nome: "Black Spire Fruit Stand",
  regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
  tipo: "Saudavel",
  acesso: "Perto da saÃƒÂ­da do mercado",
  precoMedio: 11,
  destaque: "Snacks naturais e frutas alienÃƒÂ­genas. NÃƒÂ£o deixe de experimentar o mix de frutas com nome temÃƒÂ¡tico e suco concentrado.",
  latitude: 28.3584,
  longitude: -81.5615,
},
{
  nome: "Resistance Fuel Cart",
  regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
  tipo: "Economico",
  acesso: "Ao lado da entrada da Rise of the Resistance",
  precoMedio: 8,
  destaque: "Barras energÃƒÂ©ticas e bebidas prÃƒÂ¡ticas. NÃƒÂ£o deixe de experimentar a barra de proteÃƒÂ­na 'Galaxy Crunch'.",
  latitude: 28.3583,
  longitude: -81.5612,
},

// Toy Story Land
{
  nome: "WoodyÃ¢â‚¬â„¢s Lunch Box (Breakfast Menu)",
  regiao: "Toy Story Land",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Slinky Dog Dash",
  precoMedio: 16,
  destaque: "CafÃƒÂ© criativo com pratos infantis e saborosos. NÃƒÂ£o deixe de experimentar o breakfast bowl com ovos mexidos e queijo derretido.",
  latitude: 28.3591,
  longitude: -81.5621,
},
{
  nome: "Toy Box Treats",
  regiao: "Toy Story Land",
  tipo: "Tematico",
  acesso: "Perto do Alien Swirling Saucers",
  precoMedio: 10,
  destaque: "Doces coloridos e bebidas matinais. NÃƒÂ£o deixe de experimentar o donut do Buzz com glacÃƒÂª roxo e estrelas comestÃƒÂ­veis.",
  latitude: 28.3592,
  longitude: -81.5622,
},
{
  nome: "Green Army Patrol Snacks",
  regiao: "Toy Story Land",
  tipo: "Conforto",
  acesso: "AtrÃƒÂ¡s da parada do Green Army Men",
  precoMedio: 11,
  destaque: "Snacks militares como panquecas enroladas e suco. NÃƒÂ£o deixe de experimentar o enroladinho de panqueca recheado de frutas.",
  latitude: 28.3593,
  longitude: -81.5623,
},
{
  nome: "BuzzÃ¢â‚¬â„¢s Morning Fuel",
  regiao: "Toy Story Land",
  tipo: "Saudavel",
  acesso: "Na entrada da ÃƒÂ¡rea temÃƒÂ¡tica",
  precoMedio: 12,
  destaque: "Smoothies verdes e wraps com ovo. NÃƒÂ£o deixe de experimentar o smoothie do Buzz com abacaxi, espinafre e hortelÃƒÂ£.",
  latitude: 28.3590,
  longitude: -81.5620,
},
{
  nome: "Andy's Fruit Stop",
  regiao: "Toy Story Land",
  tipo: "Economico",
  acesso: "Na lateral do WoodyÃ¢â‚¬â„¢s Lunch Box",
  precoMedio: 8,
  destaque: "MaÃƒÂ§ÃƒÂ£s, bananas e sucos naturais. NÃƒÂ£o deixe de experimentar o copo com mix de frutas picadas.",
  latitude: 28.3589,
  longitude: -81.5619,
},

// Animation Courtyard
{
  nome: "Animators CafÃƒÂ©",
  regiao: "Animation Courtyard",
  tipo: ["Classico", "Americano"],
  acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada do Disney Junior Dance Party",
  precoMedio: 14,
  destaque: "Ambiente artÃƒÂ­stico com combos de cafÃƒÂ© e sanduÃƒÂ­che. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che de ovo com queijo e o capuccino.",
  latitude: 28.3568,
  longitude: -81.5598,
},
{
  nome: "Courtyard Snacks",
  regiao: "Animation Courtyard",
  tipo: "Economico",
  acesso: "Ao lado do Walt Disney Presents",
  precoMedio: 9,
  destaque: "Cookies, leite e cereais. NÃƒÂ£o deixe de experimentar o cookie do Mickey com gotas de chocolate.",
  latitude: 28.3567,
  longitude: -81.5597,
},
{
  nome: "Toon Start Stand",
  regiao: "Animation Courtyard",
  tipo: "Tematico",
  acesso: "Em frente ÃƒÂ  estÃƒÂ¡tua do Mickey Feiticeiro",
  precoMedio: 10,
  destaque: "Mini donuts, chocolate quente e animaÃƒÂ§ÃƒÂ£o para crianÃƒÂ§as. NÃƒÂ£o deixe de experimentar o donut colorido com granulado mÃƒÂ¡gico.",
  latitude: 28.3569,
  longitude: -81.5599,
},
{
  nome: "Morning Animation Fuel",
  regiao: "Animation Courtyard",
  tipo: "Conforto",
  acesso: "Ao lado do One ManÃ¢â‚¬â„¢s Dream",
  precoMedio: 11,
  destaque: "Wraps simples e leite com achocolatado. NÃƒÂ£o deixe de experimentar o wrap de ovo com queijo cheddar.",
  latitude: 28.3566,
  longitude: -81.5596,
},
{
  nome: "ArtistÃ¢â‚¬â„¢s Greens",
  regiao: "Animation Courtyard",
  tipo: "Saudavel",
  acesso: "Fundos do pavilhÃƒÂ£o de animaÃƒÂ§ÃƒÂ£o",
  precoMedio: 12,
  destaque: "Saladas matinais com frutas e sementes. NÃƒÂ£o deixe de experimentar a salada de iogurte com granola e morango.",
  latitude: 28.3565,
  longitude: -81.5595,
},

// Sunset Boulevard
{
  nome: "Sunset Ranch Market (Breakfast Hours)",
  regiao: "Sunset Boulevard",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Rock Ã¢â‚¬ËœnÃ¢â‚¬â„¢ Roller Coaster",
  precoMedio: 16,
  destaque: "CafÃƒÂ© estilo americano com ovos, bacon e panquecas. NÃƒÂ£o deixe de experimentar o combo de panqueca com calda de frutas vermelhas.",
  latitude: 28.3556,
  longitude: -81.5599,
},
{
  nome: "RosieÃ¢â‚¬â„¢s All-American CafÃƒÂ© (Early Menu)",
  regiao: "Sunset Boulevard",
  tipo: "Tematico",
  acesso: "Em frente ao Hollywood Scoops",
  precoMedio: 13,
  destaque: "CafÃƒÂ© com cara de diner americano dos anos 50. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che de cafÃƒÂ© da manhÃƒÂ£ com ovo e salsicha.",
  latitude: 28.3557,
  longitude: -81.5598,
},
{
  nome: "Sunset Fruit Cart",
  regiao: "Sunset Boulevard",
  tipo: "Saudavel",
  acesso: "Na descida para a Tower of Terror",
  precoMedio: 9,
  destaque: "Frutas frescas, iogurtes e sucos naturais. NÃƒÂ£o deixe de experimentar o copo com morango, uva e melancia gelada.",
  latitude: 28.3555,
  longitude: -81.5600,
},
{
  nome: "Hollywood Scoops (Breakfast Specials)",
  regiao: "Sunset Boulevard",
  tipo: "Conforto",
  acesso: "Ao lado da Sunset Ranch Market",
  precoMedio: 12,
  destaque: "Sorvetes e waffles em porÃƒÂ§ÃƒÂµes matinais. NÃƒÂ£o deixe de experimentar o waffle com bola de sorvete e calda de morango.",
  latitude: 28.3554,
  longitude: -81.5601,
},
{
  nome: "Sunset Start Express",
  regiao: "Sunset Boulevard",
  tipo: "Economico",
  acesso: "Ao lado da loja Once Upon a Time",
  precoMedio: 10,
  destaque: "CafÃƒÂ© preto, bolos simples e cereais. NÃƒÂ£o deixe de experimentar o bolo de banana com nozes.",
  latitude: 28.3553,
  longitude: -81.5602,
},

// Oasis
{
  nome: "Rainforest CafÃƒÂ© (Breakfast Menu)",
  regiao: "Oasis",
  tipo: "Tematico",
  acesso: "Na entrada principal, antes dos portÃƒÂµes do parque",
  precoMedio: 28,
  destaque: "Ambiente de floresta com pratos tropicais no cafÃƒÂ© da manhÃƒÂ£. NÃƒÂ£o deixe de experimentar os waffles de banana com calda de caramelo.",
  latitude: 28.3598,
  longitude: -81.5912,
},
{
  nome: "Oasis Snacks Cart",
  regiao: "Oasis",
  tipo: "Economico",
  acesso: "Logo apÃƒÂ³s a entrada, ÃƒÂ  esquerda do mapa interativo",
  precoMedio: 9,
  destaque: "Snacks rÃƒÂ¡pidos como frutas, muffins e sucos. NÃƒÂ£o deixe de experimentar o copo de frutas com mel e limÃƒÂ£o.",
  latitude: 28.3599,
  longitude: -81.5910,
},
{
  nome: "Tropical Roots CafÃƒÂ©",
  regiao: "Oasis",
  tipo: "Saudavel",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  ponte de acesso ÃƒÂ  Discovery Island",
  precoMedio: 11,
  destaque: "Smoothies naturais e wraps leves. NÃƒÂ£o deixe de experimentar o smoothie de manga com gengibre e hortelÃƒÂ£.",
  latitude: 28.3597,
  longitude: -81.5911,
},
{
  nome: "Morning Jungle Cart",
  regiao: "Oasis",
  tipo: "Conforto",
  acesso: "Ao lado da loja Garden Gate Gifts",
  precoMedio: 10,
  destaque: "Cookies artesanais, chocolate quente e croissants. NÃƒÂ£o deixe de experimentar o croissant recheado de creme de avelÃƒÂ£.",
  latitude: 28.3596,
  longitude: -81.5913,
},
{
  nome: "ExplorerÃ¢â‚¬â„¢s Start",
  regiao: "Oasis",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente ao lago central da Oasis",
  precoMedio: 14,
  destaque: "Combo de ovos, batatas e pÃƒÂ£o grelhado. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che quente de ovo e cheddar.",
  latitude: 28.3595,
  longitude: -81.5914,
},

// Discovery Island
{
  nome: "Creature Comforts",
  regiao: "Discovery Island",
  tipo: "Tematico",
  acesso: "Entre as principais lojas do centro da ilha",
  precoMedio: 14,
  destaque: "CafÃƒÂ© no estilo Starbucks com doces e bebidas especiais. NÃƒÂ£o deixe de experimentar o muffin de banana com crumble de canela.",
  latitude: 28.3610,
  longitude: -81.5900,
},
{
  nome: "Flame Tree Barbecue (Breakfast Items)",
  regiao: "Discovery Island",
  tipo: ["Classico", "Americano"],
  acesso: "Com vista para o lago, prÃƒÂ³ximo ÃƒÂ  ponte para Asia",
  precoMedio: 18,
  destaque: "RefeiÃƒÂ§ÃƒÂµes matinais ao estilo sulista. NÃƒÂ£o deixe de experimentar os ovos com linguiÃƒÂ§a e pÃƒÂ£o de milho.",
  latitude: 28.3608,
  longitude: -81.5902,
},
{
  nome: "Island Eats Stand",
  regiao: "Discovery Island",
  tipo: "Economico",
  acesso: "PrÃƒÂ³ximo ao Tree of Life Garden",
  precoMedio: 9,
  destaque: "Snacks rÃƒÂ¡pidos e frutas para comeÃƒÂ§ar o dia leve. NÃƒÂ£o deixe de experimentar o copo de uvas e maÃƒÂ§ÃƒÂ£ verde.",
  latitude: 28.3612,
  longitude: -81.5903,
},
{
  nome: "Discovery Greens",
  regiao: "Discovery Island",
  tipo: "Saudavel",
  acesso: "AtrÃƒÂ¡s da loja Island Mercantile",
  precoMedio: 12,
  destaque: "Bowls, wraps e sucos verdes. NÃƒÂ£o deixe de experimentar o bowl de quinoa com kiwi e melÃƒÂ£o.",
  latitude: 28.3613,
  longitude: -81.5904,
},
{
  nome: "Nature's Morning",
  regiao: "Discovery Island",
  tipo: "Conforto",
  acesso: "Perto da ponte para Africa",
  precoMedio: 11,
  destaque: "Cookies e pÃƒÂ£es matinais em espaÃƒÂ§o sombreado. NÃƒÂ£o deixe de experimentar o pÃƒÂ£o doce de maÃƒÂ§ÃƒÂ£ com canela.",
  latitude: 28.3609,
  longitude: -81.5899,
},

// Pandora Ã¢â‚¬â€œ The World of Avatar
{
  nome: "SatuÃ¢â‚¬â„¢li Canteen (Breakfast Bowl)",
  regiao: "Pandora Ã¢â‚¬â€œ The World of Avatar",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o Flight of Passage",
  precoMedio: 22,
  destaque: "Pratos inspirados em Pandora para cafÃƒÂ© da manhÃƒÂ£. NÃƒÂ£o deixe de experimentar o bowl de batata doce com ovos e molho de ervas.",
  latitude: 28.3595,
  longitude: -81.5886,
},
{
  nome: "Pongu Pongu (Early Hours)",
  regiao: "Pandora Ã¢â‚¬â€œ The World of Avatar",
  tipo: "Tematico",
  acesso: "Ao lado da entrada de NaÃ¢â‚¬â„¢vi River Journey",
  precoMedio: 12,
  destaque: "Bebidas exÃƒÂ³ticas e pÃƒÂ£es doces alienÃƒÂ­genas. NÃƒÂ£o deixe de experimentar o Pongu Lumpia Ã¢â‚¬â€œ rolinho de abacaxi e cream cheese.",
  latitude: 28.3594,
  longitude: -81.5888,
},
{
  nome: "Pandora Fruit Cart",
  regiao: "Pandora Ã¢â‚¬â€œ The World of Avatar",
  tipo: "Saudavel",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  ponte de entrada em Pandora",
  precoMedio: 10,
  destaque: "Frutas alienÃƒÂ­genas (inspiradas em Earth) e sucos naturais. NÃƒÂ£o deixe de experimentar o copo de frutas com pitaya e manga.",
  latitude: 28.3593,
  longitude: -81.5885,
},
{
  nome: "Avatar Morning Fuel",
  regiao: "Pandora Ã¢â‚¬â€œ The World of Avatar",
  tipo: "Economico",
  acesso: "Ao lado do SatuÃ¢â‚¬â„¢li Canteen",
  precoMedio: 9,
  destaque: "Barras, wraps frios e chÃƒÂ¡ de Pandora. NÃƒÂ£o deixe de experimentar o wrap de ovo com batata-doce e queijo feta.",
  latitude: 28.3592,
  longitude: -81.5884,
},
{
  nome: "NeytiriÃ¢â‚¬â„¢s Start",
  regiao: "Pandora Ã¢â‚¬â€œ The World of Avatar",
  tipo: "Conforto",
  acesso: "No jardim de entrada de Pandora",
  precoMedio: 11,
  destaque: "PÃƒÂ£es doces temÃƒÂ¡ticos e bebidas azuis. NÃƒÂ£o deixe de experimentar o muffin de mirtilo com essÃƒÂªncia de flor azul.",
  latitude: 28.3591,
  longitude: -81.5883,
},

// Africa
{
  nome: "Tusker House Restaurant (Character Breakfast)",
  regiao: "Africa",
  tipo: "Tematico",
  acesso: "Perto da entrada do Kilimanjaro Safaris",
  precoMedio: 45,
  destaque: "Buffet com personagens e pratos africanos. NÃƒÂ£o deixe de experimentar o arroz jollof com ovos mexidos e banana-da-terra.",
  latitude: 28.3590,
  longitude: -81.5930,
},
{
  nome: "Harambe Fruit Market",
  regiao: "Africa",
  tipo: "Saudavel",
  acesso: "Em frente ÃƒÂ  saÃƒÂ­da da Kilimanjaro Safaris",
  precoMedio: 9,
  destaque: "Frutas frescas, barras naturais e ÃƒÂ¡gua de coco. NÃƒÂ£o deixe de experimentar o copo com melancia, manga e laranja.",
  latitude: 28.3589,
  longitude: -81.5931,
},
{
  nome: "ZuriÃ¢â‚¬â„¢s Sweets Shop (Morning Menu)",
  regiao: "Africa",
  tipo: "Conforto",
  acesso: "Ao lado do Harambe Market",
  precoMedio: 12,
  destaque: "Doces africanos, bolos e cafÃƒÂ© aromÃƒÂ¡tico. NÃƒÂ£o deixe de experimentar o bolo de especiarias com cobertura de baunilha.",
  latitude: 28.3591,
  longitude: -81.5929,
},
{
  nome: "Harambe Market (Breakfast Bowls)",
  regiao: "Africa",
  tipo: ["Classico", "Americano"],
  acesso: "PÃƒÂ¡tio central de Harambe Market",
  precoMedio: 16,
  destaque: "Pratos completos com toque africano. NÃƒÂ£o deixe de experimentar o bowl de ovos com frango marinado e molho tanzaniano.",
  latitude: 28.3588,
  longitude: -81.5932,
},
{
  nome: "Savanna Sunrise Cart",
  regiao: "Africa",
  tipo: "Economico",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  ponte de acesso a Asia",
  precoMedio: 8,
  destaque: "PÃƒÂ£es simples, chÃƒÂ¡ e frutas secas. NÃƒÂ£o deixe de experimentar o pÃƒÂ£o doce de banana com gengibre.",
  latitude: 28.3587,
  longitude: -81.5933,
},

// Asia
{
  nome: "Yak & Yeti Local Foods CafÃƒÂ© (Breakfast)",
  regiao: "Asia",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado do Yak & Yeti Restaurant",
  precoMedio: 15,
  destaque: "Pratos asiÃƒÂ¡ticos para comeÃƒÂ§ar o dia. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che de ovo com salsicha asiÃƒÂ¡tica e molho agridoce.",
  latitude: 28.3581,
  longitude: -81.5914,
},
{
  nome: "Anandapur Ice Cream Truck (Morning Sweets)",
  regiao: "Asia",
  tipo: "Conforto",
  acesso: "Em frente ÃƒÂ  Expedition Everest",
  precoMedio: 10,
  destaque: "Sorvetes e doces refrescantes. NÃƒÂ£o deixe de experimentar o sorvete de coco com calda de maracujÃƒÂ¡.",
  latitude: 28.3579,
  longitude: -81.5916,
},
{
  nome: "Asia Greens",
  regiao: "Asia",
  tipo: "Saudavel",
  acesso: "Caminho para Maharajah Jungle Trek",
  precoMedio: 11,
  destaque: "Wraps, saladas e chÃƒÂ¡s com especiarias. NÃƒÂ£o deixe de experimentar o wrap de ovo com espinafre e curry leve.",
  latitude: 28.3578,
  longitude: -81.5913,
},
{
  nome: "Tea Cart Asia",
  regiao: "Asia",
  tipo: "Tematico",
  acesso: "Em frente ao templo da Jungle Trek",
  precoMedio: 9,
  destaque: "ChÃƒÂ¡s asiÃƒÂ¡ticos, bolinhos de arroz e pÃƒÂ£o de mel. NÃƒÂ£o deixe de experimentar o bolinho de arroz doce com recheio de ameixa.",
  latitude: 28.3577,
  longitude: -81.5917,
},
{
  nome: "Expedition Start",
  regiao: "Asia",
  tipo: "Economico",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada da Expedition Everest",
  precoMedio: 8,
  destaque: "Snacks rÃƒÂ¡pidos como muffins e frutas secas. NÃƒÂ£o deixe de experimentar o muffin de chÃƒÂ¡ verde com gotas de chocolate.",
  latitude: 28.3576,
  longitude: -81.5918,
},

// DinoLand U.S.A.
{
  nome: "Restaurantosaurus (Breakfast Combo)",
  regiao: "DinoLand U.S.A.",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o DINOSAUR",
  precoMedio: 14,
  destaque: "RefeiÃƒÂ§ÃƒÂ£o completa com tema de escavaÃƒÂ§ÃƒÂ£o. NÃƒÂ£o deixe de experimentar o combo com ovo, bacon e batata smile.",
  latitude: 28.3570,
  longitude: -81.5890,
},
{
  nome: "Dino Diner",
  regiao: "DinoLand U.S.A.",
  tipo: "Economico",
  acesso: "Perto do Fossil Fun Games",
  precoMedio: 9,
  destaque: "Wraps matinais e sucos de fruta. NÃƒÂ£o deixe de experimentar o wrap de ovo com queijo cheddar e ketchup doce.",
  latitude: 28.3568,
  longitude: -81.5888,
},
{
  nome: "Trilo-Bites (Breakfast Menu)",
  regiao: "DinoLand U.S.A.",
  tipo: "Conforto",
  acesso: "Perto da entrada para a ponte de Discovery Island",
  precoMedio: 10,
  destaque: "Snacks fritos e cafÃƒÂ©s fortes. NÃƒÂ£o deixe de experimentar os mini churros com cobertura de aÃƒÂ§ÃƒÂºcar e canela.",
  latitude: 28.3569,
  longitude: -81.5889,
},
{
  nome: "Dino Greens",
  regiao: "DinoLand U.S.A.",
  tipo: "Saudavel",
  acesso: "PrÃƒÂ³ximo ao playground The Boneyard",
  precoMedio: 11,
  destaque: "Wraps de proteÃƒÂ­na magra e bowls com frutas. NÃƒÂ£o deixe de experimentar o bowl de iogurte com morango e castanhas.",
  latitude: 28.3567,
  longitude: -81.5887,
},
{
  nome: "Fossil Fuel Cart",
  regiao: "DinoLand U.S.A.",
  tipo: "Tematico",
  acesso: "Ao lado da entrada do Primeval Whirl",
  precoMedio: 8,
  destaque: "Cereal, leite e cookies temÃƒÂ¡ticos. NÃƒÂ£o deixe de experimentar o cookie jurÃƒÂ¡ssico recheado com chocolate branco.",
  latitude: 28.3566,
  longitude: -81.5886,
},



  ];
