ï»¿export const  jantaresDisney = [
// Main Street, U.S.A.
{
  nome: "The Plaza Restaurant",
  regiao: "MainStreet",
  tipo: ["Classico", "Americano"],
  acesso: "Ao final da Main Street, com vista direta para o castelo",
  precoMedio: 32,
  destaque: "Jantar perfeito para assistir ao show Disney Enchantment. NÃƒÂ£o deixe de experimentar o hambÃƒÂºrguer artesanal com fritas crocantes.",
  latitude: 28.4189,
  longitude: -81.5826,
},
{
  nome: "CaseyÃ¢â‚¬â„¢s Corner",
  regiao: "MainStreet",
  tipo: "Economico",
  acesso: "Na esquina final da Main Street, com vista frontal do castelo",
  precoMedio: 17,
  destaque: "Ideal para jantar descontraÃƒÂ­do antes dos fogos. NÃƒÂ£o deixe de experimentar o hot dog com chili e queijo cheddar.",
  latitude: 28.4187,
  longitude: -81.5824,
},
{
  nome: "Crystal Palace",
  regiao: "MainStreet",
  tipo: "Tematico",
  acesso: "Em frente ao Plaza Hub, vista para o castelo",
  precoMedio: 45,
  destaque: "Buffet com personagens e janelas panorÃƒÂ¢micas. NÃƒÂ£o deixe de experimentar o frango assado com vegetais.",
  latitude: 28.4185,
  longitude: -81.5822,
},
{
  nome: "TonyÃ¢â‚¬â„¢s Town Square Restaurant",
  regiao: "MainStreet",
  tipo: "Conforto",
  acesso: "Logo apÃƒÂ³s a entrada principal do parque",
  precoMedio: 28,
  destaque: "Ambiente italiano acolhedor, perto da saÃƒÂ­da do parque. NÃƒÂ£o deixe de experimentar o espaguete com almÃƒÂ´ndegas.",
  latitude: 28.4184,
  longitude: -81.5819,
},
{
  nome: "Main Street Patio Bites",
  regiao: "MainStreet",
  tipo: "Saudavel",
  acesso: "Ao lado do Ice Cream Parlor",
  precoMedio: 15,
  destaque: "Lanches leves com vista iluminada do castelo. NÃƒÂ£o deixe de experimentar a salada Caesar com frango grelhado.",
  latitude: 28.4188,
  longitude: -81.5825,
},

// Adventureland
{
  nome: "Skipper Canteen",
  regiao: "Adventureland",
  tipo: "Tematico",
  acesso: "Ao lado da Jungle Cruise, com iluminaÃƒÂ§ÃƒÂ£o suave",
  precoMedio: 33,
  destaque: "Ambiente de expediÃƒÂ§ÃƒÂ£o ideal para a noite. NÃƒÂ£o deixe de experimentar o frango ao curry com arroz de coco.",
  latitude: 28.4181,
  longitude: -81.5843,
},
{
  nome: "Tortuga Tavern",
  regiao: "Adventureland",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente ÃƒÂ  Pirates of the Caribbean",
  precoMedio: 19,
  destaque: "Tema pirata com tochas e clima caribenho. NÃƒÂ£o deixe de experimentar o porco desfiado com arroz picante.",
  latitude: 28.4180,
  longitude: -81.5841,
},
{
  nome: "Sunshine Tree Terrace",
  regiao: "Adventureland",
  tipo: "Conforto",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  Magic Carpets of Aladdin",
  precoMedio: 11,
  destaque: "DoÃƒÂ§ura tropical com luz suave. NÃƒÂ£o deixe de experimentar o Dole Whip de laranja sob as lanternas.",
  latitude: 28.4178,
  longitude: -81.5839,
},
{
  nome: "Aloha Isle",
  regiao: "Adventureland",
  tipo: "Economico",
  acesso: "Em frente ÃƒÂ  Tiki Room",
  precoMedio: 9,
  destaque: "Lanche refrescante noturno. NÃƒÂ£o deixe de experimentar o sorvete de abacaxi com suco natural.",
  latitude: 28.4177,
  longitude: -81.5840,
},
{
  nome: "Tiki Snacks",
  regiao: "Adventureland",
  tipo: "Saudavel",
  acesso: "Ao lado do Aloha Isle",
  precoMedio: 12,
  destaque: "Snacks leves sob luzes tropicais. NÃƒÂ£o deixe de experimentar o wrap de frango com manga.",
  latitude: 28.4176,
  longitude: -81.5838,
},
// Frontierland
{
  nome: "Pecos Bill Tall Tale Inn and Cafe",
  regiao: "Frontierland",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Splash Mountain, com acesso fÃƒÂ¡cil ao hub central",
  precoMedio: 22,
  destaque: "Ambiente rÃƒÂºstico com boa iluminaÃƒÂ§ÃƒÂ£o interna. NÃƒÂ£o deixe de experimentar o burrito bowl com carne grelhada e guacamole.",
  latitude: 28.4174,
  longitude: -81.5853,
},
{
  nome: "Westward Ho",
  regiao: "Frontierland",
  tipo: "Economico",
  acesso: "Em frente ÃƒÂ  Country Bear Jamboree",
  precoMedio: 11,
  destaque: "Perfeito para um jantar rÃƒÂ¡pido com clima de faroeste. NÃƒÂ£o deixe de experimentar o milho cozido com manteiga e especiarias.",
  latitude: 28.4175,
  longitude: -81.5851,
},
{
  nome: "Country CookinÃ¢â‚¬â„¢",
  regiao: "Frontierland",
  tipo: "Conforto",
  acesso: "Nos fundos do Pecos Bill",
  precoMedio: 15,
  destaque: "ÃƒÂrea mais tranquila para jantar longe do fluxo principal. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che de frango empanado com molho barbecue.",
  latitude: 28.4172,
  longitude: -81.5849,
},
{
  nome: "Golden Trail Grill",
  regiao: "Frontierland",
  tipo: "Tematico",
  acesso: "PrÃƒÂ³ximo ao trilho do trem",
  precoMedio: 18,
  destaque: "Visual noturno com luzes ÃƒÂ¢mbar e decoraÃƒÂ§ÃƒÂ£o do Velho Oeste. NÃƒÂ£o deixe de experimentar o chili com pÃƒÂ£o de milho grelhado.",
  latitude: 28.4171,
  longitude: -81.5848,
},
{
  nome: "Prairie Greens",
  regiao: "Frontierland",
  tipo: "Saudavel",
  acesso: "Perto da Tom Sawyer Island",
  precoMedio: 14,
  destaque: "Saladas e wraps sob luz suave, prÃƒÂ³ximo ao rio. NÃƒÂ£o deixe de experimentar a salada de grÃƒÂ£o-de-bico com molho de iogurte.",
  latitude: 28.4173,
  longitude: -81.5850,
},
// Liberty Square
{
  nome: "Liberty Tree Tavern",
  regiao: "LibertySquare",
  tipo: "Tematico",
  acesso: "Perto da Haunted Mansion, com janelas iluminadas",
  precoMedio: 34,
  destaque: "Jantar colonial com ambiente de ÃƒÂ©poca perfeito ÃƒÂ  noite. NÃƒÂ£o deixe de experimentar o assado de peru com purÃƒÂª e molho caseiro.",
  latitude: 28.4190,
  longitude: -81.5834,
},
{
  nome: "The Diamond Horseshoe",
  regiao: "LibertySquare",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Liberty Tree Tavern",
  precoMedio: 30,
  destaque: "Saloon do velho oeste com iluminaÃƒÂ§ÃƒÂ£o dourada. NÃƒÂ£o deixe de experimentar o prato de brisket defumado com milho grelhado.",
  latitude: 28.4191,
  longitude: -81.5838,
},
{
  nome: "Columbia Harbour House",
  regiao: "LibertySquare",
  tipo: "Conforto",
  acesso: "Ao lado do Hall of Presidents",
  precoMedio: 21,
  destaque: "Lugar calmo e aconchegante para comer frutos do mar. NÃƒÂ£o deixe de experimentar o prato de salmÃƒÂ£o com arroz e legumes.",
  latitude: 28.4196,
  longitude: -81.5833,
},
{
  nome: "Liberty Snacks",
  regiao: "LibertySquare",
  tipo: "Economico",
  acesso: "PrÃƒÂ³ximo ao Liberty Square Riverboat",
  precoMedio: 10,
  destaque: "Snacks noturnos prÃƒÂ¡ticos com vista lateral para o hub. NÃƒÂ£o deixe de experimentar o pretzel recheado com cream cheese.",
  latitude: 28.4193,
  longitude: -81.5831,
},
{
  nome: "Revolution Greens",
  regiao: "LibertySquare",
  tipo: "Saudavel",
  acesso: "AtrÃƒÂ¡s da Liberty Tree Tavern",
  precoMedio: 13,
  destaque: "Saladas e wraps frescos em ambiente histÃƒÂ³rico. NÃƒÂ£o deixe de experimentar a salada morna de espinafre com frango grelhado.",
  latitude: 28.4192,
  longitude: -81.5835,
},
 // Fantasyland
{
  nome: "Be Our Guest Restaurant",
  regiao: "Fantasyland",
  tipo: "Tematico",
  acesso: "Dentro do castelo da Fera",
  precoMedio: 45,
  destaque: "Ambiente mÃƒÂ¡gico com salÃƒÂ£o iluminado por candelabros. NÃƒÂ£o deixe de experimentar o filet mignon com purÃƒÂª trufado.",
  latitude: 28.4203,
  longitude: -81.5805,
},
{
  nome: "CinderellaÃ¢â‚¬â„¢s Royal Table",
  regiao: "Fantasyland",
  tipo: ["Classico", "Americano"],
  acesso: "Dentro do Castelo da Cinderela",
  precoMedio: 62,
  destaque: "Jantar real com princesas e vista para o show noturno. NÃƒÂ£o deixe de experimentar o frango assado com molho de maÃƒÂ§ÃƒÂ£.",
  latitude: 28.4194,
  longitude: -81.5812,
},
{
  nome: "Pinocchio Village Haus",
  regiao: "Fantasyland",
  tipo: "Conforto",
  acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o ItÃ¢â‚¬â„¢s a Small World",
  precoMedio: 18,
  destaque: "Ideal para famÃƒÂ­lias, com janelas temÃƒÂ¡ticas e iluminaÃƒÂ§ÃƒÂ£o suave. NÃƒÂ£o deixe de experimentar o flatbread de pepperoni.",
  latitude: 28.4195,
  longitude: -81.5820,
},
{
  nome: "GastonÃ¢â‚¬â„¢s Tavern",
  regiao: "Fantasyland",
  tipo: "Economico",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  Under the Sea Ã¢â‚¬â€œ Journey of the Little Mermaid",
  precoMedio: 14,
  destaque: "RÃƒÂºstico e aconchegante para um lanche noturno. NÃƒÂ£o deixe de experimentar o cinnamon roll gigante do Gaston.",
  latitude: 28.4211,
  longitude: -81.5809,
},
{
  nome: "The FriarÃ¢â‚¬â„¢s Nook",
  regiao: "Fantasyland",
  tipo: "Saudavel",
  acesso: "Ao lado do carrossel do PrÃƒÂ­ncipe Encantado",
  precoMedio: 13,
  destaque: "Oferece opÃƒÂ§ÃƒÂµes leves e prÃƒÂ¡ticas ÃƒÂ  noite. NÃƒÂ£o deixe de experimentar o mac and cheese com bacon.",
  latitude: 28.4198,
  longitude: -81.5817,
},
// Tomorrowland
{
  nome: "Cosmic RayÃ¢â‚¬â„¢s Starlight CafÃƒÂ©",
  regiao: "Tomorrowland",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente ÃƒÂ  Buzz LightyearÃ¢â‚¬â„¢s Space Ranger Spin",
  precoMedio: 20,
  destaque: "EspaÃƒÂ§o amplo com palco iluminado por Sonny Eclipse. NÃƒÂ£o deixe de experimentar o cheeseburger duplo com onion rings.",
  latitude: 28.4200,
  longitude: -81.5792,
},
{
  nome: "The Lunching Pad",
  regiao: "Tomorrowland",
  tipo: "Economico",
  acesso: "Na base da Astro Orbiter",
  precoMedio: 11,
  destaque: "Para um lanche rÃƒÂ¡pido sob as luzes futuristas. NÃƒÂ£o deixe de experimentar o pretzel recheado com cream cheese.",
  latitude: 28.4201,
  longitude: -81.5793,
},
{
  nome: "Tomorrowland Terrace (se aberto)",
  regiao: "Tomorrowland",
  tipo: "Conforto",
  acesso: "Entre Main Street e Tomorrowland",
  precoMedio: 16,
  destaque: "Visual incrÃƒÂ­vel para o castelo e o show noturno. NÃƒÂ£o deixe de experimentar o frango com molho teriyaki.",
  latitude: 28.4193,
  longitude: -81.5801,
},
{
  nome: "Galactic Snacks",
  regiao: "Tomorrowland",
  tipo: "Tematico",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  Space Mountain",
  precoMedio: 13,
  destaque: "IluminaÃƒÂ§ÃƒÂ£o de LED e snacks sci-fi. NÃƒÂ£o deixe de experimentar o wrap galÃƒÂ¡ctico com frango grelhado e molho de mostarda doce.",
  latitude: 28.4202,
  longitude: -81.5794,
},
{
  nome: "Orbital Greens",
  regiao: "Tomorrowland",
  tipo: "Saudavel",
  acesso: "Ao lado do Space Ranger Spin",
  precoMedio: 17,
  destaque: "Saladas e bowls frios ideais para o fim do dia. NÃƒÂ£o deixe de experimentar o bowl de quinoa com legumes assados.",
  latitude: 28.4204,
  longitude: -81.5796,
},
// World Showcase
{
  nome: "La Hacienda de San Angel",
  regiao: "World Showcase",
  tipo: "Tematico",
  acesso: "PavilhÃƒÂ£o do MÃƒÂ©xico Ã¢â‚¬â€œ ÃƒÂ  beira do lago",
  precoMedio: 42,
  destaque: "Vista espetacular para o show noturno. NÃƒÂ£o deixe de experimentar os tacos de camarÃƒÂ£o com arroz de limÃƒÂ£o.",
  latitude: 28.3711,
  longitude: -81.5475,
},
{
  nome: "Les Chefs de France",
  regiao: "World Showcase",
  tipo: ["Classico", "Americano"],
  acesso: "PavilhÃƒÂ£o da FranÃƒÂ§a Ã¢â‚¬â€œ com janelas panorÃƒÂ¢micas",
  precoMedio: 39,
  destaque: "ClÃƒÂ¡ssico francÃƒÂªs com charme ÃƒÂ  luz baixa. NÃƒÂ£o deixe de experimentar o entrecÃƒÂ´te grelhado com batatas gratinadas.",
  latitude: 28.3705,
  longitude: -81.5502,
},
{
  nome: "Spice Road Table",
  regiao: "World Showcase",
  tipo: "Conforto",
  acesso: "PavilhÃƒÂ£o do Marrocos Ã¢â‚¬â€œ ÃƒÂ  margem do lago",
  precoMedio: 28,
  destaque: "Ideal para uma noite relaxante ÃƒÂ  beira dÃ¢â‚¬â„¢ÃƒÂ¡gua. NÃƒÂ£o deixe de experimentar o hummus trio com pÃƒÂ£o sÃƒÂ­rio tostado.",
  latitude: 28.3708,
  longitude: -81.5493,
},
{
  nome: "La Cantina de San Angel",
  regiao: "World Showcase",
  tipo: "Economico",
  acesso: "PavilhÃƒÂ£o do MÃƒÂ©xico Ã¢â‚¬â€œ na beira do lago, ao lado da pirÃƒÂ¢mide",
  precoMedio: 15,
  destaque: "Tacos e nachos em estilo fast casual. NÃƒÂ£o deixe de experimentar o combo de tacos com guacamole.",
  latitude: 28.3711,
  longitude: -81.5475,
},
{
  nome: "Tangierine CafÃƒÂ©",
  regiao: "World Showcase",
  tipo: "Saudavel",
  acesso: "PavilhÃƒÂ£o do Marrocos Ã¢â‚¬â€œ em frente ÃƒÂ  entrada da Fez House",
  precoMedio: 19,
  destaque: "Pratos mediterrÃƒÂ¢neos frescos e leves. NÃƒÂ£o deixe de provar o couscous com legumes grelhados e molho de limÃƒÂ£o.",
  latitude: 28.3708,
  longitude: -81.5493,
},

// World Discovery
{
  nome: "Space 220 Restaurant",
  regiao: "World Discovery",
  tipo: "Tematico",
  acesso: "Ao lado da Mission: SPACE",
  precoMedio: 55,
  destaque: "ExperiÃƒÂªncia imersiva em estaÃƒÂ§ÃƒÂ£o espacial. NÃƒÂ£o deixe de experimentar o frango grelhado com purÃƒÂª roxo e legumes.",
  latitude: 28.3735,
  longitude: -81.5480,
},
{
  nome: "Connections Eatery",
  regiao: "World Discovery",
  tipo: ["Classico", "Americano"],
  acesso: "PrÃƒÂ³ximo da Guardians of the Galaxy",
  precoMedio: 26,
  destaque: "Ambiente moderno e iluminado ÃƒÂ  noite. NÃƒÂ£o deixe de experimentar o hambÃƒÂºrguer gourmet com fritas de alho.",
  latitude: 28.3742,
  longitude: -81.5485,
},
{
  nome: "Test Track CafÃƒÂ©",
  regiao: "World Discovery",
  tipo: "Conforto",
  acesso: "Na saÃƒÂ­da da Test Track",
  precoMedio: 22,
  destaque: "Fast-casual com vibe futurista. NÃƒÂ£o deixe de experimentar o wrap de frango com pimenta defumada.",
  latitude: 28.3751,
  longitude: -81.5483,
},
{
  nome: "Mission Fuel CafÃƒÂ©",
  regiao: "World Discovery",
  tipo: "Economico",
  acesso: "Entre Test Track e Mission: SPACE",
  precoMedio: 14,
  destaque: "Para quem quer algo leve antes dos fogos. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che de roast beef com queijo.",
  latitude: 28.3749,
  longitude: -81.5482,
},
{
  nome: "Nova Greens",
  regiao: "World Discovery",
  tipo: "Saudavel",
  acesso: "ÃƒÂrea lateral da Cosmic Rewind",
  precoMedio: 17,
  destaque: "Saladas e bowls frescos sob luz azul. NÃƒÂ£o deixe de experimentar o bowl de salmÃƒÂ£o com arroz de couve-flor.",
  latitude: 28.3748,
  longitude: -81.5477,
},
// World Celebration
{
  nome: "Eats at the Epcot Experience",
  regiao: "World Celebration",
  tipo: "Conforto",
  acesso: "PavilhÃƒÂ£o central da Spaceship Earth",
  precoMedio: 20,
  destaque: "EspaÃƒÂ§o amplo, colorido e ideal para o fim do dia. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che de porco desfiado com coleslaw.",
  latitude: 28.3743,
  longitude: -81.5490,
},
{
  nome: "Sunshine Seasons (Jantar Estendido)",
  regiao: "World Celebration",
  tipo: "Saudavel",
  acesso: "Na base da Spaceship Earth",
  precoMedio: 16,
  destaque: "RefeiÃƒÂ§ÃƒÂµes rÃƒÂ¡pidas e nutritivas no coraÃƒÂ§ÃƒÂ£o do parque. NÃƒÂ£o deixe de experimentar o bowl asiÃƒÂ¡tico com tofu grelhado.",
  latitude: 28.3741,
  longitude: -81.5488,
},
{
  nome: "Center Plate CafÃƒÂ©",
  regiao: "World Celebration",
  tipo: ["Classico", "Americano"],
  acesso: "ÃƒÂrea entre Spaceship Earth e Dreamers Point",
  precoMedio: 25,
  destaque: "Boa iluminaÃƒÂ§ÃƒÂ£o e clima elegante. NÃƒÂ£o deixe de experimentar o prato de frango com legumes assados.",
  latitude: 28.3740,
  longitude: -81.5492,
},
{
  nome: "Visionary Bites",
  regiao: "World Celebration",
  tipo: "Economico",
  acesso: "Ao lado do Connections CafÃƒÂ©",
  precoMedio: 12,
  destaque: "RÃƒÂ¡pido e saboroso com ÃƒÂ¡rea coberta. NÃƒÂ£o deixe de experimentar o wrap de salada Caesar com frango grelhado.",
  latitude: 28.3744,
  longitude: -81.5487,
},
{
  nome: "DreamerÃ¢â‚¬â„¢s Garden Grill",
  regiao: "World Celebration",
  tipo: "Tematico",
  acesso: "Perto do Dreamers Point, vista para jardins noturnos",
  precoMedio: 30,
  destaque: "Ambiente tranquilo e bem decorado. NÃƒÂ£o deixe de experimentar o risoto de cogumelos com ervas frescas.",
  latitude: 28.3746,
  longitude: -81.5493,
},
// World Nature
{
  nome: "Coral Reef Restaurant",
  regiao: "World Nature",
  tipo: "Tematico",
  acesso: "Ao lado da The Seas with Nemo & Friends",
  precoMedio: 42,
  destaque: "Tanques de aquÃƒÂ¡rio iluminados tornam o jantar mÃƒÂ¡gico. NÃƒÂ£o deixe de experimentar o filÃƒÂ© de peixe com purÃƒÂª de batata ao limÃƒÂ£o.",
  latitude: 28.3732,
  longitude: -81.5501,
},
{
  nome: "The Land Grill CafÃƒÂ©",
  regiao: "World Nature",
  tipo: ["Classico", "Americano"],
  acesso: "Dentro do pavilhÃƒÂ£o The Land",
  precoMedio: 22,
  destaque: "Ambiente iluminado e bem ventilado ÃƒÂ  noite. NÃƒÂ£o deixe de experimentar o frango grelhado com vegetais colhidos no pavilhÃƒÂ£o.",
  latitude: 28.3725,
  longitude: -81.5503,
},
{
  nome: "Living Greens",
  regiao: "World Nature",
  tipo: "Saudavel",
  acesso: "ÃƒÂrea interna do The Land",
  precoMedio: 17,
  destaque: "Pratos vegetarianos e bowls com produtos frescos. NÃƒÂ£o deixe de experimentar o bowl de quinoa com manga e abacate.",
  latitude: 28.3723,
  longitude: -81.5502,
},
{
  nome: "Nemo Snacks",
  regiao: "World Nature",
  tipo: "Economico",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada da atraÃƒÂ§ÃƒÂ£o do Nemo",
  precoMedio: 10,
  destaque: "Snacks rÃƒÂ¡pidos com vista do pÃƒÂ´r do sol. NÃƒÂ£o deixe de experimentar o pÃƒÂ£o pita com homus de cenoura.",
  latitude: 28.3734,
  longitude: -81.5504,
},
{
  nome: "Moana Island Grill",
  regiao: "World Nature",
  tipo: "Conforto",
  acesso: "Na ÃƒÂ¡rea do novo Journey of Water",
  precoMedio: 20,
  destaque: "TemÃƒÂ¡tica de ilha e iluminaÃƒÂ§ÃƒÂ£o natural. NÃƒÂ£o deixe de experimentar o prato de arroz havaiano com frango grelhado.",
  latitude: 28.3729,
  longitude: -81.5500,
},
// Hollywood Boulevard
{
  nome: "The Hollywood Brown Derby",
  regiao: "Hollywood Boulevard",
  tipo: ["Classico", "Americano"],
  acesso: "No final do boulevard principal, ÃƒÂ  esquerda",
  precoMedio: 48,
  destaque: "Ambiente clÃƒÂ¡ssico de Hollywood com luz ambiente elegante. NÃƒÂ£o deixe de experimentar o Cobb Salad original da casa.",
  latitude: 28.3571,
  longitude: -81.5584,
},
{
  nome: "The Trolley Car CafÃƒÂ©",
  regiao: "Hollywood Boulevard",
  tipo: "Economico",
  acesso: "Ao lado da entrada do parque",
  precoMedio: 12,
  destaque: "Ideal para um jantar rÃƒÂ¡pido com bebidas e sanduÃƒÂ­ches. NÃƒÂ£o deixe de experimentar o panini de presunto com queijo suÃƒÂ­ÃƒÂ§o.",
  latitude: 28.3574,
  longitude: -81.5585,
},
{
  nome: "OscarÃ¢â‚¬â„¢s CafÃƒÂ©",
  regiao: "Hollywood Boulevard",
  tipo: "Conforto",
  acesso: "PrÃƒÂ³ximo ao Crossroads of the World",
  precoMedio: 18,
  destaque: "CafÃƒÂ© clÃƒÂ¡ssico com bancos externos iluminados. NÃƒÂ£o deixe de experimentar o hambÃƒÂºrguer grelhado com batatas fritas.",
  latitude: 28.3572,
  longitude: -81.5583,
},
{
  nome: "Studio Souvenirs Bites",
  regiao: "Hollywood Boulevard",
  tipo: "Saudavel",
  acesso: "Entre lojas temÃƒÂ¡ticas do inÃƒÂ­cio da avenida",
  precoMedio: 14,
  destaque: "Snacks leves e wraps frescos. NÃƒÂ£o deixe de experimentar o wrap vegetariano com molho de iogurte.",
  latitude: 28.3573,
  longitude: -81.5586,
},
{
  nome: "Brown Derby Lounge",
  regiao: "Hollywood Boulevard",
  tipo: "Tematico",
  acesso: "ÃƒÂrea externa do Brown Derby, com vista para o boulevard",
  precoMedio: 29,
  destaque: "CoquetÃƒÂ©is e porÃƒÂ§ÃƒÂµes sob luzes de toldo. NÃƒÂ£o deixe de experimentar as mini costelas com molho barbecue.",
  latitude: 28.3570,
  longitude: -81.5582,
},

// Echo Lake
{
  nome: "50Ã¢â‚¬â„¢s Prime Time CafÃƒÂ©",
  regiao: "Echo Lake",
  tipo: "Tematico",
  acesso: "Ao lado do lago, prÃƒÂ³ximo ÃƒÂ  Indiana Jones",
  precoMedio: 35,
  destaque: "Ambiente retrÃƒÂ´ com garÃƒÂ§ons interagindo. NÃƒÂ£o deixe de experimentar o frango frito com purÃƒÂª de batata.",
  latitude: 28.3567,
  longitude: -81.5595,
},
{
  nome: "Backlot Express",
  regiao: "Echo Lake",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Star Tours",
  precoMedio: 20,
  destaque: "Jantar prÃƒÂ¡tico com mesas internas e externas. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che cubano.",
  latitude: 28.3570,
  longitude: -81.5590,
},
{
  nome: "Dockside Diner",
  regiao: "Echo Lake",
  tipo: "Conforto",
  acesso: "Ãƒâ‚¬ beira do lago, com vista temÃƒÂ¡tica",
  precoMedio: 16,
  destaque: "IluminaÃƒÂ§ÃƒÂ£o noturna linda ao redor do barco. NÃƒÂ£o deixe de experimentar o hot dog de camarÃƒÂ£o com molho cremoso.",
  latitude: 28.3569,
  longitude: -81.5593,
},
{
  nome: "Echo Snacks",
  regiao: "Echo Lake",
  tipo: "Economico",
  acesso: "Perto do Gertie the Dinosaur",
  precoMedio: 10,
  destaque: "Snacks rÃƒÂ¡pidos sob refletores antigos. NÃƒÂ£o deixe de experimentar o pretzel com cheddar e bacon.",
  latitude: 28.3571,
  longitude: -81.5591,
},
{
  nome: "Lakeside Greens",
  regiao: "Echo Lake",
  tipo: "Saudavel",
  acesso: "PrÃƒÂ³ximo ao Indiana Jones Epic Stunt Show",
  precoMedio: 15,
  destaque: "Saladas e wraps ÃƒÂ  beira do lago. NÃƒÂ£o deixe de experimentar a salada de frango grelhado com vinagrete cÃƒÂ­trico.",
  latitude: 28.3568,
  longitude: -81.5594,
},

// Grand Avenue
{
  nome: "Mama MelroseÃ¢â‚¬â„¢s Ristorante Italiano",
  regiao: "Grand Avenue",
  tipo: ["Classico", "Americano"],
  acesso: "Dentro do Muppet Courtyard",
  precoMedio: 36,
  destaque: "Jantar italiano com clima acolhedor. NÃƒÂ£o deixe de experimentar o frango ÃƒÂ  parmegiana com spaghetti.",
  latitude: 28.3557,
  longitude: -81.5611,
},
{
  nome: "PizzeRizzo",
  regiao: "Grand Avenue",
  tipo: "Economico",
  acesso: "Ao lado dos Muppets",
  precoMedio: 14,
  destaque: "Ambiente divertido com pizza rÃƒÂ¡pida. NÃƒÂ£o deixe de experimentar a pizza pepperoni com massa fina.",
  latitude: 28.3556,
  longitude: -81.5610,
},
{
  nome: "Grand Greens",
  regiao: "Grand Avenue",
  tipo: "Saudavel",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada do Muppet Vision 3D",
  precoMedio: 15,
  destaque: "RefeiÃƒÂ§ÃƒÂµes leves e prÃƒÂ¡ticas. NÃƒÂ£o deixe de experimentar o bowl mediterrÃƒÂ¢neo com grÃƒÂ£o-de-bico.",
  latitude: 28.3555,
  longitude: -81.5609,
},
{
  nome: "RizzoÃ¢â‚¬â„¢s Rooftop",
  regiao: "Grand Avenue",
  tipo: "Tematico",
  acesso: "No andar superior do PizzeRizzo",
  precoMedio: 22,
  destaque: "Vista elevada com decoraÃƒÂ§ÃƒÂ£o dos Muppets. NÃƒÂ£o deixe de experimentar a lasanha com ricota e espinafre.",
  latitude: 28.3554,
  longitude: -81.5608,
},
{
  nome: "Backlot Bites",
  regiao: "Grand Avenue",
  tipo: "Conforto",
  acesso: "Na transiÃƒÂ§ÃƒÂ£o para GalaxyÃ¢â‚¬â„¢s Edge",
  precoMedio: 18,
  destaque: "Perfeito para jantar antes da ÃƒÂ¡rea Star Wars. NÃƒÂ£o deixe de experimentar o hambÃƒÂºrguer artesanal com bacon.",
  latitude: 28.3558,
  longitude: -81.5612,
},

// Star Wars: GalaxyÃ¢â‚¬â„¢s Edge
{
  nome: "Docking Bay 7 Food and Cargo",
  regiao: "GalaxyÃ¢â‚¬â„¢s Edge",
  tipo: "Tematico",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  Millennium Falcon",
  precoMedio: 28,
  destaque: "Ambiente imersivo com pratos galÃƒÂ¡cticos. NÃƒÂ£o deixe de experimentar o frango assado Endorian com purÃƒÂª de batata.",
  latitude: 28.3550,
  longitude: -81.5619,
},
{
  nome: "Ronto Roasters",
  regiao: "GalaxyÃ¢â‚¬â„¢s Edge",
  tipo: ["Classico", "Americano"],
  acesso: "Na praÃƒÂ§a central de Batuu",
  precoMedio: 16,
  destaque: "SanduÃƒÂ­ches famosos com tema sci-fi. NÃƒÂ£o deixe de experimentar o Ronto Wrap com linguiÃƒÂ§a defumada e porco.",
  latitude: 28.3552,
  longitude: -81.5617,
},
{
  nome: "Kat SakaÃ¢â‚¬â„¢s Kettle",
  regiao: "GalaxyÃ¢â‚¬â„¢s Edge",
  tipo: "Economico",
  acesso: "Ao lado do mercado Black Spire",
  precoMedio: 9,
  destaque: "Pipocas galÃƒÂ¡cticas com sabores ÃƒÂºnicos. NÃƒÂ£o deixe de experimentar a pipoca doce picante vermelha e roxa.",
  latitude: 28.3553,
  longitude: -81.5618,
},
{
  nome: "Galactic Greens",
  regiao: "GalaxyÃ¢â‚¬â„¢s Edge",
  tipo: "Saudavel",
  acesso: "AtrÃƒÂ¡s do droid depot",
  precoMedio: 17,
  destaque: "Saladas criativas com ingredientes exÃƒÂ³ticos. NÃƒÂ£o deixe de experimentar o bowl de vegetais grelhados com molho azul.",
  latitude: 28.3551,
  longitude: -81.5616,
},
{
  nome: "Batuu Bites",
  regiao: "GalaxyÃ¢â‚¬â„¢s Edge",
  tipo: "Conforto",
  acesso: "Entre a loja do sabre de luz e o mercado",
  precoMedio: 19,
  destaque: "Pratos rÃƒÂ¡pidos e saborosos inspirados em Star Wars. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che de frango picante com chips de raiz.",
  latitude: 28.3549,
  longitude: -81.5615,
},

// Toy Story Land
{
  nome: "WoodyÃ¢â‚¬â„¢s Lunch Box",
  regiao: "Toy Story Land",
  tipo: "Tematico",
  acesso: "Centro da Toy Story Land",
  precoMedio: 18,
  destaque: "CardÃƒÂ¡pio divertido com visual vibrante. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che de brisket com queijo cheddar.",
  latitude: 28.3543,
  longitude: -81.5627,
},
{
  nome: "Buzz LightyearÃ¢â‚¬â„¢s Grill",
  regiao: "Toy Story Land",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado do Alien Swirling Saucers",
  precoMedio: 21,
  destaque: "Comida americana em ambiente intergalÃƒÂ¡ctico. NÃƒÂ£o deixe de experimentar o hambÃƒÂºrguer de frango com batata canoa.",
  latitude: 28.3544,
  longitude: -81.5626,
},
{
  nome: "JessieÃ¢â‚¬â„¢s Rodeo Wraps",
  regiao: "Toy Story Land",
  tipo: "Conforto",
  acesso: "Perto do Toy Story Mania",
  precoMedio: 17,
  destaque: "Lanches rÃƒÂ¡pidos com tema caipira. NÃƒÂ£o deixe de experimentar o wrap de carne com molho barbecue.",
  latitude: 28.3542,
  longitude: -81.5628,
},
{
  nome: "Andy's Snacks",
  regiao: "Toy Story Land",
  tipo: "Economico",
  acesso: "Entre a entrada da ÃƒÂ¡rea e a Slinky Dog Dash",
  precoMedio: 10,
  destaque: "Snacks divertidos para o fim do dia. NÃƒÂ£o deixe de experimentar o cookie de marshmallow com gotas de chocolate.",
  latitude: 28.3541,
  longitude: -81.5625,
},
{
  nome: "Toy Greens",
  regiao: "Toy Story Land",
  tipo: "Saudavel",
  acesso: "AtrÃƒÂ¡s do Alien Swirling Saucers",
  precoMedio: 15,
  destaque: "OpÃƒÂ§ÃƒÂµes leves e nutritivas no mundo dos brinquedos. NÃƒÂ£o deixe de experimentar o bowl de frango com salada tropical.",
  latitude: 28.3545,
  longitude: -81.5629,
},

// Animation Courtyard
{
  nome: "AnimatorÃ¢â‚¬â„¢s CafÃƒÂ©",
  regiao: "Animation Courtyard",
  tipo: "Tematico",
  acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o Disney Junior",
  precoMedio: 26,
  destaque: "Jantar leve com animaÃƒÂ§ÃƒÂµes clÃƒÂ¡ssicas nas telas. NÃƒÂ£o deixe de experimentar a massa primavera com molho de tomate fresco.",
  latitude: 28.3550,
  longitude: -81.5601,
},
{
  nome: "Toon Bites",
  regiao: "Animation Courtyard",
  tipo: "Economico",
  acesso: "Perto da entrada da ÃƒÂ¡rea de Star Wars",
  precoMedio: 11,
  destaque: "Snacks com tema de desenhos. NÃƒÂ£o deixe de experimentar a pipoca colorida e o suco de frutas congelado.",
  latitude: 28.3549,
  longitude: -81.5600,
},
{
  nome: "Courtyard Grill",
  regiao: "Animation Courtyard",
  tipo: ["Classico", "Americano"],
  acesso: "Na saÃƒÂ­da da atraÃƒÂ§ÃƒÂ£o do Star Wars Launch Bay",
  precoMedio: 23,
  destaque: "ClÃƒÂ¡ssico americano com sombra e espaÃƒÂ§o. NÃƒÂ£o deixe de experimentar o cheeseburger com molho especial.",
  latitude: 28.3548,
  longitude: -81.5602,
},
{
  nome: "Disney Junior CafÃƒÂ©",
  regiao: "Animation Courtyard",
  tipo: "Conforto",
  acesso: "AtrÃƒÂ¡s da loja da Disney Junior",
  precoMedio: 15,
  destaque: "Lugar para pais descansarem com refeiÃƒÂ§ÃƒÂµes simples. NÃƒÂ£o deixe de experimentar o mac and cheese com legumes.",
  latitude: 28.3551,
  longitude: -81.5603,
},
{
  nome: "Animation Greens",
  regiao: "Animation Courtyard",
  tipo: "Saudavel",
  acesso: "Ao lado do AnimatorÃ¢â‚¬â„¢s CafÃƒÂ©",
  precoMedio: 14,
  destaque: "Wraps e bowls com temÃƒÂ¡tica de desenhos animados. NÃƒÂ£o deixe de experimentar o bowl vegetariano com manga e molho cÃƒÂ­trico.",
  latitude: 28.3552,
  longitude: -81.5604,
},

// Sunset Boulevard
{
  nome: "Hollywood Scoops Grill",
  regiao: "Sunset Boulevard",
  tipo: ["Classico", "Americano"],
  acesso: "No inÃƒÂ­cio da Sunset Boulevard",
  precoMedio: 24,
  destaque: "ClÃƒÂ¡ssico americano em ambiente iluminado. NÃƒÂ£o deixe de experimentar o cheeseburger com molho de alho.",
  latitude: 28.3539,
  longitude: -81.5606,
},
{
  nome: "Sunset Ranch Market",
  regiao: "Sunset Boulevard",
  tipo: "Economico",
  acesso: "PrÃƒÂ³ximo ao Fantasmic!",
  precoMedio: 13,
  destaque: "Ideal para comer algo rÃƒÂ¡pido antes do show. NÃƒÂ£o deixe de experimentar o taco de frango grelhado.",
  latitude: 28.3540,
  longitude: -81.5605,
},
{
  nome: "Fairfax Fare",
  regiao: "Sunset Boulevard",
  tipo: "Tematico",
  acesso: "No meio da Sunset Boulevard",
  precoMedio: 20,
  destaque: "Ambiente de feira californiana. NÃƒÂ£o deixe de experimentar o bowl de carne ao estilo barbecue.",
  latitude: 28.3541,
  longitude: -81.5607,
},
{
  nome: "Sunset Snacks",
  regiao: "Sunset Boulevard",
  tipo: "Conforto",
  acesso: "Ao lado do Tower of Terror",
  precoMedio: 17,
  destaque: "Snacks e doces para o fim do dia. NÃƒÂ£o deixe de experimentar o churro recheado com doce de leite.",
  latitude: 28.3542,
  longitude: -81.5608,
},
{
  nome: "Boulevard Greens",
  regiao: "Sunset Boulevard",
  tipo: "Saudavel",
  acesso: "Ao lado do Rock Ã¢â‚¬ËœnÃ¢â‚¬â„¢ Roller Coaster",
  precoMedio: 15,
  destaque: "RefeiÃƒÂ§ÃƒÂµes leves com mÃƒÂºsica ao fundo. NÃƒÂ£o deixe de experimentar o wrap de atum com ervas e molho iogurte.",
  latitude: 28.3543,
  longitude: -81.5609,
},
// Oasis
{
  nome: "Oasis Comfort CafÃƒÂ©",
  regiao: "Oasis",
  tipo: "Conforto",
  acesso: "Entre o Rainforest CafÃƒÂ© e o inÃƒÂ­cio da trilha para Discovery Island",
  precoMedio: 16,
  destaque: "Ambiente tranquilo com pratos caseiros, como mac and cheese, frango grelhado e sopa do dia. NÃƒÂ£o deixe de experimentar o mac and cheese cremoso com pÃƒÂ£o de alho.",
  latitude: 28.3551,
  longitude: -81.5916,
},

{
  nome: "Oasis Diner",
  regiao: "Oasis",
  tipo: ["Classico", "Americano"],
  acesso: "PrÃƒÂ³ximo ÃƒÂ  ponte para Discovery Island, ao lado do Oasis Snacks",
  precoMedio: 20,
  destaque: "Pratos clÃƒÂ¡ssicos americanos como hambÃƒÂºrguer, cheeseburger, milk-shake e batata frita. NÃƒÂ£o deixe de experimentar o cheeseburger com bacon crocante e o milk-shake de baunilha.",
  latitude: 28.3552,
  longitude: -81.5911,
},
{
  nome: "Rainforest CafÃƒÂ© - Entrada Animal Kingdom",
  regiao: "Oasis",
  tipo: "Tematico",
  acesso: "Logo na entrada principal do parque",
  precoMedio: 36,
  destaque: "Ambiente de floresta tropical com sons da natureza. NÃƒÂ£o deixe de experimentar o churrasco misto com arroz e feijÃƒÂ£o preto.",
  latitude: 28.3556,
  longitude: -81.5913,
},
{
  nome: "Oasis Snacks",
  regiao: "Oasis",
  tipo: "Economico",
  acesso: "Ao lado da ponte para Discovery Island",
  precoMedio: 10,
  destaque: "Snacks rÃƒÂ¡pidos antes do show Rivers of Light. NÃƒÂ£o deixe de experimentar a pipoca com manteiga trufada.",
  latitude: 28.3555,
  longitude: -81.5912,
},
{
  nome: "Oasis Greens",
  regiao: "Oasis",
  tipo: "Saudavel",
  acesso: "Entre as trilhas iniciais do parque",
  precoMedio: 15,
  destaque: "OpÃƒÂ§ÃƒÂµes saudÃƒÂ¡veis com vista para vegetaÃƒÂ§ÃƒÂ£o tropical. NÃƒÂ£o deixe de experimentar o wrap de salmÃƒÂ£o com ervas.",
  latitude: 28.3554,
  longitude: -81.5914,
},
// Discovery Island
{
  nome: "Discovery Grill",
  regiao: "Discovery Island",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente ao Tree of Life, ao lado do Creature Comforts",
  precoMedio: 22,
  destaque: "Lanches clÃƒÂ¡ssicos americanos: hambÃƒÂºrguer, fritas crocantes, milk-shake e nuggets. NÃƒÂ£o deixe de experimentar o cheeseburger artesanal com bacon e o milk-shake de baunilha.",
  latitude: 28.3605,
  longitude: -81.5901,
},

{
  nome: "Tiffins Restaurant",
  regiao: "Discovery Island",
  tipo: "Tematico",
  acesso: "Perto da entrada de Pandora, com vista para o rio",
  precoMedio: 49,
  destaque: "Jantar refinado com pratos globais e luz ambiente. NÃƒÂ£o deixe de experimentar o polvo grelhado com purÃƒÂª de batata doce.",
  latitude: 28.3565,
  longitude: -81.5919,
},
{
  nome: "Creature Comforts",
  regiao: "Discovery Island",
  tipo: "Conforto",
  acesso: "Ao lado da ponte principal para a Tree of Life",
  precoMedio: 18,
  destaque: "CafÃƒÂ© com sanduÃƒÂ­ches e doces. NÃƒÂ£o deixe de experimentar o croissant de presunto com queijo suÃƒÂ­ÃƒÂ§o derretido.",
  latitude: 28.3568,
  longitude: -81.5917,
},
{
  nome: "Island Snacks",
  regiao: "Discovery Island",
  tipo: "Economico",
  acesso: "Frente da Tree of Life",
  precoMedio: 10,
  destaque: "Snacks rÃƒÂ¡pidos com ambiente iluminado. NÃƒÂ£o deixe de experimentar o pretzel com cheddar e mostarda.",
  latitude: 28.3569,
  longitude: -81.5915,
},
{
  nome: "Tree Greens",
  regiao: "Discovery Island",
  tipo: "Saudavel",
  acesso: "Caminho lateral para a ponte de Asia",
  precoMedio: 16,
  destaque: "Bowls naturais e smoothies. NÃƒÂ£o deixe de experimentar a salada de quinoa com manga e amÃƒÂªndoas.",
  latitude: 28.3566,
  longitude: -81.5913,
},

//Pandora Ã¢â‚¬â€œ The World of Avatar
{
  nome: "SatuÃ¢â‚¬â„¢li Canteen",
  regiao: "Pandora",
  tipo: "Tematico",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  atraÃƒÂ§ÃƒÂ£o Flight of Passage",
  precoMedio: 27,
  destaque: "Ambiente imersivo e pratos inspirados em Pandora. NÃƒÂ£o deixe de experimentar o bowl de carne com legumes assados e molho de ervas.",
  latitude: 28.3553,
  longitude: -81.5922,
},
{
  nome: "Pongu Pongu",
  regiao: "Pandora",
  tipo: "Economico",
  acesso: "Na entrada da ÃƒÂ¡rea, ao lado do SatuÃ¢â‚¬â„¢li",
  precoMedio: 11,
  destaque: "Drinks e snacks alienÃƒÂ­genas. NÃƒÂ£o deixe de experimentar o pÃƒÂ£o doce recheado com creme de abacaxi.",
  latitude: 28.3552,
  longitude: -81.5921,
},
{
  nome: "Avatar Greens",
  regiao: "Pandora",
  tipo: "Saudavel",
  acesso: "Trilha lateral prÃƒÂ³xima ao NaÃ¢â‚¬â„¢vi River Journey",
  precoMedio: 15,
  destaque: "OpÃƒÂ§ÃƒÂµes leves com temÃƒÂ¡tica natural. NÃƒÂ£o deixe de experimentar o bowl de tofu com legumes coloridos.",
  latitude: 28.3551,
  longitude: -81.5923,
},
{
  nome: "Pandora Grill",
  regiao: "Pandora",
  tipo: "Conforto",
  acesso: "AtrÃƒÂ¡s do SatuÃ¢â‚¬â„¢li Canteen",
  precoMedio: 19,
  destaque: "SanduÃƒÂ­ches quentes em ambiente iluminado. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che de frango com molho cÃƒÂ­trico.",
  latitude: 28.3554,
  longitude: -81.5920,
},
{
  nome: "NaÃ¢â‚¬â„¢vi Bites",
  regiao: "Pandora",
  tipo: ["Classico", "Americano"],
  acesso: "Caminho para o Flight of Passage",
  precoMedio: 22,
  destaque: "Comida rÃƒÂ¡pida com clima noturno de Pandora. NÃƒÂ£o deixe de experimentar o hambÃƒÂºrguer vegetal com batata doce frita.",
  latitude: 28.3550,
  longitude: -81.5924,
},
// Africa
{
  nome: "Tusker House Restaurant",
  regiao: "Africa",
  tipo: "Tematico",
  acesso: "Perto da ponte principal da ÃƒÂ¡rea",
  precoMedio: 42,
  destaque: "Buffet africano com personagens. NÃƒÂ£o deixe de experimentar o frango ao molho de amendoim com arroz de coco.",
  latitude: 28.3548,
  longitude: -81.5931,
},
{
  nome: "Harambe Market",
  regiao: "Africa",
  tipo: ["Classico", "Americano"],
  acesso: "Centro da vila Harambe",
  precoMedio: 22,
  destaque: "Pratos africanos rÃƒÂ¡pidos ao ar livre. NÃƒÂ£o deixe de experimentar o espeto de carne bovina com molho picante.",
  latitude: 28.3549,
  longitude: -81.5930,
},
{
  nome: "Dawa Bar",
  regiao: "Africa",
  tipo: "Conforto",
  acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada do Kilimanjaro Safaris",
  precoMedio: 18,
  destaque: "Drinks e petiscos sob luzes de vila africana. NÃƒÂ£o deixe de experimentar o espetinho de frango com molho tamarindo.",
  latitude: 28.3547,
  longitude: -81.5932,
},
{
  nome: "Harambe Snacks",
  regiao: "Africa",
  tipo: "Economico",
  acesso: "Em frente ao Harambe Market",
  precoMedio: 11,
  destaque: "Lanches africanos para comer andando. NÃƒÂ£o deixe de experimentar a samosa de carne.",
  latitude: 28.3550,
  longitude: -81.5929,
},
{
  nome: "Safari Greens",
  regiao: "Africa",
  tipo: "Saudavel",
  acesso: "PrÃƒÂ³ximo ao Mombasa Marketplace",
  precoMedio: 15,
  destaque: "Saladas e bowls com toque africano. NÃƒÂ£o deixe de experimentar o bowl de lentilha com legumes grelhados.",
  latitude: 28.3546,
  longitude: -81.5933,
},
// Asia
{
  nome: "Yak & Yeti Restaurant",
  regiao: "Asia",
  tipo: "Tematico",
  acesso: "Ao lado da Expedition Everest",
  precoMedio: 38,
  destaque: "Jantar asiÃƒÂ¡tico com ambiente aconchegante. NÃƒÂ£o deixe de experimentar o frango com castanha e legumes orientais.",
  latitude: 28.3539,
  longitude: -81.5942,
},
{
  nome: "Yak & Yeti Local Food Cafes",
  regiao: "Asia",
  tipo: "Economico",
  acesso: "Em frente ao restaurante principal",
  precoMedio: 14,
  destaque: "Pratos rÃƒÂ¡pidos e saborosos da ÃƒÂsia. NÃƒÂ£o deixe de experimentar o arroz com frango teriyaki.",
  latitude: 28.3540,
  longitude: -81.5941,
},
{
  nome: "Thirsty River Bar & Trek Snacks",
  regiao: "Asia",
  tipo: "Conforto",
  acesso: "Na saÃƒÂ­da da Expedition Everest",
  precoMedio: 17,
  destaque: "Drinks e snacks com vista para a montanha. NÃƒÂ£o deixe de experimentar o mix de nozes e frutas secas.",
  latitude: 28.3538,
  longitude: -81.5940,
},
{
  nome: "Anandapur Greens",
  regiao: "Asia",
  tipo: "Saudavel",
  acesso: "Caminho para o Kali River Rapids",
  precoMedio: 15,
  destaque: "Bowls leves e opÃƒÂ§ÃƒÂµes veganas. NÃƒÂ£o deixe de experimentar o bowl de grÃƒÂ£o-de-bico com molho curry.",
  latitude: 28.3541,
  longitude: -81.5943,
},
{
  nome: "Asia Bites",
  regiao: "Asia",
  tipo: ["Classico", "Americano"],
  acesso: "PrÃƒÂ³ximo ao Maharajah Jungle Trek",
  precoMedio: 20,
  destaque: "Pratos tradicionais em ambiente asiÃƒÂ¡tico. NÃƒÂ£o deixe de experimentar o curry de frango tailandÃƒÂªs com arroz de jasmim.",
  latitude: 28.3542,
  longitude: -81.5944,
},
// DinoLand U.S.A.
{
  nome: "Restaurantosaurus",
  regiao: "DinoLand",
  tipo: ["Classico", "Americano"],
  acesso: "Centro da DinoLand, ao lado do Boneyard",
  precoMedio: 21,
  destaque: "Ambiente divertido com tema de paleontologia. NÃƒÂ£o deixe de experimentar o hambÃƒÂºrguer de bacon com queijo cheddar.",
  latitude: 28.3544,
  longitude: -81.5950,
},
{
  nome: "Dino Diner",
  regiao: "DinoLand",
  tipo: "Economico",
  acesso: "Ao lado da TriceraTop Spin",
  precoMedio: 11,
  destaque: "Comida rÃƒÂ¡pida em trailer temÃƒÂ¡tico. NÃƒÂ£o deixe de experimentar o hot dog com batata frita.",
  latitude: 28.3545,
  longitude: -81.5951,
},
{
  nome: "Fossil Fuel Snacks",
  regiao: "DinoLand",
  tipo: "Conforto",
  acesso: "Perto do Fossil Fun Games",
  precoMedio: 15,
  destaque: "Snacks doces e salgados. NÃƒÂ£o deixe de experimentar o sundae de chocolate com cookies.",
  latitude: 28.3546,
  longitude: -81.5952,
},
{
  nome: "Dino Greens",
  regiao: "DinoLand",
  tipo: "Saudavel",
  acesso: "Ao lado do restaurante Restaurantosaurus",
  precoMedio: 14,
  destaque: "Saladas e wraps refrescantes. NÃƒÂ£o deixe de experimentar a salada com frango grelhado e molho de mel.",
  latitude: 28.3547,
  longitude: -81.5953,
},
{
  nome: "Boneyard Bites",
  regiao: "DinoLand",
  tipo: "Tematico",
  acesso: "Na saÃƒÂ­da da ÃƒÂ¡rea de escavaÃƒÂ§ÃƒÂ£o infantil",
  precoMedio: 18,
  destaque: "Pratos criativos com decoraÃƒÂ§ÃƒÂ£o de dinossauro. NÃƒÂ£o deixe de experimentar o sanduÃƒÂ­che de carne defumada com cheddar.",
  latitude: 28.3548,
  longitude: -81.5954,
},

  ];
