export const  jantaresDisney = [
// Main Street, U.S.A.
{
  nome: "The Plaza Restaurant",
  regiao: "MainStreet",
  tipo: ["Classico", "Americano"],
  acesso: "Ao final da Main Street, com vista direta para o castelo",
  precoMedio: 32,
  destaque: "Jantar perfeito para assistir ao show Disney Enchantment. Não deixe de experimentar o hambúrguer artesanal com fritas crocantes.",
  latitude: 28.4189,
  longitude: -81.5826,
},
{
  nome: "Casey’s Corner",
  regiao: "MainStreet",
  tipo: "Economico",
  acesso: "Na esquina final da Main Street, com vista frontal do castelo",
  precoMedio: 17,
  destaque: "Ideal para jantar descontraído antes dos fogos. Não deixe de experimentar o hot dog com chili e queijo cheddar.",
  latitude: 28.4187,
  longitude: -81.5824,
},
{
  nome: "Crystal Palace",
  regiao: "MainStreet",
  tipo: "Tematico",
  acesso: "Em frente ao Plaza Hub, vista para o castelo",
  precoMedio: 45,
  destaque: "Buffet com personagens e janelas panorâmicas. Não deixe de experimentar o frango assado com vegetais.",
  latitude: 28.4185,
  longitude: -81.5822,
},
{
  nome: "Tony’s Town Square Restaurant",
  regiao: "MainStreet",
  tipo: "Conforto",
  acesso: "Logo após a entrada principal do parque",
  precoMedio: 28,
  destaque: "Ambiente italiano acolhedor, perto da saída do parque. Não deixe de experimentar o espaguete com almôndegas.",
  latitude: 28.4184,
  longitude: -81.5819,
},
{
  nome: "Main Street Patio Bites",
  regiao: "MainStreet",
  tipo: "Saudavel",
  acesso: "Ao lado do Ice Cream Parlor",
  precoMedio: 15,
  destaque: "Lanches leves com vista iluminada do castelo. Não deixe de experimentar a salada Caesar com frango grelhado.",
  latitude: 28.4188,
  longitude: -81.5825,
},

// Adventureland
{
  nome: "Skipper Canteen",
  regiao: "Adventureland",
  tipo: "Tematico",
  acesso: "Ao lado da Jungle Cruise, com iluminação suave",
  precoMedio: 33,
  destaque: "Ambiente de expedição ideal para a noite. Não deixe de experimentar o frango ao curry com arroz de coco.",
  latitude: 28.4181,
  longitude: -81.5843,
},
{
  nome: "Tortuga Tavern",
  regiao: "Adventureland",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente à Pirates of the Caribbean",
  precoMedio: 19,
  destaque: "Tema pirata com tochas e clima caribenho. Não deixe de experimentar o porco desfiado com arroz picante.",
  latitude: 28.4180,
  longitude: -81.5841,
},
{
  nome: "Sunshine Tree Terrace",
  regiao: "Adventureland",
  tipo: "Conforto",
  acesso: "Próximo à Magic Carpets of Aladdin",
  precoMedio: 11,
  destaque: "Doçura tropical com luz suave. Não deixe de experimentar o Dole Whip de laranja sob as lanternas.",
  latitude: 28.4178,
  longitude: -81.5839,
},
{
  nome: "Aloha Isle",
  regiao: "Adventureland",
  tipo: "Economico",
  acesso: "Em frente à Tiki Room",
  precoMedio: 9,
  destaque: "Lanche refrescante noturno. Não deixe de experimentar o sorvete de abacaxi com suco natural.",
  latitude: 28.4177,
  longitude: -81.5840,
},
{
  nome: "Tiki Snacks",
  regiao: "Adventureland",
  tipo: "Saudavel",
  acesso: "Ao lado do Aloha Isle",
  precoMedio: 12,
  destaque: "Snacks leves sob luzes tropicais. Não deixe de experimentar o wrap de frango com manga.",
  latitude: 28.4176,
  longitude: -81.5838,
},
// Frontierland
{
  nome: "Pecos Bill Tall Tale Inn and Cafe",
  regiao: "Frontierland",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Splash Mountain, com acesso fácil ao hub central",
  precoMedio: 22,
  destaque: "Ambiente rústico com boa iluminação interna. Não deixe de experimentar o burrito bowl com carne grelhada e guacamole.",
  latitude: 28.4174,
  longitude: -81.5853,
},
{
  nome: "Westward Ho",
  regiao: "Frontierland",
  tipo: "Economico",
  acesso: "Em frente à Country Bear Jamboree",
  precoMedio: 11,
  destaque: "Perfeito para um jantar rápido com clima de faroeste. Não deixe de experimentar o milho cozido com manteiga e especiarias.",
  latitude: 28.4175,
  longitude: -81.5851,
},
{
  nome: "Country Cookin’",
  regiao: "Frontierland",
  tipo: "Conforto",
  acesso: "Nos fundos do Pecos Bill",
  precoMedio: 15,
  destaque: "Área mais tranquila para jantar longe do fluxo principal. Não deixe de experimentar o sanduíche de frango empanado com molho barbecue.",
  latitude: 28.4172,
  longitude: -81.5849,
},
{
  nome: "Golden Trail Grill",
  regiao: "Frontierland",
  tipo: "Tematico",
  acesso: "Próximo ao trilho do trem",
  precoMedio: 18,
  destaque: "Visual noturno com luzes âmbar e decoração do Velho Oeste. Não deixe de experimentar o chili com pão de milho grelhado.",
  latitude: 28.4171,
  longitude: -81.5848,
},
{
  nome: "Prairie Greens",
  regiao: "Frontierland",
  tipo: "Saudavel",
  acesso: "Perto da Tom Sawyer Island",
  precoMedio: 14,
  destaque: "Saladas e wraps sob luz suave, próximo ao rio. Não deixe de experimentar a salada de grão-de-bico com molho de iogurte.",
  latitude: 28.4173,
  longitude: -81.5850,
},
// Liberty Square
{
  nome: "Liberty Tree Tavern",
  regiao: "LibertySquare",
  tipo: "Tematico",
  acesso: "Perto da Haunted Mansion, com janelas iluminadas",
  precoMedio: 34,
  destaque: "Jantar colonial com ambiente de época perfeito à noite. Não deixe de experimentar o assado de peru com purê e molho caseiro.",
  latitude: 28.4190,
  longitude: -81.5834,
},
{
  nome: "The Diamond Horseshoe",
  regiao: "LibertySquare",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Liberty Tree Tavern",
  precoMedio: 30,
  destaque: "Saloon do velho oeste com iluminação dourada. Não deixe de experimentar o prato de brisket defumado com milho grelhado.",
  latitude: 28.4191,
  longitude: -81.5838,
},
{
  nome: "Columbia Harbour House",
  regiao: "LibertySquare",
  tipo: "Conforto",
  acesso: "Ao lado do Hall of Presidents",
  precoMedio: 21,
  destaque: "Lugar calmo e aconchegante para comer frutos do mar. Não deixe de experimentar o prato de salmão com arroz e legumes.",
  latitude: 28.4196,
  longitude: -81.5833,
},
{
  nome: "Liberty Snacks",
  regiao: "LibertySquare",
  tipo: "Economico",
  acesso: "Próximo ao Liberty Square Riverboat",
  precoMedio: 10,
  destaque: "Snacks noturnos práticos com vista lateral para o hub. Não deixe de experimentar o pretzel recheado com cream cheese.",
  latitude: 28.4193,
  longitude: -81.5831,
},
{
  nome: "Revolution Greens",
  regiao: "LibertySquare",
  tipo: "Saudavel",
  acesso: "Atrás da Liberty Tree Tavern",
  precoMedio: 13,
  destaque: "Saladas e wraps frescos em ambiente histórico. Não deixe de experimentar a salada morna de espinafre com frango grelhado.",
  latitude: 28.4192,
  longitude: -81.5835,
},
 // Fantasyland
{
  nome: "Be Our Guest Restaurant",
  regiao: "Fantasyland",
  tipo: "Tematico",
  acesso: "Dentro do castelo da Fera",
  precoMedio: 45,
  destaque: "Ambiente mágico com salão iluminado por candelabros. Não deixe de experimentar o filet mignon com purê trufado.",
  latitude: 28.4203,
  longitude: -81.5805,
},
{
  nome: "Cinderella’s Royal Table",
  regiao: "Fantasyland",
  tipo: ["Classico", "Americano"],
  acesso: "Dentro do Castelo da Cinderela",
  precoMedio: 62,
  destaque: "Jantar real com princesas e vista para o show noturno. Não deixe de experimentar o frango assado com molho de maçã.",
  latitude: 28.4194,
  longitude: -81.5812,
},
{
  nome: "Pinocchio Village Haus",
  regiao: "Fantasyland",
  tipo: "Conforto",
  acesso: "Ao lado da atração It’s a Small World",
  precoMedio: 18,
  destaque: "Ideal para famílias, com janelas temáticas e iluminação suave. Não deixe de experimentar o flatbread de pepperoni.",
  latitude: 28.4195,
  longitude: -81.5820,
},
{
  nome: "Gaston’s Tavern",
  regiao: "Fantasyland",
  tipo: "Economico",
  acesso: "Próximo à Under the Sea – Journey of the Little Mermaid",
  precoMedio: 14,
  destaque: "Rústico e aconchegante para um lanche noturno. Não deixe de experimentar o cinnamon roll gigante do Gaston.",
  latitude: 28.4211,
  longitude: -81.5809,
},
{
  nome: "The Friar’s Nook",
  regiao: "Fantasyland",
  tipo: "Saudavel",
  acesso: "Ao lado do carrossel do Príncipe Encantado",
  precoMedio: 13,
  destaque: "Oferece opções leves e práticas à noite. Não deixe de experimentar o mac and cheese com bacon.",
  latitude: 28.4198,
  longitude: -81.5817,
},
// Tomorrowland (Magic Kingdom)
{
  nome: "Cosmic Ray’s Starlight Café",
  regiao: "Tomorrowland",
  tipo: "Classico",
  acesso: "Em frente à Buzz Lightyear’s Space Ranger Spin",
  precoMedio: 20,
  destaque: "Quick service clássico do parque com o show do Sonny Eclipse no palco.",
  latitude: 28.4200,
  longitude: -81.5792,
},
{
  nome: "The Lunching Pad",
  regiao: "Tomorrowland",
  tipo: "Economico",
  acesso: "Na base da Astro Orbiter",
  precoMedio: 11,
  destaque: "Lanches rápidos como pretzels e hot dogs, bom para comer em movimento.",
  latitude: 28.4201,
  longitude: -81.5793,
},
{
  nome: "Tomorrowland Terrace (sazonal)",
  regiao: "Tomorrowland",
  tipo: "Conforto",
  acesso: "Entre Main Street e Tomorrowland",
  precoMedio: 16,
  destaque: "Área ampla e coberta; quando aberto, oferece pratos rápidos com vista do castelo.",
  latitude: 28.4193,
  longitude: -81.5801,
},
{
  nome: "Energy Bytes",
  regiao: "Tomorrowland",
  tipo: "Tematico",
  acesso: "Ao lado da entrada de TRON Lightcycle / Run",
  precoMedio: 13,
  destaque: "Cardápio compacto com snacks modernos e bebidas geladas em clima futurista.",
  latitude: 28.4209,
  longitude: -81.5776,
},
{
  nome: "Cool Ship",
  regiao: "Tomorrowland",
  tipo: "Saudavel",
  acesso: "Caminho para a Space Mountain, próximo ao Cool Scanner",
  precoMedio: 12,
  destaque: "Quiosque de bebidas e snacks simples; dá para montar escolhas leves.",
  latitude: 28.4200,
  longitude: -81.5783,
},

// World Showcase (EPCOT)
{
  nome: "La Hacienda de San Angel",
  regiao: "World Showcase",
  tipo: "Tematico",
  acesso: "Pavilhão do México – à beira do lago",
  precoMedio: 42,
  destaque: "Cozinha mexicana com mesas voltadas para o lago; ótima vista noturna.",
  latitude: 28.3711,
  longitude: -81.5475,
},
{
  nome: "Les Chefs de France",
  regiao: "World Showcase",
  tipo: "Classico",
  acesso: "Pavilhão da França – com janelas panorâmicas",
  precoMedio: 39,
  destaque: "Brasserie francesa tradicional com menu de clássicos e serviço de mesa.",
  latitude: 28.3705,
  longitude: -81.5502,
},
{
  nome: "Spice Road Table",
  regiao: "World Showcase",
  tipo: "Conforto",
  acesso: "Pavilhão do Marrocos – à margem do lago",
  precoMedio: 28,
  destaque: "Porções para compartilhar e clima relaxado à beira d’água.",
  latitude: 28.3708,
  longitude: -81.5493,
},
{
  nome: "La Cantina de San Angel",
  regiao: "World Showcase",
  tipo: "Economico",
  acesso: "Pavilhão do México – na beira do lago, ao lado da pirâmide",
  precoMedio: 15,
  destaque: "Quick service com tacos e nachos; balcões externos e mesas abertas.",
  latitude: 28.3711,
  longitude: -81.5475,
},
{
  nome: "Tangierine Café",
  regiao: "World Showcase",
  tipo: "Saudavel",
  acesso: "Pavilhão do Marrocos – pátio central",
  precoMedio: 19,
  destaque: "Pratos mediterrâneos leves como kefte, saladas e couscous.",
  latitude: 28.3708,
  longitude: -81.5493,
},

// World Discovery (EPCOT)
{
  nome: "Space 220 Restaurant",
  regiao: "World Discovery",
  tipo: "Tematico",
  acesso: "Ao lado da Mission: SPACE",
  precoMedio: 55,
  destaque: "Experiência imersiva de estação espacial com janelas para a ‘órbita’.",
  latitude: 28.3735,
  longitude: -81.5480,
},
{
  nome: "Space 220 Lounge",
  regiao: "World Discovery",
  tipo: "Conforto",
  acesso: "Entrada conjunta ao Space 220, ao lado da Mission: SPACE",
  precoMedio: 28,
  destaque: "Drinks assinados e pequenos pratos num ambiente temático espacial.",
  latitude: 28.3735,
  longitude: -81.5480,
},
{
  nome: "Refreshment Station (perto da Test Track)",
  regiao: "World Discovery",
  tipo: "Economico",
  acesso: "Calçada lateral da Test Track",
  precoMedio: 10,
  destaque: "Bebidas geladas e snacks rápidos; parada prática entre atrações.",
  latitude: 28.3750,
  longitude: -81.5482,
},
{
  nome: "Joffrey’s Coffee & Tea Company – Test Track",
  regiao: "World Discovery",
  tipo: "Saudavel",
  acesso: "Em frente à área de Test Track",
  precoMedio: 8,
  destaque: "Cafés, chás gelados e alguns itens leves para levar.",
  latitude: 28.3752,
  longitude: -81.5484,
},
{
  nome: "Guardians Snack Cart",
  regiao: "World Discovery",
  tipo: "Classico",
  acesso: "Próximo à Guardians of the Galaxy: Cosmic Rewind",
  precoMedio: 12,
  destaque: "Carrinho com pipoca, churros e bebidas próximo à nave Xandariana.",
  latitude: 28.3748,
  longitude: -81.5477,
},

// World Celebration (EPCOT)
{
  nome: "Connections Eatery",
  regiao: "World Celebration",
  tipo: "Classico",
  acesso: "Praça central, ao lado do Creations Shop",
  precoMedio: 26,
  destaque: "Quick service moderno com menu internacional e salão amplo.",
  latitude: 28.3742,
  longitude: -81.5485,
},
{
  nome: "Connections Café (Starbucks)",
  regiao: "World Celebration",
  tipo: "Economico",
  acesso: "Anexo ao Connections Eatery",
  precoMedio: 12,
  destaque: "Cafés especiais e lanches rápidos; ponto prático para recarregar.",
  latitude: 28.3741,
  longitude: -81.5487,
},
{
  nome: "Club Cool",
  regiao: "World Celebration",
  tipo: "Tematico",
  acesso: "Corredor entre Spaceship Earth e Creations Shop",
  precoMedio: 0,
  destaque: "Degustação de refrigerantes do mundo; experiência temática divertida.",
  latitude: 28.3740,
  longitude: -81.5489,
},
{
  nome: "Festival Market (sazonal)",
  regiao: "World Celebration",
  tipo: "Conforto",
  acesso: "Área de CommuniCore Hall/Plaza (durante festivais)",
  precoMedio: 15,
  destaque: "Estandes sazonais com pratos pequenos e sobremesas temáticas.",
  latitude: 28.3739,
  longitude: -81.5491,
},
{
  nome: "Popcorn & Ice Cream Cart – Spaceship Earth",
  regiao: "World Celebration",
  tipo: "Saudavel",
  acesso: "Base da Spaceship Earth",
  precoMedio: 9,
  destaque: "Carrinho com sorvetes, frutas embaladas e bebidas.",
  latitude: 28.3743,
  longitude: -81.5490,
},

// World Nature (EPCOT)
{
  nome: "Coral Reef Restaurant",
  regiao: "World Nature",
  tipo: "Tematico",
  acesso: "Ao lado da The Seas with Nemo & Friends",
  precoMedio: 42,
  destaque: "Jantar com vista para o aquário gigante; foco em peixes e frutos do mar.",
  latitude: 28.3732,
  longitude: -81.5501,
},
{
  nome: "Garden Grill Restaurant",
  regiao: "World Nature",
  tipo: "Classico",
  acesso: "Dentro do pavilhão The Land (andar superior)",
  precoMedio: 40,
  destaque: "Restaurante giratório com personagens e pratos ‘family-style’.",
  latitude: 28.3726,
  longitude: -81.5472,
},
{
  nome: "Sunshine Seasons",
  regiao: "World Nature",
  tipo: "Saudavel",
  acesso: "Pavilhão The Land (andar térreo)",
  precoMedio: 16,
  destaque: "Praça de alimentação com opções leves, bowls e pratos frescos.",
  latitude: 28.3724,
  longitude: -81.5472,
},
{
  nome: "The Seas Snack Cart",
  regiao: "World Nature",
  tipo: "Economico",
  acesso: "Saída de The Seas with Nemo & Friends",
  precoMedio: 10,
  destaque: "Snacks e bebidas para levar; parada rápida ao sair do pavilhão.",
  latitude: 28.3729,
  longitude: -81.5469,
},
{
  nome: "The Land Coffee & Treats (quiosque)",
  regiao: "World Nature",
  tipo: "Conforto",
  acesso: "Entrada do pavilhão The Land",
  precoMedio: 12,
  destaque: "Cafés, cookies e sobremesas simples antes/depois das atrações do pavilhão.",
  latitude: 28.3723,
  longitude: -81.5473,
},

// Hollywood Boulevard (Disney’s Hollywood Studios)
{
  nome: "The Hollywood Brown Derby",
  regiao: "Hollywood Boulevard",
  tipo: "Classico",
  acesso: "No final do boulevard principal, à esquerda",
  precoMedio: 48,
  destaque: "Clássico de Hollywood com o famoso Cobb Salad e ambiente elegante.",
  latitude: 28.3571,
  longitude: -81.5584,
},
{
  nome: "Brown Derby Lounge",
  regiao: "Hollywood Boulevard",
  tipo: "Tematico",
  acesso: "Área externa do Brown Derby, com vista para o boulevard",
  precoMedio: 29,
  destaque: "Coquetéis e porções em lounge estilizado ao ar livre.",
  latitude: 28.3570,
  longitude: -81.5582,
},
{
  nome: "The Trolley Car Café (Starbucks)",
  regiao: "Hollywood Boulevard",
  tipo: "Economico",
  acesso: "Ao lado da entrada do parque",
  precoMedio: 12,
  destaque: "Cafés e lanches rápidos para começar ou encerrar o dia.",
  latitude: 28.3574,
  longitude: -81.5585,
},
{
  nome: "Hollywood Boulevard Popcorn Cart",
  regiao: "Hollywood Boulevard",
  tipo: "Conforto",
  acesso: "Calçada principal do boulevard",
  precoMedio: 9,
  destaque: "Pipoca, churros e bebidas; parada clássica entre fotos e lojas.",
  latitude: 28.3573,
  longitude: -81.5586,
},
{
  nome: "Ice Cream Novelties Cart – Hollywood Blvd",
  regiao: "Hollywood Boulevard",
  tipo: "Saudavel",
  acesso: "Próximo ao Crossroads of the World",
  precoMedio: 10,
  destaque: "Picolés, água e frutas embaladas; opções simples e leves.",
  latitude: 28.3572,
  longitude: -81.5583,
},

// Echo Lake (Disney’s Hollywood Studios)
{
  nome: "Hollywood & Vine",
  regiao: "Echo Lake",
  tipo: "Classico",
  acesso: "Praça principal de Echo Lake, perto do 50’s Prime Time Café",
  precoMedio: 42,
  destaque: "Buffet de culinária americana; alguns períodos com personagens.",
  latitude: 28.3574,
  longitude: -81.5581,
},
{
  nome: "50’s Prime Time Café",
  regiao: "Echo Lake",
  tipo: "Tematico",
  acesso: "Ao lado do lago, próximo ao Indiana Jones",
  precoMedio: 35,
  destaque: "Restaurante retrô dos anos 50 com equipe bem-humorada na mesa.",
  latitude: 28.3567,
  longitude: -81.5595,
},
{
  nome: "Backlot Express",
  regiao: "Echo Lake",
  tipo: "Conforto",
  acesso: "Ao lado da Star Tours",
  precoMedio: 20,
  destaque: "Sanduíches, hambúrgueres e mesas internas/externas em ambiente de bastidores.",
  latitude: 28.3570,
  longitude: -81.5590,
},
{
  nome: "Dockside Diner",
  regiao: "Echo Lake",
  tipo: "Economico",
  acesso: "À beira do lago, no barco estilizado",
  precoMedio: 16,
  destaque: "Snacks e hot dogs especiais com vista para o lago.",
  latitude: 28.3569,
  longitude: -81.5593,
},
{
  nome: "Epic Eats",
  regiao: "Echo Lake",
  tipo: "Saudavel",
  acesso: "Próximo ao teatro Indiana Jones Epic Stunt Spectacular",
  precoMedio: 11,
  destaque: "Quiosque com sobremesas e algumas opções simples para lanche leve.",
  latitude: 28.3577,
  longitude: -81.5591,
},

// Grand Avenue (Disney’s Hollywood Studios)
{
  nome: "Mama Melrose’s Ristorante Italiano",
  regiao: "Grand Avenue",
  tipo: "Classico",
  acesso: "No fim da Grand Avenue, próximo ao Muppet*Vision 3D",
  precoMedio: 36,
  destaque: "Trattoria acolhedora com massas e pratos italianos tradicionais.",
  latitude: 28.3575,
  longitude: -81.5602,
},
{
  nome: "BaseLine Tap House",
  regiao: "Grand Avenue",
  tipo: "Tematico",
  acesso: "Metade da Grand Avenue, esquina para o pátio",
  precoMedio: 20,
  destaque: "Chopes californianos e petiscos como pretzel gigante e tábua de frios.",
  latitude: 28.3576,
  longitude: -81.5600,
},
{
  nome: "PizzeRizzo",
  regiao: "Grand Avenue",
  tipo: "Conforto",
  acesso: "Ao lado do Muppet*Vision 3D",
  precoMedio: 16,
  destaque: "Pizzas e saladas em serviço rápido, com salão amplo e climatizado.",
  latitude: 28.3578,
  longitude: -81.5604,
},
{
  nome: "Grand Avenue Popcorn Cart",
  regiao: "Grand Avenue",
  tipo: "Economico",
  acesso: "Calçada principal da Grand Avenue",
  precoMedio: 9,
  destaque: "Pipoca e bebidas geladas para um lanche prático.",
  latitude: 28.3577,
  longitude: -81.5601,
},
{
  nome: "Muppets Courtyard Gelato Cart",
  regiao: "Grand Avenue",
  tipo: "Saudavel",
  acesso: "Pátio dos Muppets, ao lado da entrada do Muppet*Vision 3D",
  precoMedio: 12,
  destaque: "Sorbet, água e itens leves; pausa rápida entre atrações.",
  latitude: 28.3579,
  longitude: -81.5605,
},
// Star Wars: Galaxy’s Edge (Disney’s Hollywood Studios)
{
  nome: "Docking Bay 7 Food and Cargo",
  regiao: "Galaxy’s Edge",
  tipo: "Classico",
  acesso: "Setor central de Batuu, atrás da Millennium Falcon",
  precoMedio: 28,
  destaque: "Pratos autorais com apresentação ‘galáctica’ em salão totalmente imersivo.",
  latitude: 28.3584,
  longitude: -81.5615,
},
{
  nome: "Oga’s Cantina",
  regiao: "Galaxy’s Edge",
  tipo: "Tematico",
  acesso: "Corredor do mercado Black Spire Outpost",
  precoMedio: 35,
  destaque: "Bar de Batuu com coquetéis criativos e trilha do DJ R-3X.",
  latitude: 28.3585,
  longitude: -81.5616,
},
{
  nome: "Ronto Roasters",
  regiao: "Galaxy’s Edge",
  tipo: "Conforto",
  acesso: "Praça do mercado, em frente ao Droid Depot",
  precoMedio: 16,
  destaque: "Wraps grelhados e carnes defumadas para comer em movimento.",
  latitude: 28.3586,
  longitude: -81.5614,
},
{
  nome: "Kat Saka’s Kettle",
  regiao: "Galaxy’s Edge",
  tipo: "Economico",
  acesso: "Mercado Black Spire Outpost",
  precoMedio: 9,
  destaque: "Pipocas doces tipo Outpost Mix e bebidas geladas.",
  latitude: 28.3587,
  longitude: -81.5613,
},
{
  nome: "Milk Stand",
  regiao: "Galaxy’s Edge",
  tipo: "Saudavel",
  acesso: "Caminho entre o mercado e a Millennium Falcon",
  precoMedio: 8,
  destaque: "Leite azul e verde em versões geladas; opção leve e refrescante.",
  latitude: 28.3588,
  longitude: -81.5612,
},

// Toy Story Land (Disney’s Hollywood Studios)
{
  nome: "Roundup Rodeo BBQ",
  regiao: "Toy Story Land",
  tipo: "Classico",
  acesso: "Entrada à direita após passar por Woody, perto da Slinky Dog Dash",
  precoMedio: 45,
  destaque: "Churrasco estilo família em restaurante de brinquedos com mesas temáticas.",
  latitude: 28.3590,
  longitude: -81.5620,
},
{
  nome: "Woody’s Lunch Box",
  regiao: "Toy Story Land",
  tipo: "Tematico",
  acesso: "Centro da área, ao lado de Slinky Dog Dash",
  precoMedio: 18,
  destaque: "Cardápio divertido com grilled cheese, totchos e tortinhas.",
  latitude: 28.3591,
  longitude: -81.5621,
},
{
  nome: "Ice Cream Cart – Toy Story Land",
  regiao: "Toy Story Land",
  tipo: "Conforto",
  acesso: "Caminho entre Alien Swirling Saucers e a saída para Animation Courtyard",
  precoMedio: 10,
  destaque: "Picolés e sundaes individuais para refrescar no calor.",
  latitude: 28.3594,
  longitude: -81.5624,
},
{
  nome: "Market by Toy Story Land (Snack Cart)",
  regiao: "Toy Story Land",
  tipo: "Economico",
  acesso: "Corredor central, próximo ao PhotoPass com Woody e Jessie",
  precoMedio: 10,
  destaque: "Carrinho de snacks com pretzels, pipoca e bebidas.",
  latitude: 28.3593,
  longitude: -81.5623,
},
{
  nome: "Joffrey’s Coffee & Tea Company – Toy Story Land",
  regiao: "Toy Story Land",
  tipo: "Saudavel",
  acesso: "Próximo ao acesso para a área de Alien Swirling Saucers",
  precoMedio: 12,
  destaque: "Cafés e bebidas; opções leves como donuts simples e água gelada.",
  latitude: 28.3592,
  longitude: -81.5622,
},

// Animation Courtyard (Disney’s Hollywood Studios)
{
  nome: "Joffrey’s Coffee & Tea Company – Animation Courtyard",
  regiao: "Animation Courtyard",
  tipo: "Classico",
  acesso: "Perto da entrada do Disney Junior Dance Party",
  precoMedio: 12,
  destaque: "Cafés, chás e doces clássicos para começar a noite.",
  latitude: 28.3568,
  longitude: -81.5598,
},
{
  nome: "Market – Animation Courtyard (Snack Cart)",
  regiao: "Animation Courtyard",
  tipo: "Tematico",
  acesso: "Calçada principal do Animation Courtyard",
  precoMedio: 11,
  destaque: "Snacks sazonais e bebidas em carrinho com identidade do estúdio.",
  latitude: 28.3566,
  longitude: -81.5596,
},
{
  nome: "Cartoon Treats (Ice Cream Cart)",
  regiao: "Animation Courtyard",
  tipo: "Conforto",
  acesso: "Próximo ao Walt Disney Presents",
  precoMedio: 10,
  destaque: "Sorvetes e sundaes individuais para uma pausa rápida.",
  latitude: 28.3565,
  longitude: -81.5595,
},
{
  nome: "Courtyard Popcorn Cart",
  regiao: "Animation Courtyard",
  tipo: "Economico",
  acesso: "Ao lado do Walt Disney Presents",
  precoMedio: 9,
  destaque: "Pipoca e refil de bebidas; lanche prático entre atrações.",
  latitude: 28.3567,
  longitude: -81.5597,
},
{
  nome: "Fresh Sketch Greens (Grab & Go)",
  regiao: "Animation Courtyard",
  tipo: "Saudavel",
  acesso: "Entre a loja Disney Junior e o Playhouse Disney",
  precoMedio: 14,
  destaque: "Frutas, wraps leves e snacks embalados.",
  latitude: 28.3564,
  longitude: -81.5594,
},

// Sunset Boulevard (Disney’s Hollywood Studios)
{
  nome: "Rosie’s All-American Café",
  regiao: "Sunset Boulevard",
  tipo: "Classico",
  acesso: "Praça de alimentação antes da Rock ‘n’ Roller Coaster",
  precoMedio: 24,
  destaque: "Hambúrgueres, saladas e combos clássicos em pátio aberto.",
  latitude: 28.3556,
  longitude: -81.5599,
},
{
  nome: "Fairfax Fare",
  regiao: "Sunset Boulevard",
  tipo: "Tematico",
  acesso: "Conjunto Sunset Ranch Market, lado esquerdo",
  precoMedio: 18,
  destaque: "Bowls inspirados em sabores latinos em ambiente de mercado californiano.",
  latitude: 28.3557,
  longitude: -81.5598,
},
{
  nome: "Hollywood Scoops",
  regiao: "Sunset Boulevard",
  tipo: "Conforto",
  acesso: "Em frente à The Twilight Zone Tower of Terror",
  precoMedio: 13,
  destaque: "Sorvetes e sobremesas geladas em porções generosas.",
  latitude: 28.3555,
  longitude: -81.5600,
},
{
  nome: "Catalina Eddie’s",
  regiao: "Sunset Boulevard",
  tipo: "Economico",
  acesso: "Praça Sunset Ranch Market, lado direito",
  precoMedio: 12,
  destaque: "Pizza em fatias, saladas e bebidas de quick service.",
  latitude: 28.3559,
  longitude: -81.5602,
},
{
  nome: "Anaheim Produce",
  regiao: "Sunset Boulevard",
  tipo: "Saudavel",
  acesso: "Calçada principal de Sunset Boulevard",
  precoMedio: 11,
  destaque: "Frutas, snacks leves e bebidas refrescantes.",
  latitude: 28.3558,
  longitude: -81.5601,
},

// Oasis (Disney’s Animal Kingdom)
{
  nome: "Rainforest Café (Entrada do Parque)",
  regiao: "Oasis",
  tipo: "Tematico",
  acesso: "Na entrada principal do parque, antes dos portões",
  precoMedio: 36,
  destaque: "Restaurante de floresta tropical com cardápio variado e porções fartas.",
  latitude: 28.3598,
  longitude: -81.5912,
},
{
  nome: "The Feeding Ground (Snack Cart)",
  regiao: "Oasis",
  tipo: "Classico",
  acesso: "Caminho principal da Oasis, após os portões",
  precoMedio: 10,
  destaque: "Snacks tradicionais e bebidas para iniciar a visita.",
  latitude: 28.3597,
  longitude: -81.5911,
},
{
  nome: "Oasis Ice Cream Cart",
  regiao: "Oasis",
  tipo: "Conforto",
  acesso: "À esquerda do mapa do parque, após a entrada",
  precoMedio: 12,
  destaque: "Picolés, sorvetes e refrigerantes para se refrescar.",
  latitude: 28.3599,
  longitude: -81.5910,
},
{
  nome: "Garden Gate Gifts Grab & Go",
  regiao: "Oasis",
  tipo: "Economico",
  acesso: "Ao lado da loja Garden Gate Gifts",
  precoMedio: 9,
  destaque: "Itens práticos para levar, como chips, cookies e bebidas.",
  latitude: 28.3595,
  longitude: -81.5914,
},
{
  nome: "Oasis Fruit Market (Cart)",
  regiao: "Oasis",
  tipo: "Saudavel",
  acesso: "Corredor à direita, próximo à ponte para Discovery Island",
  precoMedio: 13,
  destaque: "Frutas frescas, wraps leves e água gelada.",
  latitude: 28.3596,
  longitude: -81.5913,
},

// Discovery Island (Disney’s Animal Kingdom)
{
  nome: "Flame Tree Barbecue",
  regiao: "Discovery Island",
  tipo: "Classico",
  acesso: "Beira do lago, próximo à ponte para Asia",
  precoMedio: 26,
  destaque: "Carnes defumadas, porções bem servidas e pátios com vista.",
  latitude: 28.3608,
  longitude: -81.5902,
},
{
  nome: "Tiffins Restaurant",
  regiao: "Discovery Island",
  tipo: "Tematico",
  acesso: "Corredor entre Discovery Island e a ponte para Pandora",
  precoMedio: 49,
  destaque: "Jantar refinado com pratos globais e sala elegante com arte de expedições.",
  latitude: 28.3565,
  longitude: -81.5919,
},
{
  nome: "Creature Comforts (Starbucks)",
  regiao: "Discovery Island",
  tipo: "Conforto",
  acesso: "Entre as lojas principais, caminho para Africa",
  precoMedio: 18,
  destaque: "Cafés, bolos e bebidas especiais em ambiente climatizado.",
  latitude: 28.3610,
  longitude: -81.5900,
},
{
  nome: "Pizzafari",
  regiao: "Discovery Island",
  tipo: "Economico",
  acesso: "Próximo ao caminho para Pandora – The World of Avatar",
  precoMedio: 14,
  destaque: "Pizzas individuais, saladas e áreas internas temáticas.",
  latitude: 28.3612,
  longitude: -81.5903,
},
{
  nome: "Isle of Java",
  regiao: "Discovery Island",
  tipo: "Saudavel",
  acesso: "Margem do lago, caminho para a ponte de Asia",
  precoMedio: 11,
  destaque: "Cafés e opções leves para levar; prático no início da noite.",
  latitude: 28.3613,
  longitude: -81.5904,
},

// Pandora – The World of Avatar (Disney’s Animal Kingdom)
{
  nome: "Satu’li Canteen",
  regiao: "Pandora",
  tipo: "Tematico",
  acesso: "Próximo à atração Avatar Flight of Passage",
  precoMedio: 27,
  destaque: "Bowls personalizáveis com proteínas e bases como arroz e batata-doce.",
  latitude: 28.3595,
  longitude: -81.5886,
},
{
  nome: "Pongu Pongu",
  regiao: "Pandora",
  tipo: "Economico",
  acesso: "Perto da entrada de Na’vi River Journey",
  precoMedio: 11,
  destaque: "Drinks especiais e lanches rápidos como o clássico Pongu Lumpia.",
  latitude: 28.3594,
  longitude: -81.5888,
},
{
  nome: "Windtraders Snacks",
  regiao: "Pandora",
  tipo: "Conforto",
  acesso: "Próximo à loja Windtraders, saída de Flight of Passage",
  precoMedio: 15,
  destaque: "Doces temáticos e lanches embalados; parada prática na saída da atração.",
  latitude: 28.3596,
  longitude: -81.5887,
},
{
  nome: "Pongu Cooler Cart",
  regiao: "Pandora",
  tipo: "Classico",
  acesso: "Entre Pongu Pongu e a ponte de entrada de Pandora",
  precoMedio: 10,
  destaque: "Bebidas geladas e refrigerantes; ótimo para refrescar antes das filas.",
  latitude: 28.3597,
  longitude: -81.5885,
},
{
  nome: "Na’vi Greens",
  regiao: "Pandora",
  tipo: "Saudavel",
  acesso: "Atrás do Satu’li Canteen, próximo ao jardim bio-luminescente",
  precoMedio: 14,
  destaque: "Saladas e bowls leves com proteínas magras e frutas tropicais.",
  latitude: 28.3598,
  longitude: -81.5884,
},
// Africa (Disney’s Animal Kingdom)
{
  nome: "Tusker House Restaurant",
  regiao: "Africa",
  tipo: "Tematico",
  acesso: "Vila de Harambe, perto da ponte principal e do Safari",
  precoMedio: 46,
  destaque: "Buffet africano com personagens em cenário de mercado colonial.",
  latitude: 28.3590,
  longitude: -81.5930,
},
{
  nome: "Harambe Market",
  regiao: "Africa",
  tipo: "Classico",
  acesso: "Praça central de Harambe, perto do Kilimanjaro Safaris",
  precoMedio: 24,
  destaque: "Estações ao ar livre com pratos inspirados em street food africana.",
  latitude: 28.3588,
  longitude: -81.5932,
},
{
  nome: "Tamu Tamu Refreshments",
  regiao: "Africa",
  tipo: "Conforto",
  acesso: "Beco de Harambe, sinalização para sobremesas geladas",
  precoMedio: 14,
  destaque: "Sobremesas e lanches gelados em pátio sombreado.",
  latitude: 28.3591,
  longitude: -81.5929,
},
{
  nome: "Mahindi",
  regiao: "Africa",
  tipo: "Economico",
  acesso: "Calçadão de Harambe, próximo ao mercado",
  precoMedio: 10,
  destaque: "Carrinho de pipoca e bebidas para uma parada rápida.",
  latitude: 28.3592,
  longitude: -81.5933,
},
{
  nome: "Harambe Fruit Market",
  regiao: "Africa",
  tipo: "Saudavel",
  acesso: "Em frente à saída do Kilimanjaro Safaris",
  precoMedio: 10,
  destaque: "Frutas frescas, snacks leves e água gelada.",
  latitude: 28.3589,
  longitude: -81.5931,
},

// Asia (Disney’s Animal Kingdom)
{
  nome: "Yak & Yeti Restaurant",
  regiao: "Asia",
  tipo: "Classico",
  acesso: "Entre Kali River Rapids e Maharajah Jungle Trek",
  precoMedio: 32,
  destaque: "Cozinha pan-asiática com serviço de mesa em ambiente temático.",
  latitude: 28.3580,
  longitude: -81.5915,
},
{
  nome: "Royal Anandapur Tea Company (Joffrey’s)",
  regiao: "Asia",
  tipo: "Tematico",
  acesso: "Praça central de Anandapur",
  precoMedio: 9,
  destaque: "Cafés e chás especiais com decoração de vila asiática.",
  latitude: 28.3582,
  longitude: -81.5917,
},
{
  nome: "Anandapur Ice Cream Truck",
  regiao: "Asia",
  tipo: "Conforto",
  acesso: "Caminho para a Expedition Everest",
  precoMedio: 9,
  destaque: "Sorvetes e sundaes servidos em caminhão temático.",
  latitude: 28.3579,
  longitude: -81.5916,
},
{
  nome: "Mr. Kamal’s",
  regiao: "Asia",
  tipo: "Economico",
  acesso: "Calçada entre Asia e Africa, próximo ao teatro de aves",
  precoMedio: 11,
  destaque: "Snacks salgados e batatas temperadas para comer andando.",
  latitude: 28.3578,
  longitude: -81.5913,
},
{
  nome: "Yak & Yeti Local Food Cafes",
  regiao: "Asia",
  tipo: "Saudavel",
  acesso: "Ao lado do Yak & Yeti Restaurant",
  precoMedio: 15,
  destaque: "Quick service com bowls e saladas com toques orientais.",
  latitude: 28.3581,
  longitude: -81.5914,
},

// DinoLand U.S.A. (Disney’s Animal Kingdom)
{
  nome: "Restaurantosaurus",
  regiao: "DinoLand U.S.A.",
  tipo: "Classico",
  acesso: "Ao lado da atração DINOSAUR",
  precoMedio: 22,
  destaque: "Hambúrgueres e sanduíches em salão temático de paleontologia.",
  latitude: 28.3570,
  longitude: -81.5890,
},
{
  nome: "Restaurantosaurus Lounge",
  regiao: "DinoLand U.S.A.",
  tipo: "Tematico",
  acesso: "Anexo ao Restaurantosaurus (funcionamento sazonal)",
  precoMedio: 18,
  destaque: "Drinks e petiscos em lounge com décor do Dino Institute.",
  latitude: 28.3569,
  longitude: -81.5891,
},
{
  nome: "Ice Cream Cart – DinoLand",
  regiao: "DinoLand U.S.A.",
  tipo: "Conforto",
  acesso: "Calçada próxima ao Fossil Fun Games",
  precoMedio: 10,
  destaque: "Picolés e sundaes individuais para refrescar entre atrações.",
  latitude: 28.3569,
  longitude: -81.5889,
},
{
  nome: "Popcorn Cart – DinoLand",
  regiao: "DinoLand U.S.A.",
  tipo: "Economico",
  acesso: "Corredor central da área, perto da TriceraTop Spin",
  precoMedio: 9,
  destaque: "Pipoca e bebidas; parada rápida e barata.",
  latitude: 28.3568,
  longitude: -81.5888,
},
{
  nome: "DinoLand Fruit & Snacks",
  regiao: "DinoLand U.S.A.",
  tipo: "Saudavel",
  acesso: "Próximo à área infantil The Boneyard",
  precoMedio: 12,
  destaque: "Frutas, água e snacks simples para uma escolha leve.",
  latitude: 28.3567,
  longitude: -81.5887,
},


  ];