export const  jantaresDisney = [
// Main Street, U.S.A.
{
  nome: "The Plaza Restaurant",
  regiao: "MainStreet",
  tipo: ["Classico", "Americano"],
  acesso: "Ao final da Main Street, com vista direta para o castelo",
  precoMedio: 32,
  destaque: "Jantar perfeito para assistir ao show Disney Enchantment. NÃ£o deixe de experimentar o hambÃºrguer artesanal com fritas crocantes.",
  latitude: 28.4189,
  longitude: -81.5826,
},
{
  nome: "Caseyâ€™s Corner",
  regiao: "MainStreet",
  tipo: "Economico",
  acesso: "Na esquina final da Main Street, com vista frontal do castelo",
  precoMedio: 17,
  destaque: "Ideal para jantar descontraÃ­do antes dos fogos. NÃ£o deixe de experimentar o hot dog com chili e queijo cheddar.",
  latitude: 28.4187,
  longitude: -81.5824,
},
{
  nome: "Crystal Palace",
  regiao: "MainStreet",
  tipo: "Tematico",
  acesso: "Em frente ao Plaza Hub, vista para o castelo",
  precoMedio: 45,
  destaque: "Buffet com personagens e janelas panorÃ¢micas. NÃ£o deixe de experimentar o frango assado com vegetais.",
  latitude: 28.4185,
  longitude: -81.5822,
},
{
  nome: "Tonyâ€™s Town Square Restaurant",
  regiao: "MainStreet",
  tipo: "Conforto",
  acesso: "Logo apÃ³s a entrada principal do parque",
  precoMedio: 28,
  destaque: "Ambiente italiano acolhedor, perto da saÃ­da do parque. NÃ£o deixe de experimentar o espaguete com almÃ´ndegas.",
  latitude: 28.4184,
  longitude: -81.5819,
},
{
  nome: "Main Street Patio Bites",
  regiao: "MainStreet",
  tipo: "Saudavel",
  acesso: "Ao lado do Ice Cream Parlor",
  precoMedio: 15,
  destaque: "Lanches leves com vista iluminada do castelo. NÃ£o deixe de experimentar a salada Caesar com frango grelhado.",
  latitude: 28.4188,
  longitude: -81.5825,
},

// Adventureland
{
  nome: "Skipper Canteen",
  regiao: "Adventureland",
  tipo: "Tematico",
  acesso: "Ao lado da Jungle Cruise, com iluminaÃ§Ã£o suave",
  precoMedio: 33,
  destaque: "Ambiente de expediÃ§Ã£o ideal para a noite. NÃ£o deixe de experimentar o frango ao curry com arroz de coco.",
  latitude: 28.4181,
  longitude: -81.5843,
},
{
  nome: "Tortuga Tavern",
  regiao: "Adventureland",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente Ã  Pirates of the Caribbean",
  precoMedio: 19,
  destaque: "Tema pirata com tochas e clima caribenho. NÃ£o deixe de experimentar o porco desfiado com arroz picante.",
  latitude: 28.4180,
  longitude: -81.5841,
},
{
  nome: "Sunshine Tree Terrace",
  regiao: "Adventureland",
  tipo: "Conforto",
  acesso: "PrÃ³ximo Ã  Magic Carpets of Aladdin",
  precoMedio: 11,
  destaque: "DoÃ§ura tropical com luz suave. NÃ£o deixe de experimentar o Dole Whip de laranja sob as lanternas.",
  latitude: 28.4178,
  longitude: -81.5839,
},
{
  nome: "Aloha Isle",
  regiao: "Adventureland",
  tipo: "Economico",
  acesso: "Em frente Ã  Tiki Room",
  precoMedio: 9,
  destaque: "Lanche refrescante noturno. NÃ£o deixe de experimentar o sorvete de abacaxi com suco natural.",
  latitude: 28.4177,
  longitude: -81.5840,
},
{
  nome: "Tiki Snacks",
  regiao: "Adventureland",
  tipo: "Saudavel",
  acesso: "Ao lado do Aloha Isle",
  precoMedio: 12,
  destaque: "Snacks leves sob luzes tropicais. NÃ£o deixe de experimentar o wrap de frango com manga.",
  latitude: 28.4176,
  longitude: -81.5838,
},
// Frontierland
{
  nome: "Pecos Bill Tall Tale Inn and Cafe",
  regiao: "Frontierland",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Splash Mountain, com acesso fÃ¡cil ao hub central",
  precoMedio: 22,
  destaque: "Ambiente rÃºstico com boa iluminaÃ§Ã£o interna. NÃ£o deixe de experimentar o burrito bowl com carne grelhada e guacamole.",
  latitude: 28.4174,
  longitude: -81.5853,
},
{
  nome: "Westward Ho",
  regiao: "Frontierland",
  tipo: "Economico",
  acesso: "Em frente Ã  Country Bear Jamboree",
  precoMedio: 11,
  destaque: "Perfeito para um jantar rÃ¡pido com clima de faroeste. NÃ£o deixe de experimentar o milho cozido com manteiga e especiarias.",
  latitude: 28.4175,
  longitude: -81.5851,
},
{
  nome: "Country Cookinâ€™",
  regiao: "Frontierland",
  tipo: "Conforto",
  acesso: "Nos fundos do Pecos Bill",
  precoMedio: 15,
  destaque: "Ãrea mais tranquila para jantar longe do fluxo principal. NÃ£o deixe de experimentar o sanduÃ­che de frango empanado com molho barbecue.",
  latitude: 28.4172,
  longitude: -81.5849,
},
{
  nome: "Golden Trail Grill",
  regiao: "Frontierland",
  tipo: "Tematico",
  acesso: "PrÃ³ximo ao trilho do trem",
  precoMedio: 18,
  destaque: "Visual noturno com luzes Ã¢mbar e decoraÃ§Ã£o do Velho Oeste. NÃ£o deixe de experimentar o chili com pÃ£o de milho grelhado.",
  latitude: 28.4171,
  longitude: -81.5848,
},
{
  nome: "Prairie Greens",
  regiao: "Frontierland",
  tipo: "Saudavel",
  acesso: "Perto da Tom Sawyer Island",
  precoMedio: 14,
  destaque: "Saladas e wraps sob luz suave, prÃ³ximo ao rio. NÃ£o deixe de experimentar a salada de grÃ£o-de-bico com molho de iogurte.",
  latitude: 28.4173,
  longitude: -81.5850,
},
// Liberty Square
{
  nome: "Liberty Tree Tavern",
  regiao: "LibertySquare",
  tipo: "Tematico",
  acesso: "Perto da Haunted Mansion, com janelas iluminadas",
  precoMedio: 34,
  destaque: "Jantar colonial com ambiente de Ã©poca perfeito Ã  noite. NÃ£o deixe de experimentar o assado de peru com purÃª e molho caseiro.",
  latitude: 28.4190,
  longitude: -81.5834,
},
{
  nome: "The Diamond Horseshoe",
  regiao: "LibertySquare",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Liberty Tree Tavern",
  precoMedio: 30,
  destaque: "Saloon do velho oeste com iluminaÃ§Ã£o dourada. NÃ£o deixe de experimentar o prato de brisket defumado com milho grelhado.",
  latitude: 28.4191,
  longitude: -81.5838,
},
{
  nome: "Columbia Harbour House",
  regiao: "LibertySquare",
  tipo: "Conforto",
  acesso: "Ao lado do Hall of Presidents",
  precoMedio: 21,
  destaque: "Lugar calmo e aconchegante para comer frutos do mar. NÃ£o deixe de experimentar o prato de salmÃ£o com arroz e legumes.",
  latitude: 28.4196,
  longitude: -81.5833,
},
{
  nome: "Liberty Snacks",
  regiao: "LibertySquare",
  tipo: "Economico",
  acesso: "PrÃ³ximo ao Liberty Square Riverboat",
  precoMedio: 10,
  destaque: "Snacks noturnos prÃ¡ticos com vista lateral para o hub. NÃ£o deixe de experimentar o pretzel recheado com cream cheese.",
  latitude: 28.4193,
  longitude: -81.5831,
},
{
  nome: "Revolution Greens",
  regiao: "LibertySquare",
  tipo: "Saudavel",
  acesso: "AtrÃ¡s da Liberty Tree Tavern",
  precoMedio: 13,
  destaque: "Saladas e wraps frescos em ambiente histÃ³rico. NÃ£o deixe de experimentar a salada morna de espinafre com frango grelhado.",
  latitude: 28.4192,
  longitude: -81.5835,
},
 // Fantasyland
{
  nome: "Be Our Guest Restaurant",
  regiao: "Fantasyland",
  tipo: "Tematico",
  acesso: "Dentro do castelo da Fera",
  precoMedio: 45,
  destaque: "Ambiente mÃ¡gico com salÃ£o iluminado por candelabros. NÃ£o deixe de experimentar o filet mignon com purÃª trufado.",
  latitude: 28.4203,
  longitude: -81.5805,
},
{
  nome: "Cinderellaâ€™s Royal Table",
  regiao: "Fantasyland",
  tipo: ["Classico", "Americano"],
  acesso: "Dentro do Castelo da Cinderela",
  precoMedio: 62,
  destaque: "Jantar real com princesas e vista para o show noturno. NÃ£o deixe de experimentar o frango assado com molho de maÃ§Ã£.",
  latitude: 28.4194,
  longitude: -81.5812,
},
{
  nome: "Pinocchio Village Haus",
  regiao: "Fantasyland",
  tipo: "Conforto",
  acesso: "Ao lado da atraÃ§Ã£o Itâ€™s a Small World",
  precoMedio: 18,
  destaque: "Ideal para famÃ­lias, com janelas temÃ¡ticas e iluminaÃ§Ã£o suave. NÃ£o deixe de experimentar o flatbread de pepperoni.",
  latitude: 28.4195,
  longitude: -81.5820,
},
{
  nome: "Gastonâ€™s Tavern",
  regiao: "Fantasyland",
  tipo: "Economico",
  acesso: "PrÃ³ximo Ã  Under the Sea â€“ Journey of the Little Mermaid",
  precoMedio: 14,
  destaque: "RÃºstico e aconchegante para um lanche noturno. NÃ£o deixe de experimentar o cinnamon roll gigante do Gaston.",
  latitude: 28.4211,
  longitude: -81.5809,
},
{
  nome: "The Friarâ€™s Nook",
  regiao: "Fantasyland",
  tipo: "Saudavel",
  acesso: "Ao lado do carrossel do PrÃ­ncipe Encantado",
  precoMedio: 13,
  destaque: "Oferece opÃ§Ãµes leves e prÃ¡ticas Ã  noite. NÃ£o deixe de experimentar o mac and cheese com bacon.",
  latitude: 28.4198,
  longitude: -81.5817,
},
// Tomorrowland
{
  nome: "Cosmic Rayâ€™s Starlight CafÃ©",
  regiao: "Tomorrowland",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente Ã  Buzz Lightyearâ€™s Space Ranger Spin",
  precoMedio: 20,
  destaque: "EspaÃ§o amplo com palco iluminado por Sonny Eclipse. NÃ£o deixe de experimentar o cheeseburger duplo com onion rings.",
  latitude: 28.4200,
  longitude: -81.5792,
},
{
  nome: "The Lunching Pad",
  regiao: "Tomorrowland",
  tipo: "Economico",
  acesso: "Na base da Astro Orbiter",
  precoMedio: 11,
  destaque: "Para um lanche rÃ¡pido sob as luzes futuristas. NÃ£o deixe de experimentar o pretzel recheado com cream cheese.",
  latitude: 28.4201,
  longitude: -81.5793,
},
{
  nome: "Tomorrowland Terrace (se aberto)",
  regiao: "Tomorrowland",
  tipo: "Conforto",
  acesso: "Entre Main Street e Tomorrowland",
  precoMedio: 16,
  destaque: "Visual incrÃ­vel para o castelo e o show noturno. NÃ£o deixe de experimentar o frango com molho teriyaki.",
  latitude: 28.4193,
  longitude: -81.5801,
},
{
  nome: "Galactic Snacks",
  regiao: "Tomorrowland",
  tipo: "Tematico",
  acesso: "PrÃ³ximo Ã  Space Mountain",
  precoMedio: 13,
  destaque: "IluminaÃ§Ã£o de LED e snacks sci-fi. NÃ£o deixe de experimentar o wrap galÃ¡ctico com frango grelhado e molho de mostarda doce.",
  latitude: 28.4202,
  longitude: -81.5794,
},
{
  nome: "Orbital Greens",
  regiao: "Tomorrowland",
  tipo: "Saudavel",
  acesso: "Ao lado do Space Ranger Spin",
  precoMedio: 17,
  destaque: "Saladas e bowls frios ideais para o fim do dia. NÃ£o deixe de experimentar o bowl de quinoa com legumes assados.",
  latitude: 28.4204,
  longitude: -81.5796,
},
// World Showcase
{
  nome: "La Hacienda de San Angel",
  regiao: "World Showcase",
  tipo: "Tematico",
  acesso: "PavilhÃ£o do MÃ©xico â€“ Ã  beira do lago",
  precoMedio: 42,
  destaque: "Vista espetacular para o show noturno. NÃ£o deixe de experimentar os tacos de camarÃ£o com arroz de limÃ£o.",
  latitude: 28.3711,
  longitude: -81.5475,
},
{
  nome: "Les Chefs de France",
  regiao: "World Showcase",
  tipo: ["Classico", "Americano"],
  acesso: "PavilhÃ£o da FranÃ§a â€“ com janelas panorÃ¢micas",
  precoMedio: 39,
  destaque: "ClÃ¡ssico francÃªs com charme Ã  luz baixa. NÃ£o deixe de experimentar o entrecÃ´te grelhado com batatas gratinadas.",
  latitude: 28.3705,
  longitude: -81.5502,
},
{
  nome: "Spice Road Table",
  regiao: "World Showcase",
  tipo: "Conforto",
  acesso: "PavilhÃ£o do Marrocos â€“ Ã  margem do lago",
  precoMedio: 28,
  destaque: "Ideal para uma noite relaxante Ã  beira dâ€™Ã¡gua. NÃ£o deixe de experimentar o hummus trio com pÃ£o sÃ­rio tostado.",
  latitude: 28.3708,
  longitude: -81.5493,
},
{
  nome: "La Cantina de San Angel",
  regiao: "World Showcase",
  tipo: "Economico",
  acesso: "PavilhÃ£o do MÃ©xico â€“ na beira do lago, ao lado da pirÃ¢mide",
  precoMedio: 15,
  destaque: "Tacos e nachos em estilo fast casual. NÃ£o deixe de experimentar o combo de tacos com guacamole.",
  latitude: 28.3711,
  longitude: -81.5475,
},
{
  nome: "Tangierine CafÃ©",
  regiao: "World Showcase",
  tipo: "Saudavel",
  acesso: "PavilhÃ£o do Marrocos â€“ em frente Ã  entrada da Fez House",
  precoMedio: 19,
  destaque: "Pratos mediterrÃ¢neos frescos e leves. NÃ£o deixe de provar o couscous com legumes grelhados e molho de limÃ£o.",
  latitude: 28.3708,
  longitude: -81.5493,
},

// World Discovery
{
  nome: "Space 220 Restaurant",
  regiao: "World Discovery",
  tipo: "Tematico",
  acesso: "Ao lado da Mission: SPACE",
  precoMedio: 55,
  destaque: "ExperiÃªncia imersiva em estaÃ§Ã£o espacial. NÃ£o deixe de experimentar o frango grelhado com purÃª roxo e legumes.",
  latitude: 28.3735,
  longitude: -81.5480,
},
{
  nome: "Connections Eatery",
  regiao: "World Discovery",
  tipo: ["Classico", "Americano"],
  acesso: "PrÃ³ximo da Guardians of the Galaxy",
  precoMedio: 26,
  destaque: "Ambiente moderno e iluminado Ã  noite. NÃ£o deixe de experimentar o hambÃºrguer gourmet com fritas de alho.",
  latitude: 28.3742,
  longitude: -81.5485,
},
{
  nome: "Test Track CafÃ©",
  regiao: "World Discovery",
  tipo: "Conforto",
  acesso: "Na saÃ­da da Test Track",
  precoMedio: 22,
  destaque: "Fast-casual com vibe futurista. NÃ£o deixe de experimentar o wrap de frango com pimenta defumada.",
  latitude: 28.3751,
  longitude: -81.5483,
},
{
  nome: "Mission Fuel CafÃ©",
  regiao: "World Discovery",
  tipo: "Economico",
  acesso: "Entre Test Track e Mission: SPACE",
  precoMedio: 14,
  destaque: "Para quem quer algo leve antes dos fogos. NÃ£o deixe de experimentar o sanduÃ­che de roast beef com queijo.",
  latitude: 28.3749,
  longitude: -81.5482,
},
{
  nome: "Nova Greens",
  regiao: "World Discovery",
  tipo: "Saudavel",
  acesso: "Ãrea lateral da Cosmic Rewind",
  precoMedio: 17,
  destaque: "Saladas e bowls frescos sob luz azul. NÃ£o deixe de experimentar o bowl de salmÃ£o com arroz de couve-flor.",
  latitude: 28.3748,
  longitude: -81.5477,
},
// World Celebration
{
  nome: "Eats at the Epcot Experience",
  regiao: "World Celebration",
  tipo: "Conforto",
  acesso: "PavilhÃ£o central da Spaceship Earth",
  precoMedio: 20,
  destaque: "EspaÃ§o amplo, colorido e ideal para o fim do dia. NÃ£o deixe de experimentar o sanduÃ­che de porco desfiado com coleslaw.",
  latitude: 28.3743,
  longitude: -81.5490,
},
{
  nome: "Sunshine Seasons (Jantar Estendido)",
  regiao: "World Celebration",
  tipo: "Saudavel",
  acesso: "Na base da Spaceship Earth",
  precoMedio: 16,
  destaque: "RefeiÃ§Ãµes rÃ¡pidas e nutritivas no coraÃ§Ã£o do parque. NÃ£o deixe de experimentar o bowl asiÃ¡tico com tofu grelhado.",
  latitude: 28.3741,
  longitude: -81.5488,
},
{
  nome: "Center Plate CafÃ©",
  regiao: "World Celebration",
  tipo: ["Classico", "Americano"],
  acesso: "Ãrea entre Spaceship Earth e Dreamers Point",
  precoMedio: 25,
  destaque: "Boa iluminaÃ§Ã£o e clima elegante. NÃ£o deixe de experimentar o prato de frango com legumes assados.",
  latitude: 28.3740,
  longitude: -81.5492,
},
{
  nome: "Visionary Bites",
  regiao: "World Celebration",
  tipo: "Economico",
  acesso: "Ao lado do Connections CafÃ©",
  precoMedio: 12,
  destaque: "RÃ¡pido e saboroso com Ã¡rea coberta. NÃ£o deixe de experimentar o wrap de salada Caesar com frango grelhado.",
  latitude: 28.3744,
  longitude: -81.5487,
},
{
  nome: "Dreamerâ€™s Garden Grill",
  regiao: "World Celebration",
  tipo: "Tematico",
  acesso: "Perto do Dreamers Point, vista para jardins noturnos",
  precoMedio: 30,
  destaque: "Ambiente tranquilo e bem decorado. NÃ£o deixe de experimentar o risoto de cogumelos com ervas frescas.",
  latitude: 28.3746,
  longitude: -81.5493,
},
// World Nature
{
  nome: "Coral Reef Restaurant",
  regiao: "World Nature",
  tipo: "Tematico",
  acesso: "Ao lado da The Seas with Nemo & Friends",
  precoMedio: 42,
  destaque: "Tanques de aquÃ¡rio iluminados tornam o jantar mÃ¡gico. NÃ£o deixe de experimentar o filÃ© de peixe com purÃª de batata ao limÃ£o.",
  latitude: 28.3732,
  longitude: -81.5501,
},
{
  nome: "The Land Grill CafÃ©",
  regiao: "World Nature",
  tipo: ["Classico", "Americano"],
  acesso: "Dentro do pavilhÃ£o The Land",
  precoMedio: 22,
  destaque: "Ambiente iluminado e bem ventilado Ã  noite. NÃ£o deixe de experimentar o frango grelhado com vegetais colhidos no pavilhÃ£o.",
  latitude: 28.3725,
  longitude: -81.5503,
},
{
  nome: "Living Greens",
  regiao: "World Nature",
  tipo: "Saudavel",
  acesso: "Ãrea interna do The Land",
  precoMedio: 17,
  destaque: "Pratos vegetarianos e bowls com produtos frescos. NÃ£o deixe de experimentar o bowl de quinoa com manga e abacate.",
  latitude: 28.3723,
  longitude: -81.5502,
},
{
  nome: "Nemo Snacks",
  regiao: "World Nature",
  tipo: "Economico",
  acesso: "PrÃ³ximo Ã  entrada da atraÃ§Ã£o do Nemo",
  precoMedio: 10,
  destaque: "Snacks rÃ¡pidos com vista do pÃ´r do sol. NÃ£o deixe de experimentar o pÃ£o pita com homus de cenoura.",
  latitude: 28.3734,
  longitude: -81.5504,
},
{
  nome: "Moana Island Grill",
  regiao: "World Nature",
  tipo: "Conforto",
  acesso: "Na Ã¡rea do novo Journey of Water",
  precoMedio: 20,
  destaque: "TemÃ¡tica de ilha e iluminaÃ§Ã£o natural. NÃ£o deixe de experimentar o prato de arroz havaiano com frango grelhado.",
  latitude: 28.3729,
  longitude: -81.5500,
},
// Hollywood Boulevard
{
  nome: "The Hollywood Brown Derby",
  regiao: "Hollywood Boulevard",
  tipo: ["Classico", "Americano"],
  acesso: "No final do boulevard principal, Ã  esquerda",
  precoMedio: 48,
  destaque: "Ambiente clÃ¡ssico de Hollywood com luz ambiente elegante. NÃ£o deixe de experimentar o Cobb Salad original da casa.",
  latitude: 28.3571,
  longitude: -81.5584,
},
{
  nome: "The Trolley Car CafÃ©",
  regiao: "Hollywood Boulevard",
  tipo: "Economico",
  acesso: "Ao lado da entrada do parque",
  precoMedio: 12,
  destaque: "Ideal para um jantar rÃ¡pido com bebidas e sanduÃ­ches. NÃ£o deixe de experimentar o panini de presunto com queijo suÃ­Ã§o.",
  latitude: 28.3574,
  longitude: -81.5585,
},
{
  nome: "Oscarâ€™s CafÃ©",
  regiao: "Hollywood Boulevard",
  tipo: "Conforto",
  acesso: "PrÃ³ximo ao Crossroads of the World",
  precoMedio: 18,
  destaque: "CafÃ© clÃ¡ssico com bancos externos iluminados. NÃ£o deixe de experimentar o hambÃºrguer grelhado com batatas fritas.",
  latitude: 28.3572,
  longitude: -81.5583,
},
{
  nome: "Studio Souvenirs Bites",
  regiao: "Hollywood Boulevard",
  tipo: "Saudavel",
  acesso: "Entre lojas temÃ¡ticas do inÃ­cio da avenida",
  precoMedio: 14,
  destaque: "Snacks leves e wraps frescos. NÃ£o deixe de experimentar o wrap vegetariano com molho de iogurte.",
  latitude: 28.3573,
  longitude: -81.5586,
},
{
  nome: "Brown Derby Lounge",
  regiao: "Hollywood Boulevard",
  tipo: "Tematico",
  acesso: "Ãrea externa do Brown Derby, com vista para o boulevard",
  precoMedio: 29,
  destaque: "CoquetÃ©is e porÃ§Ãµes sob luzes de toldo. NÃ£o deixe de experimentar as mini costelas com molho barbecue.",
  latitude: 28.3570,
  longitude: -81.5582,
},

// Echo Lake
{
  nome: "50â€™s Prime Time CafÃ©",
  regiao: "Echo Lake",
  tipo: "Tematico",
  acesso: "Ao lado do lago, prÃ³ximo Ã  Indiana Jones",
  precoMedio: 35,
  destaque: "Ambiente retrÃ´ com garÃ§ons interagindo. NÃ£o deixe de experimentar o frango frito com purÃª de batata.",
  latitude: 28.3567,
  longitude: -81.5595,
},
{
  nome: "Backlot Express",
  regiao: "Echo Lake",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado da Star Tours",
  precoMedio: 20,
  destaque: "Jantar prÃ¡tico com mesas internas e externas. NÃ£o deixe de experimentar o sanduÃ­che cubano.",
  latitude: 28.3570,
  longitude: -81.5590,
},
{
  nome: "Dockside Diner",
  regiao: "Echo Lake",
  tipo: "Conforto",
  acesso: "Ã€ beira do lago, com vista temÃ¡tica",
  precoMedio: 16,
  destaque: "IluminaÃ§Ã£o noturna linda ao redor do barco. NÃ£o deixe de experimentar o hot dog de camarÃ£o com molho cremoso.",
  latitude: 28.3569,
  longitude: -81.5593,
},
{
  nome: "Echo Snacks",
  regiao: "Echo Lake",
  tipo: "Economico",
  acesso: "Perto do Gertie the Dinosaur",
  precoMedio: 10,
  destaque: "Snacks rÃ¡pidos sob refletores antigos. NÃ£o deixe de experimentar o pretzel com cheddar e bacon.",
  latitude: 28.3571,
  longitude: -81.5591,
},
{
  nome: "Lakeside Greens",
  regiao: "Echo Lake",
  tipo: "Saudavel",
  acesso: "PrÃ³ximo ao Indiana Jones Epic Stunt Show",
  precoMedio: 15,
  destaque: "Saladas e wraps Ã  beira do lago. NÃ£o deixe de experimentar a salada de frango grelhado com vinagrete cÃ­trico.",
  latitude: 28.3568,
  longitude: -81.5594,
},

// Grand Avenue
{
  nome: "Mama Melroseâ€™s Ristorante Italiano",
  regiao: "Grand Avenue",
  tipo: ["Classico", "Americano"],
  acesso: "Dentro do Muppet Courtyard",
  precoMedio: 36,
  destaque: "Jantar italiano com clima acolhedor. NÃ£o deixe de experimentar o frango Ã  parmegiana com spaghetti.",
  latitude: 28.3557,
  longitude: -81.5611,
},
{
  nome: "PizzeRizzo",
  regiao: "Grand Avenue",
  tipo: "Economico",
  acesso: "Ao lado dos Muppets",
  precoMedio: 14,
  destaque: "Ambiente divertido com pizza rÃ¡pida. NÃ£o deixe de experimentar a pizza pepperoni com massa fina.",
  latitude: 28.3556,
  longitude: -81.5610,
},
{
  nome: "Grand Greens",
  regiao: "Grand Avenue",
  tipo: "Saudavel",
  acesso: "PrÃ³ximo Ã  entrada do Muppet Vision 3D",
  precoMedio: 15,
  destaque: "RefeiÃ§Ãµes leves e prÃ¡ticas. NÃ£o deixe de experimentar o bowl mediterrÃ¢neo com grÃ£o-de-bico.",
  latitude: 28.3555,
  longitude: -81.5609,
},
{
  nome: "Rizzoâ€™s Rooftop",
  regiao: "Grand Avenue",
  tipo: "Tematico",
  acesso: "No andar superior do PizzeRizzo",
  precoMedio: 22,
  destaque: "Vista elevada com decoraÃ§Ã£o dos Muppets. NÃ£o deixe de experimentar a lasanha com ricota e espinafre.",
  latitude: 28.3554,
  longitude: -81.5608,
},
{
  nome: "Backlot Bites",
  regiao: "Grand Avenue",
  tipo: "Conforto",
  acesso: "Na transiÃ§Ã£o para Galaxyâ€™s Edge",
  precoMedio: 18,
  destaque: "Perfeito para jantar antes da Ã¡rea Star Wars. NÃ£o deixe de experimentar o hambÃºrguer artesanal com bacon.",
  latitude: 28.3558,
  longitude: -81.5612,
},

// Star Wars: Galaxyâ€™s Edge
{
  nome: "Docking Bay 7 Food and Cargo",
  regiao: "Galaxyâ€™s Edge",
  tipo: "Tematico",
  acesso: "PrÃ³ximo Ã  Millennium Falcon",
  precoMedio: 28,
  destaque: "Ambiente imersivo com pratos galÃ¡cticos. NÃ£o deixe de experimentar o frango assado Endorian com purÃª de batata.",
  latitude: 28.3550,
  longitude: -81.5619,
},
{
  nome: "Ronto Roasters",
  regiao: "Galaxyâ€™s Edge",
  tipo: ["Classico", "Americano"],
  acesso: "Na praÃ§a central de Batuu",
  precoMedio: 16,
  destaque: "SanduÃ­ches famosos com tema sci-fi. NÃ£o deixe de experimentar o Ronto Wrap com linguiÃ§a defumada e porco.",
  latitude: 28.3552,
  longitude: -81.5617,
},
{
  nome: "Kat Sakaâ€™s Kettle",
  regiao: "Galaxyâ€™s Edge",
  tipo: "Economico",
  acesso: "Ao lado do mercado Black Spire",
  precoMedio: 9,
  destaque: "Pipocas galÃ¡cticas com sabores Ãºnicos. NÃ£o deixe de experimentar a pipoca doce picante vermelha e roxa.",
  latitude: 28.3553,
  longitude: -81.5618,
},
{
  nome: "Galactic Greens",
  regiao: "Galaxyâ€™s Edge",
  tipo: "Saudavel",
  acesso: "AtrÃ¡s do droid depot",
  precoMedio: 17,
  destaque: "Saladas criativas com ingredientes exÃ³ticos. NÃ£o deixe de experimentar o bowl de vegetais grelhados com molho azul.",
  latitude: 28.3551,
  longitude: -81.5616,
},
{
  nome: "Batuu Bites",
  regiao: "Galaxyâ€™s Edge",
  tipo: "Conforto",
  acesso: "Entre a loja do sabre de luz e o mercado",
  precoMedio: 19,
  destaque: "Pratos rÃ¡pidos e saborosos inspirados em Star Wars. NÃ£o deixe de experimentar o sanduÃ­che de frango picante com chips de raiz.",
  latitude: 28.3549,
  longitude: -81.5615,
},

// Toy Story Land
{
  nome: "Woodyâ€™s Lunch Box",
  regiao: "Toy Story Land",
  tipo: "Tematico",
  acesso: "Centro da Toy Story Land",
  precoMedio: 18,
  destaque: "CardÃ¡pio divertido com visual vibrante. NÃ£o deixe de experimentar o sanduÃ­che de brisket com queijo cheddar.",
  latitude: 28.3543,
  longitude: -81.5627,
},
{
  nome: "Buzz Lightyearâ€™s Grill",
  regiao: "Toy Story Land",
  tipo: ["Classico", "Americano"],
  acesso: "Ao lado do Alien Swirling Saucers",
  precoMedio: 21,
  destaque: "Comida americana em ambiente intergalÃ¡ctico. NÃ£o deixe de experimentar o hambÃºrguer de frango com batata canoa.",
  latitude: 28.3544,
  longitude: -81.5626,
},
{
  nome: "Jessieâ€™s Rodeo Wraps",
  regiao: "Toy Story Land",
  tipo: "Conforto",
  acesso: "Perto do Toy Story Mania",
  precoMedio: 17,
  destaque: "Lanches rÃ¡pidos com tema caipira. NÃ£o deixe de experimentar o wrap de carne com molho barbecue.",
  latitude: 28.3542,
  longitude: -81.5628,
},
{
  nome: "Andy's Snacks",
  regiao: "Toy Story Land",
  tipo: "Economico",
  acesso: "Entre a entrada da Ã¡rea e a Slinky Dog Dash",
  precoMedio: 10,
  destaque: "Snacks divertidos para o fim do dia. NÃ£o deixe de experimentar o cookie de marshmallow com gotas de chocolate.",
  latitude: 28.3541,
  longitude: -81.5625,
},
{
  nome: "Toy Greens",
  regiao: "Toy Story Land",
  tipo: "Saudavel",
  acesso: "AtrÃ¡s do Alien Swirling Saucers",
  precoMedio: 15,
  destaque: "OpÃ§Ãµes leves e nutritivas no mundo dos brinquedos. NÃ£o deixe de experimentar o bowl de frango com salada tropical.",
  latitude: 28.3545,
  longitude: -81.5629,
},

// Animation Courtyard
{
  nome: "Animatorâ€™s CafÃ©",
  regiao: "Animation Courtyard",
  tipo: "Tematico",
  acesso: "Ao lado da atraÃ§Ã£o Disney Junior",
  precoMedio: 26,
  destaque: "Jantar leve com animaÃ§Ãµes clÃ¡ssicas nas telas. NÃ£o deixe de experimentar a massa primavera com molho de tomate fresco.",
  latitude: 28.3550,
  longitude: -81.5601,
},
{
  nome: "Toon Bites",
  regiao: "Animation Courtyard",
  tipo: "Economico",
  acesso: "Perto da entrada da Ã¡rea de Star Wars",
  precoMedio: 11,
  destaque: "Snacks com tema de desenhos. NÃ£o deixe de experimentar a pipoca colorida e o suco de frutas congelado.",
  latitude: 28.3549,
  longitude: -81.5600,
},
{
  nome: "Courtyard Grill",
  regiao: "Animation Courtyard",
  tipo: ["Classico", "Americano"],
  acesso: "Na saÃ­da da atraÃ§Ã£o do Star Wars Launch Bay",
  precoMedio: 23,
  destaque: "ClÃ¡ssico americano com sombra e espaÃ§o. NÃ£o deixe de experimentar o cheeseburger com molho especial.",
  latitude: 28.3548,
  longitude: -81.5602,
},
{
  nome: "Disney Junior CafÃ©",
  regiao: "Animation Courtyard",
  tipo: "Conforto",
  acesso: "AtrÃ¡s da loja da Disney Junior",
  precoMedio: 15,
  destaque: "Lugar para pais descansarem com refeiÃ§Ãµes simples. NÃ£o deixe de experimentar o mac and cheese com legumes.",
  latitude: 28.3551,
  longitude: -81.5603,
},
{
  nome: "Animation Greens",
  regiao: "Animation Courtyard",
  tipo: "Saudavel",
  acesso: "Ao lado do Animatorâ€™s CafÃ©",
  precoMedio: 14,
  destaque: "Wraps e bowls com temÃ¡tica de desenhos animados. NÃ£o deixe de experimentar o bowl vegetariano com manga e molho cÃ­trico.",
  latitude: 28.3552,
  longitude: -81.5604,
},

// Sunset Boulevard
{
  nome: "Hollywood Scoops Grill",
  regiao: "Sunset Boulevard",
  tipo: ["Classico", "Americano"],
  acesso: "No inÃ­cio da Sunset Boulevard",
  precoMedio: 24,
  destaque: "ClÃ¡ssico americano em ambiente iluminado. NÃ£o deixe de experimentar o cheeseburger com molho de alho.",
  latitude: 28.3539,
  longitude: -81.5606,
},
{
  nome: "Sunset Ranch Market",
  regiao: "Sunset Boulevard",
  tipo: "Economico",
  acesso: "PrÃ³ximo ao Fantasmic!",
  precoMedio: 13,
  destaque: "Ideal para comer algo rÃ¡pido antes do show. NÃ£o deixe de experimentar o taco de frango grelhado.",
  latitude: 28.3540,
  longitude: -81.5605,
},
{
  nome: "Fairfax Fare",
  regiao: "Sunset Boulevard",
  tipo: "Tematico",
  acesso: "No meio da Sunset Boulevard",
  precoMedio: 20,
  destaque: "Ambiente de feira californiana. NÃ£o deixe de experimentar o bowl de carne ao estilo barbecue.",
  latitude: 28.3541,
  longitude: -81.5607,
},
{
  nome: "Sunset Snacks",
  regiao: "Sunset Boulevard",
  tipo: "Conforto",
  acesso: "Ao lado do Tower of Terror",
  precoMedio: 17,
  destaque: "Snacks e doces para o fim do dia. NÃ£o deixe de experimentar o churro recheado com doce de leite.",
  latitude: 28.3542,
  longitude: -81.5608,
},
{
  nome: "Boulevard Greens",
  regiao: "Sunset Boulevard",
  tipo: "Saudavel",
  acesso: "Ao lado do Rock â€˜nâ€™ Roller Coaster",
  precoMedio: 15,
  destaque: "RefeiÃ§Ãµes leves com mÃºsica ao fundo. NÃ£o deixe de experimentar o wrap de atum com ervas e molho iogurte.",
  latitude: 28.3543,
  longitude: -81.5609,
},
// Oasis
{
  nome: "Oasis Comfort CafÃ©",
  regiao: "Oasis",
  tipo: "Conforto",
  acesso: "Entre o Rainforest CafÃ© e o inÃ­cio da trilha para Discovery Island",
  precoMedio: 16,
  destaque: "Ambiente tranquilo com pratos caseiros, como mac and cheese, frango grelhado e sopa do dia. NÃ£o deixe de experimentar o mac and cheese cremoso com pÃ£o de alho.",
  latitude: 28.3551,
  longitude: -81.5916,
},

{
  nome: "Oasis Diner",
  regiao: "Oasis",
  tipo: ["Classico", "Americano"],
  acesso: "PrÃ³ximo Ã  ponte para Discovery Island, ao lado do Oasis Snacks",
  precoMedio: 20,
  destaque: "Pratos clÃ¡ssicos americanos como hambÃºrguer, cheeseburger, milk-shake e batata frita. NÃ£o deixe de experimentar o cheeseburger com bacon crocante e o milk-shake de baunilha.",
  latitude: 28.3552,
  longitude: -81.5911,
},
{
  nome: "Rainforest CafÃ© - Entrada Animal Kingdom",
  regiao: "Oasis",
  tipo: "Tematico",
  acesso: "Logo na entrada principal do parque",
  precoMedio: 36,
  destaque: "Ambiente de floresta tropical com sons da natureza. NÃ£o deixe de experimentar o churrasco misto com arroz e feijÃ£o preto.",
  latitude: 28.3556,
  longitude: -81.5913,
},
{
  nome: "Oasis Snacks",
  regiao: "Oasis",
  tipo: "Economico",
  acesso: "Ao lado da ponte para Discovery Island",
  precoMedio: 10,
  destaque: "Snacks rÃ¡pidos antes do show Rivers of Light. NÃ£o deixe de experimentar a pipoca com manteiga trufada.",
  latitude: 28.3555,
  longitude: -81.5912,
},
{
  nome: "Oasis Greens",
  regiao: "Oasis",
  tipo: "Saudavel",
  acesso: "Entre as trilhas iniciais do parque",
  precoMedio: 15,
  destaque: "OpÃ§Ãµes saudÃ¡veis com vista para vegetaÃ§Ã£o tropical. NÃ£o deixe de experimentar o wrap de salmÃ£o com ervas.",
  latitude: 28.3554,
  longitude: -81.5914,
},
// Discovery Island
{
  nome: "Discovery Grill",
  regiao: "Discovery Island",
  tipo: ["Classico", "Americano"],
  acesso: "Em frente ao Tree of Life, ao lado do Creature Comforts",
  precoMedio: 22,
  destaque: "Lanches clÃ¡ssicos americanos: hambÃºrguer, fritas crocantes, milk-shake e nuggets. NÃ£o deixe de experimentar o cheeseburger artesanal com bacon e o milk-shake de baunilha.",
  latitude: 28.3605,
  longitude: -81.5901,
},

{
  nome: "Tiffins Restaurant",
  regiao: "Discovery Island",
  tipo: "Tematico",
  acesso: "Perto da entrada de Pandora, com vista para o rio",
  precoMedio: 49,
  destaque: "Jantar refinado com pratos globais e luz ambiente. NÃ£o deixe de experimentar o polvo grelhado com purÃª de batata doce.",
  latitude: 28.3565,
  longitude: -81.5919,
},
{
  nome: "Creature Comforts",
  regiao: "Discovery Island",
  tipo: "Conforto",
  acesso: "Ao lado da ponte principal para a Tree of Life",
  precoMedio: 18,
  destaque: "CafÃ© com sanduÃ­ches e doces. NÃ£o deixe de experimentar o croissant de presunto com queijo suÃ­Ã§o derretido.",
  latitude: 28.3568,
  longitude: -81.5917,
},
{
  nome: "Island Snacks",
  regiao: "Discovery Island",
  tipo: "Economico",
  acesso: "Frente da Tree of Life",
  precoMedio: 10,
  destaque: "Snacks rÃ¡pidos com ambiente iluminado. NÃ£o deixe de experimentar o pretzel com cheddar e mostarda.",
  latitude: 28.3569,
  longitude: -81.5915,
},
{
  nome: "Tree Greens",
  regiao: "Discovery Island",
  tipo: "Saudavel",
  acesso: "Caminho lateral para a ponte de Asia",
  precoMedio: 16,
  destaque: "Bowls naturais e smoothies. NÃ£o deixe de experimentar a salada de quinoa com manga e amÃªndoas.",
  latitude: 28.3566,
  longitude: -81.5913,
},

//Pandora â€“ The World of Avatar
{
  nome: "Satuâ€™li Canteen",
  regiao: "Pandora",
  tipo: "Tematico",
  acesso: "PrÃ³ximo Ã  atraÃ§Ã£o Flight of Passage",
  precoMedio: 27,
  destaque: "Ambiente imersivo e pratos inspirados em Pandora. NÃ£o deixe de experimentar o bowl de carne com legumes assados e molho de ervas.",
  latitude: 28.3553,
  longitude: -81.5922,
},
{
  nome: "Pongu Pongu",
  regiao: "Pandora",
  tipo: "Economico",
  acesso: "Na entrada da Ã¡rea, ao lado do Satuâ€™li",
  precoMedio: 11,
  destaque: "Drinks e snacks alienÃ­genas. NÃ£o deixe de experimentar o pÃ£o doce recheado com creme de abacaxi.",
  latitude: 28.3552,
  longitude: -81.5921,
},
{
  nome: "Avatar Greens",
  regiao: "Pandora",
  tipo: "Saudavel",
  acesso: "Trilha lateral prÃ³xima ao Naâ€™vi River Journey",
  precoMedio: 15,
  destaque: "OpÃ§Ãµes leves com temÃ¡tica natural. NÃ£o deixe de experimentar o bowl de tofu com legumes coloridos.",
  latitude: 28.3551,
  longitude: -81.5923,
},
{
  nome: "Pandora Grill",
  regiao: "Pandora",
  tipo: "Conforto",
  acesso: "AtrÃ¡s do Satuâ€™li Canteen",
  precoMedio: 19,
  destaque: "SanduÃ­ches quentes em ambiente iluminado. NÃ£o deixe de experimentar o sanduÃ­che de frango com molho cÃ­trico.",
  latitude: 28.3554,
  longitude: -81.5920,
},
{
  nome: "Naâ€™vi Bites",
  regiao: "Pandora",
  tipo: ["Classico", "Americano"],
  acesso: "Caminho para o Flight of Passage",
  precoMedio: 22,
  destaque: "Comida rÃ¡pida com clima noturno de Pandora. NÃ£o deixe de experimentar o hambÃºrguer vegetal com batata doce frita.",
  latitude: 28.3550,
  longitude: -81.5924,
},
// Africa
{
  nome: "Tusker House Restaurant",
  regiao: "Africa",
  tipo: "Tematico",
  acesso: "Perto da ponte principal da Ã¡rea",
  precoMedio: 42,
  destaque: "Buffet africano com personagens. NÃ£o deixe de experimentar o frango ao molho de amendoim com arroz de coco.",
  latitude: 28.3548,
  longitude: -81.5931,
},
{
  nome: "Harambe Market",
  regiao: "Africa",
  tipo: ["Classico", "Americano"],
  acesso: "Centro da vila Harambe",
  precoMedio: 22,
  destaque: "Pratos africanos rÃ¡pidos ao ar livre. NÃ£o deixe de experimentar o espeto de carne bovina com molho picante.",
  latitude: 28.3549,
  longitude: -81.5930,
},
{
  nome: "Dawa Bar",
  regiao: "Africa",
  tipo: "Conforto",
  acesso: "PrÃ³ximo Ã  entrada do Kilimanjaro Safaris",
  precoMedio: 18,
  destaque: "Drinks e petiscos sob luzes de vila africana. NÃ£o deixe de experimentar o espetinho de frango com molho tamarindo.",
  latitude: 28.3547,
  longitude: -81.5932,
},
{
  nome: "Harambe Snacks",
  regiao: "Africa",
  tipo: "Economico",
  acesso: "Em frente ao Harambe Market",
  precoMedio: 11,
  destaque: "Lanches africanos para comer andando. NÃ£o deixe de experimentar a samosa de carne.",
  latitude: 28.3550,
  longitude: -81.5929,
},
{
  nome: "Safari Greens",
  regiao: "Africa",
  tipo: "Saudavel",
  acesso: "PrÃ³ximo ao Mombasa Marketplace",
  precoMedio: 15,
  destaque: "Saladas e bowls com toque africano. NÃ£o deixe de experimentar o bowl de lentilha com legumes grelhados.",
  latitude: 28.3546,
  longitude: -81.5933,
},
// Asia
{
  nome: "Yak & Yeti Restaurant",
  regiao: "Asia",
  tipo: "Tematico",
  acesso: "Ao lado da Expedition Everest",
  precoMedio: 38,
  destaque: "Jantar asiÃ¡tico com ambiente aconchegante. NÃ£o deixe de experimentar o frango com castanha e legumes orientais.",
  latitude: 28.3539,
  longitude: -81.5942,
},
{
  nome: "Yak & Yeti Local Food Cafes",
  regiao: "Asia",
  tipo: "Economico",
  acesso: "Em frente ao restaurante principal",
  precoMedio: 14,
  destaque: "Pratos rÃ¡pidos e saborosos da Ãsia. NÃ£o deixe de experimentar o arroz com frango teriyaki.",
  latitude: 28.3540,
  longitude: -81.5941,
},
{
  nome: "Thirsty River Bar & Trek Snacks",
  regiao: "Asia",
  tipo: "Conforto",
  acesso: "Na saÃ­da da Expedition Everest",
  precoMedio: 17,
  destaque: "Drinks e snacks com vista para a montanha. NÃ£o deixe de experimentar o mix de nozes e frutas secas.",
  latitude: 28.3538,
  longitude: -81.5940,
},
{
  nome: "Anandapur Greens",
  regiao: "Asia",
  tipo: "Saudavel",
  acesso: "Caminho para o Kali River Rapids",
  precoMedio: 15,
  destaque: "Bowls leves e opÃ§Ãµes veganas. NÃ£o deixe de experimentar o bowl de grÃ£o-de-bico com molho curry.",
  latitude: 28.3541,
  longitude: -81.5943,
},
{
  nome: "Asia Bites",
  regiao: "Asia",
  tipo: ["Classico", "Americano"],
  acesso: "PrÃ³ximo ao Maharajah Jungle Trek",
  precoMedio: 20,
  destaque: "Pratos tradicionais em ambiente asiÃ¡tico. NÃ£o deixe de experimentar o curry de frango tailandÃªs com arroz de jasmim.",
  latitude: 28.3542,
  longitude: -81.5944,
},
// DinoLand U.S.A.
{
  nome: "Restaurantosaurus",
  regiao: "DinoLand",
  tipo: ["Classico", "Americano"],
  acesso: "Centro da DinoLand, ao lado do Boneyard",
  precoMedio: 21,
  destaque: "Ambiente divertido com tema de paleontologia. NÃ£o deixe de experimentar o hambÃºrguer de bacon com queijo cheddar.",
  latitude: 28.3544,
  longitude: -81.5950,
},
{
  nome: "Dino Diner",
  regiao: "DinoLand",
  tipo: "Economico",
  acesso: "Ao lado da TriceraTop Spin",
  precoMedio: 11,
  destaque: "Comida rÃ¡pida em trailer temÃ¡tico. NÃ£o deixe de experimentar o hot dog com batata frita.",
  latitude: 28.3545,
  longitude: -81.5951,
},
{
  nome: "Fossil Fuel Snacks",
  regiao: "DinoLand",
  tipo: "Conforto",
  acesso: "Perto do Fossil Fun Games",
  precoMedio: 15,
  destaque: "Snacks doces e salgados. NÃ£o deixe de experimentar o sundae de chocolate com cookies.",
  latitude: 28.3546,
  longitude: -81.5952,
},
{
  nome: "Dino Greens",
  regiao: "DinoLand",
  tipo: "Saudavel",
  acesso: "Ao lado do restaurante Restaurantosaurus",
  precoMedio: 14,
  destaque: "Saladas e wraps refrescantes. NÃ£o deixe de experimentar a salada com frango grelhado e molho de mel.",
  latitude: 28.3547,
  longitude: -81.5953,
},
{
  nome: "Boneyard Bites",
  regiao: "DinoLand",
  tipo: "Tematico",
  acesso: "Na saÃ­da da Ã¡rea de escavaÃ§Ã£o infantil",
  precoMedio: 18,
  destaque: "Pratos criativos com decoraÃ§Ã£o de dinossauro. NÃ£o deixe de experimentar o sanduÃ­che de carne defumada com cheddar.",
  latitude: 28.3548,
  longitude: -81.5954,
},

  ];
