// CelestialPark.ts â€” corrigido (ids alinhados com ENTRIES_EPIC)
export const CelestialPark = {
  parque: "Universal's Epic Universe",
  regiao: "Celestial Park",
  latitude: 28.4719,
  longitude: -81.4719,
  descricao: "CoraÃ§Ã£o do Epic Universe com jardins, lagos e fontes coreografadas, conectando todos os mundos por portais.",
  imagem: "celestial-park.png",
  atracoes: [
    {
      id: "starfall-racers", // <- antes estava "stardust-racers"
      titulo: "Starfall Racers", // nome oficial
      subtitulo: "Celestial Park",
      tipo: "Montanha-russa lanÃ§ada (dueling)",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 122,
      filaExpress: true,
      tempoMedioFila: 90,
      filaAceitavel: 60,
      idadeRecomendada: "7+",
      atracaoSemFila: false,
      turnoRecomendado: "noite",
      descricao: "Dueling coaster de alta velocidade com elemento Celestial Spin. Ã€ noite os trens iluminados ficam incrÃ­veis.",
      icone: "âœ¨",
      imagem: "starfall-racers.jpg", // renomeie o arquivo se preciso
      regiao: "Celestial Park",
      parque: "Universal's Epic Universe",
      latitude: 28.4722,
      longitude: -81.4716
    },
    {
      id: "constellation-carousel",
      titulo: "Constellation Carousel",
      subtitulo: "Celestial Park",
      tipo: "Carrossel 360Â°",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Criaturas celestiais giram 360Â°; Ã³timo para fotos ao pÃ´r do sol.",
      icone: "ðŸª",
      imagem: "constellation-carousel.jpg",
      regiao: "Celestial Park",
      parque: "Universal's Epic Universe",
      latitude: 28.4717,
      longitude: -81.4721
    },
    {
      id: "astronomica",
      titulo: "Astronomica",
      subtitulo: "Celestial Park",
      tipo: "Playground aquÃ¡tico",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Splash pad com jatos, mapas celestes e muito calor aliviado. Leve troca de roupa.",
      icone: "ðŸ’§",
      imagem: "astronomica.jpg",
      regiao: "Celestial Park",
      parque: "Universal's Epic Universe",
      latitude: 28.4718,
      longitude: -81.4723
    },
    {
      id: "neptunes-pool",
      titulo: "Neptuneâ€™s Pool & Fountains",
      subtitulo: "Celestial Park",
      tipo: "Show de fontes e luzes",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "Fontes coreografadas com iluminaÃ§Ã£o â€” sequÃªncia especial Ã  noite.",
      icone: "ðŸŒŠ",
      imagem: "neptunes-pool.jpg",
      regiao: "Celestial Park",
      parque: "Universal's Epic Universe",
      latitude: 28.4720,
      longitude: -81.4718
    }
  ]
};
