ï»¿// CelestialPark.ts Ã¢â‚¬â€ corrigido (ids alinhados com ENTRIES_EPIC)
export const CelestialPark = {
  parque: "Universal's Epic Universe",
  regiao: "Celestial Park",
  latitude: 28.4719,
  longitude: -81.4719,
  descricao: "CoraÃƒÂ§ÃƒÂ£o do Epic Universe com jardins, lagos e fontes coreografadas, conectando todos os mundos por portais.",
  imagem: "celestial-park.png",
  atracoes: [
    {
      id: "starfall-racers", // <- antes estava "stardust-racers"
      titulo: "Starfall Racers", // nome oficial
      subtitulo: "Celestial Park",
      tipo: "Montanha-russa lanÃƒÂ§ada (dueling)",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 122,
      filaExpress: true,
      tempoMedioFila: 90,
      filaAceitavel: 60,
      idadeRecomendada: "7+",
      atracaoSemFila: false,
      turnoRecomendado: "noite",
      descricao: "Dueling coaster de alta velocidade com elemento Celestial Spin. Ãƒâ‚¬ noite os trens iluminados ficam incrÃƒÂ­veis.",
      icone: "Ã¢Å“Â¨",
      imagem: "starfall-racers.jpg", // renomeie o arquivo se preciso
      regiao: "Celestial Park",
      parque: "Universal's Epic Universe",
      latitude: 28.4722,
      longitude: -81.4716
    },
    {
      id: "constellation-carousel",
      titulo: "Constellation Carousel",
      subtitulo: "Celestial Park",
      tipo: "Carrossel 360Ã‚Â°",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Criaturas celestiais giram 360Ã‚Â°; ÃƒÂ³timo para fotos ao pÃƒÂ´r do sol.",
      icone: "Ã°Å¸ÂªÂ",
      imagem: "constellation-carousel.jpg",
      regiao: "Celestial Park",
      parque: "Universal's Epic Universe",
      latitude: 28.4717,
      longitude: -81.4721
    },
    {
      id: "astronomica",
      titulo: "Astronomica",
      subtitulo: "Celestial Park",
      tipo: "Playground aquÃƒÂ¡tico",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Splash pad com jatos, mapas celestes e muito calor aliviado. Leve troca de roupa.",
      icone: "Ã°Å¸â€™Â§",
      imagem: "astronomica.jpg",
      regiao: "Celestial Park",
      parque: "Universal's Epic Universe",
      latitude: 28.4718,
      longitude: -81.4723
    },
    {
      id: "neptunes-pool",
      titulo: "NeptuneÃ¢â‚¬â„¢s Pool & Fountains",
      subtitulo: "Celestial Park",
      tipo: "Show de fontes e luzes",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "Fontes coreografadas com iluminaÃƒÂ§ÃƒÂ£o Ã¢â‚¬â€ sequÃƒÂªncia especial ÃƒÂ  noite.",
      icone: "Ã°Å¸Å’Å ",
      imagem: "neptunes-pool.jpg",
      regiao: "Celestial Park",
      parque: "Universal's Epic Universe",
      latitude: 28.4720,
      longitude: -81.4718
    }
  ]
};
