export const Hollywood = {
  parque: "Universal Studios Florida",
  descricao: "Ãrea com clima de Hollywood clÃ¡ssico, com shows ao vivo e efeitos especiais que celebram o cinema.",
  imagem: "hollywood.png",
  latitude: 28.4731,
  longitude: -81.4680,
  atracoes: [
    {
      id: "the-bourne-stuntacular",
      titulo: "The Bourne Stuntacular",
      subtitulo: "Hollywood",
      tipo: "Show de dublÃªs",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Show cinematogrÃ¡fico com dublÃªs, telas gigantes e efeitos ao vivo que simulam perseguiÃ§Ãµes e cenas de aÃ§Ã£o.",
      icone: "ðŸŽ¬",
      imagem: "the-bourne-stuntacular.jpg",
      regiao: "Hollywood",
      parque: "Universal Studios Florida",
      latitude: 28.4734,
      longitude: -81.4686
    },
    {
      id: "horror-make-up-show",
      titulo: "Universal Orlandoâ€™s Horror Make-Up Show",
      subtitulo: "Hollywood",
      tipo: "Show de efeitos especiais",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "ApresentaÃ§Ã£o divertida que revela truques de maquiagem e efeitos prÃ¡ticos usados em filmes de terror.",
      icone: "ðŸŽ­",
      imagem: "horror-make-up-show.jpg",
      regiao: "Hollywood",
      parque: "Universal Studios Florida",
      latitude: 28.4728,
      longitude: -81.4681
    }
  ]
};
