ï»¿export const HowToTrainYourDragon = {
  parque: "Universal's Epic Universe",
  regiao: "How to Train Your Dragon",
  descricao: "ÃƒÂrea inspirada em *Como Treinar o Seu DragÃƒÂ£o*, com montanhas-russas familiares, batalha de barcos e um show impressionante com fantoches e efeitos.",
  imagem: "how-to-train-your-dragon.png",
  latitude: 28.4701,
  longitude: -81.4697,
  atracoes: [
    {
      id: "hiccups-wing-gliders",
      titulo: "Hiccup's Wing Gliders",
      subtitulo: "How to Train Your Dragon",
      tipo: "Montanha-russa familiar",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "5+",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Coaster familiar com curvas suaves sobre Berk. Nos ÃƒÂºltimos vagÃƒÂµes a sensaÃƒÂ§ÃƒÂ£o de velocidade aumenta.",
      icone: "Ã°Å¸ÂªÂ½",
      imagem: "hiccups-wing-gliders.jpg",
      regiao: "How to Train Your Dragon",
      parque: "Universal's Epic Universe",
      latitude: 28.4703,
      longitude: -81.4695
    },
    {
      id: "dragon-racers-rally",
      titulo: "Dragon RacersÃ¢â‚¬â„¢ Rally",
      subtitulo: "How to Train Your Dragon",
      tipo: "Brinquedo giratÃƒÂ³rio",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 97,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Gire e incline o seu dragÃƒÂ£o durante os treinos de corrida. Controle o ÃƒÂ¢ngulo para um pouco mais de emoÃƒÂ§ÃƒÂ£o.",
      icone: "Ã°Å¸ÂÂ²",
      imagem: "dragon-racers-rally.jpg",
      regiao: "How to Train Your Dragon",
      parque: "Universal's Epic Universe",
      latitude: 28.4704,
      longitude: -81.4698
    },
    {
      id: "fyre-drill",
      titulo: "Fyre Drill",
      subtitulo: "How to Train Your Dragon",
      tipo: "Batalha de barcos (ÃƒÂ¡gua)",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 35,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Treinamento de combate com canhÃƒÂµes dÃ¢â‚¬â„¢ÃƒÂ¡gua. VocÃƒÂª vai se molhar Ã¢â‚¬â€ leve capa ou troca de roupa.",
      icone: "Ã°Å¸â€™Â¦",
      imagem: "fyre-drill.jpg",
      regiao: "How to Train Your Dragon",
      parque: "Universal's Epic Universe",
      latitude: 28.4707,
      longitude: -81.4699
    },
    {
      id: "the-untrainable-dragon",
      titulo: "The Untrainable Dragon",
      subtitulo: "How to Train Your Dragon",
      tipo: "Show ao vivo",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "EspetÃƒÂ¡culo com Hiccup e Banguela, fantoches gigantes e trilha ÃƒÂ©pica. Chegue com antecedÃƒÂªncia para bons assentos.",
      icone: "Ã°Å¸Å½Â­",
      imagem: "the-untrainable-dragon.jpg",
      regiao: "How to Train Your Dragon",
      parque: "Universal's Epic Universe",
      latitude: 28.4705,
      longitude: -81.4696
    }
  ]
};
