export const JurassicPark = {
  parque: "Islands of Adventure",
  descricao: "Área temática baseada no Jurassic Park, com passeios de barco, encontros com dinossauros e atrações interativas que recriam o clima do filme com realismo impressionante.",
  imagem: "jurassic-park.png",
  latitude: 28.4700,
  longitude: -81.4732,
  atracoes: [
    {
      id: "jurassic-park-river-adventure",
      titulo: "Jurassic Park River Adventure",
      subtitulo: "Jurassic Park",
      tipo: "Passeio de barco",
      tipoPerfil: ["radicais", "tematicas", "imersivas"],
      alturaMinima: 107,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 40,
      idadeRecomendada: "A partir de 8 anos",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio de barco por cenários pré-históricos com dinossauros animatrônicos e uma grande queda final. Sentar na frente aumenta a emoção e os respingos.`,
      icone: "🦖",
      imagem: "jurassic-park-river-adventure.jpg",
      regiao: "Jurassic Park",
      parque: "Islands of Adventure",
      latitude: 28.4705,
      longitude: -81.4735
    },
    {
      id: "pteranodon-flyer",
      titulo: "Pteranodon Flyer",
      subtitulo: "Jurassic Park",
      tipo: "Montanha-russa suave",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 91,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Voo panorâmico suspenso sobre a área do parque, com movimentos suaves e vista privilegiada. Os assentos laterais oferecem melhor ângulo.`,
      icone: "🦅",
      imagem: "pteranodon-flyer.jpg",
      regiao: "Jurassic Park",
      parque: "Islands of Adventure",
      latitude: 28.4702,
      longitude: -81.4730
    },
    {
      id: "raptor-encounter",
      titulo: "Raptor Encounter",
      subtitulo: "Jurassic Park",
      tipo: "Encontro com dinossauro",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Interação realista com velociraptores animatrônicos para fotos e momentos divertidos. No fim da tarde a espera costuma ser menor.`,
      icone: "🦖",
      imagem: "raptor-encounter.jpg",
      regiao: "Jurassic Park",
      parque: "Islands of Adventure",
      latitude: 28.4704,
      longitude: -81.4732
    },
    {
      id: "jurassic-park-dig-site",
      titulo: "Jurassic Park Dig Site",
      subtitulo: "Jurassic Park",
      tipo: "Área de exploração",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Espaço para crianças escavarem fósseis e explorarem réplicas de dinossauros em um ambiente educativo. Ir cedo deixa o local mais livre.`,
      icone: "🦕",
      imagem: "jurassic-park-dig-site.jpg",
      regiao: "Jurassic Park",
      parque: "Islands of Adventure",
      latitude: 28.4706,
      longitude: -81.4733
    },
    {
      id: "jurassic-park-discovery-center",
      titulo: "Jurassic Park Discovery Center",
      subtitulo: "Jurassic Park",
      tipo: "Centro educacional",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Centro de descobertas com fósseis, réplicas e atividades interativas sobre o mundo dos dinossauros. Um bom local para descansar no calor.`,
      icone: "🔬",
      imagem: "jurassic-park-discovery-center.jpg",
      regiao: "Jurassic Park",
      parque: "Islands of Adventure",
      latitude: 28.4701,
      longitude: -81.4734
    }
  ]
};
