export const LostContinent = {
  parque: "Islands of Adventure",
  descricao: "Ãrea inspirada em mitologias antigas, com shows, atraÃ§Ãµes e mercados temÃ¡ticos que misturam mistÃ©rio, aventura e magia.",
  imagem: "lost-continent.png",
  latitude: 28.4702,
  longitude: -81.4712,
  atracoes: [
    {
      id: "the-eighth-voyage-of-sindbad",
      titulo: "The Eighth Voyage of Sindbad",
      subtitulo: "Lost Continent",
      tipo: "Show de acrobacias",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `EspetÃ¡culo com acrobacias, pirotecnia e batalhas coreografadas que recriam as aventuras de Sindbad, com boa visÃ£o para quem senta mais ao centro.`,
      icone: "ðŸ—¡ï¸",
      imagem: "the-eighth-voyage-of-sindbad.jpg",
      regiao: "Lost Continent",
      parque: "Islands of Adventure",
      latitude: 28.4703,
      longitude: -81.4715
    },
    {
      id: "poseidons-fury",
      titulo: "Poseidon's Fury",
      subtitulo: "Lost Continent",
      tipo: "Show de efeitos especiais",
      tipoPerfil: ["familiares", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `ExperiÃªncia imersiva que mistura mitologia grega e tecnologia com projeÃ§Ãµes, Ã¡gua, luzes e fogo, sendo mais impactante nas fileiras frontais.`,
      icone: "ðŸŒŠ",
      imagem: "poseidons-fury.jpg",
      regiao: "Lost Continent",
      parque: "Islands of Adventure",
      latitude: 28.4706,
      longitude: -81.4710
    },
    {
      id: "arabian-marketplace",
      titulo: "Arabian Marketplace",
      subtitulo: "Lost Continent",
      tipo: "Ãrea de compras e alimentaÃ§Ã£o",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Mercado temÃ¡tico com lojas e restaurantes inspirados na cultura Ã¡rabe que vale explorar sem pressa para encontrar itens Ãºnicos.`,
      icone: "ðŸ•Œ",
      imagem: "arabian-marketplace.jpg",
      regiao: "Lost Continent",
      parque: "Islands of Adventure",
      latitude: 28.4708,
      longitude: -81.4713
    },
    {
      id: "the-flying-unicorn",
      titulo: "The Flying Unicorn",
      subtitulo: "Lost Continent",
      tipo: "Montanha-russa suave",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 91,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Montanha-russa leve com percurso panorÃ¢mico ideal para famÃ­lias, rendendo boas fotos nas curvas mais altas.`,
      icone: "ðŸ¦„",
      imagem: "the-flying-unicorn.jpg",
      regiao: "Lost Continent",
      parque: "Islands of Adventure",
      latitude: 28.4707,
      longitude: -81.4714
    },
    {
      id: "the-mystic-fountain",
      titulo: "The Mystic Fountain",
      subtitulo: "Lost Continent",
      tipo: "Fonte interativa",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Fonte falante que interage com humor e jatos dâ€™Ã¡gua, rendendo momentos divertidos para quem se aproxima demais.`,
      icone: "â›²",
      imagem: "the-mystic-fountain.jpg",
      regiao: "Lost Continent",
      parque: "Islands of Adventure",
      latitude: 28.4709,
      longitude: -81.4715
    }
  ]
};
