ï»¿export const MarvelSuperHeroIsland = {
  parque: "Islands of Adventure",
  descricao: "ÃƒÂrea vibrante dedicada aos super-herÃƒÂ³is da Marvel, com montanhas-russas radicais, simuladores imersivos e encontros interativos com personagens icÃƒÂ´nicos como Spider-Man, Hulk e Doctor Strange.",
  imagem: "marvel-super-hero-island.png",
  latitude: 28.4709,
  longitude: -81.4721,
  atracoes: [
    {
      id: "the-incredible-hulk-coaster",
      titulo: "The Incredible Hulk Coaster",
      subtitulo: "Marvel Super Hero Island",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "tematicas", "imersivas"],
      alturaMinima: 137,
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 60,
      idadeRecomendada: "A partir de 12 anos",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Montanha-russa lanÃƒÂ§ada em alta velocidade com loops, inversÃƒÂµes e forÃƒÂ§a intensa, simulando a fÃƒÂºria do Hulk. Assentos da frente oferecem a melhor vista e sensaÃƒÂ§ÃƒÂ£o de velocidade.`,
      icone: "Ã°Å¸Å¸Â¢",
      imagem: "the-incredible-hulk-coaster.jpg",
      regiao: "Marvel Super Hero Island",
      parque: "Islands of Adventure",
      latitude: 28.4712,
      longitude: -81.4724
    },
    {
      id: "the-amazing-adventures-of-spider-man",
      titulo: "The Amazing Adventures of Spider-Man",
      subtitulo: "Marvel Super Hero Island",
      tipo: "Simulador 3D",
      tipoPerfil: ["radicais", "interativas", "imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 45,
      idadeRecomendada: "A partir de 10 anos",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Simulador 3D que mistura movimentos reais, efeitos especiais e cenas imersivas enquanto Spider-Man enfrenta vilÃƒÂµes. Use os ÃƒÂ³culos 3D e observe os detalhes para aproveitar ao mÃƒÂ¡ximo.`,
      icone: "Ã°Å¸â€¢Â·Ã¯Â¸Â",
      imagem: "the-amazing-adventures-of-spider-man.jpg",
      regiao: "Marvel Super Hero Island",
      parque: "Islands of Adventure",
      latitude: 28.4715,
      longitude: -81.4727
    },
    {
      id: "doctor-stranges-journey",
      titulo: "Doctor StrangeÃ¢â‚¬â„¢s Journey",
      subtitulo: "Marvel Super Hero Island",
      tipo: "AtraÃƒÂ§ÃƒÂ£o imersiva",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Jornada visual pelo multiverso com projeÃƒÂ§ÃƒÂµes e efeitos especiais inspirados em Doctor Strange. ExperiÃƒÂªncia rica em magia e cenÃƒÂ¡rios detalhados, perfeita para fÃƒÂ£s do herÃƒÂ³i.`,
      icone: "Ã°Å¸Å’â‚¬",
      imagem: "doctor-stranges-journey.jpg",
      regiao: "Marvel Super Hero Island",
      parque: "Islands of Adventure",
      latitude: 28.4718,
      longitude: -81.4730
    },
    {
      id: "storm-force-acceleration",
      titulo: "Storm Force Acceleration",
      subtitulo: "Marvel Super Hero Island",
      tipo: "AtraÃƒÂ§ÃƒÂ£o giratÃƒÂ³ria",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Brinquedo giratÃƒÂ³rio inspirado na personagem Storm, com giros rÃƒÂ¡pidos e controle de velocidade. Sente-se nas extremidades para maior sensaÃƒÂ§ÃƒÂ£o de movimento.`,
      icone: "Ã°Å¸Å’Â©Ã¯Â¸Â",
      imagem: "storm-force-acceleration.jpg",
      regiao: "Marvel Super Hero Island",
      parque: "Islands of Adventure",
      latitude: 28.4720,
      longitude: -81.4732
    },
    {
      id: "meet-spider-man",
      titulo: "Meet Spider-Man",
      subtitulo: "Marvel Super Hero Island",
      tipo: "Encontro com personagem",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 5,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Encontro com o Spider-Man para fotos e interaÃƒÂ§ÃƒÂ£o. ExperiÃƒÂªncia imperdÃƒÂ­vel para fÃƒÂ£s e crianÃƒÂ§as, com momentos descontraÃƒÂ­dos e poses clÃƒÂ¡ssicas do herÃƒÂ³i.`,
      icone: "Ã°Å¸â€¢Â·Ã¯Â¸Â",
      imagem: "meet-spider-man.jpg",
      regiao: "Marvel Super Hero Island",
      parque: "Islands of Adventure",
      latitude: 28.4722,
      longitude: -81.4733
    }
  ]
};
