export const MinionsLand = {
  parque: "Universal Studios Florida",
  descricao: "Área temática dedicada aos Minions e ao universo de Meu Malvado Favorito, com simuladores, tiro interativo e encontros divertidos.",
  imagem: "minions-land.png",
  latitude: 28.4703,
  longitude: -81.4725,
  atracoes: [
    {
      id: "despicable-me-minion-mayhem",
      titulo: "Despicable Me Minion Mayhem",
      subtitulo: "Minions Land",
      tipo: "Simulador 3D",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Simulador 3D com os Minions em uma missão caótica e cheia de humor. Assentos centrais oferecem melhor visão.",
      icone: "😜",
      imagem: "despicable-me-minion-mayhem.jpg",
      regiao: "Minions Land",
      parque: "Universal Studios Florida",
      latitude: 28.4706,
      longitude: -81.4728
    },
    {
      id: "villain-con-minion-blast",
      titulo: "Villain-Con Minion Blast",
      subtitulo: "Minions Land",
      tipo: "Tiro interativo",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 107,
      filaExpress: false,
      tempoMedioFila: 35,
      filaAceitavel: 25,
      idadeRecomendada: "A partir de 7 anos",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Aventura de tiro interativo em esteiras, com desafios e placar. Mire nos alvos raros para pontuação extra.",
      icone: "🔫",
      imagem: "villain-con-minion-blast.jpg",
      regiao: "Minions Land",
      parque: "Universal Studios Florida",
      latitude: 28.4707,
      longitude: -81.4730
    },
    {
      id: "illumination-theater",
      titulo: "Illumination Theater – Meet & Greet",
      subtitulo: "Minions Land",
      tipo: "Encontro com personagem",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Fotos e interação com Minions, Gru e amigos no teatro da Illumination. Momentos ótimos para crianças.",
      icone: "📸",
      imagem: "illumination-theater.jpg",
      regiao: "Minions Land",
      parque: "Universal Studios Florida",
      latitude: 28.4709,
      longitude: -81.4732
    }
  ]
};
