export const NewYork = {
  parque: "Universal Studios Florida",
  descricao: "Área inspirada na cidade de Nova York, com simuladores e shows de rua que recriam o clima urbano e cinematográfico.",
  imagem: "new-york.png",
  latitude: 28.4745,
  longitude: -81.4670,
  atracoes: [
    {
      id: "race-through-new-york-starring-jimmy-fallon",
      titulo: "Race Through New York Starring Jimmy Fallon",
      subtitulo: "New York",
      tipo: "Simulador 3D",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Simulador 3D de corrida por Nova York com humor e efeitos; assentos centrais melhoram a imersão.",
      icone: "🎤",
      imagem: "race-through-new-york-starring-jimmy-fallon.jpg",
      regiao: "New York",
      parque: "Universal Studios Florida",
      latitude: 28.4743,
      longitude: -81.4672
    },
    {
      id: "revenge-of-the-mummy",
      titulo: "Revenge of the Mummy",
      subtitulo: "New York",
      tipo: "Montanha-russa no escuro",
      tipoPerfil: ["radicais", "tematicas", "imersivas"],
      alturaMinima: 122,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "A partir de 12 anos",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Coaster indoor com curvas rápidas e efeitos temáticos; o ‘final falso’ surpreende.",
      icone: "🪦",
      imagem: "revenge-of-the-mummy.jpg",
      regiao: "New York",
      parque: "Universal Studios Florida",
      latitude: 28.4747,
      longitude: -81.4675
    },
    {
      id: "the-blues-brothers-show",
      titulo: "The Blues Brothers Show",
      subtitulo: "New York",
      tipo: "Show ao vivo",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Show musical de rua com clássicos do blues e interação com o público.",
      icone: "🎷",
      imagem: "the-blues-brothers-show.jpg",
      regiao: "New York",
      parque: "Universal Studios Florida",
      latitude: 28.4743,
      longitude: -81.4672
    }
  ]
};
