export const SeussLanding = {
  parque: "Islands of Adventure",
  regiao: "Seuss Landing",
  latitude: 28.4707,
  longitude: -81.4722,
  descricao:
    "Área infantil inspirada nos livros do Dr. Seuss, repleta de cores, criatividade e personagens icônicos. Ideal para famílias com crianças pequenas, com brinquedos suaves e experiências lúdicas.",
  imagem: "seuss-landing.png",
  atracoes: [
    {
      id: "cat-in-the-hat",
      titulo: "The Cat in the Hat",
      subtitulo: "Seuss Landing",
      tipo: "Dark ride familiar",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao:
        "Passeio em carrinho pelos livros do 'Cat in the Hat', com cenários coloridos e narrativa divertida. Perfeito para crianças e fãs das histórias clássicas do Dr. Seuss.",
      icone: "🎩",
      imagem: "cat-in-the-hat.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4709,
      longitude: -81.4723
    },
    {
      id: "one-fish-two-fish-red-fish-blue-fish",
      titulo: "One Fish, Two Fish, Red Fish, Blue Fish",
      subtitulo: "Seuss Landing",
      tipo: "Brinquedo giratório interativo",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao:
        "Voe em peixes coloridos controlando a altura do passeio. Ouça a música e siga as instruções — subir ou descer na hora errada pode render um divertido banho!",
      icone: "🐟",
      imagem: "one-fish-two-fish-red-fish-blue-fish.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4710,
      longitude: -81.4724
    },
    {
      id: "the-grinchmas-whoville",
      titulo: "The Grinchmas Whoville",
      subtitulo: "Seuss Landing",
      tipo: "Show musical ao vivo (sazonal)",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao:
        "Espetáculo natalino com o Grinch e os Whos, repleto de humor, músicas e figurinos vibrantes. Realizado apenas durante a temporada de Natal (novembro a janeiro).",
      icone: "🎄",
      imagem: "the-grinchmas-whoville.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4711,
      longitude: -81.4725
    },
    {
      id: "high-in-the-sky-seuss-trolley-train-ride",
      titulo: "High in the Sky Seuss Trolley Train Ride!",
      subtitulo: "Seuss Landing",
      tipo: "Passeio de trem panorâmico",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 91,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao:
        "Passeio de trem elevado com vistas panorâmicas e histórias narradas pelos personagens de Dr. Seuss. Excelente para fotos da área e descanso leve.",
      icone: "🚂",
      imagem: "high-in-the-sky-seuss-trolley-train-ride.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4712,
      longitude: -81.4726
    },
    {
      id: "caro-seuss-el",
      titulo: "Caro-Seuss-el",
      subtitulo: "Seuss Landing",
      tipo: "Carrossel temático",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao:
        "Carrossel com criaturas fantásticas e coloridas saídas dos livros de Dr. Seuss. As figuras se movem e interagem — ideal para fotos divertidas e lembranças em família.",
      icone: "🎠",
      imagem: "caro-seuss-el.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4713,
      longitude: -81.4727
    }
  ]
};
