export const SeussLanding = {
  parque: "Islands of Adventure",
  descricao: "Ãrea infantil inspirada nos livros do Dr. Seuss, com atraÃ§Ãµes coloridas, personagens icÃ´nicos e experiÃªncias lÃºdicas para toda a famÃ­lia.",
  imagem: "seuss-landing.png",
  latitude: 28.4707,
  longitude: -81.4722,
  atracoes: [
    {
      id: "cat-in-the-hat",
      titulo: "The Cat in the Hat",
      subtitulo: "Seuss Landing",
      tipo: "Brinquedo de passeio",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Passeio interativo pelo mundo do "Cat in the Hat", com cenÃ¡rios vibrantes e histÃ³rias divertidas â€” Ã³timo para crianÃ§as pequenas que gostam de explorar com calma.`,
      icone: "ðŸŽ©",
      imagem: "cat-in-the-hat.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4709,
      longitude: -81.4723
    },
    {
      id: "one-fish-two-fish-red-fish-blue-fish",
      titulo: "One Fish, Two Fish, Red Fish, Blue Fish",
      subtitulo: "Seuss Landing",
      tipo: "Brinquedo giratÃ³rio",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Brinquedo giratÃ³rio com controle de altura inspirado nos peixes coloridos das histÃ³rias de Dr. Seuss â€” seguir as instruÃ§Ãµes de subir e descer evita um banho inesperado.`,
      icone: "ðŸŸ",
      imagem: "one-fish-two-fish-red-fish-blue-fish.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4710,
      longitude: -81.4724
    },
    {
      id: "the-grinchmas-whoville",
      titulo: "The Grinchmas Whoville",
      subtitulo: "Seuss Landing",
      tipo: "Show ao vivo",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: `EspetÃ¡culo musical com o Grinch e os Whos, repleto de humor e clima natalino â€” sentar mais Ã  frente garante melhor visÃ£o das expressÃµes e figurinos.`,
      icone: "ðŸŽ„",
      imagem: "the-grinchmas-whoville.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4711,
      longitude: -81.4725
    },
    {
      id: "high-in-the-sky-seuss-trolley-train-ride",
      titulo: "High in the Sky Seuss Trolley Train Ride",
      subtitulo: "Seuss Landing",
      tipo: "Passeio de trem",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio de trem elevado com vista panorÃ¢mica e narraÃ§Ã£o de histÃ³rias inspiradas no Dr. Seuss â€” ideal para fotos do parque de um Ã¢ngulo diferente.`,
      icone: "ðŸš‚",
      imagem: "high-in-the-sky-seuss-trolley-train-ride.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4712,
      longitude: -81.4726
    },
    {
      id: "caro-seuss-elastic",
      titulo: "Caro-Seuss-Elastic",
      subtitulo: "Seuss Landing",
      tipo: "Carrossel",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Carrossel temÃ¡tico com criaturas e personagens das histÃ³rias do Dr. Seuss â€” perfeito para fotos coloridas e lembranÃ§as divertidas.`,
      icone: "ðŸŽ ",
      imagem: "caro-seuss-elastic.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4713,
      longitude: -81.4727
    }
  ]
};
