export const SeussLanding = {
  parque: "Islands of Adventure",
  descricao: "Área infantil inspirada nos livros do Dr. Seuss, com atrações coloridas, personagens icônicos e experiências lúdicas para toda a família.",
  imagem: "seuss-landing.png",
  latitude: 28.4707,
  longitude: -81.4722,
  atracoes: [
    {
      id: "cat-in-the-hat",
      titulo: "The Cat in the Hat",
      subtitulo: "Seuss Landing",
      tipo: "Brinquedo de passeio",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Passeio interativo pelo mundo do "Cat in the Hat", com cenários vibrantes e histórias divertidas — ótimo para crianças pequenas que gostam de explorar com calma.`,
      icone: "🎩",
      imagem: "cat-in-the-hat.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4709,
      longitude: -81.4723
    },
    {
      id: "one-fish-two-fish-red-fish-blue-fish",
      titulo: "One Fish, Two Fish, Red Fish, Blue Fish",
      subtitulo: "Seuss Landing",
      tipo: "Brinquedo giratório",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Brinquedo giratório com controle de altura inspirado nos peixes coloridos das histórias de Dr. Seuss — seguir as instruções de subir e descer evita um banho inesperado.`,
      icone: "🐟",
      imagem: "one-fish-two-fish-red-fish-blue-fish.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4710,
      longitude: -81.4724
    },
    {
      id: "the-grinchmas-whoville",
      titulo: "The Grinchmas Whoville",
      subtitulo: "Seuss Landing",
      tipo: "Show ao vivo",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: `Espetáculo musical com o Grinch e os Whos, repleto de humor e clima natalino — sentar mais à frente garante melhor visão das expressões e figurinos.`,
      icone: "🎄",
      imagem: "the-grinchmas-whoville.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4711,
      longitude: -81.4725
    },
    {
      id: "high-in-the-sky-seuss-trolley-train-ride",
      titulo: "High in the Sky Seuss Trolley Train Ride",
      subtitulo: "Seuss Landing",
      tipo: "Passeio de trem",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio de trem elevado com vista panorâmica e narração de histórias inspiradas no Dr. Seuss — ideal para fotos do parque de um ângulo diferente.`,
      icone: "🚂",
      imagem: "high-in-the-sky-seuss-trolley-train-ride.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4712,
      longitude: -81.4726
    },
    {
      id: "caro-seuss-elastic",
      titulo: "Caro-Seuss-Elastic",
      subtitulo: "Seuss Landing",
      tipo: "Carrossel",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Carrossel temático com criaturas e personagens das histórias do Dr. Seuss — perfeito para fotos coloridas e lembranças divertidas.`,
      icone: "🎠",
      imagem: "caro-seuss-elastic.jpg",
      regiao: "Seuss Landing",
      parque: "Islands of Adventure",
      latitude: 28.4713,
      longitude: -81.4727
    }
  ]
};
