ï»¿// src/logic/geradores/AreasUniversal/SuperNintendoWorld.ts
export const SuperNintendoWorld = {
  parque: "Universal's Epic Universe",
  regiao: "Super Nintendo World",
  descricao: "ÃƒÂrea imersiva da Nintendo com simuladores, passeios e interaÃƒÂ§ÃƒÂµes inspiradas em Super Mario e Donkey Kong.",
  imagem: "super-nintendo-world.png",
  latitude: 28.4708,
  longitude: -81.4729,
  atracoes: [
    {
      id: "mario-kart-bowser",
      titulo: "Mario Kart: Bowser's Challenge",
      subtitulo: "Super Nintendo World",
      tipo: "Simulador interativo",
      tipoPerfil: ["radicais", "tematicas", "interativas"],
      alturaMinima: 107,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 50,
      idadeRecomendada: "A partir de 10 anos",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Simulador competitivo no universo Mario Kart, com itens, drift e disputa contra Bowser. Dica: mire nos alvos grandes para combos e mais pontos.",
      icone: "Ã°Å¸ÂÅ½Ã¯Â¸Â",
      imagem: "mario-kart-bowsers-challenge.jpg",
      regiao: "Super Nintendo World",
      parque: "Universal's Epic Universe",
      latitude: 28.4710,
      longitude: -81.4730
    },
    {
      id: "yoshis-adventure",
      titulo: "Yoshi's Adventure",
      subtitulo: "Super Nintendo World",
      tipo: "Passeio de carrinho",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Passeio tranquilo com o Yoshi por cenÃƒÂ¡rios coloridos cheios de ovos e segredos. Ãƒâ€œtimo para crianÃƒÂ§as pequenas e fotos.",
      icone: "Ã°Å¸ÂÂ¢",
      imagem: "yoshis-adventure.jpg",
      regiao: "Super Nintendo World",
      parque: "Universal's Epic Universe",
      latitude: 28.4712,
      longitude: -81.4732
    },
    {
      id: "mine-cart-madness",
      titulo: "Mine-Cart Madness",
      subtitulo: "Super Nintendo World",
      tipo: "Montanha-russa familiar",
      tipoPerfil: ["radicais", "tematicas", "familiares"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 55,
      filaAceitavel: 40,
      idadeRecomendada: "7+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Coaster de Donkey Kong com truques de trilho e sensaÃƒÂ§ÃƒÂ£o de Ã¢â‚¬Å“saltosÃ¢â‚¬Â pelos vagÃƒÂµes da mina. ÃƒÅ¡ltimos carros deixam a experiÃƒÂªncia mais intensa.",
      icone: "Ã°Å¸ÂÅ’",
      imagem: "mine-cart-madness.jpg",
      regiao: "Super Nintendo World",
      parque: "Universal's Epic Universe",
      latitude: 28.4711,
      longitude: -81.4731
    }
  ]
};
