export const TheWizardingWorldHogsmeade = {
  parque: "Islands of Adventure",
  descricao: "Ãrea temÃ¡tica de Hogsmeade, com simuladores, montanhas-russas e lojas que recriam o universo de *Harry Potter* com riqueza de detalhes.",
  imagem: "hogsmeade.png",
  latitude: 28.4714,
  longitude: -81.4736,
  atracoes: [
    {
      id: "harry-potter-and-the-forbidden-journey",
      titulo: "Harry Potter and the Forbidden Journey",
      subtitulo: "Hogsmeade",
      tipo: "Simulador 3D",
      tipoPerfil: ["radicais", "interativas", "tematicas"],
      alturaMinima: 122,
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 60,
      idadeRecomendada: "A partir de 10 anos",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Simulador 3D por Hogwarts com batalhas, criaturas mÃ¡gicas e efeitos especiais, ficando mais imersivo ao sentar nas fileiras centrais.`,
      icone: "âš¡",
      imagem: "harry-potter-forbidden-journey.jpg",
      regiao: "Hogsmeade",
      parque: "Islands of Adventure",
      latitude: 28.4715,
      longitude: -81.4738
    },
    {
      id: "flight-of-the-hippogriff",
      titulo: "Flight of the Hippogriff",
      subtitulo: "Hogsmeade",
      tipo: "Montanha-russa infantil",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 91,
      filaExpress: false,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Montanha-russa suave com vista panorÃ¢mica do Castelo de Hogwarts e percurso mais emocionante Ã  noite.`,
      icone: "ðŸ¦…",
      imagem: "flight-of-the-hippogriff.jpg",
      regiao: "Hogsmeade",
      parque: "Islands of Adventure",
      latitude: 28.4717,
      longitude: -81.4739
    },
    {
      id: "hogwarts-express-hogsmeade-station",
      titulo: "Hogwarts Express",
      subtitulo: "Hogsmeade",
      tipo: "Passeio de trem",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio de trem com simulaÃ§Ã£o imersiva ligando Hogsmeade ao Beco Diagonal, sendo melhor aproveitar fazendo o trajeto nos dois sentidos.`,
      icone: "ðŸš‚",
      imagem: "hogwarts-express.jpg",
      regiao: "Hogsmeade",
      parque: "Islands of Adventure",
      latitude: 28.4719,
      longitude: -81.4740
    },
    {
      id: "olivanders-wand-shop",
      titulo: "Ollivanders Wand Shop",
      subtitulo: "Hogsmeade",
      tipo: "Loja interativa",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Loja onde ocorre a experiÃªncia da varinha escolher o bruxo, sendo mais envolvente em grupos menores.`,
      icone: "ðŸª„",
      imagem: "olivanders-wand-shop.jpg",
      regiao: "Hogsmeade",
      parque: "Islands of Adventure",
      latitude: 28.4720,
      longitude: -81.4741
    },
    {
      id: "hagrids-magical-creatures-motorbike-adventure",
      titulo: "Hagridâ€™s Magical Creatures Motorbike Adventure",
      subtitulo: "Hogsmeade",
      tipo: "Montanha-russa temÃ¡tica",
      tipoPerfil: ["radicais", "tematicas", "imersivas"],
      alturaMinima: 122,
      filaExpress: true,
      tempoMedioFila: 80,
      filaAceitavel: 60,
      idadeRecomendada: "A partir de 12 anos",
      atracaoSemFila: false,
      turnoRecomendado: "noite",
      descricao: `Montanha-russa veloz pela Floresta Proibida em motos mÃ¡gicas guiadas por Hagrid, sendo mais imersiva no assento da moto.`,
      icone: "ðŸï¸",
      imagem: "hagrid-motorbike-adventure.jpg",
      regiao: "Hogsmeade",
      parque: "Islands of Adventure",
      latitude: 28.4721,
      longitude: -81.4742
    }
  ]
};
