ï»¿export const ToonLagoon = {
  parque: "Islands of Adventure",
  descricao: "ÃƒÂrea inspirada em desenhos clÃƒÂ¡ssicos, com atraÃƒÂ§ÃƒÂµes aquÃƒÂ¡ticas e interativas para toda a famÃƒÂ­lia.",
  imagem: "toon-lagoon.png",
  latitude: 28.4705,
  longitude: -81.4723,
  atracoes: [
    {
      id: "rip-saw-falls",
      titulo: "Rip-Saw Falls",
      subtitulo: "Toon Lagoon",
      tipo: "Montanha-russa aquÃƒÂ¡tica",
      tipoPerfil: ["radicais", "tematicas", "interativas"],
      alturaMinima: 107,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 40,
      idadeRecomendada: "A partir de 10 anos",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Montanha-russa aquÃƒÂ¡tica com quedas rÃƒÂ¡pidas e cenÃƒÂ¡rio divertido, garantindo respingos generosos principalmente na primeira fila.`,
      icone: "Ã°Å¸â€™Â¦",
      imagem: "rip-saw-falls.jpg",
      regiao: "Toon Lagoon",
      parque: "Islands of Adventure",
      latitude: 28.4706,
      longitude: -81.4725
    },
    {
      id: "duff-beer",
      titulo: "Duff Beer Garden",
      subtitulo: "Toon Lagoon",
      tipo: "Restaurante temÃƒÂ¡tico",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Bar temÃƒÂ¡tico dos Simpsons com petiscos e cervejas, sendo imperdÃƒÂ­vel experimentar a famosa Duff Beer bem gelada.`,
      icone: "Ã°Å¸ÂÂº",
      imagem: "duff-beer.jpg",
      regiao: "Toon Lagoon",
      parque: "Islands of Adventure",
      latitude: 28.4707,
      longitude: -81.4726
    },
    {
      id: "scooby-doo-spooky-coaster",
      titulo: "Scooby-Doo's Spooky Coaster",
      subtitulo: "Toon Lagoon",
      tipo: "Montanha-russa infantil",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 91,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Montanha-russa suave com Scooby e a turma em um percurso divertido, rendendo boas fotos no carrinho.`,
      icone: "Ã°Å¸â€˜Â»",
      imagem: "scooby-doo-spooky-coaster.jpg",
      regiao: "Toon Lagoon",
      parque: "Islands of Adventure",
      latitude: 28.4708,
      longitude: -81.4727
    },
    {
      id: "bluto-billboard-bash",
      titulo: "Bluto's Billboard Bash",
      subtitulo: "Toon Lagoon",
      tipo: "AtraÃƒÂ§ÃƒÂ£o aquÃƒÂ¡tica interativa",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `ÃƒÂrea com mecanismos de ÃƒÂ¡gua e brincadeiras inspiradas em Bluto, sendo ÃƒÂ³timo para refrescar nos dias quentes.`,
      icone: "Ã°Å¸â€™Â¦",
      imagem: "bluto-billboard-bash.jpg",
      regiao: "Toon Lagoon",
      parque: "Islands of Adventure",
      latitude: 28.4709,
      longitude: -81.4728
    },
    {
      id: "popeye-bluto-bilge-rat-barges",
      titulo: "Popeye & Bluto's Bilge-Rat Barges",
      subtitulo: "Toon Lagoon",
      tipo: "AtraÃƒÂ§ÃƒÂ£o aquÃƒÂ¡tica de balsa",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio em balsa com quedas e jatos dÃ¢â‚¬â„¢ÃƒÂ¡gua, e quem sentar nas bordas provavelmente sairÃƒÂ¡ encharcado.`,
      icone: "Ã°Å¸Å¡Â¤",
      imagem: "popeye-bluto-bilge-rat-barges.jpg",
      regiao: "Toon Lagoon",
      parque: "Islands of Adventure",
      latitude: 28.4710,
      longitude: -81.4729
    },
    {
      id: "me-ship-the-olive",
      titulo: "Me Ship, The Olive",
      subtitulo: "Toon Lagoon",
      tipo: "ÃƒÂrea aquÃƒÂ¡tica interativa",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Navio temÃƒÂ¡tico de Popeye com jatos de ÃƒÂ¡gua e ÃƒÂ¡reas para brincadeiras, rendendo boas pausas para descanso.`,
      icone: "Ã°Å¸Å¡Â¢",
      imagem: "me-ship-the-olive.jpg",
      regiao: "Toon Lagoon",
      parque: "Islands of Adventure",
      latitude: 28.4711,
      longitude: -81.4730
    }
  ]
};
