export const ToonLagoon = {
  parque: "Islands of Adventure",
  descricao: "Área inspirada em desenhos clássicos, com atrações aquáticas e interativas para toda a família.",
  imagem: "toon-lagoon.png",
  latitude: 28.4705,
  longitude: -81.4723,
  atracoes: [
    {
      id: "rip-saw-falls",
      titulo: "Rip-Saw Falls",
      subtitulo: "Toon Lagoon",
      tipo: "Montanha-russa aquática",
      tipoPerfil: ["radicais", "tematicas", "interativas"],
      alturaMinima: 107,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 40,
      idadeRecomendada: "A partir de 10 anos",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Montanha-russa aquática com quedas rápidas e cenário divertido, garantindo respingos generosos principalmente na primeira fila.`,
      icone: "💦",
      imagem: "rip-saw-falls.jpg",
      regiao: "Toon Lagoon",
      parque: "Islands of Adventure",
      latitude: 28.4706,
      longitude: -81.4725
    },
    {
      id: "duff-beer",
      titulo: "Duff Beer Garden",
      subtitulo: "Toon Lagoon",
      tipo: "Restaurante temático",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Bar temático dos Simpsons com petiscos e cervejas, sendo imperdível experimentar a famosa Duff Beer bem gelada.`,
      icone: "🍺",
      imagem: "duff-beer.jpg",
      regiao: "Toon Lagoon",
      parque: "Islands of Adventure",
      latitude: 28.4707,
      longitude: -81.4726
    },
    {
      id: "scooby-doo-spooky-coaster",
      titulo: "Scooby-Doo's Spooky Coaster",
      subtitulo: "Toon Lagoon",
      tipo: "Montanha-russa infantil",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 91,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Montanha-russa suave com Scooby e a turma em um percurso divertido, rendendo boas fotos no carrinho.`,
      icone: "👻",
      imagem: "scooby-doo-spooky-coaster.jpg",
      regiao: "Toon Lagoon",
      parque: "Islands of Adventure",
      latitude: 28.4708,
      longitude: -81.4727
    },
    {
      id: "bluto-billboard-bash",
      titulo: "Bluto's Billboard Bash",
      subtitulo: "Toon Lagoon",
      tipo: "Atração aquática interativa",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Área com mecanismos de água e brincadeiras inspiradas em Bluto, sendo ótimo para refrescar nos dias quentes.`,
      icone: "💦",
      imagem: "bluto-billboard-bash.jpg",
      regiao: "Toon Lagoon",
      parque: "Islands of Adventure",
      latitude: 28.4709,
      longitude: -81.4728
    },
    {
      id: "popeye-bluto-bilge-rat-barges",
      titulo: "Popeye & Bluto's Bilge-Rat Barges",
      subtitulo: "Toon Lagoon",
      tipo: "Atração aquática de balsa",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio em balsa com quedas e jatos d’água, e quem sentar nas bordas provavelmente sairá encharcado.`,
      icone: "🚤",
      imagem: "popeye-bluto-bilge-rat-barges.jpg",
      regiao: "Toon Lagoon",
      parque: "Islands of Adventure",
      latitude: 28.4710,
      longitude: -81.4729
    },
    {
      id: "me-ship-the-olive",
      titulo: "Me Ship, The Olive",
      subtitulo: "Toon Lagoon",
      tipo: "Área aquática interativa",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Navio temático de Popeye com jatos de água e áreas para brincadeiras, rendendo boas pausas para descanso.`,
      icone: "🚢",
      imagem: "me-ship-the-olive.jpg",
      regiao: "Toon Lagoon",
      parque: "Islands of Adventure",
      latitude: 28.4711,
      longitude: -81.4730
    }
  ]
};
