ï»¿// src/logic/geradores/AreasUniversal/UniversalMonsters.ts
export const UniversalMonsters = {
  parque: "Universal's Epic Universe",
  regiao: "Universal Monsters",
  descricao: "ÃƒÂrea dedicada aos monstros clÃƒÂ¡ssicos, com uma dark ride de ÃƒÂºltima geraÃƒÂ§ÃƒÂ£o, uma coaster familiar e uma experiÃƒÂªncia interativa de maquiagem em Darkmoor.",
  imagem: "universal-monsters.png",
  latitude: 28.4709,
  longitude: -81.4735,
  atracoes: [
    {
      id: "monsters-unchained",
      titulo: "Monsters Unchained: The Frankenstein Experiment",
      subtitulo: "Universal Monsters",
      tipo: "Dark ride imersiva",
      tipoPerfil: ["radicais", "tematicas", "imersivas"],
      alturaMinima: 107,
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      atracaoSemFila: false,
      turnoRecomendado: "noite",
      descricao: "ExperiÃƒÂªncia intensa no laboratÃƒÂ³rio do Dr. Frankenstein com encontros prÃƒÂ³ximos aos monstros clÃƒÂ¡ssicos. Fileiras do meio oferecem melhor visÃƒÂ£o geral.",
      icone: "Ã°Å¸Â§Âª",
      imagem: "monsters-unchained.jpg",
      regiao: "Universal Monsters",
      parque: "Universal's Epic Universe",
      latitude: 28.4710,
      longitude: -81.4736
    },
    {
      id: "curse-of-the-werewolf",
      titulo: "Curse of the Werewolf",
      subtitulo: "Universal Monsters",
      tipo: "Montanha-russa familiar",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 30,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Coaster familiar com curvas rÃƒÂ¡pidas pelo vilarejo de Darkmoor. Ãƒâ‚¬ noite a ambientaÃƒÂ§ÃƒÂ£o fica mais imersiva.",
      icone: "Ã°Å¸ÂÂº",
      imagem: "curse-of-the-werewolf.jpg",
      regiao: "Universal Monsters",
      parque: "Universal's Epic Universe",
      latitude: 28.4712,
      longitude: -81.4737
    },
    {
      id: "darkmoor-monster-makeup",
      titulo: "Darkmoor Monster Makeup Experience",
      subtitulo: "Universal Monsters",
      tipo: "ExperiÃƒÂªncia interativa",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "DemonstraÃƒÂ§ÃƒÂ£o ao vivo de maquiagem de monstros com participaÃƒÂ§ÃƒÂ£o do pÃƒÂºblico e bastidores de efeitos prÃƒÂ¡ticos.",
      icone: "Ã°Å¸Å½Â­",
      imagem: "darkmoor-monster-makeup.jpg",
      regiao: "Universal Monsters",
      parque: "Universal's Epic Universe",
      latitude: 28.4714,
      longitude: -81.4739
    }
  ]
};
