// src/logic/geradores/AreasUniversal/UniversalMonsters.ts
export const UniversalMonsters = {
  parque: "Universal's Epic Universe",
  regiao: "Universal Monsters",
  descricao: "Ãrea dedicada aos monstros clÃ¡ssicos, com uma dark ride de Ãºltima geraÃ§Ã£o, uma coaster familiar e uma experiÃªncia interativa de maquiagem em Darkmoor.",
  imagem: "universal-monsters.png",
  latitude: 28.4709,
  longitude: -81.4735,
  atracoes: [
    {
      id: "monsters-unchained",
      titulo: "Monsters Unchained: The Frankenstein Experiment",
      subtitulo: "Universal Monsters",
      tipo: "Dark ride imersiva",
      tipoPerfil: ["radicais", "tematicas", "imersivas"],
      alturaMinima: 107,
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      atracaoSemFila: false,
      turnoRecomendado: "noite",
      descricao: "ExperiÃªncia intensa no laboratÃ³rio do Dr. Frankenstein com encontros prÃ³ximos aos monstros clÃ¡ssicos. Fileiras do meio oferecem melhor visÃ£o geral.",
      icone: "ðŸ§ª",
      imagem: "monsters-unchained.jpg",
      regiao: "Universal Monsters",
      parque: "Universal's Epic Universe",
      latitude: 28.4710,
      longitude: -81.4736
    },
    {
      id: "curse-of-the-werewolf",
      titulo: "Curse of the Werewolf",
      subtitulo: "Universal Monsters",
      tipo: "Montanha-russa familiar",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 30,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Coaster familiar com curvas rÃ¡pidas pelo vilarejo de Darkmoor. Ã€ noite a ambientaÃ§Ã£o fica mais imersiva.",
      icone: "ðŸº",
      imagem: "curse-of-the-werewolf.jpg",
      regiao: "Universal Monsters",
      parque: "Universal's Epic Universe",
      latitude: 28.4712,
      longitude: -81.4737
    },
    {
      id: "darkmoor-monster-makeup",
      titulo: "Darkmoor Monster Makeup Experience",
      subtitulo: "Universal Monsters",
      tipo: "ExperiÃªncia interativa",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "DemonstraÃ§Ã£o ao vivo de maquiagem de monstros com participaÃ§Ã£o do pÃºblico e bastidores de efeitos prÃ¡ticos.",
      icone: "ðŸŽ­",
      imagem: "darkmoor-monster-makeup.jpg",
      regiao: "Universal Monsters",
      parque: "Universal's Epic Universe",
      latitude: 28.4714,
      longitude: -81.4739
    }
  ]
};
