// src/logic/geradores/AreasUniversal/UniversalMonsters.ts
export const UniversalMonsters = {
  parque: "Universal's Epic Universe",
  regiao: "Universal Monsters",
  descricao: "Área dedicada aos monstros clássicos, com uma dark ride de última geração, uma coaster familiar e uma experiência interativa de maquiagem em Darkmoor.",
  imagem: "universal-monsters.png",
  latitude: 28.4709,
  longitude: -81.4735,
  atracoes: [
    {
      id: "monsters-unchained",
      titulo: "Monsters Unchained: The Frankenstein Experiment",
      subtitulo: "Universal Monsters",
      tipo: "Dark ride imersiva",
      tipoPerfil: ["radicais", "tematicas", "imersivas"],
      alturaMinima: 107,
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      atracaoSemFila: false,
      turnoRecomendado: "noite",
      descricao: "Experiência intensa no laboratório do Dr. Frankenstein com encontros próximos aos monstros clássicos. Fileiras do meio oferecem melhor visão geral.",
      icone: "🧪",
      imagem: "monsters-unchained.jpg",
      regiao: "Universal Monsters",
      parque: "Universal's Epic Universe",
      latitude: 28.4710,
      longitude: -81.4736
    },
    {
      id: "curse-of-the-werewolf",
      titulo: "Curse of the Werewolf",
      subtitulo: "Universal Monsters",
      tipo: "Montanha-russa familiar",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 30,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Coaster familiar com curvas rápidas pelo vilarejo de Darkmoor. À noite a ambientação fica mais imersiva.",
      icone: "🐺",
      imagem: "curse-of-the-werewolf.jpg",
      regiao: "Universal Monsters",
      parque: "Universal's Epic Universe",
      latitude: 28.4712,
      longitude: -81.4737
    },
    {
      id: "darkmoor-monster-makeup",
      titulo: "Darkmoor Monster Makeup Experience",
      subtitulo: "Universal Monsters",
      tipo: "Experiência interativa",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Demonstração ao vivo de maquiagem de monstros com participação do público e bastidores de efeitos práticos.",
      icone: "🎭",
      imagem: "darkmoor-monster-makeup.jpg",
      regiao: "Universal Monsters",
      parque: "Universal's Epic Universe",
      latitude: 28.4714,
      longitude: -81.4739
    }
  ]
};
