ï»¿export const WorldExpo = {
  parque: "Universal Studios Florida",
  descricao: "World Expo e a vizinha Springfield, com simulador dos Simpsons, tiro interativo dos MIB e o clÃƒÂ¡ssico giro dos aliens.",
  imagem: "world-expo-springfield.png",
  latitude: 28.4738,
  longitude: -81.4682,
  atracoes: [
    {
      id: "men-in-black-alien-attack",
      titulo: "MEN IN BLACK: Alien Attack",
      subtitulo: "World Expo",
      tipo: "Tiro interativo",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 107,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 30,
      idadeRecomendada: "A partir de 8 anos",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Dispare nos aliens enquanto o carrinho gira; mire nos alvos que aparecem e somem rÃƒÂ¡pido para pontuar mais.",
      icone: "Ã°Å¸â€˜Â½",
      imagem: "men-in-black-alien-attack.jpg",
      regiao: "World Expo",
      parque: "Universal Studios Florida",
      latitude: 28.4739,
      longitude: -81.4684
    },
    {
      id: "the-simpsons-ride",
      titulo: "The Simpsons Ride",
      subtitulo: "Springfield",
      tipo: "Simulador 3D",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "A partir de 7 anos",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Simulador caÃƒÂ³tico em Krustyland; fileiras centrais dÃƒÂ£o melhor visÃƒÂ£o da tela gigante.",
      icone: "Ã°Å¸Å½Â¢",
      imagem: "the-simpsons-ride.jpg",
      regiao: "World Expo",
      parque: "Universal Studios Florida",
      latitude: 28.4742,
      longitude: -81.4680
    },
    {
      id: "kang-kodos-twirl-n-hurl",
      titulo: "Kang & KodosÃ¢â‚¬â„¢ Twirl Ã¢â‚¬ËœnÃ¢â‚¬â„¢ Hurl",
      subtitulo: "Springfield",
      tipo: "Brinquedo giratÃƒÂ³rio",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Gire sua nave alienÃƒÂ­gena com vistas de Springfield; assentos externos passam mais perto dos alvos.",
      icone: "Ã°Å¸â€ºÂ¸",
      imagem: "kang-and-kodos-twirl-n-hurl.jpg",
      regiao: "World Expo",
      parque: "Universal Studios Florida",
      latitude: 28.4740,
      longitude: -81.4678
    }
  ]
};
