export const WorldExpo = {
  parque: "Universal Studios Florida",
  descricao: "Ãrea que reÃºne o setor futurista World Expo e a vizinha Springfield, com simuladores, tiro interativo e um clÃ¡ssico brinquedo giratÃ³rio dos aliens de The Simpsons.",
  imagem: "world-expo-springfield.png",
  latitude: 28.4738,
  longitude: -81.4682,
  atracoes: [
    {
      id: "men-in-black-alien-attack",
      titulo: "MEN IN BLACK: Alien Attack",
      subtitulo: "World Expo",
      tipo: "Tiro interativo",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 107,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 30,
      idadeRecomendada: "A partir de 8 anos",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Dispare nos aliens enquanto o carrinho gira e compare a pontuaÃ§Ã£o no final. Dica: mire nas cabeÃ§as que surgem e somem rÃ¡pido.",
      icone: "ðŸ‘½",
      imagem: "men-in-black-alien-attack.jpg",
      regiao: "World Expo",
      parque: "Universal Studios Florida",
      latitude: 28.4739,
      longitude: -81.4684
    },
    {
      id: "the-simpsons-ride",
      titulo: "The Simpsons Ride",
      subtitulo: "Springfield",
      tipo: "Simulador 3D",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "A partir de 7 anos",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Simulador caÃ³tico com a famÃ­lia Simpsons em Krustyland. Melhores vistas nas fileiras centrais da plataforma.",
      icone: "ðŸŽ¢",
      imagem: "the-simpsons-ride.jpg",
      regiao: "World Expo",
      parque: "Universal Studios Florida",
      latitude: 28.4742,
      longitude: -81.4680
    },
    {
      id: "kang-kodos-twirl-n-hurl",
      titulo: "Kang & Kodosâ€™ Twirl â€˜nâ€™ Hurl",
      subtitulo: "Springfield",
      tipo: "Brinquedo giratÃ³rio",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Gire sua nave alienÃ­gena com vistas da Ã¡rea de Springfield. Assentos externos passam mais perto dos alvos.",
      icone: "ðŸ›¸",
      imagem: "kang-and-kodos-twirl-n-hurl.jpg",
      regiao: "World Expo",
      parque: "Universal Studios Florida",
      latitude: 28.4740,
      longitude: -81.4678
    }
  ]
};
