export const Adventureland = {
  parque: "Magic Kingdom",
  descricao: "Ãrea com temÃ¡tica de selvas tropicais, aventuras exÃ³ticas e culturas distantes. Aqui vocÃª encontra atraÃ§Ãµes icÃ´nicas como Pirates of the Caribbean e experiÃªncias tranquilas como o Tiki Room, com temÃ¡tica tropical e ambientaÃ§Ã£o imersiva.",
  imagem: "adventureland.png",
  latitude: 28.4187,
  longitude: -81.5830,
  atracoes: [
    {
      id: "jungle-cruise",
      titulo: "Jungle Cruise",
      subtitulo: "Adventureland",
      tipo: "Passeio de barco cÃ´mico",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Passeio de barco guiado com piadas enquanto explora rios fictÃ­cios de selvas tropicais. Uma atraÃ§Ã£o clÃ¡ssica com clima de aventura.",
      icone: "ðŸ›¶",
      imagem: "jungle-cruise.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4183,
      longitude: -81.5825
    },
    {
      id: "pirates-of-the-caribbean",
      titulo: "Pirates of the Caribbean",
      subtitulo: "Adventureland",
      tipo: "Dark ride",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Aventura clÃ¡ssica em barco passando por cenÃ¡rios com piratas animatrÃ´nicos em batalhas e saques. Atmosfera sombria e envolvente.",
      icone: "ðŸ´â€â˜ ï¸",
      imagem: "pirates-of-the-caribbean.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4175,
      longitude: -81.5842
    },
    {
      id: "magic-carpets-of-aladdin",
      titulo: "The Magic Carpets of Aladdin",
      subtitulo: "Adventureland",
      tipo: "Brinquedo giratÃ³rio",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Voe em um tapete mÃ¡gico giratÃ³rio com vista da Adventureland. A experiÃªncia Ã© suave e divertida para crianÃ§as pequenas.",
      icone: "ðŸ•Œ",
      imagem: "magic-carpets-of-aladdin.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4180,
      longitude: -81.5831
    },
    {
      id: "enchanted-tiki-room",
      titulo: "Walt Disneyâ€™s Enchanted Tiki Room",
      subtitulo: "Adventureland",
      tipo: "Show animatrÃ´nico",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "EspetÃ¡culo musical com aves animatrÃ´nicas tropicais, apresentado a cada 30 minutos. Ideal para um momento de descanso e imersÃ£o.",
      icone: "ðŸ¦",
      imagem: "enchanted-tiki-room.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4188,
      longitude: -81.5836
    },
    {
      id: "swiss-family-treehouse",
      titulo: "Swiss Family Treehouse",
      subtitulo: "Adventureland",
      tipo: "ExploraÃ§Ã£o interativa",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Caminhada livre por uma grande casa na Ã¡rvore com vista e ambientaÃ§Ãµes detalhadas. Sem fila, vocÃª entra quando quiser.",
      icone: "ðŸŒ´",
      imagem: "swiss-family-treehouse.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4191,
      longitude: -81.5829
    }
  ]
};
