export const Adventureland = {
  parque: "Magic Kingdom",
  descricao: "Área com temática de selvas tropicais, aventuras exóticas e culturas distantes. Aqui você encontra atrações icônicas como Pirates of the Caribbean e experiências tranquilas como o Tiki Room, com temática tropical e ambientação imersiva.",
  imagem: "adventureland.png",
  latitude: 28.4187,
  longitude: -81.5830,
  atracoes: [
    {
      id: "jungle-cruise",
      titulo: "Jungle Cruise",
      subtitulo: "Adventureland",
      tipo: "Passeio de barco cômico",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Passeio de barco guiado com piadas enquanto explora rios fictícios de selvas tropicais. Uma atração clássica com clima de aventura.",
      icone: "🛶",
      imagem: "jungle-cruise.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4183,
      longitude: -81.5825
    },
    {
      id: "pirates-of-the-caribbean",
      titulo: "Pirates of the Caribbean",
      subtitulo: "Adventureland",
      tipo: "Dark ride",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Aventura clássica em barco passando por cenários com piratas animatrônicos em batalhas e saques. Atmosfera sombria e envolvente.",
      icone: "🏴‍☠️",
      imagem: "pirates-of-the-caribbean.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4175,
      longitude: -81.5842
    },
    {
      id: "magic-carpets-of-aladdin",
      titulo: "The Magic Carpets of Aladdin",
      subtitulo: "Adventureland",
      tipo: "Brinquedo giratório",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Voe em um tapete mágico giratório com vista da Adventureland. A experiência é suave e divertida para crianças pequenas.",
      icone: "🕌",
      imagem: "magic-carpets-of-aladdin.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4180,
      longitude: -81.5831
    },
    {
      id: "enchanted-tiki-room",
      titulo: "Walt Disney’s Enchanted Tiki Room",
      subtitulo: "Adventureland",
      tipo: "Show animatrônico",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "Espetáculo musical com aves animatrônicas tropicais, apresentado a cada 30 minutos. Ideal para um momento de descanso e imersão.",
      icone: "🐦",
      imagem: "enchanted-tiki-room.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4188,
      longitude: -81.5836
    },
    {
      id: "swiss-family-treehouse",
      titulo: "Swiss Family Treehouse",
      subtitulo: "Adventureland",
      tipo: "Exploração interativa",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Caminhada livre por uma grande casa na árvore com vista e ambientações detalhadas. Sem fila, você entra quando quiser.",
      icone: "🌴",
      imagem: "swiss-family-treehouse.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4191,
      longitude: -81.5829
    }
  ]
};
