ï»¿export const Adventureland = {
  parque: "Magic Kingdom",
  descricao: "ÃƒÂrea com temÃƒÂ¡tica de selvas tropicais, aventuras exÃƒÂ³ticas e culturas distantes. Aqui vocÃƒÂª encontra atraÃƒÂ§ÃƒÂµes icÃƒÂ´nicas como Pirates of the Caribbean e experiÃƒÂªncias tranquilas como o Tiki Room, com temÃƒÂ¡tica tropical e ambientaÃƒÂ§ÃƒÂ£o imersiva.",
  imagem: "adventureland.png",
  latitude: 28.4187,
  longitude: -81.5830,
  atracoes: [
    {
      id: "jungle-cruise",
      titulo: "Jungle Cruise",
      subtitulo: "Adventureland",
      tipo: "Passeio de barco cÃƒÂ´mico",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Passeio de barco guiado com piadas enquanto explora rios fictÃƒÂ­cios de selvas tropicais. Uma atraÃƒÂ§ÃƒÂ£o clÃƒÂ¡ssica com clima de aventura.",
      icone: "Ã°Å¸â€ºÂ¶",
      imagem: "jungle-cruise.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4183,
      longitude: -81.5825
    },
    {
      id: "pirates-of-the-caribbean",
      titulo: "Pirates of the Caribbean",
      subtitulo: "Adventureland",
      tipo: "Dark ride",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Aventura clÃƒÂ¡ssica em barco passando por cenÃƒÂ¡rios com piratas animatrÃƒÂ´nicos em batalhas e saques. Atmosfera sombria e envolvente.",
      icone: "Ã°Å¸ÂÂ´Ã¢â‚¬ÂÃ¢ËœÂ Ã¯Â¸Â",
      imagem: "pirates-of-the-caribbean.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4175,
      longitude: -81.5842
    },
    {
      id: "magic-carpets-of-aladdin",
      titulo: "The Magic Carpets of Aladdin",
      subtitulo: "Adventureland",
      tipo: "Brinquedo giratÃƒÂ³rio",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Voe em um tapete mÃƒÂ¡gico giratÃƒÂ³rio com vista da Adventureland. A experiÃƒÂªncia ÃƒÂ© suave e divertida para crianÃƒÂ§as pequenas.",
      icone: "Ã°Å¸â€¢Å’",
      imagem: "magic-carpets-of-aladdin.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4180,
      longitude: -81.5831
    },
    {
      id: "enchanted-tiki-room",
      titulo: "Walt DisneyÃ¢â‚¬â„¢s Enchanted Tiki Room",
      subtitulo: "Adventureland",
      tipo: "Show animatrÃƒÂ´nico",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "EspetÃƒÂ¡culo musical com aves animatrÃƒÂ´nicas tropicais, apresentado a cada 30 minutos. Ideal para um momento de descanso e imersÃƒÂ£o.",
      icone: "Ã°Å¸ÂÂ¦",
      imagem: "enchanted-tiki-room.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4188,
      longitude: -81.5836
    },
    {
      id: "swiss-family-treehouse",
      titulo: "Swiss Family Treehouse",
      subtitulo: "Adventureland",
      tipo: "ExploraÃƒÂ§ÃƒÂ£o interativa",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Caminhada livre por uma grande casa na ÃƒÂ¡rvore com vista e ambientaÃƒÂ§ÃƒÂµes detalhadas. Sem fila, vocÃƒÂª entra quando quiser.",
      icone: "Ã°Å¸Å’Â´",
      imagem: "swiss-family-treehouse.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4191,
      longitude: -81.5829
    }
  ]
};
