export const Africa = {
  parque: "Animal Kingdom",
  descricao: "Inspirada na vila fictícia de Harambe, esta área oferece uma experiência cultural rica com shows, trilhas e um safári realista com animais selvagens em ambientes naturais.",
  imagem: "africa.png",
  latitude: 28.3585,
  longitude: -81.5970,
  atracoes: [
    {
      id: "kilimanjaro-safaris",
      titulo: "Kilimanjaro Safaris",
      subtitulo: "Africa",
      tipo: "Safári ao ar livre",
      tipoPerfil: ["familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Embarque em um safári em veículos abertos por uma savana africana repleta de animais como girafas, leões e elefantes.",
      icone: "🦒",
      imagem: "kilimanjaro-safaris.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3588,
      longitude: -81.5965
    },
    {
      id: "festival-of-the-lion-king",
      titulo: "Festival of the Lion King",
      subtitulo: "Africa",
      tipo: "Show musical ao vivo",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Espetáculo com músicas, acrobacias e personagens do Rei Leão. Apresentado em horários fixos ao longo do dia.",
      icone: "🦁",
      imagem: "festival-of-the-lion-king.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3580,
      longitude: -81.5971
    },
    {
      id: "gorilla-falls-exploration-trail",
      titulo: "Gorilla Falls Exploration Trail",
      subtitulo: "Africa",
      tipo: "Trilha de observação",
      tipoPerfil: ["familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Trilha a pé para observação de gorilas, hipopótamos e pássaros africanos. Explore no seu ritmo, sem fila.",
      icone: "🦍",
      imagem: "gorilla-falls.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3591,
      longitude: -81.5959
    },
    {
      id: "harambe-market",
      titulo: "Harambe Market",
      subtitulo: "Africa",
      tipo: "Espaço temático e gastronômico",
      tipoPerfil: ["tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Mercado a céu aberto com decoração autêntica africana, quiosques de comida típica e áreas para descanso e fotos. Ideal para explorar entre atrações.",
      icone: "🛍️",
      imagem: "harambe-market.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3576,
      longitude: -81.5962
    },
    {
      id: "tam-tam-drummers",
      titulo: "Tam Tam Drummers of Harambe",
      subtitulo: "Africa",
      tipo: "Show de música africana",
      tipoPerfil: ["tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Apresentação cultural vibrante com tambores africanos, dança e interação com o público. Um show espontâneo que acontece em horários alternados na vila de Harambe.",
      icone: "🥁",
      imagem: "tam-tam-drummers.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3579,
      longitude: -81.5978
    }
  ]
};
