export const Africa = {
  parque: "Animal Kingdom",
  descricao: "Inspirada na vila fictÃ­cia de Harambe, esta Ã¡rea oferece uma experiÃªncia cultural rica com shows, trilhas e um safÃ¡ri realista com animais selvagens em ambientes naturais.",
  imagem: "africa.png",
  latitude: 28.3585,
  longitude: -81.5970,
  atracoes: [
    {
      id: "kilimanjaro-safaris",
      titulo: "Kilimanjaro Safaris",
      subtitulo: "Africa",
      tipo: "SafÃ¡ri ao ar livre",
      tipoPerfil: ["familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Embarque em um safÃ¡ri em veÃ­culos abertos por uma savana africana repleta de animais como girafas, leÃµes e elefantes.",
      icone: "ðŸ¦’",
      imagem: "kilimanjaro-safaris.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3588,
      longitude: -81.5965
    },
    {
      id: "festival-of-the-lion-king",
      titulo: "Festival of the Lion King",
      subtitulo: "Africa",
      tipo: "Show musical ao vivo",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "EspetÃ¡culo com mÃºsicas, acrobacias e personagens do Rei LeÃ£o. Apresentado em horÃ¡rios fixos ao longo do dia.",
      icone: "ðŸ¦",
      imagem: "festival-of-the-lion-king.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3580,
      longitude: -81.5971
    },
    {
      id: "gorilla-falls-exploration-trail",
      titulo: "Gorilla Falls Exploration Trail",
      subtitulo: "Africa",
      tipo: "Trilha de observaÃ§Ã£o",
      tipoPerfil: ["familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Trilha a pÃ© para observaÃ§Ã£o de gorilas, hipopÃ³tamos e pÃ¡ssaros africanos. Explore no seu ritmo, sem fila.",
      icone: "ðŸ¦",
      imagem: "gorilla-falls.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3591,
      longitude: -81.5959
    },
    {
      id: "harambe-market",
      titulo: "Harambe Market",
      subtitulo: "Africa",
      tipo: "EspaÃ§o temÃ¡tico e gastronÃ´mico",
      tipoPerfil: ["tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Mercado a cÃ©u aberto com decoraÃ§Ã£o autÃªntica africana, quiosques de comida tÃ­pica e Ã¡reas para descanso e fotos. Ideal para explorar entre atraÃ§Ãµes.",
      icone: "ðŸ›ï¸",
      imagem: "harambe-market.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3576,
      longitude: -81.5962
    },
    {
      id: "tam-tam-drummers",
      titulo: "Tam Tam Drummers of Harambe",
      subtitulo: "Africa",
      tipo: "Show de mÃºsica africana",
      tipoPerfil: ["tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "ApresentaÃ§Ã£o cultural vibrante com tambores africanos, danÃ§a e interaÃ§Ã£o com o pÃºblico. Um show espontÃ¢neo que acontece em horÃ¡rios alternados na vila de Harambe.",
      icone: "ðŸ¥",
      imagem: "tam-tam-drummers.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3579,
      longitude: -81.5978
    }
  ]
};
