ï»¿export const Africa = {
  parque: "Animal Kingdom",
  descricao: "Inspirada na vila fictÃƒÂ­cia de Harambe, esta ÃƒÂ¡rea oferece uma experiÃƒÂªncia cultural rica com shows, trilhas e um safÃƒÂ¡ri realista com animais selvagens em ambientes naturais.",
  imagem: "africa.png",
  latitude: 28.3585,
  longitude: -81.5970,
  atracoes: [
    {
      id: "kilimanjaro-safaris",
      titulo: "Kilimanjaro Safaris",
      subtitulo: "Africa",
      tipo: "SafÃƒÂ¡ri ao ar livre",
      tipoPerfil: ["familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Embarque em um safÃƒÂ¡ri em veÃƒÂ­culos abertos por uma savana africana repleta de animais como girafas, leÃƒÂµes e elefantes.",
      icone: "Ã°Å¸Â¦â€™",
      imagem: "kilimanjaro-safaris.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3588,
      longitude: -81.5965
    },
    {
      id: "festival-of-the-lion-king",
      titulo: "Festival of the Lion King",
      subtitulo: "Africa",
      tipo: "Show musical ao vivo",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "EspetÃƒÂ¡culo com mÃƒÂºsicas, acrobacias e personagens do Rei LeÃƒÂ£o. Apresentado em horÃƒÂ¡rios fixos ao longo do dia.",
      icone: "Ã°Å¸Â¦Â",
      imagem: "festival-of-the-lion-king.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3580,
      longitude: -81.5971
    },
    {
      id: "gorilla-falls-exploration-trail",
      titulo: "Gorilla Falls Exploration Trail",
      subtitulo: "Africa",
      tipo: "Trilha de observaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Trilha a pÃƒÂ© para observaÃƒÂ§ÃƒÂ£o de gorilas, hipopÃƒÂ³tamos e pÃƒÂ¡ssaros africanos. Explore no seu ritmo, sem fila.",
      icone: "Ã°Å¸Â¦Â",
      imagem: "gorilla-falls.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3591,
      longitude: -81.5959
    },
    {
      id: "harambe-market",
      titulo: "Harambe Market",
      subtitulo: "Africa",
      tipo: "EspaÃƒÂ§o temÃƒÂ¡tico e gastronÃƒÂ´mico",
      tipoPerfil: ["tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Mercado a cÃƒÂ©u aberto com decoraÃƒÂ§ÃƒÂ£o autÃƒÂªntica africana, quiosques de comida tÃƒÂ­pica e ÃƒÂ¡reas para descanso e fotos. Ideal para explorar entre atraÃƒÂ§ÃƒÂµes.",
      icone: "Ã°Å¸â€ºÂÃ¯Â¸Â",
      imagem: "harambe-market.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3576,
      longitude: -81.5962
    },
    {
      id: "tam-tam-drummers",
      titulo: "Tam Tam Drummers of Harambe",
      subtitulo: "Africa",
      tipo: "Show de mÃƒÂºsica africana",
      tipoPerfil: ["tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "ApresentaÃƒÂ§ÃƒÂ£o cultural vibrante com tambores africanos, danÃƒÂ§a e interaÃƒÂ§ÃƒÂ£o com o pÃƒÂºblico. Um show espontÃƒÂ¢neo que acontece em horÃƒÂ¡rios alternados na vila de Harambe.",
      icone: "Ã°Å¸Â¥Â",
      imagem: "tam-tam-drummers.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3579,
      longitude: -81.5978
    }
  ]
};
