export const AnimationCourtyard = {
  parque: "Hollywood Studios",
  descricao:
    "Área voltada para os clássicos da animação da Disney, com atrações para famílias e crianças pequenas, incluindo experiências interativas e encontros com personagens.",
  imagem: "animationcourtyard.png",
  latitude: 28.3563,
  longitude: -81.5606,
  atracoes: [
    {
      id: "disney-junior-dance",
      titulo: "Disney Junior Dance Party!",
      subtitulo: "Animation Courtyard",
      tipo: "Show musical interativo",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Pré-escolares e crianças pequenas",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao:
        "Festa de dança animada com personagens como Mickey, Vampirina e Timon. Um momento para os pequenos se divertirem e gastarem energia.",
      icone: "🕺",
      imagem: "disney-junior.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3567,
      longitude: -81.5611
    },
    {
      id: "voyage-little-mermaid",
      titulo: "Voyage of The Little Mermaid",
      subtitulo: "Animation Courtyard",
      tipo: "Show ao vivo com efeitos",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao:
        "Espetáculo musical com fantoches, projeções e músicas do clássico A Pequena Sereia. Encantador e nostálgico.",
      icone: "🧜‍♀️",
      imagem: "little-mermaid.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3561,
      longitude: -81.5605
    },
    {
      id: "walt-disney-presents",
      titulo: "Walt Disney Presents",
      subtitulo: "Animation Courtyard",
      tipo: "Exposição interativa e filme",
      tipoPerfil: ["imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao:
        "Museu com a história de Walt Disney, maquetes dos parques e um curta sobre sua vida. Um passeio inspirador e tranquilo.",
      icone: "🎞️",
      imagem: "walt-disney-presents.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3564,
      longitude: -81.5602
    },
    {
      id: "star-wars-launch-bay",
      titulo: "Star Wars Launch Bay",
      subtitulo: "Animation Courtyard",
      tipo: "Exposição e encontros com personagens",
      tipoPerfil: ["interativas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "noite",
      descricao:
        "Veja réplicas e figurinos de Star Wars e tire fotos com Chewbacca, Darth Vader ou BB-8. Ideal para fãs da saga.",
      icone: "🚀",
      imagem: "star-wars-launch-bay.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3560,
      longitude: -81.5608
    },
    {
      id: "animation-photo-spot",
      titulo: "Animation Courtyard Photo Spot",
      subtitulo: "Animation Courtyard",
      tipo: "Ponto de fotos com personagens",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao:
        "Encontre personagens da Disney como Pluto, Fancy Nancy e Doc McStuffins em cenários temáticos perfeitos para fotos memoráveis.",
      icone: "📸",
      imagem: "animation-photo.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3565,
      longitude: -81.5609
    }
  ]
};
