ï»¿export const AnimationCourtyard = {
  parque: "Hollywood Studios",
  descricao:
    "ÃƒÂrea voltada para os clÃƒÂ¡ssicos da animaÃƒÂ§ÃƒÂ£o da Disney, com atraÃƒÂ§ÃƒÂµes para famÃƒÂ­lias e crianÃƒÂ§as pequenas, incluindo experiÃƒÂªncias interativas e encontros com personagens.",
  imagem: "animationcourtyard.png",
  latitude: 28.3563,
  longitude: -81.5606,
  atracoes: [
    {
      id: "disney-junior-dance",
      titulo: "Disney Junior Dance Party!",
      subtitulo: "Animation Courtyard",
      tipo: "Show musical interativo",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "PrÃƒÂ©-escolares e crianÃƒÂ§as pequenas",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao:
        "Festa de danÃƒÂ§a animada com personagens como Mickey, Vampirina e Timon. Um momento para os pequenos se divertirem e gastarem energia.",
      icone: "Ã°Å¸â€¢Âº",
      imagem: "disney-junior.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3567,
      longitude: -81.5611
    },
    {
      id: "voyage-little-mermaid",
      titulo: "Voyage of The Little Mermaid",
      subtitulo: "Animation Courtyard",
      tipo: "Show ao vivo com efeitos",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao:
        "EspetÃƒÂ¡culo musical com fantoches, projeÃƒÂ§ÃƒÂµes e mÃƒÂºsicas do clÃƒÂ¡ssico A Pequena Sereia. Encantador e nostÃƒÂ¡lgico.",
      icone: "Ã°Å¸Â§Å“Ã¢â‚¬ÂÃ¢â„¢â‚¬Ã¯Â¸Â",
      imagem: "little-mermaid.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3561,
      longitude: -81.5605
    },
    {
      id: "walt-disney-presents",
      titulo: "Walt Disney Presents",
      subtitulo: "Animation Courtyard",
      tipo: "ExposiÃƒÂ§ÃƒÂ£o interativa e filme",
      tipoPerfil: ["imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao:
        "Museu com a histÃƒÂ³ria de Walt Disney, maquetes dos parques e um curta sobre sua vida. Um passeio inspirador e tranquilo.",
      icone: "Ã°Å¸Å½Å¾Ã¯Â¸Â",
      imagem: "walt-disney-presents.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3564,
      longitude: -81.5602
    },
    {
      id: "star-wars-launch-bay",
      titulo: "Star Wars Launch Bay",
      subtitulo: "Animation Courtyard",
      tipo: "ExposiÃƒÂ§ÃƒÂ£o e encontros com personagens",
      tipoPerfil: ["interativas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "noite",
      descricao:
        "Veja rÃƒÂ©plicas e figurinos de Star Wars e tire fotos com Chewbacca, Darth Vader ou BB-8. Ideal para fÃƒÂ£s da saga.",
      icone: "Ã°Å¸Å¡â‚¬",
      imagem: "star-wars-launch-bay.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3560,
      longitude: -81.5608
    },
    {
      id: "animation-photo-spot",
      titulo: "Animation Courtyard Photo Spot",
      subtitulo: "Animation Courtyard",
      tipo: "Ponto de fotos com personagens",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao:
        "Encontre personagens da Disney como Pluto, Fancy Nancy e Doc McStuffins em cenÃƒÂ¡rios temÃƒÂ¡ticos perfeitos para fotos memorÃƒÂ¡veis.",
      icone: "Ã°Å¸â€œÂ¸",
      imagem: "animation-photo.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3565,
      longitude: -81.5609
    }
  ]
};
