export const Asia = {
  parque: "Animal Kingdom",
  descricao: "Inspirada nas paisagens do Himalaia e da selva asiÃ¡tica, essa Ã¡rea combina montanhas-russas radicais, aventuras aquÃ¡ticas e trilhas para explorar a vida selvagem.",
  imagem: "asia.png",
  latitude: 28.3588,
  longitude: -81.5915,
  atracoes: [
    {
      id: "expedition-everest",
      titulo: "Expedition Everest â€“ Legend of the Forbidden Mountain",
      subtitulo: "Asia",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "imersivas"],
      alturaMinima: 112,
      filaExpress: true,
      tempoMedioFila: 55,
      filaAceitavel: 40,
      idadeRecomendada: "8+",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Uma montanha-russa intensa que te leva ao encontro do Yeti, com trechos de rÃ©, subidas rÃ¡pidas e curvas fechadas em meio ao Himalaia.",
      icone: "ðŸ”ï¸",
      imagem: "expedition-everest.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3582,
      longitude: -81.5916
    },
    {
      id: "kali-river-rapids",
      titulo: "Kali River Rapids",
      subtitulo: "Asia",
      tipo: "Aventura aquÃ¡tica",
      tipoPerfil: ["familiares", "radicais"],
      alturaMinima: 96,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 35,
      idadeRecomendada: "6+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "DesÃ§a corredeiras em uma boia gigante, passando por florestas tropicais e Ã¡reas desmatadas. Prepare-se para se molhar completamente!",
      icone: "ðŸŒŠ",
      imagem: "kali-river-rapids.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3590,
      longitude: -81.5914
    },
    {
      id: "maharajah-jungle-trek",
      titulo: "Maharajah Jungle Trek",
      subtitulo: "Asia",
      tipo: "Trilha de observaÃ§Ã£o",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Caminhada livre por ruÃ­nas antigas e jardins asiÃ¡ticos, onde vocÃª pode observar tigres, morcegos gigantes e antÃ­lopes. A experiÃªncia Ã© exploratÃ³ria, sem fila e no seu ritmo.",
      icone: "ðŸ…",
      imagem: "maharajah-jungle-trek.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3586,
      longitude: -81.5909
    },
    {
      id: "feathered-friends-in-flight",
      titulo: "Feathered Friends in Flight!",
      subtitulo: "Asia",
      tipo: "ApresentaÃ§Ã£o com aves",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Show ao vivo com aves treinadas, apresentado por especialistas que explicam hÃ¡bitos e curiosidades das espÃ©cies. Interativo e educativo.",
      icone: "ðŸ¦œ",
      imagem: "feathered-friends.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3591,
      longitude: -81.5910
    },
    {
      id: "serpent-statue",
      titulo: "Serpent Shrine",
      subtitulo: "Asia",
      tipo: "Ponto temÃ¡tico para fotos",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "EstÃ¡tua sagrada de serpente entre ruÃ­nas, usada como ponto de contemplaÃ§Ã£o e fotos. Um canto tranquilo e curioso da Ãsia do Animal Kingdom.",
      icone: "ðŸ",
      imagem: "serpent-shrine.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3589,
      longitude: -81.5908
    }
  ]
};
