export const Asia = {
  parque: "Animal Kingdom",
  descricao: "Inspirada nas paisagens do Himalaia e da selva asiática, essa área combina montanhas-russas radicais, aventuras aquáticas e trilhas para explorar a vida selvagem.",
  imagem: "asia.png",
  latitude: 28.3588,
  longitude: -81.5915,
  atracoes: [
    {
      id: "expedition-everest",
      titulo: "Expedition Everest – Legend of the Forbidden Mountain",
      subtitulo: "Asia",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "imersivas"],
      alturaMinima: 112,
      filaExpress: true,
      tempoMedioFila: 55,
      filaAceitavel: 40,
      idadeRecomendada: "8+",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Uma montanha-russa intensa que te leva ao encontro do Yeti, com trechos de ré, subidas rápidas e curvas fechadas em meio ao Himalaia.",
      icone: "🏔️",
      imagem: "expedition-everest.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3582,
      longitude: -81.5916
    },
    {
      id: "kali-river-rapids",
      titulo: "Kali River Rapids",
      subtitulo: "Asia",
      tipo: "Aventura aquática",
      tipoPerfil: ["familiares", "radicais"],
      alturaMinima: 96,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 35,
      idadeRecomendada: "6+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Desça corredeiras em uma boia gigante, passando por florestas tropicais e áreas desmatadas. Prepare-se para se molhar completamente!",
      icone: "🌊",
      imagem: "kali-river-rapids.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3590,
      longitude: -81.5914
    },
    {
      id: "maharajah-jungle-trek",
      titulo: "Maharajah Jungle Trek",
      subtitulo: "Asia",
      tipo: "Trilha de observação",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Caminhada livre por ruínas antigas e jardins asiáticos, onde você pode observar tigres, morcegos gigantes e antílopes. A experiência é exploratória, sem fila e no seu ritmo.",
      icone: "🐅",
      imagem: "maharajah-jungle-trek.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3586,
      longitude: -81.5909
    },
    {
      id: "feathered-friends-in-flight",
      titulo: "Feathered Friends in Flight!",
      subtitulo: "Asia",
      tipo: "Apresentação com aves",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Show ao vivo com aves treinadas, apresentado por especialistas que explicam hábitos e curiosidades das espécies. Interativo e educativo.",
      icone: "🦜",
      imagem: "feathered-friends.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3591,
      longitude: -81.5910
    },
    {
      id: "serpent-statue",
      titulo: "Serpent Shrine",
      subtitulo: "Asia",
      tipo: "Ponto temático para fotos",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Estátua sagrada de serpente entre ruínas, usada como ponto de contemplação e fotos. Um canto tranquilo e curioso da Ásia do Animal Kingdom.",
      icone: "🐍",
      imagem: "serpent-shrine.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3589,
      longitude: -81.5908
    }
  ]
};
