ï»¿export const Asia = {
  parque: "Animal Kingdom",
  descricao: "Inspirada nas paisagens do Himalaia e da selva asiÃƒÂ¡tica, essa ÃƒÂ¡rea combina montanhas-russas radicais, aventuras aquÃƒÂ¡ticas e trilhas para explorar a vida selvagem.",
  imagem: "asia.png",
  latitude: 28.3588,
  longitude: -81.5915,
  atracoes: [
    {
      id: "expedition-everest",
      titulo: "Expedition Everest Ã¢â‚¬â€œ Legend of the Forbidden Mountain",
      subtitulo: "Asia",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "imersivas"],
      alturaMinima: 112,
      filaExpress: true,
      tempoMedioFila: 55,
      filaAceitavel: 40,
      idadeRecomendada: "8+",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Uma montanha-russa intensa que te leva ao encontro do Yeti, com trechos de rÃƒÂ©, subidas rÃƒÂ¡pidas e curvas fechadas em meio ao Himalaia.",
      icone: "Ã°Å¸Ââ€Ã¯Â¸Â",
      imagem: "expedition-everest.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3582,
      longitude: -81.5916
    },
    {
      id: "kali-river-rapids",
      titulo: "Kali River Rapids",
      subtitulo: "Asia",
      tipo: "Aventura aquÃƒÂ¡tica",
      tipoPerfil: ["familiares", "radicais"],
      alturaMinima: 96,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 35,
      idadeRecomendada: "6+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "DesÃƒÂ§a corredeiras em uma boia gigante, passando por florestas tropicais e ÃƒÂ¡reas desmatadas. Prepare-se para se molhar completamente!",
      icone: "Ã°Å¸Å’Å ",
      imagem: "kali-river-rapids.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3590,
      longitude: -81.5914
    },
    {
      id: "maharajah-jungle-trek",
      titulo: "Maharajah Jungle Trek",
      subtitulo: "Asia",
      tipo: "Trilha de observaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Caminhada livre por ruÃƒÂ­nas antigas e jardins asiÃƒÂ¡ticos, onde vocÃƒÂª pode observar tigres, morcegos gigantes e antÃƒÂ­lopes. A experiÃƒÂªncia ÃƒÂ© exploratÃƒÂ³ria, sem fila e no seu ritmo.",
      icone: "Ã°Å¸Ââ€¦",
      imagem: "maharajah-jungle-trek.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3586,
      longitude: -81.5909
    },
    {
      id: "feathered-friends-in-flight",
      titulo: "Feathered Friends in Flight!",
      subtitulo: "Asia",
      tipo: "ApresentaÃƒÂ§ÃƒÂ£o com aves",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Show ao vivo com aves treinadas, apresentado por especialistas que explicam hÃƒÂ¡bitos e curiosidades das espÃƒÂ©cies. Interativo e educativo.",
      icone: "Ã°Å¸Â¦Å“",
      imagem: "feathered-friends.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3591,
      longitude: -81.5910
    },
    {
      id: "serpent-statue",
      titulo: "Serpent Shrine",
      subtitulo: "Asia",
      tipo: "Ponto temÃƒÂ¡tico para fotos",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "EstÃƒÂ¡tua sagrada de serpente entre ruÃƒÂ­nas, usada como ponto de contemplaÃƒÂ§ÃƒÂ£o e fotos. Um canto tranquilo e curioso da ÃƒÂsia do Animal Kingdom.",
      icone: "Ã°Å¸ÂÂ",
      imagem: "serpent-shrine.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3589,
      longitude: -81.5908
    }
  ]
};
