export const DinoLand = {
  parque: "Animal Kingdom",
  descricao: "Ãrea com tema de dinossauros, fÃ³sseis e escavaÃ§Ãµes. Mistura diversÃ£o prÃ©-histÃ³rica com atraÃ§Ãµes radicais e atividades educativas para todas as idades.",
  imagem: "dinolandusa.png",
  latitude: 28.3581,
  longitude: -81.5867,
  atracoes: [
    {
      id: "dinosaur",
      titulo: "DINOSAUR",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Simulador escuro com movimento",
      tipoPerfil: ["radicais", "imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 30,
      idadeRecomendada: "8+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Uma viagem turbulenta ao perÃ­odo CretÃ¡ceo para resgatar um dinossauro antes de um meteoro atingir a Terra. Cheia de sustos e sacudidas.",
      icone: "ðŸ¦–",
      imagem: "dinosaur.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3579,
      longitude: -81.5871
    },
    {
      id: "triceratop-spin",
      titulo: "TriceraTop Spin",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Brinquedo giratÃ³rio",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Voe em cÃ­rculos num brinquedo giratÃ³rio em forma de dinossauro. Perfeito para os pequenos.",
      icone: "ðŸ¦•",
      imagem: "triceratop-spin.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3583,
      longitude: -81.5865
    },
    {
      id: "fossil-fun-games",
      titulo: "Fossil Fun Games",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Jogos de parque",
      tipoPerfil: ["interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Jogos estilo parque de diversÃµes com tema de fÃ³sseis e dinossauros. Participe livremente e tente ganhar prÃªmios.",
      icone: "ðŸŽ¯",
      imagem: "fossil-fun-games.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3582,
      longitude: -81.5863
    },
    {
      id: "boneyard",
      titulo: "The Boneyard",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Ãrea de escavaÃ§Ã£o e playground",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Playground ao ar livre onde as crianÃ§as podem escavar fÃ³sseis em uma enorme caixa de areia temÃ¡tica. Acesso livre, sem fila.",
      icone: "â›ï¸",
      imagem: "the-boneyard.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3580,
      longitude: -81.5869
    },
    {
      id: "donald-daisy-meet",
      titulo: "Meet Donald & Daisy at DinoLand",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Encontro com personagens",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: "Tire fotos e interaja com Donald e Daisy vestidos com trajes de exploradores jurÃ¡ssicos em um cenÃ¡rio colorido e divertido.",
      icone: "ðŸ“¸",
      imagem: "donald-daisy.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3577,
      longitude: -81.5868
    }
  ]
};
