export const DiscoveryIsland = {
  parque: "Animal Kingdom",
  descricao: "O coração do Animal Kingdom, com acesso central às demais áreas e foco em biodiversidade, trilhas com animais e o icônico Tree of Life.",
  imagem: "discoveryisland.png",
  latitude: 28.3574,
  longitude: -81.5902,
  atracoes: [
    {
      id: "its-tough-to-be-a-bug",
      titulo: "It’s Tough to Be a Bug!",
      subtitulo: "Discovery Island",
      tipo: "Show 4D",
      tipoPerfil: ["imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "6+",
      turnoRecomendado: "tarde",
      descricao: "Show 4D com personagens de Vida de Inseto, cheio de efeitos especiais, surpresas no assento e interação com o público.",
      icone: "🐜",
      imagem: "its-tough-to-be-a-bug.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3572,
      longitude: -81.5899
    },
    {
      id: "tree-of-life-trails",
      titulo: "Tree of Life Trails",
      subtitulo: "Discovery Island",
      tipo: "Trilha de observação",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Trilhas tranquilas ao redor da Árvore da Vida com esculturas de animais e áreas de observação de flamingos e cangurus.",
      icone: "🌳",
      imagem: "tree-of-life-trails.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3575,
      longitude: -81.5905
    },
    {
      id: "adventurers-outpost",
      titulo: "Adventurers Outpost",
      subtitulo: "Discovery Island",
      tipo: "Encontro com personagens",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Ponto de encontro com Mickey e Minnie vestidos de exploradores. Ideal para fotos memoráveis.",
      icone: "📸",
      imagem: "adventurers-outpost.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3571,
      longitude: -81.5903
    },
    {
      id: "island-mercantile",
      titulo: "Island Mercantile",
      subtitulo: "Discovery Island",
      tipo: "Loja temática",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Loja com produtos inspirados na natureza, roupas, brinquedos e souvenirs do Animal Kingdom. Sem filas, ambiente climatizado.",
      icone: "🛍️",
      imagem: "island-mercantile.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3576,
      longitude: -81.5901
    },
    {
      id: "flame-tree-bbq-area",
      titulo: "Área temática do Flame Tree BBQ",
      subtitulo: "Discovery Island",
      tipo: "Área de alimentação temática",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "Espaço ao ar livre com mesas à beira do lago, decoração rústica e vista para os shows noturnos. Ideal para descansar ou comer algo.",
      icone: "🍖",
      imagem: "flame-tree-area.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3578,
      longitude: -81.5898
    }
  ]
};
