ï»¿export const DiscoveryIsland = {
  parque: "Animal Kingdom",
  descricao: "O coraÃƒÂ§ÃƒÂ£o do Animal Kingdom, com acesso central ÃƒÂ s demais ÃƒÂ¡reas e foco em biodiversidade, trilhas com animais e o icÃƒÂ´nico Tree of Life.",
  imagem: "discoveryisland.png",
  latitude: 28.3574,
  longitude: -81.5902,
  atracoes: [
    {
      id: "its-tough-to-be-a-bug",
      titulo: "ItÃ¢â‚¬â„¢s Tough to Be a Bug!",
      subtitulo: "Discovery Island",
      tipo: "Show 4D",
      tipoPerfil: ["imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "6+",
      turnoRecomendado: "tarde",
      descricao: "Show 4D com personagens de Vida de Inseto, cheio de efeitos especiais, surpresas no assento e interaÃƒÂ§ÃƒÂ£o com o pÃƒÂºblico.",
      icone: "Ã°Å¸ÂÅ“",
      imagem: "its-tough-to-be-a-bug.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3572,
      longitude: -81.5899
    },
    {
      id: "tree-of-life-trails",
      titulo: "Tree of Life Trails",
      subtitulo: "Discovery Island",
      tipo: "Trilha de observaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Trilhas tranquilas ao redor da ÃƒÂrvore da Vida com esculturas de animais e ÃƒÂ¡reas de observaÃƒÂ§ÃƒÂ£o de flamingos e cangurus.",
      icone: "Ã°Å¸Å’Â³",
      imagem: "tree-of-life-trails.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3575,
      longitude: -81.5905
    },
    {
      id: "adventurers-outpost",
      titulo: "Adventurers Outpost",
      subtitulo: "Discovery Island",
      tipo: "Encontro com personagens",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Ponto de encontro com Mickey e Minnie vestidos de exploradores. Ideal para fotos memorÃƒÂ¡veis.",
      icone: "Ã°Å¸â€œÂ¸",
      imagem: "adventurers-outpost.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3571,
      longitude: -81.5903
    },
    {
      id: "island-mercantile",
      titulo: "Island Mercantile",
      subtitulo: "Discovery Island",
      tipo: "Loja temÃƒÂ¡tica",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Loja com produtos inspirados na natureza, roupas, brinquedos e souvenirs do Animal Kingdom. Sem filas, ambiente climatizado.",
      icone: "Ã°Å¸â€ºÂÃ¯Â¸Â",
      imagem: "island-mercantile.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3576,
      longitude: -81.5901
    },
    {
      id: "flame-tree-bbq-area",
      titulo: "ÃƒÂrea temÃƒÂ¡tica do Flame Tree BBQ",
      subtitulo: "Discovery Island",
      tipo: "ÃƒÂrea de alimentaÃƒÂ§ÃƒÂ£o temÃƒÂ¡tica",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "EspaÃƒÂ§o ao ar livre com mesas ÃƒÂ  beira do lago, decoraÃƒÂ§ÃƒÂ£o rÃƒÂºstica e vista para os shows noturnos. Ideal para descansar ou comer algo.",
      icone: "Ã°Å¸Ââ€“",
      imagem: "flame-tree-area.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3578,
      longitude: -81.5898
    }
  ]
};
