ï»¿export const EchoLake = {
  regiao: "Echo Lake",
  parque: "Hollywood Studios",
  latitude: 28.3574,
  longitude: -81.5606,
  descricao: "ÃƒÂrea com temÃƒÂ¡tica de cinema clÃƒÂ¡ssico, shows ao vivo e atraÃƒÂ§ÃƒÂµes baseadas em grandes franquias como Indiana Jones e Star Wars.",
  imagem: "echolake.png",
  atracoes: [
    {
      id: "indiana-jones-stunt-spectacular",
      titulo: "Indiana Jones Epic Stunt Spectacular!",
      subtitulo: "Echo Lake",
      tipo: "Show de acrobacias",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Show ao vivo com dublÃƒÂªs recriando cenas famosas dos filmes de Indiana Jones. Apresentado em horÃƒÂ¡rios fixos durante o dia.",
      icone: "Ã°Å¸Å½Â¬",
      imagem: "indiana-jones.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    },
    {
      id: "star-tours",
      titulo: "Star Tours Ã¢â‚¬â€œ The Adventures Continue",
      subtitulo: "Echo Lake",
      tipo: "Simulador 3D",
      tipoPerfil: ["imersivas", "radicais"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 30,
      idadeRecomendada: "7+",
      turnoRecomendado: "manha",
      descricao: "Simulador 3D com movimentos intensos por vÃƒÂ¡rios planetas do universo Star Wars, com cenas aleatÃƒÂ³rias em cada passeio.",
      icone: "Ã°Å¸Å¡â‚¬",
      imagem: "star-tours.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    },
    {
      id: "meet-olaf",
      titulo: "Meet Olaf at Celebrity Spotlight",
      subtitulo: "Echo Lake",
      tipo: "Encontro com personagens",
      tipoPerfil: ["familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Encontro com o Olaf, de Frozen, em um espaÃƒÂ§o com cenÃƒÂ¡rio nevado. Perfeito para crianÃƒÂ§as e fotos divertidas.",
      icone: "Ã¢ËœÆ’Ã¯Â¸Â",
      imagem: "meet-olaf.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    },
    {
      id: "for-the-first-time-in-forever",
      titulo: "For the First Time in Forever: A Frozen Sing-Along Celebration",
      subtitulo: "Echo Lake",
      tipo: "Show musical com personagens",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "Show musical divertido com personagens de Frozen, letras na tela e efeitos especiais. Ãƒâ€œtimo para descansar e cantar junto.",
      icone: "Ã°Å¸Å½Â¤",
      imagem: "frozen-sing-along.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    },
    {
      id: "dockside-diner",
      titulo: "Dockside Diner (ÃƒÂrea TemÃƒÂ¡tica)",
      subtitulo: "Echo Lake",
      tipo: "ÃƒÂrea de alimentaÃƒÂ§ÃƒÂ£o e relaxamento",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Barco cenogrÃƒÂ¡fico com lanches rÃƒÂ¡pidos e mesas ao ar livre. Ideal para uma pausa entre as atraÃƒÂ§ÃƒÂµes e observar o Echo Lake.",
      icone: "Ã°Å¸Ââ€",
      imagem: "dockside-diner.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    }
  ]
};
