export const EchoLake = {
  regiao: "Echo Lake",
  parque: "Hollywood Studios",
  latitude: 28.3574,
  longitude: -81.5606,
  descricao: "Área com temática de cinema clássico, shows ao vivo e atrações baseadas em grandes franquias como Indiana Jones e Star Wars.",
  imagem: "echolake.png",
  atracoes: [
    {
      id: "indiana-jones-stunt-spectacular",
      titulo: "Indiana Jones Epic Stunt Spectacular!",
      subtitulo: "Echo Lake",
      tipo: "Show de acrobacias",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Show ao vivo com dublês recriando cenas famosas dos filmes de Indiana Jones. Apresentado em horários fixos durante o dia.",
      icone: "🎬",
      imagem: "indiana-jones.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    },
    {
      id: "star-tours",
      titulo: "Star Tours – The Adventures Continue",
      subtitulo: "Echo Lake",
      tipo: "Simulador 3D",
      tipoPerfil: ["imersivas", "radicais"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 30,
      idadeRecomendada: "7+",
      turnoRecomendado: "manha",
      descricao: "Simulador 3D com movimentos intensos por vários planetas do universo Star Wars, com cenas aleatórias em cada passeio.",
      icone: "🚀",
      imagem: "star-tours.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    },
    {
      id: "meet-olaf",
      titulo: "Meet Olaf at Celebrity Spotlight",
      subtitulo: "Echo Lake",
      tipo: "Encontro com personagens",
      tipoPerfil: ["familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Encontro com o Olaf, de Frozen, em um espaço com cenário nevado. Perfeito para crianças e fotos divertidas.",
      icone: "☃️",
      imagem: "meet-olaf.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    },
    {
      id: "for-the-first-time-in-forever",
      titulo: "For the First Time in Forever: A Frozen Sing-Along Celebration",
      subtitulo: "Echo Lake",
      tipo: "Show musical com personagens",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "Show musical divertido com personagens de Frozen, letras na tela e efeitos especiais. Ótimo para descansar e cantar junto.",
      icone: "🎤",
      imagem: "frozen-sing-along.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    },
    {
      id: "dockside-diner",
      titulo: "Dockside Diner (Área Temática)",
      subtitulo: "Echo Lake",
      tipo: "Área de alimentação e relaxamento",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Barco cenográfico com lanches rápidos e mesas ao ar livre. Ideal para uma pausa entre as atrações e observar o Echo Lake.",
      icone: "🍔",
      imagem: "dockside-diner.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    }
  ]
};
