export const EchoLake = {
  regiao: "Echo Lake",
  parque: "Hollywood Studios",
  latitude: 28.3574,
  longitude: -81.5606,
  descricao: "Ãrea com temÃ¡tica de cinema clÃ¡ssico, shows ao vivo e atraÃ§Ãµes baseadas em grandes franquias como Indiana Jones e Star Wars.",
  imagem: "echolake.png",
  atracoes: [
    {
      id: "indiana-jones-stunt-spectacular",
      titulo: "Indiana Jones Epic Stunt Spectacular!",
      subtitulo: "Echo Lake",
      tipo: "Show de acrobacias",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Show ao vivo com dublÃªs recriando cenas famosas dos filmes de Indiana Jones. Apresentado em horÃ¡rios fixos durante o dia.",
      icone: "ðŸŽ¬",
      imagem: "indiana-jones.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    },
    {
      id: "star-tours",
      titulo: "Star Tours â€“ The Adventures Continue",
      subtitulo: "Echo Lake",
      tipo: "Simulador 3D",
      tipoPerfil: ["imersivas", "radicais"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 30,
      idadeRecomendada: "7+",
      turnoRecomendado: "manha",
      descricao: "Simulador 3D com movimentos intensos por vÃ¡rios planetas do universo Star Wars, com cenas aleatÃ³rias em cada passeio.",
      icone: "ðŸš€",
      imagem: "star-tours.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    },
    {
      id: "meet-olaf",
      titulo: "Meet Olaf at Celebrity Spotlight",
      subtitulo: "Echo Lake",
      tipo: "Encontro com personagens",
      tipoPerfil: ["familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Encontro com o Olaf, de Frozen, em um espaÃ§o com cenÃ¡rio nevado. Perfeito para crianÃ§as e fotos divertidas.",
      icone: "â˜ƒï¸",
      imagem: "meet-olaf.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    },
    {
      id: "for-the-first-time-in-forever",
      titulo: "For the First Time in Forever: A Frozen Sing-Along Celebration",
      subtitulo: "Echo Lake",
      tipo: "Show musical com personagens",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "Show musical divertido com personagens de Frozen, letras na tela e efeitos especiais. Ã“timo para descansar e cantar junto.",
      icone: "ðŸŽ¤",
      imagem: "frozen-sing-along.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    },
    {
      id: "dockside-diner",
      titulo: "Dockside Diner (Ãrea TemÃ¡tica)",
      subtitulo: "Echo Lake",
      tipo: "Ãrea de alimentaÃ§Ã£o e relaxamento",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Barco cenogrÃ¡fico com lanches rÃ¡pidos e mesas ao ar livre. Ideal para uma pausa entre as atraÃ§Ãµes e observar o Echo Lake.",
      icone: "ðŸ”",
      imagem: "dockside-diner.jpg",
      regiao: "Echo Lake",
      parque: "Hollywood Studios"
    }
  ]
};
