export const Fantasyland = {
  parque: "Magic Kingdom",
  regiao: "Fantasyland",
  latitude: 28.4194,
  longitude: -81.5812,
  descricao: "Área mágica e encantadora inspirada nos contos de fadas clássicos da Disney. Lar de princesas, castelos, voos encantados e atrações para toda a família.",
  imagem: "fantasyland.png",
  atracoes: [
    {
      id: "peter-pan-flight",
      titulo: "Peter Pan’s Flight",
      subtitulo: "Fantasyland",
      tipo: "Dark ride suspensa",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Voe sobre Londres e siga Peter Pan até a Terra do Nunca em um carrinho suspenso. A atração é um clássico e costuma ter fila longa.",
      icone: "🧚",
      imagem: "peter-pan.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    },
    {
      id: "seven-dwarfs-mine-train",
      titulo: "Seven Dwarfs Mine Train",
      subtitulo: "Fantasyland",
      tipo: "Montanha-russa suave",
      tipoPerfil: ["radicais", "tematicas"],
      alturaMinima: 97,
      filaExpress: true,
      tempoMedioFila: 75,
      filaAceitavel: 45,
      idadeRecomendada: "5+",
      turnoRecomendado: "manha",
      descricao: "Montanha-russa suave com curvas rápidas e trechos de dark ride pelas minas dos Sete Anões. Mistura aventura com magia.",
      icone: "⛏️",
      imagem: "mine-train.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    },
    {
      id: "its-a-small-world",
      titulo: "It’s a Small World",
      subtitulo: "Fantasyland",
      tipo: "Passeio de barco temático",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Passeio de barco ao redor do mundo com bonecos animados e a icônica música tema. Colorido, calmo e multicultural.",
      icone: "🌍",
      imagem: "small-world.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    },
    {
      id: "princess-fairytale-hall",
      titulo: "Princess Fairytale Hall",
      subtitulo: "Fantasyland",
      tipo: "Encontro com princesas",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Área temática para conhecer princesas como Cinderela, Rapunzel e Tiana. Ideal para fotos e interação com personagens.",
      icone: "👑",
      imagem: "princess-hall.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    },
    {
      id: "mad-tea-party",
      titulo: "Mad Tea Party",
      subtitulo: "Fantasyland",
      tipo: "Xícaras giratórias",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Gire em xícaras de chá coloridas ao som de uma trilha maluca inspirada em Alice no País das Maravilhas. Clássico e divertido.",
      icone: "🍵",
      imagem: "mad-tea-party.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    }
  ]
};
