ï»¿export const Fantasyland = {
  parque: "Magic Kingdom",
  regiao: "Fantasyland",
  latitude: 28.4194,
  longitude: -81.5812,
  descricao: "ÃƒÂrea mÃƒÂ¡gica e encantadora inspirada nos contos de fadas clÃƒÂ¡ssicos da Disney. Lar de princesas, castelos, voos encantados e atraÃƒÂ§ÃƒÂµes para toda a famÃƒÂ­lia.",
  imagem: "fantasyland.png",
  atracoes: [
    {
      id: "peter-pan-flight",
      titulo: "Peter PanÃ¢â‚¬â„¢s Flight",
      subtitulo: "Fantasyland",
      tipo: "Dark ride suspensa",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Voe sobre Londres e siga Peter Pan atÃƒÂ© a Terra do Nunca em um carrinho suspenso. A atraÃƒÂ§ÃƒÂ£o ÃƒÂ© um clÃƒÂ¡ssico e costuma ter fila longa.",
      icone: "Ã°Å¸Â§Å¡",
      imagem: "peter-pan.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    },
    {
      id: "seven-dwarfs-mine-train",
      titulo: "Seven Dwarfs Mine Train",
      subtitulo: "Fantasyland",
      tipo: "Montanha-russa suave",
      tipoPerfil: ["radicais", "tematicas"],
      alturaMinima: 97,
      filaExpress: true,
      tempoMedioFila: 75,
      filaAceitavel: 45,
      idadeRecomendada: "5+",
      turnoRecomendado: "manha",
      descricao: "Montanha-russa suave com curvas rÃƒÂ¡pidas e trechos de dark ride pelas minas dos Sete AnÃƒÂµes. Mistura aventura com magia.",
      icone: "Ã¢â€ºÂÃ¯Â¸Â",
      imagem: "mine-train.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    },
    {
      id: "its-a-small-world",
      titulo: "ItÃ¢â‚¬â„¢s a Small World",
      subtitulo: "Fantasyland",
      tipo: "Passeio de barco temÃƒÂ¡tico",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Passeio de barco ao redor do mundo com bonecos animados e a icÃƒÂ´nica mÃƒÂºsica tema. Colorido, calmo e multicultural.",
      icone: "Ã°Å¸Å’Â",
      imagem: "small-world.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    },
    {
      id: "princess-fairytale-hall",
      titulo: "Princess Fairytale Hall",
      subtitulo: "Fantasyland",
      tipo: "Encontro com princesas",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "ÃƒÂrea temÃƒÂ¡tica para conhecer princesas como Cinderela, Rapunzel e Tiana. Ideal para fotos e interaÃƒÂ§ÃƒÂ£o com personagens.",
      icone: "Ã°Å¸â€˜â€˜",
      imagem: "princess-hall.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    },
    {
      id: "mad-tea-party",
      titulo: "Mad Tea Party",
      subtitulo: "Fantasyland",
      tipo: "XÃƒÂ­caras giratÃƒÂ³rias",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Gire em xÃƒÂ­caras de chÃƒÂ¡ coloridas ao som de uma trilha maluca inspirada em Alice no PaÃƒÂ­s das Maravilhas. ClÃƒÂ¡ssico e divertido.",
      icone: "Ã°Å¸ÂÂµ",
      imagem: "mad-tea-party.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    }
  ]
};
