export const Fantasyland = {
  parque: "Magic Kingdom",
  regiao: "Fantasyland",
  latitude: 28.4194,
  longitude: -81.5812,
  descricao: "Ãrea mÃ¡gica e encantadora inspirada nos contos de fadas clÃ¡ssicos da Disney. Lar de princesas, castelos, voos encantados e atraÃ§Ãµes para toda a famÃ­lia.",
  imagem: "fantasyland.png",
  atracoes: [
    {
      id: "peter-pan-flight",
      titulo: "Peter Panâ€™s Flight",
      subtitulo: "Fantasyland",
      tipo: "Dark ride suspensa",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Voe sobre Londres e siga Peter Pan atÃ© a Terra do Nunca em um carrinho suspenso. A atraÃ§Ã£o Ã© um clÃ¡ssico e costuma ter fila longa.",
      icone: "ðŸ§š",
      imagem: "peter-pan.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    },
    {
      id: "seven-dwarfs-mine-train",
      titulo: "Seven Dwarfs Mine Train",
      subtitulo: "Fantasyland",
      tipo: "Montanha-russa suave",
      tipoPerfil: ["radicais", "tematicas"],
      alturaMinima: 97,
      filaExpress: true,
      tempoMedioFila: 75,
      filaAceitavel: 45,
      idadeRecomendada: "5+",
      turnoRecomendado: "manha",
      descricao: "Montanha-russa suave com curvas rÃ¡pidas e trechos de dark ride pelas minas dos Sete AnÃµes. Mistura aventura com magia.",
      icone: "â›ï¸",
      imagem: "mine-train.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    },
    {
      id: "its-a-small-world",
      titulo: "Itâ€™s a Small World",
      subtitulo: "Fantasyland",
      tipo: "Passeio de barco temÃ¡tico",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Passeio de barco ao redor do mundo com bonecos animados e a icÃ´nica mÃºsica tema. Colorido, calmo e multicultural.",
      icone: "ðŸŒ",
      imagem: "small-world.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    },
    {
      id: "princess-fairytale-hall",
      titulo: "Princess Fairytale Hall",
      subtitulo: "Fantasyland",
      tipo: "Encontro com princesas",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Ãrea temÃ¡tica para conhecer princesas como Cinderela, Rapunzel e Tiana. Ideal para fotos e interaÃ§Ã£o com personagens.",
      icone: "ðŸ‘‘",
      imagem: "princess-hall.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    },
    {
      id: "mad-tea-party",
      titulo: "Mad Tea Party",
      subtitulo: "Fantasyland",
      tipo: "XÃ­caras giratÃ³rias",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Gire em xÃ­caras de chÃ¡ coloridas ao som de uma trilha maluca inspirada em Alice no PaÃ­s das Maravilhas. ClÃ¡ssico e divertido.",
      icone: "ðŸµ",
      imagem: "mad-tea-party.jpg",
      regiao: "Fantasyland",
      parque: "Magic Kingdom"
    }
  ]
};
