export const Frontierland = {
  parque: "Magic Kingdom",
  regiao: "Frontierland",
  latitude: 28.4188,
  longitude: -81.5851,
  descricao: "Área com tema do Velho Oeste americano, cheia de trilhos de mina, quedas d’água e aventuras selvagens. Ideal para quem busca adrenalina em um cenário rústico e divertido.",
  imagem: "frontierland.png",
  atracoes: [
    {
      id: "big-thunder-mountain",
      titulo: "Big Thunder Mountain Railroad",
      subtitulo: "Frontierland",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "5+",
      turnoRecomendado: "tarde",
      descricao: "Montanha-russa no estilo mina de ouro com trilhos ao ar livre e curvas em alta velocidade entre rochas e dinamites.",
      icone: "🏔️",
      imagem: "big-thunder.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom"
    },
    {
      id: "tianas-bayou-adventure",
      titulo: "Tiana’s Bayou Adventure",
      subtitulo: "Frontierland",
      tipo: "Aventura aquática",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 45,
      idadeRecomendada: "5+",
      turnoRecomendado: "tarde",
      descricao: "Passeio em tronco pelo bayou com música e personagens de ‘A Princesa e o Sapo’, culminando em uma queda emocionante.",
      icone: "🎷",
      imagem: "tiana-bayou.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom"
    },
    {
      id: "country-bear-musical-jamboree",
      titulo: "Country Bear Musical Jamboree",
      subtitulo: "Frontierland",
      tipo: "Show musical com bonecos",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Versão atualizada do clássico show dos ursos, com repertório e figurinos novos em clima country.",
      icone: "🐻",
      imagem: "country-bear-musical.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom"
    }
  ]
};
