export const Frontierland = {
  parque: "Magic Kingdom",
  regiao: "Frontierland",
  latitude: 28.4188,
  longitude: -81.5851,
  descricao: "Ãrea com tema do Velho Oeste americano, cheia de trilhos de mina, quedas dâ€™Ã¡gua e aventuras selvagens. Ideal para quem busca adrenalina em um cenÃ¡rio rÃºstico e divertido.",
  imagem: "frontierland.png",
  atracoes: [
    {
      id: "big-thunder-mountain",
      titulo: "Big Thunder Mountain Railroad",
      subtitulo: "Frontierland",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "5+",
      turnoRecomendado: "tarde",
      descricao: "Montanha-russa no estilo mina de ouro com trilhos ao ar livre e curvas em alta velocidade entre rochas e dinamites.",
      icone: "ðŸ”ï¸",
      imagem: "big-thunder.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom"
    },
    {
      id: "splash-mountain",
      titulo: "Splash Mountain",
      subtitulo: "Frontierland",
      tipo: "Aventura aquÃ¡tica",
      tipoPerfil: ["familiares", "radicais"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 65,
      filaAceitavel: 45,
      idadeRecomendada: "5+",
      turnoRecomendado: "tarde",
      descricao: "Passeio em barco com trilha sonora animada, cenas de personagens e uma grande queda dâ€™Ã¡gua no final. Prepare-se para se molhar!",
      icone: "ðŸ’¦",
      imagem: "splash-mountain.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom"
    },
    {
      id: "frontierland-shooting-gallery",
      titulo: "Frontierland Shootinâ€™ Arcade",
      subtitulo: "Frontierland",
      tipo: "Jogo de tiro temÃ¡tico",
      tipoPerfil: ["interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Desafie seus reflexos em um campo de tiro do velho oeste com alvos animados. NÃ£o precisa de fila, Ã© sÃ³ chegar e brincar.",
      icone: "ðŸŽ¯",
      imagem: "shooting-gallery.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom"
    },
    {
      id: "country-bear-jamboree",
      titulo: "Country Bear Jamboree",
      subtitulo: "Frontierland",
      tipo: "Show musical com bonecos",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "EspetÃ¡culo musical com ursos animatrÃ´nicos cantando canÃ§Ãµes country em um teatro rÃºstico. Divertido, leve e sem fila.",
      icone: "ðŸ»",
      imagem: "country-bear.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom"
    }
  ]
};
