export const Frontierland = {
  parque: "Magic Kingdom",
  regiao: "Frontierland",
  latitude: 28.4188,
  longitude: -81.5851,
  descricao: "Área com tema do Velho Oeste americano, cheia de trilhos de mina, quedas d’água e aventuras selvagens. Ideal para quem busca adrenalina em um cenário rústico e divertido.",
  imagem: "frontierland.png",
  atracoes: [
    {
      id: "big-thunder-mountain",
      titulo: "Big Thunder Mountain Railroad",
      subtitulo: "Frontierland",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "5+",
      turnoRecomendado: "tarde",
      descricao: "Montanha-russa no estilo mina de ouro com trilhos ao ar livre e curvas em alta velocidade entre rochas e dinamites.",
      icone: "🏔️",
      imagem: "big-thunder.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom"
    },
    {
      id: "splash-mountain",
      titulo: "Splash Mountain",
      subtitulo: "Frontierland",
      tipo: "Aventura aquática",
      tipoPerfil: ["familiares", "radicais"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 65,
      filaAceitavel: 45,
      idadeRecomendada: "5+",
      turnoRecomendado: "tarde",
      descricao: "Passeio em barco com trilha sonora animada, cenas de personagens e uma grande queda d’água no final. Prepare-se para se molhar!",
      icone: "💦",
      imagem: "splash-mountain.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom"
    },
    {
      id: "frontierland-shooting-gallery",
      titulo: "Frontierland Shootin’ Arcade",
      subtitulo: "Frontierland",
      tipo: "Jogo de tiro temático",
      tipoPerfil: ["interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Desafie seus reflexos em um campo de tiro do velho oeste com alvos animados. Não precisa de fila, é só chegar e brincar.",
      icone: "🎯",
      imagem: "shooting-gallery.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom"
    },
    {
      id: "country-bear-jamboree",
      titulo: "Country Bear Jamboree",
      subtitulo: "Frontierland",
      tipo: "Show musical com bonecos",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Espetáculo musical com ursos animatrônicos cantando canções country em um teatro rústico. Divertido, leve e sem fila.",
      icone: "🐻",
      imagem: "country-bear.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom"
    }
  ]
};
