ï»¿export const FutureWorld = {
  parque: "Epcot",
  regiao: "Future World",
  latitude: 28.3747,
  longitude: -81.5494,
  descricao: "Antiga ÃƒÂ¡rea principal do Epcot dedicada ÃƒÂ  ciÃƒÂªncia, tecnologia e inovaÃƒÂ§ÃƒÂ£o. Algumas atraÃƒÂ§ÃƒÂµes ainda mantÃƒÂªm esse espÃƒÂ­rito futurista em experiÃƒÂªncias educativas e imersivas.",
  imagem: "futureworld.png",
  atracoes: [
    {
      id: "spaceship-earth",
      titulo: "Spaceship Earth",
      subtitulo: "Future World",
      tipo: "Dark ride educativa",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      descricao: "Viagem atravÃƒÂ©s da histÃƒÂ³ria da comunicaÃƒÂ§ÃƒÂ£o humana, dentro do icÃƒÂ´nico globo prateado do Epcot. Tranquilo e educativo.",
      icone: "Ã°Å¸Å’Â",
      imagem: "spaceship-earth.jpg",
      regiao: "Future World",
      parque: "Epcot"
    },
    {
      id: "journey-into-imagination",
      titulo: "Journey Into Imagination with Figment",
      subtitulo: "Future World",
      tipo: "Dark ride criativa",
      tipoPerfil: ["interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      descricao: "Explore os sentidos e a criatividade com o personagem Figment em um passeio leve e cheio de surpresas.",
      icone: "Ã°Å¸Å½Â¨",
      imagem: "journey-into-imagination.jpg",
      regiao: "Future World",
      parque: "Epcot"
    },
    {
      id: "project-tomorrow",
      titulo: "Project Tomorrow",
      subtitulo: "Future World",
      tipo: "EspaÃƒÂ§o interativo",
      tipoPerfil: ["interativas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      descricao: "ÃƒÂrea interativa localizada na saÃƒÂ­da do Spaceship Earth, com jogos e experiÃƒÂªncias tecnolÃƒÂ³gicas sem fila.",
      icone: "Ã°Å¸â€¢Â¹Ã¯Â¸Â",
      imagem: "project-tomorrow.jpg",
      regiao: "Future World",
      parque: "Epcot"
    },
    {
      id: "imageworks",
      titulo: "ImageWorks Ã¢â‚¬â€œ The What-If Labs",
      subtitulo: "Future World",
      tipo: "LaboratÃƒÂ³rio de experiÃƒÂªncias criativas",
      tipoPerfil: ["interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      descricao: "ÃƒÂrea interativa ao final da atraÃƒÂ§ÃƒÂ£o de Figment, com estaÃƒÂ§ÃƒÂµes criativas para experimentar sons, luzes e movimento.",
      icone: "Ã°Å¸Â§Â ",
      imagem: "imageworks.jpg",
      regiao: "Future World",
      parque: "Epcot"
    },
    {
      id: "discovery-spot",
      titulo: "Discovery Spot",
      subtitulo: "Future World",
      tipo: "Ponto temÃƒÂ¡tico de descanso e exploraÃƒÂ§ÃƒÂµes livres",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      descricao: "EspaÃƒÂ§o ao ar livre com jardins tecnolÃƒÂ³gicos, fontes interativas e bancos sombreados. Ideal para relaxar e explorar livremente.",
      icone: "Ã°Å¸Â§Â¬",
      imagem: "discovery-spot.jpg",
      regiao: "Future World",
      parque: "Epcot"
    }
  ]
};
