export const FutureWorld = {
  parque: "Epcot",
  regiao: "Future World",
  latitude: 28.3747,
  longitude: -81.5494,
  descricao: "Antiga Ã¡rea principal do Epcot dedicada Ã  ciÃªncia, tecnologia e inovaÃ§Ã£o. Algumas atraÃ§Ãµes ainda mantÃªm esse espÃ­rito futurista em experiÃªncias educativas e imersivas.",
  imagem: "futureworld.png",
  atracoes: [
    {
      id: "spaceship-earth",
      titulo: "Spaceship Earth",
      subtitulo: "Future World",
      tipo: "Dark ride educativa",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      descricao: "Viagem atravÃ©s da histÃ³ria da comunicaÃ§Ã£o humana, dentro do icÃ´nico globo prateado do Epcot. Tranquilo e educativo.",
      icone: "ðŸŒ",
      imagem: "spaceship-earth.jpg",
      regiao: "Future World",
      parque: "Epcot"
    },
    {
      id: "journey-into-imagination",
      titulo: "Journey Into Imagination with Figment",
      subtitulo: "Future World",
      tipo: "Dark ride criativa",
      tipoPerfil: ["interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      descricao: "Explore os sentidos e a criatividade com o personagem Figment em um passeio leve e cheio de surpresas.",
      icone: "ðŸŽ¨",
      imagem: "journey-into-imagination.jpg",
      regiao: "Future World",
      parque: "Epcot"
    },
    {
      id: "project-tomorrow",
      titulo: "Project Tomorrow",
      subtitulo: "Future World",
      tipo: "EspaÃ§o interativo",
      tipoPerfil: ["interativas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      descricao: "Ãrea interativa localizada na saÃ­da do Spaceship Earth, com jogos e experiÃªncias tecnolÃ³gicas sem fila.",
      icone: "ðŸ•¹ï¸",
      imagem: "project-tomorrow.jpg",
      regiao: "Future World",
      parque: "Epcot"
    },
    {
      id: "imageworks",
      titulo: "ImageWorks â€“ The What-If Labs",
      subtitulo: "Future World",
      tipo: "LaboratÃ³rio de experiÃªncias criativas",
      tipoPerfil: ["interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      descricao: "Ãrea interativa ao final da atraÃ§Ã£o de Figment, com estaÃ§Ãµes criativas para experimentar sons, luzes e movimento.",
      icone: "ðŸ§ ",
      imagem: "imageworks.jpg",
      regiao: "Future World",
      parque: "Epcot"
    },
    {
      id: "discovery-spot",
      titulo: "Discovery Spot",
      subtitulo: "Future World",
      tipo: "Ponto temÃ¡tico de descanso e exploraÃ§Ãµes livres",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      descricao: "EspaÃ§o ao ar livre com jardins tecnolÃ³gicos, fontes interativas e bancos sombreados. Ideal para relaxar e explorar livremente.",
      icone: "ðŸ§¬",
      imagem: "discovery-spot.jpg",
      regiao: "Future World",
      parque: "Epcot"
    }
  ]
};
