export const FutureWorld = {
  parque: "Epcot",
  regiao: "Future World",
  latitude: 28.3747,
  longitude: -81.5494,
  descricao: "Antiga área principal do Epcot dedicada à ciência, tecnologia e inovação. Algumas atrações ainda mantêm esse espírito futurista em experiências educativas e imersivas.",
  imagem: "futureworld.png",
  atracoes: [
    {
      id: "spaceship-earth",
      titulo: "Spaceship Earth",
      subtitulo: "Future World",
      tipo: "Dark ride educativa",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      descricao: "Viagem através da história da comunicação humana, dentro do icônico globo prateado do Epcot. Tranquilo e educativo.",
      icone: "🌐",
      imagem: "spaceship-earth.jpg",
      regiao: "Future World",
      parque: "Epcot"
    },
    {
      id: "journey-into-imagination",
      titulo: "Journey Into Imagination with Figment",
      subtitulo: "Future World",
      tipo: "Dark ride criativa",
      tipoPerfil: ["interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      descricao: "Explore os sentidos e a criatividade com o personagem Figment em um passeio leve e cheio de surpresas.",
      icone: "🎨",
      imagem: "journey-into-imagination.jpg",
      regiao: "Future World",
      parque: "Epcot"
    },
    {
      id: "project-tomorrow",
      titulo: "Project Tomorrow",
      subtitulo: "Future World",
      tipo: "Espaço interativo",
      tipoPerfil: ["interativas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      descricao: "Área interativa localizada na saída do Spaceship Earth, com jogos e experiências tecnológicas sem fila.",
      icone: "🕹️",
      imagem: "project-tomorrow.jpg",
      regiao: "Future World",
      parque: "Epcot"
    },
    {
      id: "imageworks",
      titulo: "ImageWorks – The What-If Labs",
      subtitulo: "Future World",
      tipo: "Laboratório de experiências criativas",
      tipoPerfil: ["interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      descricao: "Área interativa ao final da atração de Figment, com estações criativas para experimentar sons, luzes e movimento.",
      icone: "🧠",
      imagem: "imageworks.jpg",
      regiao: "Future World",
      parque: "Epcot"
    },
    {
      id: "discovery-spot",
      titulo: "Discovery Spot",
      subtitulo: "Future World",
      tipo: "Ponto temático de descanso e explorações livres",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      descricao: "Espaço ao ar livre com jardins tecnológicos, fontes interativas e bancos sombreados. Ideal para relaxar e explorar livremente.",
      icone: "🧬",
      imagem: "discovery-spot.jpg",
      regiao: "Future World",
      parque: "Epcot"
    }
  ]
};
