ï»¿export const GrandAvenue = {
  parque: "Hollywood Studios",
  regiao: "Grand Avenue",
  latitude: 28.3551,
  longitude: -81.5615,
  descricao:
    "Inspirada em Los Angeles, a Grand Avenue oferece uma atmosfera urbana com opÃƒÂ§ÃƒÂµes gastronÃƒÂ´micas e atraÃƒÂ§ÃƒÂµes temÃƒÂ¡ticas como Muppets e ambientes modernos.",
  imagem: "grandavenue.png",
  atracoes: [
    {
      id: "muppet-vision-3d",
      titulo: "Muppet*Vision 3D",
      subtitulo: "Grand Avenue",
      tipo: "Show 3D com fantoches",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao:
        "EspetÃƒÂ¡culo divertido com os Muppets em 3D, efeitos especiais e piadas clÃƒÂ¡ssicas. Ideal para relaxar entre atraÃƒÂ§ÃƒÂµes mais intensas.",
      icone: "Ã°Å¸Å½Â­",
      imagem: "muppet-vision.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios"
    },
    {
      id: "baseline-tap-house",
      titulo: "Baseline Tap House",
      subtitulo: "Grand Avenue",
      tipo: "Bar e lanches",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 5,
      filaAceitavel: 10,
      idadeRecomendada: "Maiores de 18",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao:
        "Local moderno com cervejas artesanais e petiscos californianos. Excelente para adultos descansarem no fim do dia.",
      icone: "Ã°Å¸ÂÂº",
      imagem: "baseline-taphouse.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios"
    },
    {
      id: "grand-street-photo",
      titulo: "Grand Street Photo Spot",
      subtitulo: "Grand Avenue",
      tipo: "Ponto para fotos temÃƒÂ¡ticas",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "CenÃƒÂ¡rio de rua urbana ideal para tirar fotos estilosas. Detalhes remetem ÃƒÂ  arquitetura de Los Angeles.",
      icone: "Ã°Å¸â€œÂ¸",
      imagem: "grand-photo.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios"
    },
    {
      id: "grand-avenue-walk",
      titulo: "Passeio pela Grand Avenue",
      subtitulo: "Grand Avenue",
      tipo: "ExploraÃƒÂ§ÃƒÂ£o urbana",
      tipoPerfil: ["imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Caminhe por calÃƒÂ§adas arborizadas com detalhes arquitetÃƒÂ´nicos da CalifÃƒÂ³rnia. Uma pausa tranquila com clima de cidade grande.",
      icone: "Ã°Å¸Å¡Â¶Ã¢â‚¬ÂÃ¢â„¢â€šÃ¯Â¸Â",
      imagem: "grand-walk.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios"
    },
    {
      id: "muppet-shop",
      titulo: "Stage 1 Company Store",
      subtitulo: "Grand Avenue",
      tipo: "Loja temÃƒÂ¡tica dos Muppets",
      tipoPerfil: ["interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao:
        "Loja colorida com produtos dos Muppets, itens colecionÃƒÂ¡veis e brinquedos exclusivos. Ideal apÃƒÂ³s o show Muppet*Vision 3D.",
      icone: "Ã°Å¸â€ºÂÃ¯Â¸Â",
      imagem: "muppet-store.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios"
    }
  ]
};
