export const GrandAvenue = {
  parque: "Hollywood Studios",
  regiao: "Grand Avenue",
  latitude: 28.3551,
  longitude: -81.5615,
  descricao:
    "Inspirada em Los Angeles, a Grand Avenue oferece uma atmosfera urbana com opÃ§Ãµes gastronÃ´micas e atraÃ§Ãµes temÃ¡ticas como Muppets e ambientes modernos.",
  imagem: "grandavenue.png",
  atracoes: [
    {
      id: "muppet-vision-3d",
      titulo: "Muppet*Vision 3D",
      subtitulo: "Grand Avenue",
      tipo: "Show 3D com fantoches",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao:
        "EspetÃ¡culo divertido com os Muppets em 3D, efeitos especiais e piadas clÃ¡ssicas. Ideal para relaxar entre atraÃ§Ãµes mais intensas.",
      icone: "ðŸŽ­",
      imagem: "muppet-vision.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios"
    },
    {
      id: "baseline-tap-house",
      titulo: "Baseline Tap House",
      subtitulo: "Grand Avenue",
      tipo: "Bar e lanches",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 5,
      filaAceitavel: 10,
      idadeRecomendada: "Maiores de 18",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao:
        "Local moderno com cervejas artesanais e petiscos californianos. Excelente para adultos descansarem no fim do dia.",
      icone: "ðŸº",
      imagem: "baseline-taphouse.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios"
    },
    {
      id: "grand-street-photo",
      titulo: "Grand Street Photo Spot",
      subtitulo: "Grand Avenue",
      tipo: "Ponto para fotos temÃ¡ticas",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "CenÃ¡rio de rua urbana ideal para tirar fotos estilosas. Detalhes remetem Ã  arquitetura de Los Angeles.",
      icone: "ðŸ“¸",
      imagem: "grand-photo.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios"
    },
    {
      id: "grand-avenue-walk",
      titulo: "Passeio pela Grand Avenue",
      subtitulo: "Grand Avenue",
      tipo: "ExploraÃ§Ã£o urbana",
      tipoPerfil: ["imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Caminhe por calÃ§adas arborizadas com detalhes arquitetÃ´nicos da CalifÃ³rnia. Uma pausa tranquila com clima de cidade grande.",
      icone: "ðŸš¶â€â™‚ï¸",
      imagem: "grand-walk.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios"
    },
    {
      id: "muppet-shop",
      titulo: "Stage 1 Company Store",
      subtitulo: "Grand Avenue",
      tipo: "Loja temÃ¡tica dos Muppets",
      tipoPerfil: ["interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao:
        "Loja colorida com produtos dos Muppets, itens colecionÃ¡veis e brinquedos exclusivos. Ideal apÃ³s o show Muppet*Vision 3D.",
      icone: "ðŸ›ï¸",
      imagem: "muppet-store.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios"
    }
  ]
};
