ï»¿export const HollywoodBoulevard = {
  parque: "Hollywood Studios",
  regiao: "Hollywood Boulevard",
  latitude: 28.3575,
  longitude: -81.5586,
  descricao:
    "A avenida principal de entrada do parque, com teatros em estilo clÃƒÂ¡ssico de Hollywood, lojas temÃƒÂ¡ticas e acesso ÃƒÂ s principais ÃƒÂ¡reas do parque.",
  imagem: "hollywoodboulevard.png",
  atracoes: [
    {
      id: "runaway-railway",
      titulo: "Mickey & MinnieÃ¢â‚¬â„¢s Runaway Railway",
      subtitulo: "Hollywood Boulevard",
      tipo: "Dark ride imersiva",
      tipoPerfil: ["imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao:
        "Passeio inovador com projeÃƒÂ§ÃƒÂµes em 2.5D e trilha sonora animada. VocÃƒÂª entra em um desenho animado com Mickey e Minnie sem necessidade de ÃƒÂ³culos.",
      icone: "Ã°Å¸Å½Â¥",
      imagem: "runaway-railway.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    },
    {
      id: "red-car-trolley",
      titulo: "Red Car Trolley",
      subtitulo: "Hollywood Boulevard",
      tipo: "Passeio de bonde temÃƒÂ¡tico",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao:
        "Passeio tranquilo de bonde elÃƒÂ©trico estilo anos 30, ambientando o visitante na era dourada de Hollywood. Sem necessidade de fila.",
      icone: "Ã°Å¸Å¡â€¹",
      imagem: "red-car-trolley.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    },
    {
      id: "hollywood-character-spot",
      titulo: "Encontro com Personagens da Disney",
      subtitulo: "Hollywood Boulevard",
      tipo: "Ponto de foto e interaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao:
        "ÃƒÂrea para tirar fotos com personagens clÃƒÂ¡ssicos da Disney em figurinos de Hollywood, como Mickey, Minnie e Pateta. Sem fila, com horÃƒÂ¡rios programados.",
      icone: "Ã°Å¸â€œÂ¸",
      imagem: "hollywood-character-spot.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    },
    {
      id: "disney-studio-store",
      titulo: "Disney Studio Store",
      subtitulo: "Hollywood Boulevard",
      tipo: "Loja temÃƒÂ¡tica",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Loja principal da entrada com itens de filmes, pelÃƒÂºcias, roupas e souvenirs exclusivos. Ideal para compras antes ou depois das atraÃƒÂ§ÃƒÂµes.",
      icone: "Ã°Å¸â€ºÂÃ¯Â¸Â",
      imagem: "studio-store.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    },
    {
      id: "crossroads-of-the-world",
      titulo: "Crossroads of the World",
      subtitulo: "Hollywood Boulevard",
      tipo: "Ponto icÃƒÂ´nico e loja",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Localizado logo na entrada, este ponto icÃƒÂ´nico com a bola do Mickey marca o comeÃƒÂ§o da aventura e possui quiosques com acessÃƒÂ³rios e bebidas.",
      icone: "Ã°Å¸Å½Ë†",
      imagem: "crossroads.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    }
  ]
};
