export const HollywoodBoulevard = {
  parque: "Hollywood Studios",
  regiao: "Hollywood Boulevard",
  latitude: 28.3575,
  longitude: -81.5586,
  descricao:
    "A avenida principal de entrada do parque, com teatros em estilo clássico de Hollywood, lojas temáticas e acesso às principais áreas do parque.",
  imagem: "hollywoodboulevard.png",
  atracoes: [
    {
      id: "runaway-railway",
      titulo: "Mickey & Minnie’s Runaway Railway",
      subtitulo: "Hollywood Boulevard",
      tipo: "Dark ride imersiva",
      tipoPerfil: ["imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao:
        "Passeio inovador com projeções em 2.5D e trilha sonora animada. Você entra em um desenho animado com Mickey e Minnie sem necessidade de óculos.",
      icone: "🎥",
      imagem: "runaway-railway.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    },
    {
      id: "red-car-trolley",
      titulo: "Red Car Trolley",
      subtitulo: "Hollywood Boulevard",
      tipo: "Passeio de bonde temático",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao:
        "Passeio tranquilo de bonde elétrico estilo anos 30, ambientando o visitante na era dourada de Hollywood. Sem necessidade de fila.",
      icone: "🚋",
      imagem: "red-car-trolley.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    },
    {
      id: "hollywood-character-spot",
      titulo: "Encontro com Personagens da Disney",
      subtitulo: "Hollywood Boulevard",
      tipo: "Ponto de foto e interação",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao:
        "Área para tirar fotos com personagens clássicos da Disney em figurinos de Hollywood, como Mickey, Minnie e Pateta. Sem fila, com horários programados.",
      icone: "📸",
      imagem: "hollywood-character-spot.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    },
    {
      id: "disney-studio-store",
      titulo: "Disney Studio Store",
      subtitulo: "Hollywood Boulevard",
      tipo: "Loja temática",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Loja principal da entrada com itens de filmes, pelúcias, roupas e souvenirs exclusivos. Ideal para compras antes ou depois das atrações.",
      icone: "🛍️",
      imagem: "studio-store.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    },
    {
      id: "crossroads-of-the-world",
      titulo: "Crossroads of the World",
      subtitulo: "Hollywood Boulevard",
      tipo: "Ponto icônico e loja",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Localizado logo na entrada, este ponto icônico com a bola do Mickey marca o começo da aventura e possui quiosques com acessórios e bebidas.",
      icone: "🎈",
      imagem: "crossroads.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    }
  ]
};