export const HollywoodBoulevard = {
  parque: "Hollywood Studios",
  regiao: "Hollywood Boulevard",
  latitude: 28.3575,
  longitude: -81.5586,
  descricao:
    "A avenida principal de entrada do parque, com teatros em estilo clÃ¡ssico de Hollywood, lojas temÃ¡ticas e acesso Ã s principais Ã¡reas do parque.",
  imagem: "hollywoodboulevard.png",
  atracoes: [
    {
      id: "runaway-railway",
      titulo: "Mickey & Minnieâ€™s Runaway Railway",
      subtitulo: "Hollywood Boulevard",
      tipo: "Dark ride imersiva",
      tipoPerfil: ["imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao:
        "Passeio inovador com projeÃ§Ãµes em 2.5D e trilha sonora animada. VocÃª entra em um desenho animado com Mickey e Minnie sem necessidade de Ã³culos.",
      icone: "ðŸŽ¥",
      imagem: "runaway-railway.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    },
    {
      id: "red-car-trolley",
      titulo: "Red Car Trolley",
      subtitulo: "Hollywood Boulevard",
      tipo: "Passeio de bonde temÃ¡tico",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao:
        "Passeio tranquilo de bonde elÃ©trico estilo anos 30, ambientando o visitante na era dourada de Hollywood. Sem necessidade de fila.",
      icone: "ðŸš‹",
      imagem: "red-car-trolley.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    },
    {
      id: "hollywood-character-spot",
      titulo: "Encontro com Personagens da Disney",
      subtitulo: "Hollywood Boulevard",
      tipo: "Ponto de foto e interaÃ§Ã£o",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao:
        "Ãrea para tirar fotos com personagens clÃ¡ssicos da Disney em figurinos de Hollywood, como Mickey, Minnie e Pateta. Sem fila, com horÃ¡rios programados.",
      icone: "ðŸ“¸",
      imagem: "hollywood-character-spot.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    },
    {
      id: "disney-studio-store",
      titulo: "Disney Studio Store",
      subtitulo: "Hollywood Boulevard",
      tipo: "Loja temÃ¡tica",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Loja principal da entrada com itens de filmes, pelÃºcias, roupas e souvenirs exclusivos. Ideal para compras antes ou depois das atraÃ§Ãµes.",
      icone: "ðŸ›ï¸",
      imagem: "studio-store.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    },
    {
      id: "crossroads-of-the-world",
      titulo: "Crossroads of the World",
      subtitulo: "Hollywood Boulevard",
      tipo: "Ponto icÃ´nico e loja",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Localizado logo na entrada, este ponto icÃ´nico com a bola do Mickey marca o comeÃ§o da aventura e possui quiosques com acessÃ³rios e bebidas.",
      icone: "ðŸŽˆ",
      imagem: "crossroads.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios"
    }
  ]
};
