export const StarWars = {
  parque: "Hollywood Studios",
  regiao: "Star Wars: Galaxyâ€™s Edge",
  latitude: 28.3541,
  longitude: -81.5909,
  descricao:
    "Ãrea totalmente imersiva que recria o planeta Batuu, com naves em escala real, lojas temÃ¡ticas, interaÃ§Ãµes com personagens e duas atraÃ§Ãµes Ã©picas do universo Star Wars.",
  imagem: "starwarsgalaxyedge.png",
  atracoes: [
    {
      id: "rise-of-the-resistance",
      titulo: "Star Wars: Rise of the Resistance",
      subtitulo: "Star Wars: Galaxyâ€™s Edge",
      tipo: "Aventura imersiva com mÃºltiplos sistemas",
      tipoPerfil: ["imersivas", "tematicas"],
      alturaMinima: 102,
      filaExpress: false,
      tempoMedioFila: 80,
      filaAceitavel: 50,
      idadeRecomendada: "7+",
      turnoRecomendado: "manha",
      descricao:
        "Uma das experiÃªncias mais tecnolÃ³gicas da Disney. VocÃª faz parte da ResistÃªncia em uma missÃ£o contra a Primeira Ordem, com mÃºltiplos ambientes e efeitos surpreendentes.",
      icone: "ðŸš€",
      imagem: "rise-of-the-resistance.jpg",
      regiao: "Star Wars: Galaxyâ€™s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3545,
      longitude: -81.5914
    },
    {
      id: "millennium-falcon-smugglers-run",
      titulo: "Millennium Falcon: Smugglers Run",
      subtitulo: "Star Wars: Galaxyâ€™s Edge",
      tipo: "Simulador interativo",
      tipoPerfil: ["interativas", "imersivas"],
      alturaMinima: 97,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "6+",
      turnoRecomendado: "tarde",
      descricao:
        "Pilotar a nave mais famosa da galÃ¡xia em uma missÃ£o como piloto, atirador ou engenheiro. A atraÃ§Ã£o Ã© interativa e muda conforme o desempenho do grupo.",
      icone: "ðŸ›¸",
      imagem: "millennium-falcon.jpg",
      regiao: "Star Wars: Galaxyâ€™s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3537,
      longitude: -81.5912
    },
    {
      id: "encontro-chewbacca",
      titulo: "Encontro com Chewbacca",
      subtitulo: "Star Wars: Galaxyâ€™s Edge",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Encontre o lendÃ¡rio Chewbacca em Batuu para tirar fotos e interagir. Ele costuma aparecer prÃ³ximo Ã  Ã¡rea da ResistÃªncia.",
      icone: "ðŸ§¸",
      imagem: "chewbacca.jpg",
      regiao: "Star Wars: Galaxyâ€™s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3542,
      longitude: -81.5908
    },
    {
      id: "encontro-kylo-ren",
      titulo: "Encontro com Kylo Ren",
      subtitulo: "Star Wars: Galaxyâ€™s Edge",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao:
        "Kylo Ren aparece em patrulhas e interaÃ§Ãµes intensas com visitantes. Prepare-se para sentir a forÃ§a do lado sombrio.",
      icone: "ðŸ–¤",
      imagem: "kylo-ren.jpg",
      regiao: "Star Wars: Galaxyâ€™s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3540,
      longitude: -81.5906
    },
    {
      id: "patrulha-stormtroopers",
      titulo: "Patrulha de Stormtroopers",
      subtitulo: "Star Wars: Galaxyâ€™s Edge",
      tipo: "InteraÃ§Ã£o temÃ¡tica ao ar livre",
      tipoPerfil: ["tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Stormtroopers circulam pela Ã¡rea de Galaxy's Edge interagindo com os visitantes de forma divertida (e Ã s vezes intimidadora).",
      icone: "âš”ï¸",
      imagem: "stormtroopers.jpg",
      regiao: "Star Wars: Galaxyâ€™s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3543,
      longitude: -81.5911
    }
  ]
};
