ï»¿export const StarWars = {
  parque: "Hollywood Studios",
  regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
  latitude: 28.3541,
  longitude: -81.5909,
  descricao:
    "ÃƒÂrea totalmente imersiva que recria o planeta Batuu, com naves em escala real, lojas temÃƒÂ¡ticas, interaÃƒÂ§ÃƒÂµes com personagens e duas atraÃƒÂ§ÃƒÂµes ÃƒÂ©picas do universo Star Wars.",
  imagem: "starwarsgalaxyedge.png",
  atracoes: [
    {
      id: "rise-of-the-resistance",
      titulo: "Star Wars: Rise of the Resistance",
      subtitulo: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      tipo: "Aventura imersiva com mÃƒÂºltiplos sistemas",
      tipoPerfil: ["imersivas", "tematicas"],
      alturaMinima: 102,
      filaExpress: false,
      tempoMedioFila: 80,
      filaAceitavel: 50,
      idadeRecomendada: "7+",
      turnoRecomendado: "manha",
      descricao:
        "Uma das experiÃƒÂªncias mais tecnolÃƒÂ³gicas da Disney. VocÃƒÂª faz parte da ResistÃƒÂªncia em uma missÃƒÂ£o contra a Primeira Ordem, com mÃƒÂºltiplos ambientes e efeitos surpreendentes.",
      icone: "Ã°Å¸Å¡â‚¬",
      imagem: "rise-of-the-resistance.jpg",
      regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3545,
      longitude: -81.5914
    },
    {
      id: "millennium-falcon-smugglers-run",
      titulo: "Millennium Falcon: Smugglers Run",
      subtitulo: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      tipo: "Simulador interativo",
      tipoPerfil: ["interativas", "imersivas"],
      alturaMinima: 97,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "6+",
      turnoRecomendado: "tarde",
      descricao:
        "Pilotar a nave mais famosa da galÃƒÂ¡xia em uma missÃƒÂ£o como piloto, atirador ou engenheiro. A atraÃƒÂ§ÃƒÂ£o ÃƒÂ© interativa e muda conforme o desempenho do grupo.",
      icone: "Ã°Å¸â€ºÂ¸",
      imagem: "millennium-falcon.jpg",
      regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3537,
      longitude: -81.5912
    },
    {
      id: "encontro-chewbacca",
      titulo: "Encontro com Chewbacca",
      subtitulo: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Encontre o lendÃƒÂ¡rio Chewbacca em Batuu para tirar fotos e interagir. Ele costuma aparecer prÃƒÂ³ximo ÃƒÂ  ÃƒÂ¡rea da ResistÃƒÂªncia.",
      icone: "Ã°Å¸Â§Â¸",
      imagem: "chewbacca.jpg",
      regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3542,
      longitude: -81.5908
    },
    {
      id: "encontro-kylo-ren",
      titulo: "Encontro com Kylo Ren",
      subtitulo: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao:
        "Kylo Ren aparece em patrulhas e interaÃƒÂ§ÃƒÂµes intensas com visitantes. Prepare-se para sentir a forÃƒÂ§a do lado sombrio.",
      icone: "Ã°Å¸â€“Â¤",
      imagem: "kylo-ren.jpg",
      regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3540,
      longitude: -81.5906
    },
    {
      id: "patrulha-stormtroopers",
      titulo: "Patrulha de Stormtroopers",
      subtitulo: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      tipo: "InteraÃƒÂ§ÃƒÂ£o temÃƒÂ¡tica ao ar livre",
      tipoPerfil: ["tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Stormtroopers circulam pela ÃƒÂ¡rea de Galaxy's Edge interagindo com os visitantes de forma divertida (e ÃƒÂ s vezes intimidadora).",
      icone: "Ã¢Å¡â€Ã¯Â¸Â",
      imagem: "stormtroopers.jpg",
      regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3543,
      longitude: -81.5911
    }
  ]
};
