export const StarWars = {
  parque: "Hollywood Studios",
  regiao: "Star Wars: Galaxy’s Edge",
  latitude: 28.3541,
  longitude: -81.5909,
  descricao:
    "Área totalmente imersiva que recria o planeta Batuu, com naves em escala real, lojas temáticas, interações com personagens e duas atrações épicas do universo Star Wars.",
  imagem: "starwarsgalaxyedge.png",
  atracoes: [
    {
      id: "rise-of-the-resistance",
      titulo: "Star Wars: Rise of the Resistance",
      subtitulo: "Star Wars: Galaxy’s Edge",
      tipo: "Aventura imersiva com múltiplos sistemas",
      tipoPerfil: ["imersivas", "tematicas"],
      alturaMinima: 102,
      filaExpress: false,
      tempoMedioFila: 80,
      filaAceitavel: 50,
      idadeRecomendada: "7+",
      turnoRecomendado: "manha",
      descricao:
        "Uma das experiências mais tecnológicas da Disney. Você faz parte da Resistência em uma missão contra a Primeira Ordem, com múltiplos ambientes e efeitos surpreendentes.",
      icone: "🚀",
      imagem: "rise-of-the-resistance.jpg",
      regiao: "Star Wars: Galaxy’s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3545,
      longitude: -81.5914
    },
    {
      id: "millennium-falcon-smugglers-run",
      titulo: "Millennium Falcon: Smugglers Run",
      subtitulo: "Star Wars: Galaxy’s Edge",
      tipo: "Simulador interativo",
      tipoPerfil: ["interativas", "imersivas"],
      alturaMinima: 97,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "6+",
      turnoRecomendado: "tarde",
      descricao:
        "Pilotar a nave mais famosa da galáxia em uma missão como piloto, atirador ou engenheiro. A atração é interativa e muda conforme o desempenho do grupo.",
      icone: "🛸",
      imagem: "millennium-falcon.jpg",
      regiao: "Star Wars: Galaxy’s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3537,
      longitude: -81.5912
    },
    {
      id: "encontro-chewbacca",
      titulo: "Encontro com Chewbacca",
      subtitulo: "Star Wars: Galaxy’s Edge",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Encontre o lendário Chewbacca em Batuu para tirar fotos e interagir. Ele costuma aparecer próximo à área da Resistência.",
      icone: "🧸",
      imagem: "chewbacca.jpg",
      regiao: "Star Wars: Galaxy’s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3542,
      longitude: -81.5908
    },
    {
      id: "encontro-kylo-ren",
      titulo: "Encontro com Kylo Ren",
      subtitulo: "Star Wars: Galaxy’s Edge",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao:
        "Kylo Ren aparece em patrulhas e interações intensas com visitantes. Prepare-se para sentir a força do lado sombrio.",
      icone: "🖤",
      imagem: "kylo-ren.jpg",
      regiao: "Star Wars: Galaxy’s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3540,
      longitude: -81.5906
    },
    {
      id: "patrulha-stormtroopers",
      titulo: "Patrulha de Stormtroopers",
      subtitulo: "Star Wars: Galaxy’s Edge",
      tipo: "Interação temática ao ar livre",
      tipoPerfil: ["tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Stormtroopers circulam pela área de Galaxy's Edge interagindo com os visitantes de forma divertida (e às vezes intimidadora).",
      icone: "⚔️",
      imagem: "stormtroopers.jpg",
      regiao: "Star Wars: Galaxy’s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3543,
      longitude: -81.5911
    }
  ]
};
