export const SunsetBoulevard = {
  parque: "Hollywood Studios",
  regiao: "Sunset Boulevard",
  latitude: 28.3554,
  longitude: -81.5618,
  descricao:
    "Avenida com visual de cinema clássico que leva a atrações cheias de adrenalina, como a icônica Tower of Terror, shows musicais e encontros com personagens.",
  imagem: "sunsetboulevard.png",
  atracoes: [
    {
      id: "tower-of-terror",
      titulo: "The Twilight Zone Tower of Terror",
      subtitulo: "Sunset Boulevard",
      tipo: "Queda livre temática",
      tipoPerfil: ["radicais", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 55,
      filaAceitavel: 35,
      idadeRecomendada: "8+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao:
        "Entre em um hotel mal-assombrado e despenca em elevadores desgovernados. Combinação perfeita de susto e diversão.",
      icone: "🏨",
      imagem: "tower-of-terror.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3557,
      longitude: -81.5619
    },
    {
      id: "rockn-roller-coaster",
      titulo: "Rock ‘n’ Roller Coaster Starring Aerosmith",
      subtitulo: "Sunset Boulevard",
      tipo: "Montanha-russa no escuro",
      tipoPerfil: ["radicais", "imersivas"],
      alturaMinima: 122,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 35,
      idadeRecomendada: "9+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao:
        "Montanha-russa de alta velocidade com lançamentos rápidos e looping ao som de Aerosmith. Uma das mais intensas da Disney.",
      icone: "🎸",
      imagem: "rockn-roller.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3561,
      longitude: -81.5614
    },
    {
      id: "beauty-and-the-beast",
      titulo: "Beauty and the Beast – Live on Stage",
      subtitulo: "Sunset Boulevard",
      tipo: "Show musical ao vivo",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Apresentação musical ao vivo com figurinos belíssimos e performances emocionantes. Ocorre em horários específicos.",
      icone: "🌹",
      imagem: "beauty-and-the-beast.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3550,
      longitude: -81.5620
    },
    {
      id: "encontro-com-bela",
      titulo: "Encontro com a Bela",
      subtitulo: "Sunset Boulevard",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "personagens"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Encontro com a princesa Bela vestida com seu traje clássico dourado. Localizado nas proximidades do teatro da Bela e a Fera.",
      icone: "👸",
      imagem: "encontro-bela.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3549,
      longitude: -81.5621
    },
    {
      id: "encontro-com-mickey-sorcerer",
      titulo: "Encontro com Mickey Feiticeiro",
      subtitulo: "Sunset Boulevard",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "personagens"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao:
        "Tire fotos com o Mickey vestido como feiticeiro do Fantasia, com seu chapéu azul estrelado. Encontro mágico e memorável.",
      icone: "🧙‍♂️",
      imagem: "mickey-feiticeiro.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3553,
      longitude: -81.5623
    }
  ]
};
