ï»¿export const SunsetBoulevard = {
  parque: "Hollywood Studios",
  regiao: "Sunset Boulevard",
  latitude: 28.3554,
  longitude: -81.5618,
  descricao:
    "Avenida com visual de cinema clÃƒÂ¡ssico que leva a atraÃƒÂ§ÃƒÂµes cheias de adrenalina, como a icÃƒÂ´nica Tower of Terror, shows musicais e encontros com personagens.",
  imagem: "sunsetboulevard.png",
  atracoes: [
    {
      id: "tower-of-terror",
      titulo: "The Twilight Zone Tower of Terror",
      subtitulo: "Sunset Boulevard",
      tipo: "Queda livre temÃƒÂ¡tica",
      tipoPerfil: ["radicais", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 55,
      filaAceitavel: 35,
      idadeRecomendada: "8+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao:
        "Entre em um hotel mal-assombrado e despenca em elevadores desgovernados. CombinaÃƒÂ§ÃƒÂ£o perfeita de susto e diversÃƒÂ£o.",
      icone: "Ã°Å¸ÂÂ¨",
      imagem: "tower-of-terror.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3557,
      longitude: -81.5619
    },
    {
      id: "rockn-roller-coaster",
      titulo: "Rock Ã¢â‚¬ËœnÃ¢â‚¬â„¢ Roller Coaster Starring Aerosmith",
      subtitulo: "Sunset Boulevard",
      tipo: "Montanha-russa no escuro",
      tipoPerfil: ["radicais", "imersivas"],
      alturaMinima: 122,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 35,
      idadeRecomendada: "9+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao:
        "Montanha-russa de alta velocidade com lanÃƒÂ§amentos rÃƒÂ¡pidos e looping ao som de Aerosmith. Uma das mais intensas da Disney.",
      icone: "Ã°Å¸Å½Â¸",
      imagem: "rockn-roller.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3561,
      longitude: -81.5614
    },
    {
      id: "beauty-and-the-beast",
      titulo: "Beauty and the Beast Ã¢â‚¬â€œ Live on Stage",
      subtitulo: "Sunset Boulevard",
      tipo: "Show musical ao vivo",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "ApresentaÃƒÂ§ÃƒÂ£o musical ao vivo com figurinos belÃƒÂ­ssimos e performances emocionantes. Ocorre em horÃƒÂ¡rios especÃƒÂ­ficos.",
      icone: "Ã°Å¸Å’Â¹",
      imagem: "beauty-and-the-beast.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3550,
      longitude: -81.5620
    },
    {
      id: "encontro-com-bela",
      titulo: "Encontro com a Bela",
      subtitulo: "Sunset Boulevard",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "personagens"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao:
        "Encontro com a princesa Bela vestida com seu traje clÃƒÂ¡ssico dourado. Localizado nas proximidades do teatro da Bela e a Fera.",
      icone: "Ã°Å¸â€˜Â¸",
      imagem: "encontro-bela.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3549,
      longitude: -81.5621
    },
    {
      id: "encontro-com-mickey-sorcerer",
      titulo: "Encontro com Mickey Feiticeiro",
      subtitulo: "Sunset Boulevard",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "personagens"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao:
        "Tire fotos com o Mickey vestido como feiticeiro do Fantasia, com seu chapÃƒÂ©u azul estrelado. Encontro mÃƒÂ¡gico e memorÃƒÂ¡vel.",
      icone: "Ã°Å¸Â§â„¢Ã¢â‚¬ÂÃ¢â„¢â€šÃ¯Â¸Â",
      imagem: "mickey-feiticeiro.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3553,
      longitude: -81.5623
    }
  ]
};
