export const Tomorrowland = {
  parque: "Magic Kingdom",
  regiao: "Tomorrowland",
  latitude: 28.4196,
  longitude: -81.5773,
  descricao:
    "Ãrea futurista repleta de atraÃ§Ãµes espaciais e tecnolÃ³gicas. Uma viagem ao futuro com simuladores, aventuras interativas e montanhas-russas no escuro.",
  imagem: "tomorrowland.png",
  atracoes: [
    {
      id: "space-mountain",
      titulo: "Space Mountain",
      subtitulo: "Tomorrowland",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "imersivas"],
      alturaMinima: 112,
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "manha",
      atracaoSemFila: false,
      descricao:
        "Montanha-russa no escuro com tema espacial, curvas fechadas e sensaÃ§Ã£o de velocidade. Uma das mais clÃ¡ssicas da Disney.",
      icone: "ðŸš€",
      imagem: "space-mountain.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4198,
      longitude: -81.5771
    },
    {
      id: "buzz-lightyear",
      titulo: "Buzz Lightyearâ€™s Space Ranger Spin",
      subtitulo: "Tomorrowland",
      tipo: "Interativa",
      tipoPerfil: ["interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 30,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      descricao:
        "AtraÃ§Ã£o interativa com canhÃµes laser para derrotar o imperador Zurg e acumular pontos. DiversÃ£o para todas as idades.",
      icone: "ðŸ”«",
      imagem: "buzz-lightyear.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4193,
      longitude: -81.5774
    },
    {
      id: "astro-orbiter",
      titulo: "Astro Orbiter",
      subtitulo: "Tomorrowland",
      tipo: "Brinquedo giratÃ³rio aÃ©reo",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 83,
      filaExpress: false,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      atracaoSemFila: false,
      descricao:
        "Gire alto pelos cÃ©us de Tomorrowland com vista panorÃ¢mica do parque. Indicado para quem curte brinquedos clÃ¡ssicos com emoÃ§Ã£o leve.",
      icone: "ðŸª",
      imagem: "astro-orbiter.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4192,
      longitude: -81.5772
    },
    {
      id: "tomorrowland-speedway",
      titulo: "Tomorrowland Speedway",
      subtitulo: "Tomorrowland",
      tipo: "Pista de carrinhos",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 82,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      descricao:
        "Dirija um carrinho em uma pista estilizada do futuro. As crianÃ§as adoram a sensaÃ§Ã£o de pilotar sozinhas, acompanhadas por um adulto.",
      icone: "ðŸ",
      imagem: "tomorrowland-speedway.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4186,
      longitude: -81.5765
    },
    {
      id: "peoplemover",
      titulo: "Tomorrowland Transit Authority PeopleMover",
      subtitulo: "Tomorrowland",
      tipo: "Passeio panorÃ¢mico elevado",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      descricao:
        "Passeio relaxante por Tomorrowland com vista das atraÃ§Ãµes, incluindo trechos dentro da Space Mountain. Sem fila na maioria das vezes.",
      icone: "ðŸš",
      imagem: "peoplemover.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4195,
      longitude: -81.5770
    },
    {
      id: "carousel-of-progress",
      titulo: "Walt Disneyâ€™s Carousel of Progress",
      subtitulo: "Tomorrowland",
      tipo: "Show com animatrÃ´nicos",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      atracaoSemFila: true,
      descricao:
        "EspetÃ¡culo clÃ¡ssico com animatrÃ´nicos que contam a evoluÃ§Ã£o da tecnologia ao longo do sÃ©culo. Homenagem nostÃ¡lgica Ã  visÃ£o de futuro da Disney.",
      icone: "ðŸŽ¡",
      imagem: "carousel-progress.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4197,
      longitude: -81.5775
    },
    {
      id: "monsters-inc-laugh-floor",
      titulo: "Monsters, Inc. Laugh Floor",
      subtitulo: "Tomorrowland",
      tipo: "Show interativo de comÃ©dia",
      tipoPerfil: ["interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      atracaoSemFila: false,
      descricao:
        "Show de stand-up com os monstros de Monstros S.A., com piadas e interaÃ§Ã£o ao vivo com a plateia. DiversÃ£o para rir com a famÃ­lia.",
      icone: "ðŸ˜‚",
      imagem: "laugh-floor.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4190,
      longitude: -81.5773
    }
  ]
};
