ï»¿export const Tomorrowland = {
  parque: "Magic Kingdom",
  regiao: "Tomorrowland",
  latitude: 28.4196,
  longitude: -81.5773,
  descricao:
    "ÃƒÂrea futurista repleta de atraÃƒÂ§ÃƒÂµes espaciais e tecnolÃƒÂ³gicas. Uma viagem ao futuro com simuladores, aventuras interativas e montanhas-russas no escuro.",
  imagem: "tomorrowland.png",
  atracoes: [
    {
      id: "space-mountain",
      titulo: "Space Mountain",
      subtitulo: "Tomorrowland",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "imersivas"],
      alturaMinima: 112,
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "manha",
      atracaoSemFila: false,
      descricao:
        "Montanha-russa no escuro com tema espacial, curvas fechadas e sensaÃƒÂ§ÃƒÂ£o de velocidade. Uma das mais clÃƒÂ¡ssicas da Disney.",
      icone: "Ã°Å¸Å¡â‚¬",
      imagem: "space-mountain.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4198,
      longitude: -81.5771
    },
    {
      id: "buzz-lightyear",
      titulo: "Buzz LightyearÃ¢â‚¬â„¢s Space Ranger Spin",
      subtitulo: "Tomorrowland",
      tipo: "Interativa",
      tipoPerfil: ["interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 30,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      descricao:
        "AtraÃƒÂ§ÃƒÂ£o interativa com canhÃƒÂµes laser para derrotar o imperador Zurg e acumular pontos. DiversÃƒÂ£o para todas as idades.",
      icone: "Ã°Å¸â€Â«",
      imagem: "buzz-lightyear.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4193,
      longitude: -81.5774
    },
    {
      id: "astro-orbiter",
      titulo: "Astro Orbiter",
      subtitulo: "Tomorrowland",
      tipo: "Brinquedo giratÃƒÂ³rio aÃƒÂ©reo",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 83,
      filaExpress: false,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      atracaoSemFila: false,
      descricao:
        "Gire alto pelos cÃƒÂ©us de Tomorrowland com vista panorÃƒÂ¢mica do parque. Indicado para quem curte brinquedos clÃƒÂ¡ssicos com emoÃƒÂ§ÃƒÂ£o leve.",
      icone: "Ã°Å¸ÂªÂ",
      imagem: "astro-orbiter.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4192,
      longitude: -81.5772
    },
    {
      id: "tomorrowland-speedway",
      titulo: "Tomorrowland Speedway",
      subtitulo: "Tomorrowland",
      tipo: "Pista de carrinhos",
      tipoPerfil: ["familiares", "interativas"],
      alturaMinima: 82,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      descricao:
        "Dirija um carrinho em uma pista estilizada do futuro. As crianÃƒÂ§as adoram a sensaÃƒÂ§ÃƒÂ£o de pilotar sozinhas, acompanhadas por um adulto.",
      icone: "Ã°Å¸ÂÂ",
      imagem: "tomorrowland-speedway.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4186,
      longitude: -81.5765
    },
    {
      id: "peoplemover",
      titulo: "Tomorrowland Transit Authority PeopleMover",
      subtitulo: "Tomorrowland",
      tipo: "Passeio panorÃƒÂ¢mico elevado",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      descricao:
        "Passeio relaxante por Tomorrowland com vista das atraÃƒÂ§ÃƒÂµes, incluindo trechos dentro da Space Mountain. Sem fila na maioria das vezes.",
      icone: "Ã°Å¸Å¡Â",
      imagem: "peoplemover.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4195,
      longitude: -81.5770
    },
    {
      id: "carousel-of-progress",
      titulo: "Walt DisneyÃ¢â‚¬â„¢s Carousel of Progress",
      subtitulo: "Tomorrowland",
      tipo: "Show com animatrÃƒÂ´nicos",
      tipoPerfil: ["tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      atracaoSemFila: true,
      descricao:
        "EspetÃƒÂ¡culo clÃƒÂ¡ssico com animatrÃƒÂ´nicos que contam a evoluÃƒÂ§ÃƒÂ£o da tecnologia ao longo do sÃƒÂ©culo. Homenagem nostÃƒÂ¡lgica ÃƒÂ  visÃƒÂ£o de futuro da Disney.",
      icone: "Ã°Å¸Å½Â¡",
      imagem: "carousel-progress.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4197,
      longitude: -81.5775
    },
    {
      id: "monsters-inc-laugh-floor",
      titulo: "Monsters, Inc. Laugh Floor",
      subtitulo: "Tomorrowland",
      tipo: "Show interativo de comÃƒÂ©dia",
      tipoPerfil: ["interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      atracaoSemFila: false,
      descricao:
        "Show de stand-up com os monstros de Monstros S.A., com piadas e interaÃƒÂ§ÃƒÂ£o ao vivo com a plateia. DiversÃƒÂ£o para rir com a famÃƒÂ­lia.",
      icone: "Ã°Å¸Ëœâ€š",
      imagem: "laugh-floor.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4190,
      longitude: -81.5773
    }
  ]
};
