export const WorldNature = {
  parque: "Epcot",
  regiao: "World Nature",
  latitude: 28.3730,
  longitude: -81.5510,
  descricao:
    "Ãrea voltada para experiÃªncias sensoriais, contato com a natureza, oceanos e sustentabilidade. Ideal para todas as idades, com atraÃ§Ãµes relaxantes e educativas.",
  imagem: "worldnature.png",
  atracoes: [
    {
      id: "soarin-around-the-world",
      titulo: "Soarinâ€™ Around the World",
      subtitulo: "World Nature",
      tipo: "Simulador de voo panorÃ¢mico",
      tipoPerfil: ["imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 35,
      idadeRecomendada: "6+",
      turnoRecomendado: "manha",
      atracaoSemFila: false,
      descricao:
        "Simulador de voo panorÃ¢mico com tela IMAX, aromas e vento nos pÃ©s que leva os visitantes a sobrevoar paisagens incrÃ­veis pelo mundo.",
      icone: "ðŸª‚",
      imagem: "soarin.jpg",
      regiao: "World Nature",
      parque: "Epcot",
      latitude: 28.3726,
      longitude: -81.5502
    },
    {
      id: "the-seas-nemo-friends",
      titulo: "The Seas with Nemo & Friends",
      subtitulo: "World Nature",
      tipo: "Passeio de carrinho subaquÃ¡tico",
      tipoPerfil: ["familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      personagemPrincipal: "Nemo, Dory, Marlin",
      atracaoSemFila: false,
      descricao:
        "Passeio leve por ambientes subaquÃ¡ticos com Nemo e seus amigos, terminando em um aquÃ¡rio real com peixes, golfinhos e tartarugas.",
      icone: "ðŸ ",
      imagem: "nemo-friends.jpg",
      regiao: "World Nature",
      parque: "Epcot",
      latitude: 28.3750,
      longitude: -81.5508
    },
    {
      id: "living-with-the-land",
      titulo: "Living with the Land",
      subtitulo: "World Nature",
      tipo: "Passeio educativo de barco",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      descricao:
        "Passeio de barco pelas estufas e sistemas de cultivo do pavilhÃ£o The Land, com foco em sustentabilidade e inovaÃ§Ã£o agrÃ­cola.",
      icone: "ðŸŒ¿",
      imagem: "living-with-the-land.jpg",
      regiao: "World Nature",
      parque: "Epcot",
      latitude: 28.3729,
      longitude: -81.5501
    },
    {
      id: "turtle-talk-with-crush",
      titulo: "Turtle Talk with Crush",
      subtitulo: "World Nature",
      tipo: "Show interativo digital",
      tipoPerfil: ["interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      personagemPrincipal: "Crush",
      atracaoSemFila: true,
      descricao:
        "Show interativo com o personagem Crush (projeÃ§Ã£o digital), que conversa ao vivo com o pÃºblico de forma divertida. Apresentado em horÃ¡rios especÃ­ficos.",
      icone: "ðŸ¢",
      imagem: "turtle-talk.jpg",
      regiao: "World Nature",
      parque: "Epcot",
      latitude: 28.3747,
      longitude: -81.5506
    },
    {
      id: "seabase-aquarium",
      titulo: "SeaBase Aquarium",
      subtitulo: "World Nature",
      tipo: "AquÃ¡rio de observaÃ§Ã£o",
      tipoPerfil: ["familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "Grande aquÃ¡rio com vÃ¡rias espÃ©cies marinhas, incluindo golfinhos, tubarÃµes e peixes tropicais. Livre para explorar no seu tempo.",
      icone: "ðŸ¬",
      imagem: "seabase.jpg",
      regiao: "World Nature",
      parque: "Epcot",
      latitude: 28.3749,
      longitude: -81.5507
    },
    {
      id: "awesome-planet",
      titulo: "Awesome Planet",
      subtitulo: "World Nature",
      tipo: "Filme educativo",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      atracaoSemFila: true,
      descricao:
        "Filme sobre o planeta Terra com imagens em alta definiÃ§Ã£o e efeitos sensoriais. Educativo e exibido em sessÃµes durante o dia.",
      icone: "ðŸŒŽ",
      imagem: "awesome-planet.jpg",
      regiao: "World Nature",
      parque: "Epcot",
      latitude: 28.3728,
      longitude: -81.5500
    }
  ]
};
