export const WorldCelebration = {
  parque: "Epcot",
  regiao: "World Celebration",
  latitude: 28.3745,
  longitude: -81.5494,
  descricao:
    "Ãrea central do Epcot que celebra a criatividade, a conexÃ£o entre pessoas e ideias. Aqui estÃ£o espaÃ§os tranquilos, atraÃ§Ãµes inspiradoras, homenagens a Walt Disney e experiÃªncias interativas.",
  imagem: "worldcelebration.png",
  atracoes: [
    {
      id: "spaceship-earth",
      titulo: "Spaceship Earth",
      subtitulo: "World Celebration",
      tipo: "Dark ride educativa",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      atracaoSemFila: false,
      descricao:
        "Viagem no tempo dentro da icÃ´nica esfera do Epcot, mostrando a evoluÃ§Ã£o da comunicaÃ§Ã£o humana com narraÃ§Ã£o envolvente e cenÃ¡rios imersivos.",
      icone: "ðŸŒ",
      imagem: "spaceship-earth.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3747,
      longitude: -81.5497
    },
    {
      id: "dreamers-point",
      titulo: "Dreamers Point",
      subtitulo: "World Celebration",
      tipo: "EspaÃ§o temÃ¡tico e homenagem",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "Escultura e Ã¡rea contemplativa em homenagem a Walt Disney, cercada por jardins e vista privilegiada da Spaceship Earth. Sem fila, ideal para uma pausa.",
      icone: "ðŸª‘",
      imagem: "dreamers-point.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3746,
      longitude: -81.5494
    },
    {
      id: "communicore-plaza",
      titulo: "CommuniCore Plaza",
      subtitulo: "World Celebration",
      tipo: "Ãrea para eventos e shows ao vivo",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      atracaoSemFila: true,
      descricao:
        "PraÃ§a interativa e palco para eventos ao ar livre e shows sazonais, com espaÃ§os abertos e Ã¡reas de descanso. Sem filas, com horÃ¡rios programados.",
      icone: "ðŸŽ¤",
      imagem: "communicore-plaza.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3744,
      longitude: -81.5492
    },
    {
      id: "journey-of-water",
      titulo: "Journey of Water, Inspired by Moana",
      subtitulo: "World Celebration",
      tipo: "Trilha interativa com Ã¡gua",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      personagemPrincipal: "Moana",
      descricao:
        "Caminho interativo inspirado em Moana, com fontes, efeitos sensoriais e atividades com Ã¡gua para todas as idades. Uma experiÃªncia educativa e divertida.",
      icone: "ðŸ’§",
      imagem: "journey-of-water.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3741,
      longitude: -81.5489
    },
    {
      id: "walt-disney-dreamers-statue",
      titulo: "EstÃ¡tua Walt the Dreamer",
      subtitulo: "World Celebration",
      tipo: "Ponto de foto e contemplaÃ§Ã£o",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      atracaoSemFila: true,
      descricao:
        "Escultura de Walt Disney sentado, localizada no Dreamers Point. Local ideal para fotos e reflexÃ£o. Acesso livre, sem fila.",
      icone: "ðŸ“¸",
      imagem: "walt-dreamer.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3746,
      longitude: -81.5495
    }
  ]
};
