ï»¿export const WorldCelebration = {
  parque: "Epcot",
  regiao: "World Celebration",
  latitude: 28.3745,
  longitude: -81.5494,
  descricao:
    "ÃƒÂrea central do Epcot que celebra a criatividade, a conexÃƒÂ£o entre pessoas e ideias. Aqui estÃƒÂ£o espaÃƒÂ§os tranquilos, atraÃƒÂ§ÃƒÂµes inspiradoras, homenagens a Walt Disney e experiÃƒÂªncias interativas.",
  imagem: "worldcelebration.png",
  atracoes: [
    {
      id: "spaceship-earth",
      titulo: "Spaceship Earth",
      subtitulo: "World Celebration",
      tipo: "Dark ride educativa",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      atracaoSemFila: false,
      descricao:
        "Viagem no tempo dentro da icÃƒÂ´nica esfera do Epcot, mostrando a evoluÃƒÂ§ÃƒÂ£o da comunicaÃƒÂ§ÃƒÂ£o humana com narraÃƒÂ§ÃƒÂ£o envolvente e cenÃƒÂ¡rios imersivos.",
      icone: "Ã°Å¸Å’Â",
      imagem: "spaceship-earth.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3747,
      longitude: -81.5497
    },
    {
      id: "dreamers-point",
      titulo: "Dreamers Point",
      subtitulo: "World Celebration",
      tipo: "EspaÃƒÂ§o temÃƒÂ¡tico e homenagem",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "Escultura e ÃƒÂ¡rea contemplativa em homenagem a Walt Disney, cercada por jardins e vista privilegiada da Spaceship Earth. Sem fila, ideal para uma pausa.",
      icone: "Ã°Å¸Âªâ€˜",
      imagem: "dreamers-point.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3746,
      longitude: -81.5494
    },
    {
      id: "communicore-plaza",
      titulo: "CommuniCore Plaza",
      subtitulo: "World Celebration",
      tipo: "ÃƒÂrea para eventos e shows ao vivo",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      atracaoSemFila: true,
      descricao:
        "PraÃƒÂ§a interativa e palco para eventos ao ar livre e shows sazonais, com espaÃƒÂ§os abertos e ÃƒÂ¡reas de descanso. Sem filas, com horÃƒÂ¡rios programados.",
      icone: "Ã°Å¸Å½Â¤",
      imagem: "communicore-plaza.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3744,
      longitude: -81.5492
    },
    {
      id: "journey-of-water",
      titulo: "Journey of Water, Inspired by Moana",
      subtitulo: "World Celebration",
      tipo: "Trilha interativa com ÃƒÂ¡gua",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      personagemPrincipal: "Moana",
      descricao:
        "Caminho interativo inspirado em Moana, com fontes, efeitos sensoriais e atividades com ÃƒÂ¡gua para todas as idades. Uma experiÃƒÂªncia educativa e divertida.",
      icone: "Ã°Å¸â€™Â§",
      imagem: "journey-of-water.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3741,
      longitude: -81.5489
    },
    {
      id: "walt-disney-dreamers-statue",
      titulo: "EstÃƒÂ¡tua Walt the Dreamer",
      subtitulo: "World Celebration",
      tipo: "Ponto de foto e contemplaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      atracaoSemFila: true,
      descricao:
        "Escultura de Walt Disney sentado, localizada no Dreamers Point. Local ideal para fotos e reflexÃƒÂ£o. Acesso livre, sem fila.",
      icone: "Ã°Å¸â€œÂ¸",
      imagem: "walt-dreamer.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3746,
      longitude: -81.5495
    }
  ]
};
