export const WorldShowcase = {
  parque: "Epcot",
  regiao: "World Showcase",
  latitude: 28.3691,
  longitude: -81.5485,
  descricao:
    "Ãrea com 11 pavilhÃµes temÃ¡ticos de paÃ­ses ao redor do mundo, oferecendo culinÃ¡ria tÃ­pica, cultura, lojas, filmes, shows e atraÃ§Ãµes imersivas.",
  imagem: "worldshowcase.png",
  atracoes: [
    {
      id: "frozen-ever-after",
      titulo: "Frozen Ever After",
      subtitulo: "World Showcase",
      tipo: "Passeio de barco temÃ¡tico",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 65,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      personagemPrincipal: "Elsa e Anna",
      atracaoSemFila: false,
      descricao:
        "Aventura congelante no reino de Arendelle com personagens de Frozen, mÃºsicas clÃ¡ssicas e efeitos especiais em um passeio de barco.",
      icone: "â„ï¸",
      imagem: "frozen.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3725,
      longitude: -81.5476
    },
    {
      id: "gran-fiesta-tour",
      titulo: "Gran Fiesta Tour Starring The Three Caballeros",
      subtitulo: "World Showcase",
      tipo: "Passeio de barco",
      tipoPerfil: ["familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      personagemPrincipal: "Pato Donald",
      atracaoSemFila: false,
      descricao:
        "Passeio leve de barco no pavilhÃ£o do MÃ©xico com o Pato Donald e os TrÃªs Caballeros em uma jornada divertida pela cultura mexicana.",
      icone: "ðŸ›¶",
      imagem: "gran-fiesta-tour.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3681,
      longitude: -81.5502
    },
    {
      id: "impressions-de-france",
      titulo: "Impressions de France",
      subtitulo: "World Showcase",
      tipo: "Filme panorÃ¢mico",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "Filme clÃ¡ssico com paisagens e cultura francesa projetado em tela ampla no pavilhÃ£o da FranÃ§a. Exibido em horÃ¡rios alternados com outro show.",
      icone: "ðŸ‡«ðŸ‡·",
      imagem: "impressions-france.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3703,
      longitude: -81.5500
    },
    {
      id: "beauty-and-the-beast-sing-along",
      titulo: "Beauty and the Beast Sing-Along",
      subtitulo: "World Showcase",
      tipo: "Filme musical interativo",
      tipoPerfil: ["familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      personagemPrincipal: "Bela",
      atracaoSemFila: true,
      descricao:
        "VersÃ£o musical com letras na tela para cantar junto com as mÃºsicas do clÃ¡ssico A Bela e a Fera. Revezado com o filme Impressions de France.",
      icone: "ðŸŽ¶",
      imagem: "beauty-sing-along.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3703,
      longitude: -81.5500
    },
    {
      id: "reflections-of-china",
      titulo: "Reflections of China",
      subtitulo: "World Showcase",
      tipo: "Filme 360Â°",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "Filme em 360Â° com paisagens e cultura tradicional chinesa, exibido de pÃ© em uma sala circular. Uma experiÃªncia contemplativa e educativa.",
      icone: "ðŸ¯",
      imagem: "reflections-china.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3707,
      longitude: -81.5443
    },
    {
      id: "canada-far-and-wide",
      titulo: "Canada: Far and Wide",
      subtitulo: "World Showcase",
      tipo: "Filme 360Â°",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      atracaoSemFila: true,
      descricao:
        "Filme com visÃ£o panorÃ¢mica da geografia, natureza e cidades do CanadÃ¡, com trilha envolvente e exibiÃ§Ã£o em tela circular.",
      icone: "ðŸ‡¨ðŸ‡¦",
      imagem: "canada-far-and-wide.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3716,
      longitude: -81.5526
    },
    {
      id: "the-american-adventure",
      titulo: "The American Adventure",
      subtitulo: "World Showcase",
      tipo: "Show com animatrÃ´nicos",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      atracaoSemFila: true,
      descricao:
        "EspetÃ¡culo teatral com figuras animatrÃ´nicas contando a histÃ³ria dos Estados Unidos, com efeitos especiais e trilha Ã©pica.",
      icone: "ðŸ—½",
      imagem: "american-adventure.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3699,
      longitude: -81.5487
    }
  ]
};
