ï»¿export const WorldShowcase = {
  parque: "Epcot",
  regiao: "World Showcase",
  latitude: 28.3691,
  longitude: -81.5485,
  descricao:
    "ÃƒÂrea com 11 pavilhÃƒÂµes temÃƒÂ¡ticos de paÃƒÂ­ses ao redor do mundo, oferecendo culinÃƒÂ¡ria tÃƒÂ­pica, cultura, lojas, filmes, shows e atraÃƒÂ§ÃƒÂµes imersivas.",
  imagem: "worldshowcase.png",
  atracoes: [
    {
      id: "frozen-ever-after",
      titulo: "Frozen Ever After",
      subtitulo: "World Showcase",
      tipo: "Passeio de barco temÃƒÂ¡tico",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 65,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      personagemPrincipal: "Elsa e Anna",
      atracaoSemFila: false,
      descricao:
        "Aventura congelante no reino de Arendelle com personagens de Frozen, mÃƒÂºsicas clÃƒÂ¡ssicas e efeitos especiais em um passeio de barco.",
      icone: "Ã¢Ââ€žÃ¯Â¸Â",
      imagem: "frozen.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3725,
      longitude: -81.5476
    },
    {
      id: "gran-fiesta-tour",
      titulo: "Gran Fiesta Tour Starring The Three Caballeros",
      subtitulo: "World Showcase",
      tipo: "Passeio de barco",
      tipoPerfil: ["familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      personagemPrincipal: "Pato Donald",
      atracaoSemFila: false,
      descricao:
        "Passeio leve de barco no pavilhÃƒÂ£o do MÃƒÂ©xico com o Pato Donald e os TrÃƒÂªs Caballeros em uma jornada divertida pela cultura mexicana.",
      icone: "Ã°Å¸â€ºÂ¶",
      imagem: "gran-fiesta-tour.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3681,
      longitude: -81.5502
    },
    {
      id: "impressions-de-france",
      titulo: "Impressions de France",
      subtitulo: "World Showcase",
      tipo: "Filme panorÃƒÂ¢mico",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "Filme clÃƒÂ¡ssico com paisagens e cultura francesa projetado em tela ampla no pavilhÃƒÂ£o da FranÃƒÂ§a. Exibido em horÃƒÂ¡rios alternados com outro show.",
      icone: "Ã°Å¸â€¡Â«Ã°Å¸â€¡Â·",
      imagem: "impressions-france.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3703,
      longitude: -81.5500
    },
    {
      id: "beauty-and-the-beast-sing-along",
      titulo: "Beauty and the Beast Sing-Along",
      subtitulo: "World Showcase",
      tipo: "Filme musical interativo",
      tipoPerfil: ["familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      personagemPrincipal: "Bela",
      atracaoSemFila: true,
      descricao:
        "VersÃƒÂ£o musical com letras na tela para cantar junto com as mÃƒÂºsicas do clÃƒÂ¡ssico A Bela e a Fera. Revezado com o filme Impressions de France.",
      icone: "Ã°Å¸Å½Â¶",
      imagem: "beauty-sing-along.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3703,
      longitude: -81.5500
    },
    {
      id: "reflections-of-china",
      titulo: "Reflections of China",
      subtitulo: "World Showcase",
      tipo: "Filme 360Ã‚Â°",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "Filme em 360Ã‚Â° com paisagens e cultura tradicional chinesa, exibido de pÃƒÂ© em uma sala circular. Uma experiÃƒÂªncia contemplativa e educativa.",
      icone: "Ã°Å¸ÂÂ¯",
      imagem: "reflections-china.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3707,
      longitude: -81.5443
    },
    {
      id: "canada-far-and-wide",
      titulo: "Canada: Far and Wide",
      subtitulo: "World Showcase",
      tipo: "Filme 360Ã‚Â°",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      atracaoSemFila: true,
      descricao:
        "Filme com visÃƒÂ£o panorÃƒÂ¢mica da geografia, natureza e cidades do CanadÃƒÂ¡, com trilha envolvente e exibiÃƒÂ§ÃƒÂ£o em tela circular.",
      icone: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â¦",
      imagem: "canada-far-and-wide.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3716,
      longitude: -81.5526
    },
    {
      id: "the-american-adventure",
      titulo: "The American Adventure",
      subtitulo: "World Showcase",
      tipo: "Show com animatrÃƒÂ´nicos",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      atracaoSemFila: true,
      descricao:
        "EspetÃƒÂ¡culo teatral com figuras animatrÃƒÂ´nicas contando a histÃƒÂ³ria dos Estados Unidos, com efeitos especiais e trilha ÃƒÂ©pica.",
      icone: "Ã°Å¸â€”Â½",
      imagem: "american-adventure.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3699,
      longitude: -81.5487
    }
  ]
};
