ï»¿export const WorldNature = {
  parque: "Epcot",
  regiao: "World Nature",
  latitude: 28.3730,
  longitude: -81.5510,
  descricao:
    "ÃƒÂrea voltada para experiÃƒÂªncias sensoriais, contato com a natureza, oceanos e sustentabilidade. Ideal para todas as idades, com atraÃƒÂ§ÃƒÂµes relaxantes e educativas.",
  imagem: "worldnature.png",
  atracoes: [
    {
      id: "soarin-around-the-world",
      titulo: "SoarinÃ¢â‚¬â„¢ Around the World",
      subtitulo: "World Nature",
      tipo: "Simulador de voo panorÃƒÂ¢mico",
      tipoPerfil: ["imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 35,
      idadeRecomendada: "6+",
      turnoRecomendado: "manha",
      atracaoSemFila: false,
      descricao:
        "Simulador de voo panorÃƒÂ¢mico com tela IMAX, aromas e vento nos pÃƒÂ©s que leva os visitantes a sobrevoar paisagens incrÃƒÂ­veis pelo mundo.",
      icone: "Ã°Å¸Âªâ€š",
      imagem: "soarin.jpg",
      regiao: "World Nature",
      parque: "Epcot",
      latitude: 28.3726,
      longitude: -81.5502
    },
    {
      id: "the-seas-nemo-friends",
      titulo: "The Seas with Nemo & Friends",
      subtitulo: "World Nature",
      tipo: "Passeio de carrinho subaquÃƒÂ¡tico",
      tipoPerfil: ["familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      personagemPrincipal: "Nemo, Dory, Marlin",
      atracaoSemFila: false,
      descricao:
        "Passeio leve por ambientes subaquÃƒÂ¡ticos com Nemo e seus amigos, terminando em um aquÃƒÂ¡rio real com peixes, golfinhos e tartarugas.",
      icone: "Ã°Å¸ÂÂ ",
      imagem: "nemo-friends.jpg",
      regiao: "World Nature",
      parque: "Epcot",
      latitude: 28.3750,
      longitude: -81.5508
    },
    {
      id: "living-with-the-land",
      titulo: "Living with the Land",
      subtitulo: "World Nature",
      tipo: "Passeio educativo de barco",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      descricao:
        "Passeio de barco pelas estufas e sistemas de cultivo do pavilhÃƒÂ£o The Land, com foco em sustentabilidade e inovaÃƒÂ§ÃƒÂ£o agrÃƒÂ­cola.",
      icone: "Ã°Å¸Å’Â¿",
      imagem: "living-with-the-land.jpg",
      regiao: "World Nature",
      parque: "Epcot",
      latitude: 28.3729,
      longitude: -81.5501
    },
    {
      id: "turtle-talk-with-crush",
      titulo: "Turtle Talk with Crush",
      subtitulo: "World Nature",
      tipo: "Show interativo digital",
      tipoPerfil: ["interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      personagemPrincipal: "Crush",
      atracaoSemFila: true,
      descricao:
        "Show interativo com o personagem Crush (projeÃƒÂ§ÃƒÂ£o digital), que conversa ao vivo com o pÃƒÂºblico de forma divertida. Apresentado em horÃƒÂ¡rios especÃƒÂ­ficos.",
      icone: "Ã°Å¸ÂÂ¢",
      imagem: "turtle-talk.jpg",
      regiao: "World Nature",
      parque: "Epcot",
      latitude: 28.3747,
      longitude: -81.5506
    },
    {
      id: "seabase-aquarium",
      titulo: "SeaBase Aquarium",
      subtitulo: "World Nature",
      tipo: "AquÃƒÂ¡rio de observaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "Grande aquÃƒÂ¡rio com vÃƒÂ¡rias espÃƒÂ©cies marinhas, incluindo golfinhos, tubarÃƒÂµes e peixes tropicais. Livre para explorar no seu tempo.",
      icone: "Ã°Å¸ÂÂ¬",
      imagem: "seabase.jpg",
      regiao: "World Nature",
      parque: "Epcot",
      latitude: 28.3749,
      longitude: -81.5507
    },
    {
      id: "awesome-planet",
      titulo: "Awesome Planet",
      subtitulo: "World Nature",
      tipo: "Filme educativo",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      atracaoSemFila: true,
      descricao:
        "Filme sobre o planeta Terra com imagens em alta definiÃƒÂ§ÃƒÂ£o e efeitos sensoriais. Educativo e exibido em sessÃƒÂµes durante o dia.",
      icone: "Ã°Å¸Å’Å½",
      imagem: "awesome-planet.jpg",
      regiao: "World Nature",
      parque: "Epcot",
      latitude: 28.3728,
      longitude: -81.5500
    }
  ]
};
