export const WorldShowcase = {
  parque: "Epcot",
  regiao: "World Showcase",
  latitude: 28.3691,
  longitude: -81.5485,
  descricao:
    "Área com 11 pavilhões temáticos de países ao redor do mundo, oferecendo culinária típica, cultura, lojas, filmes, shows e atrações imersivas.",
  imagem: "worldshowcase.png",
  atracoes: [
    {
      id: "frozen-ever-after",
      titulo: "Frozen Ever After",
      subtitulo: "World Showcase",
      tipo: "Passeio de barco temático",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 65,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      personagemPrincipal: "Elsa e Anna",
      atracaoSemFila: false,
      descricao:
        "Aventura congelante no reino de Arendelle com personagens de Frozen, músicas clássicas e efeitos especiais em um passeio de barco.",
      icone: "❄️",
      imagem: "frozen.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3725,
      longitude: -81.5476
    },
    {
      id: "gran-fiesta-tour",
      titulo: "Gran Fiesta Tour Starring The Three Caballeros",
      subtitulo: "World Showcase",
      tipo: "Passeio de barco",
      tipoPerfil: ["familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      personagemPrincipal: "Pato Donald",
      atracaoSemFila: false,
      descricao:
        "Passeio leve de barco no pavilhão do México com o Pato Donald e os Três Caballeros em uma jornada divertida pela cultura mexicana.",
      icone: "🛶",
      imagem: "gran-fiesta-tour.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3681,
      longitude: -81.5502
    },
    {
      id: "impressions-de-france",
      titulo: "Impressions de France",
      subtitulo: "World Showcase",
      tipo: "Filme panorâmico",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "Filme clássico com paisagens e cultura francesa projetado em tela ampla no pavilhão da França. Exibido em horários alternados com outro show.",
      icone: "🇫🇷",
      imagem: "impressions-france.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3703,
      longitude: -81.5500
    },
    {
      id: "beauty-and-the-beast-sing-along",
      titulo: "Beauty and the Beast Sing-Along",
      subtitulo: "World Showcase",
      tipo: "Filme musical interativo",
      tipoPerfil: ["familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      personagemPrincipal: "Bela",
      atracaoSemFila: true,
      descricao:
        "Versão musical com letras na tela para cantar junto com as músicas do clássico A Bela e a Fera. Revezado com o filme Impressions de France.",
      icone: "🎶",
      imagem: "beauty-sing-along.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3703,
      longitude: -81.5500
    },
    {
      id: "reflections-of-china",
      titulo: "Reflections of China",
      subtitulo: "World Showcase",
      tipo: "Filme 360°",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "Filme em 360° com paisagens e cultura tradicional chinesa, exibido de pé em uma sala circular. Uma experiência contemplativa e educativa.",
      icone: "🏯",
      imagem: "reflections-china.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3707,
      longitude: -81.5443
    },
    {
      id: "canada-far-and-wide",
      titulo: "Canada: Far and Wide",
      subtitulo: "World Showcase",
      tipo: "Filme 360°",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      atracaoSemFila: true,
      descricao:
        "Filme com visão panorâmica da geografia, natureza e cidades do Canadá, com trilha envolvente e exibição em tela circular.",
      icone: "🇨🇦",
      imagem: "canada-far-and-wide.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3716,
      longitude: -81.5526
    },
    {
      id: "the-american-adventure",
      titulo: "The American Adventure",
      subtitulo: "World Showcase",
      tipo: "Show com animatrônicos",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      atracaoSemFila: true,
      descricao:
        "Espetáculo teatral com figuras animatrônicas contando a história dos Estados Unidos, com efeitos especiais e trilha épica.",
      icone: "🗽",
      imagem: "american-adventure.jpg",
      regiao: "World Showcase",
      parque: "Epcot",
      latitude: 28.3699,
      longitude: -81.5487
    }
  ]
};
