export const WorldCelebration = {
  parque: "Epcot",
  regiao: "World Celebration",
  latitude: 28.3745,
  longitude: -81.5494,
  descricao:
    "Área central do Epcot que celebra a criatividade, a conexão entre pessoas e ideias. Aqui estão espaços tranquilos, atrações inspiradoras, homenagens a Walt Disney e experiências interativas.",
  imagem: "worldcelebration.png",
  atracoes: [
    {
      id: "spaceship-earth",
      titulo: "Spaceship Earth",
      subtitulo: "World Celebration",
      tipo: "Dark ride educativa",
      tipoPerfil: ["tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      atracaoSemFila: false,
      descricao:
        "Viagem no tempo dentro da icônica esfera do Epcot, mostrando a evolução da comunicação humana com narração envolvente e cenários imersivos.",
      icone: "🌐",
      imagem: "spaceship-earth.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3747,
      longitude: -81.5497
    },
    {
      id: "dreamers-point",
      titulo: "Dreamers Point",
      subtitulo: "World Celebration",
      tipo: "Espaço temático e homenagem",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "Escultura e área contemplativa em homenagem a Walt Disney, cercada por jardins e vista privilegiada da Spaceship Earth. Sem fila, ideal para uma pausa.",
      icone: "🪑",
      imagem: "dreamers-point.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3746,
      longitude: -81.5494
    },
    {
      id: "communicore-plaza",
      titulo: "CommuniCore Plaza",
      subtitulo: "World Celebration",
      tipo: "Área para eventos e shows ao vivo",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      atracaoSemFila: true,
      descricao:
        "Praça interativa e palco para eventos ao ar livre e shows sazonais, com espaços abertos e áreas de descanso. Sem filas, com horários programados.",
      icone: "🎤",
      imagem: "communicore-plaza.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3744,
      longitude: -81.5492
    },
    {
      id: "journey-of-water",
      titulo: "Journey of Water, Inspired by Moana",
      subtitulo: "World Celebration",
      tipo: "Trilha interativa com água",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      personagemPrincipal: "Moana",
      descricao:
        "Caminho interativo inspirado em Moana, com fontes, efeitos sensoriais e atividades com água para todas as idades. Uma experiência educativa e divertida.",
      icone: "💧",
      imagem: "journey-of-water.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3741,
      longitude: -81.5489
    },
    {
      id: "walt-disney-dreamers-statue",
      titulo: "Estátua Walt the Dreamer",
      subtitulo: "World Celebration",
      tipo: "Ponto de foto e contemplação",
      tipoPerfil: ["tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      atracaoSemFila: true,
      descricao:
        "Escultura de Walt Disney sentado, localizada no Dreamers Point. Local ideal para fotos e reflexão. Acesso livre, sem fila.",
      icone: "📸",
      imagem: "walt-dreamer.jpg",
      regiao: "World Celebration",
      parque: "Epcot",
      latitude: 28.3746,
      longitude: -81.5495
    }
  ]
};
