ï»¿export const WorldDiscovery = {
  parque: "Epcot",
  regiao: "World Discovery",
  latitude: 28.3742,
  longitude: -81.5472,
  descricao:
    "ÃƒÂrea dedicada ÃƒÂ  ciÃƒÂªncia, espaÃƒÂ§o e inovaÃƒÂ§ÃƒÂ£o. Aqui estÃƒÂ£o algumas das atraÃƒÂ§ÃƒÂµes mais radicais e tecnolÃƒÂ³gicas do parque, com experiÃƒÂªncias futuristas e interativas.",
  imagem: "worlddiscovery.png",
  atracoes: [
    {
      id: "guardians-of-the-galaxy-cosmic-rewind",
      titulo: "Guardians of the Galaxy: Cosmic Rewind",
      subtitulo: "World Discovery",
      tipo: "Montanha-russa indoor com rotaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["radicais"],
      alturaMinima: 107,
      filaExpress: false,
      tempoMedioFila: 75,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "tarde",
      personagemPrincipal: "Senhor das Estrelas, Gamora, Rocket, Groot, Drax",
      atracaoSemFila: false,
      descricao:
        "Montanha-russa com rotaÃƒÂ§ÃƒÂ£o de carrinho e trilha sonora dos GuardiÃƒÂµes da GalÃƒÂ¡xia. Moderna, divertida e uma das mais emocionantes da Disney.",
      icone: "Ã°Å¸Å’Å’",
      imagem: "cosmic-rewind.jpg",
      regiao: "World Discovery",
      parque: "Epcot",
      latitude: 28.3743,
      longitude: -81.5468
    },
    {
      id: "test-track",
      titulo: "Test Track",
      subtitulo: "World Discovery",
      tipo: "Simulador de carro de alta velocidade",
      tipoPerfil: ["radicais"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "6+",
      turnoRecomendado: "manha",
      atracaoSemFila: false,
      descricao:
        "Crie seu prÃƒÂ³prio carro e teste aceleraÃƒÂ§ÃƒÂ£o, curvas e resistÃƒÂªncia em um circuito real com velocidade mÃƒÂ¡xima no final.",
      icone: "Ã°Å¸ÂÅ½Ã¯Â¸Â",
      imagem: "test-track.jpg",
      regiao: "World Discovery",
      parque: "Epcot",
      latitude: 28.3735,
      longitude: -81.5477
    },
    {
      id: "mission-space",
      titulo: "Mission: SPACE",
      subtitulo: "World Discovery",
      tipo: "Simulador espacial com forÃƒÂ§a G",
      tipoPerfil: ["imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 30,
      idadeRecomendada: "8+",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      descricao:
        "SimulaÃƒÂ§ÃƒÂ£o de lanÃƒÂ§amento e pouso no espaÃƒÂ§o com dois nÃƒÂ­veis de intensidade: Verde (leve) e Laranja (intenso, com forÃƒÂ§a G).",
      icone: "Ã°Å¸Å¡â‚¬",
      imagem: "mission-space.jpg",
      regiao: "World Discovery",
      parque: "Epcot",
      latitude: 28.3742,
      longitude: -81.5473
    },
    {
      id: "advanced-training-lab",
      titulo: "Advanced Training Lab",
      subtitulo: "World Discovery",
      tipo: "EspaÃƒÂ§o interativo pÃƒÂ³s-ride",
      tipoPerfil: ["interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "EspaÃƒÂ§o com jogos e simuladores interativos voltado ao tema espacial, localizado na saÃƒÂ­da do Mission: SPACE. Acesso livre, sem fila.",
      icone: "Ã°Å¸Â§Âª",
      imagem: "advanced-training-lab.jpg",
      regiao: "World Discovery",
      parque: "Epcot",
      latitude: 28.3743,
      longitude: -81.5471
    }
  ]
};
