export const WorldDiscovery = {
  parque: "Epcot",
  regiao: "World Discovery",
  latitude: 28.3742,
  longitude: -81.5472,
  descricao:
    "Ãrea dedicada Ã  ciÃªncia, espaÃ§o e inovaÃ§Ã£o. Aqui estÃ£o algumas das atraÃ§Ãµes mais radicais e tecnolÃ³gicas do parque, com experiÃªncias futuristas e interativas.",
  imagem: "worlddiscovery.png",
  atracoes: [
    {
      id: "guardians-of-the-galaxy-cosmic-rewind",
      titulo: "Guardians of the Galaxy: Cosmic Rewind",
      subtitulo: "World Discovery",
      tipo: "Montanha-russa indoor com rotaÃ§Ã£o",
      tipoPerfil: ["radicais"],
      alturaMinima: 107,
      filaExpress: false,
      tempoMedioFila: 75,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "tarde",
      personagemPrincipal: "Senhor das Estrelas, Gamora, Rocket, Groot, Drax",
      atracaoSemFila: false,
      descricao:
        "Montanha-russa com rotaÃ§Ã£o de carrinho e trilha sonora dos GuardiÃµes da GalÃ¡xia. Moderna, divertida e uma das mais emocionantes da Disney.",
      icone: "ðŸŒŒ",
      imagem: "cosmic-rewind.jpg",
      regiao: "World Discovery",
      parque: "Epcot",
      latitude: 28.3743,
      longitude: -81.5468
    },
    {
      id: "test-track",
      titulo: "Test Track",
      subtitulo: "World Discovery",
      tipo: "Simulador de carro de alta velocidade",
      tipoPerfil: ["radicais"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "6+",
      turnoRecomendado: "manha",
      atracaoSemFila: false,
      descricao:
        "Crie seu prÃ³prio carro e teste aceleraÃ§Ã£o, curvas e resistÃªncia em um circuito real com velocidade mÃ¡xima no final.",
      icone: "ðŸŽï¸",
      imagem: "test-track.jpg",
      regiao: "World Discovery",
      parque: "Epcot",
      latitude: 28.3735,
      longitude: -81.5477
    },
    {
      id: "mission-space",
      titulo: "Mission: SPACE",
      subtitulo: "World Discovery",
      tipo: "Simulador espacial com forÃ§a G",
      tipoPerfil: ["imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 30,
      idadeRecomendada: "8+",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      descricao:
        "SimulaÃ§Ã£o de lanÃ§amento e pouso no espaÃ§o com dois nÃ­veis de intensidade: Verde (leve) e Laranja (intenso, com forÃ§a G).",
      icone: "ðŸš€",
      imagem: "mission-space.jpg",
      regiao: "World Discovery",
      parque: "Epcot",
      latitude: 28.3742,
      longitude: -81.5473
    },
    {
      id: "advanced-training-lab",
      titulo: "Advanced Training Lab",
      subtitulo: "World Discovery",
      tipo: "EspaÃ§o interativo pÃ³s-ride",
      tipoPerfil: ["interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "EspaÃ§o com jogos e simuladores interativos voltado ao tema espacial, localizado na saÃ­da do Mission: SPACE. Acesso livre, sem fila.",
      icone: "ðŸ§ª",
      imagem: "advanced-training-lab.jpg",
      regiao: "World Discovery",
      parque: "Epcot",
      latitude: 28.3743,
      longitude: -81.5471
    }
  ]
};
