export const WorldDiscovery = {
  parque: "Epcot",
  regiao: "World Discovery",
  latitude: 28.3742,
  longitude: -81.5472,
  descricao:
    "Área dedicada à ciência, espaço e inovação. Aqui estão algumas das atrações mais radicais e tecnológicas do parque, com experiências futuristas e interativas.",
  imagem: "worlddiscovery.png",
  atracoes: [
    {
      id: "guardians-of-the-galaxy-cosmic-rewind",
      titulo: "Guardians of the Galaxy: Cosmic Rewind",
      subtitulo: "World Discovery",
      tipo: "Montanha-russa indoor com rotação",
      tipoPerfil: ["radicais"],
      alturaMinima: 107,
      filaExpress: false,
      tempoMedioFila: 75,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "tarde",
      personagemPrincipal: "Senhor das Estrelas, Gamora, Rocket, Groot, Drax",
      atracaoSemFila: false,
      descricao:
        "Montanha-russa com rotação de carrinho e trilha sonora dos Guardiões da Galáxia. Moderna, divertida e uma das mais emocionantes da Disney.",
      icone: "🌌",
      imagem: "cosmic-rewind.jpg",
      regiao: "World Discovery",
      parque: "Epcot",
      latitude: 28.3743,
      longitude: -81.5468
    },
    {
      id: "test-track",
      titulo: "Test Track",
      subtitulo: "World Discovery",
      tipo: "Simulador de carro de alta velocidade",
      tipoPerfil: ["radicais"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "6+",
      turnoRecomendado: "manha",
      atracaoSemFila: false,
      descricao:
        "Crie seu próprio carro e teste aceleração, curvas e resistência em um circuito real com velocidade máxima no final.",
      icone: "🏎️",
      imagem: "test-track.jpg",
      regiao: "World Discovery",
      parque: "Epcot",
      latitude: 28.3735,
      longitude: -81.5477
    },
    {
      id: "mission-space",
      titulo: "Mission: SPACE",
      subtitulo: "World Discovery",
      tipo: "Simulador espacial com força G",
      tipoPerfil: ["imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 30,
      idadeRecomendada: "8+",
      turnoRecomendado: "tarde",
      atracaoSemFila: false,
      descricao:
        "Simulação de lançamento e pouso no espaço com dois níveis de intensidade: Verde (leve) e Laranja (intenso, com força G).",
      icone: "🚀",
      imagem: "mission-space.jpg",
      regiao: "World Discovery",
      parque: "Epcot",
      latitude: 28.3742,
      longitude: -81.5473
    },
    {
      id: "advanced-training-lab",
      titulo: "Advanced Training Lab",
      subtitulo: "World Discovery",
      tipo: "Espaço interativo pós-ride",
      tipoPerfil: ["interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      atracaoSemFila: true,
      descricao:
        "Espaço com jogos e simuladores interativos voltado ao tema espacial, localizado na saída do Mission: SPACE. Acesso livre, sem fila.",
      icone: "🧪",
      imagem: "advanced-training-lab.jpg",
      regiao: "World Discovery",
      parque: "Epcot",
      latitude: 28.3743,
      longitude: -81.5471
    }
  ]
};
