export const almocosProximos = [
  // 1 - International Drive
{
  nome: "The Capital Grille",
  regiao: "International Drive",
  tipo: "Americano",
  acesso: "9101 International Dr, Orlando, FL 32819",
  precoMedio: 36,
  destaque: "Steakhouse refinada com carnes dry aged, hambÃºrgueres gourmet e ambiente sofisticado para um almoÃ§o de alto padrÃ£o. Experimente o Prime Ribeye Dry Aged.",
  latitude: 28.4375,
  longitude: -81.4699,
},
{
  nome: "First Watch Lunch I-Drive",
  regiao: "International Drive",
  tipo: "Conforto",
  acesso: "7500 W Sand Lake Rd #50, Orlando, FL 32819",
  precoMedio: 22,
  destaque: "AlmoÃ§o leve com saladas frescas, bowls e pratos de comfort food, perfeito para refeiÃ§Ãµes rÃ¡pidas e nutritivas. Experimente o Avocado Toast com ovos orgÃ¢nicos.",
  latitude: 28.4362,
  longitude: -81.4690,
},
{
  nome: "Five Guys I-Drive Lunch",
  regiao: "International Drive",
  tipo: "Economico",
  acesso: "8250 International Dr Suite 100, Orlando, FL 32819",
  precoMedio: 12,
  destaque: "HambÃºrgueres personalizados com batatas rÃºsticas servidos em ambiente casual, Ã³timo para uma refeiÃ§Ã£o rÃ¡pida e saborosa. Experimente o Cheeseburger com bacon e batata frita rÃºstica.",
  latitude: 28.4384,
  longitude: -81.4685,
},
{
  nome: "Green Kitchen I-Drive",
  regiao: "International Drive",
  tipo: "Saudavel",
  acesso: "5450 International Dr, Orlando, FL 32819",
  precoMedio: 18,
  destaque: "Restaurante saudÃ¡vel com bowls, grelhados e opÃ§Ãµes naturais, ideal para quem busca refeiÃ§Ãµes leves e equilibradas. Experimente o Bowl de SalmÃ£o Grelhado com quinoa.",
  latitude: 28.4401,
  longitude: -81.4712,
},

// 2 - Lake Buena Vista
{
  nome: "Olive Garden Lake Buena Vista",
  regiao: "Lake Buena Vista",
  tipo: "Americano",
  acesso: "12361 S Apopka Vineland Rd, Orlando, FL 32836",
  precoMedio: 26,
  destaque: "CulinÃ¡ria italiana-americana com massas e carnes clÃ¡ssicas, ambiente familiar e porÃ§Ãµes generosas. Experimente o Fettuccine Alfredo.",
  latitude: 28.3851,
  longitude: -81.4916,
},
{
  nome: "Rainforest Cafe Lunch",
  regiao: "Lake Buena Vista",
  tipo: "Tematico",
  acesso: "1486 Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 40,
  destaque: "Restaurante com decoraÃ§Ã£o de floresta tropical, sons e efeitos especiais imersivos. Experimente o Ribs, Steak & Shrimp Trio.",
  latitude: 28.3705,
  longitude: -81.5211,
},
{
  nome: "Cheddar's Scratch Kitchen Lunch",
  regiao: "Lake Buena Vista",
  tipo: "Conforto",
  acesso: "12340 S Apopka Vineland Rd, Orlando, FL 32836",
  precoMedio: 24,
  destaque: "Comida caseira americana, porÃ§Ãµes fartas e pratos preparados do zero. Experimente o Country Fried Steak.",
  latitude: 28.3858,
  longitude: -81.5037,
},
{
  nome: "Subway Vineland Lunch",
  regiao: "Lake Buena Vista",
  tipo: "Economico",
  acesso: "12384 S Apopka Vineland Rd, Orlando, FL 32836",
  precoMedio: 10,
  destaque: "SanduÃ­ches personalizÃ¡veis montados na hora com pÃ£es frescos. Experimente o Italian B.M.T.",
  latitude: 28.3793,
  longitude: -81.4894,
},
{
  nome: "Jasonâ€™s Deli Lake Buena Vista",
  regiao: "Lake Buena Vista",
  tipo: "Saudavel",
  acesso: "7433 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 16,
  destaque: "Rede com buffet de saladas, sopas e opÃ§Ãµes naturais, lembrando o estilo do antigo Sweet Tomatoes. Experimente o Salad Bar com sopa de tomate orgÃ¢nica.",
  latitude: 28.4480,
  longitude: -81.4740,
},
// 3 - Kissimmee
{
  nome: "LongHorn Steakhouse Kissimmee",
  regiao: "Kissimmee",
  tipo: "Americano",
  acesso: "8398 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 30,
  destaque: "Carnes grelhadas e ambiente western descontraÃ­do. Experimente o Floâ€™s Filet com acompanhamento de batata assada.",
  latitude: 28.3055,
  longitude: -81.4412,
},
{
  nome: "Medieval Times Lunch",
  regiao: "Kissimmee",
  tipo: "Tematico",
  acesso: "4510 W Vine St, Kissimmee, FL 34746",
  precoMedio: 45,
  destaque: "Show medieval com batalhas de cavaleiros e refeiÃ§Ã£o inclusa. Experimente o Jantar Real com frango assado inteiro e sopa de tomate.",
  latitude: 28.3230,
  longitude: -81.4701,
},
{
  nome: "Cracker Barrel Kissimmee",
  regiao: "Kissimmee",
  tipo: "Conforto",
  acesso: "8400 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 22,
  destaque: "CulinÃ¡ria sulista tradicional e ambiente rÃºstico. Experimente o Chicken nâ€™ Dumplins.",
  latitude: 28.3078,
  longitude: -81.4299,
},
{
  nome: "Wendyâ€™s Kissimmee Lunch",
  regiao: "Kissimmee",
  tipo: "Economico",
  acesso: "7790 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 9,
  destaque: "Fast food americano com combos acessÃ­veis. Experimente o Baconator com batata frita e refrigerante.",
  latitude: 28.3042,
  longitude: -81.4281,
},
{
  nome: "Natureâ€™s Table Kissimmee",
  regiao: "Kissimmee",
  tipo: "Saudavel",
  acesso: "101 W Cypress St, Kissimmee, FL 34741",
  precoMedio: 17,
  destaque: "Wraps, saladas e smoothies frescos e nutritivos. Experimente o Turkey Club Wrap com smoothie de morango e banana.",
  latitude: 28.3164,
  longitude: -81.4383,
},

// 4 - Celebration
{
  nome: "Columbia Restaurant Lunch",
  regiao: "Celebration",
  tipo: "Americano",
  acesso: "649 Front St, Celebration, FL 34747",
  precoMedio: 30,
  destaque: "Restaurante histÃ³rico com pratos cubanos e espanhÃ³is. Experimente a Paella Valenciana.",
  latitude: 28.3175,
  longitude: -81.5419,
},
{
  nome: "Cafe Dâ€™Antonio Celebration",
  regiao: "Celebration",
  tipo: "Tematico",
  acesso: "691 Front St, Celebration, FL 34747",
  precoMedio: 36,
  destaque: "CulinÃ¡ria italiana autÃªntica em ambiente acolhedor Ã  beira do lago. Experimente o Fettuccine Alfredo com camarÃµes.",
  latitude: 28.3170,
  longitude: -81.5417,
},
{
  nome: "Market Street Cafe Lunch",
  regiao: "Celebration",
  tipo: "Conforto",
  acesso: "701 Front St, Celebration, FL 34747",
  precoMedio: 21,
  destaque: "ClÃ¡ssicos americanos em ambiente acolhedor e central. Experimente o Meatloaf caseiro.",
  latitude: 28.3169,
  longitude: -81.5413,
},
{
  nome: "Tijuana Flats Lunch",
  regiao: "Celebration",
  tipo: "Economico",
  acesso: "607 Market St, Celebration, FL 34747",
  precoMedio: 11,
  destaque: "Tex-Mex rÃ¡pido com molhos caseiros e porÃ§Ãµes generosas. Experimente o Burrito Banginâ€™ Chicken.",
  latitude: 28.3238,
  longitude: -81.5351,
},
{
  nome: "Vitality Bowls Celebration",
  regiao: "Celebration",
  tipo: "Saudavel",
  acesso: "671 Front St, Celebration, FL 34747",
  precoMedio: 18,
  destaque: "Bowls nutritivos e sucos naturais frescos. Experimente o AÃ§aÃ­ Energy Bowl.",
  latitude: 28.3171,
  longitude: -81.5415,
},
// 5 - Disney Springs
{
  nome: "House of Blues Lunch",
  regiao: "Disney Springs",
  tipo: "Americano",
  acesso: "1490 E Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 34,
  destaque: "CulinÃ¡ria sulista americana com mÃºsica ao vivo. Experimente o Jambalaya tradicional.",
  latitude: 28.3717,
  longitude: -81.5242,
},
{
  nome: "T-Rex Cafe Lunch",
  regiao: "Disney Springs",
  tipo: "Tematico",
  acesso: "1676 E Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 42,
  destaque: "Restaurante temÃ¡tico de dinossauros com ambiente imersivo. Experimente o Bronto Burger.",
  latitude: 28.3711,
  longitude: -81.5215,
},
{
  nome: "D-Luxe Burger Lunch",
  regiao: "Disney Springs",
  tipo: "Conforto",
  acesso: "1526 E Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 20,
  destaque: "HambÃºrgueres artesanais com molhos especiais. Experimente o Southern Classic Burger.",
  latitude: 28.3719,
  longitude: -81.5231,
},
{
  nome: "Earl of Sandwich Lunch",
  regiao: "Disney Springs",
  tipo: "Economico",
  acesso: "1750 E Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 12,
  destaque: "SanduÃ­ches rÃ¡pidos e saborosos a preÃ§o acessÃ­vel. Experimente o The Original 1762 Roast Beef.",
  latitude: 28.3706,
  longitude: -81.5222,
},
{
  nome: "Blaze Pizza Lunch",
  regiao: "Disney Springs",
  tipo: "Saudavel",
  acesso: "1506 E Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 16,
  destaque: "Pizzas artesanais personalizadas em poucos minutos. Experimente a Pizza de frango com pesto.",
  latitude: 28.3713,
  longitude: -81.5234,
},

// 6 - Windsor Hills
{
  nome: "Drafts Sports Bar & Grill",
  regiao: "Windsor Hills",
  tipo: "Americano",
  acesso: "9500 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 28,
  destaque: "Bar esportivo com hambÃºrgueres, pizzas e pratos americanos clÃ¡ssicos. Experimente as Chicken Wings.",
  latitude: 28.3234,
  longitude: -81.5892,
},
{
  nome: "Minnieâ€™s Cafe Lunch",
  regiao: "Windsor Hills",
  tipo: "Tematico",
  acesso: "7600 Comrow St, Kissimmee, FL 34747",
  precoMedio: 36,
  destaque: "Restaurante temÃ¡tico Disney com pratos familiares e ambiente infantil. Experimente os Mickey Waffles.",
  latitude: 28.3229,
  longitude: -81.5903,
},
{
  nome: "Perkins Restaurant & Bakery",
  regiao: "Windsor Hills",
  tipo: "Conforto",
  acesso: "13600 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34787",
  precoMedio: 23,
  destaque: "Pratos caseiros e padaria com opÃ§Ãµes para todas as refeiÃ§Ãµes. Experimente a Chicken Pot Pie.",
  latitude: 28.3251,
  longitude: -81.5869,
},
{
  nome: "McDonald's Formosa Blvd",
  regiao: "Windsor Hills",
  tipo: "Economico",
  acesso: "7764 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 8,
  destaque: "Fast food acessÃ­vel com hambÃºrgueres e combos rÃ¡pidos. Experimente o Big Mac clÃ¡ssico.",
  latitude: 28.3242,
  longitude: -81.5843,
},
{
  nome: "Freshii Windsor Hills",
  regiao: "Windsor Hills",
  tipo: "Saudavel",
  acesso: "7800 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 17,
  destaque: "RefeiÃ§Ãµes leves e bowls nutritivos com ingredientes frescos. Experimente o Buddha Satay Bowl.",
  latitude: 28.3239,
  longitude: -81.5859,
},

// 7 - ChampionsGate
{
  nome: "Millerâ€™s Ale House",
  regiao: "ChampionsGate",
  tipo: "Americano",
  acesso: "8170 Champions Gate Blvd, Champions Gate, FL 33896",
  precoMedio: 27,
  destaque: "Bar esportivo com pratos variados e porÃ§Ãµes generosas. Experimente os Zingers (frango empanado com molhos).",
  latitude: 28.2632,
  longitude: -81.6389,
},
{
  nome: "Blue Coast Asian Grill",
  regiao: "ChampionsGate",
  tipo: "Tematico",
  acesso: "8341 Champions Gate Blvd, Champions Gate, FL 33896",
  precoMedio: 34,
  destaque: "CulinÃ¡ria asiÃ¡tica moderna com pratos saborosos e ambiente acolhedor. Experimente o Teriyaki Chicken Bowl.",
  latitude: 28.2625,
  longitude: -81.6370,
},
{
  nome: "Panera Bread ChampionsGate",
  regiao: "ChampionsGate",
  tipo: "Conforto",
  acesso: "8145 Champions Gate Blvd, Champions Gate, FL 33896",
  precoMedio: 20,
  destaque: "Sopas, saladas e sanduÃ­ches artesanais frescos. Experimente o combo You Pick Two: Sopa Broccoli Cheddar + Frontega Chicken.",
  latitude: 28.2642,
  longitude: -81.6361,
},
{
  nome: "Taco Bell ChampionsGate",
  regiao: "ChampionsGate",
  tipo: "Economico",
  acesso: "8300 Champions Gate Blvd, Champions Gate, FL 33896",
  precoMedio: 9,
  destaque: "Fast food mexicano com combos baratos e rÃ¡pidos. Experimente o Crunchwrap Supreme.",
  latitude: 28.2637,
  longitude: -81.6355,
},
{
  nome: "Bolay ChampionsGate",
  regiao: "ChampionsGate",
  tipo: "Saudavel",
  acesso: "8349 Champions Gate Blvd, Champions Gate, FL 33896",
  precoMedio: 16,
  destaque: "Bowls personalizados com ingredientes frescos e saudÃ¡veis. Experimente o bowl com Havana Pulled Pork e arroz de jasmim.",
  latitude: 28.2628,
  longitude: -81.6368,
},

// 8 - Four Corners
{
  nome: "Applebeeâ€™s Four Corners",
  regiao: "Four Corners",
  tipo: "Americano",
  acesso: "631 Hwy 27, Clermont, FL 34714",
  precoMedio: 25,
  destaque: "Cadeia americana com pratos clÃ¡ssicos e ambiente familiar. Experimente o Bourbon Street Chicken & Shrimp.",
  latitude: 28.3499,
  longitude: -81.6471,
},
{
  nome: "Flippers Pizzeria Lunch",
  regiao: "Four Corners",
  tipo: "Tematico",
  acesso: "629 Hwy 27, Clermont, FL 34714",
  precoMedio: 30,
  destaque: "Pizzaria com forno Ã  lenha e sabor autÃªntico. Experimente a Pizza Margherita tradicional.",
  latitude: 28.3525,
  longitude: -81.6502,
},
{
  nome: "Perkins Family Restaurant",
  regiao: "Four Corners",
  tipo: "Conforto",
  acesso: "6311 US-192, Clermont, FL 34714",
  precoMedio: 22,
  destaque: "Restaurante familiar com pratos caseiros e padaria. Experimente o Country Fried Steak com purÃª.",
  latitude: 28.3501,
  longitude: -81.6494,
},
{
  nome: "Popeyes Louisiana Kitchen",
  regiao: "Four Corners",
  tipo: "Economico",
  acesso: "6303 US-192, Clermont, FL 34714",
  precoMedio: 10,
  destaque: "Frango frito crocante no estilo sulista. Experimente o Spicy Chicken Sandwich.",
  latitude: 28.3487,
  longitude: -81.6482,
},
{
  nome: "Tropical Smoothie Cafe",
  regiao: "Four Corners",
  tipo: "Saudavel",
  acesso: "17445 US-192, Clermont, FL 34714",
  precoMedio: 14,
  destaque: "Smoothies naturais e wraps leves e saudÃ¡veis. Experimente o Island Green Smoothie.",
  latitude: 28.3479,
  longitude: -81.6460,
},
// 9 - Reunion
{
  nome: "Eleven at Reunion Resort",
  regiao: "Reunion",
  tipo: "Americano",
  acesso: "7593 Gathering Dr, Kissimmee, FL 34747",
  precoMedio: 42,
  destaque: "Restaurante sofisticado com vista panorÃ¢mica e grelhados. Experimente o Filet Mignon com purÃª de batata trufado.",
  latitude: 28.2856,
  longitude: -81.6019,
},
{
  nome: "Grand Lobby Sushi Bar",
  regiao: "Reunion",
  tipo: "Tematico",
  acesso: "7593 Gathering Dr, Kissimmee, FL 34747",
  precoMedio: 38,
  destaque: "Sushi bar elegante com pratos asiÃ¡ticos frescos. Experimente o Sushi Combo com sashimi variado.",
  latitude: 28.2859,
  longitude: -81.6020,
},
{
  nome: "Traditions at Nicklaus Clubhouse",
  regiao: "Reunion",
  tipo: "Conforto",
  acesso: "7593 Gathering Dr, Kissimmee, FL 34747",
  precoMedio: 26,
  destaque: "Menu americano em ambiente de clube aconchegante. Experimente o Cheeseburger clÃ¡ssico com fritas.",
  latitude: 28.2872,
  longitude: -81.6001,
},
{
  nome: "7-Eleven Lunch",
  regiao: "Reunion",
  tipo: "Economico",
  acesso: "7593 Osceola Polk Line Rd, Davenport, FL 33896",
  precoMedio: 8,
  destaque: "Lanches rÃ¡pidos e conveniÃªncia para viagem. Experimente o Big Bite Hot Dog.",
  latitude: 28.2891,
  longitude: -81.6042,
},
{
  nome: "Natureâ€™s Table Reunion",
  regiao: "Reunion",
  tipo: "Saudavel",
  acesso: "7593 Gathering Dr, Kissimmee, FL 34747",
  precoMedio: 16,
  destaque: "Wraps e bowls nutritivos para refeiÃ§Ãµes leves. Experimente o Chicken Caesar Wrap.",
  latitude: 28.2884,
  longitude: -81.6031,
},

// 10 - Davenport
{
  nome: "IHOP Davenport",
  regiao: "Davenport",
  tipo: "Americano",
  acesso: "43600 US-27, Davenport, FL 33837",
  precoMedio: 17,
  destaque: "Rede americana famosa por panquecas, ovos e cafÃ©s da manhÃ£ completos. Prato tÃ­pico: Strawberry Banana Pancakes.",
  latitude: 28.2331,
  longitude: -81.6489,
},
{
  nome: "Ovation Bistro & Bar",
  regiao: "Davenport",
  tipo: "Tematico",
  acesso: "42605 US-27, Davenport, FL 33837",
  precoMedio: 32,
  destaque: "Restaurante temÃ¡tico com carnes e brunch diferenciado. Prato tÃ­pico: Smoked Brisket Hash.",
  latitude: 28.2329,
  longitude: -81.6491,
},
{
  nome: "Perkins Restaurant & Bakery Davenport",
  regiao: "Davenport",
  tipo: "Conforto",
  acesso: "43521 US-27, Davenport, FL 33837",
  precoMedio: 20,
  destaque: "CafÃ© tradicional americano com panquecas e padaria prÃ³pria. Prato tÃ­pico: Brioche French Toast Platter.",
  latitude: 28.2333,
  longitude: -81.6494,
},
{
  nome: "Burger King Davenport",
  regiao: "Davenport",
  tipo: "Economico",
  acesso: "44149 US-27, Davenport, FL 33897",
  precoMedio: 7,
  destaque: "Rede fast-food com opÃ§Ãµes acessÃ­veis de cafÃ© da manhÃ£. Prato tÃ­pico: Croissanâ€™wich de bacon e ovo.",
  latitude: 28.2335,
  longitude: -81.6487,
},
{
  nome: "Smoothie King Davenport",
  regiao: "Davenport",
  tipo: "Saudavel",
  acesso: "39871 US-27, Davenport, FL 33837",
  precoMedio: 12,
  destaque: "Smoothies nutritivos e bowls energÃ©ticos para comeÃ§ar o dia. Prato tÃ­pico: Gladiator Protein Smoothie.",
  latitude: 28.2337,
  longitude: -81.6485,
},

// 9 - Vineland Premium Outlets (AlmoÃ§o)
{
  nome: "The Cheesecake Factory Vineland",
  regiao: "Vineland Premium Outlets",
  tipo: "Americano",
  acesso: "8200 Vineland Ave, Orlando, FL 32821",
  precoMedio: 28,
  destaque: "Rede famosa com pratos variados e porÃ§Ãµes generosas. Experimente o Chicken Madeira acompanhado de um Cheesecake Original.",
  latitude: 28.3854,
  longitude: -81.4882,
  instagram: "https://www.instagram.com/cheesecakefactory/",
},
{
  nome: "Benihana Orlando",
  regiao: "Vineland Premium Outlets",
  tipo: "Tematico",
  acesso: "12650 International Dr S, Orlando, FL 32821",
  precoMedio: 45,
  destaque: "CulinÃ¡ria japonesa no estilo teppanyaki com chefs preparando os pratos na chapa. Experimente o Hibachi Steak.",
  latitude: 28.3858,
  longitude: -81.4891,
  instagram: "https://www.instagram.com/benihana/",
},
{
  nome: "BJ's Restaurant & Brewhouse Vineland",
  regiao: "Vineland Premium Outlets",
  tipo: "Conforto",
  acesso: "8763 Vineland Ave, Orlando, FL 32821",
  precoMedio: 26,
  destaque: "Menu variado com massas, carnes e pizzas, alÃ©m das cervejas artesanais. Experimente o Deep Dish Ziti.",
  latitude: 28.3860,
  longitude: -81.4894,
  instagram: "https://www.instagram.com/bjsrestaurants/",
},
{
  nome: "Panera Bread Vineland",
  regiao: "Vineland Premium Outlets",
  tipo: "Saudavel",
  acesso: "4696 Gardens Park Blvd, Orlando, FL 32839",
  precoMedio: 15,
  destaque: "SanduÃ­ches, sopas e saladas frescas em ambiente casual. Experimente o Chicken Caesar Salad.",
  latitude: 28.3857,
  longitude: -81.4890,
  instagram: "https://www.instagram.com/panerabread/",
},
{
  nome: "Olive Garden Vineland",
  regiao: "Vineland Premium Outlets",
  tipo: "Italiano",
  acesso: "12361 S Apopka Vineland Rd, Orlando, FL 32836",
  precoMedio: 22,
  destaque: "Rede italiana popular com massas e pratos fartos. Experimente o Fettuccine Alfredo.",
  latitude: 28.3862,
  longitude: -81.4887,
  instagram: "https://www.instagram.com/olivegarden/",
},


// 11 - Westgate Lakes
{
  nome: "Drafts Sports Bar & Grill",
  regiao: "Westgate Lakes",
  tipo: "Americano",
  acesso: "9500 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 28,
  destaque: "Bar esportivo com hambÃºrgueres, pizzas e pratos americanos clÃ¡ssicos, ideal para assistir jogos e curtir ambiente descontraÃ­do. Experimente as Buffalo Wings crocantes.",
  latitude: 28.4370,
  longitude: -81.4812,
},
{
  nome: "Villa Italiano Chophouse",
  regiao: "Westgate Lakes",
  tipo: "Tematico",
  acesso: "9500 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 36,
  destaque: "Restaurante italiano sofisticado com massas artesanais e carnes nobres em ambiente elegante e acolhedor. Experimente o Osso Buco com polenta cremosa.",
  latitude: 28.4368,
  longitude: -81.4809,
},
{
  nome: "Cordovano Joeâ€™s Pizza",
  regiao: "Westgate Lakes",
  tipo: "Conforto",
  acesso: "9500 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 22,
  destaque: "Pizzaria casual com opÃ§Ãµes clÃ¡ssicas e porÃ§Ãµes generosas, perfeita para refeiÃ§Ãµes rÃ¡pidas em famÃ­lia. Experimente a Pizza Pepperoni Thin Crust.",
  latitude: 28.4366,
  longitude: -81.4810,
},
{
  nome: "Subway Westgate",
  regiao: "Westgate Lakes",
  tipo: "Economico",
  acesso: "8936 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 10,
  destaque: "SanduÃ­ches personalizÃ¡veis montados na hora, prÃ¡ticos e ideais para levar. Experimente o Italian B.M.T. no pÃ£o italiano.",
  latitude: 28.4355,
  longitude: -81.4821,
},
{
  nome: "Juice Bar Westgate",
  regiao: "Westgate Lakes",
  tipo: "Saudavel",
  acesso: "9500 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 15,
  destaque: "Sucos naturais e bowls de frutas frescas, perfeitos para um lanche leve e nutritivo. Experimente o AÃ§aÃ­ Bowl com granola e banana.",
  latitude: 28.4362,
  longitude: -81.4815,
},

// 12 - Vista Cay
{
  nome: "Spencerâ€™s for Steaks and Chops",
  regiao: "Vista Cay",
  tipo: "Americano",
  acesso: "9801 International Dr, Orlando, FL 32819",
  precoMedio: 40,
  destaque: "Steakhouse sofisticada com carnes premium e ambiente elegante para ocasiÃµes especiais. Experimente o New York Strip dry-aged.",
  latitude: 28.4256,
  longitude: -81.4612,
},
{
  nome: "NYPD Pizza Vista Cay",
  regiao: "Vista Cay",
  tipo: "Tematico",
  acesso: "2589 S Hiawassee Rd, Orlando, FL 32835",
  precoMedio: 29,
  destaque: "Pizzaria estilo nova-iorquino com massas finas e sabores tradicionais. Experimente a Pizza Margherita New York-Style.",
  latitude: 28.4262,
  longitude: -81.4608,
},
{
  nome: "The Bistro â€“ Vista Cay",
  regiao: "Vista Cay",
  tipo: "Conforto",
  acesso: "4874 Cayview Ave, Orlando, FL 32819",
  precoMedio: 24,
  destaque: "Restaurante casual com pratos simples e sabor caseiro para refeiÃ§Ãµes rÃ¡pidas. Experimente o Turkey Club com chips.",
  latitude: 28.4258,
  longitude: -81.4606,
},
{
  nome: "Dominoâ€™s Pizza",
  regiao: "Vista Cay",
  tipo: "Economico",
  acesso: "8255 International Dr, Orlando, FL 32819",
  precoMedio: 11,
  destaque: "Rede de pizzas rÃ¡pidas com combos acessÃ­veis para entrega ou retirada. Experimente a Pepperoni Hand-Tossed.",
  latitude: 28.4270,
  longitude: -81.4620,
},
{
  nome: "Fresh Kitchen Vista Cay",
  regiao: "Vista Cay",
  tipo: "Saudavel",
  acesso: "2855 S Orange Ave, Orlando, FL 32806",
  precoMedio: 16,
  destaque: "Bowls personalizados com ingredientes frescos e opÃ§Ãµes nutritivas. Experimente o bowl de frango grelhado com arroz de couve-flor e legumes.",
  latitude: 28.4281,
  longitude: -81.4615,
},


// 14 - Dr. Phillips
{
  nome: "The Whiskey Orlando",
  regiao: "Dr. Phillips",
  tipo: "Americano",
  acesso: "7563 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 34,
  destaque: "Bar gourmet com hambÃºrgueres criativos e ambiente moderno. Experimente o Whiskey Burger.",
  latitude: 28.4479,
  longitude: -81.4820,
},
{
  nome: "Dragonfly Robata Grill & Sushi",
  regiao: "Dr. Phillips",
  tipo: "Tematico",
  acesso: "7972 Via Dellagio Way, Orlando, FL 32819",
  precoMedio: 39,
  destaque: "CulinÃ¡ria japonesa moderna com grelhados e sushi de alta qualidade. Experimente o Salmon Robata.",
  latitude: 28.4488,
  longitude: -81.4831,
},
{
  nome: "The H Orlando",
  regiao: "Dr. Phillips",
  tipo: "Conforto",
  acesso: "7512 Dr Phillips Blvd, Orlando, FL 32819",
  precoMedio: 28,
  destaque: "Steakhouse contemporÃ¢nea com pratos reconfortantes e porÃ§Ãµes generosas. Experimente o Ribeye com legumes assados.",
  latitude: 28.4472,
  longitude: -81.4828,
},
{
  nome: "Taco Bell Dr. Phillips",
  regiao: "Dr. Phillips",
  tipo: "Economico",
  acesso: "7531 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 9,
  destaque: "Rede mexicana rÃ¡pida e barata, ideal para refeiÃ§Ãµes expressas. Experimente o Crunchy Taco Supreme.",
  latitude: 28.4461,
  longitude: -81.4835,
},
{
  nome: "Clean Eatz Dr. Phillips",
  regiao: "Dr. Phillips",
  tipo: "Saudavel",
  acesso: "7600 Dr Phillips Blvd, Orlando, FL 32819",
  precoMedio: 15,
  destaque: "RefeiÃ§Ãµes balanceadas e bowls com opÃ§Ãµes fit e saborosas. Experimente o Build Your Own Bowl com frango grelhado.",
  latitude: 28.4465,
  longitude: -81.4826,
},


// 16 - Orlando Airport Area
{
  nome: "McCoy's Bar & Grill",
  regiao: "Orlando Airport Area",
  tipo: "Americano",
  acesso: "9300 Jeff Fuqua Blvd, Orlando, FL 32827",
  precoMedio: 33,
  destaque: "Pratos americanos clÃ¡ssicos em ambiente refinado dentro do Hyatt MCO. Experimente o Angus Burger.",
  latitude: 28.4307,
  longitude: -81.3081,
},
{
  nome: "Hemisphere Restaurant",
  regiao: "Orlando Airport Area",
  tipo: "Tematico",
  acesso: "9300 Jeff Fuqua Blvd, Orlando, FL 32827",
  precoMedio: 46,
  destaque: "Restaurante panorÃ¢mico com culinÃ¡ria internacional e vista da pista. Experimente o Filet de salmÃ£o com risoto.",
  latitude: 28.4302,
  longitude: -81.3083,
},
{
  nome: "Chili's Orlando Airport",
  regiao: "Orlando Airport Area",
  tipo: "Conforto",
  acesso: "2633 McCoy Rd, Orlando, FL 32809",
  precoMedio: 25,
  destaque: "Rede Tex-Mex com porÃ§Ãµes generosas e ambiente descontraÃ­do. Experimente o Fajita Trio.",
  latitude: 28.4441,
  longitude: -81.3085,
},
{
  nome: "Wendyâ€™s Airport Blvd",
  regiao: "Orlando Airport Area",
  tipo: "Economico",
  acesso: "5433 S Semoran Blvd, Orlando, FL 32822",
  precoMedio: 10,
  destaque: "Fast-food americano com combos prÃ¡ticos para viagem. Experimente o Baconator.",
  latitude: 28.4422,
  longitude: -81.3078,
},
{
  nome: "Natureâ€™s Table Airport Plaza",
  regiao: "Orlando Airport Area",
  tipo: "Saudavel",
  acesso: "5485 S Semoran Blvd, Orlando, FL 32822",
  precoMedio: 16,
  destaque: "Bowls, wraps e smoothies naturais para refeiÃ§Ãµes leves. Experimente o Southwest Chicken Bowl.",
  latitude: 28.4433,
  longitude: -81.3099,
},


// 17 - Downtown Orlando
{
  nome: "Hamburger Mary's",
  regiao: "Downtown Orlando",
  tipo: "Americano",
  acesso: "110 W Church St, Orlando, FL 32801",
  precoMedio: 27,
  destaque: "Hamburgueria divertida com shows ao vivo e ambiente descontraÃ­do. Experimente o Queen Mary Burger.",
  latitude: 28.5421,
  longitude: -81.3796,
},
{
  nome: "Ceviche Tapas Orlando",
  regiao: "Downtown Orlando",
  tipo: "Tematico",
  acesso: "125 W Church St, Orlando, FL 32801",
  precoMedio: 38,
  destaque: "Tapas espanholas e vinhos em espaÃ§o animado e colorido. Experimente a Paella Valenciana.",
  latitude: 28.5412,
  longitude: -81.3778,
},
{
  nome: "The Stubborn Mule",
  regiao: "Downtown Orlando",
  tipo: "Conforto",
  acesso: "100 S Eola Dr #103, Orlando, FL 32801",
  precoMedio: 28,
  destaque: "BistrÃ´ moderno com pratos americanos reconfortantes e ambiente descontraÃ­do. Experimente o Mac & Cheese trufado.",
  latitude: 28.5409,
  longitude: -81.3716,
},
{
  nome: "Jimmy Johnâ€™s",
  regiao: "Downtown Orlando",
  tipo: "Economico",
  acesso: "25 W Church St, Orlando, FL 32801",
  precoMedio: 9,
  destaque: "SanduÃ­ches rÃ¡pidos e frescos para levar ou comer no local. Experimente o Italian Night Club Sandwich.",
  latitude: 28.5409,
  longitude: -81.3730,
},
{
  nome: "The Sanctum Cafe",
  regiao: "Downtown Orlando",
  tipo: "Saudavel",
  acesso: "715 N Fern Creek Ave, Orlando, FL 32803",
  precoMedio: 18,
  destaque: "Comida vegana e orgÃ¢nica com pratos criativos e nutritivos. Experimente o Buddha Bowl vegano.",
  latitude: 28.5402,
  longitude: -81.3659,
},

// 18 - Hunter's Creek
{
  nome: "The Porch South Orange",
  regiao: "Hunter's Creek",
  tipo: "Americano",
  acesso: "4757 The Grove Dr, Windermere, FL 34786",
  precoMedio: 29,
  destaque: "Bar e restaurante descontraÃ­do com pratos americanos variados. Experimente o Smash Burger.",
  latitude: 28.3831,
  longitude: -81.4032,
},
{
  nome: "La Fiesta Mexican Grill",
  regiao: "Hunter's Creek",
  tipo: "Tematico",
  acesso: "16605 Southchase Loop, Orlando, FL 32837",
  precoMedio: 31,
  destaque: "Restaurante mexicano colorido com pratos tÃ­picos saborosos. Experimente os Tacos al Pastor.",
  latitude: 28.3838,
  longitude: -81.4010,
},
{
  nome: "Millerâ€™s Ale House",
  regiao: "Hunter's Creek",
  tipo: "Conforto",
  acesso: "12771 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 24,
  destaque: "Bar esportivo com pratos fartos e ambiente animado. Experimente o Zingers Mountain Melt.",
  latitude: 28.3852,
  longitude: -81.4047,
},
{
  nome: "Taco Bell Hunterâ€™s Creek",
  regiao: "Hunter's Creek",
  tipo: "Economico",
  acesso: "13510 John Young Pkwy, Orlando, FL 32837",
  precoMedio: 8,
  destaque: "Fast-food mexicano acessÃ­vel e rÃ¡pido para o dia a dia. Experimente o Cheesy Gordita Crunch.",
  latitude: 28.3826,
  longitude: -81.4051,
},
{
  nome: "Bolay Hunterâ€™s Creek",
  regiao: "Hunter's Creek",
  tipo: "Saudavel",
  acesso: "14311 Narcoossee Rd, Orlando, FL 32832",
  precoMedio: 16,
  destaque: "Bowls saudÃ¡veis com ingredientes frescos e combinaÃ§Ãµes personalizadas. Experimente o bowl de salmÃ£o com arroz integral.",
  latitude: 28.3839,
  longitude: -81.4026,
},

// 19 - Windermere
{
  nome: "Yellow Dog Eats",
  regiao: "Windermere",
  tipo: "Americano",
  acesso: "1236 Hempel Ave, Gotha, FL 34734",
  precoMedio: 30,
  destaque: "CafÃ© com sanduÃ­ches criativos e ambiente vintage descontraÃ­do. Experimente o pulled pork sandwich com manga.",
  latitude: 28.4967,
  longitude: -81.5384,
},
{
  nome: "Bella Tuscany",
  regiao: "Windermere",
  tipo: "Tematico",
  acesso: "13424 Summerport Village Pkwy, Windermere, FL 34786",
  precoMedio: 35,
  destaque: "CulinÃ¡ria italiana tradicional em ambiente acolhedor e elegante. Experimente o Ravioli de lagosta.",
  latitude: 28.4938,
  longitude: -81.5371,
},
{
  nome: "Peach Valley Cafe",
  regiao: "Windermere",
  tipo: "Conforto",
  acesso: "1216 S Orange Ave, Orlando, FL 32806",
  precoMedio: 23,
  destaque: "CafÃ© casual com cafÃ© da manhÃ£ e almoÃ§o reconfortantes. Experimente o Apple Fritter Pancakes.",
  latitude: 28.4952,
  longitude: -81.5362,
},
{
  nome: "McDonaldâ€™s Windermere",
  regiao: "Windermere",
  tipo: "Economico",
  acesso: "7836 Winter Garden Vineland Rd, Windermere, FL 34786",
  precoMedio: 7,
  destaque: "Rede fast-food com lanches rÃ¡pidos e acessÃ­veis. Experimente o Big Mac clÃ¡ssico.",
  latitude: 28.4940,
  longitude: -81.5350,
},
{
  nome: "Greenbeat Windermere",
  regiao: "Windermere",
  tipo: "Saudavel",
  acesso: "4750 The Grove Dr, Windermere, FL 34786",
  precoMedio: 17,
  destaque: "Bowls e saladas frescas com ingredientes naturais e saudÃ¡veis. Experimente o bowl Mediterranean Chickpea.",
  latitude: 28.4956,
  longitude: -81.5368,
},

// 20 - Winter Garden
{
  nome: "MoonCricket Grille",
  regiao: "Winter Garden",
  tipo: "Americano",
  acesso: "14 W Plant St, Winter Garden, FL 34787",
  precoMedio: 30,
  destaque: "Restaurante tradicional com pratos americanos variados e ambiente vibrante. Experimente o Blackened Chicken Pasta.",
  latitude: 28.5657,
  longitude: -81.5871,
},
{
  nome: "Crooked Can Brewing Company",
  regiao: "Winter Garden",
  tipo: "Tematico",
  acesso: "426 W Plant St, Winter Garden, FL 34787",
  precoMedio: 33,
  destaque: "Cervejaria artesanal dentro do Plant Street Market com ambiente temÃ¡tico e tours. Experimente o High Stepper IPA.",
  latitude: 28.5649,
  longitude: -81.5863,
},
{
  nome: "Urban on Plant Kitchen & Bar",
  regiao: "Winter Garden",
  tipo: "Conforto",
  acesso: "132 W Plant St, Winter Garden, FL 34787",
  precoMedio: 28,
  destaque: "BistrÃ´ americano moderno com pratos sazonais e ambiente aconchegante. Experimente o Flatbread de frango com pesto.",
  latitude: 28.5652,
  longitude: -81.5868,
},
{
  nome: "Taco Bell Winter Garden",
  regiao: "Winter Garden",
  tipo: "Economico",
  acesso: "13750 W Colonial Dr, Winter Garden, FL 34787",
  precoMedio: 8,
  destaque: "Rede mexicana acessÃ­vel com combos rÃ¡pidos e econÃ´micos. Experimente o Burrito Supreme.",
  latitude: 28.5642,
  longitude: -81.5850,
},
{
  nome: "Plant Street Market â€“ Pressâ€™d",
  regiao: "Winter Garden",
  tipo: "Saudavel",
  acesso: "426 W Plant St, Winter Garden, FL 34787",
  precoMedio: 18,
  destaque: "Mercado local com bowls e sucos naturais frescos. Experimente o AÃ§aÃ­ Bowl com frutas vermelhas.",
  latitude: 28.5648,
  longitude: -81.5862,
},

// 21 - Altamonte Springs
{
  nome: "Bahama Breeze",
  regiao: "Altamonte Springs",
  tipo: "Americano",
  acesso: "499 E Altamonte Dr, Altamonte Springs, FL 32701",
  precoMedio: 29,
  destaque: "Restaurante tropical com pratos caribenhos e americanos. Prato tÃ­pico: Jerk Chicken Pasta.",
  latitude: 28.6655,
  longitude: -81.3659,
},
{
  nome: "Kobe Japanese Steakhouse",
  regiao: "Altamonte Springs",
  tipo: "Tematico",
  acesso: "468 W State Rd 436, Altamonte Springs, FL 32714",
  precoMedio: 40,
  destaque: "Show culinÃ¡rio teppanyaki com pratos japoneses saborosos. Prato tÃ­pico: Filet Mignon Teppanyaki.",
  latitude: 28.6634,
  longitude: -81.3712,
},
{
  nome: "Cracker Barrel Old Country Store",
  regiao: "Altamonte Springs",
  tipo: "Conforto",
  acesso: "1000 Lake Murray Blvd, Altamonte Springs, FL 32714",
  precoMedio: 20,
  destaque: "CulinÃ¡ria sulista caseira com ambiente rÃºstico acolhedor. Prato tÃ­pico: Chicken nâ€™ Dumplins.",
  latitude: 28.6640,
  longitude: -81.3750,
},
{
  nome: "Chick-fil-A Altamonte",
  regiao: "Altamonte Springs",
  tipo: "Economico",
  acesso: "302 E Altamonte Dr, Altamonte Springs, FL 32701",
  precoMedio: 9,
  destaque: "Frango frito famoso com atendimento rÃ¡pido e eficiente. Prato tÃ­pico: Spicy Chicken Sandwich.",
  latitude: 28.6677,
  longitude: -81.3703,
},
{
  nome: "Vitality Bowls Altamonte",
  regiao: "Altamonte Springs",
  tipo: "Saudavel",
  acesso: "451 E Altamonte Dr, Altamonte Springs, FL 32701",
  precoMedio: 17,
  destaque: "Bowls de aÃ§aÃ­ e superfoods frescos e nutritivos. Prato tÃ­pico: Nutty Bowl.",
  latitude: 28.6642,
  longitude: -81.3653,
},

// 22 - Clermont
{
  nome: "Chiliâ€™s Grill & Bar Clermont",
  regiao: "Clermont",
  tipo: "Americano",
  acesso: "US-27",
  precoMedio: 23,
  destaque: "Comida americana com um toque tex-mex. NÃ£o deixe de experimentar o Bacon Ranch Chicken Quesadillas. PreÃ§o mÃ©dio: $23. Prato tÃ­pico: Bacon Ranch Chicken Quesadillas.",
  latitude: 28.5411,
  longitude: -81.7260,
},
{
  nome: "The Crooked Spoon Gastropub",
  regiao: "Clermont",
  tipo: "Tematico",
  acesso: "Downtown Clermont",
  precoMedio: 38,
  destaque: "Ambiente diferenciado com pratos criativos. NÃ£o deixe de experimentar o Crooked Burger com batata trufada. PreÃ§o mÃ©dio: $38. Prato tÃ­pico: Crooked Burger.",
  latitude: 28.5534,
  longitude: -81.7689,
},
{
  nome: "Bob Evans Clermont",
  regiao: "Clermont",
  tipo: "Conforto",
  acesso: "US-27",
  precoMedio: 20,
  destaque: "AlmoÃ§o caseiro com sabores tradicionais. NÃ£o deixe de pedir o Country Fried Steak com purÃª. PreÃ§o mÃ©dio: $20. Prato tÃ­pico: Country Fried Steak.",
  latitude: 28.5379,
  longitude: -81.7165,
},
{
  nome: "Taco Bell Clermont",
  regiao: "Clermont",
  tipo: "Economico",
  acesso: "US-27",
  precoMedio: 9,
  destaque: "RÃ¡pido, barato e saboroso. NÃ£o deixe de aproveitar o Crunchwrap Supreme com refrigerante. PreÃ§o mÃ©dio: $9. Prato tÃ­pico: Crunchwrap Supreme.",
  latitude: 28.5392,
  longitude: -81.7222,
},
{
  nome: "Vitality Bowls Clermont",
  regiao: "Clermont",
  tipo: "Saudavel",
  acesso: "RegiÃ£o central de Clermont",
  precoMedio: 14,
  destaque: "Bowls de aÃ§aÃ­, smoothies e refeiÃ§Ãµes naturais. NÃ£o deixe de pedir o Nutty Bowl com granola crocante. PreÃ§o mÃ©dio: $14. Prato tÃ­pico: Nutty Bowl.",
  latitude: 28.5450,
  longitude: -81.7229,
},

// 23 - Oak Ridge
{
  nome: "Applebeeâ€™s Grill + Bar",
  regiao: "Oak Ridge",
  tipo: "Americano",
  acesso: "6324 S Orange Blossom Trl, Orlando, FL 32809",
  precoMedio: 24,
  destaque: "Rede americana com pratos variados e ambiente descontraÃ­do. Prato tÃ­pico: Bourbon Street Steak.",
  latitude: 28.4741,
  longitude: -81.4123,
},
{
  nome: "CafÃ© Tu Tu Tango",
  regiao: "Oak Ridge",
  tipo: "Tematico",
  acesso: "8625 International Dr, Orlando, FL 32819",
  precoMedio: 36,
  destaque: "Restaurante artÃ­stico com tapas criativas e ambiente vibrante. Prato tÃ­pico: Cajun Chicken Egg Rolls.",
  latitude: 28.4542,
  longitude: -81.4301,
},
{
  nome: "Perkins Restaurant & Bakery",
  regiao: "Oak Ridge",
  tipo: "Conforto",
  acesso: "6813 S Orange Blossom Trl, Orlando, FL 32809",
  precoMedio: 20,
  destaque: "Restaurante casual com pratos caseiros e padaria prÃ³pria. Prato tÃ­pico: Chicken Pot Pie.",
  latitude: 28.4722,
  longitude: -81.4135,
},
{
  nome: "Pollo Tropical Oak Ridge",
  regiao: "Oak Ridge",
  tipo: "Economico",
  acesso: "6315 S Orange Blossom Trl, Orlando, FL 32809",
  precoMedio: 11,
  destaque: "Rede caribenha com pratos rÃ¡pidos e saborosos. Prato tÃ­pico: TropiChop Bowl.",
  latitude: 28.4729,
  longitude: -81.4141,
},
{
  nome: "Smoothie King Oak Ridge",
  regiao: "Oak Ridge",
  tipo: "Saudavel",
  acesso: "6303 S Orange Blossom Trl, Orlando, FL 32809",
  precoMedio: 13,
  destaque: "Smoothies e opÃ§Ãµes leves para um lanche saudÃ¡vel. Prato tÃ­pico: Gladiator Protein Smoothie.",
  latitude: 28.4736,
  longitude: -81.4138,
},

// 24 - Maingate East
{
  nome: "Olive Garden Maingate East",
  regiao: "Maingate East",
  tipo: "Americano",
  acesso: "5021 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 25,
  destaque: "Massas e pratos italianos-americanos em ambiente familiar. Prato tÃ­pico: Tour of Italy.",
  latitude: 28.3321,
  longitude: -81.5092,
},
{
  nome: "Pirateâ€™s Dinner Adventure Lunch",
  regiao: "Maingate East",
  tipo: "Tematico",
  acesso: "6400 Carrier Dr, Orlando, FL 32819",
  precoMedio: 48,
  destaque: "Show temÃ¡tico de piratas com jantar incluso e diversÃ£o garantida. Prato tÃ­pico: Roasted Chicken.",
  latitude: 28.3338,
  longitude: -81.5124,
},
{
  nome: "Cracker Barrel Old Country Store",
  regiao: "Maingate East",
  tipo: "Conforto",
  acesso: "5400 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 22,
  destaque: "CulinÃ¡ria caseira americana com ambiente rÃºstico acolhedor. Prato tÃ­pico: Country Fried Steak.",
  latitude: 28.3318,
  longitude: -81.5103,
},
{
  nome: "Taco Bell Maingate East",
  regiao: "Maingate East",
  tipo: "Economico",
  acesso: "5250 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 9,
  destaque: "Fast-food mexicano rÃ¡pido e econÃ´mico. Prato tÃ­pico: Nachos BellGrande.",
  latitude: 28.3329,
  longitude: -81.5100,
},
{
  nome: "Natureâ€™s Table Maingate East",
  regiao: "Maingate East",
  tipo: "Saudavel",
  acesso: "5045 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 14,
  destaque: "Bowls, wraps e saladas frescas para uma refeiÃ§Ã£o leve. Prato tÃ­pico: Baja Chicken Wrap.",
  latitude: 28.3331,
  longitude: -81.5095,
},
// 25 - Maingate West
{
  nome: "Ford's Garage Sunset Walk",
  regiao: "Maingate West",
  tipo: "Tematico",
  acesso: "3251 Margaritaville Blvd, Kissimmee, FL 34747",
  precoMedio: 32,
  destaque: "HambÃºrgueres gourmet em ambiente temÃ¡tico automotivo com decoraÃ§Ã£o de garagem. Prato tÃ­pico: Fordâ€™s Signature Burger.",
  latitude: 28.3349,
  longitude: -81.5886,
},
{
  nome: "Loganâ€™s Roadhouse",
  regiao: "Maingate West",
  tipo: "Americano",
  acesso: "7480 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 26,
  destaque: "Carnes grelhadas e ambiente descontraÃ­do estilo roadhouse. Prato tÃ­pico: Roadhouse Sirloin.",
  latitude: 28.3284,
  longitude: -81.5932,
},
{
  nome: "Bob Evans Maingate West",
  regiao: "Maingate West",
  tipo: "Conforto",
  acesso: "7411 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 21,
  destaque: "Pratos tradicionais americanos e cafÃ© da manhÃ£ o dia todo. Prato tÃ­pico: Country Biscuit Breakfast.",
  latitude: 28.3275,
  longitude: -81.5928,
},
{
  nome: "Wendyâ€™s Maingate West",
  regiao: "Maingate West",
  tipo: "Economico",
  acesso: "7603 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 10,
  destaque: "Fast-food americano com combos rÃ¡pidos e acessÃ­veis. Prato tÃ­pico: Baconator.",
  latitude: 28.3288,
  longitude: -81.5935,
},
{
  nome: "Freshii Maingate West",
  regiao: "Maingate West",
  tipo: "Saudavel",
  acesso: "7601 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 16,
  destaque: "Bowls e wraps frescos com ingredientes saudÃ¡veis e saborosos. Prato tÃ­pico: Buddhaâ€™s Satay Bowl.",
  latitude: 28.3292,
  longitude: -81.5931,
},

// 26 - Bonnet Creek
{
  nome: "Zeta Asia at Hilton Bonnet Creek",
  regiao: "Bonnet Creek",
  tipo: "Americano",
  acesso: "14100 Bonnet Creek Resort Ln, Orlando, FL 32821",
  precoMedio: 35,
  destaque: "CulinÃ¡ria contemporÃ¢nea com toques asiÃ¡ticos e ambiente sofisticado. Prato tÃ­pico: Asian Short Ribs.",
  latitude: 28.3633,
  longitude: -81.5242,
},
{
  nome: "La Luce at Hilton Bonnet Creek",
  regiao: "Bonnet Creek",
  tipo: "Tematico",
  acesso: "14100 Bonnet Creek Resort Ln, Orlando, FL 32821",
  precoMedio: 52,
  destaque: "Restaurante italiano refinado com massas artesanais e pratos sofisticados. Prato tÃ­pico: Lasagna Napoletana.",
  latitude: 28.3635,
  longitude: -81.5239,
},
{
  nome: "Harvest Bistro",
  regiao: "Bonnet Creek",
  tipo: "Conforto",
  acesso: "14200 Bonnet Creek Resort Ln, Orlando, FL 32821",
  precoMedio: 29,
  destaque: "Buffet e pratos reconfortantes em ambiente casual e agradÃ¡vel. Prato tÃ­pico: Grilled Chicken Club.",
  latitude: 28.3627,
  longitude: -81.5244,
},
{
  nome: "Subway Bonnet Creek",
  regiao: "Bonnet Creek",
  tipo: "Economico",
  acesso: "14001 Chelonia Pkwy, Orlando, FL 32821",
  precoMedio: 9,
  destaque: "SanduÃ­ches rÃ¡pidos e customizÃ¡veis a preÃ§os acessÃ­veis. Prato tÃ­pico: Italian B.M.T.",
  latitude: 28.3652,
  longitude: -81.5215,
},
{
  nome: "Spoon & Sprout Bonnet Creek",
  regiao: "Bonnet Creek",
  tipo: "Saudavel",
  acesso: "14200 Bonnet Creek Resort Ln, Orlando, FL 32821",
  precoMedio: 18,
  destaque: "OpÃ§Ãµes leves e nutritivas como wraps, saladas e smoothies. Prato tÃ­pico: Mediterranean Wrap.",
  latitude: 28.3631,
  longitude: -81.5227,
},

// 28 - Flamingo Crossings
{
  nome: "Five Guys Flamingo",
  regiao: "Flamingo Crossings",
  tipo: "Americano",
  acesso: "14005 Hartzog Rd, Winter Garden, FL 34787",
  precoMedio: 18,
  destaque: "HambÃºrgueres frescos e batatas artesanais em porÃ§Ãµes generosas. Prato tÃ­pico: Cheeseburger com Cajun Fries.",
  latitude: 28.3772,
  longitude: -81.6111,
},
{
  nome: "Hash House A Go Go",
  regiao: "Flamingo Crossings",
  tipo: "Tematico",
  acesso: "14035 Flamingo Crossings Blvd, Winter Garden, FL 34787",
  precoMedio: 39,
  destaque: "PorÃ§Ãµes grandes e pratos criativos com toque caseiro. Prato tÃ­pico: Sage Fried Chicken & Waffles.",
  latitude: 28.3781,
  longitude: -81.6103,
},
{
  nome: "Applebee's Flamingo",
  regiao: "Flamingo Crossings",
  tipo: "Conforto",
  acesso: "14045 Flamingo Crossings Blvd, Winter Garden, FL 34787",
  precoMedio: 23,
  destaque: "Rede americana com pratos variados e ambiente familiar. Prato tÃ­pico: Bourbon Street Chicken & Shrimp.",
  latitude: 28.3775,
  longitude: -81.6109,
},
{
  nome: "Taco Bell Flamingo",
  regiao: "Flamingo Crossings",
  tipo: "Economico",
  acesso: "14055 Flamingo Crossings Blvd, Winter Garden, FL 34787",
  precoMedio: 8,
  destaque: "Fast-food mexicano rÃ¡pido e acessÃ­vel com combos variados. Prato tÃ­pico: Crunchwrap Supreme.",
  latitude: 28.3780,
  longitude: -81.6115,
},
{
  nome: "Green Fork CafÃ©",
  regiao: "Flamingo Crossings",
  tipo: "Saudavel",
  acesso: "14065 Flamingo Crossings Blvd, Winter Garden, FL 34787",
  precoMedio: 15,
  destaque: "Saladas, wraps e smoothies orgÃ¢nicos para refeiÃ§Ãµes leves. Prato tÃ­pico: Green Goddess Bowl.",
  latitude: 28.3788,
  longitude: -81.6107,
},

// 29 - MetroWest
{
  nome: "Teak Neighborhood Grill",
  regiao: "MetroWest",
  tipo: "Americano",
  acesso: "6400 Time Square Ave, Orlando, FL 32835",
  precoMedio: 29,
  destaque: "HambÃºrgueres artesanais e pratos criativos em ambiente descontraÃ­do. Prato tÃ­pico: Drunken Monk Burger.",
  latitude: 28.5182,
  longitude: -81.4807,
},
{
  nome: "Outta Control Magic Show Lunch",
  regiao: "MetroWest",
  tipo: "Tematico",
  acesso: "9067 International Dr, Orlando, FL 32819",
  precoMedio: 43,
  destaque: "Show de mÃ¡gica interativo com jantar incluso e muita diversÃ£o, mantendo a proposta temÃ¡tica. Prato tÃ­pico: Pizza All-You-Can-Eat.",
  latitude: 28.4430,
  longitude: -81.4705,
},
{
  nome: "Metro Diner",
  regiao: "MetroWest",
  tipo: "Conforto",
  acesso: "9858 International Dr, Orlando, FL 32819",
  precoMedio: 22,
  destaque: "Pratos clÃ¡ssicos americanos com porÃ§Ãµes generosas. Prato tÃ­pico: Chicken & Waffles.",
  latitude: 28.5190,
  longitude: -81.4790,
},
{
  nome: "Taco Maker MetroWest",
  regiao: "MetroWest",
  tipo: "Economico",
  acesso: "6401 Raleigh St, Orlando, FL 32835",
  precoMedio: 9,
  destaque: "Rede tex-mex rÃ¡pida com opÃ§Ãµes acessÃ­veis e saborosas. Prato tÃ­pico: Burrito Supremo.",
  latitude: 28.5177,
  longitude: -81.4815,
},
{
  nome: "Fresh Kitchen MetroWest",
  regiao: "MetroWest",
  tipo: "Saudavel",
  acesso: "4101 Millenia Blvd, Orlando, FL 32839",
  precoMedio: 16,
  destaque: "Bowls personalizÃ¡veis com ingredientes frescos e nutritivos. Prato tÃ­pico: Six Bowl (mix de proteÃ­nas, grÃ£os e vegetais).",
  latitude: 28.5165,
  longitude: -81.4822,
},

// 30 - Winter Park
{
  nome: "The Ravenous Pig",
  regiao: "Winter Park",
  tipo: "Americano",
  acesso: "565 W Fairbanks Ave, Winter Park, FL 32789",
  precoMedio: 38,
  destaque: "Gastrobar elegante com pratos sazonais criativos. Prato tÃ­pico: Pub Burger.",
  latitude: 28.5973,
  longitude: -81.3555,
},
{
  nome: "Bosphorous Turkish Cuisine",
  regiao: "Winter Park",
  tipo: "Tematico",
  acesso: "108 S Park Ave, Winter Park, FL 32789",
  precoMedio: 40,
  destaque: "CulinÃ¡ria turca autÃªntica com ambiente acolhedor. Prato tÃ­pico: PÃ£o Pide com Homus.",
  latitude: 28.5962,
  longitude: -81.3514,
},
{
  nome: "Hillstone Restaurant",
  regiao: "Winter Park",
  tipo: "Conforto",
  acesso: "215 S Orlando Ave, Winter Park, FL 32789",
  precoMedio: 33,
  destaque: "Restaurante Ã  beira do lago com pratos reconfortantes. Prato tÃ­pico: Prime Rib Sandwich.",
  latitude: 28.5968,
  longitude: -81.3702,
},
{
  nome: "BurgerFi Winter Park",
  regiao: "Winter Park",
  tipo: "Economico",
  acesso: "538 S Park Ave, Winter Park, FL 32789",
  precoMedio: 11,
  destaque: "Rede de hambÃºrgueres naturais com opÃ§Ãµes vegetarianas. Prato tÃ­pico: BurgerFi Cheeseburger.",
  latitude: 28.5991,
  longitude: -81.3539,
},
{
  nome: "Create Your Nature",
  regiao: "Winter Park",
  tipo: "Saudavel",
  acesso: "1284 Orange Ave, Winter Park, FL 32789",
  precoMedio: 17,
  destaque: "AÃ§aÃ­ bowls, saladas e wraps com ingredientes frescos. Prato tÃ­pico: Nutty by Nature AÃ§aÃ­ Bowl.",
  latitude: 28.6004,
  longitude: -81.3533,
},

// 31 - Osceola Parkway
{
  nome: "Texas Roadhouse Osceola",
  regiao: "Osceola Parkway",
  tipo: "Americano",
  acesso: "5351 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 27,
  destaque: "Carnes grelhadas, pÃ£o amanteigado e ambiente texano animado. Prato tÃ­pico: Fall-Off-The-Bone Ribs.",
  latitude: 28.3354,
  longitude: -81.4812,
},
{
  nome: "Planet Hollywood Lunch",
  regiao: "Osceola Parkway",
  tipo: "Tematico",
  acesso: "1506 E Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 45,
  destaque: "Restaurante cinematogrÃ¡fico com pratos criativos e decoraÃ§Ã£o temÃ¡tica. Prato tÃ­pico: L.A. Lasagna.",
  latitude: 28.3706,
  longitude: -81.5167,
},
{
  nome: "Perkins Restaurant Osceola",
  regiao: "Osceola Parkway",
  tipo: "Conforto",
  acesso: "1700 W Osceola Pkwy, Kissimmee, FL 34741",
  precoMedio: 19,
  destaque: "Comida caseira e padaria em ambiente familiar. Prato tÃ­pico: Country Club Melt.",
  latitude: 28.3323,
  longitude: -81.4881,
},
{
  nome: "Burger King Osceola Parkway",
  regiao: "Osceola Parkway",
  tipo: "Economico",
  acesso: "5320 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 8,
  destaque: "Fast-food tradicional com combos rÃ¡pidos e acessÃ­veis. Prato tÃ­pico: Whopper.",
  latitude: 28.3342,
  longitude: -81.4790,
},
{
  nome: "Tropical Smoothie CafÃ© Osceola",
  regiao: "Osceola Parkway",
  tipo: "Saudavel",
  acesso: "5770 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 13,
  destaque: "Smoothies, wraps e bowls nutritivos e saborosos. Prato tÃ­pico: Island Green Smoothie.",
  latitude: 28.3360,
  longitude: -81.4801,
},

// 32 - Millenia Area
{
  nome: "The Cheesecake Factory Millenia",
  regiao: "Millenia Area",
  tipo: "Conforto",
  acesso: "4200 Conroy Rd, Orlando, FL 32839",
  precoMedio: 28,
  destaque: "Rede famosa com pratos variados e sobremesas icÃ´nicas. Prato tÃ­pico: Chicken Madeira.",
  latitude: 28.4885,
  longitude: -81.4306,
},
{
  nome: "P.F. Changâ€™s Millenia",
  regiao: "Millenia Area",
  tipo: "Tematico",
  acesso: "4200 Conroy Rd, Orlando, FL 32839",
  precoMedio: 38,
  destaque: "CulinÃ¡ria asiÃ¡tica moderna em ambiente sofisticado. Prato tÃ­pico: Mongolian Beef.",
  latitude: 28.4887,
  longitude: -81.4301,
},
{
  nome: "Brio Italian Grille",
  regiao: "Millenia Area",
  tipo: "Americano",
  acesso: "4200 Conroy Rd, Orlando, FL 32839",
  precoMedio: 32,
  destaque: "Pratos italianos e americanos em ambiente elegante. Prato tÃ­pico: Pasta alla Vodka.",
  latitude: 28.4892,
  longitude: -81.4299,
},
{
  nome: "Chipotle Millenia",
  regiao: "Millenia Area",
  tipo: "Economico",
  acesso: "4200 Conroy Rd, Orlando, FL 32839",
  precoMedio: 10,
  destaque: "Burritos e bowls rÃ¡pidos com ingredientes frescos. Prato tÃ­pico: Chicken Burrito Bowl.",
  latitude: 28.4896,
  longitude: -81.4297,
},
{
  nome: "Bolay Millenia",
  regiao: "Millenia Area",
  tipo: "Saudavel",
  acesso: "4192 Conroy Rd, Orlando, FL 32839",
  precoMedio: 16,
  destaque: "Bowls nutritivos personalizÃ¡veis com ingredientes saudÃ¡veis. Prato tÃ­pico: Teriyaki Chicken Bowl.",
  latitude: 28.4901,
  longitude: -81.4293,
},

// 33 - Southchase
{
  nome: "Miller's Ale House Southchase",
  regiao: "Southchase",
  tipo: "Americano",
  acesso: "12779 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 26,
  destaque: "Bar esportivo com pratos americanos e ambiente animado. Prato tÃ­pico: Zinger Mountain Melt.",
  latitude: 28.3857,
  longitude: -81.3972,
},
{
  nome: "Chuy's Tex-Mex Southchase",
  regiao: "Southchase",
  tipo: "Tematico",
  acesso: "6688 S Semoran Blvd, Orlando, FL 32822",
  precoMedio: 31,
  destaque: "Rede Tex-Mex divertida com pratos coloridos e saborosos. Prato tÃ­pico: Chicka-Chicka Boom-Boom Enchiladas.",
  latitude: 28.3842,
  longitude: -81.3964,
},
{
  nome: "Perkins Restaurant & Bakery",
  regiao: "Southchase",
  tipo: "Conforto",
  acesso: "1995 E Osceola Pkwy, Kissimmee, FL 34743",
  precoMedio: 20,
  destaque: "Menu variado e pratos reconfortantes o dia todo. Prato tÃ­pico: Chicken Pot Pie.",
  latitude: 28.3845,
  longitude: -81.3959,
},
{
  nome: "Pollo Tropical Southchase",
  regiao: "Southchase",
  tipo: "Economico",
  acesso: "12001 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 9,
  destaque: "Rede caribenha com refeiÃ§Ãµes rÃ¡pidas e acessÃ­veis. Prato tÃ­pico: TropiChop Bowl.",
  latitude: 28.3836,
  longitude: -81.3966,
},
{
  nome: "Tropical Smoothie Cafe Southchase",
  regiao: "Southchase",
  tipo: "Saudavel",
  acesso: "12005 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 14,
  destaque: "Smoothies, wraps e bowls leves e nutritivos. Prato tÃ­pico: Bahama Mama Smoothie.",
  latitude: 28.3849,
  longitude: -81.3954,
},

// 34 - Baldwin Park
{
  nome: "Seito Sushi Baldwin",
  regiao: "Baldwin Park",
  tipo: "Tematico",
  acesso: "4898 New Broad St, Orlando, FL 32814",
  precoMedio: 43,
  destaque: "Sushi bar moderno com pratos japoneses sofisticados. Prato tÃ­pico: Dragon Roll.",
  latitude: 28.5675,
  longitude: -81.3272,
},
{
  nome: "The Osprey Tavern",
  regiao: "Baldwin Park",
  tipo: "Americano",
  acesso: "4899 New Broad St, Orlando, FL 32814",
  precoMedio: 36,
  destaque: "Gastrobar refinado com pratos americanos criativos. Prato tÃ­pico: Osprey Burger.",
  latitude: 28.5673,
  longitude: -81.3270,
},
{
  nome: "Gators Dockside Baldwin",
  regiao: "Baldwin Park",
  tipo: "Conforto",
  acesso: "4982 New Broad St, Orlando, FL 32814",
  precoMedio: 23,
  destaque: "Bar esportivo com pratos fartos e clima descontraÃ­do. Prato tÃ­pico: Buffalo Wings.",
  latitude: 28.5671,
  longitude: -81.3268,
},
{
  nome: "Tijuana Flats Baldwin Park",
  regiao: "Baldwin Park",
  tipo: "Economico",
  acesso: "4982 New Broad St, Orlando, FL 32814",
  precoMedio: 10,
  destaque: "Rede Tex-Mex rÃ¡pida e acessÃ­vel para refeiÃ§Ãµes casuais. Prato tÃ­pico: Dos Tacos Meal.",
  latitude: 28.5668,
  longitude: -81.3267,
},
{
  nome: "Green Kitchen Baldwin Park",
  regiao: "Baldwin Park",
  tipo: "Saudavel",
  acesso: "4982 New Broad St, Orlando, FL 32814",
  precoMedio: 15,
  destaque: "Saladas, bowls e wraps com ingredientes frescos e leves. Prato tÃ­pico: Avocado Quinoa Bowl.",
  latitude: 28.5666,
  longitude: -81.3265,
},

// 35 - Sand Lake Road Area
{
  nome: "Rocco's Tacos and Tequila Bar",
  regiao: "Sand Lake Road Area",
  tipo: "Americano",
  acesso: "7468 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 34,
  destaque: "Bar animado com pratos mexicanos e coquetÃ©is variados. Prato tÃ­pico: Tacos al Pastor.",
  latitude: 28.4512,
  longitude: -81.4899,
},
{
  nome: "The Melting Pot Orlando",
  regiao: "Sand Lake Road Area",
  tipo: "Tematico",
  acesso: "7549 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 49,
  destaque: "Fondue refinado em ambiente romÃ¢ntico e aconchegante. Prato tÃ­pico: Fondue de Queijo SuÃ­Ã§o.",
  latitude: 28.4519,
  longitude: -81.4907,
},
{
  nome: "The Whiskey",
  regiao: "Sand Lake Road Area",
  tipo: "Conforto",
  acesso: "7563 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 27,
  destaque: "HambÃºrgueres criativos com ingredientes frescos e molhos especiais. Prato tÃ­pico: The Whiskey Burger.",
  latitude: 28.4517,
  longitude: -81.4888,
},
{
  nome: "Moeâ€™s Southwest Grill",
  regiao: "Sand Lake Road Area",
  tipo: "Economico",
  acesso: "7681 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 9,
  destaque: "Tex-Mex rÃ¡pido com opÃ§Ãµes personalizÃ¡veis e acessÃ­veis. Prato tÃ­pico: Homewrecker Burrito.",
  latitude: 28.4508,
  longitude: -81.4893,
},
{
  nome: "Too Much Sauce",
  regiao: "Sand Lake Road Area",
  tipo: "Saudavel",
  acesso: "7455 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 17,
  destaque: "Bowls saudÃ¡veis com molhos exclusivos e frescos. Prato tÃ­pico: Chicken Teriyaki Bowl.",
  latitude: 28.4505,
  longitude: -81.4900,
},

// 36 - North Kissimmee
{
  nome: "Medieval Times Lunch Hall",
  regiao: "North Kissimmee",
  tipo: "Tematico",
  acesso: "4510 W Vine St, Kissimmee, FL 34746",
  precoMedio: 45,
  destaque: "Show medieval com batalhas e jantar incluso. Prato tÃ­pico: Roasted Chicken Medieval Feast.",
  latitude: 28.3056,
  longitude: -81.4692,
},
{
  nome: "Broadway Pizza Bar",
  regiao: "North Kissimmee",
  tipo: "Americano",
  acesso: "403 Broadway, Kissimmee, FL 34741",
  precoMedio: 24,
  destaque: "Pizzaria e restaurante americano com ambiente familiar. Prato tÃ­pico: Broadway Special Pizza.",
  latitude: 28.2919,
  longitude: -81.4106,
},
{
  nome: "Dennyâ€™s North Kissimmee",
  regiao: "North Kissimmee",
  tipo: "Conforto",
  acesso: "4018 W Vine St, Kissimmee, FL 34741",
  precoMedio: 18,
  destaque: "Rede americana com cafÃ© da manhÃ£ e almoÃ§o o dia todo. Prato tÃ­pico: Grand Slam Breakfast.",
  latitude: 28.3050,
  longitude: -81.4695,
},
{
  nome: "Taco Bell North Kissimmee",
  regiao: "North Kissimmee",
  tipo: "Economico",
  acesso: "4040 W Vine St, Kissimmee, FL 34741",
  precoMedio: 8,
  destaque: "Fast-food mexicano rÃ¡pido e acessÃ­vel. Prato tÃ­pico: Beef Chalupa Supreme.",
  latitude: 28.3062,
  longitude: -81.4697,
},
{
  nome: "Natureâ€™s Table Kissimmee",
  regiao: "North Kissimmee",
  tipo: "Saudavel",
  acesso: "102 Park Place Blvd, Kissimmee, FL 34741",
  precoMedio: 13,
  destaque: "Wraps, bowls e smoothies frescos e nutritivos. Prato tÃ­pico: Baja Chicken Wrap.",
  latitude: 28.3047,
  longitude: -81.4701,
},


];
