export const cafesProximos = [

// 1 - International Drive
{
  nome: "The Capital Grille",
  regiao: "International Drive",
  tipo: "Americano",
  acesso: "9101 International Dr, Orlando, FL 32819",
  precoMedio: 36,
  destaque: "Steaks, hambúrgueres gourmet e saladas em ambiente refinado. Prato sugerido: Dry-Aged NY Strip.",
  latitude: 28.4375,
  longitude: -81.4699,
  instagram: "https://www.instagram.com/thecapitalgrille/",
},

{
  nome: "Maggiano's Little Italy (Pointe Orlando)",
  regiao: "International Drive",
  tipo: "Conforto",
  acesso: "9101 International Dr Suite 2400, Orlando, FL 32819",
  precoMedio: 28,
  destaque: "Massas e clássicos italianos em ambiente aconchegante. Prato sugerido: Chicken Parmesan.",
  latitude: 28.4360,
  longitude: -81.4702,
  instagram: "https://www.instagram.com/maggianoslittleitaly/",
},

{
  nome: "Shake Shack – ICON Park",
  regiao: "International Drive",
  tipo: "Economico",
  acesso: "8359 International Dr, Orlando, FL 32819",
  precoMedio: 12,
  destaque: "Hambúrgueres e batatas artesanais servidos rapidamente. Prato sugerido: ShackBurger com crinkle-cut fries.",
  latitude: 28.4441,
  longitude: -81.4707,
  instagram: "https://www.instagram.com/shakeshack/",
},

{
  nome: "Nature’s Table (Convention Center)",
  regiao: "International Drive",
  tipo: "Saudavel",
  acesso: "9800 International Dr (OCCC), Orlando, FL 32819",
  precoMedio: 15,
  destaque: "Saladas, wraps e bowls leves dentro do centro de convenções. Prato sugerido: Chicken Caesar Wrap.",
  latitude: 28.425,
  longitude: -81.462,
  instagram: "https://www.instagram.com/naturestable/",
},

{
  nome: "Seito Sushi Baldwin Park",
  regiao: "International Drive",
  tipo: "Tematico",
  acesso: "4898 New Broad St, Orlando, FL 32814",
  precoMedio: 41,
  destaque: "Culinária japonesa moderna em ambiente sofisticado. Prato sugerido: Sushi Combo Brunch.",
  latitude: 28.5674,
  longitude: -81.3276,
  instagram: "https://www.instagram.com/seitobp/",
},



// 2 - Lake Buena Vista (Disney Springs)
{
  nome: "The Polite Pig",
  regiao: "Lake Buena Vista",
  tipo: "Americano",
  acesso: "1536 Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 29,
  destaque: "Churrasco moderno estilo Florida em serviço rápido. Prato sugerido: Half Chicken com milho grelhado.",
  latitude: 28.3707,
  longitude: -81.5189,
}, // Disney Springs – Town Center. :contentReference[oaicite:5]{index=5}

{
  nome: "T-REX Café",
  regiao: "Lake Buena Vista",
  tipo: "Tematico",
  acesso: "1676 E Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 48,
  destaque: "Restaurante de dinossauros com cenários imersivos. Prato sugerido: Boneyard Burger.",
  latitude: 28.3711,
  longitude: -81.5215,
}, // Disney Springs. :contentReference[oaicite:6]{index=6}

{
  nome: "Earl of Sandwich",
  regiao: "Lake Buena Vista",
  tipo: "Conforto",
  acesso: "1750 E Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 14,
  destaque: "Sanduíches quentes e clássicos de balcão. Prato sugerido: The Original 1762.",
  latitude: 28.3706,
  longitude: -81.5222,
}, // endereço oficial. :contentReference[oaicite:7]{index=7}

{
  nome: "Blaze Fast-Fire’d Pizza",
  regiao: "Lake Buena Vista",
  tipo: "Economico",
  acesso: "1506 E Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 10,
  destaque: "Pizzas personalizadas assadas em forno rápido. Prato sugerido: Build Your Own com massa fina.",
  latitude: 28.3713,
  longitude: -81.5234,
}, // unidade de Disney Springs. :contentReference[oaicite:8]{index=8}

{
  nome: "Joffrey’s Coffee & Tea Company (Disney Springs)",
  regiao: "Lake Buena Vista",
  tipo: "Saudavel",
  acesso: "1486 Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 8,
  destaque: "Cafés especiais, chás e opções geladas. Prato sugerido: Cold Brew Nitro com leite de aveia.",
  latitude: 28.3706,
  longitude: -81.5213,
}, // quiosques listados no diretório de Disney Springs. :contentReference[oaicite:9]{index=9}
// 3 - Kissimmee

{
  nome: "LongHorn Steakhouse Kissimmee",
  regiao: "Kissimmee",
  tipo: "Americano",
  acesso: "5351 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 28,
  destaque: "Churrascaria americana especializada em cortes grelhados. Prato sugerido: Renegade Sirloin.",
  latitude: 28.3347,
  longitude: -81.5022,
  instagram: "https://www.instagram.com/longhornsteaks/",
},

{
  nome: "Medieval Times Kissimmee",
  regiao: "Kissimmee",
  tipo: "Tematico",
  acesso: "4510 W Vine St, Kissimmee, FL 34746",
  precoMedio: 55,
  destaque: "Jantar-show em castelo medieval com cavaleiros e batalhas ao vivo. Prato sugerido: Roasted Chicken Feast.",
  latitude: 28.3108,
  longitude: -81.4715,
  instagram: "https://www.instagram.com/medievaltimes/",
},

{
  nome: "Cracker Barrel Kissimmee",
  regiao: "Kissimmee",
  tipo: "Conforto",
  acesso: "2859 W Vine St, Kissimmee, FL 34741",
  precoMedio: 18,
  destaque: "Rede tradicional com comida caseira sulista e loja country. Prato sugerido: Chicken n’ Dumplins.",
  latitude: 28.3035,
  longitude: -81.4398,
  instagram: "https://www.instagram.com/crackerbarrel/",
},

{
  nome: "Wendy’s Kissimmee",
  regiao: "Kissimmee",
  tipo: "Economico",
  acesso: "3250 Vineland Rd, Kissimmee, FL 34746",
  precoMedio: 9,
  destaque: "Rede de fast-food com hambúrgueres frescos e lanches rápidos. Prato sugerido: Dave’s Single.",
  latitude: 28.3359,
  longitude: -81.4955,
  instagram: "https://www.instagram.com/wendys/",
},

{
  nome: "Nature’s Table Kissimmee",
  regiao: "Kissimmee",
  tipo: "Saudavel",
  acesso: "410 W Vine St, Kissimmee, FL 34741",
  precoMedio: 14,
  destaque: "Opções leves como saladas, wraps e smoothies preparados na hora. Prato sugerido: Turkey Club Wrap.",
  latitude: 28.3050,
  longitude: -81.4198,
  instagram: "https://www.instagram.com/naturestable/",
},


// 4 - Celebration
{
  nome: "Columbia Restaurant – Celebration",
  regiao: "Celebration",
  tipo: "Americano",
  acesso: "649 Front St, Celebration, FL 34747",
  precoMedio: 32,
  destaque: "Clássicos espanhóis e cubanos em casa histórica. Prato sugerido: 1905 Salad + Paella a la Valenciana.",
  latitude: 28.3176,
  longitude: -81.5434,
}, // site oficial Celebration. 

{
  nome: "Celebration Town Tavern",
  regiao: "Celebration",
  tipo: "Tematico",
  acesso: "721 Front St, Celebration, FL 34747",
  precoMedio: 29,
  destaque: "Taverna com frutos do mar e pratos americanos. Prato sugerido: New England Clam Chowder.",
  latitude: 28.3172,
  longitude: -81.5437,
}, // site oficial. :contentReference[oaicite:16]{index=16}

{
  nome: "Downtown Diner – Celebration",
  regiao: "Celebration",
  tipo: "Conforto",
  acesso: "701 Front St, Celebration, FL 34747",
  precoMedio: 18,
  destaque: "Diner clássico no coração de Celebration (antigo Market Street Café). Prato sugerido: Chicken & Waffles.",
  latitude: 28.3174,
  longitude: -81.5435,
}, // substituiu o Market Street Café. 

{
  nome: "Upper Crust Pizza",
  regiao: "Celebration",
  tipo: "Economico",
  acesso: "606 Market St, Celebration, FL 34747",
  precoMedio: 11,
  destaque: "Pizzaria local com fatias generosas. Prato sugerido: Pepperoni slice + garlic knots.",
  latitude: 28.3180,
  longitude: -81.5439,
}, // listado no diretório local. 

{
  nome: "Sweet Escape – Celebration",
  regiao: "Celebration",
  tipo: "Saudavel",
  acesso: "671 Front St, Celebration, FL 34747",
  precoMedio: 9,
  destaque: "Smoothies, sucos e snacks leves. Prato sugerido: Açaí bowl com granola.",
  latitude: 28.3175,
  longitude: -81.5431,
}, // ponto de bebidas/gelatos na Front St (diretório). 

// 5 - Kissimmee Gateway
{
  nome: "Savion's Place",
  regiao: "Kissimmee Gateway",
  tipo: "Americano",
  acesso: "16 E Dakin Ave, Kissimmee, FL 34741",
  precoMedio: 27,
  destaque: "Culinária americana com toque caribenho. Prato típico: Jerk Chicken.",
  latitude: 28.2910,
  longitude: -81.4073,
  instagram: "https://www.instagram.com/savionsplace/",
},
{
  nome: "El Tapatio Mexican Restaurant",
  regiao: "Kissimmee Gateway",
  tipo: "Tematico",
  acesso: "1804 W Vine St, Kissimmee, FL 34741",
  precoMedio: 21,
  destaque: "Pratos mexicanos autênticos e saborosos. Prato típico: Enchiladas Verdes.",
  latitude: 28.3037,
  longitude: -81.4264,
  instagram: "https://www.instagram.com/eltapatiokissimmee/",
},
{
  nome: "Joanie's Diner",
  regiao: "Kissimmee Gateway",
  tipo: "Conforto",
  acesso: "1225 W Vine St, Kissimmee, FL 34741",
  precoMedio: 14,
  destaque: "Diner tradicional com pratos simples e caseiros. Prato típico: Country Breakfast Platter.",
  latitude: 28.3001,
  longitude: -81.4162,
  instagram: "https://www.instagram.com/joaniesdiner/",
},
{
  nome: "Panda Express Kissimmee",
  regiao: "Kissimmee Gateway",
  tipo: "Economico",
  acesso: "1900 W Vine St, Kissimmee, FL 34741",
  precoMedio: 10,
  destaque: "Comida chinesa rápida e acessível. Prato típico: Orange Chicken.",
  latitude: 28.3039,
  longitude: -81.4275,
  instagram: "https://www.instagram.com/officialpandaexpress/",
},
{
  nome: "Raw Juice Bar Kissimmee",
  regiao: "Kissimmee Gateway",
  tipo: "Saudavel",
  acesso: "1820 W Vine St, Kissimmee, FL 34741",
  precoMedio: 12,
  destaque: "Sucos naturais, smoothies e opções veganas. Prato típico: Açaí Energy Bowl.",
  latitude: 28.3036,
  longitude: -81.4267,
  instagram: "https://www.instagram.com/rawjuicebar/",
},

// 6 - Westgate Lakes
{
  nome: "Drafts Sports Bar & Grill",
  regiao: "Westgate Lakes",
  tipo: "Americano",
  acesso: "9500 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 27,
  destaque: "Bar esportivo com hambúrgueres, pizzas e ambiente animado. Prato típico: BBQ Bacon Burger.",
  latitude: 28.4371,
  longitude: -81.4708,
},
{
  nome: "Villa Italiano Chophouse",
  regiao: "Westgate Lakes",
  tipo: "Tematico",
  acesso: "9500 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 38,
  destaque: "Culinária italiana com carnes e massas sofisticadas. Prato típico: Lasagna Bolognese.",
  latitude: 28.4374,
  longitude: -81.4706,
},
{
  nome: "Sid's Bistro",
  regiao: "Westgate Lakes",
  tipo: "Conforto",
  acesso: "9500 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 20,
  destaque: "Café casual com sanduíches, sopas e saladas. Prato típico: Turkey Club Sandwich.",
  latitude: 28.4373,
  longitude: -81.4705,
},
{
  nome: "Subway Westgate Lakes",
  regiao: "Westgate Lakes",
  tipo: "Economico",
  acesso: "9500 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 9,
  destaque: "Sanduíches personalizados rápidos e acessíveis. Prato típico: Italian B.M.T.",
  latitude: 28.4372,
  longitude: -81.4707,
},
{
  nome: "Juice Bar Westgate",
  regiao: "Westgate Lakes",
  tipo: "Saudavel",
  acesso: "9500 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 12,
  destaque: "Sucos, smoothies e bowls frescos e nutritivos. Prato típico: Green Detox Smoothie.",
  latitude: 28.4370,
  longitude: -81.4709,
},

// 7 - Dr. Phillips
{
  nome: "Seasons 52",
  regiao: "Dr. Phillips",
  tipo: "Americano",
  acesso: "7700 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 33,
  destaque: "Pratos sazonais com ingredientes frescos e grelhados. Prato típico: Cedar Plank Salmon.",
  latitude: 28.4510,
  longitude: -81.4820,
  instagram: "https://www.instagram.com/seasons52/",
},
{
  nome: "Christini's Ristorante Italiano",
  regiao: "Dr. Phillips",
  tipo: "Tematico",
  acesso: "7600 Dr Phillips Blvd, Orlando, FL 32819",
  precoMedio: 52,
  destaque: "Restaurante italiano refinado com pratos clássicos. Prato típico: Veal Chop Alla Milanese.",
  latitude: 28.4514,
  longitude: -81.4890,
  instagram: "https://www.instagram.com/christinisorlando/",
},
{
  nome: "The Venetian Chop House",
  regiao: "Dr. Phillips",
  tipo: "Conforto",
  acesso: "8101 World Center Dr, Orlando, FL 32821",
  precoMedio: 40,
  destaque: "Carnes premium e frutos do mar em ambiente sofisticado. Prato típico: Prime Ribeye Steak.",
  latitude: 28.4516,
  longitude: -81.4824,
  instagram: "https://www.instagram.com/venetianchophouse/",
},
{
  nome: "Tijuana Flats Dr. Phillips",
  regiao: "Dr. Phillips",
  tipo: "Economico",
  acesso: "7600 Dr Phillips Blvd, Orlando, FL 32819",
  precoMedio: 10,
  destaque: "Tex-Mex descontraído com preços acessíveis. Prato típico: Chicken Chimichanga.",
  latitude: 28.4515,
  longitude: -81.4888,
  instagram: "https://www.instagram.com/tijuanaflats/",
},
{
  nome: "Pressed Juice Bar Dr. Phillips",
  regiao: "Dr. Phillips",
  tipo: "Saudavel",
  acesso: "7600 Dr Phillips Blvd, Orlando, FL 32819",
  precoMedio: 14,
  destaque: "Sucos prensados a frio e bowls nutritivos. Prato típico: Açaí Protein Bowl.",
  latitude: 28.4513,
  longitude: -81.4891,
  instagram: "https://www.instagram.com/pressedjuicebar/",
},

// 37 - Four Corners (Cagan Crossings / US-27 & US-192)
{
  nome: "Chili’s Grill & Bar – Four Corners",
  regiao: "Four Corners",
  tipo: "Americano",
  acesso: "708 Cagan View Rd, Clermont, FL 34714",
  precoMedio: 22,
  destaque: "Clássicos americanos e combos para família. Prato sugerido: Oldtimer Cheeseburger + chips & salsa.",
  latitude: 28.3548,
  longitude: -81.6819,
},
{
  nome: "Sr. Tequila Mexican Grill",
  regiao: "Four Corners",
  tipo: "Tematico",
  acesso: "16745 Cagan Crossings Blvd, Clermont, FL 34714",
  precoMedio: 25,
  destaque: "Mexicano festivo com margaritas e porções generosas. Prato sugerido: Fajitas mistas.",
  latitude: 28.3566,
  longitude: -81.6835,
},
{
  nome: "Friar Tuck – British Fish & Chips",
  regiao: "Four Corners",
  tipo: "Conforto",
  acesso: "601 Cagan Park Ave, Clermont, FL 34714",
  precoMedio: 18,
  destaque: "Fish & chips estilo britânico e tortas salgadas. Prato sugerido: Cod & Chips com mushy peas.",
  latitude: 28.3577,
  longitude: -81.6843,
},
{
  nome: "Orlando Cat Café",
  regiao: "Four Corners",
  tipo: "Saudavel",
  acesso: "532 Cagan Park Ave, Clermont, FL 34714",
  precoMedio: 15,
  destaque: "Cafés, chás e snacks leves com lounge de gatos adotáveis. Prato sugerido: Iced latte + muffin de blueberry.",
  latitude: 28.3573,
  longitude: -81.6846,
},
{
  nome: "I Love NY Pizza – Cagan Crossings",
  regiao: "Four Corners",
  tipo: "Economico",
  acesso: "532 Cagan Park Ave, Clermont, FL 34714",
  precoMedio: 12,
  destaque: "Fatias à moda NY e calzones. Prato sugerido: Pepperoni slice + garlic knots.",
  latitude: 28.3572,
  longitude: -81.6847,
},


// 9 - Vineland Premium Outlets
{
  nome: "The Cheesecake Factory Vineland",
  regiao: "Vineland Premium Outlets",
  tipo: "Americano",
  acesso: "8200 Vineland Ave, Orlando, FL 32821",
  precoMedio: 28,
  destaque: "Pratos variados e cheesecakes famosos. Prato típico: Chicken Madeira.",
  latitude: 28.3854,
  longitude: -81.4882,
},

{
  nome: "Benihana Orlando",
  regiao: "Vineland Premium Outlets",
  tipo: "Tematico",
  acesso: "12650 International Dr S, Orlando, FL 32821",
  precoMedio: 45,
  destaque: "Culinária japonesa teppanyaki com show de preparo. Prato típico: Hibachi Steak.",
  latitude: 28.3858,
  longitude: -81.4891,
},

{
  nome: "BJ's Restaurant & Brewhouse Vineland",
  regiao: "Vineland Premium Outlets",
  tipo: "Conforto",
  acesso: "8763 Vineland Ave, Orlando, FL 32821",
  precoMedio: 26,
  destaque: "Menu variado e cervejas artesanais. Prato típico: Deep Dish Ziti.",
  latitude: 28.3860,
  longitude: -81.4894,
},

{
  nome: "Panda Express Vineland",
  regiao: "Vineland Premium Outlets",
  tipo: "Economico",
  acesso: "8200 Vineland Ave, Orlando, FL 32821",
  precoMedio: 9,
  destaque: "Comida chinesa rápida e saborosa. Prato típico: Orange Chicken.",
  latitude: 28.3856,
  longitude: -81.4888,
},

{
  nome: "Green Leaf's Vineland",
  regiao: "Vineland Premium Outlets",
  tipo: "Saudavel",
  acesso: "8200 Vineland Ave, Orlando, FL 32821",
  precoMedio: 13,
  destaque: "Saladas frescas e wraps leves. Prato típico: Chicken Caesar Wrap.",
  latitude: 28.3859,
  longitude: -81.4886,
},


// 10 - Davenport
{
  nome: "IHOP Davenport",
  regiao: "Davenport",
  tipo: "Americano",
  acesso: "43600 US-27, Davenport, FL 33837",
  precoMedio: 17,
  destaque: "Rede americana famosa por panquecas, ovos e cafés da manhã completos. Prato típico: Strawberry Banana Pancakes.",
  latitude: 28.2331,
  longitude: -81.6489,
},
{
  nome: "Ovation Bistro & Bar",
  regiao: "Davenport",
  tipo: "Tematico",
  acesso: "42605 US-27, Davenport, FL 33837",
  precoMedio: 32,
  destaque: "Restaurante temático com carnes e brunch diferenciado. Prato típico: Smoked Brisket Hash.",
  latitude: 28.2329,
  longitude: -81.6491,
},
{
  nome: "Perkins Restaurant & Bakery Davenport",
  regiao: "Davenport",
  tipo: "Conforto",
  acesso: "43521 US-27, Davenport, FL 33837",
  precoMedio: 20,
  destaque: "Café tradicional americano com panquecas e padaria própria. Prato típico: Brioche French Toast Platter.",
  latitude: 28.2333,
  longitude: -81.6494,
},
{
  nome: "Burger King Davenport",
  regiao: "Davenport",
  tipo: "Economico",
  acesso: "44149 US-27, Davenport, FL 33897",
  precoMedio: 7,
  destaque: "Rede fast-food com opções acessíveis de café da manhã. Prato típico: Croissan’wich de bacon e ovo.",
  latitude: 28.2335,
  longitude: -81.6487,
},
{
  nome: "Smoothie King Davenport",
  regiao: "Davenport",
  tipo: "Saudavel",
  acesso: "39871 US-27, Davenport, FL 33837",
  precoMedio: 12,
  destaque: "Smoothies nutritivos e bowls energéticos para começar o dia. Prato típico: Gladiator Protein Smoothie.",
  latitude: 28.2337,
  longitude: -81.6485,
},


// 10 - Disney Springs
{
  nome: "The Boathouse",
  regiao: "Disney Springs",
  tipo: "Americano",
  acesso: "1620 E Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 42,
  destaque: "Frutos do mar frescos e ambiente náutico elegante. Prato típico: Maine Lobster Roll.",
  latitude: 28.3701,
  longitude: -81.5154,
},
{
  nome: "Rainforest Café Disney Springs",
  regiao: "Disney Springs",
  tipo: "Tematico",
  acesso: "1486 Buena Vista Dr, Orlando, FL 32830",
  precoMedio: 39,
  destaque: "Ambiente de selva com pratos variados e show temático. Prato típico: Jungle Safari Steak.",
  latitude: 28.3704,
  longitude: -81.5210,
},
{
  nome: "Wolfgang Puck Bar & Grill",
  regiao: "Disney Springs",
  tipo: "Conforto",
  acesso: "1510 E Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 35,
  destaque: "Culinária californiana com pratos reconfortantes. Prato típico: Spaghetti Pomodoro.",
  latitude: 28.3706,
  longitude: -81.5160,
},
{
  nome: "Earl of Sandwich Disney Springs",
  regiao: "Disney Springs",
  tipo: "Economico",
  acesso: "1750 E Buena Vista Dr, Orlando, FL 32830",
  precoMedio: 10,
  destaque: "Sanduíches artesanais com ingredientes frescos. Prato típico: The Original 1762.",
  latitude: 28.3712,
  longitude: -81.5223,
},
{
  nome: "Joffrey's Coffee Disney Springs",
  regiao: "Disney Springs",
  tipo: "Saudavel",
  acesso: "1486 Buena Vista Dr, Orlando, FL 32830",
  precoMedio: 8,
  destaque: "Cafés e chás especiais preparados na hora. Prato típico: Nitro Cold Brew.",
  latitude: 28.3705,
  longitude: -81.5212,
},

// 11 - Westgate Lakes
{
  nome: "Westgate Smokehouse Café",
  regiao: "Westgate Lakes",
  tipo: "Americano",
  acesso: "1000 Westgate Blvd, Orlando, FL 32819",
  precoMedio: 16,
  destaque: "Buffet americano com bacon, panquecas e waffles. Prato típico: Waffles com morangos e chantilly.",
  latitude: 28.4213,
  longitude: -81.4759,
},
{
  nome: "Villa Italiano Brunch",
  regiao: "Westgate Lakes",
  tipo: "Tematico",
  acesso: "9500 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 38,
  destaque: "Café da manhã italiano com frittatas e croissants. Prato típico: Croissant recheado com presunto e queijo.",
  latitude: 28.4211,
  longitude: -81.4761,
},
{
  nome: "Joe’s Brunch Westgate",
  regiao: "Westgate Lakes",
  tipo: "Conforto",
  acesso: "9600 Westgate Blvd, Orlando, FL 32819",
  precoMedio: 21,
  destaque: "Brunch clássico com cafés artesanais. Prato típico: Sanduíche de ovo com bacon no brioche.",
  latitude: 28.4208,
  longitude: -81.4752,
},
{
  nome: "Dunkin’ Westgate",
  regiao: "Westgate Lakes",
  tipo: "Economico",
  acesso: "9339 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 7,
  destaque: "Donuts, cafés rápidos e combos matinais. Prato típico: Café americano com Boston Kreme Donut.",
  latitude: 28.4212,
  longitude: -81.4757,
},
{
  nome: "Juice Bar Westgate",
  regiao: "Westgate Lakes",
  tipo: "Saudavel",
  acesso: "9500 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 12,
  destaque: "Sucos prensados, smoothies e bowls naturais no coração do Westgate Lakes Resort.",
  latitude: 28.4370,
  longitude: -81.4709,
  menuUrl: "https://www.westgateresorts.com/hotels/florida/orlando/westgate-lakes-resort/dining/"
},
// 12 - Vista Cay
{
  nome: "Spoleto Italian Kitchen",
  regiao: "Vista Cay",
  tipo: "Americano",
  acesso: "7600 Dr Phillips Blvd Suite 18, Orlando, FL 32819",
  precoMedio: 18,
  destaque: "Culinária italiana casual onde você monta sua própria massa ou salada. Prato típico: Pasta personalizada com molho Alfredo.",
  latitude: 28.4258,
  longitude: -81.4602,
  instagram: "https://www.instagram.com/spoleto_usa/",
},
{
  nome: "NYPD Pizza Café",
  regiao: "Vista Cay",
  tipo: "Tematico",
  acesso: "2589 S Hiawassee Rd, Orlando, FL 32835",
  precoMedio: 24,
  destaque: "Pizzaria estilo Nova Iorque com fatias generosas e ambiente descontraído. Prato típico: Pepperoni Pizza Slice.",
  latitude: 28.4265,
  longitude: -81.4600,
  instagram: "https://www.instagram.com/nypdpizzaorlando/",
},
{
  nome: "Menchie’s Frozen Yogurt Vista Cay",
  regiao: "Vista Cay",
  tipo: "Conforto",
  acesso: "9920 Universal Blvd, Orlando, FL 32819",
  precoMedio: 10,
  destaque: "Frozen yogurt self-service com diversas coberturas. Prato típico: Frozen Yogurt com frutas frescas.",
  latitude: 28.4263,
  longitude: -81.4599,
  instagram: "https://www.instagram.com/menchiesfroyo/",
},
{
  nome: "Dunkin’ Vista Cay",
  regiao: "Vista Cay",
  tipo: "Economico",
  acesso: "9922 Universal Blvd, Orlando, FL 32819",
  precoMedio: 8,
  destaque: "Cafés, donuts e sanduíches rápidos em rede popular. Prato típico: Egg & Cheese Sandwich.",
  latitude: 28.4261,
  longitude: -81.4600,
  instagram: "https://www.instagram.com/dunkin/",
},
{
  nome: "Subway Vista Cay",
  regiao: "Vista Cay",
  tipo: "Saudavel",
  acesso: "9926 Universal Blvd, Orlando, FL 32819",
  precoMedio: 11,
  destaque: "Sanduíches frescos montados na hora com opções de wraps e bowls. Prato típico: Sub de Frango Teriyaki.",
  latitude: 28.4266,
  longitude: -81.4598,
  instagram: "https://www.instagram.com/subway/",
},

// 14 - Dr. Phillips
{
  nome: "Keke’s Breakfast Café",
  regiao: "Dr. Phillips",
  tipo: "Americano",
  acesso: "7512 Doctor Phillips Blvd #100, Orlando, FL 32819",
  precoMedio: 17,
  destaque: "Panquecas artesanais, ovos mexidos e bacon. A panqueca de banana com mel é um destaque delicioso.",
  latitude: 28.4641,
  longitude: -81.4912,
},

{
  nome: "Toothsome Brunch Lab",
  regiao: "Dr. Phillips",
  tipo: "Tematico",
  acesso: "6000 Universal Blvd, Orlando, FL 32819",
  precoMedio: 45,
  destaque: "Ambiente steampunk com milkshakes e pratos doces. A panqueca recheada de chocolate branco é bem criativa.",
  latitude: 28.4639,
  longitude: -81.4910,
},

{
  nome: "Cozy Brunch Spot",
  regiao: "Dr. Phillips",
  tipo: "Conforto",
  acesso: "7510 Doctor Phillips Blvd, Orlando, FL 32819",
  precoMedio: 20,
  destaque: "Brunch tradicional com café orgânico e pratos quentes. Pão de queijo artesanal com ovos mexidos traz conforto.",
  latitude: 28.4640,
  longitude: -81.4911,
},

{
  nome: "Green Fuel Café",
  regiao: "Dr. Phillips",
  tipo: "Saudavel",
  acesso: "7540 Dr. Phillips Blvd, Orlando, FL 32819",
  precoMedio: 14,
  destaque: "Bowls de frutas, chia pudding e sucos detox. O bowl de banana com pasta de amendoim combina nutrição e sabor.",
  latitude: 28.4642,
  longitude: -81.4913,
},

{
  nome: "Dunkin’ Dr. Phillips",
  regiao: "Dr. Phillips",
  tipo: "Economico",
  acesso: "7500 Dr. Phillips Blvd, Orlando, FL 32819",
  precoMedio: 8,
  destaque: "Donuts, muffins e café expresso. O combo de café com croissant de queijo é rápido e satisfatório.",
  latitude: 28.4643,
  longitude: -81.4914,
},
// 16 - Orlando Airport Area
{
  nome: "Chili’s Grill & Bar – Orlando Airport",
  regiao: "Orlando Airport Area",
  tipo: "Americano",
  acesso: "6815 S Semoran Blvd, Orlando, FL 32822",
  precoMedio: 22,
  destaque: "Rede americana com hambúrgueres, fajitas e ribs famosas. Prato típico: Baby Back Ribs.",
  latitude: 28.4596,
  longitude: -81.3085,
  instagram: "https://www.instagram.com/chilis/",
},

{
  nome: "Another Broken Egg Cafe",
  regiao: "Orlando Airport Area",
  tipo: "Tematico",
  acesso: "6324 S Orange Ave, Orlando, FL 32809",
  precoMedio: 40,
  destaque: "Café brunch temático em ambiente descontraído.",
  latitude: 28.4330,
  longitude: -81.3083,
},
{
  nome: "OpenTable – Airport options",
  regiao: "Orlando Airport Area",
  tipo: "Conforto",
  acesso: "Várias opções dentro e perto do aeroporto via OpenTable",
  precoMedio: 20,
  destaque: "Restaurantes confortáveis com reserva fácil antes do voo.",
  latitude: 28.4327,
  longitude: -81.3082,
},
{
  nome: "Rock & Brews - Lee Vista (perto do aeroporto)",
  regiao: "Orlando Airport Area",
  tipo: "Saudavel",
  acesso: "perto do aeroporto, East Orlando",
  precoMedio: 13,
  destaque: "Ambiente casual com opções modernas de brunch.",
  latitude: 28.4332,
  longitude: -81.3084,
},
{
  nome: "Bar Louie - Orlando Airport",
  regiao: "Orlando Airport Area",
  tipo: "Economico",
  acesso: "perto do aeroporto, East Orlando",
  precoMedio: 6,
  destaque: "Café e lanches rápidos num espaço descontraído.",
  latitude: 28.4328,
  longitude: -81.3080,
},

// 17 - Downtown Orlando
{
  nome: "Cindy’s Cuban Café",
  regiao: "Downtown Orlando",
  tipo: "Americano",
  acesso: "16 W Pine St, Orlando, FL 32801",
  precoMedio: 17,
  destaque: "Culinária cubana/americana com pratos tradicionais em ambiente casual. Prato típico: Cuban Sandwich.",
  latitude: 28.5419,
  longitude: -81.3794,
},
{
  nome: "Hamburger Mary’s Orlando",
  regiao: "Downtown Orlando",
  tipo: "Tematico",
  acesso: "110 W Church St, Orlando, FL 32801",
  precoMedio: 28,
  destaque: "Ambiente temático divertido com shows e hambúrgueres criativos. Prato típico: Queen Mary Burger.",
  latitude: 28.5421,
  longitude: -81.3796,
},
{
  nome: "The Stubborn Mule",
  regiao: "Downtown Orlando",
  tipo: "Conforto",
  acesso: "100 S Eola Dr #103, Orlando, FL 32801",
  precoMedio: 22,
  destaque: "Bistrô moderno com comfort food americana e brunch animado. Prato típico: Mule Eggs Benedict.",
  latitude: 28.5409,
  longitude: -81.3716,
},
{
  nome: "Planted Kitchen",
  regiao: "Downtown Orlando",
  tipo: "Saudavel",
  acesso: "1035 N Orange Ave, Orlando, FL 32801",
  precoMedio: 16,
  destaque: "Culinária vegana criativa e nutritiva, com bowls, wraps e smoothies. Prato típico: Buddha Bowl.",
  latitude: 28.5550,
  longitude: -81.3790,
},
{
  nome: "Dunkin’ Downtown Orlando",
  regiao: "Downtown Orlando",
  tipo: "Economico",
  acesso: "200 S Orange Ave, Orlando, FL 32801",
  precoMedio: 7,
  destaque: "Donuts, cafés e lanches rápidos para o dia a dia. Prato típico: Combo café + donut glacê.",
  latitude: 28.5412,
  longitude: -81.3785,
},


// 18 - Hunter's Creek
{
  nome: "Keke’s Breakfast Café",
  regiao: "Hunter's Creek",
  tipo: "Americano",
  acesso: "4000 Town Center Blvd, Orlando, FL 32837",
  precoMedio: 16,
  destaque: "Clássicos americanos de café da manhã em ambiente familiar. Prato típico: Blueberry Pancakes.",
  latitude: 28.3581,
  longitude: -81.4200,
},
{
  nome: "La Fiesta Mexican Grill",
  regiao: "Hunter's Creek",
  tipo: "Tematico",
  acesso: "16605 Southchase Loop, Orlando, FL 32837",
  precoMedio: 28,
  destaque: "Restaurante mexicano com pratos típicos saborosos. Prato típico: Fajitas de Carne.",
  latitude: 28.3838,
  longitude: -81.4010,
},
{
  nome: "Metro Diner Hunter’s Creek",
  regiao: "Hunter's Creek",
  tipo: "Conforto",
  acesso: "120 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 21,
  destaque: "Diner com pratos reconfortantes e porções generosas. Prato típico: Fried Chicken & Waffle.",
  latitude: 28.3579,
  longitude: -81.4198,
},
{
  nome: "Bolay Fresh Bold Kitchen",
  regiao: "Hunter's Creek",
  tipo: "Saudavel",
  acesso: "14311 Narcoossee Rd, Orlando, FL 32832",
  precoMedio: 14,
  destaque: "Bowls saudáveis personalizáveis com ingredientes frescos. Prato típico: Spicy Thai Shrimp Bowl.",
  latitude: 28.3840,
  longitude: -81.4026,
},
{
  nome: "Dunkin’ Hunter’s Creek",
  regiao: "Hunter's Creek",
  tipo: "Economico",
  acesso: "13510 John Young Pkwy, Orlando, FL 32837",
  precoMedio: 7,
  destaque: "Rede econômica de café com opções rápidas. Prato típico: Egg & Cheese Wake-Up Wrap.",
  latitude: 28.3826,
  longitude: -81.4051,
},

// 19 - Windermere
{
  nome: "Yellow Dog Eats",
  regiao: "Windermere",
  tipo: "Americano",
  acesso: "1236 Hempel Ave, Gotha, FL 34734 (próx. Windermere)",
  precoMedio: 20,
  destaque: "Café excêntrico com sanduíches criativos e ambiente alternativo. Prato típico: Pulled Pork Sandwich.",
  latitude: 28.5399,
  longitude: -81.5238,
},
{
  nome: "Bella Tuscany Ristorante Italiano",
  regiao: "Windermere",
  tipo: "Tematico",
  acesso: "13424 Summerport Village Pkwy, Windermere, FL 34786",
  precoMedio: 35,
  destaque: "Culinária italiana clássica em ambiente acolhedor. Prato típico: Fettuccine Alfredo.",
  latitude: 28.4938,
  longitude: -81.5371,
},
{
  nome: "Peach Valley Café",
  regiao: "Windermere",
  tipo: "Conforto",
  acesso: "1216 S Orange Ave, Orlando, FL 32806 (próx. Windermere)",
  precoMedio: 22,
  destaque: "Café casual com pratos de brunch e almoço. Prato típico: Apple Fritter Bites.",
  latitude: 28.4952,
  longitude: -81.5362,
},
{
  nome: "Greenbeat Windermere",
  regiao: "Windermere",
  tipo: "Saudavel",
  acesso: "4750 The Grove Dr, Windermere, FL 34786",
  precoMedio: 16,
  destaque: "Bowls de saladas frescas e saudáveis. Prato típico: Mediterranean Bowl.",
  latitude: 28.4956,
  longitude: -81.5368,
},
{
  nome: "Dunkin’ Windermere",
  regiao: "Windermere",
  tipo: "Economico",
  acesso: "6536 Old Brick Rd, Windermere, FL 34786",
  precoMedio: 6,
  destaque: "Donuts, cafés e lanches rápidos e baratos. Prato típico: Bagel com cream cheese + café.",
  latitude: 28.4940,
  longitude: -81.5350,
},

// 20 - Winter Garden
{
  nome: "Winter Garden Café",
  regiao: "Winter Garden",
  tipo: "Americano",
  acesso: "42 W Plant St, Winter Garden, FL 34787",
  precoMedio: 17,
  destaque: "Café tradicional e aconchegante com pratos clássicos. Prato típico: Country Breakfast com ovos, bacon e panquecas.",
  latitude: 28.5652,
  longitude: -81.5864,
  instagram: "https://www.instagram.com/wintergardencafe/",
},
{
  nome: "Crooked Can Brewing Company",
  regiao: "Winter Garden",
  tipo: "Tematico",
  acesso: "426 W Plant St, Winter Garden, FL 34787",
  precoMedio: 35,
  destaque: "Cervejaria artesanal no Plant Street Market com ambiente animado. Prato típico: Bavarian Pretzel com mostarda.",
  latitude: 28.5649,
  longitude: -81.5863,
  instagram: "https://www.instagram.com/crookedcan/",
},
{
  nome: "MoonCricket Grille",
  regiao: "Winter Garden",
  tipo: "Conforto",
  acesso: "14 W Plant St, Winter Garden, FL 34787",
  precoMedio: 23,
  destaque: "Restaurante descontraído com comfort food americana. Prato típico: Fish & Chips.",
  latitude: 28.5657,
  longitude: -81.5871,
  instagram: "https://www.instagram.com/mooncricketgrille/",
},
{
  nome: "Plant Street Market – Press’d",
  regiao: "Winter Garden",
  tipo: "Saudavel",
  acesso: "426 W Plant St, Winter Garden, FL 34787",
  precoMedio: 14,
  destaque: "Bowls, sucos e opções naturais em mercado local. Prato típico: Açaí Bowl com granola e frutas.",
  latitude: 28.5648,
  longitude: -81.5862,
  instagram: "https://www.instagram.com/plantstreetmarket/",
},
{
  nome: "Dunkin’ Winter Garden",
  regiao: "Winter Garden",
  tipo: "Economico",
  acesso: "13755 W Colonial Dr, Winter Garden, FL 34787",
  precoMedio: 6,
  destaque: "Donuts, café e lanches rápidos para viagem. Prato típico: Glazed Donut com café preto.",
  latitude: 28.5642,
  longitude: -81.5850,
  instagram: "https://www.instagram.com/dunkin/",
},


// 21 - Altamonte Springs
{
  nome: "First Watch Altamonte",
  regiao: "Altamonte Springs",
  tipo: "Americano",
  acesso: "520 W State Rd 436 #1140, Altamonte Springs, FL 32714",
  precoMedio: 20,
  destaque: "Brunch americano em ambiente aconchegante, com panquecas, ovos frescos e sanduíches leves. Prato típico: Avocado Toast com ovos.",
  latitude: 28.6640,
  longitude: -81.3750,
},

{
  nome: "Kobe Japanese Steakhouse",
  regiao: "Altamonte Springs",
  tipo: "Tematico",
  acesso: "468 W State Rd 436, Altamonte Springs, FL 32714",
  precoMedio: 40,
  destaque: "Teppanyaki japonês com preparo show ao vivo. Prato típico: Hibachi Shrimp.",
  latitude: 28.6634,
  longitude: -81.3712,
},
{
  nome: "First Watch Altamonte",
  regiao: "Altamonte Springs",
  tipo: "Conforto",
  acesso: "520 W State Rd 436 #1140, Altamonte Springs, FL 32714",
  precoMedio: 20,
  destaque: "Brunch clássico americano em ambiente aconchegante. Prato típico: Avocado Toast com ovos.",
  latitude: 28.6640,
  longitude: -81.3750,
},
{
  nome: "Dunkin’ Altamonte",
  regiao: "Altamonte Springs",
  tipo: "Econômico",
  acesso: "1010 N State Rd 434, Altamonte Springs, FL 32714",
  precoMedio: 6,
  destaque: "Donuts, cafés e combos acessíveis. Prato típico: Iced Coffee com Boston Kreme Donut.",
  latitude: 28.6677,
  longitude: -81.3703,
},
{
  nome: "Vitality Bowls Altamonte",
  regiao: "Altamonte Springs",
  tipo: "Saudavel",
  acesso: "451 E Altamonte Dr, Altamonte Springs, FL 32701",
  precoMedio: 14,
  destaque: "Bowls de açaí e superfoods nutritivos. Prato típico: Nutty Bowl.",
  latitude: 28.6642,
  longitude: -81.3653,
},

// 22 - Clermont
{
  nome: "Lilly’s on the Lake",
  regiao: "Clermont",
  tipo: "Americano",
  acesso: "846 W Osceola St, Clermont, FL 34711",
  precoMedio: 18,
  destaque: "Restaurante à beira do lago com pratos americanos variados. Prato típico: All-American Breakfast.",
  latitude: 28.5534,
  longitude: -81.7621,
},
{
  nome: "The Crooked Spoon Gastropub",
  regiao: "Clermont",
  tipo: "Tematico",
  acesso: "200 Citrus Tower Blvd, Clermont, FL 34711",
  precoMedio: 36,
  destaque: "Gastropub criativo com ambiente diferenciado. Prato típico: Crooked Burger.",
  latitude: 28.5534,
  longitude: -81.7689,
},
{
  nome: "Bob Evans Clermont",
  regiao: "Clermont",
  tipo: "Conforto",
  acesso: "1650 US-27, Clermont, FL 34714",
  precoMedio: 20,
  destaque: "Café da manhã e brunch caseiros em ambiente familiar. Prato típico: Country Fried Steak.",
  latitude: 28.5379,
  longitude: -81.7165,
},
{
  nome: "Taco Bell Clermont",
  regiao: "Clermont",
  tipo: "Economico",
  acesso: "1605 US-27, Clermont, FL 34714",
  precoMedio: 8,
  destaque: "Tex-Mex rápido e barato. Prato típico: Crunchwrap Supreme.",
  latitude: 28.5392,
  longitude: -81.7222,
},
{
  nome: "Vitality Bowls Clermont",
  regiao: "Clermont",
  tipo: "Saudavel",
  acesso: "2425 US-27, Clermont, FL 34711",
  precoMedio: 14,
  destaque: "Smoothies e bowls nutritivos. Prato típico: Açaí Superfood Bowl.",
  latitude: 28.5450,
  longitude: -81.7229,
},

// 30 - Winter Park (cafés com Instagram)
{
  nome: "The Glass Knife",
  regiao: "Winter Park",
  tipo: "Tematico",
  acesso: "276 S Orlando Ave, Winter Park, FL 32789",
  precoMedio: 43,
  destaque: "Confeitaria moderna com brunch criativo (donuts, toasts, omeletes). Prato típico: Red Velvet Cake Donut.",
  latitude: 28.5964,
  longitude: -81.3535,
  instagram: "https://www.instagram.com/theglassknife/",
},
{
  nome: "Barnie’s Coffee & Tea Co. – Park Ave",
  regiao: "Winter Park",
  tipo: "Saudavel",
  acesso: "118 S Park Ave, Winter Park, FL 32789",
  precoMedio: 12,
  destaque: "Cafés especiais, toasts e bowls leves. Prato típico: Avocado Toast + café Santa’s White Christmas® (sazonal).",
  latitude: 28.5969,
  longitude: -81.3520,
  instagram: "https://www.instagram.com/barniescoffee/",
},
{
  nome: "Foxtail Coffee Co. – Winter Park",
  regiao: "Winter Park",
  tipo: "Economico",
  acesso: "1282 N Orange Ave, Winter Park, FL 32789",
  precoMedio: 8,
  destaque: "Tostadora local com cafés de especialidade e pastries. Prato típico: Cold Brew + croissant.",
  latitude: 28.5961,
  longitude: -81.3532,
  instagram: "https://www.instagram.com/foxtailcoffee/",
},
{
  nome: "First Watch – Winter Park",
  regiao: "Winter Park",
  tipo: "Americano",
  acesso: "140 N Orlando Ave, Ste 100, Winter Park, FL 32789",
  precoMedio: 16,
  destaque: "Pratos leves e nutritivos de brunch. Prato típico: A.M. Superfood Bowl.",
  latitude: 28.5965,
  longitude: -81.3536,
  instagram: "https://www.instagram.com/firstwatch/",
},
{
  nome: "Keke’s Breakfast Café – Winter Park",
  regiao: "Winter Park",
  tipo: "Conforto",
  acesso: "1955 Aloma Ave, Winter Park, FL 32792",
  precoMedio: 20,
  destaque: "Panquecas, waffles e clássicos americanos fartos. Prato típico: Banana Nut Pancakes.",
  latitude: 28.5998,
  longitude: -81.3279,
  instagram: "https://www.instagram.com/kekesbreakfastcafe/",
},


// 23 - Oak Ridge
{
  nome: "Applebee’s Oak Ridge",
  regiao: "Oak Ridge",
  tipo: "Americano",
  acesso: "6324 S Orange Blossom Trl, Orlando, FL 32809",
  precoMedio: 18,
  destaque: "Rede americana com pratos variados e ambiente descontraído. Prato típico: Classic Bacon Cheeseburger.",
  latitude: 28.4741,
  longitude: -81.4123,
},
{
  nome: "Café Tu Tu Tango",
  regiao: "Oak Ridge",
  tipo: "Tematico",
  acesso: "8625 International Dr, Orlando, FL 32819",
  precoMedio: 37,
  destaque: "Ambiente artístico com tapas criativas e decoração vibrante. Prato típico: Cajun Chicken Egg Rolls.",
  latitude: 28.4542,
  longitude: -81.4301,
},
{
  nome: "Perkins Restaurant & Bakery",
  regiao: "Oak Ridge",
  tipo: "Conforto",
  acesso: "6813 S Orange Blossom Trl, Orlando, FL 32809",
  precoMedio: 19,
  destaque: "Pratos de brunch e padaria caseira. Prato típico: Brioche French Toast.",
  latitude: 28.4722,
  longitude: -81.4135,
},
{
  nome: "Pollo Tropical Oak Ridge",
  regiao: "Oak Ridge",
  tipo: "Economico",
  acesso: "6315 S Orange Blossom Trl, Orlando, FL 32809",
  precoMedio: 8,
  destaque: "Rede caribenha com refeições rápidas e acessíveis. Prato típico: TropiChop Bowl.",
  latitude: 28.4729,
  longitude: -81.4141,
},
{
  nome: "Smoothie King Oak Ridge",
  regiao: "Oak Ridge",
  tipo: "Saudavel",
  acesso: "6303 S Orange Blossom Trl, Orlando, FL 32809",
  precoMedio: 12,
  destaque: "Smoothies e bowls energéticos e nutritivos. Prato típico: Hulk Strawberry Smoothie.",
  latitude: 28.4736,
  longitude: -81.4138,
},

// 24 - Maingate East
{
  nome: "Olive Garden Maingate East",
  regiao: "Maingate East",
  tipo: "Americano",
  acesso: "5021 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 25,
  destaque: "Massas e pratos italianos-americanos em ambiente familiar. Prato típico: Tour of Italy (Lasagna, Chicken Parm e Fettuccine Alfredo).",
  latitude: 28.3321,
  longitude: -81.5092,
},
{
  nome: "Pirate’s Dinner Adventure",
  regiao: "Maingate East",
  tipo: "Tematico",
  acesso: "6400 Carrier Dr, Orlando, FL 32819",
  precoMedio: 42,
  destaque: "Jantar-show temático com piratas e aventura. Prato típico: Frango assado com legumes.",
  latitude: 28.3338,
  longitude: -81.5124,
},
{
  nome: "Cracker Barrel Maingate East",
  regiao: "Maingate East",
  tipo: "Conforto",
  acesso: "5400 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 22,
  destaque: "Café da manhã sulista e comfort food americana. Prato típico: Chicken n’ Dumplins.",
  latitude: 28.3318,
  longitude: -81.5103,
},
{
  nome: "Taco Bell Maingate East",
  regiao: "Maingate East",
  tipo: "Economico",
  acesso: "5250 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 8,
  destaque: "Fast-food mexicano rápido e barato. Prato típico: Beef Chalupa Supreme.",
  latitude: 28.3329,
  longitude: -81.5100,
},
{
  nome: "Nature’s Table Maingate East",
  regiao: "Maingate East",
  tipo: "Saudavel",
  acesso: "5045 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 13,
  destaque: "Bowls, wraps e smoothies naturais. Prato típico: Southwest Chicken Bowl.",
  latitude: 28.3331,
  longitude: -81.5095,
},

// 25 - Maingate West
{
  nome: "IHOP Maingate West",
  regiao: "Maingate West",
  tipo: "Americano",
  acesso: "7491 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 17,
  destaque: "Rede clássica americana com panquecas, ovos e bacon. Prato típico: Strawberry & Banana Pancakes.",
  latitude: 28.3290,
  longitude: -81.5930,
},
{
  nome: "Ford’s Garage Sunset Walk",
  regiao: "Maingate West",
  tipo: "Tematico",
  acesso: "3251 Margaritaville Blvd, Kissimmee, FL 34747",
  precoMedio: 32,
  destaque: "Restaurante temático automotivo com hambúrgueres gourmet. Prato típico: Ford’s Signature Burger.",
  latitude: 28.3350,
  longitude: -81.5886,
},
{
  nome: "Bob Evans Maingate West",
  regiao: "Maingate West",
  tipo: "Conforto",
  acesso: "7411 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 20,
  destaque: "Café da manhã e brunch caseiros em ambiente familiar. Prato típico: Rise & Shine Breakfast.",
  latitude: 28.3275,
  longitude: -81.5928,
},
{
  nome: "McDonald’s Formosa Blvd",
  regiao: "Maingate West",
  tipo: "Economico",
  acesso: "7711 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 7,
  destaque: "Rede fast-food acessível para refeições rápidas. Prato típico: Egg McMuffin.",
  latitude: 28.3242,
  longitude: -81.5843,
},
{
  nome: "Freshii Maingate West",
  regiao: "Maingate West",
  tipo: "Saudavel",
  acesso: "7601 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 14,
  destaque: "Opções leves com bowls, wraps e smoothies naturais. Prato típico: Oaxaca Bowl.",
  latitude: 28.3292,
  longitude: -81.5931,
},

// 26 - Bonnet Creek
{
  nome: "Harvest Bistro",
  regiao: "Bonnet Creek",
  tipo: "Americano",
  acesso: "Hilton Bonnet Creek, 14100 Bonnet Creek Resort Ln, Orlando, FL 32821",
  precoMedio: 20,
  destaque: "Café da manhã completo com omeletes e estações variadas. Prato típico: Omelete Station.",
  latitude: 28.3627,
  longitude: -81.5244,
},
{
  nome: "La Luce at Hilton Bonnet Creek",
  regiao: "Bonnet Creek",
  tipo: "Tematico",
  acesso: "14100 Bonnet Creek Resort Ln, Orlando, FL 32821",
  precoMedio: 45,
  destaque: "Italiano sofisticado com massas artesanais e brunch especial. Prato típico: Ricotta Pancakes.",
  latitude: 28.3635,
  longitude: -81.5239,
},
{
  nome: "Zeta Asia",
  regiao: "Bonnet Creek",
  tipo: "Conforto",
  acesso: "Waldorf Astoria Orlando, 14200 Bonnet Creek Resort Ln, Orlando, FL 32821",
  precoMedio: 28,
  destaque: "Culinária asiática moderna com opções para brunch. Prato típico: Sushi Roll Combo.",
  latitude: 28.3633,
  longitude: -81.5242,
},
{
  nome: "Nature’s Table Bonnet Creek",
  regiao: "Bonnet Creek",
  tipo: "Saudavel",
  acesso: "14200 Bonnet Creek Resort Ln, Orlando, FL 32821",
  precoMedio: 14,
  destaque: "Wraps, bowls e smoothies frescos e nutritivos. Prato típico: Spinach & Feta Wrap.",
  latitude: 28.3631,
  longitude: -81.5227,
},
{
  nome: "Subway Bonnet Creek",
  regiao: "Bonnet Creek",
  tipo: "Economico",
  acesso: "14001 Chelonia Pkwy, Orlando, FL 32821",
  precoMedio: 8,
  destaque: "Sanduíches rápidos e personalizáveis. Prato típico: Italian B.M.T.",
  latitude: 28.3652,
  longitude: -81.5215,
},



// 28 - Flamingo Crossings
{
  nome: "IHOP Flamingo Crossings",
  regiao: "Flamingo Crossings",
  tipo: "Americano",
  acesso: "14311 Reese Dr, Winter Garden, FL 34787",
  precoMedio: 17,
  destaque: "Café da manhã completo com panquecas e omeletes. Prato típico: Double Blueberry Pancakes.",
  latitude: 28.3772,
  longitude: -81.6111,
},
{
  nome: "Hash House A Go Go",
  regiao: "Flamingo Crossings",
  tipo: "Tematico",
  acesso: "13272 Hartzog Rd, Winter Garden, FL 34787",
  precoMedio: 38,
  destaque: "Porções gigantes em ambiente temático. Prato típico: Sage Fried Chicken & Waffles.",
  latitude: 28.3781,
  longitude: -81.6103,
},
{
  nome: "Applebee’s Flamingo Crossings",
  regiao: "Flamingo Crossings",
  tipo: "Conforto",
  acesso: "14045 Flamingo Crossings Blvd, Winter Garden, FL 34787",
  precoMedio: 22,
  destaque: "Rede americana com pratos variados. Prato típico: Classic Combo Sampler.",
  latitude: 28.3775,
  longitude: -81.6109,
},
{
  nome: "Tropical Smoothie Café Flamingo",
  regiao: "Flamingo Crossings",
  tipo: "Saudavel",
  acesso: "14055 Flamingo Crossings Blvd, Winter Garden, FL 34787",
  precoMedio: 12,
  destaque: "Smoothies energéticos e wraps saudáveis. Prato típico: Sunrise Sunset Smoothie.",
  latitude: 28.3780,
  longitude: -81.6115,
},
{
  nome: "Dunkin’ Flamingo Crossings",
  regiao: "Flamingo Crossings",
  tipo: "Economico",
  acesso: "14015 Flamingo Crossings Blvd, Winter Garden, FL 34787",
  precoMedio: 6,
  destaque: "Donuts e cafés rápidos a preço acessível. Prato típico: Coffee & Glazed Donut.",
  latitude: 28.3774,
  longitude: -81.6107,
},

// 27 - ChampionsGate
{
  nome: "First Watch – ChampionsGate",
  regiao: "ChampionsGate",
  tipo: "Americano",
  acesso: "8303 Champions Gate Blvd, Davenport, FL 33896",
  precoMedio: 19,
  destaque: "Café da manhã clássico americano com pratos frescos e saudáveis. Prato típico: Avocado Toast com ovos mexidos.",
  latitude: 28.2632,
  longitude: -81.6419,
},
{
  nome: "Dulcetto Café & Gelato",
  regiao: "ChampionsGate",
  tipo: "Tematico",
  acesso: "8293 Champions Gate Blvd, Davenport, FL 33896",
  precoMedio: 28,
  destaque: "Café europeu com temática italiana e gelatos artesanais. Prato típico: Cappuccino com Tiramisu.",
  latitude: 28.2630,
  longitude: -81.6422,
},
{
  nome: "Panera Bread – ChampionsGate",
  regiao: "ChampionsGate",
  tipo: "Conforto",
  acesso: "8174 Champions Gate Blvd, Davenport, FL 33896",
  precoMedio: 22,
  destaque: "Rede aconchegante com sopas, sanduíches e saladas. Prato típico: Broccoli Cheddar Soup in Bread Bowl.",
  latitude: 28.2628,
  longitude: -81.6417,
},
{
  nome: "Clean Juice – ChampionsGate",
  regiao: "ChampionsGate",
  tipo: "Saudavel",
  acesso: "8289 Champions Gate Blvd, Davenport, FL 33896",
  precoMedio: 14,
  destaque: "Smoothies orgânicos, bowls e wraps naturais. Prato típico: The Immunity One (suco de laranja, cenoura e gengibre).",
  latitude: 28.2631,
  longitude: -81.6420,
},
{
  nome: "Dunkin’ – ChampionsGate",
  regiao: "ChampionsGate",
  tipo: "Economico",
  acesso: "8220 Champions Gate Blvd, Davenport, FL 33896",
  precoMedio: 6,
  destaque: "Rede rápida com cafés, donuts e sanduíches acessíveis. Prato típico: Café americano + Glazed Donut.",
  latitude: 28.2629,
  longitude: -81.6418,
},



// 29 - MetroWest
{
  nome: "Metro Diner",
  regiao: "MetroWest",
  tipo: "Americano",
  acesso: "9858 International Dr, Orlando, FL 32819",
  precoMedio: 19,
  destaque: "Diner americano famoso pelos cafés da manhã robustos. Prato típico: Fried Chicken & Waffles.",
  latitude: 28.5183,
  longitude: -81.4640,
},
{
  nome: "Teak Neighborhood Grill",
  regiao: "MetroWest",
  tipo: "Tematico",
  acesso: "6400 Time Square Ave, Orlando, FL 32835",
  precoMedio: 32,
  destaque: "Pub temático moderno com hambúrgueres criativos e ambiente descontraído. Prato típico: Drunken Monk Burger.",
  latitude: 28.5185,
  longitude: -81.4642,
},
{
  nome: "Peach Valley Café MetroWest",
  regiao: "MetroWest",
  tipo: "Conforto",
  acesso: "5072 Dr Phillips Blvd, Orlando, FL 32819",
  precoMedio: 23,
  destaque: "Café acolhedor com pratos caseiros e brunch variado. Prato típico: Biscuits & Gravy.",
  latitude: 28.5184,
  longitude: -81.4641,
},
{
  nome: "Fresh Kitchen MetroWest",
  regiao: "MetroWest",
  tipo: "Saudavel",
  acesso: "4101 Millenia Blvd, Orlando, FL 32839",
  precoMedio: 14,
  destaque: "Bowls saudáveis e wraps preparados com ingredientes frescos. Prato típico: Six Bowl (arroz integral, frango grelhado e vegetais).",
  latitude: 28.5186,
  longitude: -81.4643,
},
{
  nome: "Dunkin’ MetroWest",
  regiao: "MetroWest",
  tipo: "Economico",
  acesso: "2295 S Hiawassee Rd, Orlando, FL 32835",
  precoMedio: 6,
  destaque: "Rede de cafés rápida e econômica. Prato típico: Café preto com Glazed Donut.",
  latitude: 28.5182,
  longitude: -81.4639,
},



// 31 - Osceola Parkway
{
  nome: "First Watch – The Loop",
  regiao: "Osceola Parkway",
  tipo: "Americano",
  acesso: "12609 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 19,
  destaque: "Café da manhã robusto e brunch variado. Prato típico: Trifecta Breakfast (waffle, ovos e bacon).",
  latitude: 28.3389,
  longitude: -81.4541,
},
{
  nome: "Panera Bread – The Loop",
  regiao: "Osceola Parkway",
  tipo: "Tematico",
  acesso: "1267 W Osceola Pkwy, Kissimmee, FL 34741",
  precoMedio: 15,
  destaque: "Rede casual de sopas, saladas e sanduíches. Prato típico: Broccoli Cheddar Soup in Bread Bowl.",
  latitude: 28.3391,
  longitude: -81.4543,
},
{
  nome: "Perkins Restaurant & Bakery",
  regiao: "Osceola Parkway",
  tipo: "Conforto",
  acesso: "1700 W Osceola Pkwy, Kissimmee, FL 34741",
  precoMedio: 23,
  destaque: "Café americano caseiro e padaria tradicional. Prato típico: Brioche French Toast Platter.",
  latitude: 28.3390,
  longitude: -81.4542,
},
{
  nome: "Vitality Bowls – Kissimmee",
  regiao: "Osceola Parkway",
  tipo: "Saudavel",
  acesso: "1151 W Osceola Pkwy, Kissimmee, FL 34741",
  precoMedio: 14,
  destaque: "Rede focada em bowls energéticos e superfoods. Prato típico: Açai Energy Bowl.",
  latitude: 28.3392,
  longitude: -81.4544,
},
{
  nome: "Dunkin’ Osceola Parkway",
  regiao: "Osceola Parkway",
  tipo: "Economico",
  acesso: "1178 W Osceola Pkwy, Kissimmee, FL 34741",
  precoMedio: 6,
  destaque: "Donuts, cafés e sanduíches rápidos. Prato típico: Bagel com cream cheese.",
  latitude: 28.3388,
  longitude: -81.4540,
},

// 32 - Millenia Area
{
  nome: "Keke's Breakfast Café – Millenia",
  regiao: "Millenia Area",
  tipo: "Americano",
  acesso: "4192 Conroy Rd #100, Orlando, FL 32839",
  precoMedio: 20,
  destaque: "Café da manhã e brunch americano com panquecas e omeletes. Prato típico: Banana Nut Pancakes.",
  latitude: 28.4862,
  longitude: -81.4301,
},
{
  nome: "Earls Kitchen + Bar",
  regiao: "Millenia Area",
  tipo: "Tematico",
  acesso: "4200 Conroy Rd H246, Orlando, FL 32839",
  precoMedio: 42,
  destaque: "Ambiente moderno com pratos criativos e cocktails. Prato típico: Avocado Super Toast.",
  latitude: 28.4864,
  longitude: -81.4303,
},
{
  nome: "Brio Italian Grille – Millenia",
  regiao: "Millenia Area",
  tipo: "Conforto",
  acesso: "4200 Conroy Rd, Orlando, FL 32839",
  precoMedio: 24,
  destaque: "Clássicos italianos em ambiente refinado. Prato típico: Frittata Rustica.",
  latitude: 28.4863,
  longitude: -81.4302,
},
{
  nome: "The Cheesecake Factory – Millenia",
  regiao: "Millenia Area",
  tipo: "Saudavel",
  acesso: "4200 Conroy Rd A-148, Orlando, FL 32839",
  precoMedio: 17,
  destaque: "Menu extenso com opções leves e saladas icônicas. Prato típico: SkinnyLicious Chicken Salad.",
  latitude: 28.4865,
  longitude: -81.4304,
},
{
  nome: "Foxtail Coffee – Millenia",
  regiao: "Millenia Area",
  tipo: "Economico",
  acesso: "4200 Conroy Rd, Orlando, FL 32839",
  precoMedio: 6,
  destaque: "Cafeteria local com cafés especiais e pastries rápidos. Prato típico: Cold Brew com croissant de manteiga.",
  latitude: 28.4861,
  longitude: -81.4300,
},

// 33 - Southchase
{
  nome: "Metro Diner Southchase",
  regiao: "Southchase",
  tipo: "Americano",
  acesso: "120 S John Young Pkwy, Orlando, FL 32809",
  precoMedio: 18,
  destaque: "Clássico café americano com ovos, panquecas e bacon. Prato típico: Chicken & Waffles.",
  latitude: 28.3950,
  longitude: -81.3992,
},
{
  nome: "Chuy’s Tex-Mex Southchase",
  regiao: "Southchase",
  tipo: "Tematico",
  acesso: "6688 S Semoran Blvd, Orlando, FL 32822",
  precoMedio: 40,
  destaque: "Restaurante tex-mex vibrante com pratos criativos. Prato típico: Fajitas de Carne Asada.",
  latitude: 28.3952,
  longitude: -81.3994,
},
{
  nome: "Miller’s Ale House Southchase",
  regiao: "Southchase",
  tipo: "Conforto",
  acesso: "12771 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 22,
  destaque: "Ambiente acolhedor com pratos fartos e variados. Prato típico: Zinger Mountain Melt.",
  latitude: 28.3951,
  longitude: -81.3993,
},
{
  nome: "Tropical Smoothie Cafe Southchase",
  regiao: "Southchase",
  tipo: "Saudavel",
  acesso: "12005 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 15,
  destaque: "Smoothies, wraps e bowls leves e nutritivos. Prato típico: Island Green Smoothie.",
  latitude: 28.3953,
  longitude: -81.3995,
},
{
  nome: "Dunkin’ Southchase",
  regiao: "Southchase",
  tipo: "Economico",
  acesso: "12141 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 6,
  destaque: "Café rápido com donuts e sanduíches práticos. Prato típico: Egg & Cheese Croissant.",
  latitude: 28.3949,
  longitude: -81.3991,
},

// 34 - Baldwin Park
{
  nome: "The Osprey Tavern",
  regiao: "Baldwin Park",
  tipo: "Americano",
  acesso: "4899 New Broad St, Orlando, FL 32814",
  precoMedio: 20,
  destaque: "Clássicos americanos com toque moderno em ambiente elegante. Prato típico: Buttermilk Pancakes.",
  latitude: 28.5672,
  longitude: -81.3274,
},
{
  nome: "Seito Sushi Baldwin Park",
  regiao: "Baldwin Park",
  tipo: "Tematico",
  acesso: "4898 New Broad St, Orlando, FL 32814",
  precoMedio: 41,
  destaque: "Culinária japonesa moderna em ambiente sofisticado. Prato típico: Sushi Combo Brunch.",
  latitude: 28.5674,
  longitude: -81.3276,
},
{
  nome: "Gators Dockside Baldwin",
  regiao: "Baldwin Park",
  tipo: "Conforto",
  acesso: "4982 New Broad St, Orlando, FL 32814",
  precoMedio: 23,
  destaque: "Bar esportivo com brunch e pratos generosos. Prato típico: Chicken Wings + Waffles.",
  latitude: 28.5673,
  longitude: -81.3275,
},
{
  nome: "Green Kitchen Baldwin Park",
  regiao: "Baldwin Park",
  tipo: "Saudavel",
  acesso: "4982 New Broad St, Orlando, FL 32814",
  precoMedio: 14,
  destaque: "Opções leves com bowls e wraps nutritivos. Prato típico: Quinoa Avocado Bowl.",
  latitude: 28.5675,
  longitude: -81.3277,
},
{
  nome: "Dunkin’ Baldwin Park",
  regiao: "Baldwin Park",
  tipo: "Economico",
  acesso: "4796 New Broad St, Orlando, FL 32814",
  precoMedio: 6,
  destaque: "Rede prática com cafés e lanches rápidos. Prato típico: Bagel com Cream Cheese.",
  latitude: 28.5671,
  longitude: -81.3273,
},

// 35 - Sand Lake Road Area
{
  nome: "The Whiskey",
  regiao: "Sand Lake Road Area",
  tipo: "Americano",
  acesso: "7563 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 21,
  destaque: "Hambúrgueres artesanais e brunch americano moderno. Prato típico: The Whiskey Burger.",
  latitude: 28.4461,
  longitude: -81.4810,
},
{
  nome: "The Melting Pot Orlando",
  regiao: "Sand Lake Road Area",
  tipo: "Tematico",
  acesso: "7549 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 44,
  destaque: "Fondue temático em ambiente aconchegante. Prato típico: Classic Alpine Cheese Fondue.",
  latitude: 28.4463,
  longitude: -81.4812,
},
{
  nome: "Rocco’s Tacos & Tequila Bar",
  regiao: "Sand Lake Road Area",
  tipo: "Conforto",
  acesso: "7468 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 24,
  destaque: "Tex-Mex descontraído com brunch aos finais de semana. Prato típico: Huevos Rancheros.",
  latitude: 28.4462,
  longitude: -81.4811,
},
{
  nome: "Too Much Sauce",
  regiao: "Sand Lake Road Area",
  tipo: "Saudavel",
  acesso: "7455 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 16,
  destaque: "Bowls saudáveis e personalizáveis com molhos especiais. Prato típico: Spicy Chicken Bowl.",
  latitude: 28.4464,
  longitude: -81.4813,
},
{
  nome: "Dunkin’ Sand Lake",
  regiao: "Sand Lake Road Area",
  tipo: "Economico",
  acesso: "7515 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 6,
  destaque: "Café rápido e econômico com donuts e cafés variados. Prato típico: Iced Coffee com Boston Kreme Donut.",
  latitude: 28.4460,
  longitude: -81.4809,
},

// 36 - North Kissimmee
{
  nome: "Denny’s North Kissimmee",
  regiao: "North Kissimmee",
  tipo: "Americano",
  acesso: "4018 W Vine St, Kissimmee, FL 34741",
  precoMedio: 19,
  destaque: "Rede clássica americana com panquecas, ovos e bacon. Prato típico: Grand Slam Breakfast.",
  latitude: 28.3050,
  longitude: -81.4695,
},
{
  nome: "Medieval Times Dinner & Tournament",
  regiao: "North Kissimmee",
  tipo: "Tematico",
  acesso: "4510 W Vine St, Kissimmee, FL 34746",
  precoMedio: 42,
  destaque: "Show medieval com jantar incluso em cenário temático. Prato típico: Roasted Chicken com Batatas.",
  latitude: 28.3056,
  longitude: -81.4692,
},
{
  nome: "Cracker Barrel Old Country Store",
  regiao: "North Kissimmee",
  tipo: "Conforto",
  acesso: "5400 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 22,
  destaque: "Café caseiro sulista em ambiente rústico. Prato típico: Biscuits & Gravy.",
  latitude: 28.3078,
  longitude: -81.4299,
},
{
  nome: "Nature’s Table Kissimmee",
  regiao: "North Kissimmee",
  tipo: "Saudavel",
  acesso: "101 W Cypress St, Kissimmee, FL 34741",
  precoMedio: 15,
  destaque: "Bowls e wraps nutritivos em ambiente casual. Prato típico: Baja Chicken Wrap.",
  latitude: 28.3164,
  longitude: -81.4383,
},
{
  nome: "Dunkin’ North Kissimmee",
  regiao: "North Kissimmee",
  tipo: "Economico",
  acesso: "1040 W Vine St, Kissimmee, FL 34741",
  precoMedio: 6,
  destaque: "Café acessível e prático com donuts clássicos. Prato típico: Café preto com Glazed Donut.",
  latitude: 28.3062,
  longitude: -81.4697,
},

// 38 - Reunion
{
  nome: "Traditions at Reunion Resort",
  regiao: "Reunion",
  tipo: "Americano",
  acesso: "7593 Gathering Dr, Kissimmee, FL 34747",
  precoMedio: 28,
  destaque: "Café da manhã completo com pratos americanos clássicos em ambiente elegante. Prato típico: Avocado Toast com ovos.",
  latitude: 28.2648,
  longitude: -81.5882,
  instagram: "https://www.instagram.com/reunionresort/",
},
{
  nome: "Eleven at Reunion Resort",
  regiao: "Reunion",
  tipo: "Tematico",
  acesso: "7593 Gathering Dr, Kissimmee, FL 34747",
  precoMedio: 35,
  destaque: "Restaurante no rooftop com temática moderna e brunch sofisticado. Prato típico: Smoked Salmon Benedict.",
  latitude: 28.2650,
  longitude: -81.5878,
  instagram: "https://www.instagram.com/reunionresort/",
},
{
  nome: "Clubhouse Grille",
  regiao: "Reunion",
  tipo: "Conforto",
  acesso: "7593 Gathering Dr, Kissimmee, FL 34747",
  precoMedio: 22,
  destaque: "Brunch casual com omeletes, panquecas e comfort food americana. Prato típico: Buttermilk Pancakes.",
  latitude: 28.2652,
  longitude: -81.5885,
  instagram: "https://www.instagram.com/reunionresort/",
},
{
  nome: "Dunkin’ – Reunion",
  regiao: "Reunion",
  tipo: "Economico",
  acesso: "7810 Lake Wilson Rd, Davenport, FL 33896",
  precoMedio: 7,
  destaque: "Donuts, cafés e sanduíches rápidos em rede popular. Prato típico: Café médio + Glazed Donut.",
  latitude: 28.2625,
  longitude: -81.5930,
  instagram: "https://www.instagram.com/dunkin/",
},
{
  nome: "Starbucks – Reunion",
  regiao: "Reunion",
  tipo: "Saudavel",
  acesso: "7970 Lake Wilson Rd, Davenport, FL 33896",
  precoMedio: 9,
  destaque: "Cafeteria moderna com cafés especiais, bowls e wraps leves. Prato típico: Spinach, Feta & Egg White Wrap.",
  latitude: 28.2632,
  longitude: -81.5940,
  instagram: "https://www.instagram.com/starbucks/",
},




];
