export const jantaresProximos = [
// 1 - International Drive
{
  nome: "The Capital Grille",
  regiao: "International Drive",
  tipo: "Americano",
  acesso: "9101 International Dr, Suite 1000, Orlando, FL 32819",
  precoMedio: 36,
  destaque: "Steakhouse refinada com carnes dry aged e ambiente sofisticado. Prato tÃ­pico: Dry Aged Steak com purÃª trufado.",
  latitude: 28.4375,
  longitude: -81.4699,
},
{
  nome: "Toothsome Chocolate Emporium Dinner",
  regiao: "International Drive",
  tipo: "Tematico",
  acesso: "6000 Universal Blvd, Orlando, FL 32819",
  precoMedio: 51,
  destaque: "Restaurante temÃ¡tico steampunk com pratos criativos e milkshakes icÃ´nicos. Prato tÃ­pico: Milkshake de Red Velvet.",
  latitude: 28.4811,
  longitude: -81.4712,
},
{
  nome: "Olive Garden I-Drive",
  regiao: "International Drive",
  tipo: "Conforto",
  acesso: "8984 International Dr, Orlando, FL 32819",
  precoMedio: 28,
  destaque: "Massas italianas clÃ¡ssicas em ambiente familiar. Prato tÃ­pico: Fettuccine Alfredo.",
  latitude: 28.4361,
  longitude: -81.4702,
},
{
  nome: "Green Fork",
  regiao: "International Drive",
  tipo: "Saudavel",
  acesso: "7799 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 19,
  destaque: "Bowls, wraps e sucos prensados a frio com ingredientes frescos. Prato tÃ­pico: Bowl MediterrÃ¢neo.",
  latitude: 28.4462,
  longitude: -81.4820,
},
{
  nome: "Dennyâ€™s I-Drive",
  regiao: "International Drive",
  tipo: "Economico",
  acesso: "7660 International Dr, Orlando, FL 32819",
  precoMedio: 12,
  destaque: "Rede 24h com burgers e panquecas. Prato tÃ­pico: Grand Slam Breakfast.",
  latitude: 28.4518,
  longitude: -81.4703,
},

// 2 - Lake Buena Vista
{
  nome: "Chevys Fresh Mex",
  regiao: "Lake Buena Vista",
  tipo: "Americano",
  acesso: "12547 State Road 535, Orlando, FL 32836",
  precoMedio: 31,
  destaque: "Tex-Mex descontraÃ­do com margaritas e pratos generosos. Prato tÃ­pico: Fajitas de Carne.",
  latitude: 28.3854,
  longitude: -81.4992,
},
{
  nome: "Rainforest Cafe",
  regiao: "Lake Buena Vista",
  tipo: "Tematico",
  acesso: "1486 Buena Vista Dr, Orlando, FL 32830",
  precoMedio: 46,
  destaque: "Ambiente de floresta tropical com sons e efeitos imersivos. Prato tÃ­pico: Ribs, Steak & Shrimp Trio.",
  latitude: 28.3691,
  longitude: -81.5195,
},
{
  nome: "The Polite Pig",
  regiao: "Lake Buena Vista",
  tipo: "Conforto",
  acesso: "Disney Springs, 1536 Buena Vista Dr, Orlando, FL 32830",
  precoMedio: 27,
  destaque: "Churrasco artesanal com acompanhamentos sulistas. Prato tÃ­pico: Pulled Pork com cornbread.",
  latitude: 28.3698,
  longitude: -81.5191,
},
{
  nome: "Sweet Tomatoes LBV (FECHADO, SUBSTITUÃDO por First Watch LBV)",
  regiao: "Lake Buena Vista",
  tipo: "Saudavel",
  acesso: "12359 S Apopka Vineland Rd, Orlando, FL 32836",
  precoMedio: 18,
  destaque: "Rede de brunch saudÃ¡vel com bowls e pratos leves. Prato tÃ­pico: Avocado Toast com ovo pochÃª.",
  latitude: 28.3865,
  longitude: -81.4987,
},
{
  nome: "Millerâ€™s Ale House LBV",
  regiao: "Lake Buena Vista",
  tipo: "Economico",
  acesso: "12371 Winter Garden Vineland Rd, Orlando, FL 32836",
  precoMedio: 14,
  destaque: "Esportivo casual com pratos fartos e baratos. Prato tÃ­pico: Zinger Wings.",
  latitude: 28.3852,
  longitude: -81.4991,
},

// 3 - Kissimmee
{
  nome: "Loganâ€™s Roadhouse",
  regiao: "Kissimmee",
  tipo: "Americano",
  acesso: "8191 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 29,
  destaque: "Steaks, ribs e pÃ£es quentinhos em ambiente descontraÃ­do. Prato tÃ­pico: Roadhouse Sirloin.",
  latitude: 28.3047,
  longitude: -81.4383,
},
{
  nome: "Medieval Times Dinner & Tournament",
  regiao: "Kissimmee",
  tipo: "Tematico",
  acesso: "4510 W Vine St, Kissimmee, FL 34746",
  precoMedio: 65,
  destaque: "Jantar medieval com espetÃ¡culo de cavaleiros. Prato tÃ­pico: Frango Assado Inteiro estilo medieval.",
  latitude: 28.3243,
  longitude: -81.4675,
},
{
  nome: "Cracker Barrel Kissimmee",
  regiao: "Kissimmee",
  tipo: "Conforto",
  acesso: "5400 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 23,
  destaque: "Comida sulista em ambiente rÃºstico. Prato tÃ­pico: Chicken nâ€™ Dumplins.",
  latitude: 28.3081,
  longitude: -81.4415,
},
{
  nome: "Green Leaf Grill",
  regiao: "Kissimmee",
  tipo: "Saudavel",
  acesso: "5770 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 17,
  destaque: "RefeiÃ§Ãµes leves, wraps e grelhados saudÃ¡veis. Prato tÃ­pico: Grilled Chicken Wrap.",
  latitude: 28.3095,
  longitude: -81.4422,
},
{
  nome: "Wendyâ€™s Kissimmee",
  regiao: "Kissimmee",
  tipo: "Economico",
  acesso: "5781 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 9,
  destaque: "Rede fast food americana com burgers e batatas. Prato tÃ­pico: Baconator.",
  latitude: 28.3102,
  longitude: -81.4431,
},

// 4 - Celebration
{
  nome: "Columbia Restaurant Celebration",
  regiao: "Celebration",
  tipo: "Americano",
  acesso: "649 Front St, Celebration, FL 34747",
  precoMedio: 37,
  destaque: "Restaurante histÃ³rico com pratos espanhÃ³is e cubanos. Prato tÃ­pico: Paella Valenciana.",
  latitude: 28.3176,
  longitude: -81.5407,
},
{
  nome: "Bohemian Hotel â€“ Lakeside Bar & Grill",
  regiao: "Celebration",
  tipo: "Tematico",
  acesso: "700 Bloom St, Celebration, FL 34747",
  precoMedio: 48,
  destaque: "Hotel com jantar elegante e pratos autorais. Prato tÃ­pico: Seared Scallops.",
  latitude: 28.3180,
  longitude: -81.5411,
},
{
  nome: "Celebration Town Tavern",
  regiao: "Celebration",
  tipo: "Conforto",
  acesso: "721 Front St, Celebration, FL 34747",
  precoMedio: 27,
  destaque: "Comida americana tradicional e frutos do mar. Prato tÃ­pico: New England Clam Chowder.",
  latitude: 28.3184,
  longitude: -81.5405,
},
{
  nome: "Vitality Bowls Celebration",
  regiao: "Celebration",
  tipo: "Saudavel",
  acesso: "671 Front St, Celebration, FL 34747",
  precoMedio: 21,
  destaque: "AÃ§aÃ­ bowls, saladas e smoothies frescos. Prato tÃ­pico: Nutty Bowl.",
  latitude: 28.3190,
  longitude: -81.5413,
},
{
  nome: "Upper Crust Pizza",
  regiao: "Celebration",
  tipo: "Economico",
  acesso: "606 Market St, Celebration, FL 34747",
  precoMedio: 13,
  destaque: "Pizzaria casual com preÃ§os acessÃ­veis. Prato tÃ­pico: Pepperoni Pizza.",
  latitude: 28.3179,
  longitude: -81.5410,
},

// 6 - Windsor Hills
{
  nome: "Outback Steakhouse Kissimmee",
  regiao: "Windsor Hills",
  tipo: "Americano",
  acesso: "7804 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 35,
  destaque: "Steaks, costelas e pratos inspirados na AustrÃ¡lia. Prato tÃ­pico: Outback Special Sirloin.",
  latitude: 28.3271,
  longitude: -81.5869,
},
{
  nome: "Fordâ€™s Garage Sunset Walk",
  regiao: "Windsor Hills",
  tipo: "Tematico",
  acesso: "3251 Margaritaville Blvd, Kissimmee, FL 34747",
  precoMedio: 32,
  destaque: "TemÃ¡tico automotivo com hambÃºrgueres gourmet. Prato tÃ­pico: Fordâ€™s Signature Burger.",
  latitude: 28.3349,
  longitude: -81.5886,
},
{
  nome: "Carrabbaâ€™s Italian Grill",
  regiao: "Windsor Hills",
  tipo: "Conforto",
  acesso: "7890 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 26,
  destaque: "Italiano acolhedor com massas e carnes grelhadas. Prato tÃ­pico: Chicken Bryan.",
  latitude: 28.3287,
  longitude: -81.5890,
},
{
  nome: "Freshii Windsor",
  regiao: "Windsor Hills",
  tipo: "Saudavel",
  acesso: "7802 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 20,
  destaque: "Bowls, wraps e smoothies frescos. Prato tÃ­pico: Oaxaca Bowl.",
  latitude: 28.3269,
  longitude: -81.5874,
},
{
  nome: "IHOP Windsor Hills",
  regiao: "Windsor Hills",
  tipo: "Economico",
  acesso: "7491 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 11,
  destaque: "Rede econÃ´mica de panquecas e omeletes. Prato tÃ­pico: Original Buttermilk Pancakes.",
  latitude: 28.3291,
  longitude: -81.5863,
},

// 7 - ChampionsGate
{
  nome: "Chiliâ€™s ChampionsGate",
  regiao: "ChampionsGate",
  tipo: "Americano",
  acesso: "8180 Laura Ln, Davenport, FL 33896",
  precoMedio: 32,
  destaque: "Tex-Mex e hambÃºrgueres em ambiente casual. Prato tÃ­pico: Baby Back Ribs.",
  latitude: 28.2634,
  longitude: -81.6501,
},
{
  nome: "Treviâ€™s at Omni Orlando",
  regiao: "ChampionsGate",
  tipo: "Tematico",
  acesso: "1500 Masters Blvd, ChampionsGate, FL 33896",
  precoMedio: 52,
  destaque: "Italiano sofisticado dentro do Omni Resort. Prato tÃ­pico: Fettuccine Alfredo.",
  latitude: 28.2639,
  longitude: -81.6509,
},
{
  nome: "Millerâ€™s Ale House ChampionsGate",
  regiao: "ChampionsGate",
  tipo: "Conforto",
  acesso: "8170 Laura Ln, Davenport, FL 33896",
  precoMedio: 24,
  destaque: "Pub esportivo com pratos variados. Prato tÃ­pico: Zingers com molho de alho.",
  latitude: 28.2641,
  longitude: -81.6492,
},
{
  nome: "Bolay ChampionsGate",
  regiao: "ChampionsGate",
  tipo: "Saudavel",
  acesso: "7809 Osceola Polk Line Rd, Davenport, FL 33896",
  precoMedio: 19,
  destaque: "Bowls saudÃ¡veis e frescos personalizÃ¡veis. Prato tÃ­pico: Teriyaki Chicken Bowl.",
  latitude: 28.2636,
  longitude: -81.6497,
},
{
  nome: "Subway ChampionsGate",
  regiao: "ChampionsGate",
  tipo: "Economico",
  acesso: "8301 Champions Gate Blvd #103, ChampionsGate, FL 33896",
  precoMedio: 10,
  destaque: "SanduÃ­ches rÃ¡pidos e baratos. Prato tÃ­pico: Italian B.M.T.",
  latitude: 28.2637,
  longitude: -81.6499,
},

// 8 - Four Corners
{
  nome: "Texas Roadhouse Four Corners",
  regiao: "Four Corners",
  tipo: "Americano",
  acesso: "7973 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 30,
  destaque: "Steaks, pÃ£es caseiros e porÃ§Ãµes fartas. Prato tÃ­pico: Ft. Worth Ribeye.",
  latitude: 28.3322,
  longitude: -81.6421,
},
{
  nome: "Flippers Pizzeria Four Corners",
  regiao: "Four Corners",
  tipo: "Tematico",
  acesso: "5770 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 25,
  destaque: "Pizzaria temÃ¡tica local com forno a lenha. Prato tÃ­pico: Pepperoni Rustica Pizza.",
  latitude: 28.3330,
  longitude: -81.6415,
},
{
  nome: "Bonefish Grill Four Corners",
  regiao: "Four Corners",
  tipo: "Conforto",
  acesso: "7801 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 28,
  destaque: "Frutos do mar grelhados em ambiente refinado. Prato tÃ­pico: Bang Bang Shrimp.",
  latitude: 28.3331,
  longitude: -81.6434,
},
{
  nome: "Clean Eatz Four Corners",
  regiao: "Four Corners",
  tipo: "Saudavel",
  acesso: "7790 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 18,
  destaque: "RefeiÃ§Ãµes balanceadas e fitness. Prato tÃ­pico: Build-Your-Own Bowl.",
  latitude: 28.3340,
  longitude: -81.6440,
},
{
  nome: "Taco Bell Four Corners",
  regiao: "Four Corners",
  tipo: "Economico",
  acesso: "7802 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 8,
  destaque: "Tex-Mex econÃ´mico para refeiÃ§Ãµes rÃ¡pidas. Prato tÃ­pico: Crunchwrap Supreme.",
  latitude: 28.3329,
  longitude: -81.6426,
},

// 9 - Vineland Premium Outlets (Jantar)
{
  nome: "The Capital Grille Vineland",
  regiao: "Vineland Premium Outlets",
  tipo: "Americano",
  acesso: "9101 International Dr Suite 1000, Orlando, FL 32819",
  precoMedio: 60,
  destaque: "Steakhouse sofisticada com cortes premium e vinhos selecionados. Experimente o Dry Aged NY Strip.",
  latitude: 28.3859,
  longitude: -81.4902,
  instagram: "https://www.instagram.com/thecapitalgrille/",
},
{
  nome: "Benihana Orlando",
  regiao: "Vineland Premium Outlets",
  tipo: "Tematico",
  acesso: "12650 International Dr S, Orlando, FL 32821",
  precoMedio: 45,
  destaque: "Teppanyaki japonÃªs com chefs preparando os pratos na chapa em frente aos clientes. Experimente o Hibachi Chicken & Shrimp.",
  latitude: 28.3858,
  longitude: -81.4891,
  instagram: "https://www.instagram.com/benihana/",
},
{
  nome: "Seasons 52 Vineland",
  regiao: "Vineland Premium Outlets",
  tipo: "Conforto",
  acesso: "7700 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 38,
  destaque: "Menu sazonal com pratos assados e opÃ§Ãµes leves. Experimente o Cedar Plank Salmon.",
  latitude: 28.3861,
  longitude: -81.4893,
  instagram: "https://www.instagram.com/seasons52/",
},
{
  nome: "Olive Garden Vineland",
  regiao: "Vineland Premium Outlets",
  tipo: "Italiano",
  acesso: "12361 S Apopka Vineland Rd, Orlando, FL 32836",
  precoMedio: 22,
  destaque: "ClÃ¡ssicos italianos com massas, sopas e breadsticks ilimitados. Experimente o Tour of Italy.",
  latitude: 28.3862,
  longitude: -81.4887,
  instagram: "https://www.instagram.com/olivegarden/",
},
{
  nome: "Bahama Breeze Vineland",
  regiao: "Vineland Premium Outlets",
  tipo: "Tematico",
  acesso: "8735 Vineland Ave, Orlando, FL 32821",
  precoMedio: 30,
  destaque: "CulinÃ¡ria caribenha com mÃºsica ao vivo e ambiente tropical. Experimente o Jerk Chicken Pasta.",
  latitude: 28.3864,
  longitude: -81.4885,
  instagram: "https://www.instagram.com/bahamabreezeislandgrille/",
},


// 9 - Reunion
{
  nome: "Eleven at Reunion Resort",
  regiao: "Reunion",
  tipo: "Americano",
  acesso: "7593 Gathering Dr, Kissimmee, FL 34747",
  precoMedio: 45,
  destaque: "Restaurante rooftop com carnes nobres e vista incrÃ­vel. Prato tÃ­pico: Filet Mignon.",
  latitude: 28.2810,
  longitude: -81.5882,
},
{
  nome: "Forte at Reunion Resort",
  regiao: "Reunion",
  tipo: "Tematico",
  acesso: "7593 Gathering Dr, Kissimmee, FL 34747",
  precoMedio: 52,
  destaque: "Italiano sofisticado dentro do resort. Prato tÃ­pico: Osso Buco.",
  latitude: 28.2808,
  longitude: -81.5880,
},
{
  nome: "Reunion CafÃ©",
  regiao: "Reunion",
  tipo: "Conforto",
  acesso: "7525 Osceola Polk Line Rd, Davenport, FL 33896",
  precoMedio: 21,
  destaque: "Restaurante casual com pratos caseiros. Prato tÃ­pico: Country Fried Chicken.",
  latitude: 28.2821,
  longitude: -81.5875,
},
{
  nome: "Vitality Bowls Reunion",
  regiao: "Reunion",
  tipo: "Saudavel",
  acesso: "7800 Lake Wilson Rd #105, Davenport, FL 33896",
  precoMedio: 17,
  destaque: "Bowls energÃ©ticos e nutritivos. Prato tÃ­pico: AÃ§ai Energy Bowl.",
  latitude: 28.2825,
  longitude: -81.5868,
},
{
  nome: "Burger King Reunion",
  regiao: "Reunion",
  tipo: "Economico",
  acesso: "7790 Lake Wilson Rd, Davenport, FL 33896",
  precoMedio: 7,
  destaque: "Rede econÃ´mica de fast-food. Prato tÃ­pico: Whopper.",
  latitude: 28.2832,
  longitude: -81.5880,
},

// 10 - Davenport
{
  nome: "LongHorn Steakhouse Davenport",
  regiao: "Davenport",
  tipo: "Americano",
  acesso: "8110 Osceola Polk Line Rd, Davenport, FL 33896",
  precoMedio: 34,
  destaque: "Steaks grelhados no estilo sulista. Prato tÃ­pico: Outlaw Ribeye.",
  latitude: 28.2345,
  longitude: -81.6432,
},
{
  nome: "Ovation Bistro & Bar",
  regiao: "Davenport",
  tipo: "Tematico",
  acesso: "42605 US-27, Davenport, FL 33837",
  precoMedio: 39,
  destaque: "Restaurante local com carnes e frutos do mar em ambiente moderno. Prato tÃ­pico: Baby Back Ribs.",
  latitude: 28.2361,
  longitude: -81.6407,
},
{
  nome: "Perkins Restaurant & Bakery",
  regiao: "Davenport",
  tipo: "Conforto",
  acesso: "43522 US Hwy 27, Davenport, FL 33837",
  precoMedio: 23,
  destaque: "Comida caseira americana e padaria prÃ³pria. Prato tÃ­pico: Chicken Pot Pie.",
  latitude: 28.2339,
  longitude: -81.6411,
},
{
  nome: "Natureâ€™s Table Davenport",
  regiao: "Davenport",
  tipo: "Saudavel",
  acesso: "40544 US Hwy 27, Davenport, FL 33837",
  precoMedio: 19,
  destaque: "Pratos leves, wraps e smoothies nutritivos. Prato tÃ­pico: Baja Turkey Wrap.",
  latitude: 28.2355,
  longitude: -81.6420,
},
{
  nome: "Little Caesars Davenport",
  regiao: "Davenport",
  tipo: "Economico",
  acesso: "42605 US-27, Davenport, FL 33837",
  precoMedio: 9,
  destaque: "Rede de pizzas rÃ¡pidas e baratas. Prato tÃ­pico: Hot-N-Ready Pepperoni.",
  latitude: 28.2347,
  longitude: -81.6418,
},

// 11 - Westgate Lakes
{
  nome: "Drafts Sports Bar & Grill",
  regiao: "Westgate Lakes",
  tipo: "Americano",
  acesso: "10000 Turkey Lake Rd, Orlando, FL 32819",
  precoMedio: 29,
  destaque: "Bar esportivo descontraÃ­do com burgers, steaks e cervejas. Prato tÃ­pico: Drafts Burger.",
  latitude: 28.4278,
  longitude: -81.4829,
},
{
  nome: "Villa Italiano Chophouse",
  regiao: "Westgate Lakes",
  tipo: "Tematico",
  acesso: "7700 Westgate Blvd, Kissimmee, FL 34747",
  precoMedio: 42,
  destaque: "Ambiente elegante com pratos italianos e carnes premium. Prato tÃ­pico: Osso Buco.",
  latitude: 28.4273,
  longitude: -81.4831,
},
{
  nome: "Sidâ€™s Bistro",
  regiao: "Westgate Lakes",
  tipo: "Conforto",
  acesso: "7700 Westgate Blvd, Kissimmee, FL 34747",
  precoMedio: 25,
  destaque: "SanduÃ­ches quentes, sopas e saladas em espaÃ§o acolhedor. Prato tÃ­pico: French Dip Sandwich.",
  latitude: 28.4275,
  longitude: -81.4830,
},
{
  nome: "The Juice Bar Westgate",
  regiao: "Westgate Lakes",
  tipo: "Saudavel",
  acesso: "7700 Westgate Blvd, Kissimmee, FL 34747",
  precoMedio: 18,
  destaque: "Sucos prensados a frio, smoothies e bowls nutritivos. Prato tÃ­pico: AÃ§aÃ­ Energy Bowl.",
  latitude: 28.4276,
  longitude: -81.4832,
},
{
  nome: "Cordovano Joeâ€™s Pizza",
  regiao: "Westgate Lakes",
  tipo: "Economico",
  acesso: "7700 Westgate Blvd, Kissimmee, FL 34747",
  precoMedio: 14,
  destaque: "Pizzas acessÃ­veis e prÃ¡ticas para toda a famÃ­lia. Prato tÃ­pico: Pepperoni Pizza.",
  latitude: 28.4279,
  longitude: -81.4833,
},

// 12 - Vista Cay
{
  nome: "NYPD Pizza",
  regiao: "Vista Cay",
  tipo: "Americano",
  acesso: "9900 Universal Blvd #100, Orlando, FL 32819",
  precoMedio: 20,
  destaque: "Pizzaria estilo Nova Iorque com fatias generosas. Prato tÃ­pico: New York Thin Crust Pepperoni.",
  latitude: 28.4212,
  longitude: -81.4674,
},
{
  nome: "Mikado Japanese Steakhouse",
  regiao: "Vista Cay",
  tipo: "Tematico",
  acesso: "7499 Augusta National Dr, Orlando, FL 32822",
  precoMedio: 48,
  destaque: "JaponÃªs tradicional com show de teppan. Prato tÃ­pico: Hibachi Filet Mignon.",
  latitude: 28.4210,
  longitude: -81.4669,
},
{
  nome: "Bethâ€™s Burger Bar",
  regiao: "Vista Cay",
  tipo: "Conforto",
  acesso: "9938 Universal Blvd, Orlando, FL 32819",
  precoMedio: 22,
  destaque: "HambÃºrgueres artesanais e batatas especiais. Prato tÃ­pico: Peanut Butter Burger.",
  latitude: 28.4215,
  longitude: -81.4670,
},
{
  nome: "Freshii Vista Cay",
  regiao: "Vista Cay",
  tipo: "Saudavel",
  acesso: "9930 Universal Blvd, Orlando, FL 32819",
  precoMedio: 19,
  destaque: "OpÃ§Ãµes leves como bowls, wraps e smoothies. Prato tÃ­pico: Buddhaâ€™s Satay Bowl.",
  latitude: 28.4213,
  longitude: -81.4672,
},
{
  nome: "Subway Vista Cay",
  regiao: "Vista Cay",
  tipo: "Economico",
  acesso: "9938 Universal Blvd Ste 130, Orlando, FL 32819",
  precoMedio: 11,
  destaque: "SanduÃ­ches rÃ¡pidos e econÃ´micos. Prato tÃ­pico: Italian B.M.T.",
  latitude: 28.4216,
  longitude: -81.4673,
},

// 14 - Dr. Phillips
{
  nome: "Ruthâ€™s Chris Steak House",
  regiao: "Dr. Phillips",
  tipo: "Americano",
  acesso: "7501 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 52,
  destaque: "Steakhouse refinada com carnes nobres. Prato tÃ­pico: Filet Mignon com manteiga.",
  latitude: 28.4581,
  longitude: -81.4899,
},
{
  nome: "The Melting Pot",
  regiao: "Dr. Phillips",
  tipo: "Tematico",
  acesso: "7549 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 49,
  destaque: "Fondue em ambiente intimista. Prato tÃ­pico: Fondue de queijo suÃ­Ã§o clÃ¡ssico.",
  latitude: 28.4583,
  longitude: -81.4901,
},
{
  nome: "Seasons 52",
  regiao: "Dr. Phillips",
  tipo: "Conforto",
  acesso: "7700 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 34,
  destaque: "Menu sazonal com pratos leves e sofisticados. Prato tÃ­pico: Cedar Plank Salmon.",
  latitude: 28.4584,
  longitude: -81.4903,
},
{
  nome: "Fresh Kitchen Dr. Phillips",
  regiao: "Dr. Phillips",
  tipo: "Saudavel",
  acesso: "7600 Dr Phillips Blvd, Orlando, FL 32819",
  precoMedio: 20,
  destaque: "Pratos saudÃ¡veis personalizÃ¡veis em bowls. Prato tÃ­pico: Spicy Tofu Bowl.",
  latitude: 28.4586,
  longitude: -81.4905,
},
{
  nome: "Firehouse Subs Dr. Phillips",
  regiao: "Dr. Phillips",
  tipo: "Economico",
  acesso: "7541 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 12,
  destaque: "SanduÃ­ches quentes e acessÃ­veis. Prato tÃ­pico: Hook & Ladder Sub.",
  latitude: 28.4585,
  longitude: -81.4904,
},

// 16 - Orlando Airport Area
{
  nome: "Bonefish Grill Airport",
  regiao: "Orlando Airport Area",
  tipo: "Americano",
  acesso: "5463 Gateway Village Cir, Orlando, FL 32812",
  precoMedio: 35,
  destaque: "Frutos do mar em ambiente sofisticado. Prato tÃ­pico: Bang Bang Shrimp.",
  latitude: 28.4441,
  longitude: -81.3080,
},
{
  nome: "Marlowâ€™s Tavern",
  regiao: "Orlando Airport Area",
  tipo: "Tematico",
  acesso: "6889 Eagle Watch Dr, Orlando, FL 32822",
  precoMedio: 38,
  destaque: "Taverna moderna com pratos criativos e cervejas artesanais. Prato tÃ­pico: Tavern Burger.",
  latitude: 28.4435,
  longitude: -81.3085,
},
{
  nome: "LongHorn Steakhouse MCO",
  regiao: "Orlando Airport Area",
  tipo: "Conforto",
  acesso: "5449 Gateway Village Cir, Orlando, FL 32812",
  precoMedio: 32,
  destaque: "Steaks grelhados e ambiente familiar. Prato tÃ­pico: Outlaw Ribeye.",
  latitude: 28.4442,
  longitude: -81.3078,
},
{
  nome: "Harvest Bistro",
  regiao: "Orlando Airport Area",
  tipo: "Saudavel",
  acesso: "7499 Augusta National Dr, Orlando, FL 32822",
  precoMedio: 28,
  destaque: "RefeiÃ§Ãµes balanceadas em ambiente sofisticado. Prato tÃ­pico: Grilled Salmon Bowl.",
  latitude: 28.4440,
  longitude: -81.3082,
},
{
  nome: "Chiliâ€™s MCO",
  regiao: "Orlando Airport Area",
  tipo: "Economico",
  acesso: "One Jeff Fuqua Blvd, Orlando, FL 32827 (Terminal B)",
  precoMedio: 17,
  destaque: "Tex-mex prÃ¡tico e acessÃ­vel dentro do aeroporto. Prato tÃ­pico: Baby Back Ribs.",
  latitude: 28.4438,
  longitude: -81.3081,
},

// 17 - Downtown Orlando
{
  nome: "The Boheme",
  regiao: "Downtown Orlando",
  tipo: "Americano",
  acesso: "325 S Orange Ave, Orlando, FL 32801",
  precoMedio: 45,
  destaque: "Restaurante refinado no Grand Bohemian Hotel. Prato tÃ­pico: Filet Mignon.",
  latitude: 28.5421,
  longitude: -81.3790,
},
{
  nome: "Hamburger Maryâ€™s",
  regiao: "Downtown Orlando",
  tipo: "Tematico",
  acesso: "110 W Church St, Orlando, FL 32801",
  precoMedio: 33,
  destaque: "HambÃºrgueres divertidos com shows e atmosfera vibrante. Prato tÃ­pico: Queen Mary Burger.",
  latitude: 28.5418,
  longitude: -81.3787,
},
{
  nome: "Artisanâ€™s Table",
  regiao: "Downtown Orlando",
  tipo: "Conforto",
  acesso: "55 W Church St #128, Orlando, FL 32801",
  precoMedio: 30,
  destaque: "Menu criativo com pratos reconfortantes. Prato tÃ­pico: Short Rib Grilled Cheese.",
  latitude: 28.5416,
  longitude: -81.3789,
},
{
  nome: "Dandelion Community CafÃ©",
  regiao: "Downtown Orlando",
  tipo: "Saudavel",
  acesso: "618 N Thornton Ave, Orlando, FL 32803",
  precoMedio: 22,
  destaque: "CulinÃ¡ria vegetariana com ingredientes orgÃ¢nicos. Prato tÃ­pico: Giddyup Veggie Chili.",
  latitude: 28.5414,
  longitude: -81.3791,
},
{
  nome: "Gringos Locos",
  regiao: "Downtown Orlando",
  tipo: "Economico",
  acesso: "20 E Washington St, Orlando, FL 32801",
  precoMedio: 12,
  destaque: "Tacos e burritos rÃ¡pidos e baratos. Prato tÃ­pico: Double Dâ€™s Taco.",
  latitude: 28.5413,
  longitude: -81.3792,
},

// 18 - Hunter's Creek
{
  nome: "Outback Steakhouse Hunterâ€™s Creek",
  regiao: "Hunter's Creek",
  tipo: "Americano",
  acesso: "8150 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 34,
  destaque: "Steaks e pratos australianos-americanos. Prato tÃ­pico: Victoriaâ€™s Filet.",
  latitude: 28.3661,
  longitude: -81.4063,
},
{
  nome: "Tijuana Flats Hunterâ€™s Creek",
  regiao: "Hunter's Creek",
  tipo: "Tematico",
  acesso: "4001 W Town Center Blvd, Orlando, FL 32837",
  precoMedio: 26,
  destaque: "Tex-mex vibrante com molhos autorais. Prato tÃ­pico: Tacos de Carnitas.",
  latitude: 28.3663,
  longitude: -81.4062,
},
{
  nome: "Millerâ€™s Ale House Hunterâ€™s Creek",
  regiao: "Hunter's Creek",
  tipo: "Conforto",
  acesso: "12711 S John Young Pkwy, Orlando, FL 32837",
  precoMedio: 28,
  destaque: "Pub esportivo descontraÃ­do. Prato tÃ­pico: Zingers Mountain Melt.",
  latitude: 28.3665,
  longitude: -81.4064,
},
{
  nome: "Bolay Fresh Bold Kitchen",
  regiao: "Hunter's Creek",
  tipo: "Saudavel",
  acesso: "15687 S Apopka Vineland Rd, Orlando, FL 32821",
  precoMedio: 23,
  destaque: "Bowls personalizados com ingredientes frescos. Prato tÃ­pico: Teriyaki Chicken Bowl.",
  latitude: 28.3666,
  longitude: -81.4066,
},
{
  nome: "McDonald's Hunterâ€™s Creek",
  regiao: "Hunter's Creek",
  tipo: "Economico",
  acesso: "13027 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 10,
  destaque: "Rede fast food rÃ¡pida e confiÃ¡vel. Prato tÃ­pico: Big Mac.",
  latitude: 28.3667,
  longitude: -81.4067,
},

// 19 - Windermere
{
  nome: "Yellow Dog Eats",
  regiao: "Windermere",
  tipo: "Americano",
  acesso: "1236 Hempel Ave, Windermere, FL 34786",
  precoMedio: 31,
  destaque: "SanduÃ­ches criativos e ambiente casual. Prato tÃ­pico: Pulled Pork Sandwich.",
  latitude: 28.5001,
  longitude: -81.5332,
},
{
  nome: "My French CafÃ©",
  regiao: "Windermere",
  tipo: "Tematico",
  acesso: "7782 Winter Garden Vineland Rd #100, Windermere, FL 34786",
  precoMedio: 36,
  destaque: "BistrÃ´ francÃªs aconchegante. Prato tÃ­pico: Quiche Lorraine.",
  latitude: 28.5003,
  longitude: -81.5334,
},
{
  nome: "Bella Tuscany",
  regiao: "Windermere",
  tipo: "Conforto",
  acesso: "13424 Summerport Village Pkwy, Windermere, FL 34786",
  precoMedio: 32,
  destaque: "Italiano tradicional com massas e vinhos. Prato tÃ­pico: Lasagna al Forno.",
  latitude: 28.5005,
  longitude: -81.5336,
},
{
  nome: "The Grove Orlando",
  regiao: "Windermere",
  tipo: "Saudavel",
  acesso: "4744 S Apopka Vineland Rd, Orlando, FL 32819",
  precoMedio: 27,
  destaque: "CafÃ© natural com pratos orgÃ¢nicos e frescos. Prato tÃ­pico: Avocado Toast.",
  latitude: 28.5007,
  longitude: -81.5338,
},
{
  nome: "Subway Windermere",
  regiao: "Windermere",
  tipo: "Economico",
  acesso: "6516 Old Brick Rd Ste 140, Windermere, FL 34786",
  precoMedio: 11,
  destaque: "SanduÃ­ches prÃ¡ticos e baratos. Prato tÃ­pico: Meatball Marinara Sub.",
  latitude: 28.5009,
  longitude: -81.5340,
},

// 20 - Winter Garden
{
  nome: "Urban Flats",
  regiao: "Winter Garden",
  tipo: "Americano",
  acesso: "132 W Plant St, Winter Garden, FL 34787",
  precoMedio: 33,
  destaque: "American grill com vinhos e pratos variados. Prato tÃ­pico: Flatbread de Frango BBQ.",
  latitude: 28.5650,
  longitude: -81.5865,
},
{
  nome: "MoonCricket Grille",
  regiao: "Winter Garden",
  tipo: "Tematico",
  acesso: "14 W Plant St, Winter Garden, FL 34787",
  precoMedio: 29,
  destaque: "Restaurante animado em espaÃ§o histÃ³rico. Prato tÃ­pico: Crab Cake Sandwich.",
  latitude: 28.5652,
  longitude: -81.5866,
},
{
  nome: "The Whole Enchilada",
  regiao: "Winter Garden",
  tipo: "Conforto",
  acesso: "129 W Plant St, Winter Garden, FL 34787",
  precoMedio: 27,
  destaque: "Tex-Mex acolhedor em ambiente familiar. Prato tÃ­pico: Burrito Especial.",
  latitude: 28.5654,
  longitude: -81.5867,
},
{
  nome: "Plant St. Market - Pressâ€™d",
  regiao: "Winter Garden",
  tipo: "Saudavel",
  acesso: "426 W Plant St, Winter Garden, FL 34787",
  precoMedio: 21,
  destaque: "Sucos prensados a frio e pratos naturais. Prato tÃ­pico: Kale Caesar Wrap.",
  latitude: 28.5656,
  longitude: -81.5868,
},
{
  nome: "Five Guys Winter Garden",
  regiao: "Winter Garden",
  tipo: "Economico",
  acesso: "3371 Daniels Rd, Winter Garden, FL 34787",
  precoMedio: 14,
  destaque: "Rede de hambÃºrgueres frescos e acessÃ­veis. Prato tÃ­pico: Cheeseburger com batata rÃºstica.",
  latitude: 28.5658,
  longitude: -81.5869,
},

// 21 - Altamonte Springs
{
  nome: "Seasons 52",
  regiao: "Altamonte Springs",
  tipo: "Americano",
  acesso: "463 E Altamonte Dr, Altamonte Springs, FL 32701",
  precoMedio: 38,
  destaque: "CardÃ¡pio sazonal, pratos grelhados e ambiente elegante. Prato tÃ­pico: Cedar Plank Salmon.",
  latitude: 28.6645,
  longitude: -81.3859,
},
{
  nome: "Kobe Japanese Steakhouse",
  regiao: "Altamonte Springs",
  tipo: "Tematico",
  acesso: "468 W State Rd 436, Altamonte Springs, FL 32714",
  precoMedio: 42,
  destaque: "Show de teppanyaki com cortes de carne e frutos do mar. Prato tÃ­pico: Hibachi Steak.",
  latitude: 28.6650,
  longitude: -81.3861,
},
{
  nome: "Olive Garden Altamonte",
  regiao: "Altamonte Springs",
  tipo: "Conforto",
  acesso: "300 E Altamonte Dr, Altamonte Springs, FL 32701",
  precoMedio: 30,
  destaque: "Italiana clÃ¡ssica com massas e sopas ilimitadas. Prato tÃ­pico: Fettuccine Alfredo.",
  latitude: 28.6648,
  longitude: -81.3860,
},
{
  nome: "Fresh Kitchen Altamonte",
  regiao: "Altamonte Springs",
  tipo: "Saudavel",
  acesso: "398 E Altamonte Dr, Altamonte Springs, FL 32701",
  precoMedio: 24,
  destaque: "Bowls de proteÃ­nas, grÃ£os e vegetais frescos. Prato tÃ­pico: Southwest Chicken Bowl.",
  latitude: 28.6647,
  longitude: -81.3858,
},
{
  nome: "Tijuana Flats Altamonte",
  regiao: "Altamonte Springs",
  tipo: "Economico",
  acesso: "190 E Altamonte Dr Ste 1020, Altamonte Springs, FL 32701",
  precoMedio: 13,
  destaque: "Tex-Mex descontraÃ­do com molhos caseiros. Prato tÃ­pico: Tacos de Carne Asada.",
  latitude: 28.6651,
  longitude: -81.3862,
},

// 22 - Clermont
{
  nome: "Guru Restaurant Clermont",
  regiao: "Clermont",
  tipo: "Americano",
  acesso: "2400 S Hwy 27, Clermont, FL 34711",
  precoMedio: 29,
  destaque: "Americano casual com carnes grelhadas e vista para o lago. Prato tÃ­pico: Prime Rib.",
  latitude: 28.5456,
  longitude: -81.7282,
},
{
  nome: "San Jose's Original Mexican Restaurant",
  regiao: "Clermont",
  tipo: "Tematico",
  acesso: "2400 S Clermont Citrus Tower Blvd, Clermont, FL 34711",
  precoMedio: 26,
  destaque: "Mexicano tradicional em ambiente festivo. Prato tÃ­pico: Enchiladas Verdes.",
  latitude: 28.5460,
  longitude: -81.7285,
},
{
  nome: "Carrabba's Italian Grill Clermont",
  regiao: "Clermont",
  tipo: "Conforto",
  acesso: "2240 E Hwy 50, Clermont, FL 34711",
  precoMedio: 32,
  destaque: "Italiano familiar com massas e carnes grelhadas. Prato tÃ­pico: Chicken Marsala.",
  latitude: 28.5462,
  longitude: -81.7287,
},
{
  nome: "Planet Smoothie & Bowl",
  regiao: "Clermont",
  tipo: "Saudavel",
  acesso: "1738 E Hwy 50, Clermont, FL 34711",
  precoMedio: 20,
  destaque: "Smoothies e bowls com frutas frescas. Prato tÃ­pico: AÃ§ai Energy Bowl.",
  latitude: 28.5465,
  longitude: -81.7290,
},
{
  nome: "Zaxby's Clermont",
  regiao: "Clermont",
  tipo: "Economico",
  acesso: "2375 S Hwy 27, Clermont, FL 34711",
  precoMedio: 11,
  destaque: "Rede de frango empanado com porÃ§Ãµes fartas. Prato tÃ­pico: Chicken Finger Plate.",
  latitude: 28.5468,
  longitude: -81.7292,
},

// 23 - Oak Ridge
{
  nome: "Red Lobster Oak Ridge",
  regiao: "Oak Ridge",
  tipo: "Americano",
  acesso: "3552 S Orange Blossom Trl, Orlando, FL 32839",
  precoMedio: 35,
  destaque: "Especializado em frutos do mar frescos. Prato tÃ­pico: Ultimate Feast.",
  latitude: 28.4750,
  longitude: -81.3980,
},
{
  nome: "Azteca Dâ€™Oro Mexican Restaurant",
  regiao: "Oak Ridge",
  tipo: "Tematico",
  acesso: "12403 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 30,
  destaque: "Mexicano autÃªntico com margaritas artesanais. Prato tÃ­pico: Fajitas Mistas.",
  latitude: 28.4752,
  longitude: -81.3982,
},
{
  nome: "Cheddarâ€™s Scratch Kitchen Oak Ridge",
  regiao: "Oak Ridge",
  tipo: "Conforto",
  acesso: "6650 S Semoran Blvd, Orlando, FL 32822",
  precoMedio: 27,
  destaque: "Comida caseira em porÃ§Ãµes generosas. Prato tÃ­pico: Country Fried Steak.",
  latitude: 28.4755,
  longitude: -81.3984,
},
{
  nome: "Greenbeat Oak Ridge",
  regiao: "Oak Ridge",
  tipo: "Saudavel",
  acesso: "2850 S Orange Ave, Orlando, FL 32806",
  precoMedio: 19,
  destaque: "Saladas frescas, bowls e wraps. Prato tÃ­pico: Mediterranean Bowl.",
  latitude: 28.4757,
  longitude: -81.3986,
},
{
  nome: "Taco Bell Oak Ridge",
  regiao: "Oak Ridge",
  tipo: "Economico",
  acesso: "3600 S Orange Blossom Trl, Orlando, FL 32839",
  precoMedio: 10,
  destaque: "Tex-Mex rÃ¡pido e acessÃ­vel. Prato tÃ­pico: Crunchwrap Supreme.",
  latitude: 28.4760,
  longitude: -81.3988,
},

// 24 - Maingate East
{
  nome: "Olive Garden Maingate East",
  regiao: "Maingate East",
  tipo: "Americano",
  acesso: "5021 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 30,
  destaque: "Italiano-americano clÃ¡ssico com massas e sopas ilimitadas. Prato tÃ­pico: Tour of Italy.",
  latitude: 28.3330,
  longitude: -81.4890,
},
{
  nome: "El Tenampa Mexican Restaurant",
  regiao: "Maingate East",
  tipo: "Tematico",
  acesso: "4565 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 25,
  destaque: "Mexicano autÃªntico e animado. Prato tÃ­pico: Tacos al Pastor.",
  latitude: 28.3332,
  longitude: -81.4892,
},
{
  nome: "Perkins Restaurant & Bakery Maingate",
  regiao: "Maingate East",
  tipo: "Conforto",
  acesso: "5410 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 27,
  destaque: "Rede americana com pratos caseiros e sobremesas. Prato tÃ­pico: Chicken Pot Pie.",
  latitude: 28.3334,
  longitude: -81.4894,
},
{
  nome: "Bolay Fresh Bold Kitchen",
  regiao: "Maingate East",
  tipo: "Saudavel",
  acesso: "1040 W Osceola Pkwy, Kissimmee, FL 34741",
  precoMedio: 21,
  destaque: "Bowls nutritivos montados ao gosto. Prato tÃ­pico: Havana Pulled Pork Bowl.",
  latitude: 28.3336,
  longitude: -81.4896,
},
{
  nome: "McDonald's Maingate East",
  regiao: "Maingate East",
  tipo: "Economico",
  acesso: "5711 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 9,
  destaque: "Rede 24h com opÃ§Ãµes rÃ¡pidas. Prato tÃ­pico: Big Mac.",
  latitude: 28.3338,
  longitude: -81.4898,
},

// 25 - Maingate West
{
  nome: "Cracker Barrel Maingate West",
  regiao: "Maingate West",
  tipo: "Americano",
  acesso: "5400 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 28,
  destaque: "Comida sulista clÃ¡ssica em ambiente rÃºstico. Prato tÃ­pico: Chicken nâ€™ Dumplins.",
  latitude: 28.3245,
  longitude: -81.5890,
},
{
  nome: "El Ranchito Mexican Grill",
  regiao: "Maingate West",
  tipo: "Tematico",
  acesso: "5820 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34746",
  precoMedio: 23,
  destaque: "Mexicano caseiro com ambiente familiar. Prato tÃ­pico: Enchiladas Rancheras.",
  latitude: 28.3247,
  longitude: -81.5892,
},
{
  nome: "Giordanoâ€™s Maingate",
  regiao: "Maingate West",
  tipo: "Conforto",
  acesso: "12151 S Apopka Vineland Rd, Lake Buena Vista, FL 32836",
  precoMedio: 33,
  destaque: "Pizza deep-dish estilo Chicago. Prato tÃ­pico: Deep Dish Stuffed Pizza.",
  latitude: 28.3249,
  longitude: -81.5894,
},
{
  nome: "Panera Bread Maingate",
  regiao: "Maingate West",
  tipo: "Saudavel",
  acesso: "2415 Sand Mine Rd, Davenport, FL 33897",
  precoMedio: 22,
  destaque: "Saladas, sopas e sanduÃ­ches frescos. Prato tÃ­pico: Fuji Apple Chicken Salad.",
  latitude: 28.3251,
  longitude: -81.5896,
},
{
  nome: "Wendyâ€™s Maingate West",
  regiao: "Maingate West",
  tipo: "Economico",
  acesso: "7780 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34747",
  precoMedio: 10,
  destaque: "Fast-food clÃ¡ssico americano. Prato tÃ­pico: Daveâ€™s Single.",
  latitude: 28.3253,
  longitude: -81.5898,
},

// 26 - Bonnet Creek
{
  nome: "Bull & Bear",
  regiao: "Bonnet Creek",
  tipo: "Americano",
  acesso: "14200 Bonnet Creek Resort Ln, Orlando, FL 32821",
  precoMedio: 65,
  destaque: "Steakhouse sofisticado com cortes nobres e vinhos finos. Prato tÃ­pico: Tomahawk Ribeye.",
  latitude: 28.3657,
  longitude: -81.5351,
},
{
  nome: "La Luce",
  regiao: "Bonnet Creek",
  tipo: "Tematico",
  acesso: "14100 Bonnet Creek Resort Ln, Orlando, FL 32821",
  precoMedio: 55,
  destaque: "Italiano elegante com massas artesanais. Prato tÃ­pico: Lasagna Napoletana.",
  latitude: 28.3648,
  longitude: -81.5342,
},
{
  nome: "Harvest Bistro",
  regiao: "Bonnet Creek",
  tipo: "Conforto",
  acesso: "14100 Bonnet Creek Resort Ln, Orlando, FL 32821",
  precoMedio: 38,
  destaque: "CulinÃ¡ria americana casual em ambiente familiar. Prato tÃ­pico: Angus Burger com fritas.",
  latitude: 28.3651,
  longitude: -81.5339,
},
{
  nome: "Zeta Asia",
  regiao: "Bonnet Creek",
  tipo: "Saudavel",
  acesso: "14100 Bonnet Creek Resort Ln, Orlando, FL 32821",
  precoMedio: 44,
  destaque: "AsiÃ¡tico moderno com sushi e pratos leves. Prato tÃ­pico: Sushi Roll Rainbow.",
  latitude: 28.3654,
  longitude: -81.5344,
},
{
  nome: "Subway Bonnet Creek",
  regiao: "Bonnet Creek",
  tipo: "Economico",
  acesso: "14100 Bonnet Creek Resort Ln, Orlando, FL 32821",
  precoMedio: 11,
  destaque: "SanduÃ­ches rÃ¡pidos e customizÃ¡veis. Prato tÃ­pico: Italian B.M.T.",
  latitude: 28.3649,
  longitude: -81.5337,
},

// 28 - Flamingo Crossings
{
  nome: "PDQ Flamingo Crossings",
  regiao: "Flamingo Crossings",
  tipo: "Americano",
  acesso: "1531 Flamingo Crossings Blvd, Winter Garden, FL 34787",
  precoMedio: 20,
  destaque: "Frango fresco e batatas rÃºsticas em ambiente casual. Prato tÃ­pico: Chicken Tenders.",
  latitude: 28.3702,
  longitude: -81.6264,
},
{
  nome: "Antojitos Flamingo Crossings",
  regiao: "Flamingo Crossings",
  tipo: "Tematico",
  acesso: "1421 Flamingo Crossings Blvd, Winter Garden, FL 34787",
  precoMedio: 28,
  destaque: "Mexicano vibrante com tacos e margaritas. Prato tÃ­pico: Tacos de Carnitas.",
  latitude: 28.3708,
  longitude: -81.6260,
},
{
  nome: "Five Guys Flamingo",
  regiao: "Flamingo Crossings",
  tipo: "Conforto",
  acesso: "1415 Flamingo Crossings Blvd, Winter Garden, FL 34787",
  precoMedio: 22,
  destaque: "HambÃºrgueres artesanais e batatas generosas. Prato tÃ­pico: Bacon Cheeseburger.",
  latitude: 28.3710,
  longitude: -81.6259,
},
{
  nome: "The Salad Station",
  regiao: "Flamingo Crossings",
  tipo: "Saudavel",
  acesso: "1429 Flamingo Crossings Blvd, Winter Garden, FL 34787",
  precoMedio: 17,
  destaque: "Monte sua salada ou bowl com ingredientes frescos. Prato tÃ­pico: Caesar Salad.",
  latitude: 28.3705,
  longitude: -81.6263,
},
{
  nome: "Little Caesars Flamingo",
  regiao: "Flamingo Crossings",
  tipo: "Economico",
  acesso: "1431 Flamingo Crossings Blvd, Winter Garden, FL 34787",
  precoMedio: 9,
  destaque: "Rede popular de pizzas econÃ´micas. Prato tÃ­pico: Hot-N-Ready Pepperoni Pizza.",
  latitude: 28.3706,
  longitude: -81.6261,
},

// 29 - MetroWest
{
  nome: "Teak Neighborhood Grill",
  regiao: "MetroWest",
  tipo: "Americano",
  acesso: "6400 Time Square Ave, Orlando, FL 32835",
  precoMedio: 33,
  destaque: "HambÃºrgueres premiados e grelhados especiais. Prato tÃ­pico: Drunken Monk Burger.",
  latitude: 28.5153,
  longitude: -81.4579,
},
{
  nome: "Chili's MetroWest",
  regiao: "MetroWest",
  tipo: "Tematico",
  acesso: "7341 W Colonial Dr, Orlando, FL 32818",
  precoMedio: 25,
  destaque: "Tex-Mex descontraÃ­do e porÃ§Ãµes generosas. Prato tÃ­pico: Baby Back Ribs.",
  latitude: 28.5145,
  longitude: -81.4573,
},
{
  nome: "Applebee's MetroWest",
  regiao: "MetroWest",
  tipo: "Conforto",
  acesso: "11030 W Colonial Dr, Ocoee, FL 34761",
  precoMedio: 26,
  destaque: "ClÃ¡ssicos americanos em ambiente casual. Prato tÃ­pico: Bourbon Street Chicken & Shrimp.",
  latitude: 28.5148,
  longitude: -81.4571,
},
{
  nome: "Bolay MetroWest",
  regiao: "MetroWest",
  tipo: "Saudavel",
  acesso: "2564 S Kirkman Rd, Orlando, FL 32811",
  precoMedio: 20,
  destaque: "Bowls nutritivos com superalimentos. Prato tÃ­pico: Baja Lemon Chicken Bowl.",
  latitude: 28.5151,
  longitude: -81.4575,
},
{
  nome: "Taco Bell MetroWest",
  regiao: "MetroWest",
  tipo: "Economico",
  acesso: "6250 W Colonial Dr, Orlando, FL 32818",
  precoMedio: 9,
  destaque: "Tex-Mex rÃ¡pido e econÃ´mico. Prato tÃ­pico: Crunchwrap Supreme.",
  latitude: 28.5147,
  longitude: -81.4570,
},

// 30 - Winter Park
{
  nome: "The Ravenous Pig",
  regiao: "Winter Park",
  tipo: "Americano",
  acesso: "565 W Fairbanks Ave, Winter Park, FL 32789",
  precoMedio: 45,
  destaque: "Gastrobar sofisticado com pratos sazonais. Prato tÃ­pico: Pork Belly com grits.",
  latitude: 28.5995,
  longitude: -81.3616,
},
{
  nome: "Bulla Gastrobar",
  regiao: "Winter Park",
  tipo: "Tematico",
  acesso: "110 S Orlando Ave #7, Winter Park, FL 32789",
  precoMedio: 42,
  destaque: "Espanhol contemporÃ¢neo com tapas e vinhos. Prato tÃ­pico: Huevos Bulla.",
  latitude: 28.6002,
  longitude: -81.3609,
},
{
  nome: "Hillstone Restaurant",
  regiao: "Winter Park",
  tipo: "Conforto",
  acesso: "215 S Orlando Ave, Winter Park, FL 32789",
  precoMedio: 48,
  destaque: "ClÃ¡ssicos americanos com vista para o lago. Prato tÃ­pico: Prime Rib com baked potato.",
  latitude: 28.6023,
  longitude: -81.3605,
},
{
  nome: "First Watch â€“ Winter Park",
  regiao: "Winter Park",
  tipo: "Saudavel",
  acesso: "140 N Orlando Ave Ste 100, Winter Park, FL 32789",
  precoMedio: 19,
  destaque: "Pratos leves, bowls e sucos naturais (atÃ© meio da tarde). Prato tÃ­pico: AÃ§aÃ­ Bowl.",
  latitude: 28.6015,
  longitude: -81.3612,
},
{
  nome: "BurgerFi Winter Park",
  regiao: "Winter Park",
  tipo: "Economico",
  acesso: "490 N Orlando Ave #118, Winter Park, FL 32789",
  precoMedio: 13,
  destaque: "HambÃºrgueres rÃ¡pidos com ingredientes de qualidade. Prato tÃ­pico: BurgerFi Cheeseburger.",
  latitude: 28.6017,
  longitude: -81.3610,
},

// 31 - Osceola Parkway
{
  nome: "Olive Garden Osceola",
  regiao: "Osceola Parkway",
  tipo: "Americano",
  acesso: "3210 Rolling Oaks Blvd, Kissimmee, FL 34747",
  precoMedio: 28,
  destaque: "Italiano-americano com porÃ§Ãµes generosas. Prato tÃ­pico: Fettuccine Alfredo.",
  latitude: 28.3422,
  longitude: -81.4829,
},
{
  nome: "T-Rex Cafe",
  regiao: "Osceola Parkway",
  tipo: "Tematico",
  acesso: "1676 E Buena Vista Dr, Lake Buena Vista, FL 32830",
  precoMedio: 42,
  destaque: "Ambiente jurÃ¡ssico e menu variado. Prato tÃ­pico: Boneyard Burger.",
  latitude: 28.3708,
  longitude: -81.5163,
},
{
  nome: "Cheddarâ€™s Scratch Kitchen",
  regiao: "Osceola Parkway",
  tipo: "Conforto",
  acesso: "16455 W Irlo Bronson Memorial Hwy, Kissimmee, FL 34714",
  precoMedio: 24,
  destaque: "Comfort food feita do zero. Prato tÃ­pico: Country Fried Steak.",
  latitude: 28.3426,
  longitude: -81.4831,
},
{
  nome: "Panera Bread â€“ The Loop",
  regiao: "Osceola Parkway",
  tipo: "Saudavel",
  acesso: "2705 W Osceola Pkwy, Kissimmee, FL 34741",
  precoMedio: 20,
  destaque: "Saladas, sopas e sanduÃ­ches leves. Prato tÃ­pico: Fuji Apple Chicken Salad.",
  latitude: 28.3419,
  longitude: -81.4834,
},
{
  nome: "Taco Bell Osceola",
  regiao: "Osceola Parkway",
  tipo: "Economico",
  acesso: "3251 Vineland Rd, Kissimmee, FL 34746",
  precoMedio: 8,
  destaque: "Tex-mex rÃ¡pido e acessÃ­vel. Prato tÃ­pico: Crunchwrap Supreme.",
  latitude: 28.3416,
  longitude: -81.4832,
},

// 32 - Millenia Area
{
  nome: "Earls Kitchen + Bar",
  regiao: "Millenia Area",
  tipo: "Americano",
  acesso: "4200 Conroy Rd, Suite H246, Orlando, FL 32839",
  precoMedio: 40,
  destaque: "Casual sofisticado com toques internacionais. Prato tÃ­pico: Cajun Chicken.",
  latitude: 28.4843,
  longitude: -81.4312,
},
{
  nome: "P.F. Changâ€™s",
  regiao: "Millenia Area",
  tipo: "Tematico",
  acesso: "4200 Conroy Rd, Orlando, FL 32839",
  precoMedio: 38,
  destaque: "AsiÃ¡tico moderno em ambiente elegante. Prato tÃ­pico: Chicken Lettuce Wraps.",
  latitude: 28.4839,
  longitude: -81.4308,
},
{
  nome: "The Cheesecake Factory â€“ Millenia",
  regiao: "Millenia Area",
  tipo: "Conforto",
  acesso: "4200 Conroy Rd, Orlando, FL 32839",
  precoMedio: 36,
  destaque: "Menu extenso e sobremesas icÃ´nicas. Prato tÃ­pico: Chicken Madeira.",
  latitude: 28.4845,
  longitude: -81.4317,
},
{
  nome: "Panera Bread â€“ Millenia Plaza",
  regiao: "Millenia Area",
  tipo: "Saudavel",
  acesso: "4200 S Orange Blossom Trl (prÃ³x. Conroy Rd), Orlando, FL",
  precoMedio: 19,
  destaque: "Sopas, saladas e bowls equilibrados. Prato tÃ­pico: Green Goddess Cobb.",
  latitude: 28.4837,
  longitude: -81.4309,
},
{
  nome: "Chick-fil-A Millenia",
  regiao: "Millenia Area",
  tipo: "Economico",
  acesso: "4698 Gardens Park Blvd, Orlando, FL 32839",
  precoMedio: 10,
  destaque: "Frango crocante e serviÃ§o Ã¡gil. Prato tÃ­pico: Chicken Sandwich.",
  latitude: 28.4840,
  longitude: -81.4310,
},

// 33 - Southchase
{
  nome: "Outback Steakhouse Southchase",
  regiao: "Southchase",
  tipo: "Americano",
  acesso: "11025 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 32,
  destaque: "Carnes grelhadas em clima descontraÃ­do. Prato tÃ­pico: Outback Special (Sirloin).",
  latitude: 28.3956,
  longitude: -81.4042,
},
{
  nome: "Bahama Breeze (Vineland)",
  regiao: "Southchase",
  tipo: "Tematico",
  acesso: "8735 Vineland Ave, Orlando, FL 32821",
  precoMedio: 34,
  destaque: "Sabores caribenhos e coquetÃ©is tropicais. Prato tÃ­pico: Jerk Chicken Pasta.",
  latitude: 28.3971,
  longitude: -81.4038,
},
{
  nome: "Red Lobster S OBT",
  regiao: "Southchase",
  tipo: "Conforto",
  acesso: "11500 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 35,
  destaque: "Frutos do mar clÃ¡ssicos. Prato tÃ­pico: Ultimate Feast.",
  latitude: 28.3967,
  longitude: -81.4040,
},
{
  nome: "Tropical Smoothie Cafe",
  regiao: "Southchase",
  tipo: "Saudavel",
  acesso: "12231 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 16,
  destaque: "Smoothies, wraps e bowls leves. Prato tÃ­pico: Island Green + Thai Chicken Wrap.",
  latitude: 28.3953,
  longitude: -81.4039,
},
{
  nome: "McDonald's Southchase",
  regiao: "Southchase",
  tipo: "Economico",
  acesso: "12035 S Orange Blossom Trl, Orlando, FL 32837",
  precoMedio: 7,
  destaque: "Fast food clÃ¡ssico. Prato tÃ­pico: Big Mac.",
  latitude: 28.3955,
  longitude: -81.4041,
},

// 34 - Baldwin Park
{
  nome: "The Osprey",
  regiao: "Baldwin Park",
  tipo: "Americano",
  acesso: "4899 New Broad St, Orlando, FL 32814",
  precoMedio: 45,
  destaque: "Moderno, focado em frutos do mar. Prato tÃ­pico: Cedar Plank Salmon.",
  latitude: 28.5681,
  longitude: -81.3274,
},
{
  nome: "Seito Sushi",
  regiao: "Baldwin Park",
  tipo: "Tematico",
  acesso: "4898 New Broad St, Orlando, FL 32814",
  precoMedio: 42,
  destaque: "Sushi contemporÃ¢neo e asiÃ¡ticos criativos. Prato tÃ­pico: Seito Sashimi Combo.",
  latitude: 28.5677,
  longitude: -81.3272,
},
{
  nome: "Gators Dockside â€“ Baldwin Park",
  regiao: "Baldwin Park",
  tipo: "Conforto",
  acesso: "4982 New Broad St, Orlando, FL 32814",
  precoMedio: 26,
  destaque: "Esportivo casual com porÃ§Ãµes fartas. Prato tÃ­pico: Buffalo Wings.",
  latitude: 28.5679,
  longitude: -81.3275,
},
{
  nome: "Green Kitchen",
  regiao: "Baldwin Park",
  tipo: "Saudavel",
  acesso: "4879 New Broad St, Orlando, FL 32814",
  precoMedio: 20,
  destaque: "OpÃ§Ãµes naturais, veganas e sem glÃºten. Prato tÃ­pico: Buddha Bowl.",
  latitude: 28.5680,
  longitude: -81.3273,
},
{
  nome: "Subway Baldwin Park",
  regiao: "Baldwin Park",
  tipo: "Economico",
  acesso: "4833 New Broad St, Orlando, FL 32814",
  precoMedio: 9,
  destaque: "SanduÃ­ches personalizÃ¡veis. Prato tÃ­pico: Italian B.M.T.",
  latitude: 28.5682,
  longitude: -81.3271,
},

// 35 - Sand Lake Road Area
{
  nome: "Ruthâ€™s Chris Steak House",
  regiao: "Sand Lake Road Area",
  tipo: "Americano",
  acesso: "7501 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 58,
  destaque: "Cortes nobres e manteiga clarificada na pedra quente. Prato tÃ­pico: Filet Mignon.",
  latitude: 28.4507,
  longitude: -81.4673,
},
{
  nome: "Benihana I-Drive",
  regiao: "Sand Lake Road Area",
  tipo: "Tematico",
  acesso: "12690 International Dr S, Orlando, FL 32821",
  precoMedio: 47,
  destaque: "Hibachi com show. Prato tÃ­pico: Hibachi Chicken & Shrimp.",
  latitude: 28.4512,
  longitude: -81.4678,
},
{
  nome: "Seasons 52",
  regiao: "Sand Lake Road Area",
  tipo: "Conforto",
  acesso: "7700 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 40,
  destaque: "Menu sazonal, grelha a lenha. Prato tÃ­pico: Cedar Plank-Roasted Salmon.",
  latitude: 28.4509,
  longitude: -81.4675,
},
{
  nome: "True Food Kitchen",
  regiao: "Sand Lake Road Area",
  tipo: "Saudavel",
  acesso: "7600 Dr Phillips Blvd Suite 158, Orlando, FL 32819",
  precoMedio: 28,
  destaque: "CulinÃ¡ria de bem-estar com ingredientes frescos. Prato tÃ­pico: Ancient Grains Bowl.",
  latitude: 28.4505,
  longitude: -81.4671,
},
{
  nome: "Wendyâ€™s Sand Lake",
  regiao: "Sand Lake Road Area",
  tipo: "Economico",
  acesso: "7701 W Sand Lake Rd, Orlando, FL 32819",
  precoMedio: 8,
  destaque: "ClÃ¡ssicos do fast food. Prato tÃ­pico: Baconator.",
  latitude: 28.4506,
  longitude: -81.4674,
},

// 36 - North Kissimmee
{
  nome: "Loganâ€™s Roadhouse",
  regiao: "North Kissimmee",
  tipo: "Americano",
  acesso: "819 W Vine St, Kissimmee, FL 34741",
  precoMedio: 30,
  destaque: "Steaks na brasa e pÃ£o quentinho. Prato tÃ­pico: USDA Sirloin.",
  latitude: 28.3047,
  longitude: -81.4123,
},
{
  nome: "El Tenampa",
  regiao: "North Kissimmee",
  tipo: "Tematico",
  acesso: "851 W Vine St, Kissimmee, FL 34741",
  precoMedio: 26,
  destaque: "Mexicano autÃªntico e farto. Prato tÃ­pico: Fajitas Mistas.",
  latitude: 28.3045,
  longitude: -81.4121,
},
{
  nome: "Cracker Barrel Old Country Store",
  regiao: "North Kissimmee",
  tipo: "Conforto",
  acesso: "2850 N John Young Pkwy, Kissimmee, FL 34741",
  precoMedio: 24,
  destaque: "Comida sulista e ambiente rÃºstico. Prato tÃ­pico: Chicken nâ€™ Dumplins.",
  latitude: 28.3046,
  longitude: -81.4122,
},
{
  nome: "Vitality Bowls",
  regiao: "North Kissimmee",
  tipo: "Saudavel",
  acesso: "2601 W Vine St, Kissimmee, FL 34741",
  precoMedio: 18,
  destaque: "AÃ§aÃ­ bowls e smoothies naturais. Prato tÃ­pico: Warrior Bowl.",
  latitude: 28.3048,
  longitude: -81.4124,
},
{
  nome: "Checkers Drive-In",
  regiao: "North Kissimmee",
  tipo: "Economico",
  acesso: "2610 W Vine St, Kissimmee, FL 34741",
  precoMedio: 7,
  destaque: "Lanches rÃ¡pidos e saborosos. Prato tÃ­pico: Big Buford.",
  latitude: 28.3049,
  longitude: -81.4120,
},

];

  
