export const Adventureland = {
  parque: "Magic Kingdom",
  descricao: "Área tropical e exótica com aventuras e shows temáticos. Combina selvas, piratas e cultura polinésia em atrações clássicas e experiências relaxantes.",
  imagem: "adventureland.png",
  latitude: 28.4187,
  longitude: -81.5830,
  atracoes: [
    {
      id: "jungle-cruise",
      titulo: "Jungle Cruise",
      subtitulo: "Adventureland",
      tipo: "Passeio de barco cômico",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio de barco por rios com cenários de selva, animais animatrônicos e piadas divertidas dos guias. Ideal para relaxar e se divertir sem sustos. Sente-se à esquerda para ótimas fotos e aproveite nos dias quentes.`,
      icone: "🛶",
      imagem: "jungle-cruise.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4183,
      longitude: -81.5825
    },
    {
      id: "pirates-of-the-caribbean",
      titulo: "Pirates of the Caribbean",
      subtitulo: "Adventureland",
      tipo: "Dark ride temática",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Barco por cidades invadidas por piratas animatrônicos com cenas detalhadas e efeitos clássicos. Pequena descida e respingos leves. Os melhores lugares são no meio do barco para ver tudo sem molhar.`,
      icone: "🏴‍☠️",
      imagem: "pirates-of-the-caribbean.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4175,
      longitude: -81.5842
    },
    {
      id: "magic-carpets-of-aladdin",
      titulo: "The Magic Carpets of Aladdin",
      subtitulo: "Adventureland",
      tipo: "Brinquedo giratório infantil",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Voe em um tapete mágico controlando a altura, com vista para Adventureland. Movimentos suaves e sem giros rápidos. Fique atento aos camelos dourados que espirram água e pilote alto para uma visão melhor.`,
      icone: "🕌",
      imagem: "magic-carpets-of-aladdin.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4180,
      longitude: -81.5831
    },
    {
      id: "enchanted-tiki-room",
      titulo: "Walt Disney’s Enchanted Tiki Room",
      subtitulo: "Adventureland",
      tipo: "Show animatrônico musical",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: `Show de aves animatrônicas com músicas alegres e ambiente tropical. Perfeito para descansar e se refrescar. Sente-se no fundo para ver todos os efeitos e aproveitar melhor o espetáculo.`,
      icone: "🐦",
      imagem: "enchanted-tiki-room.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4188,
      longitude: -81.5836
    },
    {
      id: "swiss-family-treehouse",
      titulo: "Swiss Family Treehouse",
      subtitulo: "Adventureland",
      tipo: "Exploração temática interativa",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Exploração da casa na árvore da família suíça, com vistas panorâmicas e detalhes encantadores. Suba no fim da tarde para fotos incríveis do parque.`,
      icone: "🌴",
      imagem: "swiss-family-treehouse.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4191,
      longitude: -81.5829
    }
  ]
};
