ï»¿export const Adventureland = {
  parque: "Magic Kingdom",
  descricao: "ÃƒÂrea tropical e exÃƒÂ³tica com aventuras e shows temÃƒÂ¡ticos. Combina selvas, piratas e cultura polinÃƒÂ©sia em atraÃƒÂ§ÃƒÂµes clÃƒÂ¡ssicas e experiÃƒÂªncias relaxantes.",
  imagem: "adventureland.png",
  latitude: 28.4187,
  longitude: -81.5830,
  atracoes: [
    {
      id: "jungle-cruise",
      titulo: "Jungle Cruise",
      subtitulo: "Adventureland",
      tipo: "Passeio de barco cÃƒÂ´mico",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio de barco por rios com cenÃƒÂ¡rios de selva, animais animatrÃƒÂ´nicos e piadas divertidas dos guias. Ideal para relaxar e se divertir sem sustos. Sente-se ÃƒÂ  esquerda para ÃƒÂ³timas fotos e aproveite nos dias quentes.`,
      icone: "Ã°Å¸â€ºÂ¶",
      imagem: "jungle-cruise.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4183,
      longitude: -81.5825
    },
    {
      id: "pirates-of-the-caribbean",
      titulo: "Pirates of the Caribbean",
      subtitulo: "Adventureland",
      tipo: "Dark ride temÃƒÂ¡tica",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Barco por cidades invadidas por piratas animatrÃƒÂ´nicos com cenas detalhadas e efeitos clÃƒÂ¡ssicos. Pequena descida e respingos leves. Os melhores lugares sÃƒÂ£o no meio do barco para ver tudo sem molhar.`,
      icone: "Ã°Å¸ÂÂ´Ã¢â‚¬ÂÃ¢ËœÂ Ã¯Â¸Â",
      imagem: "pirates-of-the-caribbean.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4175,
      longitude: -81.5842
    },
    {
      id: "magic-carpets-of-aladdin",
      titulo: "The Magic Carpets of Aladdin",
      subtitulo: "Adventureland",
      tipo: "Brinquedo giratÃƒÂ³rio infantil",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Voe em um tapete mÃƒÂ¡gico controlando a altura, com vista para Adventureland. Movimentos suaves e sem giros rÃƒÂ¡pidos. Fique atento aos camelos dourados que espirram ÃƒÂ¡gua e pilote alto para uma visÃƒÂ£o melhor.`,
      icone: "Ã°Å¸â€¢Å’",
      imagem: "magic-carpets-of-aladdin.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4180,
      longitude: -81.5831
    },
    {
      id: "enchanted-tiki-room",
      titulo: "Walt DisneyÃ¢â‚¬â„¢s Enchanted Tiki Room",
      subtitulo: "Adventureland",
      tipo: "Show animatrÃƒÂ´nico musical",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: `Show de aves animatrÃƒÂ´nicas com mÃƒÂºsicas alegres e ambiente tropical. Perfeito para descansar e se refrescar. Sente-se no fundo para ver todos os efeitos e aproveitar melhor o espetÃƒÂ¡culo.`,
      icone: "Ã°Å¸ÂÂ¦",
      imagem: "enchanted-tiki-room.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4188,
      longitude: -81.5836
    },
    {
      id: "swiss-family-treehouse",
      titulo: "Swiss Family Treehouse",
      subtitulo: "Adventureland",
      tipo: "ExploraÃƒÂ§ÃƒÂ£o temÃƒÂ¡tica interativa",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `ExploraÃƒÂ§ÃƒÂ£o da casa na ÃƒÂ¡rvore da famÃƒÂ­lia suÃƒÂ­ÃƒÂ§a, com vistas panorÃƒÂ¢micas e detalhes encantadores. Suba no fim da tarde para fotos incrÃƒÂ­veis do parque.`,
      icone: "Ã°Å¸Å’Â´",
      imagem: "swiss-family-treehouse.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4191,
      longitude: -81.5829
    }
  ]
};
