export const Adventureland = {
  parque: "Magic Kingdom",
  descricao: "Ãrea tropical e exÃ³tica com aventuras e shows temÃ¡ticos. Combina selvas, piratas e cultura polinÃ©sia em atraÃ§Ãµes clÃ¡ssicas e experiÃªncias relaxantes.",
  imagem: "adventureland.png",
  latitude: 28.4187,
  longitude: -81.5830,
  atracoes: [
    {
      id: "jungle-cruise",
      titulo: "Jungle Cruise",
      subtitulo: "Adventureland",
      tipo: "Passeio de barco cÃ´mico",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio de barco por rios com cenÃ¡rios de selva, animais animatrÃ´nicos e piadas divertidas dos guias. Ideal para relaxar e se divertir sem sustos. Sente-se Ã  esquerda para Ã³timas fotos e aproveite nos dias quentes.`,
      icone: "ðŸ›¶",
      imagem: "jungle-cruise.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4183,
      longitude: -81.5825
    },
    {
      id: "pirates-of-the-caribbean",
      titulo: "Pirates of the Caribbean",
      subtitulo: "Adventureland",
      tipo: "Dark ride temÃ¡tica",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Barco por cidades invadidas por piratas animatrÃ´nicos com cenas detalhadas e efeitos clÃ¡ssicos. Pequena descida e respingos leves. Os melhores lugares sÃ£o no meio do barco para ver tudo sem molhar.`,
      icone: "ðŸ´â€â˜ ï¸",
      imagem: "pirates-of-the-caribbean.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4175,
      longitude: -81.5842
    },
    {
      id: "magic-carpets-of-aladdin",
      titulo: "The Magic Carpets of Aladdin",
      subtitulo: "Adventureland",
      tipo: "Brinquedo giratÃ³rio infantil",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Voe em um tapete mÃ¡gico controlando a altura, com vista para Adventureland. Movimentos suaves e sem giros rÃ¡pidos. Fique atento aos camelos dourados que espirram Ã¡gua e pilote alto para uma visÃ£o melhor.`,
      icone: "ðŸ•Œ",
      imagem: "magic-carpets-of-aladdin.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4180,
      longitude: -81.5831
    },
    {
      id: "enchanted-tiki-room",
      titulo: "Walt Disneyâ€™s Enchanted Tiki Room",
      subtitulo: "Adventureland",
      tipo: "Show animatrÃ´nico musical",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: `Show de aves animatrÃ´nicas com mÃºsicas alegres e ambiente tropical. Perfeito para descansar e se refrescar. Sente-se no fundo para ver todos os efeitos e aproveitar melhor o espetÃ¡culo.`,
      icone: "ðŸ¦",
      imagem: "enchanted-tiki-room.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4188,
      longitude: -81.5836
    },
    {
      id: "swiss-family-treehouse",
      titulo: "Swiss Family Treehouse",
      subtitulo: "Adventureland",
      tipo: "ExploraÃ§Ã£o temÃ¡tica interativa",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `ExploraÃ§Ã£o da casa na Ã¡rvore da famÃ­lia suÃ­Ã§a, com vistas panorÃ¢micas e detalhes encantadores. Suba no fim da tarde para fotos incrÃ­veis do parque.`,
      icone: "ðŸŒ´",
      imagem: "swiss-family-treehouse.jpg",
      regiao: "Adventureland",
      parque: "Magic Kingdom",
      latitude: 28.4191,
      longitude: -81.5829
    }
  ]
};
