ï»¿export const Africa = {
  parque: "Animal Kingdom",
  descricao: "Inspirada na vila fictÃƒÂ­cia de Harambe, mistura cultura africana, mÃƒÂºsica, gastronomia e experiÃƒÂªncias imersivas, incluindo um safÃƒÂ¡ri realista com animais em ambientes naturais.",
  imagem: "africa.png",
  latitude: 28.3585,
  longitude: -81.5970,
  atracoes: [
    {
      id: "kilimanjaro-safaris",
      titulo: "Kilimanjaro Safaris",
      subtitulo: "Africa",
      tipo: "SafÃƒÂ¡ri ao ar livre",
      tipoPerfil:["familiares", "radicais", "tematicas", "imersivas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Passeio em veÃƒÂ­culo aberto por savanas com girafas, leÃƒÂµes, elefantes e outros animais. Trilha tranquila, mas pode balanÃƒÂ§ar um pouco. Sente-se ÃƒÂ  esquerda para ver melhor e vÃƒÂ¡ cedo para encontrar mais bichos.`,
      icone: "Ã°Å¸Â¦â€™",
      imagem: "kilimanjaro-safaris.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3588,
      longitude: -81.5965
    },
    {
      id: "festival-of-the-lion-king",
      titulo: "Festival of the Lion King",
      subtitulo: "Africa",
      tipo: "Show musical ao vivo",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `EspetÃƒÂ¡culo vibrante com mÃƒÂºsicas, acrobacias e personagens do Rei LeÃƒÂ£o. Colorido e emocionante, agrada todas as idades. Sente-se no centro para ver melhor e chegue cedo para bons lugares.`,
      icone: "Ã°Å¸Â¦Â",
      imagem: "festival-of-the-lion-king.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3580,
      longitude: -81.5971
    },
    {
      id: "gorilla-falls-exploration-trail",
      titulo: "Gorilla Falls Exploration Trail",
      subtitulo: "Africa",
      tipo: "Trilha de observaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["familiares", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Caminhada leve por ÃƒÂ¡reas naturais com gorilas, hipopÃƒÂ³tamos e aves. Ambiente sombreado e ideal para fotos. Os melhores cliques dos animais acontecem no meio do percurso.`,
      icone: "Ã°Å¸Â¦Â",
      imagem: "gorilla-falls.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3591,
      longitude: -81.5959
    },
    {
      id: "harambe-market",
      titulo: "Harambe Market",
      subtitulo: "Africa",
      tipo: "EspaÃƒÂ§o temÃƒÂ¡tico e gastronÃƒÂ´mico",
      tipoPerfil: ["tematicas", "interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Mercado ao ar livre com pratos tÃƒÂ­picos africanos, lojas e decoraÃƒÂ§ÃƒÂ£o autÃƒÂªntica. Ãƒâ€œtimo para pausar e experimentar sabores. Tire fotos nas paredes grafitadas e fique atento a apresentaÃƒÂ§ÃƒÂµes culturais.`,
      icone: "Ã°Å¸â€ºÂÃ¯Â¸Â",
      imagem: "harambe-market.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3576,
      longitude: -81.5962
    },
    {
      id: "tam-tam-drummers",
      titulo: "Tam Tam Drummers of Harambe",
      subtitulo: "Africa",
      tipo: "Show de mÃƒÂºsica africana",
      tipoPerfil: ["tematicas", "interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `ApresentaÃƒÂ§ÃƒÂ£o animada de tambores africanos com danÃƒÂ§a e interaÃƒÂ§ÃƒÂ£o com o pÃƒÂºblico. Clima de festa e energia contagiante. Participe das danÃƒÂ§as e experimente os instrumentos no final.`,
      icone: "Ã°Å¸Â¥Â",
      imagem: "tam-tam-drummers.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3579,
      longitude: -81.5978
    }
  ]
};
