export const Africa = {
  parque: "Animal Kingdom",
  descricao: "Inspirada na vila fictícia de Harambe, mistura cultura africana, música, gastronomia e experiências imersivas, incluindo um safári realista com animais em ambientes naturais.",
  imagem: "africa.png",
  latitude: 28.3585,
  longitude: -81.5970,
  atracoes: [
    {
      id: "kilimanjaro-safaris",
      titulo: "Kilimanjaro Safaris",
      subtitulo: "Africa",
      tipo: "Safári ao ar livre",
      tipoPerfil:["familiares", "radicais", "tematicas", "imersivas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Passeio em veículo aberto por savanas com girafas, leões, elefantes e outros animais. Trilha tranquila, mas pode balançar um pouco. Sente-se à esquerda para ver melhor e vá cedo para encontrar mais bichos.`,
      icone: "🦒",
      imagem: "kilimanjaro-safaris.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3588,
      longitude: -81.5965
    },
    {
      id: "festival-of-the-lion-king",
      titulo: "Festival of the Lion King",
      subtitulo: "Africa",
      tipo: "Show musical ao vivo",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Espetáculo vibrante com músicas, acrobacias e personagens do Rei Leão. Colorido e emocionante, agrada todas as idades. Sente-se no centro para ver melhor e chegue cedo para bons lugares.`,
      icone: "🦁",
      imagem: "festival-of-the-lion-king.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3580,
      longitude: -81.5971
    },
    {
      id: "gorilla-falls-exploration-trail",
      titulo: "Gorilla Falls Exploration Trail",
      subtitulo: "Africa",
      tipo: "Trilha de observação",
      tipoPerfil: ["familiares", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Caminhada leve por áreas naturais com gorilas, hipopótamos e aves. Ambiente sombreado e ideal para fotos. Os melhores cliques dos animais acontecem no meio do percurso.`,
      icone: "🦍",
      imagem: "gorilla-falls.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3591,
      longitude: -81.5959
    },
    {
      id: "harambe-market",
      titulo: "Harambe Market",
      subtitulo: "Africa",
      tipo: "Espaço temático e gastronômico",
      tipoPerfil: ["tematicas", "interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Mercado ao ar livre com pratos típicos africanos, lojas e decoração autêntica. Ótimo para pausar e experimentar sabores. Tire fotos nas paredes grafitadas e fique atento a apresentações culturais.`,
      icone: "🛍️",
      imagem: "harambe-market.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3576,
      longitude: -81.5962
    },
    {
      id: "tam-tam-drummers",
      titulo: "Tam Tam Drummers of Harambe",
      subtitulo: "Africa",
      tipo: "Show de música africana",
      tipoPerfil: ["tematicas", "interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Apresentação animada de tambores africanos com dança e interação com o público. Clima de festa e energia contagiante. Participe das danças e experimente os instrumentos no final.`,
      icone: "🥁",
      imagem: "tam-tam-drummers.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3579,
      longitude: -81.5978
    }
  ]
};
