export const Africa = {
  parque: "Animal Kingdom",
  descricao: "Inspirada na vila fictÃ­cia de Harambe, mistura cultura africana, mÃºsica, gastronomia e experiÃªncias imersivas, incluindo um safÃ¡ri realista com animais em ambientes naturais.",
  imagem: "africa.png",
  latitude: 28.3585,
  longitude: -81.5970,
  atracoes: [
    {
      id: "kilimanjaro-safaris",
      titulo: "Kilimanjaro Safaris",
      subtitulo: "Africa",
      tipo: "SafÃ¡ri ao ar livre",
      tipoPerfil:["familiares", "radicais", "tematicas", "imersivas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Passeio em veÃ­culo aberto por savanas com girafas, leÃµes, elefantes e outros animais. Trilha tranquila, mas pode balanÃ§ar um pouco. Sente-se Ã  esquerda para ver melhor e vÃ¡ cedo para encontrar mais bichos.`,
      icone: "ðŸ¦’",
      imagem: "kilimanjaro-safaris.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3588,
      longitude: -81.5965
    },
    {
      id: "festival-of-the-lion-king",
      titulo: "Festival of the Lion King",
      subtitulo: "Africa",
      tipo: "Show musical ao vivo",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `EspetÃ¡culo vibrante com mÃºsicas, acrobacias e personagens do Rei LeÃ£o. Colorido e emocionante, agrada todas as idades. Sente-se no centro para ver melhor e chegue cedo para bons lugares.`,
      icone: "ðŸ¦",
      imagem: "festival-of-the-lion-king.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3580,
      longitude: -81.5971
    },
    {
      id: "gorilla-falls-exploration-trail",
      titulo: "Gorilla Falls Exploration Trail",
      subtitulo: "Africa",
      tipo: "Trilha de observaÃ§Ã£o",
      tipoPerfil: ["familiares", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Caminhada leve por Ã¡reas naturais com gorilas, hipopÃ³tamos e aves. Ambiente sombreado e ideal para fotos. Os melhores cliques dos animais acontecem no meio do percurso.`,
      icone: "ðŸ¦",
      imagem: "gorilla-falls.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3591,
      longitude: -81.5959
    },
    {
      id: "harambe-market",
      titulo: "Harambe Market",
      subtitulo: "Africa",
      tipo: "EspaÃ§o temÃ¡tico e gastronÃ´mico",
      tipoPerfil: ["tematicas", "interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Mercado ao ar livre com pratos tÃ­picos africanos, lojas e decoraÃ§Ã£o autÃªntica. Ã“timo para pausar e experimentar sabores. Tire fotos nas paredes grafitadas e fique atento a apresentaÃ§Ãµes culturais.`,
      icone: "ðŸ›ï¸",
      imagem: "harambe-market.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3576,
      longitude: -81.5962
    },
    {
      id: "tam-tam-drummers",
      titulo: "Tam Tam Drummers of Harambe",
      subtitulo: "Africa",
      tipo: "Show de mÃºsica africana",
      tipoPerfil: ["tematicas", "interativas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `ApresentaÃ§Ã£o animada de tambores africanos com danÃ§a e interaÃ§Ã£o com o pÃºblico. Clima de festa e energia contagiante. Participe das danÃ§as e experimente os instrumentos no final.`,
      icone: "ðŸ¥",
      imagem: "tam-tam-drummers.jpg",
      regiao: "Africa",
      parque: "Animal Kingdom",
      latitude: 28.3579,
      longitude: -81.5978
    }
  ]
};
