export const AnimationCourtyard = {
  parque: "Hollywood Studios",
  descricao: "Ãrea dedicada aos clÃ¡ssicos da animaÃ§Ã£o Disney, com atraÃ§Ãµes interativas, encontros com personagens e shows para todas as idades.",
  imagem: "animationcourtyard.png",
  latitude: 28.3563,
  longitude: -81.5606,
  atracoes: [
    {
      id: "disney-junior-dance",
      titulo: "Disney Junior Dance Party!",
      subtitulo: "Animation Courtyard",
      tipo: "Show musical interativo",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "PrÃ©-escolares e crianÃ§as pequenas",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Show animado com Mickey, Vampirina e Timon, onde crianÃ§as danÃ§am e interagem com os personagens. Fique nas primeiras fileiras para aumentar as chances de serem chamadas ao palco.`,
      icone: "ðŸ•º",
      imagem: "disney-junior.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3567,
      longitude: -81.5611
    },
    {
      id: "voyage-little-mermaid",
      titulo: "Voyage of The Little Mermaid",
      subtitulo: "Animation Courtyard",
      tipo: "Show ao vivo com efeitos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Musical de Ariel com fantoches, projeÃ§Ãµes, mÃºsicas e efeitos de Ã¡gua. Encanta todas as idades. Sente-se no meio para melhor visÃ£o e evite as primeiras filas se nÃ£o gosta de respingos.`,
      icone: "ðŸ§œâ€â™€ï¸",
      imagem: "little-mermaid.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3561,
      longitude: -81.5605
    },
    {
      id: "walt-disney-presents",
      titulo: "Walt Disney Presents",
      subtitulo: "Animation Courtyard",
      tipo: "ExposiÃ§Ã£o interativa e filme",
      tipoPerfil: ["imersivas", "tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `ExposiÃ§Ã£o sobre a vida e obras de Walt Disney, com maquetes, objetos histÃ³ricos e um filme inspirador. Explore tudo antes do filme, pois as luzes se apagam durante a exibiÃ§Ã£o.`,
      icone: "ðŸŽžï¸",
      imagem: "walt-disney-presents.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3564,
      longitude: -81.5602
    },
    {
      id: "star-wars-launch-bay",
      titulo: "Star Wars Launch Bay",
      subtitulo: "Animation Courtyard",
      tipo: "ExposiÃ§Ã£o e encontros com personagens",
      tipoPerfil: ["interativas", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "noite",
      descricao: `Encontros com Chewbacca, Darth Vader e BB-8, alÃ©m de figurinos e adereÃ§os originais de Star Wars. Leve cÃ¢mera para registrar as interaÃ§Ãµes e os cenÃ¡rios.`,
      icone: "ðŸš€",
      imagem: "star-wars-launch-bay.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3560,
      longitude: -81.5608
    },
    {
      id: "animation-photo-spot",
      titulo: "Animation Courtyard Photo Spot",
      subtitulo: "Animation Courtyard",
      tipo: "Ponto de fotos com personagens",
      tipoPerfil: ["tematicas", "familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `CenÃ¡rios temÃ¡ticos para fotos com Pluto, Fancy Nancy e Doc McStuffins. Leve algo para autÃ³grafos, pois os personagens assinam e interagem bastante.`,
      icone: "ðŸ“¸",
      imagem: "animation-photo.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3565,
      longitude: -81.5609
    }
  ]
};
