ï»¿export const AnimationCourtyard = {
  parque: "Hollywood Studios",
  descricao: "ÃƒÂrea dedicada aos clÃƒÂ¡ssicos da animaÃƒÂ§ÃƒÂ£o Disney, com atraÃƒÂ§ÃƒÂµes interativas, encontros com personagens e shows para todas as idades.",
  imagem: "animationcourtyard.png",
  latitude: 28.3563,
  longitude: -81.5606,
  atracoes: [
    {
      id: "disney-junior-dance",
      titulo: "Disney Junior Dance Party!",
      subtitulo: "Animation Courtyard",
      tipo: "Show musical interativo",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "PrÃƒÂ©-escolares e crianÃƒÂ§as pequenas",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Show animado com Mickey, Vampirina e Timon, onde crianÃƒÂ§as danÃƒÂ§am e interagem com os personagens. Fique nas primeiras fileiras para aumentar as chances de serem chamadas ao palco.`,
      icone: "Ã°Å¸â€¢Âº",
      imagem: "disney-junior.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3567,
      longitude: -81.5611
    },
    {
      id: "voyage-little-mermaid",
      titulo: "Voyage of The Little Mermaid",
      subtitulo: "Animation Courtyard",
      tipo: "Show ao vivo com efeitos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Musical de Ariel com fantoches, projeÃƒÂ§ÃƒÂµes, mÃƒÂºsicas e efeitos de ÃƒÂ¡gua. Encanta todas as idades. Sente-se no meio para melhor visÃƒÂ£o e evite as primeiras filas se nÃƒÂ£o gosta de respingos.`,
      icone: "Ã°Å¸Â§Å“Ã¢â‚¬ÂÃ¢â„¢â‚¬Ã¯Â¸Â",
      imagem: "little-mermaid.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3561,
      longitude: -81.5605
    },
    {
      id: "walt-disney-presents",
      titulo: "Walt Disney Presents",
      subtitulo: "Animation Courtyard",
      tipo: "ExposiÃƒÂ§ÃƒÂ£o interativa e filme",
      tipoPerfil: ["imersivas", "tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `ExposiÃƒÂ§ÃƒÂ£o sobre a vida e obras de Walt Disney, com maquetes, objetos histÃƒÂ³ricos e um filme inspirador. Explore tudo antes do filme, pois as luzes se apagam durante a exibiÃƒÂ§ÃƒÂ£o.`,
      icone: "Ã°Å¸Å½Å¾Ã¯Â¸Â",
      imagem: "walt-disney-presents.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3564,
      longitude: -81.5602
    },
    {
      id: "star-wars-launch-bay",
      titulo: "Star Wars Launch Bay",
      subtitulo: "Animation Courtyard",
      tipo: "ExposiÃƒÂ§ÃƒÂ£o e encontros com personagens",
      tipoPerfil: ["interativas", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "noite",
      descricao: `Encontros com Chewbacca, Darth Vader e BB-8, alÃƒÂ©m de figurinos e adereÃƒÂ§os originais de Star Wars. Leve cÃƒÂ¢mera para registrar as interaÃƒÂ§ÃƒÂµes e os cenÃƒÂ¡rios.`,
      icone: "Ã°Å¸Å¡â‚¬",
      imagem: "star-wars-launch-bay.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3560,
      longitude: -81.5608
    },
    {
      id: "animation-photo-spot",
      titulo: "Animation Courtyard Photo Spot",
      subtitulo: "Animation Courtyard",
      tipo: "Ponto de fotos com personagens",
      tipoPerfil: ["tematicas", "familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `CenÃƒÂ¡rios temÃƒÂ¡ticos para fotos com Pluto, Fancy Nancy e Doc McStuffins. Leve algo para autÃƒÂ³grafos, pois os personagens assinam e interagem bastante.`,
      icone: "Ã°Å¸â€œÂ¸",
      imagem: "animation-photo.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3565,
      longitude: -81.5609
    }
  ]
};
