export const AnimationCourtyard = {
  parque: "Hollywood Studios",
  descricao: "Área dedicada aos clássicos da animação Disney, com atrações interativas, encontros com personagens e shows para todas as idades.",
  imagem: "animationcourtyard.png",
  latitude: 28.3563,
  longitude: -81.5606,
  atracoes: [
    {
      id: "disney-junior-dance",
      titulo: "Disney Junior Dance Party!",
      subtitulo: "Animation Courtyard",
      tipo: "Show musical interativo",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Pré-escolares e crianças pequenas",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Show animado com Mickey, Vampirina e Timon, onde crianças dançam e interagem com os personagens. Fique nas primeiras fileiras para aumentar as chances de serem chamadas ao palco.`,
      icone: "🕺",
      imagem: "disney-junior.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3567,
      longitude: -81.5611
    },
    {
      id: "voyage-little-mermaid",
      titulo: "Voyage of The Little Mermaid",
      subtitulo: "Animation Courtyard",
      tipo: "Show ao vivo com efeitos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Musical de Ariel com fantoches, projeções, músicas e efeitos de água. Encanta todas as idades. Sente-se no meio para melhor visão e evite as primeiras filas se não gosta de respingos.`,
      icone: "🧜‍♀️",
      imagem: "little-mermaid.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3561,
      longitude: -81.5605
    },
    {
      id: "walt-disney-presents",
      titulo: "Walt Disney Presents",
      subtitulo: "Animation Courtyard",
      tipo: "Exposição interativa e filme",
      tipoPerfil: ["imersivas", "tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Exposição sobre a vida e obras de Walt Disney, com maquetes, objetos históricos e um filme inspirador. Explore tudo antes do filme, pois as luzes se apagam durante a exibição.`,
      icone: "🎞️",
      imagem: "walt-disney-presents.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3564,
      longitude: -81.5602
    },
    {
      id: "star-wars-launch-bay",
      titulo: "Star Wars Launch Bay",
      subtitulo: "Animation Courtyard",
      tipo: "Exposição e encontros com personagens",
      tipoPerfil: ["interativas", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "noite",
      descricao: `Encontros com Chewbacca, Darth Vader e BB-8, além de figurinos e adereços originais de Star Wars. Leve câmera para registrar as interações e os cenários.`,
      icone: "🚀",
      imagem: "star-wars-launch-bay.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3560,
      longitude: -81.5608
    },
    {
      id: "animation-photo-spot",
      titulo: "Animation Courtyard Photo Spot",
      subtitulo: "Animation Courtyard",
      tipo: "Ponto de fotos com personagens",
      tipoPerfil: ["tematicas", "familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Cenários temáticos para fotos com Pluto, Fancy Nancy e Doc McStuffins. Leve algo para autógrafos, pois os personagens assinam e interagem bastante.`,
      icone: "📸",
      imagem: "animation-photo.jpg",
      regiao: "Animation Courtyard",
      parque: "Hollywood Studios",
      latitude: 28.3565,
      longitude: -81.5609
    }
  ]
};
