ï»¿export const Asia = {
  parque: "Animal Kingdom",
  descricao: "Inspirada no Himalaia e na selva asiÃƒÂ¡tica, mistura montanhas-russas radicais, aventuras aquÃƒÂ¡ticas e trilhas com vida selvagem.",
  imagem: "asia.png",
  latitude: 28.3588,
  longitude: -81.5915,
  atracoes: [
    {
      id: "expedition-everest",
      titulo: "Expedition Everest Ã¢â‚¬â€œ Legend of the Forbidden Mountain",
      subtitulo: "Asia",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 112,
      filaExpress: true,
      tempoMedioFila: 55,
      filaAceitavel: 40,
      idadeRecomendada: "8+",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Montanha-russa veloz com rÃƒÂ©, tÃƒÂºneis escuros e encontro com o Yeti. Para mais emoÃƒÂ§ÃƒÂ£o, sente nos primeiros vagÃƒÂµes; para curtir o visual e o suspense, escolha os ÃƒÂºltimos.`,
      icone: "Ã°Å¸Ââ€Ã¯Â¸Â",
      imagem: "expedition-everest.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3582,
      longitude: -81.5916
    },
    {
      id: "kali-river-rapids",
      titulo: "Kali River Rapids",
      subtitulo: "Asia",
      tipo: "Aventura aquÃƒÂ¡tica",
      tipoPerfil: ["familiares", "radicais", "interativas"],
      alturaMinima: 96,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 35,
      idadeRecomendada: "6+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Descida de bote por corredeiras com respingos e quedas refrescantes. Leve capa ou troca de roupa, pois quem senta de costas nas quedas se molha mais.`,
      icone: "Ã°Å¸Å’Å ",
      imagem: "kali-river-rapids.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3590,
      longitude: -81.5914
    },
    {
      id: "maharajah-jungle-trek",
      titulo: "Maharajah Jungle Trek",
      subtitulo: "Asia",
      tipo: "Trilha de observaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Trilha por jardins e ruÃƒÂ­nas com tigres, aves exÃƒÂ³ticas e outros animais. Os melhores ÃƒÂ¢ngulos para fotos dos tigres ficam no meio do percurso.`,
      icone: "Ã°Å¸Ââ€¦",
      imagem: "maharajah-jungle-trek.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3586,
      longitude: -81.5909
    },
    {
      id: "feathered-friends-in-flight",
      titulo: "Feathered Friends in Flight!",
      subtitulo: "Asia",
      tipo: "ApresentaÃƒÂ§ÃƒÂ£o com aves",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Show educativo com aves treinadas voando sobre o pÃƒÂºblico. Sente nas pontas das fileiras para vÃƒÂª-las passando bem perto e garantir fotos incrÃƒÂ­veis.`,
      icone: "Ã°Å¸Â¦Å“",
      imagem: "feathered-friends.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3591,
      longitude: -81.5910
    },
    {
      id: "serpent-statue",
      titulo: "Serpent Shrine",
      subtitulo: "Asia",
      tipo: "Ponto temÃƒÂ¡tico para fotos",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `EstÃƒÂ¡tua sagrada em ruÃƒÂ­nas asiÃƒÂ¡ticas, cenÃƒÂ¡rio perfeito para fotos. A luz do fim da tarde deixa o visual ainda mais bonito.`,
      icone: "Ã°Å¸ÂÂ",
      imagem: "serpent-shrine.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3589,
      longitude: -81.5908
    }
  ]
};
