export const Asia = {
  parque: "Animal Kingdom",
  descricao: "Inspirada no Himalaia e na selva asiÃ¡tica, mistura montanhas-russas radicais, aventuras aquÃ¡ticas e trilhas com vida selvagem.",
  imagem: "asia.png",
  latitude: 28.3588,
  longitude: -81.5915,
  atracoes: [
    {
      id: "expedition-everest",
      titulo: "Expedition Everest â€“ Legend of the Forbidden Mountain",
      subtitulo: "Asia",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 112,
      filaExpress: true,
      tempoMedioFila: 55,
      filaAceitavel: 40,
      idadeRecomendada: "8+",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Montanha-russa veloz com rÃ©, tÃºneis escuros e encontro com o Yeti. Para mais emoÃ§Ã£o, sente nos primeiros vagÃµes; para curtir o visual e o suspense, escolha os Ãºltimos.`,
      icone: "ðŸ”ï¸",
      imagem: "expedition-everest.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3582,
      longitude: -81.5916
    },
    {
      id: "kali-river-rapids",
      titulo: "Kali River Rapids",
      subtitulo: "Asia",
      tipo: "Aventura aquÃ¡tica",
      tipoPerfil: ["familiares", "radicais", "interativas"],
      alturaMinima: 96,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 35,
      idadeRecomendada: "6+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Descida de bote por corredeiras com respingos e quedas refrescantes. Leve capa ou troca de roupa, pois quem senta de costas nas quedas se molha mais.`,
      icone: "ðŸŒŠ",
      imagem: "kali-river-rapids.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3590,
      longitude: -81.5914
    },
    {
      id: "maharajah-jungle-trek",
      titulo: "Maharajah Jungle Trek",
      subtitulo: "Asia",
      tipo: "Trilha de observaÃ§Ã£o",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Trilha por jardins e ruÃ­nas com tigres, aves exÃ³ticas e outros animais. Os melhores Ã¢ngulos para fotos dos tigres ficam no meio do percurso.`,
      icone: "ðŸ…",
      imagem: "maharajah-jungle-trek.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3586,
      longitude: -81.5909
    },
    {
      id: "feathered-friends-in-flight",
      titulo: "Feathered Friends in Flight!",
      subtitulo: "Asia",
      tipo: "ApresentaÃ§Ã£o com aves",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Show educativo com aves treinadas voando sobre o pÃºblico. Sente nas pontas das fileiras para vÃª-las passando bem perto e garantir fotos incrÃ­veis.`,
      icone: "ðŸ¦œ",
      imagem: "feathered-friends.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3591,
      longitude: -81.5910
    },
    {
      id: "serpent-statue",
      titulo: "Serpent Shrine",
      subtitulo: "Asia",
      tipo: "Ponto temÃ¡tico para fotos",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `EstÃ¡tua sagrada em ruÃ­nas asiÃ¡ticas, cenÃ¡rio perfeito para fotos. A luz do fim da tarde deixa o visual ainda mais bonito.`,
      icone: "ðŸ",
      imagem: "serpent-shrine.jpg",
      regiao: "Asia",
      parque: "Animal Kingdom",
      latitude: 28.3589,
      longitude: -81.5908
    }
  ]
};
