ï»¿export const DinoLand = {
  parque: "Animal Kingdom",
  descricao: "Tema de dinossauros, fÃƒÂ³sseis e escavaÃƒÂ§ÃƒÂµes, misturando atraÃƒÂ§ÃƒÂµes radicais e diversÃƒÂ£o para todas as idades.",
  imagem: "dinolandusa.png",
  latitude: 28.3581,
  longitude: -81.5867,
  atracoes: [
    {
      id: "dinosaur",
      titulo: "DINOSAUR",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Simulador escuro com movimento",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 30,
      idadeRecomendada: "8+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Simulador intenso em jipe pelo mundo dos dinossauros, com sustos e sacudidas. Sente-se no meio para menos impacto e prepare-se para rugidos e efeitos no escuro.`,
      icone: "Ã°Å¸Â¦â€“",
      imagem: "dinosaur.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3579,
      longitude: -81.5871
    },
    {
      id: "triceratop-spin",
      titulo: "TriceraTop Spin",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Brinquedo giratÃƒÂ³rio",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Voe num dinossauro controlando a altura durante o giro. Sente nas pontas para melhor vista da ÃƒÂ¡rea e mais liberdade para brincar.`,
      icone: "Ã°Å¸Â¦â€¢",
      imagem: "triceratop-spin.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3583,
      longitude: -81.5865
    },
    {
      id: "fossil-fun-games",
      titulo: "Fossil Fun Games",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Jogos de parque",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Jogos de argolas, alvos e prÃƒÂªmios no tema de fÃƒÂ³sseis. Jogue em horÃƒÂ¡rios mais tranquilos para aumentar as chances de ganhar.`,
      icone: "Ã°Å¸Å½Â¯",
      imagem: "fossil-fun-games.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3582,
      longitude: -81.5863
    },
    {
      id: "boneyard",
      titulo: "The Boneyard",
      subtitulo: "DinoLand U.S.A.",
      tipo: "ÃƒÂrea de escavaÃƒÂ§ÃƒÂ£o e playground",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Playground temÃƒÂ¡tico com escavaÃƒÂ§ÃƒÂµes, tÃƒÂºneis e escorregadores. Leve ÃƒÂ¡gua, protetor solar e supervisione os pequenos nas ÃƒÂ¡reas de areia.`,
      icone: "Ã¢â€ºÂÃ¯Â¸Â",
      imagem: "the-boneyard.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3580,
      longitude: -81.5869
    },
    {
      id: "donald-daisy-meet",
      titulo: "Meet Donald & Daisy at DinoLand",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Encontro com personagens",
      tipoPerfil: ["tematicas", "familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Fotos e interaÃƒÂ§ÃƒÂ£o com Donald e Daisy em trajes jurÃƒÂ¡ssicos. Leve caderno ou objeto para autÃƒÂ³grafo e registre o momento.`,
      icone: "Ã°Å¸â€œÂ¸",
      imagem: "donald-daisy.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3577,
      longitude: -81.5868
    }
  ]
};
