export const DinoLand = {
  parque: "Animal Kingdom",
  descricao: "Tema de dinossauros, fósseis e escavações, misturando atrações radicais e diversão para todas as idades.",
  imagem: "dinolandusa.png",
  latitude: 28.3581,
  longitude: -81.5867,
  atracoes: [
    {
      id: "dinosaur",
      titulo: "DINOSAUR",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Simulador escuro com movimento",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 30,
      idadeRecomendada: "8+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Simulador intenso em jipe pelo mundo dos dinossauros, com sustos e sacudidas. Sente-se no meio para menos impacto e prepare-se para rugidos e efeitos no escuro.`,
      icone: "🦖",
      imagem: "dinosaur.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3579,
      longitude: -81.5871
    },
    {
      id: "triceratop-spin",
      titulo: "TriceraTop Spin",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Brinquedo giratório",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Voe num dinossauro controlando a altura durante o giro. Sente nas pontas para melhor vista da área e mais liberdade para brincar.`,
      icone: "🦕",
      imagem: "triceratop-spin.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3583,
      longitude: -81.5865
    },
    {
      id: "fossil-fun-games",
      titulo: "Fossil Fun Games",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Jogos de parque",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Jogos de argolas, alvos e prêmios no tema de fósseis. Jogue em horários mais tranquilos para aumentar as chances de ganhar.`,
      icone: "🎯",
      imagem: "fossil-fun-games.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3582,
      longitude: -81.5863
    },
    {
      id: "boneyard",
      titulo: "The Boneyard",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Área de escavação e playground",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Playground temático com escavações, túneis e escorregadores. Leve água, protetor solar e supervisione os pequenos nas áreas de areia.`,
      icone: "⛏️",
      imagem: "the-boneyard.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3580,
      longitude: -81.5869
    },
    {
      id: "donald-daisy-meet",
      titulo: "Meet Donald & Daisy at DinoLand",
      subtitulo: "DinoLand U.S.A.",
      tipo: "Encontro com personagens",
      tipoPerfil: ["tematicas", "familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Fotos e interação com Donald e Daisy em trajes jurássicos. Leve caderno ou objeto para autógrafo e registre o momento.`,
      icone: "📸",
      imagem: "donald-daisy.jpg",
      regiao: "DinoLand U.S.A.",
      parque: "Animal Kingdom",
      latitude: 28.3577,
      longitude: -81.5868
    }
  ]
};
