ï»¿export const DiscoveryIsland = {
  parque: "Animal Kingdom",
  descricao: "CoraÃƒÂ§ÃƒÂ£o do parque, com acesso central, trilhas, biodiversidade e o icÃƒÂ´nico Tree of Life.",
  imagem: "discoveryisland.png",
  latitude: 28.3574,
  longitude: -81.5902,
  atracoes: [
    {
      id: "its-tough-to-be-a-bug",
      titulo: "ItÃ¢â‚¬â„¢s Tough to Be a Bug!",
      subtitulo: "Discovery Island",
      tipo: "Show 4D",
      tipoPerfil: ["imersivas", "tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "6+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Show 4D divertido com personagens de Vida de Inseto, cheios de efeitos e surpresas. Sente no meio do teatro para melhor experiÃƒÂªncia.`,
      icone: "Ã°Å¸ÂÅ“",
      imagem: "its-tough-to-be-a-bug.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3572,
      longitude: -81.5899
    },
    {
      id: "tree-of-life-trails",
      titulo: "Tree of Life Trails",
      subtitulo: "Discovery Island",
      tipo: "Trilha de observaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Trilhas ao redor da ÃƒÂrvore da Vida, com esculturas de animais e vistas lindas. Explore cada lado para descobrir figuras escondidas.`,
      icone: "Ã°Å¸Å’Â³",
      imagem: "tree-of-life-trails.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3575,
      longitude: -81.5905
    },
    {
      id: "adventurers-outpost",
      titulo: "Adventurers Outpost",
      subtitulo: "Discovery Island",
      tipo: "Encontro com personagens",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Fotos e interaÃƒÂ§ÃƒÂ£o com Mickey e Minnie vestidos de exploradores. Leve caderno ou objeto para autÃƒÂ³grafo e registre o momento.`,
      icone: "Ã°Å¸â€œÂ¸",
      imagem: "adventurers-outpost.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3571,
      longitude: -81.5903
    },
    {
      id: "island-mercantile",
      titulo: "Island Mercantile",
      subtitulo: "Discovery Island",
      tipo: "Loja temÃƒÂ¡tica",
      tipoPerfil: ["tematicas", "familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Loja ampla e climatizada com roupas, brinquedos e souvenirs do Animal Kingdom. Procure itens exclusivos com o logo da Tree of Life.`,
      icone: "Ã°Å¸â€ºÂÃ¯Â¸Â",
      imagem: "island-mercantile.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3576,
      longitude: -81.5901
    },
    {
      id: "flame-tree-bbq-area",
      titulo: "ÃƒÂrea temÃƒÂ¡tica do Flame Tree BBQ",
      subtitulo: "Discovery Island",
      tipo: "ÃƒÂrea de alimentaÃƒÂ§ÃƒÂ£o temÃƒÂ¡tica",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: `Mesas ÃƒÂ  beira do lago com vista para shows noturnos. Sente prÃƒÂ³ximo ÃƒÂ  ÃƒÂ¡gua para ver o pÃƒÂ´r do sol e aproveitar a noite.`,
      icone: "Ã°Å¸Ââ€“",
      imagem: "flame-tree-area.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3578,
      longitude: -81.5898
    }
  ]
};
