export const DiscoveryIsland = {
  parque: "Animal Kingdom",
  descricao: "Coração do parque, com acesso central, trilhas, biodiversidade e o icônico Tree of Life.",
  imagem: "discoveryisland.png",
  latitude: 28.3574,
  longitude: -81.5902,
  atracoes: [
    {
      id: "its-tough-to-be-a-bug",
      titulo: "It’s Tough to Be a Bug!",
      subtitulo: "Discovery Island",
      tipo: "Show 4D",
      tipoPerfil: ["imersivas", "tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "6+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Show 4D divertido com personagens de Vida de Inseto, cheios de efeitos e surpresas. Sente no meio do teatro para melhor experiência.`,
      icone: "🐜",
      imagem: "its-tough-to-be-a-bug.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3572,
      longitude: -81.5899
    },
    {
      id: "tree-of-life-trails",
      titulo: "Tree of Life Trails",
      subtitulo: "Discovery Island",
      tipo: "Trilha de observação",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Trilhas ao redor da Árvore da Vida, com esculturas de animais e vistas lindas. Explore cada lado para descobrir figuras escondidas.`,
      icone: "🌳",
      imagem: "tree-of-life-trails.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3575,
      longitude: -81.5905
    },
    {
      id: "adventurers-outpost",
      titulo: "Adventurers Outpost",
      subtitulo: "Discovery Island",
      tipo: "Encontro com personagens",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Fotos e interação com Mickey e Minnie vestidos de exploradores. Leve caderno ou objeto para autógrafo e registre o momento.`,
      icone: "📸",
      imagem: "adventurers-outpost.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3571,
      longitude: -81.5903
    },
    {
      id: "island-mercantile",
      titulo: "Island Mercantile",
      subtitulo: "Discovery Island",
      tipo: "Loja temática",
      tipoPerfil: ["tematicas", "familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Loja ampla e climatizada com roupas, brinquedos e souvenirs do Animal Kingdom. Procure itens exclusivos com o logo da Tree of Life.`,
      icone: "🛍️",
      imagem: "island-mercantile.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3576,
      longitude: -81.5901
    },
    {
      id: "flame-tree-bbq-area",
      titulo: "Área temática do Flame Tree BBQ",
      subtitulo: "Discovery Island",
      tipo: "Área de alimentação temática",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: `Mesas à beira do lago com vista para shows noturnos. Sente próximo à água para ver o pôr do sol e aproveitar a noite.`,
      icone: "🍖",
      imagem: "flame-tree-area.jpg",
      regiao: "Discovery Island",
      parque: "Animal Kingdom",
      latitude: 28.3578,
      longitude: -81.5898
    }
  ]
};
