ï»¿export const EchoLake = {
  regiao: "Echo Lake",
  parque: "Hollywood Studios",
  latitude: 28.3574,
  longitude: -81.5606,
  descricao: "Cinema clÃƒÂ¡ssico, shows ao vivo e atraÃƒÂ§ÃƒÂµes inspiradas em Indiana Jones, Star Wars e Frozen.",
  imagem: "echolake.png",
  atracoes: [
    {
      id: "indiana-jones-stunt-spectacular",
      titulo: "Indiana Jones Epic Stunt Spectacular!",
      subtitulo: "Echo Lake",
      tipo: "Show de acrobacias",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Show com dublÃƒÂªs, explosÃƒÂµes e cenas clÃƒÂ¡ssicas de Indiana Jones. Sente-se no centro para melhor visÃƒÂ£o das acrobacias.`,
      icone: "Ã°Å¸Å½Â¬",
      imagem: "indiana-jones.jpg",
      latitude: 28.3575,
      longitude: -81.5607
    },
    {
      id: "star-tours",
      titulo: "Star Tours Ã¢â‚¬â€œ The Adventures Continue",
      subtitulo: "Echo Lake",
      tipo: "Simulador 3D",
      tipoPerfil: ["imersivas", "radicais", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 30,
      idadeRecomendada: "7+",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Simulador 3D com aventuras variadas no universo Star Wars. Sente-se no meio da cabine para menos impacto.`,
      icone: "Ã°Å¸Å¡â‚¬",
      imagem: "star-tours.jpg",
      latitude: 28.3576,
      longitude: -81.5605
    },
    {
      id: "meet-olaf",
      titulo: "Meet Olaf at Celebrity Spotlight",
      subtitulo: "Echo Lake",
      tipo: "Encontro com personagens",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Fotos e interaÃƒÂ§ÃƒÂ£o com Olaf em cenÃƒÂ¡rio nevado. Leve caderno para autÃƒÂ³grafos e chegue cedo.`,
      icone: "Ã¢ËœÆ’Ã¯Â¸Â",
      imagem: "meet-olaf.jpg",
      latitude: 28.3573,
      longitude: -81.5608
    },
    {
      id: "for-the-first-time-in-forever",
      titulo: "Frozen Sing-Along Celebration",
      subtitulo: "Echo Lake",
      tipo: "Show musical com personagens",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: `Show musical de Frozen com efeitos e neve artificial. Sente-se no meio para melhor visÃƒÂ£o.`,
      icone: "Ã°Å¸Å½Â¤",
      imagem: "frozen-sing-along.jpg",
      latitude: 28.3578,
      longitude: -81.5604
    },
    {
      id: "dockside-diner",
      titulo: "Dockside Diner",
      subtitulo: "Echo Lake",
      tipo: "ÃƒÂrea de alimentaÃƒÂ§ÃƒÂ£o e relaxamento",
      tipoPerfil: ["tematicas", "familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Barco cenogrÃƒÂ¡fico com lanches e mesas ao ar livre. Sente ÃƒÂ  beira do lago para fotos incrÃƒÂ­veis.`,
      icone: "Ã°Å¸Ââ€",
      imagem: "dockside-diner.jpg",
      latitude: 28.3577,
      longitude: -81.5606
    }
  ]
};
