export const EchoLake = {
  regiao: "Echo Lake",
  parque: "Hollywood Studios",
  latitude: 28.3574,
  longitude: -81.5606,
  descricao: "Cinema clássico, shows ao vivo e atrações inspiradas em Indiana Jones, Star Wars e Frozen.",
  imagem: "echolake.png",
  atracoes: [
    {
      id: "indiana-jones-stunt-spectacular",
      titulo: "Indiana Jones Epic Stunt Spectacular!",
      subtitulo: "Echo Lake",
      tipo: "Show de acrobacias",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Show com dublês, explosões e cenas clássicas de Indiana Jones. Sente-se no centro para melhor visão das acrobacias.`,
      icone: "🎬",
      imagem: "indiana-jones.jpg",
      latitude: 28.3575,
      longitude: -81.5607
    },
    {
      id: "star-tours",
      titulo: "Star Tours – The Adventures Continue",
      subtitulo: "Echo Lake",
      tipo: "Simulador 3D",
      tipoPerfil: ["imersivas", "radicais", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 30,
      idadeRecomendada: "7+",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Simulador 3D com aventuras variadas no universo Star Wars. Sente-se no meio da cabine para menos impacto.`,
      icone: "🚀",
      imagem: "star-tours.jpg",
      latitude: 28.3576,
      longitude: -81.5605
    },
    {
      id: "meet-olaf",
      titulo: "Meet Olaf at Celebrity Spotlight",
      subtitulo: "Echo Lake",
      tipo: "Encontro com personagens",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Fotos e interação com Olaf em cenário nevado. Leve caderno para autógrafos e chegue cedo.`,
      icone: "☃️",
      imagem: "meet-olaf.jpg",
      latitude: 28.3573,
      longitude: -81.5608
    },
    {
      id: "for-the-first-time-in-forever",
      titulo: "Frozen Sing-Along Celebration",
      subtitulo: "Echo Lake",
      tipo: "Show musical com personagens",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: `Show musical de Frozen com efeitos e neve artificial. Sente-se no meio para melhor visão.`,
      icone: "🎤",
      imagem: "frozen-sing-along.jpg",
      latitude: 28.3578,
      longitude: -81.5604
    },
    {
      id: "dockside-diner",
      titulo: "Dockside Diner",
      subtitulo: "Echo Lake",
      tipo: "Área de alimentação e relaxamento",
      tipoPerfil: ["tematicas", "familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Barco cenográfico com lanches e mesas ao ar livre. Sente à beira do lago para fotos incríveis.`,
      icone: "🍔",
      imagem: "dockside-diner.jpg",
      latitude: 28.3577,
      longitude: -81.5606
    }
  ]
};
