ï»¿export const Fantasyland = {
  parque: "Magic Kingdom",
  regiao: "Fantasyland",
  latitude: 28.4194,
  longitude: -81.5812,
  descricao: "Encantadora ÃƒÂ¡rea inspirada nos contos de fadas, com princesas, castelos e atraÃƒÂ§ÃƒÂµes mÃƒÂ¡gicas para todas as idades.",
  imagem: "fantasyland.png",
  atracoes: [
    {
      id: "peter-pan-flight",
      titulo: "Peter PanÃ¢â‚¬â„¢s Flight",
      subtitulo: "Fantasyland",
      tipo: "Dark ride suspensa",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Voe sobre Londres atÃƒÂ© a Terra do Nunca num carrinho suspenso. VÃƒÂ¡ cedo e sente ÃƒÂ  direita para melhor vista.",
      icone: "Ã°Å¸Â§Å¡",
      imagem: "peter-pan.jpg",
      latitude: 28.4196,
      longitude: -81.5814
    },
    {
      id: "seven-dwarfs-mine-train",
      titulo: "Seven Dwarfs Mine Train",
      subtitulo: "Fantasyland",
      tipo: "Montanha-russa suave",
      tipoPerfil: ["radicais", "tematicas", "familiares"],
      alturaMinima: 97,
      filaExpress: true,
      tempoMedioFila: 75,
      filaAceitavel: 45,
      idadeRecomendada: "5+",
      turnoRecomendado: "manha",
      descricao: "Montanha-russa leve por minas cheias de anÃƒÂµes animatrÃƒÂ´nicos. ÃƒÅ¡ltimos vagÃƒÂµes dÃƒÂ£o mais balanÃƒÂ§o.",
      icone: "Ã¢â€ºÂÃ¯Â¸Â",
      imagem: "mine-train.jpg",
      latitude: 28.4192,
      longitude: -81.5810
    },
    {
      id: "its-a-small-world",
      titulo: "ItÃ¢â‚¬â„¢s a Small World",
      subtitulo: "Fantasyland",
      tipo: "Passeio de barco temÃƒÂ¡tico",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Passeio de barco por cenÃƒÂ¡rios e culturas do mundo com a icÃƒÂ´nica mÃƒÂºsica. Olhe para todos os lados para ver os detalhes.",
      icone: "Ã°Å¸Å’Â",
      imagem: "small-world.jpg",
      latitude: 28.4198,
      longitude: -81.5816
    },
    {
      id: "the-many-adventures-of-winnie",
      titulo: "The Many Adventures of Winnie the Pooh",
      subtitulo: "Fantasyland",
      tipo: "Dark ride interativa",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Acompanhe o Pooh em cenas fofas com abelhas, sonhos e tigger-pulos. Brinque nas telas interativas da fila.",
      icone: "Ã°Å¸ÂÂ»Ã°Å¸ÂÂ¯",
      imagem: "winnie-the-pooh.jpg",
      latitude: 28.4190,
      longitude: -81.5811
    },
    {
      id: "mad-tea-party",
      titulo: "Mad Tea Party",
      subtitulo: "Fantasyland",
      tipo: "XÃƒÂ­caras giratÃƒÂ³rias",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Gire em xÃƒÂ­caras coloridas ao som de Alice. Controle o volante para mais ou menos velocidade; ÃƒÂ  noite fica ainda mais bonito.",
      icone: "Ã°Å¸ÂÂµ",
      imagem: "mad-tea-party.jpg",
      latitude: 28.4191,
      longitude: -81.5809
    },
    {
      id: "under-the-sea-little-mermaid",
      titulo: "Under the Sea Ã¢â‚¬â€œ Journey of The Little Mermaid",
      subtitulo: "Fantasyland",
      tipo: "Dark ride musical",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Passeio em conchas pelo mundo de Ariel com mÃƒÂºsicas clÃƒÂ¡ssicas e cenÃƒÂ¡rios coloridos. Observe os detalhes das animaÃƒÂ§ÃƒÂµes nas paredes.",
      icone: "Ã°Å¸Â§Å“Ã¢â‚¬ÂÃ¢â„¢â‚¬Ã¯Â¸Â",
      imagem: "under-the-sea.jpg",
      latitude: 28.4200,
      longitude: -81.5812
    },
    {
      id: "enchanted-tales-with-belle",
      titulo: "Enchanted Tales with Belle",
      subtitulo: "Fantasyland",
      tipo: "Encontro/contaÃƒÂ§ÃƒÂ£o de histÃƒÂ³rias",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Participe da histÃƒÂ³ria com a Bela em uma sala mÃƒÂ¡gica com espelho-portal. CrianÃƒÂ§as podem atuar; chegue um pouco antes para garantir lugar.",
      icone: "Ã°Å¸â€œâ€“Ã°Å¸Å’Â¹",
      imagem: "enchanted-belle.jpg",
      latitude: 28.4199,
      longitude: -81.5818
    },
    {
      id: "prince-charming-regal-carrousel",
      titulo: "Prince Charming Regal Carrousel",
      subtitulo: "Fantasyland",
      tipo: "Carrossel clÃƒÂ¡ssico",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Carrossel vintage com cavalos detalhados em frente ao castelo. Fotos ficam lindas ao amanhecer.",
      icone: "Ã°Å¸Å½Â ",
      imagem: "regal-carrousel.jpg",
      latitude: 28.4195,
      longitude: -81.5815
    },
    {
      id: "barnstormer",
      titulo: "The Barnstormer",
      subtitulo: "Fantasyland (Storybook Circus)",
      tipo: "Montanha-russa infantil",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 89,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 20,
      idadeRecomendada: "4+",
      turnoRecomendado: "manha",
      descricao: "Mini-coaster do Pateta com curvas rÃƒÂ¡pidas e trajeto curto Ã¢â‚¬â€ perfeita como Ã¢â‚¬Ëœprimeira montanha-russaÃ¢â‚¬â„¢.",
      icone: "Ã¢Å“Ë†Ã¯Â¸Â",
      imagem: "barnstormer.jpg",
      latitude: 28.4203,
      longitude: -81.5806
    },
    {
      id: "mickeys-philharmagic",
      titulo: "MickeyÃ¢â‚¬â„¢s PhilharMagic",
      subtitulo: "Fantasyland",
      tipo: "Cinema 3D musical",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Filme 3D com mÃƒÂºsicas clÃƒÂ¡ssicas e efeitos de vento e aromas. Ãƒâ€œtimo para descansar e curtir ar-condicionado.",
      icone: "Ã°Å¸Å½Â¬Ã°Å¸Å½Â¶",
      imagem: "philharmagic.jpg",
      latitude: 28.4197,
      longitude: -81.5817
    },
    {
      id: "dumbo-the-flying-elephant",
      titulo: "Dumbo the Flying Elephant",
      subtitulo: "Fantasyland (Storybook Circus)",
      tipo: "Brinquedo giratÃƒÂ³rio",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Voe com o Dumbo controlando a altura da sua gÃƒÂ´ndola. A ÃƒÂ¡rea de fila tem playground climatizado para as crianÃƒÂ§as.",
      icone: "Ã°Å¸ÂËœ",
      imagem: "dumbo.jpg",
      latitude: 28.4204,
      longitude: -81.5808
    },
    {
      id: "princess-fairytale-hall",
      titulo: "Princess Fairytale Hall",
      subtitulo: "Fantasyland",
      tipo: "Encontro com princesas",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Encontro com princesas como Cinderela, Rapunzel e Tiana. Leve caderno para autÃƒÂ³grafos e perguntas para interagir.",
      icone: "Ã°Å¸â€˜â€˜",
      imagem: "princess-hall.jpg",
      latitude: 28.4195,
      longitude: -81.5813
    }
  ]
};
