export const Fantasyland = {
  parque: "Magic Kingdom",
  regiao: "Fantasyland",
  latitude: 28.4194,
  longitude: -81.5812,
  descricao: "Encantadora Ã¡rea inspirada nos contos de fadas, com princesas, castelos e atraÃ§Ãµes mÃ¡gicas para todas as idades.",
  imagem: "fantasyland.png",
  atracoes: [
    {
      id: "peter-pan-flight",
      titulo: "Peter Panâ€™s Flight",
      subtitulo: "Fantasyland",
      tipo: "Dark ride suspensa",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Voe sobre Londres atÃ© a Terra do Nunca num carrinho suspenso. VÃ¡ cedo e sente Ã  direita para melhor vista.",
      icone: "ðŸ§š",
      imagem: "peter-pan.jpg",
      latitude: 28.4196,
      longitude: -81.5814
    },
    {
      id: "seven-dwarfs-mine-train",
      titulo: "Seven Dwarfs Mine Train",
      subtitulo: "Fantasyland",
      tipo: "Montanha-russa suave",
      tipoPerfil: ["radicais", "tematicas", "familiares"],
      alturaMinima: 97,
      filaExpress: true,
      tempoMedioFila: 75,
      filaAceitavel: 45,
      idadeRecomendada: "5+",
      turnoRecomendado: "manha",
      descricao: "Montanha-russa leve por minas cheias de anÃµes animatrÃ´nicos. Ãšltimos vagÃµes dÃ£o mais balanÃ§o.",
      icone: "â›ï¸",
      imagem: "mine-train.jpg",
      latitude: 28.4192,
      longitude: -81.5810
    },
    {
      id: "its-a-small-world",
      titulo: "Itâ€™s a Small World",
      subtitulo: "Fantasyland",
      tipo: "Passeio de barco temÃ¡tico",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Passeio de barco por cenÃ¡rios e culturas do mundo com a icÃ´nica mÃºsica. Olhe para todos os lados para ver os detalhes.",
      icone: "ðŸŒ",
      imagem: "small-world.jpg",
      latitude: 28.4198,
      longitude: -81.5816
    },
    {
      id: "the-many-adventures-of-winnie",
      titulo: "The Many Adventures of Winnie the Pooh",
      subtitulo: "Fantasyland",
      tipo: "Dark ride interativa",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Acompanhe o Pooh em cenas fofas com abelhas, sonhos e tigger-pulos. Brinque nas telas interativas da fila.",
      icone: "ðŸ»ðŸ¯",
      imagem: "winnie-the-pooh.jpg",
      latitude: 28.4190,
      longitude: -81.5811
    },
    {
      id: "mad-tea-party",
      titulo: "Mad Tea Party",
      subtitulo: "Fantasyland",
      tipo: "XÃ­caras giratÃ³rias",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Gire em xÃ­caras coloridas ao som de Alice. Controle o volante para mais ou menos velocidade; Ã  noite fica ainda mais bonito.",
      icone: "ðŸµ",
      imagem: "mad-tea-party.jpg",
      latitude: 28.4191,
      longitude: -81.5809
    },
    {
      id: "under-the-sea-little-mermaid",
      titulo: "Under the Sea â€“ Journey of The Little Mermaid",
      subtitulo: "Fantasyland",
      tipo: "Dark ride musical",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Passeio em conchas pelo mundo de Ariel com mÃºsicas clÃ¡ssicas e cenÃ¡rios coloridos. Observe os detalhes das animaÃ§Ãµes nas paredes.",
      icone: "ðŸ§œâ€â™€ï¸",
      imagem: "under-the-sea.jpg",
      latitude: 28.4200,
      longitude: -81.5812
    },
    {
      id: "enchanted-tales-with-belle",
      titulo: "Enchanted Tales with Belle",
      subtitulo: "Fantasyland",
      tipo: "Encontro/contaÃ§Ã£o de histÃ³rias",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Participe da histÃ³ria com a Bela em uma sala mÃ¡gica com espelho-portal. CrianÃ§as podem atuar; chegue um pouco antes para garantir lugar.",
      icone: "ðŸ“–ðŸŒ¹",
      imagem: "enchanted-belle.jpg",
      latitude: 28.4199,
      longitude: -81.5818
    },
    {
      id: "prince-charming-regal-carrousel",
      titulo: "Prince Charming Regal Carrousel",
      subtitulo: "Fantasyland",
      tipo: "Carrossel clÃ¡ssico",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Carrossel vintage com cavalos detalhados em frente ao castelo. Fotos ficam lindas ao amanhecer.",
      icone: "ðŸŽ ",
      imagem: "regal-carrousel.jpg",
      latitude: 28.4195,
      longitude: -81.5815
    },
    {
      id: "barnstormer",
      titulo: "The Barnstormer",
      subtitulo: "Fantasyland (Storybook Circus)",
      tipo: "Montanha-russa infantil",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 89,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 20,
      idadeRecomendada: "4+",
      turnoRecomendado: "manha",
      descricao: "Mini-coaster do Pateta com curvas rÃ¡pidas e trajeto curto â€” perfeita como â€˜primeira montanha-russaâ€™.",
      icone: "âœˆï¸",
      imagem: "barnstormer.jpg",
      latitude: 28.4203,
      longitude: -81.5806
    },
    {
      id: "mickeys-philharmagic",
      titulo: "Mickeyâ€™s PhilharMagic",
      subtitulo: "Fantasyland",
      tipo: "Cinema 3D musical",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Filme 3D com mÃºsicas clÃ¡ssicas e efeitos de vento e aromas. Ã“timo para descansar e curtir ar-condicionado.",
      icone: "ðŸŽ¬ðŸŽ¶",
      imagem: "philharmagic.jpg",
      latitude: 28.4197,
      longitude: -81.5817
    },
    {
      id: "dumbo-the-flying-elephant",
      titulo: "Dumbo the Flying Elephant",
      subtitulo: "Fantasyland (Storybook Circus)",
      tipo: "Brinquedo giratÃ³rio",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Voe com o Dumbo controlando a altura da sua gÃ´ndola. A Ã¡rea de fila tem playground climatizado para as crianÃ§as.",
      icone: "ðŸ˜",
      imagem: "dumbo.jpg",
      latitude: 28.4204,
      longitude: -81.5808
    },
    {
      id: "princess-fairytale-hall",
      titulo: "Princess Fairytale Hall",
      subtitulo: "Fantasyland",
      tipo: "Encontro com princesas",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Encontro com princesas como Cinderela, Rapunzel e Tiana. Leve caderno para autÃ³grafos e perguntas para interagir.",
      icone: "ðŸ‘‘",
      imagem: "princess-hall.jpg",
      latitude: 28.4195,
      longitude: -81.5813
    }
  ]
};
