export const Fantasyland = {
  parque: "Magic Kingdom",
  regiao: "Fantasyland",
  latitude: 28.4194,
  longitude: -81.5812,
  descricao:
    "Encantadora área inspirada nos contos de fadas, com princesas, castelos e atrações mágicas para todas as idades.",
  imagem: "fantasyland.png",
  atracoes: [
    {
      id: "peter-pan-flight",
      titulo: "Peter Pan’s Flight",
      subtitulo: "Fantasyland",
      tipo: "Dark ride suspensa",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao:
        "Voe sobre Londres até a Terra do Nunca num carrinho suspenso. Vá cedo e sente à direita para melhor vista.",
      icone: "🧚",
      imagem: "peter-pan.jpg",
      latitude: 28.4196,
      longitude: -81.5814
    },
    {
      id: "seven-dwarfs-mine-train",
      titulo: "Seven Dwarfs Mine Train",
      subtitulo: "Fantasyland",
      tipo: "Montanha-russa suave",
      tipoPerfil: ["radicais", "tematicas", "familiares"],
      alturaMinima: 97,
      filaExpress: true,
      tempoMedioFila: 75,
      filaAceitavel: 45,
      idadeRecomendada: "5+",
      turnoRecomendado: "manha",
      descricao:
        "Montanha-russa leve por minas cheias de anões animatrônicos. Últimos vagões dão mais balanço.",
      icone: "⛏️",
      imagem: "mine-train.jpg",
      latitude: 28.4192,
      longitude: -81.5810
    },
    {
      id: "its-a-small-world",
      titulo: "It’s a Small World",
      subtitulo: "Fantasyland",
      tipo: "Passeio de barco temático",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao:
        "Passeio de barco por cenários e culturas do mundo com a icônica música. Olhe para todos os lados para ver os detalhes.",
      icone: "🌍",
      imagem: "small-world.jpg",
      latitude: 28.4198,
      longitude: -81.5816
    },
    {
      id: "the-many-adventures-of-winnie",
      titulo: "The Many Adventures of Winnie the Pooh",
      subtitulo: "Fantasyland",
      tipo: "Dark ride interativa",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao:
        "Acompanhe o Pooh em cenas fofas com abelhas, sonhos e tigger-pulos. Brinque nas telas interativas da fila.",
      icone: "🐻🍯",
      imagem: "winnie-the-pooh.jpg",
      latitude: 28.4190,
      longitude: -81.5811
    },
    {
      id: "mad-tea-party",
      titulo: "Mad Tea Party",
      subtitulo: "Fantasyland",
      tipo: "Xícaras giratórias",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao:
        "Gire em xícaras coloridas ao som de Alice. Controle o volante para mais ou menos velocidade; à noite fica ainda mais bonito.",
      icone: "🍵",
      imagem: "mad-tea-party.jpg",
      latitude: 28.4191,
      longitude: -81.5809
    },
    {
      id: "under-the-sea-little-mermaid",
      titulo: "Under the Sea – Journey of The Little Mermaid",
      subtitulo: "Fantasyland",
      tipo: "Dark ride musical",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao:
        "Passeio em conchas pelo mundo de Ariel com músicas clássicas e cenários coloridos. Observe os detalhes das animações nas paredes.",
      icone: "🧜‍♀️",
      imagem: "under-the-sea.jpg",
      latitude: 28.4200,
      longitude: -81.5812
    },
    {
      id: "enchanted-tales-with-belle",
      titulo: "Enchanted Tales with Belle",
      subtitulo: "Fantasyland",
      tipo: "Encontro/contação de histórias",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao:
        "Participe da história com a Bela em uma sala mágica com espelho-portal. Crianças podem atuar; chegue um pouco antes para garantir lugar.",
      icone: "📖🌹",
      imagem: "enchanted-belle.jpg",
      latitude: 28.4199,
      longitude: -81.5818
    },
    {
      id: "prince-charming-regal-carrousel",
      titulo: "Prince Charming Regal Carrousel",
      subtitulo: "Fantasyland",
      tipo: "Carrossel clássico",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao:
        "Carrossel vintage com cavalos detalhados em frente ao castelo. Fotos ficam lindas ao amanhecer.",
      icone: "🎠",
      imagem: "regal-carrousel.jpg",
      latitude: 28.4195,
      longitude: -81.5815
    },
    {
      id: "barnstormer",
      titulo: "The Barnstormer",
      subtitulo: "Fantasyland (Storybook Circus)",
      tipo: "Montanha-russa infantil",
      tipoPerfil: ["familiares", "tematicas"],
      alturaMinima: 89,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 20,
      idadeRecomendada: "4+",
      turnoRecomendado: "manha",
      descricao:
        "Mini-coaster do Pateta com curvas rápidas e trajeto curto — perfeita como ‘primeira montanha-russa’.",
      icone: "✈️",
      imagem: "barnstormer.jpg",
      latitude: 28.4203,
      longitude: -81.5806
    },
    // SHOW PRINCIPAL DA ÁREA
    {
      id: "mickeys-philharmagic",
      titulo: "Mickey’s PhilharMagic",
      subtitulo: "Fantasyland",
      tipo: "Cinema 3D musical",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao:
        "Filme 3D com músicas clássicas e efeitos de vento e aromas. Ótimo para descansar e curtir ar-condicionado.",
      icone: "🎬🎶",
      imagem: "philharmagic.jpg",
      latitude: 28.4197,
      longitude: -81.5817
    },
    {
      id: "dumbo-the-flying-elephant",
      titulo: "Dumbo the Flying Elephant",
      subtitulo: "Fantasyland (Storybook Circus)",
      tipo: "Brinquedo giratório",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao:
        "Voe com o Dumbo controlando a altura da sua gôndola. A área de fila tem playground climatizado para as crianças.",
      icone: "🐘",
      imagem: "dumbo.jpg",
      latitude: 28.4204,
      longitude: -81.5808
    },
    {
      id: "princess-fairytale-hall",
      titulo: "Princess Fairytale Hall",
      subtitulo: "Fantasyland",
      tipo: "Encontro com princesas",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao:
        "Encontro com princesas como Cinderela, Rapunzel e Tiana. Leve caderno para autógrafos e perguntas para interagir.",
      icone: "👑",
      imagem: "princess-hall.jpg",
      latitude: 28.4195,
      longitude: -81.5813
    }
  ]
};
