export const Frontierland = {
  parque: "Magic Kingdom",
  regiao: "Frontierland",
  latitude: 28.4188,
  longitude: -81.5851,
  descricao: "Velho Oeste da Disney, com minas, quedas dâ€™Ã¡gua e aventuras ao ar livre. Perfeito para quem gosta de emoÃ§Ã£o em cenÃ¡rio rÃºstico.",
  imagem: "frontierland.png",
  atracoes: [
    {
      id: "big-thunder-mountain",
      titulo: "Big Thunder Mountain Railroad",
      subtitulo: "Frontierland",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "tematicas", "familiares"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "5+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Montanha-russa em mina de ouro, com curvas rÃ¡pidas e visual do Velho Oeste. SugestÃ£o: sente-se nos Ãºltimos vagÃµes para mais emoÃ§Ã£o.`,
      icone: "ðŸ”ï¸",
      imagem: "big-thunder.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom",
      latitude: 28.4190,
      longitude: -81.5853
    },
    {
      id: "splash-mountain",
      titulo: "Splash Mountain",
      subtitulo: "Frontierland",
      tipo: "Aventura aquÃ¡tica",
      tipoPerfil: ["familiares", "radicais", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 65,
      filaAceitavel: 45,
      idadeRecomendada: "5+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio musical com personagens animados e grande queda dâ€™Ã¡gua no final. SugestÃ£o: leve capa ou sente no fundo para molhar menos.`,
      icone: "ðŸ’¦",
      imagem: "splash-mountain.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom",
      latitude: 28.4186,
      longitude: -81.5850
    },
    {
      id: "frontierland-shooting-gallery",
      titulo: "Frontierland Shootinâ€™ Arcade",
      subtitulo: "Frontierland",
      tipo: "Jogo de tiro temÃ¡tico",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Campo de tiro com alvos do Velho Oeste. SugestÃ£o: mire nos alvos mÃ³veis para marcar mais pontos.`,
      icone: "ðŸŽ¯",
      imagem: "shooting-gallery.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom",
      latitude: 28.4187,
      longitude: -81.5852
    },
    {
      id: "country-bear-jamboree",
      titulo: "Country Bear Jamboree",
      subtitulo: "Frontierland",
      tipo: "Show musical com bonecos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Show divertido com ursos animatrÃ´nicos cantando country. SugestÃ£o: sente nas fileiras da frente para ver melhor.`,
      icone: "ðŸ»",
      imagem: "country-bear.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom",
      latitude: 28.4189,
      longitude: -81.5854
    }
  ]
};
