export const Frontierland = {
  parque: "Magic Kingdom",
  regiao: "Frontierland",
  latitude: 28.4188,
  longitude: -81.5851,
  descricao: "Velho Oeste da Disney, com minas, quedas d’água e aventuras ao ar livre. Perfeito para quem gosta de emoção em cenário rústico.",
  imagem: "frontierland.png",
  atracoes: [
    {
      id: "big-thunder-mountain",
      titulo: "Big Thunder Mountain Railroad",
      subtitulo: "Frontierland",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "tematicas", "familiares"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "5+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Montanha-russa em mina de ouro, com curvas rápidas e visual do Velho Oeste. Sugestão: sente-se nos últimos vagões para mais emoção.`,
      icone: "🏔️",
      imagem: "big-thunder.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom",
      latitude: 28.4190,
      longitude: -81.5853
    },
    {
      id: "splash-mountain",
      titulo: "Splash Mountain",
      subtitulo: "Frontierland",
      tipo: "Aventura aquática",
      tipoPerfil: ["familiares", "radicais", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 65,
      filaAceitavel: 45,
      idadeRecomendada: "5+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio musical com personagens animados e grande queda d’água no final. Sugestão: leve capa ou sente no fundo para molhar menos.`,
      icone: "💦",
      imagem: "splash-mountain.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom",
      latitude: 28.4186,
      longitude: -81.5850
    },
    {
      id: "frontierland-shooting-gallery",
      titulo: "Frontierland Shootin’ Arcade",
      subtitulo: "Frontierland",
      tipo: "Jogo de tiro temático",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Campo de tiro com alvos do Velho Oeste. Sugestão: mire nos alvos móveis para marcar mais pontos.`,
      icone: "🎯",
      imagem: "shooting-gallery.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom",
      latitude: 28.4187,
      longitude: -81.5852
    },
    {
      id: "country-bear-jamboree",
      titulo: "Country Bear Jamboree",
      subtitulo: "Frontierland",
      tipo: "Show musical com bonecos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Show divertido com ursos animatrônicos cantando country. Sugestão: sente nas fileiras da frente para ver melhor.`,
      icone: "🐻",
      imagem: "country-bear.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom",
      latitude: 28.4189,
      longitude: -81.5854
    }
  ]
};
