ï»¿export const Frontierland = {
  parque: "Magic Kingdom",
  regiao: "Frontierland",
  latitude: 28.4188,
  longitude: -81.5851,
  descricao: "Velho Oeste da Disney, com minas, quedas dÃ¢â‚¬â„¢ÃƒÂ¡gua e aventuras ao ar livre. Perfeito para quem gosta de emoÃƒÂ§ÃƒÂ£o em cenÃƒÂ¡rio rÃƒÂºstico.",
  imagem: "frontierland.png",
  atracoes: [
    {
      id: "big-thunder-mountain",
      titulo: "Big Thunder Mountain Railroad",
      subtitulo: "Frontierland",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "tematicas", "familiares"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "5+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Montanha-russa em mina de ouro, com curvas rÃƒÂ¡pidas e visual do Velho Oeste. SugestÃƒÂ£o: sente-se nos ÃƒÂºltimos vagÃƒÂµes para mais emoÃƒÂ§ÃƒÂ£o.`,
      icone: "Ã°Å¸Ââ€Ã¯Â¸Â",
      imagem: "big-thunder.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom",
      latitude: 28.4190,
      longitude: -81.5853
    },
    {
      id: "splash-mountain",
      titulo: "Splash Mountain",
      subtitulo: "Frontierland",
      tipo: "Aventura aquÃƒÂ¡tica",
      tipoPerfil: ["familiares", "radicais", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 65,
      filaAceitavel: 45,
      idadeRecomendada: "5+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio musical com personagens animados e grande queda dÃ¢â‚¬â„¢ÃƒÂ¡gua no final. SugestÃƒÂ£o: leve capa ou sente no fundo para molhar menos.`,
      icone: "Ã°Å¸â€™Â¦",
      imagem: "splash-mountain.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom",
      latitude: 28.4186,
      longitude: -81.5850
    },
    {
      id: "frontierland-shooting-gallery",
      titulo: "Frontierland ShootinÃ¢â‚¬â„¢ Arcade",
      subtitulo: "Frontierland",
      tipo: "Jogo de tiro temÃƒÂ¡tico",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Campo de tiro com alvos do Velho Oeste. SugestÃƒÂ£o: mire nos alvos mÃƒÂ³veis para marcar mais pontos.`,
      icone: "Ã°Å¸Å½Â¯",
      imagem: "shooting-gallery.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom",
      latitude: 28.4187,
      longitude: -81.5852
    },
    {
      id: "country-bear-jamboree",
      titulo: "Country Bear Jamboree",
      subtitulo: "Frontierland",
      tipo: "Show musical com bonecos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Show divertido com ursos animatrÃƒÂ´nicos cantando country. SugestÃƒÂ£o: sente nas fileiras da frente para ver melhor.`,
      icone: "Ã°Å¸ÂÂ»",
      imagem: "country-bear.jpg",
      regiao: "Frontierland",
      parque: "Magic Kingdom",
      latitude: 28.4189,
      longitude: -81.5854
    }
  ]
};
