ï»¿export const GrandAvenue = {
  parque: "Hollywood Studios",
  regiao: "Grand Avenue",
  latitude: 28.3551,
  longitude: -81.5615,
  descricao: "Inspirada em Los Angeles, com clima urbano, opÃƒÂ§ÃƒÂµes gastronÃƒÂ´micas e atraÃƒÂ§ÃƒÂµes como os Muppets.",
  imagem: "grandavenue.png",
  atracoes: [
    {
      id: "muppet-vision-3d",
      titulo: "Muppet*Vision 3D",
      subtitulo: "Grand Avenue",
      tipo: "Show 3D com fantoches",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Show 3D divertido com os Muppets e efeitos especiais. SugestÃƒÂ£o: sente-se no meio para aproveitar melhor os efeitos.`,
      icone: "Ã°Å¸Å½Â­",
      imagem: "muppet-vision.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios",
      latitude: 28.3551,
      longitude: -81.5615
    },
    {
      id: "baseline-tap-house",
      titulo: "Baseline Tap House",
      subtitulo: "Grand Avenue",
      tipo: "Bar e lanches",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 5,
      filaAceitavel: 10,
      idadeRecomendada: "Maiores de 18",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: `Bar com cervejas artesanais e petiscos californianos. SugestÃƒÂ£o: sente-se nas mesas externas para observar o movimento.`,
      icone: "Ã°Å¸ÂÂº",
      imagem: "baseline-taphouse.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios",
      latitude: 28.3551,
      longitude: -81.5615
    },
    {
      id: "grand-street-photo",
      titulo: "Grand Street Photo Spot",
      subtitulo: "Grand Avenue",
      tipo: "Ponto para fotos temÃƒÂ¡ticas",
      tipoPerfil: ["tematicas", "familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `CenÃƒÂ¡rio urbano inspirado em Los Angeles. SugestÃƒÂ£o: aproveite a luz da manhÃƒÂ£ para fotos mais bonitas.`,
      icone: "Ã°Å¸â€œÂ¸",
      imagem: "grand-photo.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios",
      latitude: 28.3551,
      longitude: -81.5615
    },
    {
      id: "grand-avenue-walk",
      titulo: "Passeio pela Grand Avenue",
      subtitulo: "Grand Avenue",
      tipo: "ExploraÃƒÂ§ÃƒÂ£o urbana",
      tipoPerfil: ["imersivas", "tematicas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Passeio leve por calÃƒÂ§adas arborizadas com arquitetura californiana. SugestÃƒÂ£o: repare nas vitrines e placas com curiosidades.`,
      icone: "Ã°Å¸Å¡Â¶Ã¢â‚¬ÂÃ¢â„¢â€šÃ¯Â¸Â",
      imagem: "grand-walk.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios",
      latitude: 28.3551,
      longitude: -81.5615
    },
    {
      id: "muppet-shop",
      titulo: "Stage 1 Company Store",
      subtitulo: "Grand Avenue",
      tipo: "Loja temÃƒÂ¡tica dos Muppets",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Loja com produtos e lembranÃƒÂ§as dos Muppets. Procure itens exclusivos que sÃƒÂ³ existem aqui.`,
      icone: "Ã°Å¸â€ºÂÃ¯Â¸Â",
      imagem: "muppet-store.jpg",
      regiao: "Grand Avenue",
      parque: "Hollywood Studios",
      latitude: 28.3551,
      longitude: -81.5615
    }
  ]
};
