export const HollywoodBoulevard = {
  parque: "Hollywood Studios",
  regiao: "Hollywood Boulevard",
  latitude: 28.3575,
  longitude: -81.5586,
  descricao: "A avenida principal do parque, com teatros clássicos, lojas temáticas e acesso às áreas centrais.",
  imagem: "hollywoodboulevard.png",
  atracoes: [
    {
      id: "runaway-railway",
      titulo: "Mickey & Minnie’s Runaway Railway",
      subtitulo: "Hollywood Boulevard",
      tipo: "Dark ride imersiva",
      tipoPerfil: ["imersivas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Passeio imersivo com Mickey e Minnie, projeções e trilha animada. Sugestão: sente-se no meio para melhor visão das cenas.`,
      icone: "🎥",
      imagem: "runaway-railway.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3576,
      longitude: -81.5587
    },
    {
      id: "red-car-trolley",
      titulo: "Red Car Trolley",
      subtitulo: "Hollywood Boulevard",
      tipo: "Passeio de bonde temático",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Passeio calmo em bonde elétrico anos 30. Sugestão: escolha o assento da janela para boas fotos.`,
      icone: "🚋",
      imagem: "red-car-trolley.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3574,
      longitude: -81.5585
    },
    {
      id: "hollywood-character-spot",
      titulo: "Encontro com Personagens da Disney",
      subtitulo: "Hollywood Boulevard",
      tipo: "Ponto de foto e interação",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Fotos e interação com Mickey, Minnie e Pateta. Sugestão: leve caderno de autógrafos para registrar o momento.`,
      icone: "📸",
      imagem: "hollywood-character-spot.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3575,
      longitude: -81.5586
    },
    {
      id: "disney-studio-store",
      titulo: "Disney Studio Store",
      subtitulo: "Hollywood Boulevard",
      tipo: "Loja temática",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Loja com itens exclusivos e souvenirs. Sugestão: compre no final do dia e solicite entrega no hotel.`,
      icone: "🛍️",
      imagem: "studio-store.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3577,
      longitude: -81.5588
    },
    {
      id: "crossroads-of-the-world",
      titulo: "Crossroads of the World",
      subtitulo: "Hollywood Boulevard",
      tipo: "Ponto icônico e loja",
      tipoPerfil: ["tematicas", "familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Ponto marcante com a bola do Mickey e quiosques. Sugestão: tire fotos logo na entrada para evitar movimento.`,
      icone: "🎈",
      imagem: "crossroads.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3573,
      longitude: -81.5584
    }
  ]
};
