ï»¿export const HollywoodBoulevard = {
  parque: "Hollywood Studios",
  regiao: "Hollywood Boulevard",
  latitude: 28.3575,
  longitude: -81.5586,
  descricao: "A avenida principal do parque, com teatros clÃƒÂ¡ssicos, lojas temÃƒÂ¡ticas e acesso ÃƒÂ s ÃƒÂ¡reas centrais.",
  imagem: "hollywoodboulevard.png",
  atracoes: [
    {
      id: "runaway-railway",
      titulo: "Mickey & MinnieÃ¢â‚¬â„¢s Runaway Railway",
      subtitulo: "Hollywood Boulevard",
      tipo: "Dark ride imersiva",
      tipoPerfil: ["imersivas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Passeio imersivo com Mickey e Minnie, projeÃƒÂ§ÃƒÂµes e trilha animada. SugestÃƒÂ£o: sente-se no meio para melhor visÃƒÂ£o das cenas.`,
      icone: "Ã°Å¸Å½Â¥",
      imagem: "runaway-railway.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3576,
      longitude: -81.5587
    },
    {
      id: "red-car-trolley",
      titulo: "Red Car Trolley",
      subtitulo: "Hollywood Boulevard",
      tipo: "Passeio de bonde temÃƒÂ¡tico",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Passeio calmo em bonde elÃƒÂ©trico anos 30. SugestÃƒÂ£o: escolha o assento da janela para boas fotos.`,
      icone: "Ã°Å¸Å¡â€¹",
      imagem: "red-car-trolley.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3574,
      longitude: -81.5585
    },
    {
      id: "hollywood-character-spot",
      titulo: "Encontro com Personagens da Disney",
      subtitulo: "Hollywood Boulevard",
      tipo: "Ponto de foto e interaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Fotos e interaÃƒÂ§ÃƒÂ£o com Mickey, Minnie e Pateta. SugestÃƒÂ£o: leve caderno de autÃƒÂ³grafos para registrar o momento.`,
      icone: "Ã°Å¸â€œÂ¸",
      imagem: "hollywood-character-spot.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3575,
      longitude: -81.5586
    },
    {
      id: "disney-studio-store",
      titulo: "Disney Studio Store",
      subtitulo: "Hollywood Boulevard",
      tipo: "Loja temÃƒÂ¡tica",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Loja com itens exclusivos e souvenirs. SugestÃƒÂ£o: compre no final do dia e solicite entrega no hotel.`,
      icone: "Ã°Å¸â€ºÂÃ¯Â¸Â",
      imagem: "studio-store.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3577,
      longitude: -81.5588
    },
    {
      id: "crossroads-of-the-world",
      titulo: "Crossroads of the World",
      subtitulo: "Hollywood Boulevard",
      tipo: "Ponto icÃƒÂ´nico e loja",
      tipoPerfil: ["tematicas", "familiares", "interativas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Ponto marcante com a bola do Mickey e quiosques. SugestÃƒÂ£o: tire fotos logo na entrada para evitar movimento.`,
      icone: "Ã°Å¸Å½Ë†",
      imagem: "crossroads.jpg",
      regiao: "Hollywood Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3573,
      longitude: -81.5584
    }
  ]
};
