ï»¿export const LibertySquare = {
  parque: "Magic Kingdom",
  regiao: "Liberty Square",
  latitude: 28.4194,
  longitude: -81.5812,
  descricao: "ÃƒÂrea com tema da era colonial americana, com mansÃƒÂ£o assombrada, barco a vapor e atraÃƒÂ§ÃƒÂµes histÃƒÂ³ricas.",
  imagem: "libertysquare.png",
  atracoes: [
    {
      id: "haunted-mansion",
      titulo: "Haunted Mansion",
      subtitulo: "Liberty Square",
      tipo: "Dark ride",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 30,
      idadeRecomendada: "6+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio por mansÃƒÂ£o assombrada com fantasmas e efeitos especiais. SugestÃƒÂ£o: repare no fantasma da noiva no salÃƒÂ£o principal.`,
      icone: "Ã°Å¸â€˜Â»",
      imagem: "haunted-mansion.jpg",
      regiao: "Liberty Square",
      parque: "Magic Kingdom",
      latitude: 28.4200,
      longitude: -81.5815
    },
    {
      id: "liberty-square-riverboat",
      titulo: "Liberty Square Riverboat",
      subtitulo: "Liberty Square",
      tipo: "Passeio de barco a vapor",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Passeio tranquilo em barco a vapor pelo Rivers of America. SugestÃƒÂ£o: suba no ÃƒÂºltimo deck para vistas melhores.`,
      icone: "Ã°Å¸Å¡Â¢",
      imagem: "liberty-riverboat.jpg",
      regiao: "Liberty Square",
      parque: "Magic Kingdom",
      latitude: 28.4192,
      longitude: -81.5809
    },
    {
      id: "hall-of-presidents",
      titulo: "The Hall of Presidents",
      subtitulo: "Liberty Square",
      tipo: "Show com animatrÃƒÂ´nicos",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "10+",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Show com animatrÃƒÂ´nicos de todos os presidentes dos EUA. SugestÃƒÂ£o: sente-se na frente para ver os detalhes.`,
      icone: "Ã°Å¸â€”Â½",
      imagem: "hall-of-presidents.jpg",
      regiao: "Liberty Square",
      parque: "Magic Kingdom",
      latitude: 28.4191,
      longitude: -81.5813
    },
    {
      id: "liberty-bell-photo",
      titulo: "Liberty Bell Replica",
      subtitulo: "Liberty Square",
      tipo: "Ponto histÃƒÂ³rico para fotos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `RÃƒÂ©plica da Liberty Bell com curiosidades histÃƒÂ³ricas. SugestÃƒÂ£o: fotografe de vÃƒÂ¡rios ÃƒÂ¢ngulos e leia as placas informativas.`,
      icone: "Ã°Å¸â€â€",
      imagem: "liberty-bell.jpg",
      regiao: "Liberty Square",
      parque: "Magic Kingdom",
      latitude: 28.4193,
      longitude: -81.5811
    }
  ]
};
