export const LibertySquare = {
  parque: "Magic Kingdom",
  regiao: "Liberty Square",
  latitude: 28.4194,
  longitude: -81.5812,
  descricao: "Área com tema da era colonial americana, com mansão assombrada, barco a vapor e atrações históricas.",
  imagem: "libertysquare.png",
  atracoes: [
    {
      id: "haunted-mansion",
      titulo: "Haunted Mansion",
      subtitulo: "Liberty Square",
      tipo: "Dark ride",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 30,
      idadeRecomendada: "6+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio por mansão assombrada com fantasmas e efeitos especiais. Sugestão: repare no fantasma da noiva no salão principal.`,
      icone: "👻",
      imagem: "haunted-mansion.jpg",
      regiao: "Liberty Square",
      parque: "Magic Kingdom",
      latitude: 28.4200,
      longitude: -81.5815
    },
    {
      id: "liberty-square-riverboat",
      titulo: "Liberty Square Riverboat",
      subtitulo: "Liberty Square",
      tipo: "Passeio de barco a vapor",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Passeio tranquilo em barco a vapor pelo Rivers of America. Sugestão: suba no último deck para vistas melhores.`,
      icone: "🚢",
      imagem: "liberty-riverboat.jpg",
      regiao: "Liberty Square",
      parque: "Magic Kingdom",
      latitude: 28.4192,
      longitude: -81.5809
    },
    {
      id: "hall-of-presidents",
      titulo: "The Hall of Presidents",
      subtitulo: "Liberty Square",
      tipo: "Show com animatrônicos",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "10+",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Show com animatrônicos de todos os presidentes dos EUA. Sugestão: sente-se na frente para ver os detalhes.`,
      icone: "🗽",
      imagem: "hall-of-presidents.jpg",
      regiao: "Liberty Square",
      parque: "Magic Kingdom",
      latitude: 28.4191,
      longitude: -81.5813
    },
    {
      id: "liberty-bell-photo",
      titulo: "Liberty Bell Replica",
      subtitulo: "Liberty Square",
      tipo: "Ponto histórico para fotos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `Réplica da Liberty Bell com curiosidades históricas. Sugestão: fotografe de vários ângulos e leia as placas informativas.`,
      icone: "🔔",
      imagem: "liberty-bell.jpg",
      regiao: "Liberty Square",
      parque: "Magic Kingdom",
      latitude: 28.4193,
      longitude: -81.5811
    }
  ]
};
