export const LibertySquare = {
  parque: "Magic Kingdom",
  regiao: "Liberty Square",
  latitude: 28.4194,
  longitude: -81.5812,
  descricao: "Ãrea com tema da era colonial americana, com mansÃ£o assombrada, barco a vapor e atraÃ§Ãµes histÃ³ricas.",
  imagem: "libertysquare.png",
  atracoes: [
    {
      id: "haunted-mansion",
      titulo: "Haunted Mansion",
      subtitulo: "Liberty Square",
      tipo: "Dark ride",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 30,
      idadeRecomendada: "6+",
      atracaoSemFila: false,
      turnoRecomendado: "tarde",
      descricao: `Passeio por mansÃ£o assombrada com fantasmas e efeitos especiais. SugestÃ£o: repare no fantasma da noiva no salÃ£o principal.`,
      icone: "ðŸ‘»",
      imagem: "haunted-mansion.jpg",
      regiao: "Liberty Square",
      parque: "Magic Kingdom",
      latitude: 28.4200,
      longitude: -81.5815
    },
    {
      id: "liberty-square-riverboat",
      titulo: "Liberty Square Riverboat",
      subtitulo: "Liberty Square",
      tipo: "Passeio de barco a vapor",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: `Passeio tranquilo em barco a vapor pelo Rivers of America. SugestÃ£o: suba no Ãºltimo deck para vistas melhores.`,
      icone: "ðŸš¢",
      imagem: "liberty-riverboat.jpg",
      regiao: "Liberty Square",
      parque: "Magic Kingdom",
      latitude: 28.4192,
      longitude: -81.5809
    },
    {
      id: "hall-of-presidents",
      titulo: "The Hall of Presidents",
      subtitulo: "Liberty Square",
      tipo: "Show com animatrÃ´nicos",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "10+",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: `Show com animatrÃ´nicos de todos os presidentes dos EUA. SugestÃ£o: sente-se na frente para ver os detalhes.`,
      icone: "ðŸ—½",
      imagem: "hall-of-presidents.jpg",
      regiao: "Liberty Square",
      parque: "Magic Kingdom",
      latitude: 28.4191,
      longitude: -81.5813
    },
    {
      id: "liberty-bell-photo",
      titulo: "Liberty Bell Replica",
      subtitulo: "Liberty Square",
      tipo: "Ponto histÃ³rico para fotos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: `RÃ©plica da Liberty Bell com curiosidades histÃ³ricas. SugestÃ£o: fotografe de vÃ¡rios Ã¢ngulos e leia as placas informativas.`,
      icone: "ðŸ””",
      imagem: "liberty-bell.jpg",
      regiao: "Liberty Square",
      parque: "Magic Kingdom",
      latitude: 28.4193,
      longitude: -81.5811
    }
  ]
};
