ï»¿export const MainStreet = {
  parque: "Magic Kingdom",
  regiao: "Main Street, U.S.A.",
  latitude: 28.4187,
  longitude: -81.5818,
  descricao: "Entrada principal do parque, inspirada em cidade americana do inÃƒÂ­cio do sÃƒÂ©culo 20, com vista para o Castelo da Cinderela, lojas, restaurantes e paradas mÃƒÂ¡gicas ao longo do dia.",
  imagem: "mainstreetusa.png",
  atracoes: [
    {
      id: "main-street-parade",
      titulo: "Festival of Fantasy Parade",
      subtitulo: "Main Street, U.S.A.",
      tipo: "Desfile temÃƒÂ¡tico",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Desfile com carros alegÃƒÂ³ricos, mÃƒÂºsicas e personagens Disney. MultidÃƒÂ£o animada e clima festivo, sem sustos. Chegue cedo para garantir sombra e um bom lugar para fotos.",
      icone: "Ã°Å¸Å½â€°",
      imagem: "festival-of-fantasy.jpg",
      regiao: "Main Street, U.S.A.",
      parque: "Magic Kingdom",
      latitude: 28.4190,
      longitude: -81.5817
    },
    {
      id: "walt-disney-world-railroad",
      titulo: "Walt Disney World Railroad Ã¢â‚¬â€œ Main Street Station",
      subtitulo: "Main Street, U.S.A.",
      tipo: "Passeio de trem nostÃƒÂ¡lgico",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Trem a vapor que percorre o parque com paradas em Frontierland e Fantasyland. Passeio tranquilo e refrescante. Sente-se do lado direito para melhores vistas.",
      icone: "Ã°Å¸Å¡â€š",
      imagem: "main-street-train.jpg",
      regiao: "Main Street, U.S.A.",
      parque: "Magic Kingdom",
      latitude: 28.4188,
      longitude: -81.5819
    },
    {
      id: "dapper-dans",
      titulo: "Dapper Dans",
      subtitulo: "Main Street, U.S.A.",
      tipo: "Show musical de calÃƒÂ§ada",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Quarteto vocal clÃƒÂ¡ssico cantando mÃƒÂºsicas Disney e canÃƒÂ§ÃƒÂµes tradicionais. Clima nostÃƒÂ¡lgico e animado. Fique prÃƒÂ³ximo aos mÃƒÂºsicos para ouvir melhor e aproveitar as piadas.",
      icone: "Ã°Å¸Å½Â©",
      imagem: "dapper-dans.jpg",
      regiao: "Main Street, U.S.A.",
      parque: "Magic Kingdom",
      latitude: 28.4186,
      longitude: -81.5816
    },
    {
      id: "character-greetings-town-square",
      titulo: "Encontro com Mickey na Town Square Theater",
      subtitulo: "Main Street, U.S.A.",
      tipo: "Encontro com personagem",
      tipoPerfil: ["personagens", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Fotos e autÃƒÂ³grafos com Mickey em trajes clÃƒÂ¡ssicos. Ambiente climatizado e alegre. Leve algo para assinar e registre o abraÃƒÂ§o na primeira foto.",
      icone: "Ã°Å¸Å½Â­",
      imagem: "mickey-town-square.jpg",
      regiao: "Main Street, U.S.A.",
      parque: "Magic Kingdom",
      latitude: 28.4185,
      longitude: -81.5820
    },
    {
      id: "let-the-magic-begin",
      titulo: "Let the Magic Begin",
      subtitulo: "Main Street, U.S.A.",
      tipo: "Show de abertura do parque",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Show de abertura com personagens em frente ao Castelo da Cinderela. Muita mÃƒÂºsica e animaÃƒÂ§ÃƒÂ£o. Chegue cedo e posicione-se de frente para o castelo para melhores fotos.",
      icone: "Ã¢Å“Â¨",
      imagem: "let-the-magic-begin.jpg",
      regiao: "Main Street, U.S.A.",
      parque: "Magic Kingdom",
      latitude: 28.4191,
      longitude: -81.5815
    }
  ]
};
