export const MainStreet = {
  parque: "Magic Kingdom",
  regiao: "Main Street, U.S.A.",
  latitude: 28.4187,
  longitude: -81.5818,
  descricao: "Entrada principal do parque, inspirada em cidade americana do inÃ­cio do sÃ©culo 20, com vista para o Castelo da Cinderela, lojas, restaurantes e paradas mÃ¡gicas ao longo do dia.",
  imagem: "mainstreetusa.png",
  atracoes: [
    {
      id: "main-street-parade",
      titulo: "Festival of Fantasy Parade",
      subtitulo: "Main Street, U.S.A.",
      tipo: "Desfile temÃ¡tico",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Desfile com carros alegÃ³ricos, mÃºsicas e personagens Disney. MultidÃ£o animada e clima festivo, sem sustos. Chegue cedo para garantir sombra e um bom lugar para fotos.",
      icone: "ðŸŽ‰",
      imagem: "festival-of-fantasy.jpg",
      regiao: "Main Street, U.S.A.",
      parque: "Magic Kingdom",
      latitude: 28.4190,
      longitude: -81.5817
    },
    {
      id: "walt-disney-world-railroad",
      titulo: "Walt Disney World Railroad â€“ Main Street Station",
      subtitulo: "Main Street, U.S.A.",
      tipo: "Passeio de trem nostÃ¡lgico",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Trem a vapor que percorre o parque com paradas em Frontierland e Fantasyland. Passeio tranquilo e refrescante. Sente-se do lado direito para melhores vistas.",
      icone: "ðŸš‚",
      imagem: "main-street-train.jpg",
      regiao: "Main Street, U.S.A.",
      parque: "Magic Kingdom",
      latitude: 28.4188,
      longitude: -81.5819
    },
    {
      id: "dapper-dans",
      titulo: "Dapper Dans",
      subtitulo: "Main Street, U.S.A.",
      tipo: "Show musical de calÃ§ada",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Quarteto vocal clÃ¡ssico cantando mÃºsicas Disney e canÃ§Ãµes tradicionais. Clima nostÃ¡lgico e animado. Fique prÃ³ximo aos mÃºsicos para ouvir melhor e aproveitar as piadas.",
      icone: "ðŸŽ©",
      imagem: "dapper-dans.jpg",
      regiao: "Main Street, U.S.A.",
      parque: "Magic Kingdom",
      latitude: 28.4186,
      longitude: -81.5816
    },
    {
      id: "character-greetings-town-square",
      titulo: "Encontro com Mickey na Town Square Theater",
      subtitulo: "Main Street, U.S.A.",
      tipo: "Encontro com personagem",
      tipoPerfil: ["personagens", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: false,
      turnoRecomendado: "manha",
      descricao: "Fotos e autÃ³grafos com Mickey em trajes clÃ¡ssicos. Ambiente climatizado e alegre. Leve algo para assinar e registre o abraÃ§o na primeira foto.",
      icone: "ðŸŽ­",
      imagem: "mickey-town-square.jpg",
      regiao: "Main Street, U.S.A.",
      parque: "Magic Kingdom",
      latitude: 28.4185,
      longitude: -81.5820
    },
    {
      id: "let-the-magic-begin",
      titulo: "Let the Magic Begin",
      subtitulo: "Main Street, U.S.A.",
      tipo: "Show de abertura do parque",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Show de abertura com personagens em frente ao Castelo da Cinderela. Muita mÃºsica e animaÃ§Ã£o. Chegue cedo e posicione-se de frente para o castelo para melhores fotos.",
      icone: "âœ¨",
      imagem: "let-the-magic-begin.jpg",
      regiao: "Main Street, U.S.A.",
      parque: "Magic Kingdom",
      latitude: 28.4191,
      longitude: -81.5815
    }
  ]
};
