export const Oasis = {
  parque: "Animal Kingdom",
  regiao: "Oasis",
  latitude: 28.3548,
  longitude: -81.5901,
  descricao: "Entrada do parque com vegetação exuberante e trilhas tranquilas, levando por habitats de animais exóticos. Ambiente sombreado e relaxante, perfeito para fotos logo cedo e para começar o dia no seu ritmo.",
  imagem: "oasis.png",
  atracoes: [
    {
      id: "oasis-exhibits",
      titulo: "Oasis Animal Exhibits",
      subtitulo: "Oasis",
      tipo: "Trilhas e observação de animais",
      tipoPerfil: ["familiares", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Trilhas sombreadas entre pontes e córregos para observar antas, porcos-do-mato e aves tropicais. Frescor e tranquilidade, ideal para fotos logo cedo.",
      icone: "🦥",
      imagem: "oasis-exhibits.jpg",
      regiao: "Oasis",
      parque: "Animal Kingdom",
      latitude: 28.3547,
      longitude: -81.5895
    },
    {
      id: "welcome-waterfall",
      titulo: "Cachoeira de Boas-Vindas",
      subtitulo: "Oasis",
      tipo: "Ponto contemplativo e fotos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Pequena queda d'água cercada por plantas tropicais, cenário calmo e ótimo para contemplar e fotografar logo na entrada.",
      icone: "💧",
      imagem: "oasis-waterfall.jpg",
      regiao: "Oasis",
      parque: "Animal Kingdom",
      latitude: 28.3551,
      longitude: -81.5893
    },
    {
      id: "oasis-trails",
      titulo: "Exploração das Trilhas Tropicais",
      subtitulo: "Oasis",
      tipo: "Trilha temática sensorial",
      tipoPerfil: ["familiares", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Passarelas rodeadas de vegetação densa, sons naturais e sombra. Imersão na natureza, ideal para desacelerar e observar detalhes tropicais.",
      icone: "🌿",
      imagem: "oasis-trails.jpg",
      regiao: "Oasis",
      parque: "Animal Kingdom",
      latitude: 28.3553,
      longitude: -81.5898
    }
  ]
};
