export const Pandora = {
  parque: "Animal Kingdom",
  regiao: "Pandora â€“ The World of Avatar",
  latitude: 28.3564,
  longitude: -81.5916,
  descricao: "Ãrea imersiva inspirada no mundo de Avatar, com florestas bioluminescentes, cachoeiras flutuantes e experiÃªncias Ãºnicas, dia e noite. Vale visitar tambÃ©m Ã  noite, quando tudo ganha vida com luzes vibrantes.",
  imagem: "pandora.png",
  atracoes: [
    {
      id: "avatar-flight-of-passage",
      titulo: "Avatar Flight of Passage",
      subtitulo: "Pandora â€“ The World of Avatar",
      tipo: "Simulador 3D",
      tipoPerfil: ["imersivas", "radicais", "tematicas"],
      alturaMinima: 112,
      filaExpress: true,
      tempoMedioFila: 80,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "tarde",
      descricao: "Voe nas costas de um Banshee com vento, aromas e sensaÃ§Ã£o de liberdade total. ExperiÃªncia intensa e realista, mas pode causar enjoo em sensÃ­veis a simuladores. Se possÃ­vel, agende no fim do dia para aproveitar o visual noturno da fila e da Ã¡rea.",
      icone: "ðŸ¦‹",
      imagem: "flight-of-passage.jpg",
      regiao: "Pandora â€“ The World of Avatar",
      parque: "Animal Kingdom",
      latitude: 28.3568,
      longitude: -81.5917
    },
    {
      id: "navi-river-journey",
      titulo: "Na'vi River Journey",
      subtitulo: "Pandora â€“ The World of Avatar",
      tipo: "Passeio de barco",
      tipoPerfil: ["familiares", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 30,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Passeio de barco pela floresta bioluminescente com criaturas mÃ¡gicas e trilha relaxante. Tranquilo e encantador, ideal para descansar e admirar os detalhes. Melhor aproveitado de manhÃ£, quando a fila Ã© menor.",
      icone: "ðŸŒŒ",
      imagem: "navi-river.jpg",
      regiao: "Pandora â€“ The World of Avatar",
      parque: "Animal Kingdom",
      latitude: 28.3562,
      longitude: -81.5911
    },
    {
      id: "pandora-ambiente-imersivo",
      titulo: "Ambiente Imersivo de Pandora",
      subtitulo: "Pandora â€“ The World of Avatar",
      tipo: "ExperiÃªncia interativa ao ar livre",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "Trilhas com vegetaÃ§Ã£o bioluminescente, cachoeiras e sons da natureza. Melhor vivida Ã  noite, quando as plantas brilham e a atmosfera fica mÃ¡gica. Tire fotos sem flash para capturar o efeito natural.",
      icone: "ðŸŒ ",
      imagem: "pandora-imersiva.jpg",
      regiao: "Pandora â€“ The World of Avatar",
      parque: "Animal Kingdom",
      latitude: 28.3560,
      longitude: -81.5919
    }
  ]
};
