ï»¿export const Pandora = {
  parque: "Animal Kingdom",
  regiao: "Pandora Ã¢â‚¬â€œ The World of Avatar",
  latitude: 28.3564,
  longitude: -81.5916,
  descricao: "ÃƒÂrea imersiva inspirada no mundo de Avatar, com florestas bioluminescentes, cachoeiras flutuantes e experiÃƒÂªncias ÃƒÂºnicas, dia e noite. Vale visitar tambÃƒÂ©m ÃƒÂ  noite, quando tudo ganha vida com luzes vibrantes.",
  imagem: "pandora.png",
  atracoes: [
    {
      id: "avatar-flight-of-passage",
      titulo: "Avatar Flight of Passage",
      subtitulo: "Pandora Ã¢â‚¬â€œ The World of Avatar",
      tipo: "Simulador 3D",
      tipoPerfil: ["imersivas", "radicais", "tematicas"],
      alturaMinima: 112,
      filaExpress: true,
      tempoMedioFila: 80,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "tarde",
      descricao: "Voe nas costas de um Banshee com vento, aromas e sensaÃƒÂ§ÃƒÂ£o de liberdade total. ExperiÃƒÂªncia intensa e realista, mas pode causar enjoo em sensÃƒÂ­veis a simuladores. Se possÃƒÂ­vel, agende no fim do dia para aproveitar o visual noturno da fila e da ÃƒÂ¡rea.",
      icone: "Ã°Å¸Â¦â€¹",
      imagem: "flight-of-passage.jpg",
      regiao: "Pandora Ã¢â‚¬â€œ The World of Avatar",
      parque: "Animal Kingdom",
      latitude: 28.3568,
      longitude: -81.5917
    },
    {
      id: "navi-river-journey",
      titulo: "Na'vi River Journey",
      subtitulo: "Pandora Ã¢â‚¬â€œ The World of Avatar",
      tipo: "Passeio de barco",
      tipoPerfil: ["familiares", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 30,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Passeio de barco pela floresta bioluminescente com criaturas mÃƒÂ¡gicas e trilha relaxante. Tranquilo e encantador, ideal para descansar e admirar os detalhes. Melhor aproveitado de manhÃƒÂ£, quando a fila ÃƒÂ© menor.",
      icone: "Ã°Å¸Å’Å’",
      imagem: "navi-river.jpg",
      regiao: "Pandora Ã¢â‚¬â€œ The World of Avatar",
      parque: "Animal Kingdom",
      latitude: 28.3562,
      longitude: -81.5911
    },
    {
      id: "pandora-ambiente-imersivo",
      titulo: "Ambiente Imersivo de Pandora",
      subtitulo: "Pandora Ã¢â‚¬â€œ The World of Avatar",
      tipo: "ExperiÃƒÂªncia interativa ao ar livre",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "Trilhas com vegetaÃƒÂ§ÃƒÂ£o bioluminescente, cachoeiras e sons da natureza. Melhor vivida ÃƒÂ  noite, quando as plantas brilham e a atmosfera fica mÃƒÂ¡gica. Tire fotos sem flash para capturar o efeito natural.",
      icone: "Ã°Å¸Å’Â ",
      imagem: "pandora-imersiva.jpg",
      regiao: "Pandora Ã¢â‚¬â€œ The World of Avatar",
      parque: "Animal Kingdom",
      latitude: 28.3560,
      longitude: -81.5919
    }
  ]
};
