export const StarWars = {
  parque: "Hollywood Studios",
  regiao: "Star Wars: Galaxyâ€™s Edge",
  latitude: 28.3541,
  longitude: -81.5909,
  descricao: "Ãrea imersiva que recria o planeta Batuu, com naves em escala real, lojas, personagens e duas atraÃ§Ãµes Ã©picas da saga. Vale explorar Ã  noite, quando as luzes e sons criam uma atmosfera ainda mais intensa.",
  imagem: "starwarsgalaxyedge.png",
  atracoes: [
    {
      id: "rise-of-the-resistance",
      titulo: "Star Wars: Rise of the Resistance",
      subtitulo: "Star Wars: Galaxyâ€™s Edge",
      tipo: "Aventura imersiva",
      tipoPerfil: ["imersivas", "tematicas", "radicais"],
      alturaMinima: 102,
      filaExpress: false,
      tempoMedioFila: 80,
      filaAceitavel: 50,
      idadeRecomendada: "7+",
      turnoRecomendado: "manha",
      descricao: "MissÃ£o Ã©pica com mÃºltiplos cenÃ¡rios, efeitos e personagens da saga. Surpreendente e intensa, podendo assustar levemente crianÃ§as pequenas. Chegue cedo para filas menores e repare nos detalhes dos cenÃ¡rios.",
      icone: "ðŸš€",
      imagem: "rise-of-the-resistance.jpg",
      regiao: "Star Wars: Galaxyâ€™s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3545,
      longitude: -81.5914
    },
    {
      id: "millennium-falcon-smugglers-run",
      titulo: "Millennium Falcon: Smugglers Run",
      subtitulo: "Star Wars: Galaxyâ€™s Edge",
      tipo: "Simulador interativo",
      tipoPerfil: ["interativas", "imersivas", "tematicas"],
      alturaMinima: 97,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "6+",
      turnoRecomendado: "tarde",
      descricao: "Simulador onde cada um assume um papel na Millennium Falcon, com resultado variando conforme o desempenho. Pode causar leve enjoo, mas Ã© divertido e Ãºnico a cada rodada. PeÃ§a para ser piloto para a experiÃªncia mais disputada.",
      icone: "ðŸ›¸",
      imagem: "millennium-falcon.jpg",
      regiao: "Star Wars: Galaxyâ€™s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3537,
      longitude: -81.5912
    },
    {
      id: "encontro-chewbacca",
      titulo: "Encontro com Chewbacca",
      subtitulo: "Star Wars: Galaxyâ€™s Edge",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Fotos e abraÃ§os com Chewbacca, sempre interagindo de forma divertida e carismÃ¡tica. Chegue cedo para evitar filas e peÃ§a uma pose especial para a foto.",
      icone: "ðŸ§¸",
      imagem: "chewbacca.jpg",
      regiao: "Star Wars: Galaxyâ€™s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3542,
      longitude: -81.5908
    },
    {
      id: "encontro-kylo-ren",
      titulo: "Encontro com Kylo Ren",
      subtitulo: "Star Wars: Galaxyâ€™s Edge",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "imersivas", "radicais"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Kylo Ren interage de forma intensa e sÃ©ria, podendo intimidar crianÃ§as pequenas. Fique atento aos horÃ¡rios e prepare-se para uma foto Ãºnica.",
      icone: "ðŸ–¤",
      imagem: "kylo-ren.jpg",
      regiao: "Star Wars: Galaxyâ€™s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3540,
      longitude: -81.5906
    },
    {
      id: "patrulha-stormtroopers",
      titulo: "Patrulha de Stormtroopers",
      subtitulo: "Star Wars: Galaxyâ€™s Edge",
      tipo: "InteraÃ§Ã£o temÃ¡tica",
      tipoPerfil: ["tematicas", "interativas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Stormtroopers patrulham a Ã¡rea, interagindo de forma divertida e imprevisÃ­vel. Responda Ã s perguntas para reaÃ§Ãµes engraÃ§adas e registre em vÃ­deo.",
      icone: "âš”ï¸",
      imagem: "stormtroopers.jpg",
      regiao: "Star Wars: Galaxyâ€™s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3543,
      longitude: -81.5911
    }
  ]
};
