ï»¿export const StarWars = {
  parque: "Hollywood Studios",
  regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
  latitude: 28.3541,
  longitude: -81.5909,
  descricao: "ÃƒÂrea imersiva que recria o planeta Batuu, com naves em escala real, lojas, personagens e duas atraÃƒÂ§ÃƒÂµes ÃƒÂ©picas da saga. Vale explorar ÃƒÂ  noite, quando as luzes e sons criam uma atmosfera ainda mais intensa.",
  imagem: "starwarsgalaxyedge.png",
  atracoes: [
    {
      id: "rise-of-the-resistance",
      titulo: "Star Wars: Rise of the Resistance",
      subtitulo: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      tipo: "Aventura imersiva",
      tipoPerfil: ["imersivas", "tematicas", "radicais"],
      alturaMinima: 102,
      filaExpress: false,
      tempoMedioFila: 80,
      filaAceitavel: 50,
      idadeRecomendada: "7+",
      turnoRecomendado: "manha",
      descricao: "MissÃƒÂ£o ÃƒÂ©pica com mÃƒÂºltiplos cenÃƒÂ¡rios, efeitos e personagens da saga. Surpreendente e intensa, podendo assustar levemente crianÃƒÂ§as pequenas. Chegue cedo para filas menores e repare nos detalhes dos cenÃƒÂ¡rios.",
      icone: "Ã°Å¸Å¡â‚¬",
      imagem: "rise-of-the-resistance.jpg",
      regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3545,
      longitude: -81.5914
    },
    {
      id: "millennium-falcon-smugglers-run",
      titulo: "Millennium Falcon: Smugglers Run",
      subtitulo: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      tipo: "Simulador interativo",
      tipoPerfil: ["interativas", "imersivas", "tematicas"],
      alturaMinima: 97,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "6+",
      turnoRecomendado: "tarde",
      descricao: "Simulador onde cada um assume um papel na Millennium Falcon, com resultado variando conforme o desempenho. Pode causar leve enjoo, mas ÃƒÂ© divertido e ÃƒÂºnico a cada rodada. PeÃƒÂ§a para ser piloto para a experiÃƒÂªncia mais disputada.",
      icone: "Ã°Å¸â€ºÂ¸",
      imagem: "millennium-falcon.jpg",
      regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3537,
      longitude: -81.5912
    },
    {
      id: "encontro-chewbacca",
      titulo: "Encontro com Chewbacca",
      subtitulo: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Fotos e abraÃƒÂ§os com Chewbacca, sempre interagindo de forma divertida e carismÃƒÂ¡tica. Chegue cedo para evitar filas e peÃƒÂ§a uma pose especial para a foto.",
      icone: "Ã°Å¸Â§Â¸",
      imagem: "chewbacca.jpg",
      regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3542,
      longitude: -81.5908
    },
    {
      id: "encontro-kylo-ren",
      titulo: "Encontro com Kylo Ren",
      subtitulo: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "imersivas", "radicais"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "tarde",
      descricao: "Kylo Ren interage de forma intensa e sÃƒÂ©ria, podendo intimidar crianÃƒÂ§as pequenas. Fique atento aos horÃƒÂ¡rios e prepare-se para uma foto ÃƒÂºnica.",
      icone: "Ã°Å¸â€“Â¤",
      imagem: "kylo-ren.jpg",
      regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3540,
      longitude: -81.5906
    },
    {
      id: "patrulha-stormtroopers",
      titulo: "Patrulha de Stormtroopers",
      subtitulo: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      tipo: "InteraÃƒÂ§ÃƒÂ£o temÃƒÂ¡tica",
      tipoPerfil: ["tematicas", "interativas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Stormtroopers patrulham a ÃƒÂ¡rea, interagindo de forma divertida e imprevisÃƒÂ­vel. Responda ÃƒÂ s perguntas para reaÃƒÂ§ÃƒÂµes engraÃƒÂ§adas e registre em vÃƒÂ­deo.",
      icone: "Ã¢Å¡â€Ã¯Â¸Â",
      imagem: "stormtroopers.jpg",
      regiao: "Star Wars: GalaxyÃ¢â‚¬â„¢s Edge",
      parque: "Hollywood Studios",
      latitude: 28.3543,
      longitude: -81.5911
    }
  ]
};
