ï»¿export const SunsetBoulevard = {
  parque: "Hollywood Studios",
  regiao: "Sunset Boulevard",
  latitude: 28.3554,
  longitude: -81.5618,
  descricao: "Avenida com visual de cinema clÃƒÂ¡ssico que leva a atraÃƒÂ§ÃƒÂµes radicais, shows e encontros com personagens. Ãƒâ€œtima para fotos ao pÃƒÂ´r do sol e para curtir a iluminaÃƒÂ§ÃƒÂ£o noturna.",
  imagem: "sunsetboulevard.png",
  atracoes: [
    {
      id: "tower-of-terror",
      titulo: "The Twilight Zone Tower of Terror",
      subtitulo: "Sunset Boulevard",
      tipo: "Queda livre temÃƒÂ¡tica",
      tipoPerfil: ["radicais", "tematicas", "imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 55,
      filaAceitavel: 35,
      idadeRecomendada: "8+",
      turnoRecomendado: "tarde",
      descricao: "Hotel mal-assombrado com elevadores desgovernados, quedas inesperadas e clima de suspense. Indicado para quem gosta de sustos e frio na barriga; sente-se perto das janelas para uma vista incrÃƒÂ­vel.",
      icone: "Ã°Å¸ÂÂ¨",
      imagem: "tower-of-terror.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3557,
      longitude: -81.5619
    },
    {
      id: "rockn-roller-coaster",
      titulo: "Rock Ã¢â‚¬ËœnÃ¢â‚¬â„¢ Roller Coaster Starring Aerosmith",
      subtitulo: "Sunset Boulevard",
      tipo: "Montanha-russa no escuro",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 122,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 35,
      idadeRecomendada: "9+",
      turnoRecomendado: "tarde",
      descricao: "Montanha-russa veloz com trilha do Aerosmith, loopings e curvas no escuro. Guarde os objetos antes da largada e sente-se nos primeiros carros para sentir mais vento.",
      icone: "Ã°Å¸Å½Â¸",
      imagem: "rockn-roller.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3561,
      longitude: -81.5614
    },
    {
      id: "beauty-and-the-beast",
      titulo: "Beauty and the Beast Ã¢â‚¬â€œ Live on Stage",
      subtitulo: "Sunset Boulevard",
      tipo: "Show musical ao vivo",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Musical com figurinos e cenÃƒÂ¡rios encantadores, recriando a histÃƒÂ³ria da Bela e a Fera. Chegue 20 minutos antes para escolher bons lugares e aproveite para descansar ÃƒÂ  sombra.",
      icone: "Ã°Å¸Å’Â¹",
      imagem: "beauty-and-the-beast.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3550,
      longitude: -81.5620
    },
    {
      id: "encontro-com-bela",
      titulo: "Encontro com a Bela",
      subtitulo: "Sunset Boulevard",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "personagens", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Fotos com a Bela em traje dourado, prÃƒÂ³ximas ao teatro do musical. Leve algo para autÃƒÂ³grafo e pergunte sobre o baile para ter interaÃƒÂ§ÃƒÂµes ÃƒÂºnicas.",
      icone: "Ã°Å¸â€˜Â¸",
      imagem: "encontro-bela.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3549,
      longitude: -81.5621
    },
    {
      id: "encontro-com-mickey-sorcerer",
      titulo: "Encontro com Mickey Feiticeiro",
      subtitulo: "Sunset Boulevard",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "personagens", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "Fotos com o Mickey como feiticeiro do Fantasia, chapÃƒÂ©u azul estrelado e tÃƒÂºnica vermelha. PeÃƒÂ§a para ele fazer pose com a varinha mÃƒÂ¡gica para fotos mais divertidas.",
      icone: "Ã°Å¸Â§â„¢Ã¢â‚¬ÂÃ¢â„¢â€šÃ¯Â¸Â",
      imagem: "mickey-feiticeiro.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3553,
      longitude: -81.5623
    }
  ]
};
