export const SunsetBoulevard = {
  parque: "Hollywood Studios",
  regiao: "Sunset Boulevard",
  latitude: 28.3554,
  longitude: -81.5618,
  descricao: "Avenida com visual de cinema clÃ¡ssico que leva a atraÃ§Ãµes radicais, shows e encontros com personagens. Ã“tima para fotos ao pÃ´r do sol e para curtir a iluminaÃ§Ã£o noturna.",
  imagem: "sunsetboulevard.png",
  atracoes: [
    {
      id: "tower-of-terror",
      titulo: "The Twilight Zone Tower of Terror",
      subtitulo: "Sunset Boulevard",
      tipo: "Queda livre temÃ¡tica",
      tipoPerfil: ["radicais", "tematicas", "imersivas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 55,
      filaAceitavel: 35,
      idadeRecomendada: "8+",
      turnoRecomendado: "tarde",
      descricao: "Hotel mal-assombrado com elevadores desgovernados, quedas inesperadas e clima de suspense. Indicado para quem gosta de sustos e frio na barriga; sente-se perto das janelas para uma vista incrÃ­vel.",
      icone: "ðŸ¨",
      imagem: "tower-of-terror.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3557,
      longitude: -81.5619
    },
    {
      id: "rockn-roller-coaster",
      titulo: "Rock â€˜nâ€™ Roller Coaster Starring Aerosmith",
      subtitulo: "Sunset Boulevard",
      tipo: "Montanha-russa no escuro",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 122,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 35,
      idadeRecomendada: "9+",
      turnoRecomendado: "tarde",
      descricao: "Montanha-russa veloz com trilha do Aerosmith, loopings e curvas no escuro. Guarde os objetos antes da largada e sente-se nos primeiros carros para sentir mais vento.",
      icone: "ðŸŽ¸",
      imagem: "rockn-roller.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3561,
      longitude: -81.5614
    },
    {
      id: "beauty-and-the-beast",
      titulo: "Beauty and the Beast â€“ Live on Stage",
      subtitulo: "Sunset Boulevard",
      tipo: "Show musical ao vivo",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Musical com figurinos e cenÃ¡rios encantadores, recriando a histÃ³ria da Bela e a Fera. Chegue 20 minutos antes para escolher bons lugares e aproveite para descansar Ã  sombra.",
      icone: "ðŸŒ¹",
      imagem: "beauty-and-the-beast.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3550,
      longitude: -81.5620
    },
    {
      id: "encontro-com-bela",
      titulo: "Encontro com a Bela",
      subtitulo: "Sunset Boulevard",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "personagens", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "manha",
      descricao: "Fotos com a Bela em traje dourado, prÃ³ximas ao teatro do musical. Leve algo para autÃ³grafo e pergunte sobre o baile para ter interaÃ§Ãµes Ãºnicas.",
      icone: "ðŸ‘¸",
      imagem: "encontro-bela.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3549,
      longitude: -81.5621
    },
    {
      id: "encontro-com-mickey-sorcerer",
      titulo: "Encontro com Mickey Feiticeiro",
      subtitulo: "Sunset Boulevard",
      tipo: "Personagem para fotos",
      tipoPerfil: ["tematicas", "personagens", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      atracaoSemFila: true,
      turnoRecomendado: "noite",
      descricao: "Fotos com o Mickey como feiticeiro do Fantasia, chapÃ©u azul estrelado e tÃºnica vermelha. PeÃ§a para ele fazer pose com a varinha mÃ¡gica para fotos mais divertidas.",
      icone: "ðŸ§™â€â™‚ï¸",
      imagem: "mickey-feiticeiro.jpg",
      regiao: "Sunset Boulevard",
      parque: "Hollywood Studios",
      latitude: 28.3553,
      longitude: -81.5623
    }
  ]
};
