export const Tomorrowland = {
  parque: "Magic Kingdom",
  regiao: "Tomorrowland",
  latitude: 28.4196,
  longitude: -81.5773,
  descricao: "Área futurista com luzes vibrantes, simuladores, aventuras interativas e montanhas-russas no escuro. Ideal para fãs de tecnologia, ação e vistas panorâmicas, especialmente à noite com a iluminação especial.",
  imagem: "tomorrowland.png",
  atracoes: [
    {
      id: "space-mountain",
      titulo: "Space Mountain",
      subtitulo: "Tomorrowland",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 112,
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "manha",
      descricao: "Montanha-russa no escuro com curvas fechadas e atmosfera espacial clássica. Ótima para quem gosta de velocidade e adrenalina; sente-se nos primeiros carros para uma sensação mais intensa.",
      icone: "🚀",
      imagem: "space-mountain.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4198,
      longitude: -81.5771
    },
    {
      id: "buzz-lightyear",
      titulo: "Buzz Lightyear’s Space Ranger Spin",
      subtitulo: "Tomorrowland",
      tipo: "Interativa",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 30,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Atração interativa com canhões laser para derrotar Zurg e acumular pontos. Mire nos alvos iluminados para pontuação extra e desafie os amigos para ver quem faz mais pontos.",
      icone: "🔫",
      imagem: "buzz-lightyear.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4193,
      longitude: -81.5774
    },
    {
      id: "astro-orbiter",
      titulo: "Astro Orbiter",
      subtitulo: "Tomorrowland",
      tipo: "Brinquedo giratório aéreo",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 83,
      filaExpress: false,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Foguetes giratórios com vista panorâmica de Tomorrowland. Suba pela torre para embarcar e aproveite para tirar fotos incríveis, principalmente ao amanhecer ou entardecer.",
      icone: "🪐",
      imagem: "astro-orbiter.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4192,
      longitude: -81.5772
    },
    {
      id: "tomorrowland-speedway",
      titulo: "Tomorrowland Speedway",
      subtitulo: "Tomorrowland",
      tipo: "Pista de carrinhos",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 82,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Dirija carrinhos em pista temática futurista. Crianças adoram segurar o volante; mantenha aceleração constante para evitar paradas bruscas.",
      icone: "🏁",
      imagem: "tomorrowland-speedway.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4186,
      longitude: -81.5765
    },
    {
      id: "peoplemover",
      titulo: "Tomorrowland Transit Authority PeopleMover",
      subtitulo: "Tomorrowland",
      tipo: "Passeio panorâmico elevado",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Passeio elevado com vistas exclusivas de Tomorrowland e bastidores de atrações. Perfeito para descansar e aproveitar a paisagem sem pressa.",
      icone: "🚝",
      imagem: "peoplemover.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4195,
      longitude: -81.5770
    },
    {
      id: "carousel-of-progress",
      titulo: "Walt Disney’s Carousel of Progress",
      subtitulo: "Tomorrowland",
      tipo: "Show com animatrônicos",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Show clássico que apresenta a evolução tecnológica ao longo das décadas em cenário giratório. Ótima opção para dias quentes ou chuvosos, com ar-condicionado e assentos confortáveis.",
      icone: "🎡",
      imagem: "carousel-progress.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4197,
      longitude: -81.5775
    },
    {
      id: "monsters-inc-laugh-floor",
      titulo: "Monsters, Inc. Laugh Floor",
      subtitulo: "Tomorrowland",
      tipo: "Show interativo de comédia",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Show de comédia interativo com personagens de Monstros S.A. Envie piadas pelo aplicativo para tentar aparecer no telão durante a apresentação.",
      icone: "😂",
      imagem: "laugh-floor.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4190,
      longitude: -81.5773
    },

    // 👉 Adições
    {
      id: "tron-lightcycle-run",
      titulo: "TRON Lightcycle / Run",
      subtitulo: "Tomorrowland",
      tipo: "Montanha-russa lançada",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 122, // 48"
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "noite",
      descricao: "Coaster de alta velocidade com lançamento sob a canopy luminosa. Assentos tipo 'moto' (há assentos tradicionais na última fileira). Utilize Virtual Queue/Lightning Lane quando disponível.",
      icone: "💡",
      imagem: "tron.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4201,
      longitude: -81.5766
    },
    {
      id: "tomorrowland-launch-depot",
      titulo: "Tomorrowland Launch Depot",
      subtitulo: "Tomorrowland",
      tipo: "Loja temática (TRON)",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Loja oficial do TRON com roupas, pins e acessórios tecnológicos. Boa para fotos com vitrines iluminadas.",
      icone: "🛍️",
      imagem: "launch-depot.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4200,
      longitude: -81.5769
    },
    {
      id: "energy-bytes",
      titulo: "Energy Bytes",
      subtitulo: "Tomorrowland",
      tipo: "Lanchonete futurista (TRON)",
      tipoPerfil: ["refeicoes", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Quiosque de snacks inspirado no TRON (bites doces e salgados, bebidas temáticas). Perfeito para uma pausa rápida antes ou depois do TRON.",
      icone: "🥤",
      imagem: "energy-bytes.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4202,
      longitude: -81.5763
    }
  ]
};
