ï»¿export const Tomorrowland = {
  parque: "Magic Kingdom",
  regiao: "Tomorrowland",
  latitude: 28.4196,
  longitude: -81.5773,
  descricao: "ÃƒÂrea futurista com luzes vibrantes, simuladores, aventuras interativas e montanhas-russas no escuro. Ideal para fÃƒÂ£s de tecnologia, aÃƒÂ§ÃƒÂ£o e vistas panorÃƒÂ¢micas, especialmente ÃƒÂ  noite com a iluminaÃƒÂ§ÃƒÂ£o especial.",
  imagem: "tomorrowland.png",
  atracoes: [
    {
      id: "space-mountain",
      titulo: "Space Mountain",
      subtitulo: "Tomorrowland",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 112,
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "manha",
      descricao: "Montanha-russa no escuro com curvas fechadas e atmosfera espacial clÃƒÂ¡ssica. Ãƒâ€œtima para quem gosta de velocidade e adrenalina; sente-se nos primeiros carros para uma sensaÃƒÂ§ÃƒÂ£o mais intensa.",
      icone: "Ã°Å¸Å¡â‚¬",
      imagem: "space-mountain.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4198,
      longitude: -81.5771
    },
    {
      id: "buzz-lightyear",
      titulo: "Buzz LightyearÃ¢â‚¬â„¢s Space Ranger Spin",
      subtitulo: "Tomorrowland",
      tipo: "Interativa",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 30,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "AtraÃƒÂ§ÃƒÂ£o interativa com canhÃƒÂµes laser para derrotar Zurg e acumular pontos. Mire nos alvos iluminados para pontuaÃƒÂ§ÃƒÂ£o extra e desafie os amigos para ver quem faz mais pontos.",
      icone: "Ã°Å¸â€Â«",
      imagem: "buzz-lightyear.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4193,
      longitude: -81.5774
    },
    {
      id: "astro-orbiter",
      titulo: "Astro Orbiter",
      subtitulo: "Tomorrowland",
      tipo: "Brinquedo giratÃƒÂ³rio aÃƒÂ©reo",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 83,
      filaExpress: false,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Foguetes giratÃƒÂ³rios com vista panorÃƒÂ¢mica de Tomorrowland. Suba pela torre para embarcar e aproveite para tirar fotos incrÃƒÂ­veis, principalmente ao amanhecer ou entardecer.",
      icone: "Ã°Å¸ÂªÂ",
      imagem: "astro-orbiter.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4192,
      longitude: -81.5772
    },
    {
      id: "tomorrowland-speedway",
      titulo: "Tomorrowland Speedway",
      subtitulo: "Tomorrowland",
      tipo: "Pista de carrinhos",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 82,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Dirija carrinhos em pista temÃƒÂ¡tica futurista. CrianÃƒÂ§as adoram segurar o volante; mantenha aceleraÃƒÂ§ÃƒÂ£o constante para evitar paradas bruscas.",
      icone: "Ã°Å¸ÂÂ",
      imagem: "tomorrowland-speedway.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4186,
      longitude: -81.5765
    },
    {
      id: "peoplemover",
      titulo: "Tomorrowland Transit Authority PeopleMover",
      subtitulo: "Tomorrowland",
      tipo: "Passeio panorÃƒÂ¢mico elevado",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Passeio elevado com vistas exclusivas de Tomorrowland e bastidores de atraÃƒÂ§ÃƒÂµes. Perfeito para descansar e aproveitar a paisagem sem pressa.",
      icone: "Ã°Å¸Å¡Â",
      imagem: "peoplemover.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4195,
      longitude: -81.5770
    },
    {
      id: "carousel-of-progress",
      titulo: "Walt DisneyÃ¢â‚¬â„¢s Carousel of Progress",
      subtitulo: "Tomorrowland",
      tipo: "Show com animatrÃƒÂ´nicos",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Show clÃƒÂ¡ssico que apresenta a evoluÃƒÂ§ÃƒÂ£o tecnolÃƒÂ³gica ao longo das dÃƒÂ©cadas em cenÃƒÂ¡rio giratÃƒÂ³rio. Ãƒâ€œtima opÃƒÂ§ÃƒÂ£o para dias quentes ou chuvosos, com ar-condicionado e assentos confortÃƒÂ¡veis.",
      icone: "Ã°Å¸Å½Â¡",
      imagem: "carousel-progress.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4197,
      longitude: -81.5775
    },
    {
      id: "monsters-inc-laugh-floor",
      titulo: "Monsters, Inc. Laugh Floor",
      subtitulo: "Tomorrowland",
      tipo: "Show interativo de comÃƒÂ©dia",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Show de comÃƒÂ©dia interativo com personagens de Monstros S.A. Envie piadas pelo aplicativo para tentar aparecer no telÃƒÂ£o durante a apresentaÃƒÂ§ÃƒÂ£o.",
      icone: "Ã°Å¸Ëœâ€š",
      imagem: "laugh-floor.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4190,
      longitude: -81.5773
    },

    // Ã°Å¸â€˜â€° AdiÃƒÂ§ÃƒÂµes
    {
      id: "tron-lightcycle-run",
      titulo: "TRON Lightcycle / Run",
      subtitulo: "Tomorrowland",
      tipo: "Montanha-russa lanÃƒÂ§ada",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 122, // 48"
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "noite",
      descricao: "Coaster de alta velocidade com lanÃƒÂ§amento sob a canopy luminosa. Assentos tipo 'moto' (hÃƒÂ¡ assentos tradicionais na ÃƒÂºltima fileira). Utilize Virtual Queue/Lightning Lane quando disponÃƒÂ­vel.",
      icone: "Ã°Å¸â€™Â¡",
      imagem: "tron.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4201,
      longitude: -81.5766
    },
    {
      id: "tomorrowland-launch-depot",
      titulo: "Tomorrowland Launch Depot",
      subtitulo: "Tomorrowland",
      tipo: "Loja temÃƒÂ¡tica (TRON)",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Loja oficial do TRON com roupas, pins e acessÃƒÂ³rios tecnolÃƒÂ³gicos. Boa para fotos com vitrines iluminadas.",
      icone: "Ã°Å¸â€ºÂÃ¯Â¸Â",
      imagem: "launch-depot.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4200,
      longitude: -81.5769
    },
    {
      id: "energy-bytes",
      titulo: "Energy Bytes",
      subtitulo: "Tomorrowland",
      tipo: "Lanchonete futurista (TRON)",
      tipoPerfil: ["refeicoes", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Quiosque de snacks inspirado no TRON (bites doces e salgados, bebidas temÃƒÂ¡ticas). Perfeito para uma pausa rÃƒÂ¡pida antes ou depois do TRON.",
      icone: "Ã°Å¸Â¥Â¤",
      imagem: "energy-bytes.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4202,
      longitude: -81.5763
    }
  ]
};
