export const Tomorrowland = {
  parque: "Magic Kingdom",
  regiao: "Tomorrowland",
  latitude: 28.4196,
  longitude: -81.5773,
  descricao: "Ãrea futurista com luzes vibrantes, simuladores, aventuras interativas e montanhas-russas no escuro. Ideal para fÃ£s de tecnologia, aÃ§Ã£o e vistas panorÃ¢micas, especialmente Ã  noite com a iluminaÃ§Ã£o especial.",
  imagem: "tomorrowland.png",
  atracoes: [
    {
      id: "space-mountain",
      titulo: "Space Mountain",
      subtitulo: "Tomorrowland",
      tipo: "Montanha-russa",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 112,
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "manha",
      descricao: "Montanha-russa no escuro com curvas fechadas e atmosfera espacial clÃ¡ssica. Ã“tima para quem gosta de velocidade e adrenalina; sente-se nos primeiros carros para uma sensaÃ§Ã£o mais intensa.",
      icone: "ðŸš€",
      imagem: "space-mountain.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4198,
      longitude: -81.5771
    },
    {
      id: "buzz-lightyear",
      titulo: "Buzz Lightyearâ€™s Space Ranger Spin",
      subtitulo: "Tomorrowland",
      tipo: "Interativa",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 30,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "AtraÃ§Ã£o interativa com canhÃµes laser para derrotar Zurg e acumular pontos. Mire nos alvos iluminados para pontuaÃ§Ã£o extra e desafie os amigos para ver quem faz mais pontos.",
      icone: "ðŸ”«",
      imagem: "buzz-lightyear.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4193,
      longitude: -81.5774
    },
    {
      id: "astro-orbiter",
      titulo: "Astro Orbiter",
      subtitulo: "Tomorrowland",
      tipo: "Brinquedo giratÃ³rio aÃ©reo",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 83,
      filaExpress: false,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Foguetes giratÃ³rios com vista panorÃ¢mica de Tomorrowland. Suba pela torre para embarcar e aproveite para tirar fotos incrÃ­veis, principalmente ao amanhecer ou entardecer.",
      icone: "ðŸª",
      imagem: "astro-orbiter.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4192,
      longitude: -81.5772
    },
    {
      id: "tomorrowland-speedway",
      titulo: "Tomorrowland Speedway",
      subtitulo: "Tomorrowland",
      tipo: "Pista de carrinhos",
      tipoPerfil: ["familiares", "interativas", "tematicas"],
      alturaMinima: 82,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Dirija carrinhos em pista temÃ¡tica futurista. CrianÃ§as adoram segurar o volante; mantenha aceleraÃ§Ã£o constante para evitar paradas bruscas.",
      icone: "ðŸ",
      imagem: "tomorrowland-speedway.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4186,
      longitude: -81.5765
    },
    {
      id: "peoplemover",
      titulo: "Tomorrowland Transit Authority PeopleMover",
      subtitulo: "Tomorrowland",
      tipo: "Passeio panorÃ¢mico elevado",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 10,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Passeio elevado com vistas exclusivas de Tomorrowland e bastidores de atraÃ§Ãµes. Perfeito para descansar e aproveitar a paisagem sem pressa.",
      icone: "ðŸš",
      imagem: "peoplemover.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4195,
      longitude: -81.5770
    },
    {
      id: "carousel-of-progress",
      titulo: "Walt Disneyâ€™s Carousel of Progress",
      subtitulo: "Tomorrowland",
      tipo: "Show com animatrÃ´nicos",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Show clÃ¡ssico que apresenta a evoluÃ§Ã£o tecnolÃ³gica ao longo das dÃ©cadas em cenÃ¡rio giratÃ³rio. Ã“tima opÃ§Ã£o para dias quentes ou chuvosos, com ar-condicionado e assentos confortÃ¡veis.",
      icone: "ðŸŽ¡",
      imagem: "carousel-progress.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4197,
      longitude: -81.5775
    },
    {
      id: "monsters-inc-laugh-floor",
      titulo: "Monsters, Inc. Laugh Floor",
      subtitulo: "Tomorrowland",
      tipo: "Show interativo de comÃ©dia",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Show de comÃ©dia interativo com personagens de Monstros S.A. Envie piadas pelo aplicativo para tentar aparecer no telÃ£o durante a apresentaÃ§Ã£o.",
      icone: "ðŸ˜‚",
      imagem: "laugh-floor.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4190,
      longitude: -81.5773
    },

    // ðŸ‘‰ AdiÃ§Ãµes
    {
      id: "tron-lightcycle-run",
      titulo: "TRON Lightcycle / Run",
      subtitulo: "Tomorrowland",
      tipo: "Montanha-russa lanÃ§ada",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 122, // 48"
      filaExpress: true,
      tempoMedioFila: 70,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "noite",
      descricao: "Coaster de alta velocidade com lanÃ§amento sob a canopy luminosa. Assentos tipo 'moto' (hÃ¡ assentos tradicionais na Ãºltima fileira). Utilize Virtual Queue/Lightning Lane quando disponÃ­vel.",
      icone: "ðŸ’¡",
      imagem: "tron.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4201,
      longitude: -81.5766
    },
    {
      id: "tomorrowland-launch-depot",
      titulo: "Tomorrowland Launch Depot",
      subtitulo: "Tomorrowland",
      tipo: "Loja temÃ¡tica (TRON)",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Loja oficial do TRON com roupas, pins e acessÃ³rios tecnolÃ³gicos. Boa para fotos com vitrines iluminadas.",
      icone: "ðŸ›ï¸",
      imagem: "launch-depot.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4200,
      longitude: -81.5769
    },
    {
      id: "energy-bytes",
      titulo: "Energy Bytes",
      subtitulo: "Tomorrowland",
      tipo: "Lanchonete futurista (TRON)",
      tipoPerfil: ["refeicoes", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Quiosque de snacks inspirado no TRON (bites doces e salgados, bebidas temÃ¡ticas). Perfeito para uma pausa rÃ¡pida antes ou depois do TRON.",
      icone: "ðŸ¥¤",
      imagem: "energy-bytes.jpg",
      regiao: "Tomorrowland",
      parque: "Magic Kingdom",
      latitude: 28.4202,
      longitude: -81.5763
    }
  ]
};
