export const ToyStoryLand = {
  parque: "Hollywood Studios",
  regiao: "Toy Story Land",
  latitude: 28.3558,
  longitude: -81.5904,
  descricao: "Ãrea onde vocÃª se sente do tamanho de um brinquedo no quintal de Andy. Com cores vibrantes, trilhos gigantes e brinquedos interativos, Ã© puro charme e nostalgia para todas as idades.",
  imagem: "toystoryland.png",
  atracoes: [
    {
      id: "slinky-dog-dash",
      titulo: "Slinky Dog Dash",
      subtitulo: "Toy Story Land",
      tipo: "Montanha-russa familiar",
      tipoPerfil: ["radicais", "familiares", "tematicas"],
      alturaMinima: 97,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "5+",
      turnoRecomendado: "manha",
      descricao: "Montanha-russa divertida com curvas suaves, subidas e descidas no quintal de Andy. EmoÃ§Ã£o moderada, vento no rosto e visual colorido; sente-se nos Ãºltimos vagÃµes para mais velocidade.",
      icone: "ðŸ¶",
      imagem: "slinky-dog-dash.jpg",
      regiao: "Toy Story Land",
      parque: "Hollywood Studios",
      latitude: 28.3560,
      longitude: -81.5906
    },
    {
      id: "alien-swirling-saucers",
      titulo: "Alien Swirling Saucers",
      subtitulo: "Toy Story Land",
      tipo: "Brinquedo giratÃ³rio",
      tipoPerfil: ["familiares", "tematicas", "interativas"],
      alturaMinima: 81,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Gire com os alienÃ­genas verdes em discos ao som de mÃºsica galÃ¡ctica e luzes coloridas. DiversÃ£o suave, sem sustos, ideal para crianÃ§as pequenas; cada rodada tem trilha diferente.",
      icone: "ðŸ‘½",
      imagem: "alien-saucers.jpg",
      regiao: "Toy Story Land",
      parque: "Hollywood Studios",
      latitude: 28.3556,
      longitude: -81.5902
    },
    {
      id: "toy-story-mania",
      titulo: "Toy Story Mania!",
      subtitulo: "Toy Story Land",
      tipo: "Jogo interativo 3D",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 40,
      filaAceitavel: 30,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Jogo interativo 3D com mini-desafios de tiro ao alvo no universo Toy Story. Mire nos alvos que mudam de cor para pontuar mais e desafie os amigos durante o passeio.",
      icone: "ðŸŽ¯",
      imagem: "toy-story-mania.jpg",
      regiao: "Toy Story Land",
      parque: "Hollywood Studios",
      latitude: 28.3557,
      longitude: -81.5905
    },
    {
      id: "personagens-toy-story",
      titulo: "Encontro com Personagens",
      subtitulo: "Toy Story Land",
      tipo: "Personagem para fotos",
      tipoPerfil: ["personagens", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Fotos e autÃ³grafos com Woody, Jessie e Buzz Lightyear em cenÃ¡rios coloridos. Leve algo especial para assinar e peÃ§a poses criativas para fotos divertidas.",
      icone: "ðŸ¤ ",
      imagem: "encontro-personagens.jpg",
      regiao: "Toy Story Land",
      parque: "Hollywood Studios",
      latitude: 28.3559,
      longitude: -81.5907
    },
    {
      id: "roundup-rodeo-bbq",
      titulo: "Roundup Rodeo BBQ",
      subtitulo: "Toy Story Land",
      tipo: "Restaurante temÃ¡tico",
      tipoPerfil: ["refeicoes", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Restaurante com decoraÃ§Ã£o temÃ¡tica e pratos tÃ­picos de churrasco americano servidos Ã  vontade. Reserve com antecedÃªncia e explore os cenÃ¡rios para fotos criativas.",
      icone: "ðŸ—",
      imagem: "roundup-rodeo.jpg",
      regiao: "Toy Story Land",
      parque: "Hollywood Studios",
      latitude: 28.3555,
      longitude: -81.5908
    }
  ]
};
