export const WorldShowcase = {
  parque: "EPCOT",
  regiao: "World Showcase",
  latitude: 28.3691,
  longitude: -81.5485,
  descricao: "Ãrea com 11 pavilhÃµes representando paÃ­ses, oferecendo culinÃ¡ria tÃ­pica, cultura, lojas, filmes, shows e atraÃ§Ãµes imersivas. Ideal para explorar com calma e vivenciar diferentes culturas em um Ãºnico passeio.",
  imagem: "worldshowcase.png",
  atracoes: [
    {
      id: "frozen-ever-after",
      titulo: "Frozen Ever After",
      subtitulo: "World Showcase",
      tipo: "Passeio de barco temÃ¡tico",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 65,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Passeio de barco em Arendelle com personagens e mÃºsicas de Frozen, repleto de efeitos especiais e animatrÃ´nicos realistas. Leves quedas e clima gelado; indicado para todas as idades e fÃ£s da franquia.",
      icone: "â„ï¸",
      imagem: "frozen.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3725,
      longitude: -81.5476
    },
    {
      id: "gran-fiesta-tour",
      titulo: "Gran Fiesta Tour Starring The Three Caballeros",
      subtitulo: "World Showcase",
      tipo: "Passeio de barco",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Passeio tranquilo de barco pelo pavilhÃ£o do MÃ©xico com Pato Donald e os TrÃªs Caballeros, mÃºsicas alegres e cenÃ¡rios coloridos. Ã“timo para todas as idades e para descansar das filas.",
      icone: "ðŸ›¶",
      imagem: "gran-fiesta-tour.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3681,
      longitude: -81.5502
    },
    {
      id: "impressions-de-france",
      titulo: "Impressions de France",
      subtitulo: "World Showcase",
      tipo: "Filme panorÃ¢mico",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Filme panorÃ¢mico com belas paisagens, cultura e mÃºsica francesa, exibido no pavilhÃ£o da FranÃ§a. Relaxante e inspirador; chegue cedo para pegar assentos centrais.",
      icone: "ðŸ‡«ðŸ‡·",
      imagem: "impressions-france.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3703,
      longitude: -81.5500
    },
    {
      id: "remys-ratatouille-adventure",
      titulo: "Remyâ€™s Ratatouille Adventure",
      subtitulo: "PavilhÃ£o da FranÃ§a",
      tipo: "Dark ride 3D",
      tipoPerfil: ["familiares", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Aventura 3D onde vocÃª encolhe ao tamanho de um rato e passeia pela cozinha do Gusteau ao lado de Remy. Cheio de cheiros, Ã¡gua e efeitos de calor, Ã© divertido para toda a famÃ­lia.",
      icone: "ðŸ­",
      imagem: "ratatouille.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3711,
      longitude: -81.5497
    },
    {
      id: "beauty-and-the-beast-sing-along",
      titulo: "Beauty and the Beast Sing-Along",
      subtitulo: "World Showcase",
      tipo: "Filme musical interativo",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "SessÃ£o para cantar junto com as mÃºsicas de A Bela e a Fera, alternada com Impressions de France. Leve e divertida; sente-se na frente para envolver mais as crianÃ§as.",
      icone: "ðŸŽ¶",
      imagem: "beauty-sing-along.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3703,
      longitude: -81.5500
    },
    {
      id: "reflections-of-china",
      titulo: "Reflections of China",
      subtitulo: "World Showcase",
      tipo: "Filme 360Â°",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Filme em 360Â° com paisagens e cultura tradicional chinesa, exibido em sala circular de pÃ©. Imersivo e educativo; procure ficar centralizado para melhor visÃ£o.",
      icone: "ðŸ¯",
      imagem: "reflections-china.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3707,
      longitude: -81.5443
    },
    {
      id: "canada-far-and-wide",
      titulo: "Canada Far and Wide",
      subtitulo: "World Showcase",
      tipo: "Filme 360Â°",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Filme panorÃ¢mico sobre a natureza, cidades e cultura do CanadÃ¡, com trilha envolvente. Imagens vibrantes e ambiente fresco; fique no centro da sala para melhor experiÃªncia.",
      icone: "ðŸ‡¨ðŸ‡¦",
      imagem: "canada-far-and-wide.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3716,
      longitude: -81.5526
    },
    {
      id: "the-american-adventure",
      titulo: "The American Adventure",
      subtitulo: "World Showcase",
      tipo: "Show com animatrÃ´nicos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Show com animatrÃ´nicos narrando a histÃ³ria dos EUA, com efeitos especiais e trilha Ã©pica. Inspirador e educativo; sente-se no centro para melhor visÃ£o do palco.",
      icone: "ðŸ—½",
      imagem: "american-adventure.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3699,
      longitude: -81.5487
    }
  ]
};
