ï»¿export const WorldShowcase = {
  parque: "EPCOT",
  regiao: "World Showcase",
  latitude: 28.3691,
  longitude: -81.5485,
  descricao: "ÃƒÂrea com 11 pavilhÃƒÂµes representando paÃƒÂ­ses, oferecendo culinÃƒÂ¡ria tÃƒÂ­pica, cultura, lojas, filmes, shows e atraÃƒÂ§ÃƒÂµes imersivas. Ideal para explorar com calma e vivenciar diferentes culturas em um ÃƒÂºnico passeio.",
  imagem: "worldshowcase.png",
  atracoes: [
    {
      id: "frozen-ever-after",
      titulo: "Frozen Ever After",
      subtitulo: "World Showcase",
      tipo: "Passeio de barco temÃƒÂ¡tico",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 65,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Passeio de barco em Arendelle com personagens e mÃƒÂºsicas de Frozen, repleto de efeitos especiais e animatrÃƒÂ´nicos realistas. Leves quedas e clima gelado; indicado para todas as idades e fÃƒÂ£s da franquia.",
      icone: "Ã¢Ââ€žÃ¯Â¸Â",
      imagem: "frozen.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3725,
      longitude: -81.5476
    },
    {
      id: "gran-fiesta-tour",
      titulo: "Gran Fiesta Tour Starring The Three Caballeros",
      subtitulo: "World Showcase",
      tipo: "Passeio de barco",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Passeio tranquilo de barco pelo pavilhÃƒÂ£o do MÃƒÂ©xico com Pato Donald e os TrÃƒÂªs Caballeros, mÃƒÂºsicas alegres e cenÃƒÂ¡rios coloridos. Ãƒâ€œtimo para todas as idades e para descansar das filas.",
      icone: "Ã°Å¸â€ºÂ¶",
      imagem: "gran-fiesta-tour.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3681,
      longitude: -81.5502
    },
    {
      id: "impressions-de-france",
      titulo: "Impressions de France",
      subtitulo: "World Showcase",
      tipo: "Filme panorÃƒÂ¢mico",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Filme panorÃƒÂ¢mico com belas paisagens, cultura e mÃƒÂºsica francesa, exibido no pavilhÃƒÂ£o da FranÃƒÂ§a. Relaxante e inspirador; chegue cedo para pegar assentos centrais.",
      icone: "Ã°Å¸â€¡Â«Ã°Å¸â€¡Â·",
      imagem: "impressions-france.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3703,
      longitude: -81.5500
    },
    {
      id: "remys-ratatouille-adventure",
      titulo: "RemyÃ¢â‚¬â„¢s Ratatouille Adventure",
      subtitulo: "PavilhÃƒÂ£o da FranÃƒÂ§a",
      tipo: "Dark ride 3D",
      tipoPerfil: ["familiares", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Aventura 3D onde vocÃƒÂª encolhe ao tamanho de um rato e passeia pela cozinha do Gusteau ao lado de Remy. Cheio de cheiros, ÃƒÂ¡gua e efeitos de calor, ÃƒÂ© divertido para toda a famÃƒÂ­lia.",
      icone: "Ã°Å¸ÂÂ­",
      imagem: "ratatouille.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3711,
      longitude: -81.5497
    },
    {
      id: "beauty-and-the-beast-sing-along",
      titulo: "Beauty and the Beast Sing-Along",
      subtitulo: "World Showcase",
      tipo: "Filme musical interativo",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "SessÃƒÂ£o para cantar junto com as mÃƒÂºsicas de A Bela e a Fera, alternada com Impressions de France. Leve e divertida; sente-se na frente para envolver mais as crianÃƒÂ§as.",
      icone: "Ã°Å¸Å½Â¶",
      imagem: "beauty-sing-along.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3703,
      longitude: -81.5500
    },
    {
      id: "reflections-of-china",
      titulo: "Reflections of China",
      subtitulo: "World Showcase",
      tipo: "Filme 360Ã‚Â°",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Filme em 360Ã‚Â° com paisagens e cultura tradicional chinesa, exibido em sala circular de pÃƒÂ©. Imersivo e educativo; procure ficar centralizado para melhor visÃƒÂ£o.",
      icone: "Ã°Å¸ÂÂ¯",
      imagem: "reflections-china.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3707,
      longitude: -81.5443
    },
    {
      id: "canada-far-and-wide",
      titulo: "Canada Far and Wide",
      subtitulo: "World Showcase",
      tipo: "Filme 360Ã‚Â°",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Filme panorÃƒÂ¢mico sobre a natureza, cidades e cultura do CanadÃƒÂ¡, com trilha envolvente. Imagens vibrantes e ambiente fresco; fique no centro da sala para melhor experiÃƒÂªncia.",
      icone: "Ã°Å¸â€¡Â¨Ã°Å¸â€¡Â¦",
      imagem: "canada-far-and-wide.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3716,
      longitude: -81.5526
    },
    {
      id: "the-american-adventure",
      titulo: "The American Adventure",
      subtitulo: "World Showcase",
      tipo: "Show com animatrÃƒÂ´nicos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Show com animatrÃƒÂ´nicos narrando a histÃƒÂ³ria dos EUA, com efeitos especiais e trilha ÃƒÂ©pica. Inspirador e educativo; sente-se no centro para melhor visÃƒÂ£o do palco.",
      icone: "Ã°Å¸â€”Â½",
      imagem: "american-adventure.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3699,
      longitude: -81.5487
    }
  ]
};
