export const WorldDiscovery = {
  parque: "EPCOT",
  regiao: "World Discovery",
  latitude: 28.3742,
  longitude: -81.5472,
  descricao: "Ãrea dedicada Ã  ciÃªncia, espaÃ§o e inovaÃ§Ã£o, reunindo algumas das atraÃ§Ãµes mais radicais e tecnolÃ³gicas do EPCOT. Combina experiÃªncias futuristas e interativas que agradam desde exploradores curiosos atÃ© amantes de adrenalina.",
  imagem: "worlddiscovery.png",
  atracoes: [
    {
      id: "guardians-of-the-galaxy-cosmic-rewind",
      titulo: "Guardians of the Galaxy: Cosmic Rewind",
      subtitulo: "World Discovery",
      tipo: "Montanha-russa indoor com rotaÃ§Ã£o",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 107,
      filaExpress: false,
      tempoMedioFila: 75,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "tarde",
      descricao: "Montanha-russa inovadora com rotaÃ§Ã£o dos carros e trilha sonora dos GuardiÃµes da GalÃ¡xia. Alta adrenalina com curvas inesperadas, giros e mÃºsicas que mudam a cada passeio; aproveite a fila tematizada cheia de detalhes.",
      icone: "ðŸŒŒ",
      imagem: "cosmic-rewind.jpg",
      regiao: "World Discovery",
      parque: "EPCOT",
      latitude: 28.3743,
      longitude: -81.5468
    },
    {
      id: "test-track",
      titulo: "Test Track",
      subtitulo: "World Discovery",
      tipo: "Simulador de carro de alta velocidade",
      tipoPerfil: ["radicais", "interativas", "familiares"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "6+",
      turnoRecomendado: "manha",
      descricao: "Projete seu prÃ³prio carro e teste aceleraÃ§Ã£o, curvas e frenagens em pista real, finalizando com alta velocidade ao ar livre. Personalize bem o veÃ­culo antes de entrar e sente-se nas laterais para sentir mais o vento.",
      icone: "ðŸŽï¸",
      imagem: "test-track.jpg",
      regiao: "World Discovery",
      parque: "EPCOT",
      latitude: 28.3735,
      longitude: -81.5477
    },
    {
      id: "mission-space",
      titulo: "Mission: SPACE",
      subtitulo: "World Discovery",
      tipo: "Simulador espacial com forÃ§a G",
      tipoPerfil: ["imersivas", "radicais", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 30,
      idadeRecomendada: "8+",
      turnoRecomendado: "tarde",
      descricao: "SimulaÃ§Ã£o de lanÃ§amento ao espaÃ§o com duas intensidades: Verde (leve) e Laranja (intensa, com forÃ§a G). A versÃ£o laranja Ã© mais radical e pode causar tontura; a verde Ã© suave e indicada para todos. Respire fundo e siga as instruÃ§Ãµes para aproveitar melhor.",
      icone: "ðŸš€",
      imagem: "mission-space.jpg",
      regiao: "World Discovery",
      parque: "EPCOT",
      latitude: 28.3742,
      longitude: -81.5473
    },
    {
      id: "advanced-training-lab",
      titulo: "Advanced Training Lab",
      subtitulo: "World Discovery",
      tipo: "EspaÃ§o interativo pÃ³s-ride",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Ãrea interativa com jogos e simuladores de tema espacial, localizada na saÃ­da do Mission: SPACE. Ideal para brincar em grupo e aproveitar o ar-condicionado; experimente o simulador de astronauta e explore todos os desafios disponÃ­veis.",
      icone: "ðŸ§ª",
      imagem: "advanced-training-lab.jpg",
      regiao: "World Discovery",
      parque: "EPCOT",
      latitude: 28.3743,
      longitude: -81.5471
    }
  ]
};
