ï»¿export const WorldDiscovery = {
  parque: "EPCOT",
  regiao: "World Discovery",
  latitude: 28.3742,
  longitude: -81.5472,
  descricao: "ÃƒÂrea dedicada ÃƒÂ  ciÃƒÂªncia, espaÃƒÂ§o e inovaÃƒÂ§ÃƒÂ£o, reunindo algumas das atraÃƒÂ§ÃƒÂµes mais radicais e tecnolÃƒÂ³gicas do EPCOT. Combina experiÃƒÂªncias futuristas e interativas que agradam desde exploradores curiosos atÃƒÂ© amantes de adrenalina.",
  imagem: "worlddiscovery.png",
  atracoes: [
    {
      id: "guardians-of-the-galaxy-cosmic-rewind",
      titulo: "Guardians of the Galaxy: Cosmic Rewind",
      subtitulo: "World Discovery",
      tipo: "Montanha-russa indoor com rotaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["radicais", "imersivas", "tematicas"],
      alturaMinima: 107,
      filaExpress: false,
      tempoMedioFila: 75,
      filaAceitavel: 45,
      idadeRecomendada: "7+",
      turnoRecomendado: "tarde",
      descricao: "Montanha-russa inovadora com rotaÃƒÂ§ÃƒÂ£o dos carros e trilha sonora dos GuardiÃƒÂµes da GalÃƒÂ¡xia. Alta adrenalina com curvas inesperadas, giros e mÃƒÂºsicas que mudam a cada passeio; aproveite a fila tematizada cheia de detalhes.",
      icone: "Ã°Å¸Å’Å’",
      imagem: "cosmic-rewind.jpg",
      regiao: "World Discovery",
      parque: "EPCOT",
      latitude: 28.3743,
      longitude: -81.5468
    },
    {
      id: "test-track",
      titulo: "Test Track",
      subtitulo: "World Discovery",
      tipo: "Simulador de carro de alta velocidade",
      tipoPerfil: ["radicais", "interativas", "familiares"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 60,
      filaAceitavel: 40,
      idadeRecomendada: "6+",
      turnoRecomendado: "manha",
      descricao: "Projete seu prÃƒÂ³prio carro e teste aceleraÃƒÂ§ÃƒÂ£o, curvas e frenagens em pista real, finalizando com alta velocidade ao ar livre. Personalize bem o veÃƒÂ­culo antes de entrar e sente-se nas laterais para sentir mais o vento.",
      icone: "Ã°Å¸ÂÅ½Ã¯Â¸Â",
      imagem: "test-track.jpg",
      regiao: "World Discovery",
      parque: "EPCOT",
      latitude: 28.3735,
      longitude: -81.5477
    },
    {
      id: "mission-space",
      titulo: "Mission: SPACE",
      subtitulo: "World Discovery",
      tipo: "Simulador espacial com forÃƒÂ§a G",
      tipoPerfil: ["imersivas", "radicais", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 35,
      filaAceitavel: 30,
      idadeRecomendada: "8+",
      turnoRecomendado: "tarde",
      descricao: "SimulaÃƒÂ§ÃƒÂ£o de lanÃƒÂ§amento ao espaÃƒÂ§o com duas intensidades: Verde (leve) e Laranja (intensa, com forÃƒÂ§a G). A versÃƒÂ£o laranja ÃƒÂ© mais radical e pode causar tontura; a verde ÃƒÂ© suave e indicada para todos. Respire fundo e siga as instruÃƒÂ§ÃƒÂµes para aproveitar melhor.",
      icone: "Ã°Å¸Å¡â‚¬",
      imagem: "mission-space.jpg",
      regiao: "World Discovery",
      parque: "EPCOT",
      latitude: 28.3742,
      longitude: -81.5473
    },
    {
      id: "advanced-training-lab",
      titulo: "Advanced Training Lab",
      subtitulo: "World Discovery",
      tipo: "EspaÃƒÂ§o interativo pÃƒÂ³s-ride",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "ÃƒÂrea interativa com jogos e simuladores de tema espacial, localizada na saÃƒÂ­da do Mission: SPACE. Ideal para brincar em grupo e aproveitar o ar-condicionado; experimente o simulador de astronauta e explore todos os desafios disponÃƒÂ­veis.",
      icone: "Ã°Å¸Â§Âª",
      imagem: "advanced-training-lab.jpg",
      regiao: "World Discovery",
      parque: "EPCOT",
      latitude: 28.3743,
      longitude: -81.5471
    }
  ]
};
