export const WorldShowcase = {
  parque: "EPCOT",
  regiao: "World Showcase",
  latitude: 28.3691,
  longitude: -81.5485,
  descricao: "Área com 11 pavilhões representando países, oferecendo culinária típica, cultura, lojas, filmes, shows e atrações imersivas. Ideal para explorar com calma e vivenciar diferentes culturas em um único passeio.",
  imagem: "worldshowcase.png",
  atracoes: [
    {
      id: "frozen-ever-after",
      titulo: "Frozen Ever After",
      subtitulo: "World Showcase",
      tipo: "Passeio de barco temático",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 65,
      filaAceitavel: 40,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Passeio de barco em Arendelle com personagens e músicas de Frozen, repleto de efeitos especiais e animatrônicos realistas. Leves quedas e clima gelado; indicado para todas as idades e fãs da franquia.",
      icone: "❄️",
      imagem: "frozen.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3725,
      longitude: -81.5476
    },
    {
      id: "gran-fiesta-tour",
      titulo: "Gran Fiesta Tour Starring The Three Caballeros",
      subtitulo: "World Showcase",
      tipo: "Passeio de barco",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 20,
      filaAceitavel: 15,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Passeio tranquilo de barco pelo pavilhão do México com Pato Donald e os Três Caballeros, músicas alegres e cenários coloridos. Ótimo para todas as idades e para descansar das filas.",
      icone: "🛶",
      imagem: "gran-fiesta-tour.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3681,
      longitude: -81.5502
    },
    {
      id: "impressions-de-france",
      titulo: "Impressions de France",
      subtitulo: "World Showcase",
      tipo: "Filme panorâmico",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Filme panorâmico com belas paisagens, cultura e música francesa, exibido no pavilhão da França. Relaxante e inspirador; chegue cedo para pegar assentos centrais.",
      icone: "🇫🇷",
      imagem: "impressions-france.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3703,
      longitude: -81.5500
    },
    {
      id: "remys-ratatouille-adventure",
      titulo: "Remy’s Ratatouille Adventure",
      subtitulo: "Pavilhão da França",
      tipo: "Dark ride 3D",
      tipoPerfil: ["familiares", "imersivas", "tematicas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 45,
      filaAceitavel: 35,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Aventura 3D onde você encolhe ao tamanho de um rato e passeia pela cozinha do Gusteau ao lado de Remy. Cheio de cheiros, água e efeitos de calor, é divertido para toda a família.",
      icone: "🐭",
      imagem: "ratatouille.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3711,
      longitude: -81.5497
    },
    {
      id: "beauty-and-the-beast-sing-along",
      titulo: "Beauty and the Beast Sing-Along",
      subtitulo: "World Showcase",
      tipo: "Filme musical interativo",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Sessão para cantar junto com as músicas de A Bela e a Fera, alternada com Impressions de France. Leve e divertida; sente-se na frente para envolver mais as crianças.",
      icone: "🎶",
      imagem: "beauty-sing-along.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3703,
      longitude: -81.5500
    },
    {
      id: "reflections-of-china",
      titulo: "Reflections of China",
      subtitulo: "World Showcase",
      tipo: "Filme 360°",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Filme em 360° com paisagens e cultura tradicional chinesa, exibido em sala circular de pé. Imersivo e educativo; procure ficar centralizado para melhor visão.",
      icone: "🏯",
      imagem: "reflections-china.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3707,
      longitude: -81.5443
    },
    {
      id: "canada-far-and-wide",
      titulo: "Canada Far and Wide",
      subtitulo: "World Showcase",
      tipo: "Filme 360°",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Filme panorâmico sobre a natureza, cidades e cultura do Canadá, com trilha envolvente. Imagens vibrantes e ambiente fresco; fique no centro da sala para melhor experiência.",
      icone: "🇨🇦",
      imagem: "canada-far-and-wide.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3716,
      longitude: -81.5526
    },
    {
      id: "the-american-adventure",
      titulo: "The American Adventure",
      subtitulo: "World Showcase",
      tipo: "Show com animatrônicos",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Show com animatrônicos narrando a história dos EUA, com efeitos especiais e trilha épica. Inspirador e educativo; sente-se no centro para melhor visão do palco.",
      icone: "🗽",
      imagem: "american-adventure.jpg",
      regiao: "World Showcase",
      parque: "EPCOT",
      latitude: 28.3699,
      longitude: -81.5487
    }
  ]
};
