ï»¿export const WorldNature = {
  parque: "EPCOT",
  regiao: "World Nature",
  latitude: 28.3730,
  longitude: -81.5510,
  descricao: "ÃƒÂrea voltada para experiÃƒÂªncias sensoriais e contato com a natureza, oceanos e sustentabilidade. Ideal para todas as idades, oferecendo atraÃƒÂ§ÃƒÂµes relaxantes, educativas e imersivas.",
  imagem: "worldnature.png",
  atracoes: [
    {
      id: "soarin-around-the-world",
      titulo: "SoarinÃ¢â‚¬â„¢ Around the World",
      subtitulo: "World Nature",
      tipo: "Simulador de voo panorÃƒÂ¢mico",
      tipoPerfil: ["imersivas", "familiares", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 35,
      idadeRecomendada: "6+",
      turnoRecomendado: "manha",
      descricao: "Simulador de voo com tela IMAX, vento e aromas, sobrevoando paisagens icÃƒÂ´nicas do mundo. ExperiÃƒÂªncia suave e emocionante, sem sustos; sente-se na fileira do meio para melhor visualizaÃƒÂ§ÃƒÂ£o e repare nos aromas de cada cenÃƒÂ¡rio.",
      icone: "Ã°Å¸Âªâ€š",
      imagem: "soarin.jpg",
      regiao: "World Nature",
      parque: "EPCOT",
      latitude: 28.3726,
      longitude: -81.5502
    },
    {
      id: "the-seas-nemo-friends",
      titulo: "The Seas with Nemo & Friends",
      subtitulo: "World Nature",
      tipo: "Passeio de carrinho subaquÃƒÂ¡tico",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Passeio leve por cenÃƒÂ¡rios subaquÃƒÂ¡ticos com Nemo e seus amigos, terminando em um grande aquÃƒÂ¡rio real com peixes, golfinhos e tartarugas. Relaxante e colorido; explore o aquÃƒÂ¡rio apÃƒÂ³s a atraÃƒÂ§ÃƒÂ£o e observe os golfinhos na ÃƒÂ¡rea interativa.",
      icone: "Ã°Å¸ÂÂ ",
      imagem: "nemo-friends.jpg",
      regiao: "World Nature",
      parque: "EPCOT",
      latitude: 28.3750,
      longitude: -81.5508
    },
    {
      id: "living-with-the-land",
      titulo: "Living with the Land",
      subtitulo: "World Nature",
      tipo: "Passeio educativo de barco",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Passeio de barco pelas estufas e sistemas de cultivo do The Land, mostrando inovaÃƒÂ§ÃƒÂ£o agrÃƒÂ­cola e sustentabilidade. Tranquilo e educativo; repare nas tÃƒÂ©cnicas de cultivo e aproveite para tirar fotos nas estufas.",
      icone: "Ã°Å¸Å’Â¿",
      imagem: "living-with-the-land.jpg",
      regiao: "World Nature",
      parque: "EPCOT",
      latitude: 28.3729,
      longitude: -81.5501
    },
    {
      id: "turtle-talk-with-crush",
      titulo: "Turtle Talk with Crush",
      subtitulo: "World Nature",
      tipo: "Show interativo digital",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Show digital interativo onde Crush conversa ao vivo com o pÃƒÂºblico, com piadas e respostas personalizadas. Divertido e climatizado; incentive as crianÃƒÂ§as a fazerem perguntas e chegue cedo para sentar nas primeiras fileiras.",
      icone: "Ã°Å¸ÂÂ¢",
      imagem: "turtle-talk.jpg",
      regiao: "World Nature",
      parque: "EPCOT",
      latitude: 28.3747,
      longitude: -81.5506
    },
    {
      id: "seabase-aquarium",
      titulo: "SeaBase Aquarium",
      subtitulo: "World Nature",
      tipo: "AquÃƒÂ¡rio de observaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Grande aquÃƒÂ¡rio com golfinhos, tubarÃƒÂµes e peixes tropicais. Ambiente calmo e fresco, ideal para pausas; leia os painÃƒÂ©is informativos e participe das apresentaÃƒÂ§ÃƒÂµes para aprender mais sobre a vida marinha.",
      icone: "Ã°Å¸ÂÂ¬",
      imagem: "seabase.jpg",
      regiao: "World Nature",
      parque: "EPCOT",
      latitude: 28.3749,
      longitude: -81.5507
    },
    {
      id: "awesome-planet",
      titulo: "Awesome Planet",
      subtitulo: "World Nature",
      tipo: "Filme educativo",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Filme educativo sobre a Terra, com imagens em alta definiÃƒÂ§ÃƒÂ£o, efeitos sensoriais e mensagem inspiradora sobre sustentabilidade. Climatizado e relaxante; sente-se no centro da sala para melhor visualizaÃƒÂ§ÃƒÂ£o.",
      icone: "Ã°Å¸Å’Å½",
      imagem: "awesome-planet.jpg",
      regiao: "World Nature",
      parque: "EPCOT",
      latitude: 28.3728,
      longitude: -81.5500
    }
  ]
};
