export const WorldCelebration = {
  parque: "EPCOT",
  regiao: "World Celebration",
  latitude: 28.3745,
  longitude: -81.5494,
  descricao: "Área central do EPCOT que celebra a criatividade e a conexão entre pessoas e ideias, com espaços tranquilos, atrações inspiradoras, homenagens a Walt Disney e experiências interativas para todas as idades.",
  imagem: "worldcelebration.png",
  atracoes: [
    {
      id: "spaceship-earth",
      titulo: "Spaceship Earth",
      subtitulo: "World Celebration",
      tipo: "Dark ride educativa",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Viagem no tempo dentro da icônica esfera do EPCOT, mostrando a evolução da comunicação com narração envolvente e cenários imersivos. Passeio escuro e lento, ótimo para descansar e aprender; olhe para cima nos cenários e personalize o final no painel interativo.",
      icone: "🌐",
      imagem: "spaceship-earth.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3747,
      longitude: -81.5497
    },
    {
      id: "dreamers-point",
      titulo: "Dreamers Point",
      subtitulo: "World Celebration",
      tipo: "Espaço temático e homenagem",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Escultura e área de homenagem a Walt Disney, com jardins tranquilos e vista privilegiada. Ambiente calmo e inspirador, ideal para pausas e fotos; sente-se ao lado da estátua e leia as mensagens para entender o espírito criativo do EPCOT.",
      icone: "🪑",
      imagem: "dreamers-point.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3746,
      longitude: -81.5494
    },
    {
      id: "communicore-plaza",
      titulo: "CommuniCore Plaza",
      subtitulo: "World Celebration",
      tipo: "Área para eventos e shows ao vivo",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Praça interativa para eventos ao ar livre, shows e experiências em família, com áreas de descanso e boa visibilidade. À noite, luzes e música deixam o ambiente mais vibrante; consulte a programação para não perder apresentações especiais.",
      icone: "🎤",
      imagem: "communicore-plaza.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3744,
      longitude: -81.5492
    },
    {
      id: "journey-of-water",
      titulo: "Journey of Water, Inspired by Moana",
      subtitulo: "World Celebration",
      tipo: "Trilha interativa com água",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Trilha interativa com fontes e efeitos de água inspirada em Moana, perfeita para refrescar nos dias quentes. Leve roupas leves e protetor solar; explore cada área sensorial e registre fotos nos pontos com jatos d’água.",
      icone: "💧",
      imagem: "journey-of-water.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3741,
      longitude: -81.5489
    },
    {
      id: "walt-disney-dreamers-statue",
      titulo: "Estátua Walt the Dreamer",
      subtitulo: "World Celebration",
      tipo: "Ponto de foto e contemplação",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Escultura de Walt Disney sentado no Dreamers Point, cercada por jardins inspiradores. Ótimo local para fotos únicas e momentos de reflexão; observe os detalhes ao redor para captar todo o significado do lugar.",
      icone: "📸",
      imagem: "walt-dreamer.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3746,
      longitude: -81.5495
    }
  ]
};
