export const WorldNature = {
  parque: "EPCOT",
  regiao: "World Nature",
  latitude: 28.3730,
  longitude: -81.5510,
  descricao: "Ãrea voltada para experiÃªncias sensoriais e contato com a natureza, oceanos e sustentabilidade. Ideal para todas as idades, oferecendo atraÃ§Ãµes relaxantes, educativas e imersivas.",
  imagem: "worldnature.png",
  atracoes: [
    {
      id: "soarin-around-the-world",
      titulo: "Soarinâ€™ Around the World",
      subtitulo: "World Nature",
      tipo: "Simulador de voo panorÃ¢mico",
      tipoPerfil: ["imersivas", "familiares", "tematicas"],
      alturaMinima: 102,
      filaExpress: true,
      tempoMedioFila: 50,
      filaAceitavel: 35,
      idadeRecomendada: "6+",
      turnoRecomendado: "manha",
      descricao: "Simulador de voo com tela IMAX, vento e aromas, sobrevoando paisagens icÃ´nicas do mundo. ExperiÃªncia suave e emocionante, sem sustos; sente-se na fileira do meio para melhor visualizaÃ§Ã£o e repare nos aromas de cada cenÃ¡rio.",
      icone: "ðŸª‚",
      imagem: "soarin.jpg",
      regiao: "World Nature",
      parque: "EPCOT",
      latitude: 28.3726,
      longitude: -81.5502
    },
    {
      id: "the-seas-nemo-friends",
      titulo: "The Seas with Nemo & Friends",
      subtitulo: "World Nature",
      tipo: "Passeio de carrinho subaquÃ¡tico",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Passeio leve por cenÃ¡rios subaquÃ¡ticos com Nemo e seus amigos, terminando em um grande aquÃ¡rio real com peixes, golfinhos e tartarugas. Relaxante e colorido; explore o aquÃ¡rio apÃ³s a atraÃ§Ã£o e observe os golfinhos na Ã¡rea interativa.",
      icone: "ðŸ ",
      imagem: "nemo-friends.jpg",
      regiao: "World Nature",
      parque: "EPCOT",
      latitude: 28.3750,
      longitude: -81.5508
    },
    {
      id: "living-with-the-land",
      titulo: "Living with the Land",
      subtitulo: "World Nature",
      tipo: "Passeio educativo de barco",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 25,
      filaAceitavel: 20,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Passeio de barco pelas estufas e sistemas de cultivo do The Land, mostrando inovaÃ§Ã£o agrÃ­cola e sustentabilidade. Tranquilo e educativo; repare nas tÃ©cnicas de cultivo e aproveite para tirar fotos nas estufas.",
      icone: "ðŸŒ¿",
      imagem: "living-with-the-land.jpg",
      regiao: "World Nature",
      parque: "EPCOT",
      latitude: 28.3729,
      longitude: -81.5501
    },
    {
      id: "turtle-talk-with-crush",
      titulo: "Turtle Talk with Crush",
      subtitulo: "World Nature",
      tipo: "Show interativo digital",
      tipoPerfil: ["interativas", "familiares", "tematicas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Show digital interativo onde Crush conversa ao vivo com o pÃºblico, com piadas e respostas personalizadas. Divertido e climatizado; incentive as crianÃ§as a fazerem perguntas e chegue cedo para sentar nas primeiras fileiras.",
      icone: "ðŸ¢",
      imagem: "turtle-talk.jpg",
      regiao: "World Nature",
      parque: "EPCOT",
      latitude: 28.3747,
      longitude: -81.5506
    },
    {
      id: "seabase-aquarium",
      titulo: "SeaBase Aquarium",
      subtitulo: "World Nature",
      tipo: "AquÃ¡rio de observaÃ§Ã£o",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Grande aquÃ¡rio com golfinhos, tubarÃµes e peixes tropicais. Ambiente calmo e fresco, ideal para pausas; leia os painÃ©is informativos e participe das apresentaÃ§Ãµes para aprender mais sobre a vida marinha.",
      icone: "ðŸ¬",
      imagem: "seabase.jpg",
      regiao: "World Nature",
      parque: "EPCOT",
      latitude: 28.3749,
      longitude: -81.5507
    },
    {
      id: "awesome-planet",
      titulo: "Awesome Planet",
      subtitulo: "World Nature",
      tipo: "Filme educativo",
      tipoPerfil: ["tematicas", "imersivas", "familiares"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "Filme educativo sobre a Terra, com imagens em alta definiÃ§Ã£o, efeitos sensoriais e mensagem inspiradora sobre sustentabilidade. Climatizado e relaxante; sente-se no centro da sala para melhor visualizaÃ§Ã£o.",
      icone: "ðŸŒŽ",
      imagem: "awesome-planet.jpg",
      regiao: "World Nature",
      parque: "EPCOT",
      latitude: 28.3728,
      longitude: -81.5500
    }
  ]
};
