ï»¿export const WorldCelebration = {
  parque: "EPCOT",
  regiao: "World Celebration",
  latitude: 28.3745,
  longitude: -81.5494,
  descricao: "ÃƒÂrea central do EPCOT que celebra a criatividade e a conexÃƒÂ£o entre pessoas e ideias, com espaÃƒÂ§os tranquilos, atraÃƒÂ§ÃƒÂµes inspiradoras, homenagens a Walt Disney e experiÃƒÂªncias interativas para todas as idades.",
  imagem: "worldcelebration.png",
  atracoes: [
    {
      id: "spaceship-earth",
      titulo: "Spaceship Earth",
      subtitulo: "World Celebration",
      tipo: "Dark ride educativa",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Viagem no tempo dentro da icÃƒÂ´nica esfera do EPCOT, mostrando a evoluÃƒÂ§ÃƒÂ£o da comunicaÃƒÂ§ÃƒÂ£o com narraÃƒÂ§ÃƒÂ£o envolvente e cenÃƒÂ¡rios imersivos. Passeio escuro e lento, ÃƒÂ³timo para descansar e aprender; olhe para cima nos cenÃƒÂ¡rios e personalize o final no painel interativo.",
      icone: "Ã°Å¸Å’Â",
      imagem: "spaceship-earth.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3747,
      longitude: -81.5497
    },
    {
      id: "dreamers-point",
      titulo: "Dreamers Point",
      subtitulo: "World Celebration",
      tipo: "EspaÃƒÂ§o temÃƒÂ¡tico e homenagem",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Escultura e ÃƒÂ¡rea de homenagem a Walt Disney, com jardins tranquilos e vista privilegiada. Ambiente calmo e inspirador, ideal para pausas e fotos; sente-se ao lado da estÃƒÂ¡tua e leia as mensagens para entender o espÃƒÂ­rito criativo do EPCOT.",
      icone: "Ã°Å¸Âªâ€˜",
      imagem: "dreamers-point.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3746,
      longitude: -81.5494
    },
    {
      id: "communicore-plaza",
      titulo: "CommuniCore Plaza",
      subtitulo: "World Celebration",
      tipo: "ÃƒÂrea para eventos e shows ao vivo",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "PraÃƒÂ§a interativa para eventos ao ar livre, shows e experiÃƒÂªncias em famÃƒÂ­lia, com ÃƒÂ¡reas de descanso e boa visibilidade. Ãƒâ‚¬ noite, luzes e mÃƒÂºsica deixam o ambiente mais vibrante; consulte a programaÃƒÂ§ÃƒÂ£o para nÃƒÂ£o perder apresentaÃƒÂ§ÃƒÂµes especiais.",
      icone: "Ã°Å¸Å½Â¤",
      imagem: "communicore-plaza.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3744,
      longitude: -81.5492
    },
    {
      id: "journey-of-water",
      titulo: "Journey of Water, Inspired by Moana",
      subtitulo: "World Celebration",
      tipo: "Trilha interativa com ÃƒÂ¡gua",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Trilha interativa com fontes e efeitos de ÃƒÂ¡gua inspirada em Moana, perfeita para refrescar nos dias quentes. Leve roupas leves e protetor solar; explore cada ÃƒÂ¡rea sensorial e registre fotos nos pontos com jatos dÃ¢â‚¬â„¢ÃƒÂ¡gua.",
      icone: "Ã°Å¸â€™Â§",
      imagem: "journey-of-water.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3741,
      longitude: -81.5489
    },
    {
      id: "walt-disney-dreamers-statue",
      titulo: "EstÃƒÂ¡tua Walt the Dreamer",
      subtitulo: "World Celebration",
      tipo: "Ponto de foto e contemplaÃƒÂ§ÃƒÂ£o",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Escultura de Walt Disney sentado no Dreamers Point, cercada por jardins inspiradores. Ãƒâ€œtimo local para fotos ÃƒÂºnicas e momentos de reflexÃƒÂ£o; observe os detalhes ao redor para captar todo o significado do lugar.",
      icone: "Ã°Å¸â€œÂ¸",
      imagem: "walt-dreamer.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3746,
      longitude: -81.5495
    }
  ]
};
