export const WorldCelebration = {
  parque: "EPCOT",
  regiao: "World Celebration",
  latitude: 28.3745,
  longitude: -81.5494,
  descricao: "Ãrea central do EPCOT que celebra a criatividade e a conexÃ£o entre pessoas e ideias, com espaÃ§os tranquilos, atraÃ§Ãµes inspiradoras, homenagens a Walt Disney e experiÃªncias interativas para todas as idades.",
  imagem: "worldcelebration.png",
  atracoes: [
    {
      id: "spaceship-earth",
      titulo: "Spaceship Earth",
      subtitulo: "World Celebration",
      tipo: "Dark ride educativa",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: true,
      tempoMedioFila: 30,
      filaAceitavel: 25,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Viagem no tempo dentro da icÃ´nica esfera do EPCOT, mostrando a evoluÃ§Ã£o da comunicaÃ§Ã£o com narraÃ§Ã£o envolvente e cenÃ¡rios imersivos. Passeio escuro e lento, Ã³timo para descansar e aprender; olhe para cima nos cenÃ¡rios e personalize o final no painel interativo.",
      icone: "ðŸŒ",
      imagem: "spaceship-earth.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3747,
      longitude: -81.5497
    },
    {
      id: "dreamers-point",
      titulo: "Dreamers Point",
      subtitulo: "World Celebration",
      tipo: "EspaÃ§o temÃ¡tico e homenagem",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Escultura e Ã¡rea de homenagem a Walt Disney, com jardins tranquilos e vista privilegiada. Ambiente calmo e inspirador, ideal para pausas e fotos; sente-se ao lado da estÃ¡tua e leia as mensagens para entender o espÃ­rito criativo do EPCOT.",
      icone: "ðŸª‘",
      imagem: "dreamers-point.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3746,
      longitude: -81.5494
    },
    {
      id: "communicore-plaza",
      titulo: "CommuniCore Plaza",
      subtitulo: "World Celebration",
      tipo: "Ãrea para eventos e shows ao vivo",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "noite",
      descricao: "PraÃ§a interativa para eventos ao ar livre, shows e experiÃªncias em famÃ­lia, com Ã¡reas de descanso e boa visibilidade. Ã€ noite, luzes e mÃºsica deixam o ambiente mais vibrante; consulte a programaÃ§Ã£o para nÃ£o perder apresentaÃ§Ãµes especiais.",
      icone: "ðŸŽ¤",
      imagem: "communicore-plaza.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3744,
      longitude: -81.5492
    },
    {
      id: "journey-of-water",
      titulo: "Journey of Water, Inspired by Moana",
      subtitulo: "World Celebration",
      tipo: "Trilha interativa com Ã¡gua",
      tipoPerfil: ["familiares", "tematicas", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 15,
      filaAceitavel: 10,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "tarde",
      descricao: "Trilha interativa com fontes e efeitos de Ã¡gua inspirada em Moana, perfeita para refrescar nos dias quentes. Leve roupas leves e protetor solar; explore cada Ã¡rea sensorial e registre fotos nos pontos com jatos dâ€™Ã¡gua.",
      icone: "ðŸ’§",
      imagem: "journey-of-water.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3741,
      longitude: -81.5489
    },
    {
      id: "walt-disney-dreamers-statue",
      titulo: "EstÃ¡tua Walt the Dreamer",
      subtitulo: "World Celebration",
      tipo: "Ponto de foto e contemplaÃ§Ã£o",
      tipoPerfil: ["tematicas", "familiares", "imersivas"],
      alturaMinima: 0,
      filaExpress: false,
      tempoMedioFila: 0,
      filaAceitavel: 0,
      idadeRecomendada: "Todas as idades",
      turnoRecomendado: "manha",
      descricao: "Escultura de Walt Disney sentado no Dreamers Point, cercada por jardins inspiradores. Ã“timo local para fotos Ãºnicas e momentos de reflexÃ£o; observe os detalhes ao redor para captar todo o significado do lugar.",
      icone: "ðŸ“¸",
      imagem: "walt-dreamer.jpg",
      regiao: "World Celebration",
      parque: "EPCOT",
      latitude: 28.3746,
      longitude: -81.5495
    }
  ]
};
