import type { Promocao } from "./promocao";

export const PROMOCOES: Promocao[] = [
  // ============= COMPRAS (10) =============
  {
    id: 'orlando-intl-premium-outlets',
    titulo: 'Orlando International Premium Outlets – Deals',
    descricao: 'Página oficial de ofertas do maior outlet da I-Drive.',
    categoria: 'compras',
    parceiro: 'Simon Premium Outlets',
    link: 'https://www.premiumoutlets.com/outlet/orlando-international/deals',
  },
  {
    id: 'orlando-vineland-premium-outlets',
    titulo: 'Orlando Vineland Premium Outlets – Deals',
    descricao: 'Deals atualizados do outlet mais próximo da Disney.',
    categoria: 'compras',
    parceiro: 'Simon Premium Outlets',
    link: 'https://www.premiumoutlets.com/outlet/orlando-vineland/deals',
  },
  {
    id: 'the-florida-mall-deals',
    titulo: 'The Florida Mall – Deals & Steals',
    descricao: 'Ofertas e cupons no maior shopping de Orlando.',
    categoria: 'compras',
    parceiro: 'Simon',
    link: 'https://www.simon.com/mall/the-florida-mall/deals',
  },
  {
    id: 'lake-buena-vista-factory-stores',
    titulo: 'Lake Buena Vista Factory Stores – Coupons',
    descricao: 'Cupons oficiais dos outlets de Lake Buena Vista.',
    categoria: 'compras',
    parceiro: 'LBVFS',
    link: 'https://www.lbvfs.com/coupons/',
  },
  {
    id: 'orlando-outlet-marketplace-deals',
    titulo: 'Orlando Outlet Marketplace – Deals',
    descricao: 'Ofertas do outlet Marketplace na International Dr.',
    categoria: 'compras',
    parceiro: 'Simon Premium Outlets',
    link: 'https://www.premiumoutlets.com/outlet/orlando-outlet-marketplace/deals',
  },
  {
    id: 'mall-at-millenia-events',
    titulo: 'The Mall at Millenia – Offers/Events',
    descricao: 'Página de novidades e promoções sazonais.',
    categoria: 'compras',
    parceiro: 'Mall at Millenia',
    link: 'https://www.mallatmillenia.com/events/',
  },
  {
    id: 'disney-character-warehouse',
    titulo: 'Disney Character Warehouse (Outlet Disney)',
    descricao: 'Excedentes oficiais Disney com grandes descontos.',
    categoria: 'compras',
    parceiro: 'Disney Outlet',
    link: 'https://www.premiumoutlets.com/outlet/orlando-vineland/stores/disney-character-warehouse',
  },
  {
    id: 'disney-springs-offers',
    titulo: 'Disney Springs – Ofertas e Eventos',
    descricao: 'Promoções sazonais em lojas e experiências.',
    categoria: 'compras',
    parceiro: 'Disney Springs',
    link: 'https://www.disneysprings.com/latest-news/',
  },
  {
    id: 'icon-park-shopping-deals',
    titulo: 'ICON Park – Shopping Deals',
    descricao: 'Cupons/combos para lojas e atrações no complexo.',
    categoria: 'compras',
    parceiro: 'ICON Park',
    link: 'https://iconparkorlando.com/offers/',
  },
  {
    id: 'visitorlando-shopping',
    titulo: 'Visit Orlando – Shopping Deals',
    descricao: 'Seleção oficial de ofertas de compras em Orlando.',
    categoria: 'compras',
    parceiro: 'Visit Orlando',
    link: 'https://www.visitorlando.com/offers/shopping/',
  },

  // ============= PARQUES (10) =============
  {
    id: 'walt-disney-world',
    titulo: 'Walt Disney World – Special Offers',
    descricao: 'Ofertas em hotéis, ingressos e pacotes Disney.',
    categoria: 'parques',
    parceiro: 'Walt Disney World',
    link: 'https://disneyworld.disney.go.com/pt-br/special-offers/',
  },
  {
    id: 'universal-orlando',
    titulo: 'Universal Orlando – Offers',
    descricao: 'Ingressos, combos e pacotes com desconto.',
    categoria: 'parques',
    parceiro: 'Universal Orlando',
    link: 'https://www.universalorlando.com/web/en/us/tickets-packages/offers',
  },
  {
    id: 'seaworld-orlando',
    titulo: 'SeaWorld Orlando – Offers',
    descricao: 'Promoções sazonais e passes com desconto.',
    categoria: 'parques',
    parceiro: 'SeaWorld Orlando',
    link: 'https://seaworld.com/orlando/offers/',
  },
  {
    id: 'discovery-cove',
    titulo: 'Discovery Cove – Tickets & Deals',
    descricao: 'Pacotes com alimentação e experiências.',
    categoria: 'parques',
    parceiro: 'SeaWorld Parks',
    link: 'https://www.discoverycove.com/orlando/tickets/',
  },
  {
    id: 'aquatica-orlando',
    titulo: 'Aquatica Orlando – Offers',
    descricao: 'Parque aquático com descontos e combos.',
    categoria: 'parques',
    parceiro: 'Aquatica',
    link: 'https://aquatica.com/orlando/offers/',
  },
  {
    id: 'fun-spot-america',
    titulo: 'Fun Spot America Orlando – Deals',
    descricao: 'Promoções em passes diários e anuais.',
    categoria: 'parques',
    parceiro: 'Fun Spot',
    link: 'https://fun-spot.com/orlando/specials/',
  },
  {
    id: 'icon-park-attractions',
    titulo: 'ICON Park – Attraction Deals',
    descricao: 'Combos para The Wheel e outras atrações.',
    categoria: 'parques',
    parceiro: 'ICON Park',
    link: 'https://iconparkorlando.com/offers/',
  },
  {
    id: 'gatorland',
    titulo: 'Gatorland – Coupons & Specials',
    descricao: 'Cupons oficiais e ofertas para o “Alligator Capital”.',
    categoria: 'parques',
    parceiro: 'Gatorland',
    link: 'https://www.gatorland.com/specials/',
  },
  {
    id: 'legoland-florida',
    titulo: 'LEGOLAND Florida – Deals',
    descricao: 'Ofertas de ingressos e pacotes (próximo a Orlando).',
    categoria: 'parques',
    parceiro: 'LEGOLAND',
    link: 'https://www.legoland.com/florida/tickets-passes/offers/',
  },
  {
    id: 'kennedy-space-center',
    titulo: 'Kennedy Space Center – Offers',
    descricao: 'Descontos sazonais para o complexo espacial.',
    categoria: 'parques',
    parceiro: 'KSC',
    link: 'https://www.kennedyspacecenter.com/info/tickets',
  },

  // ============= RESTAURANTES (10) =============
  {
    id: 'magical-dining',
    titulo: 'Visit Orlando’s Magical Dining',
    descricao: 'Menu fixo com preço promocional (sazonal).',
    categoria: 'restaurantes',
    parceiro: 'Visit Orlando',
    link: 'https://www.magicaldining.com/',
  },
  {
    id: 'disney-dining-offers',
    titulo: 'Walt Disney World – Dining Offers',
    descricao: 'Ofertas e eventos em restaurantes Disney.',
    categoria: 'restaurantes',
    parceiro: 'Walt Disney World',
    link: 'https://disneyworld.disney.go.com/pt-br/dining/',
  },
  {
    id: 'disney-springs-dining',
    titulo: 'Disney Springs – Dining News',
    descricao: 'Novidades e promoções em restaurantes do complexo.',
    categoria: 'restaurantes',
    parceiro: 'Disney Springs',
    link: 'https://www.disneysprings.com/latest-news/',
  },
  {
    id: 'universal-citywalk-dining',
    titulo: 'Universal CityWalk – Dining Deals',
    descricao: 'Ofertas em bares e restaurantes no CityWalk.',
    categoria: 'restaurantes',
    parceiro: 'Universal Orlando',
    link: 'https://www.universalorlando.com/web/en/us/things-to-do/dining',
  },
  {
    id: 'icon-park-dining',
    titulo: 'ICON Park – Dining Offers',
    descricao: 'Cupons e combos em restaurantes do ICON Park.',
    categoria: 'restaurantes',
    parceiro: 'ICON Park',
    link: 'https://iconparkorlando.com/offers/',
  },
  {
    id: 'orlando-restaurant-deals-visitorlando',
    titulo: 'Visit Orlando – Restaurant Deals',
    descricao: 'Ofertas oficiais em diversos restaurantes.',
    categoria: 'restaurantes',
    parceiro: 'Visit Orlando',
    link: 'https://www.visitorlando.com/offers/restaurants/',
  },
  {
    id: 'earl-of-sandwich-disney-springs',
    titulo: 'Earl of Sandwich – Offers (Disney Springs)',
    descricao: 'Promoções e cupons do clássico sanduíche.',
    categoria: 'restaurantes',
    parceiro: 'Earl of Sandwich',
    link: 'https://www.earlofsandwichusa.com/locations/disney-springs/',
  },
  {
    id: 'the-boathouse-specials',
    titulo: 'The BOATHOUSE – Specials',
    descricao: 'Eventos e ofertas no restaurante à beira do lago.',
    categoria: 'restaurantes',
    parceiro: 'The BOATHOUSE',
    link: 'https://theboathouseorlando.com/',
  },
  {
    id: 'vivo-italian-kitchen-offers',
    titulo: 'VIVO Italian Kitchen – Offers (CityWalk)',
    descricao: 'Promoções sazonais e menus especiais.',
    categoria: 'restaurantes',
    parceiro: 'Universal Orlando',
    link: 'https://www.universalorlando.com/web/en/us/things-to-do/dining/vivo-italian-kitchen',
  },
  {
    id: 'shake-shack-orlando-deals',
    titulo: 'Shake Shack – Deals (Orlando)',
    descricao: 'Cupons e novidades em lojas da região.',
    categoria: 'restaurantes',
    parceiro: 'Shake Shack',
    link: 'https://www.shakeshack.com/location/',
  },

  // ============= HOTÉIS (10) =============
  {
    id: 'disney-resorts-offers',
    titulo: 'Disney Resorts – Special Offers',
    descricao: 'Descontos em hotéis do complexo Disney.',
    categoria: 'hoteis',
    parceiro: 'Walt Disney World',
    link: 'https://disneyworld.disney.go.com/pt-br/special-offers/',
  },
  {
    id: 'universal-hotels-offers',
    titulo: 'Universal Orlando Hotels – Offers',
    descricao: 'Ofertas nos hotéis Loews/Universal.',
    categoria: 'hoteis',
    parceiro: 'Universal Orlando',
    link: 'https://www.universalorlando.com/web/en/us/places-to-stay/offers',
  },
  {
    id: 'swan-dolphin-offers',
    titulo: 'Walt Disney World Swan & Dolphin – Offers',
    descricao: 'Tarifas promocionais e pacotes.',
    categoria: 'hoteis',
    parceiro: 'Swan & Dolphin',
    link: 'https://swandolphin.com/offers/',
  },
  {
    id: 'four-seasons-orlando-offers',
    titulo: 'Four Seasons Orlando – Offers',
    descricao: 'Pacotes de luxo com benefícios.',
    categoria: 'hoteis',
    parceiro: 'Four Seasons',
    link: 'https://www.fourseasons.com/orlando/offers/',
  },
  {
    id: 'b-resort-disney-springs-offers',
    titulo: 'B Resort & Spa Disney Springs – Offers',
    descricao: 'Descontos e pacotes em hotel parceiro Disney Springs.',
    categoria: 'hoteis',
    parceiro: 'B Resort & Spa',
    link: 'https://www.bresortlbv.com/offers',
  },
  {
    id: 'wyndham-lake-buena-vista-offers',
    titulo: 'Wyndham Lake Buena Vista – Deals',
    descricao: 'Tarifas promocionais próximo à Disney.',
    categoria: 'hoteis',
    parceiro: 'Wyndham',
    link: 'https://www.wyndhamlakebuenavista.com/specials/',
  },
  {
    id: 'rosen-shingle-creek-offers',
    titulo: 'Rosen Shingle Creek – Offers',
    descricao: 'Pacotes e tarifas especiais.',
    categoria: 'hoteis',
    parceiro: 'Rosen Hotels',
    link: 'https://www.rosenshinglecreek.com/specials-packages/',
  },
  {
    id: 'rosen-centre-offers',
    titulo: 'Rosen Centre – Offers',
    descricao: 'Ofertas e códigos promocionais.',
    categoria: 'hoteis',
    parceiro: 'Rosen Hotels',
    link: 'https://www.rosencentre.com/specials/',
  },
  {
    id: 'rosen-inn-lbv-offers',
    titulo: 'Rosen Inn Lake Buena Vista – Deals',
    descricao: 'Tarifas econômicas perto da Disney.',
    categoria: 'hoteis',
    parceiro: 'Rosen Hotels',
    link: 'https://www.roseninnlbv.com/specials/',
  },
  {
    id: 'hilton-orlando-offers',
    titulo: 'Hilton Orlando – Offers',
    descricao: 'Pacotes e descontos diretos do hotel.',
    categoria: 'hoteis',
    parceiro: 'Hilton',
    link: 'https://www.thehiltonorlando.com/offers/',
  },

  // ============= TRANSPORTE (10) =============
  {
    id: 'mears-connect',
    titulo: 'Mears Connect – Airport Shuttle Deals',
    descricao: 'Traslado MCO ↔ Disney/área turística.',
    categoria: 'transporte',
    parceiro: 'Mears',
    link: 'https://www.mearsconnect.com/',
  },
  {
    id: 'lynx-fares',
    titulo: 'LYNX Bus – Fares & Passes',
    descricao: 'Passes e informações de tarifas do transporte público.',
    categoria: 'transporte',
    parceiro: 'LYNX',
    link: 'https://www.golynx.com/fares-passes/',
  },
  {
    id: 'i-ride-trolley-coupons',
    titulo: 'I-RIDE Trolley – Coupons',
    descricao: 'Cupons para o bonde da International Drive.',
    categoria: 'transporte',
    parceiro: 'I-RIDE Trolley',
    link: 'https://iridetrolley.com/coupons/',
  },
  {
    id: 'alamo-mco-deals',
    titulo: 'Alamo Rent A Car – Orlando Deals',
    descricao: 'Ofertas para retirada no Aeroporto de Orlando.',
    categoria: 'transporte',
    parceiro: 'Alamo',
    link: 'https://www.alamo.com/en_US/car-rental/deals/us.html',
  },
  {
    id: 'hertz-mco-deals',
    titulo: 'Hertz – Deals (MCO)',
    descricao: 'Tarifas promocionais e cupons.',
    categoria: 'transporte',
    parceiro: 'Hertz',
    link: 'https://www.hertz.com/rentacar/misc/index.jsp?targetPage=deals.jsp',
  },
  {
    id: 'avis-mco-deals',
    titulo: 'Avis – Orlando/MCO Offers',
    descricao: 'Códigos e ofertas para Orlando.',
    categoria: 'transporte',
    parceiro: 'Avis',
    link: 'https://www.avis.com/en/offers',
  },
  {
    id: 'budget-mco-deals',
    titulo: 'Budget – Orlando Deals',
    descricao: 'Cupons e promoções sazonais.',
    categoria: 'transporte',
    parceiro: 'Budget',
    link: 'https://www.budget.com/en/offers',
  },
  {
    id: 'sixt-mco-deals',
    titulo: 'SIXT – Orlando/MCO Offers',
    descricao: 'Descontos e upgrades no aluguel.',
    categoria: 'transporte',
    parceiro: 'SIXT',
    link: 'https://www.sixt.com/deals/',
  },
  {
    id: 'lyft-promo',
    titulo: 'Lyft – Promo & Credits',
    descricao: 'Página de novidades e créditos promocionais.',
    categoria: 'transporte',
    parceiro: 'Lyft',
    link: 'https://www.lyft.com/rider/promo',
  },
  {
    id: 'uber-promotions',
    titulo: 'Uber – Promotions',
    descricao: 'Informações de cupons e campanhas.',
    categoria: 'transporte',
    parceiro: 'Uber',
    link: 'https://www.uber.com/us/en/ride/uber-rewards/',
  },

  // ============= OUTROS / ATRAÇÕES (10) =============
  {
    id: 'crayola-experience',
    titulo: 'Crayola Experience – Special Offers',
    descricao: 'Cupons e promoções da atração indoor.',
    categoria: 'outros',
    parceiro: 'Crayola',
    link: 'https://www.crayolaexperience.com/orlando/plan-your-visit/special-offers',
  },
  {
    id: 'madame-tussauds-orlando',
    titulo: 'Madame Tussauds Orlando – Deals',
    descricao: 'Ingressos com desconto e combos.',
    categoria: 'outros',
    parceiro: 'Merlin Entertainments',
    link: 'https://www.madametussauds.com/orlando/tickets-prices/',
  },
  {
    id: 'sea-life-orlando',
    titulo: 'SEA LIFE Orlando – Deals',
    descricao: 'Ofertas e combos com outras atrações.',
    categoria: 'outros',
    parceiro: 'Merlin Entertainments',
    link: 'https://www.visitsealife.com/orlando/tickets-passes/',
  },
  {
    id: 'museum-of-illusions',
    titulo: 'Museum of Illusions Orlando – Offers',
    descricao: 'Cupons e pacotes promocionais.',
    categoria: 'outros',
    parceiro: 'MOI Orlando',
    link: 'https://moiorlando.com/',
  },
  {
    id: 'wonderworks-orlando',
    titulo: 'WonderWorks Orlando – Coupons',
    descricao: 'Cupons oficiais e combos.',
    categoria: 'outros',
    parceiro: 'WonderWorks',
    link: 'https://www.wonderworksonline.com/orlando/coupons/',
  },
  {
    id: 'the-wheel-icon-park',
    titulo: 'The Wheel at ICON Park – Offers',
    descricao: 'Ofertas para a roda-gigante e combos.',
    categoria: 'outros',
    parceiro: 'ICON Park',
    link: 'https://iconparkorlando.com/offers/',
  },
  {
    id: 'ripleys-orlando',
    titulo: 'Ripley’s Believe It or Not! Orlando – Deals',
    descricao: 'Descontos e cupons oficiais.',
    categoria: 'outros',
    parceiro: 'Ripley’s',
    link: 'https://www.ripleys.com/attractions/ripleys-believe-it-or-not-orlando/',
  },
  {
    id: 'chocolate-kingdom',
    titulo: 'Chocolate Kingdom – Coupons',
    descricao: 'Cupons para tour do chocolate.',
    categoria: 'outros',
    parceiro: 'Chocolate Kingdom',
    link: 'https://www.chocolatekingdom.com/coupons',
  },
  {
    id: 'boggy-creek-airboat',
    titulo: 'Boggy Creek Airboat Adventures – Deals',
    descricao: 'Ofertas em passeios de airboat.',
    categoria: 'outros',
    parceiro: 'Boggy Creek',
    link: 'https://bcairboats.com/specials/',
  },
  {
    id: 'orlando-science-center',
    titulo: 'Orlando Science Center – Discounts',
    descricao: 'Descontos e programas especiais.',
    categoria: 'outros',
    parceiro: 'OSC',
    link: 'https://www.osc.org/discounts/',
  },

  {
    id: 'vip-shopper-club-coupons',
    titulo: 'VIP Shopper Club – Digital Coupon Book',
    descricao: 'Livro de cupons oficial dos Premium Outlets (exige cadastro grátis).',
    categoria: 'compras',
    parceiro: 'Simon Premium Outlets',
    link: 'https://www.premiumoutlets.com/vip', // cupons digitais p/ Orlando International & Vineland
  },

  // (os 10 que já estavam:)
  {
    id: 'orlando-intl-premium-outlets',
    titulo: 'Orlando International Premium Outlets – Deals',
    descricao: 'Página oficial de ofertas do maior outlet da I-Drive.',
    categoria: 'compras',
    parceiro: 'Simon Premium Outlets',
    link: 'https://www.premiumoutlets.com/outlet/orlando-international/deals',
  },
  {
    id: 'orlando-vineland-premium-outlets',
    titulo: 'Orlando Vineland Premium Outlets – Deals',
    descricao: 'Deals atualizados do outlet mais próximo da Disney.',
    categoria: 'compras',
    parceiro: 'Simon Premium Outlets',
    link: 'https://www.premiumoutlets.com/outlet/orlando-vineland/deals',
  },
  {
    id: 'the-florida-mall-deals',
    titulo: 'The Florida Mall – Deals & Steals',
    descricao: 'Ofertas e cupons no maior shopping de Orlando.',
    categoria: 'compras',
    parceiro: 'Simon',
    link: 'https://www.simon.com/mall/the-florida-mall/deals',
  },
  {
    id: 'lake-buena-vista-factory-stores',
    titulo: 'Lake Buena Vista Factory Stores – Coupons',
    descricao: 'Cupons oficiais dos outlets de Lake Buena Vista.',
    categoria: 'compras',
    parceiro: 'LBVFS',
    link: 'https://www.lbvfs.com/coupons/',
  },
  {
    id: 'orlando-outlet-marketplace-deals',
    titulo: 'Orlando Outlet Marketplace – Deals',
    descricao: 'Ofertas do outlet Marketplace na International Dr.',
    categoria: 'compras',
    parceiro: 'Simon Premium Outlets',
    link: 'https://www.premiumoutlets.com/outlet/orlando-outlet-marketplace/deals',
  },
  {
    id: 'mall-at-millenia-events',
    titulo: 'The Mall at Millenia – Offers/Events',
    descricao: 'Página de novidades e promoções sazonais.',
    categoria: 'compras',
    parceiro: 'Mall at Millenia',
    link: 'https://www.mallatmillenia.com/events/',
  },
  {
    id: 'disney-character-warehouse',
    titulo: 'Disney Character Warehouse (Outlet Disney)',
    descricao: 'Excedentes oficiais Disney com grandes descontos.',
    categoria: 'compras',
    parceiro: 'Disney Outlet',
    link: 'https://www.premiumoutlets.com/outlet/orlando-vineland/stores/disney-character-warehouse',
  },
  {
    id: 'disney-springs-offers',
    titulo: 'Disney Springs – Ofertas e Eventos',
    descricao: 'Promoções sazonais em lojas e experiências.',
    categoria: 'compras',
    parceiro: 'Disney Springs',
    link: 'https://www.disneysprings.com/latest-news/',
  },
  {
    id: 'icon-park-shopping-deals',
    titulo: 'ICON Park – Shopping Deals',
    descricao: 'Cupons/combos para lojas e atrações no complexo.',
    categoria: 'compras',
    parceiro: 'ICON Park',
    link: 'https://iconparkorlando.com/offers/',
  },
  {
    id: 'visitorlando-shopping',
    titulo: 'Visit Orlando – Shopping Deals',
    descricao: 'Seleção oficial de ofertas de compras em Orlando.',
    categoria: 'compras',
    parceiro: 'Visit Orlando',
    link: 'https://www.visitorlando.com/offers/shopping/',
  },

  // … (restante das categorias PARQUES, RESTAURANTES, HOTÉIS, TRANSPORTE, OUTROS ficam iguais)

];
