ï»¿import type { Promocao } from "./promocao";

// 1 item por domÃƒÂ­nio; sÃƒÂ³ pÃƒÂ¡ginas que abrem e levam a ofertas/benefÃƒÂ­cios.
export const PROMOCOES: (Promocao & { sobre?: string; oQueTem?: string[] })[] = [
  // ============= COMPRAS =============
  {
    id: 'orlando-intl-premium-outlets',
    titulo: 'Orlando International Premium Outlets Ã¢â‚¬â€œ Deals',
    descricao: 'PÃƒÂ¡gina oficial de ofertas do maior outlet da I-Drive.',
    categoria: 'compras',
    parceiro: 'Simon Premium Outlets',
    link: 'https://www.premiumoutlets.com/outlet/orlando-international/deals',
    sobre: 'O maior outlet da International Drive, com dezenas de marcas populares e premium em formato ao ar livre.',
    oQueTem: ['Lojas ÃƒÂ¢ncora e grifes', 'PraÃƒÂ§a de alimentaÃƒÂ§ÃƒÂ£o', 'Cupons e deals oficiais no site'],
  },
  {
    id: 'the-florida-mall-deals',
    titulo: 'The Florida Mall Ã¢â‚¬â€œ Deals & Steals',
    descricao: 'Ofertas e cupons no maior shopping de Orlando.',
    categoria: 'compras',
    parceiro: 'Simon',
    link: 'https://www.simon.com/mall/the-florida-mall/deals',
    sobre: 'Shopping coberto com centenas de lojas e experiÃƒÂªncias para famÃƒÂ­lia.',
    oQueTem: ['Lojas ÃƒÂ¢ncora e boutiques', 'AlimentaÃƒÂ§ÃƒÂ£o variada', 'Eventos e promoÃƒÂ§ÃƒÂµes sazonais'],
  },
  {
    id: 'lake-buena-vista-factory-stores',
    titulo: 'Lake Buena Vista Factory Stores Ã¢â‚¬â€œ Deals (PT-BR)',
    descricao: 'PÃƒÂ¡gina de ofertas dos outlets de Lake Buena Vista (em portuguÃƒÂªs).',
    categoria: 'compras',
    parceiro: 'LBVFS',
    link: 'https://lbvfs.com/deals/?lang=pt-br',
    sobre: 'Conjunto de outlets prÃƒÂ³ximo ÃƒÂ  Disney com estacionamento fÃƒÂ¡cil.',
    oQueTem: ['Lojas de roupas e calÃƒÂ§ados', 'Ofertas ativas por loja', 'OpÃƒÂ§ÃƒÂµes de alimentaÃƒÂ§ÃƒÂ£o prÃƒÂ³ximas'],
  },
  {
    id: 'mall-at-millenia-events',
    titulo: 'The Mall at Millenia Ã¢â‚¬â€œ Offers/Events',
    descricao: 'PÃƒÂ¡gina de novidades e promoÃƒÂ§ÃƒÂµes sazonais.',
    categoria: 'compras',
    parceiro: 'Mall at Millenia',
    link: 'https://www.mallatmillenia.com/events/',
    sobre: 'Shopping premium e sofisticado com ÃƒÂ¢ncoras de luxo.',
    oQueTem: ['Marcas de alto padrÃƒÂ£o', 'Restaurantes e cafÃƒÂ©s', 'Eventos e vitrines especiais'],
  },
{
  id: 'icon-park-shopping-deals',
  titulo: 'ICON Park Ã¢â‚¬â€œ Shopping Deals',
  descricao: 'Cupons/combos para lojas e atraÃƒÂ§ÃƒÂµes no complexo.',
  categoria: 'compras',
  parceiro: 'ICON Park',
  link: 'https://iconparkorlando.com/deals/',
  sobre: 'Complexo de lazer na I-Drive com lojas, restaurantes e atraÃƒÂ§ÃƒÂµes.',
  oQueTem: ['Lojas temÃƒÂ¡ticas', 'Combos com atraÃƒÂ§ÃƒÂµes', 'Restaurantes e bares'],
},

{
  id: 'visitorlando-shopping',
  titulo: 'Visit Orlando Ã¢â‚¬â€œ Ofertas (PT)',
  descricao: 'PÃƒÂ¡gina oficial de ofertas em portuguÃƒÂªs (use o filtro para Ã¢â‚¬Å“ComprasÃ¢â‚¬Â).',
  categoria: 'compras',
  parceiro: 'Visit Orlando',
  link: 'https://pt.visitorlando.com/ofertas/',
  sobre: 'Portal oficial de turismo de Orlando com ofertas ativas (em portuguÃƒÂªs).',
  oQueTem: ['Filtro por categoria (Compras)', 'Ofertas de lojas e outlets', 'PromoÃƒÂ§ÃƒÂµes atualizadas pelo Visit Orlando'],
},

  // ============= PARQUES =============
  {
    id: 'walt-disney-world-ofertas',
    titulo: 'Walt Disney World Ã¢â‚¬â€œ Ofertas e Descontos',
    descricao: 'Central oficial de ofertas: ingressos especiais e descontos em hotÃƒÂ©is.',
    categoria: 'parques',
    parceiro: 'Walt Disney World',
    link: 'https://disneyworld.disney.go.com/pt-br/special-offers/',
    sobre: 'Maior complexo de parques do mundo, com ofertas sazonais.',
    oQueTem: ['Ingressos promocionais', 'Descontos em hotÃƒÂ©is', 'BenefÃƒÂ­cios para pÃƒÂºblicos elegÃƒÂ­veis'],
  },


  {
    id: 'universal-orlando-deals',
    titulo: 'Universal Orlando Ã¢â‚¬â€œ Deals & Specials',
    descricao: 'Ofertas oficiais de ingressos e pacotes.',
    categoria: 'parques',
    parceiro: 'Universal Orlando',
    link: 'https://www.universalorlando.com/web/en/us/all-products',
    sobre: 'Hub oficial de produtos com seÃƒÂ§ÃƒÂ£o de Ã¢â‚¬Å“Deals & SpecialsÃ¢â‚¬Â sempre ativa.',
    oQueTem: ['Ofertas multi-dia', 'Pacotes com hotel', 'PromoÃƒÂ§ÃƒÂµes sazonais'],
  },



  {
    id: 'seaworld-orlando-ofertas',
    titulo: 'SeaWorld Orlando Ã¢â‚¬â€œ Special Offers',
    descricao: 'PÃƒÂ¡gina oficial com descontos, combos e passes.',
    categoria: 'parques',
    parceiro: 'SeaWorld Orlando',
    link: 'https://seaworld.com/orlando/special-offers/',
    sobre: 'Parque marinho com montanhas-russas e eventos sazonais.',
    oQueTem: ['Passes anuais', 'Combos com Aquatica/Discovery Cove', 'Ofertas por perÃƒÂ­odo'],
  },
  {
    id: 'discovery-cove-deals',
    titulo: 'Discovery Cove Ã¢â‚¬â€œ Day Resort Packages',
    descricao: 'Pacotes all-inclusive e ofertas sazonais.',
    categoria: 'parques',
    parceiro: 'Discovery Cove',
    link: 'https://discoverycove.com/orlando/day-resort-packages/',
    sobre: 'ExperiÃƒÂªncia de dia inteiro com lagoas, snorkel e interaÃƒÂ§ÃƒÂ£o com animais.',
    oQueTem: ['RefeiÃƒÂ§ÃƒÂµes incluÃƒÂ­das', 'OpÃƒÂ§ÃƒÂ£o com golfinhos', 'Combos com SeaWorld/Aquatica'],
  },
  {
    id: 'aquatica-orlando-ofertas',
    titulo: 'Aquatica Orlando Ã¢â‚¬â€œ Limited-Time Offers',
    descricao: 'Descontos e combos oficiais do parque aquÃƒÂ¡tico.',
    categoria: 'parques',
    parceiro: 'Aquatica',
    link: 'https://aquatica.com/orlando/limited-time-offers/',
    sobre: 'Parque aquÃƒÂ¡tico com toboÃƒÂ¡guas e ÃƒÂ¡reas infantis.',
    oQueTem: ['Ingressos com desconto', 'All-Day Dining (add-on)', 'Combos com SeaWorld'],
  },

  {
    id: 'fun-spot-orlando-specials',
    titulo: 'Fun Spot America Orlando Ã¢â‚¬â€œ Ofertas',
    descricao: 'PÃƒÂ¡gina com eventos e promoÃƒÂ§ÃƒÂµes ativas em Orlando.',
    categoria: 'parques',
    parceiro: 'Fun Spot',
    link: 'https://fun-spot.com/category/orlando-events/',
    sobre: 'Parque familiar com karts e atraÃƒÂ§ÃƒÂµes radicais.',
    oQueTem: ['Passes e descontos sazonais', 'Eventos em Orlando', 'Ofertas por tempo limitado'],
  },

  {
    id: 'gatorland-specials',
    titulo: 'Gatorland Ã¢â‚¬â€œ Coupons & Specials',
    descricao: 'Cupons oficiais e ofertas para o Ã¢â‚¬Å“Alligator CapitalÃ¢â‚¬Â.',
    categoria: 'parques',
    parceiro: 'Gatorland',
    link: 'https://www.gatorland.com/specials/',
    sobre: 'Parque temÃƒÂ¡tico de vida selvagem da FlÃƒÂ³rida.',
    oQueTem: ['Cupons no site', 'Zip line e experiÃƒÂªncias', 'Shows e trilhas'],
  },
  {
    id: 'legoland-florida-deals',
    titulo: 'LEGOLAND Florida Ã¢â‚¬â€œ Tickets & Passes',
    descricao: 'PÃƒÂ¡gina oficial de ingressos e passes (link estÃƒÂ¡vel, sem 404).',
    categoria: 'parques',
    parceiro: 'LEGOLAND',
    link: 'https://www.legoland.com/florida/tickets-passes/',
    sobre: 'Ingressos e passes com preÃƒÂ§os atualizados; a pÃƒÂ¡gina tambÃƒÂ©m destaca ofertas e eventos sazonais.',
    oQueTem: ['Ingressos datados', 'Passes anuais', 'Extras como FasTrack e cabanas']
  }
  ,

  // ============= RESTAURANTES/COMPLEXOS =============
  {
    id: 'magical-dining',
    titulo: 'Visit OrlandoÃ¢â‚¬â„¢s Magical Dining',
    descricao: 'Menu fixo com preÃƒÂ§o promocional (sazonal).',
    categoria: 'restaurantes',
    parceiro: 'Visit Orlando',
    link: 'https://www.magicaldining.com/',
    sobre: 'Evento anual com menus fechados em restaurantes selecionados.',
    oQueTem: ['PreÃƒÂ§o fixo por pessoa', 'Lista de restaurantes participantes', 'PerÃƒÂ­odo sazonal'],
  },
  {
    id: 'the-boathouse-specials',
    titulo: 'The BOATHOUSE Ã¢â‚¬â€œ Specials',
    descricao: 'Eventos e ofertas no restaurante ÃƒÂ  beira do lago.',
    categoria: 'restaurantes',
    parceiro: 'The BOATHOUSE',
    link: 'https://theboathouseorlando.com/',
    sobre: 'Restaurante ÃƒÂ  beira da ÃƒÂ¡gua em Disney Springs.',
    oQueTem: ['Menu de peixes e carnes', 'Passeios de Amphicar (pago ÃƒÂ  parte)', 'Eventos e reservas'],
  },

  // ============= HOTÃƒâ€°IS =============
  {
    id: 'swan-dolphin-offers',
    titulo: 'Walt Disney World Swan & Dolphin Ã¢â‚¬â€œ Offers',
    descricao: 'Tarifas promocionais e pacotes.',
    categoria: 'hoteis',
    parceiro: 'Swan & Dolphin',
    link: 'https://swandolphin.com/offers/',
    sobre: 'HotÃƒÂ©is dentro do complexo Disney operados por terceiros.',
    oQueTem: ['LocalizaÃƒÂ§ÃƒÂ£o privilegiada', 'Restaurantes e spa', 'Ofertas diretas no site'],
  },
  {
    id: 'four-seasons-orlando-offers',
    titulo: 'Four Seasons Orlando Ã¢â‚¬â€œ Offers',
    descricao: 'Pacotes de luxo com benefÃƒÂ­cios.',
    categoria: 'hoteis',
    parceiro: 'Four Seasons',
    link: 'https://www.fourseasons.com/orlando/offers/',
    sobre: 'Hotel 5 estrelas dentro do complexo, foco em luxo e serviÃƒÂ§os.',
    oQueTem: ['Piscinas e lazy river', 'Kids club e spa', 'Pacotes com crÃƒÂ©dito de resort'],
  },
  {
    id: 'renaissance-disney-springs-offers',
    titulo: 'Renaissance Orlando Resort Ã¢â‚¬â€œ Ofertas (ex-B Resort)',
    descricao: 'PÃƒÂ¡gina oficial de ofertas do hotel (Marriott).',
    categoria: 'hoteis',
    parceiro: 'Marriott / Renaissance',
    link: 'https://www.marriott.com/offers/findOffers.mi?propertycodes=MCOBU',
    sobre: 'Hotel rebatizado (ex-B Resort) na ÃƒÂ¡rea Disney Springs; ofertas ativas na pÃƒÂ¡gina da rede.',
    oQueTem: ['Tarifas promocionais', 'Pacotes sazonais', 'BenefÃƒÂ­cios Marriott Bonvoy']
  },

  {
    id: 'wyndham-lake-buena-vista-offers',
    titulo: 'Wyndham Lake Buena Vista Ã¢â‚¬â€œ Deals',
    descricao: 'Tarifas promocionais prÃƒÂ³ximo ÃƒÂ  Disney.',
    categoria: 'hoteis',
    parceiro: 'Wyndham',
    link: 'https://www.wyndhamlakebuenavista.com/specials/',
    sobre: 'Hotel vizinho a Disney Springs, com passarela de acesso.',
    oQueTem: ['Quartos familiares', 'Acesso prÃƒÂ¡tico a lojas', 'Tarifas e combos sazonais'],
  },
  {
    id: 'rosen-shingle-creek-offers',
    titulo: 'Rosen Shingle Creek Ã¢â‚¬â€œ Offers',
    descricao: 'Pacotes e tarifas especiais.',
    categoria: 'hoteis',
    parceiro: 'Rosen Hotels',
    link: 'https://www.rosenshinglecreek.com/specials-packages/',
    sobre: 'Resort completo com campo de golfe e estrutura de convenÃƒÂ§ÃƒÂµes.',
    oQueTem: ['Piscinas e lazer', 'Restaurantes no local', 'Pacotes e cÃƒÂ³digos de desconto'],
  },

  // ============= TRANSPORTE =============
  {
    id: 'lynx-fares',
    titulo: 'LYNX Bus Ã¢â‚¬â€œ Fares & Passes',
    descricao: 'Passes e informaÃƒÂ§ÃƒÂµes de tarifas do transporte pÃƒÂºblico.',
    categoria: 'transporte',
    parceiro: 'LYNX',
    link: 'https://www.golynx.com/fares-passes/',
    sobre: 'Sistema de ÃƒÂ´nibus pÃƒÂºblico da regiÃƒÂ£o de Orlando.',
    oQueTem: ['Day/Week passes', 'Linhas por toda a cidade'],
  },
  {
    id: 'i-ride-trolley',
    titulo: 'I-RIDE Trolley Ã¢â‚¬â€œ Fares & Passes',
    descricao: 'PÃƒÂ¡gina oficial com tarifas e compra de passes.',
    categoria: 'transporte',
    parceiro: 'International Drive Orlando',
    link: 'https://www.internationaldriveorlando.com/iride-trolley/',
    sobre: 'Bonde turÃƒÂ­stico que percorre a International Drive.',
    oQueTem: ['Rotas Green/Red', 'Comprar passes', 'Mapa e horÃƒÂ¡rios'],
  },
  {
    id: 'alamo-mco-deals',
    titulo: 'Alamo Rent A Car Ã¢â‚¬â€œ Deals',
    descricao: 'Ofertas e cÃƒÂ³digos para aluguel.',
    categoria: 'transporte',
    parceiro: 'Alamo',
    link: 'https://www.alamo.com/en_US/car-rental/deals/us.html',
    sobre: 'Locadora com balcÃƒÂµes no Aeroporto de Orlando (MCO).',
    oQueTem: ['Frota variada', 'CÃƒÂ³digos promocionais'],
  },
  {
    id: 'lyft-promo',
    titulo: 'Lyft Ã¢â‚¬â€œ Promo & Credits',
    descricao: 'Novidades e crÃƒÂ©ditos promocionais.',
    categoria: 'transporte',
    parceiro: 'Lyft',
    link: 'https://www.lyft.com/rider/promo',
    sobre: 'Aplicativo de mobilidade urbana.',
    oQueTem: ['CrÃƒÂ©ditos', 'Categorias variadas'],
  },
  {
    id: 'uber-one-br',
    titulo: 'Uber Ã¢â‚¬â€œ Uber One (benefÃƒÂ­cios)',
    descricao: 'PÃƒÂ¡gina oficial (PT-BR) com como assinar e benefÃƒÂ­cios do Uber One.',
    categoria: 'transporte',
    parceiro: 'Uber',
    link: 'https://help.uber.com/pt-BR/riders/article/como-posso-fazer-a-assinatura-do-uber-one?nodeId=7d93e091-805e-44a3-9ce8-31c736a01e23',
    sobre: 'Programa de assinatura com vantagens em viagens e entregas (disponibilidade varia por regiÃƒÂ£o).',
    oQueTem: ['Como assinar', 'Principais benefÃƒÂ­cios', 'Gerenciar/cancelar'],
  },

  // ============= OUTROS / ATRAÃƒâ€¡Ãƒâ€¢ES =============
  {
    id: 'crayola-experience',
    titulo: 'Crayola Experience Ã¢â‚¬â€œ Special Offers',
    descricao: 'Cupons e promoÃƒÂ§ÃƒÂµes da atraÃƒÂ§ÃƒÂ£o indoor.',
    categoria: 'outros',
    parceiro: 'Crayola',
    link: 'https://www.crayolaexperience.com/orlando/plan-your-visit/special-offers',
    sobre: 'AtraÃƒÂ§ÃƒÂ£o coberta com atividades criativas para crianÃƒÂ§as.',
    oQueTem: ['Oficinas e artes interativas', 'Loja temÃƒÂ¡tica', 'Cupons sazonais'],
  },
  {
    id: 'madame-tussauds-orlando',
    titulo: 'Madame Tussauds Orlando Ã¢â‚¬â€œ Tickets',
    descricao: 'Ingressos e combos oficiais.',
    categoria: 'outros',
    parceiro: 'Merlin Entertainments',
    link: 'https://www.madametussauds.com/orlando/tickets/',
    sobre: 'Museu de cera com personalidades do cinema, mÃƒÂºsica e esportes.',
    oQueTem: ['Combos com SEA LIFE/The Wheel', 'Ingressos datados', 'ExposiÃƒÂ§ÃƒÂµes temÃƒÂ¡ticas'],
  },
  {
    id: 'sea-life-orlando',
    titulo: 'SEA LIFE Orlando Ã¢â‚¬â€œ Tickets & Passes',
    descricao: 'Ofertas e combos com outras atraÃƒÂ§ÃƒÂµes.',
    categoria: 'outros',
    parceiro: 'Merlin Entertainments',
    link: 'https://www.visitsealife.com/orlando/tickets-passes/',
    sobre: 'AquÃƒÂ¡rio com tÃƒÂºneis e tanques de espÃƒÂ©cies marinhas.',
    oQueTem: ['Ingressos e combos', 'ExperiÃƒÂªncias educativas', 'Local no ICON Park'],
  },
  {
    id: 'wonderworks-orlando',
    titulo: 'WonderWorks Orlando Ã¢â‚¬â€œ Coupons',
    descricao: 'Cupons oficiais e combos.',
    categoria: 'outros',
    parceiro: 'WonderWorks',
    link: 'https://www.wonderworksonline.com/orlando/coupons/',
    sobre: 'AtraÃƒÂ§ÃƒÂ£o indoor Ã¢â‚¬Å“casa de cabeÃƒÂ§a para baixoÃ¢â‚¬Â com atividades interativas.',
    oQueTem: ['Brincadeiras educativas', 'Laser tag/cordas (planos)', 'Cupons no site'],
  },

  // ============= PASSES / REVENDEDORES =============
  {
    id: 'undercover-tourist-orlando',
    titulo: 'Undercover Tourist Ã¢â‚¬â€œ Orlando Tickets Deals',
    descricao: 'Ingressos de parques com desconto (Disney, Universal, SeaWorld).',
    categoria: 'parques',
    parceiro: 'Undercover Tourist',
    link: 'https://www.undercovertourist.com/orlando/',
    sobre: 'Revendedor autorizado de ingressos com preÃƒÂ§os abaixo da bilheteria.',
    oQueTem: ['Disney/Universal/SeaWorld', 'E-tickets', 'Ofertas sazonais'],
  },
  {
    id: 'best-of-orlando',
    titulo: 'BestOfOrlando Ã¢â‚¬â€œ Deals',
    descricao: 'Ofertas em ingressos de parques e atraÃƒÂ§ÃƒÂµes (parceiro do Visit Orlando).',
    categoria: 'parques',
    parceiro: 'BestOfOrlando',
    link: 'https://www.bestoforlando.com/',
    sobre: 'Plataforma com combos e promoÃƒÂ§ÃƒÂµes frequentes.',
    oQueTem: ['Ingressos com desconto', 'Combos de atraÃƒÂ§ÃƒÂµes', 'Ofertas por tempo limitado'],
  },
];
