import type { Promocao } from "./promocao";

// 1 item por domÃ­nio; sÃ³ pÃ¡ginas que abrem e levam a ofertas/benefÃ­cios.
export const PROMOCOES: (Promocao & { sobre?: string; oQueTem?: string[] })[] = [
  // ============= COMPRAS =============
  {
    id: 'orlando-intl-premium-outlets',
    titulo: 'Orlando International Premium Outlets â€“ Deals',
    descricao: 'PÃ¡gina oficial de ofertas do maior outlet da I-Drive.',
    categoria: 'compras',
    parceiro: 'Simon Premium Outlets',
    link: 'https://www.premiumoutlets.com/outlet/orlando-international/deals',
    sobre: 'O maior outlet da International Drive, com dezenas de marcas populares e premium em formato ao ar livre.',
    oQueTem: ['Lojas Ã¢ncora e grifes', 'PraÃ§a de alimentaÃ§Ã£o', 'Cupons e deals oficiais no site'],
  },
  {
    id: 'the-florida-mall-deals',
    titulo: 'The Florida Mall â€“ Deals & Steals',
    descricao: 'Ofertas e cupons no maior shopping de Orlando.',
    categoria: 'compras',
    parceiro: 'Simon',
    link: 'https://www.simon.com/mall/the-florida-mall/deals',
    sobre: 'Shopping coberto com centenas de lojas e experiÃªncias para famÃ­lia.',
    oQueTem: ['Lojas Ã¢ncora e boutiques', 'AlimentaÃ§Ã£o variada', 'Eventos e promoÃ§Ãµes sazonais'],
  },
  {
    id: 'lake-buena-vista-factory-stores',
    titulo: 'Lake Buena Vista Factory Stores â€“ Deals (PT-BR)',
    descricao: 'PÃ¡gina de ofertas dos outlets de Lake Buena Vista (em portuguÃªs).',
    categoria: 'compras',
    parceiro: 'LBVFS',
    link: 'https://lbvfs.com/deals/?lang=pt-br',
    sobre: 'Conjunto de outlets prÃ³ximo Ã  Disney com estacionamento fÃ¡cil.',
    oQueTem: ['Lojas de roupas e calÃ§ados', 'Ofertas ativas por loja', 'OpÃ§Ãµes de alimentaÃ§Ã£o prÃ³ximas'],
  },
  {
    id: 'mall-at-millenia-events',
    titulo: 'The Mall at Millenia â€“ Offers/Events',
    descricao: 'PÃ¡gina de novidades e promoÃ§Ãµes sazonais.',
    categoria: 'compras',
    parceiro: 'Mall at Millenia',
    link: 'https://www.mallatmillenia.com/events/',
    sobre: 'Shopping premium e sofisticado com Ã¢ncoras de luxo.',
    oQueTem: ['Marcas de alto padrÃ£o', 'Restaurantes e cafÃ©s', 'Eventos e vitrines especiais'],
  },
{
  id: 'icon-park-shopping-deals',
  titulo: 'ICON Park â€“ Shopping Deals',
  descricao: 'Cupons/combos para lojas e atraÃ§Ãµes no complexo.',
  categoria: 'compras',
  parceiro: 'ICON Park',
  link: 'https://iconparkorlando.com/deals/',
  sobre: 'Complexo de lazer na I-Drive com lojas, restaurantes e atraÃ§Ãµes.',
  oQueTem: ['Lojas temÃ¡ticas', 'Combos com atraÃ§Ãµes', 'Restaurantes e bares'],
},

{
  id: 'visitorlando-shopping',
  titulo: 'Visit Orlando â€“ Ofertas (PT)',
  descricao: 'PÃ¡gina oficial de ofertas em portuguÃªs (use o filtro para â€œComprasâ€).',
  categoria: 'compras',
  parceiro: 'Visit Orlando',
  link: 'https://pt.visitorlando.com/ofertas/',
  sobre: 'Portal oficial de turismo de Orlando com ofertas ativas (em portuguÃªs).',
  oQueTem: ['Filtro por categoria (Compras)', 'Ofertas de lojas e outlets', 'PromoÃ§Ãµes atualizadas pelo Visit Orlando'],
},

  // ============= PARQUES =============
  {
    id: 'walt-disney-world-ofertas',
    titulo: 'Walt Disney World â€“ Ofertas e Descontos',
    descricao: 'Central oficial de ofertas: ingressos especiais e descontos em hotÃ©is.',
    categoria: 'parques',
    parceiro: 'Walt Disney World',
    link: 'https://disneyworld.disney.go.com/pt-br/special-offers/',
    sobre: 'Maior complexo de parques do mundo, com ofertas sazonais.',
    oQueTem: ['Ingressos promocionais', 'Descontos em hotÃ©is', 'BenefÃ­cios para pÃºblicos elegÃ­veis'],
  },


  {
    id: 'universal-orlando-deals',
    titulo: 'Universal Orlando â€“ Deals & Specials',
    descricao: 'Ofertas oficiais de ingressos e pacotes.',
    categoria: 'parques',
    parceiro: 'Universal Orlando',
    link: 'https://www.universalorlando.com/web/en/us/all-products',
    sobre: 'Hub oficial de produtos com seÃ§Ã£o de â€œDeals & Specialsâ€ sempre ativa.',
    oQueTem: ['Ofertas multi-dia', 'Pacotes com hotel', 'PromoÃ§Ãµes sazonais'],
  },



  {
    id: 'seaworld-orlando-ofertas',
    titulo: 'SeaWorld Orlando â€“ Special Offers',
    descricao: 'PÃ¡gina oficial com descontos, combos e passes.',
    categoria: 'parques',
    parceiro: 'SeaWorld Orlando',
    link: 'https://seaworld.com/orlando/special-offers/',
    sobre: 'Parque marinho com montanhas-russas e eventos sazonais.',
    oQueTem: ['Passes anuais', 'Combos com Aquatica/Discovery Cove', 'Ofertas por perÃ­odo'],
  },
  {
    id: 'discovery-cove-deals',
    titulo: 'Discovery Cove â€“ Day Resort Packages',
    descricao: 'Pacotes all-inclusive e ofertas sazonais.',
    categoria: 'parques',
    parceiro: 'Discovery Cove',
    link: 'https://discoverycove.com/orlando/day-resort-packages/',
    sobre: 'ExperiÃªncia de dia inteiro com lagoas, snorkel e interaÃ§Ã£o com animais.',
    oQueTem: ['RefeiÃ§Ãµes incluÃ­das', 'OpÃ§Ã£o com golfinhos', 'Combos com SeaWorld/Aquatica'],
  },
  {
    id: 'aquatica-orlando-ofertas',
    titulo: 'Aquatica Orlando â€“ Limited-Time Offers',
    descricao: 'Descontos e combos oficiais do parque aquÃ¡tico.',
    categoria: 'parques',
    parceiro: 'Aquatica',
    link: 'https://aquatica.com/orlando/limited-time-offers/',
    sobre: 'Parque aquÃ¡tico com toboÃ¡guas e Ã¡reas infantis.',
    oQueTem: ['Ingressos com desconto', 'All-Day Dining (add-on)', 'Combos com SeaWorld'],
  },

  {
    id: 'fun-spot-orlando-specials',
    titulo: 'Fun Spot America Orlando â€“ Ofertas',
    descricao: 'PÃ¡gina com eventos e promoÃ§Ãµes ativas em Orlando.',
    categoria: 'parques',
    parceiro: 'Fun Spot',
    link: 'https://fun-spot.com/category/orlando-events/',
    sobre: 'Parque familiar com karts e atraÃ§Ãµes radicais.',
    oQueTem: ['Passes e descontos sazonais', 'Eventos em Orlando', 'Ofertas por tempo limitado'],
  },

  {
    id: 'gatorland-specials',
    titulo: 'Gatorland â€“ Coupons & Specials',
    descricao: 'Cupons oficiais e ofertas para o â€œAlligator Capitalâ€.',
    categoria: 'parques',
    parceiro: 'Gatorland',
    link: 'https://www.gatorland.com/specials/',
    sobre: 'Parque temÃ¡tico de vida selvagem da FlÃ³rida.',
    oQueTem: ['Cupons no site', 'Zip line e experiÃªncias', 'Shows e trilhas'],
  },
  {
    id: 'legoland-florida-deals',
    titulo: 'LEGOLAND Florida â€“ Tickets & Passes',
    descricao: 'PÃ¡gina oficial de ingressos e passes (link estÃ¡vel, sem 404).',
    categoria: 'parques',
    parceiro: 'LEGOLAND',
    link: 'https://www.legoland.com/florida/tickets-passes/',
    sobre: 'Ingressos e passes com preÃ§os atualizados; a pÃ¡gina tambÃ©m destaca ofertas e eventos sazonais.',
    oQueTem: ['Ingressos datados', 'Passes anuais', 'Extras como FasTrack e cabanas']
  }
  ,

  // ============= RESTAURANTES/COMPLEXOS =============
  {
    id: 'magical-dining',
    titulo: 'Visit Orlandoâ€™s Magical Dining',
    descricao: 'Menu fixo com preÃ§o promocional (sazonal).',
    categoria: 'restaurantes',
    parceiro: 'Visit Orlando',
    link: 'https://www.magicaldining.com/',
    sobre: 'Evento anual com menus fechados em restaurantes selecionados.',
    oQueTem: ['PreÃ§o fixo por pessoa', 'Lista de restaurantes participantes', 'PerÃ­odo sazonal'],
  },
  {
    id: 'the-boathouse-specials',
    titulo: 'The BOATHOUSE â€“ Specials',
    descricao: 'Eventos e ofertas no restaurante Ã  beira do lago.',
    categoria: 'restaurantes',
    parceiro: 'The BOATHOUSE',
    link: 'https://theboathouseorlando.com/',
    sobre: 'Restaurante Ã  beira da Ã¡gua em Disney Springs.',
    oQueTem: ['Menu de peixes e carnes', 'Passeios de Amphicar (pago Ã  parte)', 'Eventos e reservas'],
  },

  // ============= HOTÃ‰IS =============
  {
    id: 'swan-dolphin-offers',
    titulo: 'Walt Disney World Swan & Dolphin â€“ Offers',
    descricao: 'Tarifas promocionais e pacotes.',
    categoria: 'hoteis',
    parceiro: 'Swan & Dolphin',
    link: 'https://swandolphin.com/offers/',
    sobre: 'HotÃ©is dentro do complexo Disney operados por terceiros.',
    oQueTem: ['LocalizaÃ§Ã£o privilegiada', 'Restaurantes e spa', 'Ofertas diretas no site'],
  },
  {
    id: 'four-seasons-orlando-offers',
    titulo: 'Four Seasons Orlando â€“ Offers',
    descricao: 'Pacotes de luxo com benefÃ­cios.',
    categoria: 'hoteis',
    parceiro: 'Four Seasons',
    link: 'https://www.fourseasons.com/orlando/offers/',
    sobre: 'Hotel 5 estrelas dentro do complexo, foco em luxo e serviÃ§os.',
    oQueTem: ['Piscinas e lazy river', 'Kids club e spa', 'Pacotes com crÃ©dito de resort'],
  },
  {
    id: 'renaissance-disney-springs-offers',
    titulo: 'Renaissance Orlando Resort â€“ Ofertas (ex-B Resort)',
    descricao: 'PÃ¡gina oficial de ofertas do hotel (Marriott).',
    categoria: 'hoteis',
    parceiro: 'Marriott / Renaissance',
    link: 'https://www.marriott.com/offers/findOffers.mi?propertycodes=MCOBU',
    sobre: 'Hotel rebatizado (ex-B Resort) na Ã¡rea Disney Springs; ofertas ativas na pÃ¡gina da rede.',
    oQueTem: ['Tarifas promocionais', 'Pacotes sazonais', 'BenefÃ­cios Marriott Bonvoy']
  },

  {
    id: 'wyndham-lake-buena-vista-offers',
    titulo: 'Wyndham Lake Buena Vista â€“ Deals',
    descricao: 'Tarifas promocionais prÃ³ximo Ã  Disney.',
    categoria: 'hoteis',
    parceiro: 'Wyndham',
    link: 'https://www.wyndhamlakebuenavista.com/specials/',
    sobre: 'Hotel vizinho a Disney Springs, com passarela de acesso.',
    oQueTem: ['Quartos familiares', 'Acesso prÃ¡tico a lojas', 'Tarifas e combos sazonais'],
  },
  {
    id: 'rosen-shingle-creek-offers',
    titulo: 'Rosen Shingle Creek â€“ Offers',
    descricao: 'Pacotes e tarifas especiais.',
    categoria: 'hoteis',
    parceiro: 'Rosen Hotels',
    link: 'https://www.rosenshinglecreek.com/specials-packages/',
    sobre: 'Resort completo com campo de golfe e estrutura de convenÃ§Ãµes.',
    oQueTem: ['Piscinas e lazer', 'Restaurantes no local', 'Pacotes e cÃ³digos de desconto'],
  },

  // ============= TRANSPORTE =============
  {
    id: 'lynx-fares',
    titulo: 'LYNX Bus â€“ Fares & Passes',
    descricao: 'Passes e informaÃ§Ãµes de tarifas do transporte pÃºblico.',
    categoria: 'transporte',
    parceiro: 'LYNX',
    link: 'https://www.golynx.com/fares-passes/',
    sobre: 'Sistema de Ã´nibus pÃºblico da regiÃ£o de Orlando.',
    oQueTem: ['Day/Week passes', 'Linhas por toda a cidade'],
  },
  {
    id: 'i-ride-trolley',
    titulo: 'I-RIDE Trolley â€“ Fares & Passes',
    descricao: 'PÃ¡gina oficial com tarifas e compra de passes.',
    categoria: 'transporte',
    parceiro: 'International Drive Orlando',
    link: 'https://www.internationaldriveorlando.com/iride-trolley/',
    sobre: 'Bonde turÃ­stico que percorre a International Drive.',
    oQueTem: ['Rotas Green/Red', 'Comprar passes', 'Mapa e horÃ¡rios'],
  },
  {
    id: 'alamo-mco-deals',
    titulo: 'Alamo Rent A Car â€“ Deals',
    descricao: 'Ofertas e cÃ³digos para aluguel.',
    categoria: 'transporte',
    parceiro: 'Alamo',
    link: 'https://www.alamo.com/en_US/car-rental/deals/us.html',
    sobre: 'Locadora com balcÃµes no Aeroporto de Orlando (MCO).',
    oQueTem: ['Frota variada', 'CÃ³digos promocionais'],
  },
  {
    id: 'lyft-promo',
    titulo: 'Lyft â€“ Promo & Credits',
    descricao: 'Novidades e crÃ©ditos promocionais.',
    categoria: 'transporte',
    parceiro: 'Lyft',
    link: 'https://www.lyft.com/rider/promo',
    sobre: 'Aplicativo de mobilidade urbana.',
    oQueTem: ['CrÃ©ditos', 'Categorias variadas'],
  },
  {
    id: 'uber-one-br',
    titulo: 'Uber â€“ Uber One (benefÃ­cios)',
    descricao: 'PÃ¡gina oficial (PT-BR) com como assinar e benefÃ­cios do Uber One.',
    categoria: 'transporte',
    parceiro: 'Uber',
    link: 'https://help.uber.com/pt-BR/riders/article/como-posso-fazer-a-assinatura-do-uber-one?nodeId=7d93e091-805e-44a3-9ce8-31c736a01e23',
    sobre: 'Programa de assinatura com vantagens em viagens e entregas (disponibilidade varia por regiÃ£o).',
    oQueTem: ['Como assinar', 'Principais benefÃ­cios', 'Gerenciar/cancelar'],
  },

  // ============= OUTROS / ATRAÃ‡Ã•ES =============
  {
    id: 'crayola-experience',
    titulo: 'Crayola Experience â€“ Special Offers',
    descricao: 'Cupons e promoÃ§Ãµes da atraÃ§Ã£o indoor.',
    categoria: 'outros',
    parceiro: 'Crayola',
    link: 'https://www.crayolaexperience.com/orlando/plan-your-visit/special-offers',
    sobre: 'AtraÃ§Ã£o coberta com atividades criativas para crianÃ§as.',
    oQueTem: ['Oficinas e artes interativas', 'Loja temÃ¡tica', 'Cupons sazonais'],
  },
  {
    id: 'madame-tussauds-orlando',
    titulo: 'Madame Tussauds Orlando â€“ Tickets',
    descricao: 'Ingressos e combos oficiais.',
    categoria: 'outros',
    parceiro: 'Merlin Entertainments',
    link: 'https://www.madametussauds.com/orlando/tickets/',
    sobre: 'Museu de cera com personalidades do cinema, mÃºsica e esportes.',
    oQueTem: ['Combos com SEA LIFE/The Wheel', 'Ingressos datados', 'ExposiÃ§Ãµes temÃ¡ticas'],
  },
  {
    id: 'sea-life-orlando',
    titulo: 'SEA LIFE Orlando â€“ Tickets & Passes',
    descricao: 'Ofertas e combos com outras atraÃ§Ãµes.',
    categoria: 'outros',
    parceiro: 'Merlin Entertainments',
    link: 'https://www.visitsealife.com/orlando/tickets-passes/',
    sobre: 'AquÃ¡rio com tÃºneis e tanques de espÃ©cies marinhas.',
    oQueTem: ['Ingressos e combos', 'ExperiÃªncias educativas', 'Local no ICON Park'],
  },
  {
    id: 'wonderworks-orlando',
    titulo: 'WonderWorks Orlando â€“ Coupons',
    descricao: 'Cupons oficiais e combos.',
    categoria: 'outros',
    parceiro: 'WonderWorks',
    link: 'https://www.wonderworksonline.com/orlando/coupons/',
    sobre: 'AtraÃ§Ã£o indoor â€œcasa de cabeÃ§a para baixoâ€ com atividades interativas.',
    oQueTem: ['Brincadeiras educativas', 'Laser tag/cordas (planos)', 'Cupons no site'],
  },

  // ============= PASSES / REVENDEDORES =============
  {
    id: 'undercover-tourist-orlando',
    titulo: 'Undercover Tourist â€“ Orlando Tickets Deals',
    descricao: 'Ingressos de parques com desconto (Disney, Universal, SeaWorld).',
    categoria: 'parques',
    parceiro: 'Undercover Tourist',
    link: 'https://www.undercovertourist.com/orlando/',
    sobre: 'Revendedor autorizado de ingressos com preÃ§os abaixo da bilheteria.',
    oQueTem: ['Disney/Universal/SeaWorld', 'E-tickets', 'Ofertas sazonais'],
  },
  {
    id: 'best-of-orlando',
    titulo: 'BestOfOrlando â€“ Deals',
    descricao: 'Ofertas em ingressos de parques e atraÃ§Ãµes (parceiro do Visit Orlando).',
    categoria: 'parques',
    parceiro: 'BestOfOrlando',
    link: 'https://www.bestoforlando.com/',
    sobre: 'Plataforma com combos e promoÃ§Ãµes frequentes.',
    oQueTem: ['Ingressos com desconto', 'Combos de atraÃ§Ãµes', 'Ofertas por tempo limitado'],
  },
];
