// src/logic/blocos/parques/Universal/AlmocosUniversal.ts

export const almocosUniversal = [

  // FogosEpicoUniverse
  {
    nome: "Epic Feast Grill",
    regiao: "FogosEpicoUniverse",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  entrada principal do Epic Universe",
    precoMedio: 35,
    destaque: "CulinÃ¡ria americana com hambÃºrgueres e grelhados. Experimente o cheeseburger gourmet com batatas rÃºsticas.",
    latitude: 28.4801,
    longitude: -81.4650,
  },
  {
    nome: "Starlight Bistro",
    regiao: "FogosEpicoUniverse",
    tipo: "Tematico",
    acesso: "Ãrea central com vista para os fogos",
    precoMedio: 42,
    destaque: "Ambiente sofisticado com pratos exclusivos. Experimente o filÃ© de salmÃ£o com risoto de limÃ£o siciliano.",
    latitude: 28.4802,
    longitude: -81.4651,
  },
  {
    nome: "Universe Snacks",
    regiao: "FogosEpicoUniverse",
    tipo: "Economico",
    acesso: "Carrinho ao lado do Epic Plaza",
    precoMedio: 14,
    destaque: "Snacks rÃ¡pidos e econÃ´micos. Experimente o wrap de frango com molho especial.",
    latitude: 28.4803,
    longitude: -81.4652,
  },
  {
    nome: "Healthy Galaxy",
    regiao: "FogosEpicoUniverse",
    tipo: "Saudavel",
    acesso: "Perto do Epic Fountain Garden",
    precoMedio: 19,
    destaque: "Bowls leves com proteÃ­nas magras e saladas. Experimente o bowl de quinoa com frango grelhado e molho cÃ­trico.",
    latitude: 28.4804,
    longitude: -81.4653,
  },
    {
  nome: "Cosmic Comfort Diner",
  regiao: "FogosEpicoUniverse",
  tipo: "Conforto",
  acesso: "PrÃ³ximo ao Epic Plaza, Ã¡rea coberta e aconchegante",
  precoMedio: 25,
  destaque: "Pratos caseiros com toque americano, como mac and cheese e frango assado com legumes. Experimente o mac and cheese com crosta de parmesÃ£o.",
  latitude: 28.4805,
  longitude: -81.4654,
},


  // FogosIslandsOfAdventure
  {
  nome: "Island Comfort Kitchen",
  regiao: "FogosIslandsOfAdventure",
  tipo: "Conforto",
  acesso: "PrÃ³ximo Ã  Ã¡rea central com mesas ao ar livre",
  precoMedio: 24,
  destaque: "Comidas reconfortantes como ensopados e massas. Experimente o frango ao molho de ervas com purÃª.",
  latitude: 28.4745,
  longitude: -81.4675,
},
  {
    nome: "Island Grill House",
    regiao: "FogosIslandsOfAdventure",
    tipo: ["Classico", "Americano"],
    acesso: "Na entrada principal de Islands of Adventure",
    precoMedio: 34,
    destaque: "Pratos americanos com carnes grelhadas. Experimente o frango assado com batata e milho.",
    latitude: 28.4741,
    longitude: -81.4671,
  },
  {
    nome: "Adventure Tavern",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Tematico",
    acesso: "PrÃ³ximo Ã  Ã¡rea central do parque",
    precoMedio: 40,
    destaque: "CulinÃ¡ria inspirada em aventuras e sabores exÃ³ticos. Experimente o cordeiro assado com especiarias.",
    latitude: 28.4742,
    longitude: -81.4672,
  },
  {
    nome: "Island Snacks",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Economico",
    acesso: "Carrinho de lanches ao lado da lagoa principal",
    precoMedio: 13,
    destaque: "Snacks, sanduÃ­ches e wraps rÃ¡pidos. Experimente o wrap de peru com queijo suÃ­Ã§o.",
    latitude: 28.4743,
    longitude: -81.4673,
  },
  {
    nome: "Lagoon Greens",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Saudavel",
    acesso: "Caminho para Seuss Landing",
    precoMedio: 18,
    destaque: "Bowls e saladas com ingredientes frescos. Experimente a salada mediterrÃ¢nea com molho de limÃ£o.",
    latitude: 28.4744,
    longitude: -81.4674,
  },


  // FogosUniversalStudios
  {
    nome: "Studio Grill",
    regiao: "FogosUniversalStudios",
    tipo: ["Classico", "Americano"],
    acesso: "Logo na entrada do Universal Studios Florida",
    precoMedio: 36,
    destaque: "HambÃºrgueres e grelhados clÃ¡ssicos. Experimente o cheeseburger defumado com bacon crocante.",
    latitude: 28.4791,
    longitude: -81.4701,
  },
  {
    nome: "Cinematic CafÃ©",
    regiao: "FogosUniversalStudios",
    tipo: "Tematico",
    acesso: "PrÃ³ximo ao palco central de shows",
    precoMedio: 43,
    destaque: "Ambiente temÃ¡tico de cinema com pratos refinados. Experimente o steak com molho de cogumelos.",
    latitude: 28.4792,
    longitude: -81.4702,
  },
  {
    nome: "Quick Studio Snacks",
    regiao: "FogosUniversalStudios",
    tipo: "Economico",
    acesso: "Carrinho ao lado do lago principal",
    precoMedio: 12,
    destaque: "SanduÃ­ches, wraps e bebidas. Experimente o sanduÃ­che frio com peito de peru.",
    latitude: 28.4793,
    longitude: -81.4703,
  },
  {
    nome: "Healthy Reel",
    regiao: "FogosUniversalStudios",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo ao Universal Music Plaza",
    precoMedio: 19,
    destaque: "Bowls com proteÃ­nas magras e vegetais frescos. Experimente o bowl de salmÃ£o grelhado.",
    latitude: 28.4794,
    longitude: -81.4704,
  },
  {
  nome: "Universal Comfort CafÃ©",
  regiao: "FogosUniversalStudios",
  tipo: "Conforto",
  acesso: "Ao lado do Universal Music Plaza",
  precoMedio: 27,
  destaque: "OpÃ§Ãµes caseiras como sopas, massas e sanduÃ­ches quentes. Experimente o sanduÃ­che de frango com queijo cheddar derretido.",
  latitude: 28.4795,
  longitude: -81.4705,
},


  // Hollywood
  {
    nome: "Hollywood Grill",
    regiao: "Hollywood",
    tipo: ["Classico", "Americano"],
    acesso: "Na entrada da Ã¡rea Hollywood Boulevard",
    precoMedio: 33,
    destaque: "ClÃ¡ssicos americanos com estilo vintage. Experimente o cheeseburger com onion rings.",
    latitude: 28.4771,
    longitude: -81.4691,
  },
  {
    nome: "Cinema Star CafÃ©",
    regiao: "Hollywood",
    tipo: "Tematico",
    acesso: "Ao lado do Universal Studios Store",
    precoMedio: 39,
    destaque: "Pratos inspirados na era dourada de Hollywood. Experimente o frango assado com molho de ervas.",
    latitude: 28.4772,
    longitude: -81.4692,
  },
  {
    nome: "Hollywood Express",
    regiao: "Hollywood",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo Ã  entrada de atraÃ§Ãµes",
    precoMedio: 14,
    destaque: "Snacks rÃ¡pidos e sanduÃ­ches. Experimente o wrap de frango Caesar.",
    latitude: 28.4773,
    longitude: -81.4693,
  },
  {
    nome: "Hollywood Greens",
    regiao: "Hollywood",
    tipo: "Saudavel",
    acesso: "Perto do pÃ¡tio principal de Hollywood Boulevard",
    precoMedio: 18,
    destaque: "Saladas e bowls nutritivos. Experimente o bowl de frango com molho de mostarda e mel.",
    latitude: 28.4774,
    longitude: -81.4694,
  },
  {
  nome: "Hollywood Comfort Kitchen",
  regiao: "Hollywood",
  tipo: "Conforto",
  acesso: "Ãrea central da Hollywood Boulevard",
  precoMedio: 23,
  destaque: "Massas e sopas no estilo americano clÃ¡ssico. Experimente o macarrÃ£o ao molho de queijo com bacon.",
  latitude: 28.4775,
  longitude: -81.4695,
},

    // HowToTrainYourDragon
  {
    nome: "Viking Grill",
    regiao: "HowToTrainYourDragon",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  atraÃ§Ã£o Dragon Riders",
    precoMedio: 32,
    destaque: "Pratos rÃºsticos com carnes grelhadas. Experimente o peito de frango defumado com batatas rÃºsticas.",
    latitude: 28.4760,
    longitude: -81.4680,
  },
  {
    nome: "Berk Feast Hall",
    regiao: "HowToTrainYourDragon",
    tipo: "Tematico",
    acesso: "Ãrea central da vila dos vikings",
    precoMedio: 40,
    destaque: "CulinÃ¡ria inspirada na sÃ©rie 'Como Treinar seu DragÃ£o'. Experimente o ensopado de cordeiro com ervas.",
    latitude: 28.4761,
    longitude: -81.4681,
  },
  {
    nome: "Dragon Snacks",
    regiao: "HowToTrainYourDragon",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo ao playground infantil",
    precoMedio: 12,
    destaque: "Snacks rÃ¡pidos com inspiraÃ§Ã£o nÃ³rdica. Experimente o wrap de frango com molho agridoce.",
    latitude: 28.4762,
    longitude: -81.4682,
  },
  {
    nome: "Viking Greens",
    regiao: "HowToTrainYourDragon",
    tipo: "Saudavel",
    acesso: "Ao lado do Viking Market",
    precoMedio: 18,
    destaque: "Saladas e bowls com legumes frescos. Experimente o bowl de quinoa com frango grelhado.",
    latitude: 28.4763,
    longitude: -81.4683,
  },
  {
  nome: "Viking Comfort Hearth",
  regiao: "HowToTrainYourDragon",
  tipo: "Conforto",
  acesso: "Perto da Ã¡rea de descanso dos vikings",
  precoMedio: 26,
  destaque: "Pratos quentes e saborosos como ensopado de carne e sopas rÃºsticas. Experimente o ensopado de cordeiro com batatas.",
  latitude: 28.4764,
  longitude: -81.4684,
},


  // JurassicPark
  {
    nome: "Thunder Falls Terrace",
    regiao: "JurassicPark",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atraÃ§Ã£o River Adventure",
    precoMedio: 34,
    destaque: "Carnes e frangos grelhados com acompanhamentos. Experimente as costelas ao molho barbecue.",
    latitude: 28.4746,
    longitude: -81.4705,
  },
  {
    nome: "Raptor Grill",
    regiao: "JurassicPark",
    tipo: "Tematico",
    acesso: "PrÃ³ximo ao VelociCoaster",
    precoMedio: 39,
    destaque: "Ambiente prÃ©-histÃ³rico com carnes nobres. Experimente o bife Angus com batatas trufadas.",
    latitude: 28.4747,
    longitude: -81.4706,
  },
  {
    nome: "Dino Snacks",
    regiao: "JurassicPark",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo ao Discovery Center",
    precoMedio: 11,
    destaque: "Snacks rÃ¡pidos com tema jurÃ¡ssico. Experimente o wrap de frango com queijo cheddar.",
    latitude: 28.4748,
    longitude: -81.4707,
  },
  {
    nome: "Jurassic Greens",
    regiao: "JurassicPark",
    tipo: "Saudavel",
    acesso: "Ao lado da ponte para a Ã¡rea de King Kong",
    precoMedio: 17,
    destaque: "Bowls e saladas leves. Experimente a salada Caesar com frango grelhado.",
    latitude: 28.4749,
    longitude: -81.4708,
  },
  {
  nome: "Jurassic Comfort Grill",
  regiao: "JurassicPark",
  tipo: "Conforto",
  acesso: "Perto do Discovery Center",
  precoMedio: 24,
  destaque: "Comidas aconchegantes como massas e pratos com molhos cremosos. Experimente o macarrÃ£o com frango e cogumelos.",
  latitude: 28.4750,
  longitude: -81.4709,
},


  // LostContinent
  {
    nome: "Mythos Restaurant",
    regiao: "LostContinent",
    tipo: ["Classico", "Americano"],
    acesso: "No coraÃ§Ã£o da Ã¡rea Lost Continent",
    precoMedio: 38,
    destaque: "Pratos mediterrÃ¢neos com um toque moderno. Experimente o cordeiro assado com purÃª de batata.",
    latitude: 28.4742,
    longitude: -81.4690,
  },
  {
    nome: "Poseidonâ€™s Diner",
    regiao: "LostContinent",
    tipo: "Tematico",
    acesso: "PrÃ³ximo Ã  atraÃ§Ã£o Poseidonâ€™s Fury",
    precoMedio: 41,
    destaque: "CulinÃ¡ria do mar com peixes e frutos do mar frescos. Experimente o salmÃ£o grelhado com molho de ervas.",
    latitude: 28.4743,
    longitude: -81.4691,
  },
  {
    nome: "Lost Snacks",
    regiao: "LostContinent",
    tipo: "Economico",
    acesso: "Ao lado da entrada de Mythos",
    precoMedio: 13,
    destaque: "Snacks e lanches rÃ¡pidos. Experimente o wrap de carne com queijo.",
    latitude: 28.4744,
    longitude: -81.4692,
  },
  {
    nome: "Mediterranean Greens",
    regiao: "LostContinent",
    tipo: "Saudavel",
    acesso: "Carrinho prÃ³ximo Ã  Ã¡rea central",
    precoMedio: 18,
    destaque: "Saladas e bowls inspirados na culinÃ¡ria grega. Experimente o bowl de tabule com frango grelhado.",
    latitude: 28.4745,
    longitude: -81.4693,
  },
{
  nome: "Lost Comfort Tavern",
  regiao: "LostContinent",
  tipo: "Conforto",
  acesso: "No corredor principal perto da Mythos",
  precoMedio: 22,
  destaque: "Comida mediterrÃ¢nea com toque caseiro, incluindo sopas e pÃ£es frescos. Experimente a sopa de lentilhas com especiarias.",
  latitude: 28.4746,
  longitude: -81.4694,
},

  // MarvelSuperHeroIsland
  {
    nome: "Captain America Diner",
    regiao: "MarvelSuperHeroIsland",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  atraÃ§Ã£o The Amazing Adventures of Spider-Man",
    precoMedio: 30,
    destaque: "HambÃºrgueres e lanches em estilo americano. Experimente o hambÃºrguer do CapitÃ£o AmÃ©rica com cheddar.",
    latitude: 28.4750,
    longitude: -81.4710,
  },
  {
    nome: "Heroes Grill",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Tematico",
    acesso: "Ãrea central, prÃ³xima ao cafÃ© do Homem de Ferro",
    precoMedio: 38,
    destaque: "Pratos inspirados nos herÃ³is da Marvel. Experimente o frango ao molho teriyaki com arroz jasmim.",
    latitude: 28.4751,
    longitude: -81.4711,
  },
  {
    nome: "Avengers Snacks",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo Ã  entrada da Hulk Coaster",
    precoMedio: 12,
    destaque: "Snacks temÃ¡ticos para um lanche rÃ¡pido. Experimente o wrap de presunto com queijo suÃ­Ã§o.",
    latitude: 28.4752,
    longitude: -81.4712,
  },
  {
    nome: "Marvel Greens",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Saudavel",
    acesso: "Ao lado da saÃ­da da Hulk Coaster",
    precoMedio: 17,
    destaque: "Bowls com proteÃ­nas e vegetais frescos. Experimente a salada Caesar com frango.",
    latitude: 28.4753,
    longitude: -81.4713,
  },
  {
  nome: "Hero Comfort CafÃ©",
  regiao: "MarvelSuperHeroIsland",
  tipo: "Conforto",
  acesso: "PrÃ³ximo Ã  Hulk Coaster",
  precoMedio: 23,
  destaque: "SanduÃ­ches quentes, massas e sopas inspiradas em herÃ³is. Experimente o sanduÃ­che de rosbife com queijo cheddar.",
  latitude: 28.4754,
  longitude: -81.4714,
},

    // MinionsLand
  {
    nome: "Minion CafÃ©",
    regiao: "MinionsLand",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  atraÃ§Ã£o Despicable Me Minion Mayhem",
    precoMedio: 28,
    destaque: "Pratos divertidos e coloridos inspirados nos Minions. Experimente o mac and cheese com bacon crocante.",
    latitude: 28.4775,
    longitude: -81.4705,
  },
  {
  nome: "Minion Comfort Spot",
  regiao: "MinionsLand",
  tipo: "Conforto",
  acesso: "Ao lado do Minion CafÃ©",
  precoMedio: 20,
  destaque: "Pratos quentes e reconfortantes com o toque divertido dos Minions. Experimente o macarrÃ£o com queijo e crocante de bacon.",
  latitude: 28.4779,
  longitude: -81.4709,
},

  {
    nome: "Gruâ€™s Kitchen",
    regiao: "MinionsLand",
    tipo: "Tematico",
    acesso: "Ao lado da Minion Mart",
    precoMedio: 34,
    destaque: "CulinÃ¡ria criativa com decoraÃ§Ã£o do laboratÃ³rio de Gru. Experimente o frango ao molho de queijo especial.",
    latitude: 28.4776,
    longitude: -81.4706,
  },
  {
    nome: "Minion Snacks",
    regiao: "MinionsLand",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo Ã  entrada da atraÃ§Ã£o Minion Mayhem",
    precoMedio: 12,
    destaque: "Snacks rÃ¡pidos e sobremesas divertidas. Experimente o cookie em formato de Minion.",
    latitude: 28.4777,
    longitude: -81.4707,
  },
  {
    nome: "Minion Greens",
    regiao: "MinionsLand",
    tipo: "Saudavel",
    acesso: "Ãrea lateral da MinionsLand",
    precoMedio: 16,
    destaque: "Bowls e saladas com ingredientes frescos. Experimente a salada Caesar com frango grelhado.",
    latitude: 28.4778,
    longitude: -81.4708,
  },

  // NewYork
  {
    nome: "Lombardâ€™s Seafood Grille",
    regiao: "NewYork",
    tipo: ["Classico", "Americano"],
    acesso: "Em frente ao lago principal de New York",
    precoMedio: 38,
    destaque: "Especializado em frutos do mar frescos. Experimente o prato de camarÃµes ao alho com arroz cremoso.",
    latitude: 28.4780,
    longitude: -81.4710,
  },
  {
    nome: "Big Apple Deli",
    regiao: "NewYork",
    tipo: "Tematico",
    acesso: "PrÃ³ximo Ã  Ã¡rea de shows ao ar livre",
    precoMedio: 32,
    destaque: "SanduÃ­ches artesanais inspirados em Nova York. Experimente o pastrami com mostarda e picles.",
    latitude: 28.4781,
    longitude: -81.4711,
  },
  {
    nome: "NYC Snacks",
    regiao: "NewYork",
    tipo: "Economico",
    acesso: "Carrinho ao lado da fachada do Ghostbusters",
    precoMedio: 10,
    destaque: "Snacks prÃ¡ticos e econÃ´micos. Experimente o hot dog com ketchup e mostarda.",
    latitude: 28.4782,
    longitude: -81.4712,
  },
  {
    nome: "Central Park Greens",
    regiao: "NewYork",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo Ã  entrada de atraÃ§Ãµes clÃ¡ssicas",
    precoMedio: 17,
    destaque: "Saladas leves e wraps vegetarianos. Experimente a salada de quinoa com tomate e pepino.",
    latitude: 28.4783,
    longitude: -81.4713,
  },
  {
  nome: "NY Comfort Deli",
  regiao: "NewYork",
  tipo: "Conforto",
  acesso: "PrÃ³ximo ao lago central da Ã¡rea de New York",
  precoMedio: 25,
  destaque: "Comidas tradicionais de Nova York como sopas e sanduÃ­ches quentes. Experimente o clÃ¡ssico sanduÃ­che de pastrami.",
  latitude: 28.4784,
  longitude: -81.4714,
},


  // ProductionCentral
  {
    nome: "Soundstage Grill",
    regiao: "ProductionCentral",
    tipo: ["Classico", "Americano"],
    acesso: "Na Ã¡rea principal de Production Central",
    precoMedio: 33,
    destaque: "HambÃºrgueres e grelhados para fÃ£s de cinema. Experimente o cheeseburger com batata frita rÃºstica.",
    latitude: 28.4790,
    longitude: -81.4720,
  },
  {
    nome: "Directorâ€™s Cut CafÃ©",
    regiao: "ProductionCentral",
    tipo: "Tematico",
    acesso: "Ao lado do simulador Transformers",
    precoMedio: 39,
    destaque: "Pratos exclusivos com toque cinematogrÃ¡fico. Experimente o frango grelhado com molho de ervas.",
    latitude: 28.4791,
    longitude: -81.4721,
  },
  {
    nome: "Studio Express",
    regiao: "ProductionCentral",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo Ã  entrada do parque",
    precoMedio: 11,
    destaque: "SanduÃ­ches e wraps rÃ¡pidos. Experimente o wrap de peru com molho Caesar.",
    latitude: 28.4792,
    longitude: -81.4722,
  },
  {
    nome: "Fit Stage Bowls",
    regiao: "ProductionCentral",
    tipo: "Saudavel",
    acesso: "Ãrea lateral de Production Central",
    precoMedio: 18,
    destaque: "Bowls nutritivos e sucos detox. Experimente o bowl de salmÃ£o com arroz integral.",
    latitude: 28.4793,
    longitude: -81.4723,
  },
  {
  nome: "Production Comfort CafÃ©",
  regiao: "ProductionCentral",
  tipo: "Conforto",
  acesso: "PrÃ³ximo Ã  entrada do parque",
  precoMedio: 22,
  destaque: "Massas, sopas e pratos com sabor caseiro. Experimente a lasanha com molho de tomate rÃºstico.",
  latitude: 28.4794,
  longitude: -81.4724,
},


  // SanFrancisco
  {
    nome: "Richterâ€™s Burger Co.",
    regiao: "SanFrancisco",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  atraÃ§Ã£o Fast & Furious â€“ Supercharged",
    precoMedio: 35,
    destaque: "HambÃºrgueres artesanais com batatas fritas. Experimente o hambÃºrguer duplo com cheddar.",
    latitude: 28.4785,
    longitude: -81.4730,
  },
  {
    nome: "Pier 41 Seafood",
    regiao: "SanFrancisco",
    tipo: "Tematico",
    acesso: "Na Ã¡rea do pier principal",
    precoMedio: 42,
    destaque: "Pratos com frutos do mar frescos. Experimente a sopa de clam chowder no pÃ£o italiano.",
    latitude: 28.4786,
    longitude: -81.4731,
  },
  {
    nome: "Bay Snacks",
    regiao: "SanFrancisco",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo ao Fast & Furious",
    precoMedio: 12,
    destaque: "Snacks rÃ¡pidos com vista para o lago. Experimente o wrap de frango com alface e tomate.",
    latitude: 28.4787,
    longitude: -81.4732,
  },
  {
    nome: "Golden Gate Greens",
    regiao: "SanFrancisco",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo Ã  Ã¡rea de shows aquÃ¡ticos",
    precoMedio: 19,
    destaque: "Saladas frescas e wraps vegetarianos. Experimente a salada de quinoa com amÃªndoas.",
    latitude: 28.4788,
    longitude: -81.4733,
  },
  {
  nome: "Bay Comfort Kitchen",
  regiao: "SanFrancisco",
  tipo: "Conforto",
  acesso: "Na Ã¡rea principal do pier",
  precoMedio: 27,
  destaque: "Comida caseira com pratos como frango assado e purÃª de batata. Experimente o frango grelhado com ervas.",
  latitude: 28.4789,
  longitude: -81.4734,
},

  // SeussLanding
  {
    nome: "Circus McGurkus CafÃ© Stoo-pendous",
    regiao: "SeussLanding",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atraÃ§Ã£o The High in the Sky Seuss Trolley Train Ride",
    precoMedio: 29,
    destaque: "Pratos coloridos e divertidos inspirados no universo Dr. Seuss. Experimente o macarrÃ£o com queijo e nuggets crocantes.",
    latitude: 28.4795,
    longitude: -81.4740,
  },
  {
    nome: "Green Eggs and Ham CafÃ©",
    regiao: "SeussLanding",
    tipo: "Tematico",
    acesso: "PrÃ³ximo Ã  entrada principal da Ã¡rea Seuss Landing",
    precoMedio: 27,
    destaque: "CardÃ¡pio criativo com ovos verdes e sanduÃ­ches temÃ¡ticos. Experimente o prato de ovos verdes com presunto.",
    latitude: 28.4796,
    longitude: -81.4741,
  },
  {
    nome: "Seuss Snacks",
    regiao: "SeussLanding",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo Ã  Ã¡rea de recreaÃ§Ã£o infantil",
    precoMedio: 12,
    destaque: "Snacks divertidos e coloridos. Experimente o cookie do Lorax com gotas de chocolate.",
    latitude: 28.4797,
    longitude: -81.4742,
  },
  {
    nome: "Whoville Greens",
    regiao: "SeussLanding",
    tipo: "Saudavel",
    acesso: "Ao lado do If I Ran the Zoo",
    precoMedio: 18,
    destaque: "Bowls e saladas leves com toque criativo. Experimente a salada com frutas tropicais e nozes caramelizadas.",
    latitude: 28.4798,
    longitude: -81.4743,
  },
{
  nome: "Whoville Comfort CafÃ©",
  regiao: "SeussLanding",
  tipo: "Conforto",
  acesso: "PrÃ³ximo ao Green Eggs and Ham CafÃ©",
  precoMedio: 21,
  destaque: "Pratos quentes e sobremesas inspiradas no mundo do Dr. Seuss. Experimente o bolo de cenoura com cobertura de cream cheese.",
  latitude: 28.4799,
  longitude: -81.4744,
},

  // SuperNintendoWorld
  {
    nome: "Toadstool CafÃ©",
    regiao: "SuperNintendoWorld",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da entrada principal de Super Nintendo World",
    precoMedio: 36,
    destaque: "Pratos inspirados no universo Mario e Luigi. Experimente o hambÃºrguer do Mario com queijo cheddar.",
    latitude: 28.4800,
    longitude: -81.4750,
  },
  {
    nome: "Peachâ€™s Castle Kitchen",
    regiao: "SuperNintendoWorld",
    tipo: "Tematico",
    acesso: "Dentro do Castelo da Princesa Peach",
    precoMedio: 40,
    destaque: "CulinÃ¡ria temÃ¡tica com pratos dignos da realeza. Experimente o risoto de cogumelos com parmesÃ£o.",
    latitude: 28.4801,
    longitude: -81.4751,
  },
  {
    nome: "Mario Kart Snacks",
    regiao: "SuperNintendoWorld",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo Ã  atraÃ§Ã£o Mario Kart: Bowserâ€™s Challenge",
    precoMedio: 14,
    destaque: "Snacks rÃ¡pidos inspirados nos personagens. Experimente o wrap do Luigi com frango e queijo.",
    latitude: 28.4802,
    longitude: -81.4752,
  },
  {
    nome: "Yoshi Greens",
    regiao: "SuperNintendoWorld",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo Ã  Yoshiâ€™s Adventure",
    precoMedio: 20,
    destaque: "Saladas e bowls inspirados em Yoshi. Experimente o bowl de quinoa com espinafre e tomate seco.",
    latitude: 28.4803,
    longitude: -81.4753,
  },
  {
  nome: "Luigi Comfort Diner",
  regiao: "SuperNintendoWorld",
  tipo: "Conforto",
  acesso: "Perto da entrada da atraÃ§Ã£o Mario Kart",
  precoMedio: 24,
  destaque: "Pratos quentes como massas e pizzas inspiradas no Luigi. Experimente a pizza de quatro queijos com crosta crocante.",
  latitude: 28.4804,
  longitude: -81.4754,
},


  // TheWitcher
  {
    nome: "Kaer Morhen Tavern",
    regiao: "TheWitcher",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  entrada principal da Ã¡rea The Witcher",
    precoMedio: 38,
    destaque: "Pratos robustos e grelhados para guerreiros. Experimente o cordeiro assado com batatas ao alecrim.",
    latitude: 28.4810,
    longitude: -81.4760,
  },
  {
    nome: "Geraltâ€™s Grill",
    regiao: "TheWitcher",
    tipo: "Tematico",
    acesso: "Ao lado da atraÃ§Ã£o Witcherâ€™s Hunt",
    precoMedio: 42,
    destaque: "Pratos inspirados no universo do bruxo Geralt. Experimente o javali defumado com molho de ervas.",
    latitude: 28.4811,
    longitude: -81.4761,
  },
  {
    nome: "Witcher Snacks",
    regiao: "TheWitcher",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo Ã  loja de poÃ§Ãµes",
    precoMedio: 13,
    destaque: "Snacks rÃ¡pidos e temÃ¡ticos. Experimente a empanada de frango com especiarias.",
    latitude: 28.4812,
    longitude: -81.4762,
  },
  {
    nome: "Sorceress Greens",
    regiao: "TheWitcher",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo ao pÃ¡tio de treinos de bruxos",
    precoMedio: 18,
    destaque: "Bowls com ingredientes naturais e frescos. Experimente o bowl de quinoa com salmÃ£o grelhado.",
    latitude: 28.4813,
    longitude: -81.4763,
  },
{
  nome: "Witcher Comfort Tavern",
  regiao: "TheWitcher",
  tipo: "Conforto",
  acesso: "Ao lado da Geraltâ€™s Grill",
  precoMedio: 28,
  destaque: "Pratos robustos e sopas em estilo medieval. Experimente a sopa de abÃ³bora com especiarias e pÃ£o rÃºstico.",
  latitude: 28.4814,
  longitude: -81.4764,
},

  // TheWizardingWorld
  {
    nome: "Leaky Cauldron",
    regiao: "TheWizardingWorld",
    tipo: ["Classico", "Americano"],
    acesso: "Dentro da Ã¡rea do Beco Diagonal",
    precoMedio: 45,
    destaque: "Pratos clÃ¡ssicos britÃ¢nicos em ambiente mÃ¡gico. Experimente o fish and chips com molho de ervas.",
    latitude: 28.4815,
    longitude: -81.4770,
  },
  {
    nome: "The Hopping Pot",
    regiao: "TheWizardingWorld",
    tipo: "Tematico",
    acesso: "Ao lado da Florean Fortescueâ€™s Ice Cream Parlour",
    precoMedio: 30,
    destaque: "Bebidas e snacks com tema bruxo. Experimente a butterbeer gelada com espuma cremosa.",
    latitude: 28.4816,
    longitude: -81.4771,
  },
  {
    nome: "Diagon Snacks",
    regiao: "TheWizardingWorld",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo Ã  entrada do Beco Diagonal",
    precoMedio: 15,
    destaque: "Snacks e lanches mÃ¡gicos. Experimente o biscoito de abÃ³bora.",
    latitude: 28.4817,
    longitude: -81.4772,
  },
  {
    nome: "Magic Greens",
    regiao: "TheWizardingWorld",
    tipo: "Saudavel",
    acesso: "Ãrea lateral perto da Ollivanders",
    precoMedio: 20,
    destaque: "Bowls leves e saudÃ¡veis. Experimente a salada de folhas verdes com frango grelhado.",
    latitude: 28.4818,
    longitude: -81.4773,
  },
  {
  nome: "Diagon Comfort Kitchen",
  regiao: "TheWizardingWorld",
  tipo: "Conforto",
  acesso: "Perto da entrada do Leaky Cauldron",
  precoMedio: 26,
  destaque: "Pratos quentes e tortas britÃ¢nicas para um jantar aconchegante. Experimente o shepherdâ€™s pie com purÃª cremoso.",
  latitude: 28.4819,
  longitude: -81.4774,
},

  // TheWizardingWorldHogsmeade
  {
    nome: "Three Broomsticks",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: ["Classico", "Americano"],
    acesso: "No centro de Hogsmeade, prÃ³ximo Ã  loja Honeydukes",
    precoMedio: 44,
    destaque: "Pratos tÃ­picos britÃ¢nicos com ambiente rÃºstico. Experimente o prato de costela defumada com purÃª de batata.",
    latitude: 28.4820,
    longitude: -81.4780,
  },
  {
    nome: "Hogs Head Pub",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Tematico",
    acesso: "Ao lado do Three Broomsticks",
    precoMedio: 29,
    destaque: "Bebidas especiais e petiscos mÃ¡gicos. Experimente a butterbeer quente com espuma cremosa.",
    latitude: 28.4821,
    longitude: -81.4781,
  },
  {
    nome: "Hogsmeade Snacks",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo Ã  entrada da Ã¡rea",
    precoMedio: 12,
    destaque: "Snacks e doces mÃ¡gicos para levar. Experimente o fudge de abÃ³bora.",
    latitude: 28.4822,
    longitude: -81.4782,
  },
  {
    nome: "Enchanted Greens",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo ao castelo de Hogwarts",
    precoMedio: 18,
    destaque: "Bowls leves e saladas temÃ¡ticas. Experimente a salada de frutas da estaÃ§Ã£o com mel mÃ¡gico.",
    latitude: 28.4823,
    longitude: -81.4783,
  },
  {
  nome: "Hogsmeade Comfort House",
  regiao: "TheWizardingWorldHogsmeade",
  tipo: "Conforto",
  acesso: "Entre o Three Broomsticks e o Hogs Head Pub",
  precoMedio: 27,
  destaque: "Pratos britÃ¢nicos aconchegantes, como ensopados e tortas. Experimente o beef stew com pÃ£o caseiro.",
  latitude: 28.4824,
  longitude: -81.4784,
},


  // ToonLagoon
  {
    nome: "Comic Strip CafÃ©",
    regiao: "ToonLagoon",
    tipo: ["Classico", "Americano"],
    acesso: "No centro da Toon Lagoon, prÃ³ximo Ã  Dudley Do-Rightâ€™s Ripsaw Falls",
    precoMedio: 32,
    destaque: "Pratos clÃ¡ssicos com decoraÃ§Ã£o de quadrinhos. Experimente o cheeseburger com batatas fritas crocantes.",
    latitude: 28.4825,
    longitude: -81.4790,
  },
  {
    nome: "Blondieâ€™s â€“ Home of the Dagwood",
    regiao: "ToonLagoon",
    tipo: "Tematico",
    acesso: "Ao lado da Popeye & Blutoâ€™s Bilge-Rat Barges",
    precoMedio: 30,
    destaque: "SanduÃ­ches enormes no estilo Dagwood. Experimente o sanduÃ­che de vÃ¡rias camadas com frios e queijos.",
    latitude: 28.4826,
    longitude: -81.4791,
  },
  {
    nome: "Toon Snacks",
    regiao: "ToonLagoon",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo Ã  Comic Strip CafÃ©",
    precoMedio: 11,
    destaque: "Snacks rÃ¡pidos e econÃ´micos. Experimente o cookie com gotas de chocolate.",
    latitude: 28.4827,
    longitude: -81.4792,
  },
  {
    nome: "Lagoon Greens",
    regiao: "ToonLagoon",
    tipo: "Saudavel",
    acesso: "Ãrea lateral perto da Popeye & Blutoâ€™s",
    precoMedio: 17,
    destaque: "Bowls e wraps vegetarianos. Experimente a salada de rÃºcula com tomate seco.",
    latitude: 28.4828,
    longitude: -81.4793,
  },
  {
  nome: "Toon Comfort Diner",
  regiao: "ToonLagoon",
  tipo: "Conforto",
  acesso: "Ao lado da entrada da Comic Strip CafÃ©",
  precoMedio: 20,
  destaque: "Lanches e sobremesas inspiradas nos personagens dos quadrinhos. Experimente o brownie com calda de chocolate.",
  latitude: 28.4829,
  longitude: -81.4794,
},


  // UniversalMonsters
  {
    nome: "Monster CafÃ©",
    regiao: "UniversalMonsters",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  Ã¡rea de atraÃ§Ãµes clÃ¡ssicas dos monstros",
    precoMedio: 35,
    destaque: "Pratos tradicionais com tema de filmes de terror. Experimente o hambÃºrguer Frankenstein com queijo cheddar.",
    latitude: 28.4830,
    longitude: -81.4800,
  },
  {
    nome: "Draculaâ€™s Feast",
    regiao: "UniversalMonsters",
    tipo: "Tematico",
    acesso: "Ao lado da exposiÃ§Ã£o Universal Monsters",
    precoMedio: 38,
    destaque: "CulinÃ¡ria temÃ¡tica inspirada nos vampiros. Experimente o strogonoff de carne com molho especial.",
    latitude: 28.4831,
    longitude: -81.4801,
  },
  {
    nome: "Monster Snacks",
    regiao: "UniversalMonsters",
    tipo: "Economico",
    acesso: "Carrinho ao lado do Monster CafÃ©",
    precoMedio: 13,
    destaque: "Snacks e doces assustadoramente deliciosos. Experimente o cookie em forma de caveira.",
    latitude: 28.4832,
    longitude: -81.4802,
  },
  {
    nome: "Creature Greens",
    regiao: "UniversalMonsters",
    tipo: "Saudavel",
    acesso: "Ãrea lateral prÃ³xima Ã  Universal Monsters Store",
    precoMedio: 18,
    destaque: "Saladas frescas e wraps vegetarianos. Experimente o wrap de frango Caesar.",
    latitude: 28.4833,
    longitude: -81.4803,
  },
  {
  nome: "Monster Comfort Tavern",
  regiao: "UniversalMonsters",
  tipo: "Conforto",
  acesso: "PrÃ³ximo ao Monster CafÃ©",
  precoMedio: 23,
  destaque: "Pratos reconfortantes inspirados nos clÃ¡ssicos monstros da Universal. Experimente a sopa cremosa de abÃ³bora com alho-porÃ³.",
  latitude: 28.4834,
  longitude: -81.4804,
},


  // WorldExpo
  {
    nome: "International CafÃ©",
    regiao: "WorldExpo",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  atraÃ§Ã£o MEN IN BLACK Alien Attack",
    precoMedio: 34,
    destaque: "Pratos internacionais com toque americano. Experimente o frango teriyaki com arroz de jasmim.",
    latitude: 28.4835,
    longitude: -81.4810,
  },
  {
    nome: "Expo Food Court",
    regiao: "WorldExpo",
    tipo: "Tematico",
    acesso: "No centro da World Expo",
    precoMedio: 28,
    destaque: "Comidas rÃ¡pidas com estilo futurista. Experimente o hambÃºrguer com molho picante e batatas fritas.",
    latitude: 28.4836,
    longitude: -81.4811,
  },
  {
    nome: "Expo Snacks",
    regiao: "WorldExpo",
    tipo: "Economico",
    acesso: "Carrinho prÃ³ximo Ã  entrada principal da Ã¡rea",
    precoMedio: 11,
    destaque: "Snacks leves para um lanche rÃ¡pido. Experimente o cachorro-quente com molho barbecue.",
    latitude: 28.4837,
    longitude: -81.4812,
  },
  {
    nome: "Expo Greens",
    regiao: "WorldExpo",
    tipo: "Saudavel",
    acesso: "Ao lado da International CafÃ©",
    precoMedio: 17,
    destaque: "Saladas e wraps frescos e naturais. Experimente a salada Caesar com frango grelhado.",
    latitude: 28.4838,
    longitude: -81.4813,
  },
  {
  nome: "Expo Comfort Bites",
  regiao: "WorldExpo",
  tipo: "Conforto",
  acesso: "Ao lado do Expo Food Court",
  precoMedio: 22,
  destaque: "Pratos quentes e massas leves para uma refeiÃ§Ã£o rÃ¡pida. Experimente a lasanha de frango com molho branco.",
  latitude: 28.4839,
  longitude: -81.4814,
},

];
