ï»¿// src/logic/blocos/parques/Universal/CafeUniversal.ts

export const cafesUniversal = [

  // FogosEpicoUniverse
  {
    nome: "Epic Morning CafÃƒÂ©",
    regiao: "FogosEpicoUniverse",
    tipo: "Tematico",
    acesso: "Ao lado do lago central do Epic Universe",
    precoMedio: 16,
    destaque: "CafÃƒÂ© temÃƒÂ¡tico com pÃƒÂ£es decorados inspirados nos fogos. NÃƒÂ£o deixe de experimentar o croissant com cobertura de frutas vermelhas.",
    latitude: 28.4801,
    longitude: -81.4590,
  },
  {
    nome: "Luminous Start",
    regiao: "FogosEpicoUniverse",
    tipo: ["Classico", "Americano"],
    acesso: "Frente ÃƒÂ  ÃƒÂ¡rea de shows do Epic Universe",
    precoMedio: 18,
    destaque: "CafÃƒÂ© clÃƒÂ¡ssico americano com ovos, bacon e panquecas. Experimente o combo matinal especial.",
    latitude: 28.4803,
    longitude: -81.4592,
  },
  {
    nome: "Starlight Bakery",
    regiao: "FogosEpicoUniverse",
    tipo: "Conforto",
    acesso: "PrÃƒÂ³ximo ao portÃƒÂ£o principal",
    precoMedio: 12,
    destaque: "Doces caseiros e cafÃƒÂ© expresso. Experimente o bolo de baunilha com calda quente.",
    latitude: 28.4802,
    longitude: -81.4591,
  },
  {
    nome: "Green Aurora Cart",
    regiao: "FogosEpicoUniverse",
    tipo: "Saudavel",
    acesso: "Carrinho perto da entrada do lago",
    precoMedio: 10,
    destaque: "Frutas frescas e smoothies naturais. Experimente o smoothie de manga e gengibre.",
    latitude: 28.4800,
    longitude: -81.4593,
  },
  {
    nome: "Spark Morning Kiosk",
    regiao: "FogosEpicoUniverse",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido ao lado da ÃƒÂ¡rea de fogos",
    precoMedio: 8,
    destaque: "CafÃƒÂ© preto e pÃƒÂ£es simples. Experimente o pÃƒÂ£o doce de canela.",
    latitude: 28.4799,
    longitude: -81.4594,
  },

  // FogosIslandsOfAdventure
  {
    nome: "Island Dawn CafÃƒÂ©",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ao lago do show de fogos do Islands",
    precoMedio: 15,
    destaque: "CafÃƒÂ© temÃƒÂ¡tico com decoraÃƒÂ§ÃƒÂ£o inspirada em ilhas. Experimente o bolo de abacaxi com coco.",
    latitude: 28.4715,
    longitude: -81.4710,
  },
  {
    nome: "Sunrise Harbor",
    regiao: "FogosIslandsOfAdventure",
    tipo: ["Classico", "Americano"],
    acesso: "Na frente do Port of Entry",
    precoMedio: 19,
    destaque: "Pratos matinais clÃƒÂ¡ssicos com vista para os fogos. Experimente o combo de ovos com panquecas.",
    latitude: 28.4717,
    longitude: -81.4712,
  },
  {
    nome: "Lagoon Bakery",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Conforto",
    acesso: "Ao lado da ponte para Marvel",
    precoMedio: 11,
    destaque: "Cappuccinos e muffins. Experimente o muffin de chocolate intenso.",
    latitude: 28.4716,
    longitude: -81.4711,
  },
  {
    nome: "Tropical Breeze Cart",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Saudavel",
    acesso: "Carrinho ao lado do lago",
    precoMedio: 9,
    destaque: "Smoothies, frutas e chÃƒÂ¡s leves. Experimente o smoothie de frutas vermelhas.",
    latitude: 28.4714,
    longitude: -81.4713,
  },
  {
    nome: "Morning Isles Express",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Economico",
    acesso: "Na entrada da ÃƒÂ¡rea de fogos",
    precoMedio: 8,
    destaque: "OpÃƒÂ§ÃƒÂµes rÃƒÂ¡pidas de pÃƒÂ£es e cafÃƒÂ© simples. Experimente o pÃƒÂ£o doce de leite.",
    latitude: 28.4713,
    longitude: -81.4714,
  },

  // FogosUniversalStudios
  {
    nome: "Cinematic CafÃƒÂ©",
    regiao: "FogosUniversalStudios",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ao lago central do Universal Studios",
    precoMedio: 16,
    destaque: "CafÃƒÂ© temÃƒÂ¡tico inspirado nos filmes da Universal. Experimente o brownie de chocolate intenso.",
    latitude: 28.4742,
    longitude: -81.4670,
  },
  {
    nome: "Studio Morning Grill",
    regiao: "FogosUniversalStudios",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado do palco de fogos",
    precoMedio: 20,
    destaque: "Pratos tradicionais americanos com vista para os shows. Experimente o combo de ovos e panquecas.",
    latitude: 28.4744,
    longitude: -81.4672,
  },
  {
    nome: "Film Reel Bakery",
    regiao: "FogosUniversalStudios",
    tipo: "Conforto",
    acesso: "PrÃƒÂ³ximo ao Universal Music Plaza",
    precoMedio: 12,
    destaque: "CafÃƒÂ© e doces cinematogrÃƒÂ¡ficos. Experimente o cookie gigante de baunilha.",
    latitude: 28.4743,
    longitude: -81.4671,
  },
  {
    nome: "Movie Start Cart",
    regiao: "FogosUniversalStudios",
    tipo: "Saudavel",
    acesso: "Carrinho ao lado do lago principal",
    precoMedio: 10,
    destaque: "OpÃƒÂ§ÃƒÂµes leves de frutas e sucos. Experimente a salada de frutas tropicais.",
    latitude: 28.4741,
    longitude: -81.4673,
  },
  {
    nome: "Quick Film CafÃƒÂ©",
    regiao: "FogosUniversalStudios",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido perto do show de fogos",
    precoMedio: 8,
    destaque: "CafÃƒÂ© preto e bolinhos simples. Experimente o bolo de baunilha.",
    latitude: 28.4740,
    longitude: -81.4674,
  },

  // Hollywood
  {
    nome: "Beverly Hills Boulangerie",
    regiao: "Hollywood",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada principal do Universal Studios",
    precoMedio: 15,
    destaque: "CafÃƒÂ© francÃƒÂªs com pÃƒÂ£es artesanais e doces. Experimente o croissant de amÃƒÂªndoas.",
    latitude: 28.4732,
    longitude: -81.4665,
  },
  {
    nome: "MelÃ¢â‚¬â„¢s Drive-In (Breakfast)",
    regiao: "Hollywood",
    tipo: ["Classico", "Americano"],
    acesso: "Em frente ao simulador de Minions",
    precoMedio: 19,
    destaque: "CafÃƒÂ© no estilo retrÃƒÂ´ com pratos clÃƒÂ¡ssicos. Experimente as panquecas com xarope de bordo.",
    latitude: 28.4734,
    longitude: -81.4667,
  },
  {
    nome: "Starbucks Hollywood",
    regiao: "Hollywood",
    tipo: "Conforto",
    acesso: "Na avenida principal",
    precoMedio: 12,
    destaque: "CafÃƒÂ©s clÃƒÂ¡ssicos e snacks rÃƒÂ¡pidos. Experimente o frappuccino de caramelo.",
    latitude: 28.4733,
    longitude: -81.4666,
  },
  {
    nome: "Healthy Morning Spot",
    regiao: "Hollywood",
    tipo: "Saudavel",
    acesso: "Perto do Universal Music Plaza",
    precoMedio: 10,
    destaque: "Smoothies, frutas e barras energÃƒÂ©ticas. Experimente o smoothie de banana com aveia.",
    latitude: 28.4731,
    longitude: -81.4668,
  },
  {
    nome: "Universal Bakery Cart",
    regiao: "Hollywood",
    tipo: "Economico",
    acesso: "Carrinho mÃƒÂ³vel na Hollywood Boulevard",
    precoMedio: 8,
    destaque: "PÃƒÂ£es simples, cookies e cafÃƒÂ© preto. Experimente o cookie de chocolate.",
    latitude: 28.4730,
    longitude: -81.4669,
  },
  // HowToTrainYourDragon
  {
    nome: "Viking Start CafÃƒÂ©",
    regiao: "HowToTrainYourDragon",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada principal da ÃƒÂ¡rea Viking",
    precoMedio: 16,
    destaque: "CafÃƒÂ© inspirado no universo de Banguela e SoluÃƒÂ§o, com pÃƒÂ£es e bolos vikings. Experimente o bolo de canela com cobertura doce.",
    latitude: 28.4720,
    longitude: -81.4625,
  },
  {
    nome: "Berk Morning Feast",
    regiao: "HowToTrainYourDragon",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o Dragon Riders",
    precoMedio: 19,
    destaque: "CafÃƒÂ© completo com ovos, bacon e pÃƒÂ£es rÃƒÂºsticos. Experimente o combo com panquecas de frutas.",
    latitude: 28.4722,
    longitude: -81.4627,
  },
  {
    nome: "Dragonfire Bakery",
    regiao: "HowToTrainYourDragon",
    tipo: "Conforto",
    acesso: "PrÃƒÂ³ximo ao show de Banguela",
    precoMedio: 12,
    destaque: "Cookies e muffins artesanais. Experimente o muffin de chocolate com mel.",
    latitude: 28.4721,
    longitude: -81.4626,
  },
  {
    nome: "Viking Fruit Stand",
    regiao: "HowToTrainYourDragon",
    tipo: "Saudavel",
    acesso: "Carrinho ao lado do lago",
    precoMedio: 9,
    destaque: "Frutas frescas e sucos naturais. Experimente o mix de frutas com mel.",
    latitude: 28.4719,
    longitude: -81.4624,
  },
  {
    nome: "Hiccup Quick CafÃƒÂ©",
    regiao: "HowToTrainYourDragon",
    tipo: "Economico",
    acesso: "Carrinho prÃƒÂ³ximo ÃƒÂ  praÃƒÂ§a central",
    precoMedio: 8,
    destaque: "CafÃƒÂ© preto, pÃƒÂ£o simples e croissants. Experimente o croissant recheado de queijo.",
    latitude: 28.4718,
    longitude: -81.4623,
  },

  // JurassicPark
  {
    nome: "Thunder Falls Terrace (Breakfast)",
    regiao: "JurassicPark",
    tipo: "Tematico",
    acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o Jurassic Park River Adventure",
    precoMedio: 16,
    destaque: "Pratos inspirados na ilha jurÃƒÂ¡ssica com pÃƒÂ£es e cafÃƒÂ©s fortes. Experimente o pÃƒÂ£o de banana com mel.",
    latitude: 28.4765,
    longitude: -81.4710,
  },
  {
    nome: "Discovery Grill Morning",
    regiao: "JurassicPark",
    tipo: ["Classico", "Americano"],
    acesso: "Perto do Discovery Center",
    precoMedio: 20,
    destaque: "CafÃƒÂ© ao estilo americano com ovos, bacon e torradas. Experimente o combo clÃƒÂ¡ssico com panquecas.",
    latitude: 28.4763,
    longitude: -81.4707,
  },
  {
    nome: "Dino Bites Cart",
    regiao: "JurassicPark",
    tipo: "Conforto",
    acesso: "Ao lado do Raptor Encounter",
    precoMedio: 11,
    destaque: "Pretzels e croissants temÃƒÂ¡ticos. Experimente o pretzel em formato de dinossauro.",
    latitude: 28.4764,
    longitude: -81.4708,
  },
  {
    nome: "Jurassic Fruit Stand",
    regiao: "JurassicPark",
    tipo: "Saudavel",
    acesso: "Caminho para a saÃƒÂ­da do River Adventure",
    precoMedio: 9,
    destaque: "Frutas tropicais e sucos naturais. Experimente a salada de frutas com maracujÃƒÂ¡.",
    latitude: 28.4762,
    longitude: -81.4709,
  },
  {
    nome: "Dino Quick CafÃƒÂ©",
    regiao: "JurassicPark",
    tipo: "Economico",
    acesso: "Carrinho prÃƒÂ³ximo ao Discovery Trail",
    precoMedio: 8,
    destaque: "Bolos simples e cafÃƒÂ© americano. Experimente o bolo de cenoura com canela.",
    latitude: 28.4761,
    longitude: -81.4706,
  },

  // LostContinent
  {
    nome: "Mythos Morning CafÃƒÂ©",
    regiao: "LostContinent",
    tipo: "Tematico",
    acesso: "Ao lado do restaurante Mythos",
    precoMedio: 17,
    destaque: "CafÃƒÂ©s especiais e pÃƒÂ£es gregos. Experimente o pÃƒÂ£o de mel com iogurte grego.",
    latitude: 28.4738,
    longitude: -81.4701,
  },
  {
    nome: "OracleÃ¢â‚¬â„¢s Breakfast",
    regiao: "LostContinent",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada para Seuss Landing",
    precoMedio: 20,
    destaque: "Pratos americanos com ovos, bacon e panquecas. Experimente o combo de ovos com bacon.",
    latitude: 28.4740,
    longitude: -81.4703,
  },
  {
    nome: "Athena Bakery",
    regiao: "LostContinent",
    tipo: "Conforto",
    acesso: "Em frente ÃƒÂ  fonte mÃƒÂ¡gica",
    precoMedio: 12,
    destaque: "Muffins, croissants e cafÃƒÂ©s especiais. Experimente o muffin de blueberry.",
    latitude: 28.4739,
    longitude: -81.4702,
  },
  {
    nome: "Temple Fruit Stand",
    regiao: "LostContinent",
    tipo: "Saudavel",
    acesso: "Carrinho ao lado da Mystic Fountain",
    precoMedio: 10,
    destaque: "Smoothies e frutas frescas. Experimente o smoothie de abacaxi com hortelÃƒÂ£.",
    latitude: 28.4737,
    longitude: -81.4704,
  },
  {
    nome: "Lost Morning Express",
    regiao: "LostContinent",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido na saÃƒÂ­da para Jurassic Park",
    precoMedio: 8,
    destaque: "CafÃƒÂ© preto e pÃƒÂ£es simples. Experimente o bolo de chocolate quente.",
    latitude: 28.4736,
    longitude: -81.4705,
  },

  // MarvelSuperHeroIsland
  {
    nome: "Stark CafÃƒÂ©",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada do simulador do Hulk",
    precoMedio: 16,
    destaque: "CafÃƒÂ© inspirado nos herÃƒÂ³is da Marvel. Experimente o bolo de chocolate do Iron Man.",
    latitude: 28.4731,
    longitude: -81.4725,
  },
  {
    nome: "Avengers Morning Diner",
    regiao: "MarvelSuperHeroIsland",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da loja principal da Marvel",
    precoMedio: 19,
    destaque: "CafÃƒÂ© ao estilo americano com waffles e bacon. Experimente o combo especial de ovos.",
    latitude: 28.4733,
    longitude: -81.4727,
  },
  {
    nome: "Hero Bakery",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Conforto",
    acesso: "Perto da atraÃƒÂ§ÃƒÂ£o do Spider-Man",
    precoMedio: 12,
    destaque: "Doces temÃƒÂ¡ticos e cafÃƒÂ©s cremosos. Experimente o cookie do CapitÃƒÂ£o AmÃƒÂ©rica.",
    latitude: 28.4732,
    longitude: -81.4726,
  },
  {
    nome: "Shield Fruit Stand",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Saudavel",
    acesso: "Carrinho prÃƒÂ³ximo ao CafÃƒÂ© Four",
    precoMedio: 9,
    destaque: "Frutas e smoothies energÃƒÂ©ticos. Experimente o smoothie de morango e banana.",
    latitude: 28.4730,
    longitude: -81.4728,
  },
  {
    nome: "Quick Marvel CafÃƒÂ©",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Economico",
    acesso: "Carrinho na saÃƒÂ­da da ÃƒÂ¡rea Marvel",
    precoMedio: 8,
    destaque: "CafÃƒÂ© simples e bolos leves. Experimente o bolo de laranja.",
    latitude: 28.4729,
    longitude: -81.4729,
  },
  // MinionsLand
  {
    nome: "GruÃ¢â‚¬â„¢s Morning CafÃƒÂ©",
    regiao: "MinionsLand",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  atraÃƒÂ§ÃƒÂ£o Despicable Me Minion Mayhem",
    precoMedio: 16,
    destaque: "CafÃƒÂ© temÃƒÂ¡tico com doces e bolos dos Minions. Experimente a rosquinha amarela com cobertura de baunilha.",
    latitude: 28.4745,
    longitude: -81.4650,
  },
  {
    nome: "Minion Pancake House",
    regiao: "MinionsLand",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da loja dos Minions",
    precoMedio: 19,
    destaque: "Panquecas, ovos e bacon com tema Minion. Experimente o combo de panquecas com calda de morango.",
    latitude: 28.4747,
    longitude: -81.4652,
  },
  {
    nome: "Banana Bakery",
    regiao: "MinionsLand",
    tipo: "Conforto",
    acesso: "Perto da entrada da ÃƒÂ¡rea dos Minions",
    precoMedio: 12,
    destaque: "Doces de banana e muffins especiais. Experimente o muffin de banana com gotas de chocolate.",
    latitude: 28.4746,
    longitude: -81.4651,
  },
  {
    nome: "Minion Fruit Cart",
    regiao: "MinionsLand",
    tipo: "Saudavel",
    acesso: "Carrinho na saÃƒÂ­da da Minion Mayhem",
    precoMedio: 9,
    destaque: "Frutas frescas, sucos e wraps leves. Experimente o smoothie de banana com mel.",
    latitude: 28.4744,
    longitude: -81.4653,
  },
  {
    nome: "Minion Quick CafÃƒÂ©",
    regiao: "MinionsLand",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido prÃƒÂ³ximo ÃƒÂ  entrada principal",
    precoMedio: 8,
    destaque: "CafÃƒÂ© simples e bolos leves. Experimente o bolo de baunilha com cobertura amarela.",
    latitude: 28.4743,
    longitude: -81.4654,
  },

  // NewYork
  {
    nome: "Broadway Morning CafÃƒÂ©",
    regiao: "NewYork",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  atraÃƒÂ§ÃƒÂ£o Revenge of the Mummy",
    precoMedio: 17,
    destaque: "CafÃƒÂ© inspirado em Nova York com bagels e doces. Experimente o bagel com cream cheese e salmÃƒÂ£o.",
    latitude: 28.4751,
    longitude: -81.4641,
  },
  {
    nome: "Times Square Breakfast",
    regiao: "NewYork",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da New York Public Library (cenÃƒÂ¡rio)",
    precoMedio: 20,
    destaque: "Pratos clÃƒÂ¡ssicos americanos com bacon e ovos. Experimente o combo de ovos com torradas.",
    latitude: 28.4753,
    longitude: -81.4643,
  },
  {
    nome: "NY Bakery",
    regiao: "NewYork",
    tipo: "Conforto",
    acesso: "PrÃƒÂ³ximo ao palco da Blues Brothers Show",
    precoMedio: 12,
    destaque: "Cookies e cheesecakes tÃƒÂ­picos de NY. Experimente o cheesecake de morango.",
    latitude: 28.4752,
    longitude: -81.4642,
  },
  {
    nome: "Central Park Fruit Stand",
    regiao: "NewYork",
    tipo: "Saudavel",
    acesso: "Carrinho prÃƒÂ³ximo ao cenÃƒÂ¡rio de Nova York",
    precoMedio: 10,
    destaque: "Frutas, smoothies e saladas leves. Experimente o smoothie de maÃƒÂ§ÃƒÂ£ e espinafre.",
    latitude: 28.4750,
    longitude: -81.4644,
  },
  {
    nome: "Quick Bagel Stop",
    regiao: "NewYork",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido ao lado do restaurante LouieÃ¢â‚¬â„¢s",
    precoMedio: 8,
    destaque: "CafÃƒÂ© preto e bagels simples. Experimente o bagel com manteiga.",
    latitude: 28.4749,
    longitude: -81.4645,
  },

  // ProductionCentral
  {
    nome: "Studio CafÃƒÂ©",
    regiao: "ProductionCentral",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada principal do parque",
    precoMedio: 15,
    destaque: "CafÃƒÂ© temÃƒÂ¡tico de estÃƒÂºdios de cinema. Experimente o muffin de cenoura com glacÃƒÂª.",
    latitude: 28.4758,
    longitude: -81.4630,
  },
  {
    nome: "DirectorÃ¢â‚¬â„¢s Breakfast",
    regiao: "ProductionCentral",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o Despicable Me Minion Mayhem",
    precoMedio: 19,
    destaque: "CafÃƒÂ© americano com ovos e panquecas. Experimente o combo clÃƒÂ¡ssico.",
    latitude: 28.4760,
    longitude: -81.4632,
  },
  {
    nome: "Movie Bakery",
    regiao: "ProductionCentral",
    tipo: "Conforto",
    acesso: "Em frente ao Universal Store",
    precoMedio: 11,
    destaque: "Cookies, donuts e cafÃƒÂ©s. Experimente o donut de chocolate.",
    latitude: 28.4759,
    longitude: -81.4631,
  },
  {
    nome: "Cinematic Fruit Stand",
    regiao: "ProductionCentral",
    tipo: "Saudavel",
    acesso: "Carrinho prÃƒÂ³ximo ÃƒÂ  entrada do parque",
    precoMedio: 9,
    destaque: "Frutas frescas e barras energÃƒÂ©ticas. Experimente o bowl de frutas com mel.",
    latitude: 28.4757,
    longitude: -81.4633,
  },
  {
    nome: "Quick Studio CafÃƒÂ©",
    regiao: "ProductionCentral",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido em frente ÃƒÂ  Universal Store",
    precoMedio: 8,
    destaque: "CafÃƒÂ© preto e bolos simples. Experimente o bolo de baunilha.",
    latitude: 28.4756,
    longitude: -81.4634,
  },

  // SanFrancisco
  {
    nome: "Pier 39 Morning CafÃƒÂ©",
    regiao: "SanFrancisco",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  atraÃƒÂ§ÃƒÂ£o Fast & Furious Ã¢â‚¬â€œ Supercharged",
    precoMedio: 17,
    destaque: "CafÃƒÂ© inspirado no Pier 39 com muffins e pÃƒÂ£es. Experimente o muffin de limÃƒÂ£o com cobertura.",
    latitude: 28.4767,
    longitude: -81.4615,
  },
  {
    nome: "Golden Gate Breakfast",
    regiao: "SanFrancisco",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado do restaurante LombardÃ¢â‚¬â„¢s Seafood Grille",
    precoMedio: 20,
    destaque: "Pratos clÃƒÂ¡ssicos com bacon, ovos e panquecas. Experimente o combo de ovos com bacon crocante.",
    latitude: 28.4769,
    longitude: -81.4617,
  },
  {
    nome: "Bay Bakery",
    regiao: "SanFrancisco",
    tipo: "Conforto",
    acesso: "Perto da ÃƒÂ¡rea de Dockside",
    precoMedio: 12,
    destaque: "Cookies e brownies artesanais. Experimente o brownie de chocolate com nozes.",
    latitude: 28.4768,
    longitude: -81.4616,
  },
  {
    nome: "Fisherman Fruit Stand",
    regiao: "SanFrancisco",
    tipo: "Saudavel",
    acesso: "Carrinho prÃƒÂ³ximo ao pier",
    precoMedio: 10,
    destaque: "Smoothies e frutas frescas. Experimente o smoothie de frutas cÃƒÂ­tricas.",
    latitude: 28.4766,
    longitude: -81.4618,
  },
  {
    nome: "Quick Bay CafÃƒÂ©",
    regiao: "SanFrancisco",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido prÃƒÂ³ximo ao LombardÃ¢â‚¬â„¢s",
    precoMedio: 8,
    destaque: "CafÃƒÂ© preto e donuts simples. Experimente o donut de aÃƒÂ§ÃƒÂºcar.",
    latitude: 28.4765,
    longitude: -81.4619,
  },
  // SeussLanding
  {
    nome: "Cat in the Hat CafÃƒÂ©",
    regiao: "SeussLanding",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  atraÃƒÂ§ÃƒÂ£o The Cat in the Hat",
    precoMedio: 15,
    destaque: "CafÃƒÂ© lÃƒÂºdico com doces coloridos inspirados no Dr. Seuss. Experimente o cupcake do Lorax.",
    latitude: 28.4739,
    longitude: -81.4709,
  },
  {
    nome: "Green Eggs & Ham Breakfast",
    regiao: "SeussLanding",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da montanha-russa infantil",
    precoMedio: 19,
    destaque: "Pratos inspirados nos livros, com ovos verdes e bacon. Experimente o combo temÃƒÂ¡tico.",
    latitude: 28.4740,
    longitude: -81.4708,
  },
  {
    nome: "Thing 1 Bakery",
    regiao: "SeussLanding",
    tipo: "Conforto",
    acesso: "Em frente ao One Fish, Two Fish",
    precoMedio: 11,
    destaque: "Doces, muffins e cafÃƒÂ©s especiais. Experimente o muffin de morango com cobertura azul.",
    latitude: 28.4741,
    longitude: -81.4707,
  },
  {
    nome: "Who-ville Fruit Stand",
    regiao: "SeussLanding",
    tipo: "Saudavel",
    acesso: "Carrinho prÃƒÂ³ximo ao Caro-Seuss-el",
    precoMedio: 9,
    destaque: "Frutas e smoothies coloridos. Experimente o smoothie de frutas tropicais.",
    latitude: 28.4738,
    longitude: -81.4706,
  },
  {
    nome: "Quick Seuss CafÃƒÂ©",
    regiao: "SeussLanding",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido perto da entrada da ÃƒÂ¡rea",
    precoMedio: 8,
    destaque: "CafÃƒÂ© preto e bolos simples. Experimente o bolo de baunilha com glacÃƒÂª.",
    latitude: 28.4737,
    longitude: -81.4705,
  },

  // SuperNintendoWorld
  {
    nome: "Toad CafÃƒÂ© Morning",
    regiao: "SuperNintendoWorld",
    tipo: "Tematico",
    acesso: "Dentro da ÃƒÂ¡rea do Mario Kart",
    precoMedio: 18,
    destaque: "CafÃƒÂ© temÃƒÂ¡tico com doces e bebidas inspiradas no Mario. Experimente o bolo da Princesa Peach.",
    latitude: 28.4772,
    longitude: -81.4680,
  },
  {
    nome: "PeachÃ¢â‚¬â„¢s Bakery",
    regiao: "SuperNintendoWorld",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada principal da ÃƒÂ¡rea",
    precoMedio: 20,
    destaque: "Waffles e panquecas temÃƒÂ¡ticas. Experimente o waffle do Luigi com calda de morango.",
    latitude: 28.4771,
    longitude: -81.4682,
  },
  {
    nome: "LuigiÃ¢â‚¬â„¢s Snack Stand",
    regiao: "SuperNintendoWorld",
    tipo: "Conforto",
    acesso: "Ao lado do BowserÃ¢â‚¬â„¢s Challenge",
    precoMedio: 12,
    destaque: "Cookies e cappuccinos. Experimente o cappuccino verde do Luigi.",
    latitude: 28.4773,
    longitude: -81.4681,
  },
  {
    nome: "YoshiÃ¢â‚¬â„¢s Fruit Corner",
    regiao: "SuperNintendoWorld",
    tipo: "Saudavel",
    acesso: "Perto do YoshiÃ¢â‚¬â„¢s Adventure",
    precoMedio: 10,
    destaque: "Smoothies e frutas frescas. Experimente o smoothie tropical do Yoshi.",
    latitude: 28.4770,
    longitude: -81.4683,
  },
  {
    nome: "Mario Quick Morning",
    regiao: "SuperNintendoWorld",
    tipo: "Economico",
    acesso: "Carrinho prÃƒÂ³ximo ÃƒÂ  entrada",
    precoMedio: 9,
    destaque: "CafÃƒÂ© preto e biscoitos temÃƒÂ¡ticos. Experimente o cookie de estrela.",
    latitude: 28.4769,
    longitude: -81.4684,
  },

  // TheWitcher
  {
    nome: "Kaer Morhen CafÃƒÂ©",
    regiao: "TheWitcher",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada principal da ÃƒÂ¡rea",
    precoMedio: 17,
    destaque: "CafÃƒÂ© inspirado no universo de The Witcher, com pÃƒÂ£es rÃƒÂºsticos e hidromel quente. Experimente o pÃƒÂ£o doce com especiarias.",
    latitude: 28.4782,
    longitude: -81.4600,
  },
  {
    nome: "GeraltÃ¢â‚¬â„¢s Breakfast",
    regiao: "TheWitcher",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da taverna temÃƒÂ¡tica",
    precoMedio: 20,
    destaque: "Pratos matinais robustos com ovos e linguiÃƒÂ§a. Experimente o combo com pÃƒÂ£o artesanal.",
    latitude: 28.4783,
    longitude: -81.4601,
  },
  {
    nome: "SorcererÃ¢â‚¬â„¢s Bakery",
    regiao: "TheWitcher",
    tipo: "Conforto",
    acesso: "PrÃƒÂ³ximo ao show de magia",
    precoMedio: 12,
    destaque: "Doces e bolos com especiarias. Experimente o muffin de maÃƒÂ§ÃƒÂ£ e canela.",
    latitude: 28.4784,
    longitude: -81.4602,
  },
  {
    nome: "YenneferÃ¢â‚¬â„¢s Fruit Stand",
    regiao: "TheWitcher",
    tipo: "Saudavel",
    acesso: "Carrinho ao lado da ÃƒÂ¡rea principal",
    precoMedio: 9,
    destaque: "Frutas e bebidas naturais. Experimente o smoothie de frutas roxas.",
    latitude: 28.4781,
    longitude: -81.4603,
  },
  {
    nome: "Witcher Quick CafÃƒÂ©",
    regiao: "TheWitcher",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido prÃƒÂ³ximo ao portal",
    precoMedio: 8,
    destaque: "CafÃƒÂ© preto e biscoitos simples. Experimente o cookie de mel.",
    latitude: 28.4780,
    longitude: -81.4604,
  },

  // TheWizardingWorld
  {
    nome: "Leaky Cauldron Morning",
    regiao: "TheWizardingWorld",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada do Beco Diagonal",
    precoMedio: 18,
    destaque: "CafÃƒÂ© temÃƒÂ¡tico com pratos britÃƒÂ¢nicos. Experimente o pÃƒÂ£o de mel com chÃƒÂ¡ inglÃƒÂªs.",
    latitude: 28.4760,
    longitude: -81.4690,
  },
  {
    nome: "Diagon Alley Breakfast",
    regiao: "TheWizardingWorld",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da Gringotts Bank",
    precoMedio: 21,
    destaque: "Pratos britÃƒÂ¢nicos com ovos e linguiÃƒÂ§a. Experimente o combo clÃƒÂ¡ssico de cafÃƒÂ© da manhÃƒÂ£.",
    latitude: 28.4762,
    longitude: -81.4692,
  },
  {
    nome: "OllivanderÃ¢â‚¬â„¢s Bakery",
    regiao: "TheWizardingWorld",
    tipo: "Conforto",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  loja de varinhas",
    precoMedio: 12,
    destaque: "Doces mÃƒÂ¡gicos e bolos especiais. Experimente o bolo de abÃƒÂ³bora.",
    latitude: 28.4761,
    longitude: -81.4691,
  },
  {
    nome: "Magic Fruit Stand",
    regiao: "TheWizardingWorld",
    tipo: "Saudavel",
    acesso: "Carrinho prÃƒÂ³ximo ao palco de feitiÃƒÂ§os",
    precoMedio: 9,
    destaque: "Frutas e sucos especiais. Experimente o suco de abÃƒÂ³bora.",
    latitude: 28.4759,
    longitude: -81.4693,
  },
  {
    nome: "Quick Wizard CafÃƒÂ©",
    regiao: "TheWizardingWorld",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido ao lado da entrada do Beco Diagonal",
    precoMedio: 8,
    destaque: "CafÃƒÂ© preto e bolos simples. Experimente o muffin de chocolate.",
    latitude: 28.4758,
    longitude: -81.4694,
  },
  // TheWizardingWorldHogsmeade
  {
    nome: "Three Broomsticks Breakfast",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Tematico",
    acesso: "Dentro do restaurante TrÃƒÂªs Vassouras",
    precoMedio: 19,
    destaque: "CafÃƒÂ© britÃƒÂ¢nico completo com pratos tÃƒÂ­picos. Experimente o feijÃƒÂ£o com torradas e ovos.",
    latitude: 28.4732,
    longitude: -81.4702,
  },
  {
    nome: "Hogsmeade Morning Feast",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da loja Zonko's",
    precoMedio: 20,
    destaque: "Pratos robustos com bacon, ovos e salsichas. Experimente o combo especial com panquecas.",
    latitude: 28.4733,
    longitude: -81.4703,
  },
  {
    nome: "Honeydukes Bakery",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Conforto",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  loja Honeydukes",
    precoMedio: 12,
    destaque: "Doces mÃƒÂ¡gicos e muffins especiais. Experimente o muffin de chocolate branco.",
    latitude: 28.4734,
    longitude: -81.4704,
  },
  {
    nome: "Butterbeer Fruit Cart",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Saudavel",
    acesso: "Carrinho prÃƒÂ³ximo ÃƒÂ  entrada do castelo",
    precoMedio: 10,
    destaque: "Frutas frescas e sucos naturais. Experimente o suco de maÃƒÂ§ÃƒÂ£ com canela.",
    latitude: 28.4731,
    longitude: -81.4705,
  },
  {
    nome: "Quick Owl CafÃƒÂ©",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido perto da entrada da ÃƒÂ¡rea",
    precoMedio: 8,
    destaque: "CafÃƒÂ© preto e bolos simples. Experimente o bolo de abÃƒÂ³bora.",
    latitude: 28.4730,
    longitude: -81.4706,
  },

  // ToonLagoon
  {
    nome: "PopeyeÃ¢â‚¬â„¢s Breakfast Spot",
    regiao: "ToonLagoon",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  atraÃƒÂ§ÃƒÂ£o Popeye & BlutoÃ¢â‚¬â„¢s Bilge-Rat Barges",
    precoMedio: 16,
    destaque: "CafÃƒÂ© temÃƒÂ¡tico com pratos energÃƒÂ©ticos. Experimente o sanduÃƒÂ­che de ovos com espinafre.",
    latitude: 28.4728,
    longitude: -81.4715,
  },
  {
    nome: "Cartoon Morning Diner",
    regiao: "ToonLagoon",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado do Dudley Do-RightÃ¢â‚¬â„¢s Ripsaw Falls",
    precoMedio: 19,
    destaque: "Pratos clÃƒÂ¡ssicos com bacon e panquecas. Experimente o combo com ovos mexidos.",
    latitude: 28.4729,
    longitude: -81.4716,
  },
  {
    nome: "Toon Bakery",
    regiao: "ToonLagoon",
    tipo: "Conforto",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  loja Betty Boop",
    precoMedio: 12,
    destaque: "Cookies e muffins temÃƒÂ¡ticos. Experimente o cookie do Popeye com amendoim.",
    latitude: 28.4727,
    longitude: -81.4717,
  },
  {
    nome: "Lagoon Fruit Cart",
    regiao: "ToonLagoon",
    tipo: "Saudavel",
    acesso: "Carrinho prÃƒÂ³ximo ao ponto de observaÃƒÂ§ÃƒÂ£o da ÃƒÂ¡gua",
    precoMedio: 10,
    destaque: "Smoothies, frutas e barras leves. Experimente o smoothie de manga.",
    latitude: 28.4726,
    longitude: -81.4718,
  },
  {
    nome: "Quick Toon CafÃƒÂ©",
    regiao: "ToonLagoon",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido na saÃƒÂ­da da ÃƒÂ¡rea",
    precoMedio: 8,
    destaque: "CafÃƒÂ© simples e pÃƒÂ£es. Experimente o pÃƒÂ£o doce de canela.",
    latitude: 28.4725,
    longitude: -81.4719,
  },

  // UniversalMonsters
  {
    nome: "Monster CafÃƒÂ© Morning",
    regiao: "UniversalMonsters",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  ÃƒÂ¡rea clÃƒÂ¡ssica de monstros",
    precoMedio: 17,
    destaque: "CafÃƒÂ© temÃƒÂ¡tico com pratos inspirados em filmes clÃƒÂ¡ssicos. Experimente o bolo de chocolate do DrÃƒÂ¡cula.",
    latitude: 28.4764,
    longitude: -81.4685,
  },
  {
    nome: "Classic Horror Breakfast",
    regiao: "UniversalMonsters",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado do teatro de shows",
    precoMedio: 20,
    destaque: "Pratos clÃƒÂ¡ssicos de cafÃƒÂ© da manhÃƒÂ£ com estilo retrÃƒÂ´. Experimente o combo com bacon e panquecas.",
    latitude: 28.4765,
    longitude: -81.4686,
  },
  {
    nome: "MummyÃ¢â‚¬â„¢s Bakery",
    regiao: "UniversalMonsters",
    tipo: "Conforto",
    acesso: "Perto da atraÃƒÂ§ÃƒÂ£o Revenge of the Mummy",
    precoMedio: 12,
    destaque: "Doces e cafÃƒÂ©s especiais. Experimente o pÃƒÂ£o de mel com especiarias.",
    latitude: 28.4763,
    longitude: -81.4684,
  },
  {
    nome: "WolfmanÃ¢â‚¬â„¢s Fruit Cart",
    regiao: "UniversalMonsters",
    tipo: "Saudavel",
    acesso: "Carrinho prÃƒÂ³ximo ao estande de fotos",
    precoMedio: 9,
    destaque: "Frutas e barras leves. Experimente a salada de frutas com mel.",
    latitude: 28.4762,
    longitude: -81.4683,
  },
  {
    nome: "Quick Monster CafÃƒÂ©",
    regiao: "UniversalMonsters",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido na entrada da ÃƒÂ¡rea",
    precoMedio: 8,
    destaque: "CafÃƒÂ© preto e bolos simples. Experimente o bolo de chocolate.",
    latitude: 28.4761,
    longitude: -81.4682,
  },

  // WorldExpo
  {
    nome: "Expo Start CafÃƒÂ©",
    regiao: "WorldExpo",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ao Men in Black: Alien Attack",
    precoMedio: 16,
    destaque: "CafÃƒÂ© com tema futurista. Experimente o donut galÃƒÂ¡ctico com glacÃƒÂª azul.",
    latitude: 28.4775,
    longitude: -81.4671,
  },
  {
    nome: "Future Breakfast Hub",
    regiao: "WorldExpo",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado do simulador de MIB",
    precoMedio: 19,
    destaque: "Pratos clÃƒÂ¡ssicos com bacon, ovos e panquecas. Experimente o combo tradicional.",
    latitude: 28.4776,
    longitude: -81.4672,
  },
  {
    nome: "Cosmic Bakery",
    regiao: "WorldExpo",
    tipo: "Conforto",
    acesso: "PrÃƒÂ³ximo ao palco futurista",
    precoMedio: 11,
    destaque: "Cookies, brownies e cafÃƒÂ© expresso. Experimente o cookie de chocolate galÃƒÂ¡ctico.",
    latitude: 28.4774,
    longitude: -81.4670,
  },
  {
    nome: "Galaxy Fruit Stand",
    regiao: "WorldExpo",
    tipo: "Saudavel",
    acesso: "Carrinho prÃƒÂ³ximo ÃƒÂ  ÃƒÂ¡rea Kids Zone",
    precoMedio: 9,
    destaque: "Smoothies, frutas e wraps leves. Experimente o smoothie de framboesa.",
    latitude: 28.4773,
    longitude: -81.4669,
  },
  {
    nome: "Quick Expo CafÃƒÂ©",
    regiao: "WorldExpo",
    tipo: "Economico",
    acesso: "Ponto rÃƒÂ¡pido perto do MIB Shop",
    precoMedio: 8,
    destaque: "CafÃƒÂ© preto e bolos simples. Experimente o bolo de baunilha.",
    latitude: 28.4772,
    longitude: -81.4668,
  },
];



