// src/logic/blocos/parques/Universal/CafeUniversal.ts

export const cafesUniversal = [

  // FogosEpicoUniverse
  {
    nome: "Epic Morning Café",
    regiao: "FogosEpicoUniverse",
    tipo: "Tematico",
    acesso: "Ao lado do lago central do Epic Universe",
    precoMedio: 16,
    destaque: "Café temático com pães decorados inspirados nos fogos. Não deixe de experimentar o croissant com cobertura de frutas vermelhas.",
    latitude: 28.4801,
    longitude: -81.4590,
  },
  {
    nome: "Luminous Start",
    regiao: "FogosEpicoUniverse",
    tipo: ["Classico", "Americano"],
    acesso: "Frente à área de shows do Epic Universe",
    precoMedio: 18,
    destaque: "Café clássico americano com ovos, bacon e panquecas. Experimente o combo matinal especial.",
    latitude: 28.4803,
    longitude: -81.4592,
  },
  {
    nome: "Starlight Bakery",
    regiao: "FogosEpicoUniverse",
    tipo: "Conforto",
    acesso: "Próximo ao portão principal",
    precoMedio: 12,
    destaque: "Doces caseiros e café expresso. Experimente o bolo de baunilha com calda quente.",
    latitude: 28.4802,
    longitude: -81.4591,
  },
  {
    nome: "Green Aurora Cart",
    regiao: "FogosEpicoUniverse",
    tipo: "Saudavel",
    acesso: "Carrinho perto da entrada do lago",
    precoMedio: 10,
    destaque: "Frutas frescas e smoothies naturais. Experimente o smoothie de manga e gengibre.",
    latitude: 28.4800,
    longitude: -81.4593,
  },
  {
    nome: "Spark Morning Kiosk",
    regiao: "FogosEpicoUniverse",
    tipo: "Economico",
    acesso: "Ponto rápido ao lado da área de fogos",
    precoMedio: 8,
    destaque: "Café preto e pães simples. Experimente o pão doce de canela.",
    latitude: 28.4799,
    longitude: -81.4594,
  },

  // FogosIslandsOfAdventure
  {
    nome: "Island Dawn Café",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Tematico",
    acesso: "Próximo ao lago do show de fogos do Islands",
    precoMedio: 15,
    destaque: "Café temático com decoração inspirada em ilhas. Experimente o bolo de abacaxi com coco.",
    latitude: 28.4715,
    longitude: -81.4710,
  },
  {
    nome: "Sunrise Harbor",
    regiao: "FogosIslandsOfAdventure",
    tipo: ["Classico", "Americano"],
    acesso: "Na frente do Port of Entry",
    precoMedio: 19,
    destaque: "Pratos matinais clássicos com vista para os fogos. Experimente o combo de ovos com panquecas.",
    latitude: 28.4717,
    longitude: -81.4712,
  },
  {
    nome: "Lagoon Bakery",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Conforto",
    acesso: "Ao lado da ponte para Marvel",
    precoMedio: 11,
    destaque: "Cappuccinos e muffins. Experimente o muffin de chocolate intenso.",
    latitude: 28.4716,
    longitude: -81.4711,
  },
  {
    nome: "Tropical Breeze Cart",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Saudavel",
    acesso: "Carrinho ao lado do lago",
    precoMedio: 9,
    destaque: "Smoothies, frutas e chás leves. Experimente o smoothie de frutas vermelhas.",
    latitude: 28.4714,
    longitude: -81.4713,
  },
  {
    nome: "Morning Isles Express",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Economico",
    acesso: "Na entrada da área de fogos",
    precoMedio: 8,
    destaque: "Opções rápidas de pães e café simples. Experimente o pão doce de leite.",
    latitude: 28.4713,
    longitude: -81.4714,
  },

  // FogosUniversalStudios
  {
    nome: "Cinematic Café",
    regiao: "FogosUniversalStudios",
    tipo: "Tematico",
    acesso: "Próximo ao lago central do Universal Studios",
    precoMedio: 16,
    destaque: "Café temático inspirado nos filmes da Universal. Experimente o brownie de chocolate intenso.",
    latitude: 28.4742,
    longitude: -81.4670,
  },
  {
    nome: "Studio Morning Grill",
    regiao: "FogosUniversalStudios",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado do palco de fogos",
    precoMedio: 20,
    destaque: "Pratos tradicionais americanos com vista para os shows. Experimente o combo de ovos e panquecas.",
    latitude: 28.4744,
    longitude: -81.4672,
  },
  {
    nome: "Film Reel Bakery",
    regiao: "FogosUniversalStudios",
    tipo: "Conforto",
    acesso: "Próximo ao Universal Music Plaza",
    precoMedio: 12,
    destaque: "Café e doces cinematográficos. Experimente o cookie gigante de baunilha.",
    latitude: 28.4743,
    longitude: -81.4671,
  },
  {
    nome: "Movie Start Cart",
    regiao: "FogosUniversalStudios",
    tipo: "Saudavel",
    acesso: "Carrinho ao lado do lago principal",
    precoMedio: 10,
    destaque: "Opções leves de frutas e sucos. Experimente a salada de frutas tropicais.",
    latitude: 28.4741,
    longitude: -81.4673,
  },
  {
    nome: "Quick Film Café",
    regiao: "FogosUniversalStudios",
    tipo: "Economico",
    acesso: "Ponto rápido perto do show de fogos",
    precoMedio: 8,
    destaque: "Café preto e bolinhos simples. Experimente o bolo de baunilha.",
    latitude: 28.4740,
    longitude: -81.4674,
  },

  // Hollywood
  {
    nome: "Beverly Hills Boulangerie",
    regiao: "Hollywood",
    tipo: "Tematico",
    acesso: "Próximo à entrada principal do Universal Studios",
    precoMedio: 15,
    destaque: "Café francês com pães artesanais e doces. Experimente o croissant de amêndoas.",
    latitude: 28.4732,
    longitude: -81.4665,
  },
  {
    nome: "Mel’s Drive-In (Breakfast)",
    regiao: "Hollywood",
    tipo: ["Classico", "Americano"],
    acesso: "Em frente ao simulador de Minions",
    precoMedio: 19,
    destaque: "Café no estilo retrô com pratos clássicos. Experimente as panquecas com xarope de bordo.",
    latitude: 28.4734,
    longitude: -81.4667,
  },
  {
    nome: "Starbucks Hollywood",
    regiao: "Hollywood",
    tipo: "Conforto",
    acesso: "Na avenida principal",
    precoMedio: 12,
    destaque: "Cafés clássicos e snacks rápidos. Experimente o frappuccino de caramelo.",
    latitude: 28.4733,
    longitude: -81.4666,
  },
  {
    nome: "Healthy Morning Spot",
    regiao: "Hollywood",
    tipo: "Saudavel",
    acesso: "Perto do Universal Music Plaza",
    precoMedio: 10,
    destaque: "Smoothies, frutas e barras energéticas. Experimente o smoothie de banana com aveia.",
    latitude: 28.4731,
    longitude: -81.4668,
  },
  {
    nome: "Universal Bakery Cart",
    regiao: "Hollywood",
    tipo: "Economico",
    acesso: "Carrinho móvel na Hollywood Boulevard",
    precoMedio: 8,
    destaque: "Pães simples, cookies e café preto. Experimente o cookie de chocolate.",
    latitude: 28.4730,
    longitude: -81.4669,
  },
  // HowToTrainYourDragon
  {
    nome: "Viking Start Café",
    regiao: "HowToTrainYourDragon",
    tipo: "Tematico",
    acesso: "Próximo à entrada principal da área Viking",
    precoMedio: 16,
    destaque: "Café inspirado no universo de Banguela e Soluço, com pães e bolos vikings. Experimente o bolo de canela com cobertura doce.",
    latitude: 28.4720,
    longitude: -81.4625,
  },
  {
    nome: "Berk Morning Feast",
    regiao: "HowToTrainYourDragon",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atração Dragon Riders",
    precoMedio: 19,
    destaque: "Café completo com ovos, bacon e pães rústicos. Experimente o combo com panquecas de frutas.",
    latitude: 28.4722,
    longitude: -81.4627,
  },
  {
    nome: "Dragonfire Bakery",
    regiao: "HowToTrainYourDragon",
    tipo: "Conforto",
    acesso: "Próximo ao show de Banguela",
    precoMedio: 12,
    destaque: "Cookies e muffins artesanais. Experimente o muffin de chocolate com mel.",
    latitude: 28.4721,
    longitude: -81.4626,
  },
  {
    nome: "Viking Fruit Stand",
    regiao: "HowToTrainYourDragon",
    tipo: "Saudavel",
    acesso: "Carrinho ao lado do lago",
    precoMedio: 9,
    destaque: "Frutas frescas e sucos naturais. Experimente o mix de frutas com mel.",
    latitude: 28.4719,
    longitude: -81.4624,
  },
  {
    nome: "Hiccup Quick Café",
    regiao: "HowToTrainYourDragon",
    tipo: "Economico",
    acesso: "Carrinho próximo à praça central",
    precoMedio: 8,
    destaque: "Café preto, pão simples e croissants. Experimente o croissant recheado de queijo.",
    latitude: 28.4718,
    longitude: -81.4623,
  },

  // JurassicPark
  {
    nome: "Thunder Falls Terrace (Breakfast)",
    regiao: "JurassicPark",
    tipo: "Tematico",
    acesso: "Ao lado da atração Jurassic Park River Adventure",
    precoMedio: 16,
    destaque: "Pratos inspirados na ilha jurássica com pães e cafés fortes. Experimente o pão de banana com mel.",
    latitude: 28.4765,
    longitude: -81.4710,
  },
  {
    nome: "Discovery Grill Morning",
    regiao: "JurassicPark",
    tipo: ["Classico", "Americano"],
    acesso: "Perto do Discovery Center",
    precoMedio: 20,
    destaque: "Café ao estilo americano com ovos, bacon e torradas. Experimente o combo clássico com panquecas.",
    latitude: 28.4763,
    longitude: -81.4707,
  },
  {
    nome: "Dino Bites Cart",
    regiao: "JurassicPark",
    tipo: "Conforto",
    acesso: "Ao lado do Raptor Encounter",
    precoMedio: 11,
    destaque: "Pretzels e croissants temáticos. Experimente o pretzel em formato de dinossauro.",
    latitude: 28.4764,
    longitude: -81.4708,
  },
  {
    nome: "Jurassic Fruit Stand",
    regiao: "JurassicPark",
    tipo: "Saudavel",
    acesso: "Caminho para a saída do River Adventure",
    precoMedio: 9,
    destaque: "Frutas tropicais e sucos naturais. Experimente a salada de frutas com maracujá.",
    latitude: 28.4762,
    longitude: -81.4709,
  },
  {
    nome: "Dino Quick Café",
    regiao: "JurassicPark",
    tipo: "Economico",
    acesso: "Carrinho próximo ao Discovery Trail",
    precoMedio: 8,
    destaque: "Bolos simples e café americano. Experimente o bolo de cenoura com canela.",
    latitude: 28.4761,
    longitude: -81.4706,
  },

  // LostContinent
  {
    nome: "Mythos Morning Café",
    regiao: "LostContinent",
    tipo: "Tematico",
    acesso: "Ao lado do restaurante Mythos",
    precoMedio: 17,
    destaque: "Cafés especiais e pães gregos. Experimente o pão de mel com iogurte grego.",
    latitude: 28.4738,
    longitude: -81.4701,
  },
  {
    nome: "Oracle’s Breakfast",
    regiao: "LostContinent",
    tipo: ["Classico", "Americano"],
    acesso: "Próximo à entrada para Seuss Landing",
    precoMedio: 20,
    destaque: "Pratos americanos com ovos, bacon e panquecas. Experimente o combo de ovos com bacon.",
    latitude: 28.4740,
    longitude: -81.4703,
  },
  {
    nome: "Athena Bakery",
    regiao: "LostContinent",
    tipo: "Conforto",
    acesso: "Em frente à fonte mágica",
    precoMedio: 12,
    destaque: "Muffins, croissants e cafés especiais. Experimente o muffin de blueberry.",
    latitude: 28.4739,
    longitude: -81.4702,
  },
  {
    nome: "Temple Fruit Stand",
    regiao: "LostContinent",
    tipo: "Saudavel",
    acesso: "Carrinho ao lado da Mystic Fountain",
    precoMedio: 10,
    destaque: "Smoothies e frutas frescas. Experimente o smoothie de abacaxi com hortelã.",
    latitude: 28.4737,
    longitude: -81.4704,
  },
  {
    nome: "Lost Morning Express",
    regiao: "LostContinent",
    tipo: "Economico",
    acesso: "Ponto rápido na saída para Jurassic Park",
    precoMedio: 8,
    destaque: "Café preto e pães simples. Experimente o bolo de chocolate quente.",
    latitude: 28.4736,
    longitude: -81.4705,
  },

  // MarvelSuperHeroIsland
  {
    nome: "Stark Café",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Tematico",
    acesso: "Próximo à entrada do simulador do Hulk",
    precoMedio: 16,
    destaque: "Café inspirado nos heróis da Marvel. Experimente o bolo de chocolate do Iron Man.",
    latitude: 28.4731,
    longitude: -81.4725,
  },
  {
    nome: "Avengers Morning Diner",
    regiao: "MarvelSuperHeroIsland",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da loja principal da Marvel",
    precoMedio: 19,
    destaque: "Café ao estilo americano com waffles e bacon. Experimente o combo especial de ovos.",
    latitude: 28.4733,
    longitude: -81.4727,
  },
  {
    nome: "Hero Bakery",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Conforto",
    acesso: "Perto da atração do Spider-Man",
    precoMedio: 12,
    destaque: "Doces temáticos e cafés cremosos. Experimente o cookie do Capitão América.",
    latitude: 28.4732,
    longitude: -81.4726,
  },
  {
    nome: "Shield Fruit Stand",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Saudavel",
    acesso: "Carrinho próximo ao Café Four",
    precoMedio: 9,
    destaque: "Frutas e smoothies energéticos. Experimente o smoothie de morango e banana.",
    latitude: 28.4730,
    longitude: -81.4728,
  },
  {
    nome: "Quick Marvel Café",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Economico",
    acesso: "Carrinho na saída da área Marvel",
    precoMedio: 8,
    destaque: "Café simples e bolos leves. Experimente o bolo de laranja.",
    latitude: 28.4729,
    longitude: -81.4729,
  },
  // MinionsLand
  {
    nome: "Gru’s Morning Café",
    regiao: "MinionsLand",
    tipo: "Tematico",
    acesso: "Próximo à atração Despicable Me Minion Mayhem",
    precoMedio: 16,
    destaque: "Café temático com doces e bolos dos Minions. Experimente a rosquinha amarela com cobertura de baunilha.",
    latitude: 28.4745,
    longitude: -81.4650,
  },
  {
    nome: "Minion Pancake House",
    regiao: "MinionsLand",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da loja dos Minions",
    precoMedio: 19,
    destaque: "Panquecas, ovos e bacon com tema Minion. Experimente o combo de panquecas com calda de morango.",
    latitude: 28.4747,
    longitude: -81.4652,
  },
  {
    nome: "Banana Bakery",
    regiao: "MinionsLand",
    tipo: "Conforto",
    acesso: "Perto da entrada da área dos Minions",
    precoMedio: 12,
    destaque: "Doces de banana e muffins especiais. Experimente o muffin de banana com gotas de chocolate.",
    latitude: 28.4746,
    longitude: -81.4651,
  },
  {
    nome: "Minion Fruit Cart",
    regiao: "MinionsLand",
    tipo: "Saudavel",
    acesso: "Carrinho na saída da Minion Mayhem",
    precoMedio: 9,
    destaque: "Frutas frescas, sucos e wraps leves. Experimente o smoothie de banana com mel.",
    latitude: 28.4744,
    longitude: -81.4653,
  },
  {
    nome: "Minion Quick Café",
    regiao: "MinionsLand",
    tipo: "Economico",
    acesso: "Ponto rápido próximo à entrada principal",
    precoMedio: 8,
    destaque: "Café simples e bolos leves. Experimente o bolo de baunilha com cobertura amarela.",
    latitude: 28.4743,
    longitude: -81.4654,
  },

  // NewYork
  {
    nome: "Broadway Morning Café",
    regiao: "NewYork",
    tipo: "Tematico",
    acesso: "Próximo à atração Revenge of the Mummy",
    precoMedio: 17,
    destaque: "Café inspirado em Nova York com bagels e doces. Experimente o bagel com cream cheese e salmão.",
    latitude: 28.4751,
    longitude: -81.4641,
  },
  {
    nome: "Times Square Breakfast",
    regiao: "NewYork",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da New York Public Library (cenário)",
    precoMedio: 20,
    destaque: "Pratos clássicos americanos com bacon e ovos. Experimente o combo de ovos com torradas.",
    latitude: 28.4753,
    longitude: -81.4643,
  },
  {
    nome: "NY Bakery",
    regiao: "NewYork",
    tipo: "Conforto",
    acesso: "Próximo ao palco da Blues Brothers Show",
    precoMedio: 12,
    destaque: "Cookies e cheesecakes típicos de NY. Experimente o cheesecake de morango.",
    latitude: 28.4752,
    longitude: -81.4642,
  },
  {
    nome: "Central Park Fruit Stand",
    regiao: "NewYork",
    tipo: "Saudavel",
    acesso: "Carrinho próximo ao cenário de Nova York",
    precoMedio: 10,
    destaque: "Frutas, smoothies e saladas leves. Experimente o smoothie de maçã e espinafre.",
    latitude: 28.4750,
    longitude: -81.4644,
  },
  {
    nome: "Quick Bagel Stop",
    regiao: "NewYork",
    tipo: "Economico",
    acesso: "Ponto rápido ao lado do restaurante Louie’s",
    precoMedio: 8,
    destaque: "Café preto e bagels simples. Experimente o bagel com manteiga.",
    latitude: 28.4749,
    longitude: -81.4645,
  },

  // ProductionCentral
  {
    nome: "Studio Café",
    regiao: "ProductionCentral",
    tipo: "Tematico",
    acesso: "Próximo à entrada principal do parque",
    precoMedio: 15,
    destaque: "Café temático de estúdios de cinema. Experimente o muffin de cenoura com glacê.",
    latitude: 28.4758,
    longitude: -81.4630,
  },
  {
    nome: "Director’s Breakfast",
    regiao: "ProductionCentral",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atração Despicable Me Minion Mayhem",
    precoMedio: 19,
    destaque: "Café americano com ovos e panquecas. Experimente o combo clássico.",
    latitude: 28.4760,
    longitude: -81.4632,
  },
  {
    nome: "Movie Bakery",
    regiao: "ProductionCentral",
    tipo: "Conforto",
    acesso: "Em frente ao Universal Store",
    precoMedio: 11,
    destaque: "Cookies, donuts e cafés. Experimente o donut de chocolate.",
    latitude: 28.4759,
    longitude: -81.4631,
  },
  {
    nome: "Cinematic Fruit Stand",
    regiao: "ProductionCentral",
    tipo: "Saudavel",
    acesso: "Carrinho próximo à entrada do parque",
    precoMedio: 9,
    destaque: "Frutas frescas e barras energéticas. Experimente o bowl de frutas com mel.",
    latitude: 28.4757,
    longitude: -81.4633,
  },
  {
    nome: "Quick Studio Café",
    regiao: "ProductionCentral",
    tipo: "Economico",
    acesso: "Ponto rápido em frente à Universal Store",
    precoMedio: 8,
    destaque: "Café preto e bolos simples. Experimente o bolo de baunilha.",
    latitude: 28.4756,
    longitude: -81.4634,
  },

  // SanFrancisco
  {
    nome: "Pier 39 Morning Café",
    regiao: "SanFrancisco",
    tipo: "Tematico",
    acesso: "Próximo à atração Fast & Furious – Supercharged",
    precoMedio: 17,
    destaque: "Café inspirado no Pier 39 com muffins e pães. Experimente o muffin de limão com cobertura.",
    latitude: 28.4767,
    longitude: -81.4615,
  },
  {
    nome: "Golden Gate Breakfast",
    regiao: "SanFrancisco",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado do restaurante Lombard’s Seafood Grille",
    precoMedio: 20,
    destaque: "Pratos clássicos com bacon, ovos e panquecas. Experimente o combo de ovos com bacon crocante.",
    latitude: 28.4769,
    longitude: -81.4617,
  },
  {
    nome: "Bay Bakery",
    regiao: "SanFrancisco",
    tipo: "Conforto",
    acesso: "Perto da área de Dockside",
    precoMedio: 12,
    destaque: "Cookies e brownies artesanais. Experimente o brownie de chocolate com nozes.",
    latitude: 28.4768,
    longitude: -81.4616,
  },
  {
    nome: "Fisherman Fruit Stand",
    regiao: "SanFrancisco",
    tipo: "Saudavel",
    acesso: "Carrinho próximo ao pier",
    precoMedio: 10,
    destaque: "Smoothies e frutas frescas. Experimente o smoothie de frutas cítricas.",
    latitude: 28.4766,
    longitude: -81.4618,
  },
  {
    nome: "Quick Bay Café",
    regiao: "SanFrancisco",
    tipo: "Economico",
    acesso: "Ponto rápido próximo ao Lombard’s",
    precoMedio: 8,
    destaque: "Café preto e donuts simples. Experimente o donut de açúcar.",
    latitude: 28.4765,
    longitude: -81.4619,
  },
  // SeussLanding
  {
    nome: "Cat in the Hat Café",
    regiao: "SeussLanding",
    tipo: "Tematico",
    acesso: "Próximo à atração The Cat in the Hat",
    precoMedio: 15,
    destaque: "Café lúdico com doces coloridos inspirados no Dr. Seuss. Experimente o cupcake do Lorax.",
    latitude: 28.4739,
    longitude: -81.4709,
  },
  {
    nome: "Green Eggs & Ham Breakfast",
    regiao: "SeussLanding",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da montanha-russa infantil",
    precoMedio: 19,
    destaque: "Pratos inspirados nos livros, com ovos verdes e bacon. Experimente o combo temático.",
    latitude: 28.4740,
    longitude: -81.4708,
  },
  {
    nome: "Thing 1 Bakery",
    regiao: "SeussLanding",
    tipo: "Conforto",
    acesso: "Em frente ao One Fish, Two Fish",
    precoMedio: 11,
    destaque: "Doces, muffins e cafés especiais. Experimente o muffin de morango com cobertura azul.",
    latitude: 28.4741,
    longitude: -81.4707,
  },
  {
    nome: "Who-ville Fruit Stand",
    regiao: "SeussLanding",
    tipo: "Saudavel",
    acesso: "Carrinho próximo ao Caro-Seuss-el",
    precoMedio: 9,
    destaque: "Frutas e smoothies coloridos. Experimente o smoothie de frutas tropicais.",
    latitude: 28.4738,
    longitude: -81.4706,
  },
  {
    nome: "Quick Seuss Café",
    regiao: "SeussLanding",
    tipo: "Economico",
    acesso: "Ponto rápido perto da entrada da área",
    precoMedio: 8,
    destaque: "Café preto e bolos simples. Experimente o bolo de baunilha com glacê.",
    latitude: 28.4737,
    longitude: -81.4705,
  },

  // SuperNintendoWorld
  {
    nome: "Toad Café Morning",
    regiao: "SuperNintendoWorld",
    tipo: "Tematico",
    acesso: "Dentro da área do Mario Kart",
    precoMedio: 18,
    destaque: "Café temático com doces e bebidas inspiradas no Mario. Experimente o bolo da Princesa Peach.",
    latitude: 28.4772,
    longitude: -81.4680,
  },
  {
    nome: "Peach’s Bakery",
    regiao: "SuperNintendoWorld",
    tipo: ["Classico", "Americano"],
    acesso: "Próximo à entrada principal da área",
    precoMedio: 20,
    destaque: "Waffles e panquecas temáticas. Experimente o waffle do Luigi com calda de morango.",
    latitude: 28.4771,
    longitude: -81.4682,
  },
  {
    nome: "Luigi’s Snack Stand",
    regiao: "SuperNintendoWorld",
    tipo: "Conforto",
    acesso: "Ao lado do Bowser’s Challenge",
    precoMedio: 12,
    destaque: "Cookies e cappuccinos. Experimente o cappuccino verde do Luigi.",
    latitude: 28.4773,
    longitude: -81.4681,
  },
  {
    nome: "Yoshi’s Fruit Corner",
    regiao: "SuperNintendoWorld",
    tipo: "Saudavel",
    acesso: "Perto do Yoshi’s Adventure",
    precoMedio: 10,
    destaque: "Smoothies e frutas frescas. Experimente o smoothie tropical do Yoshi.",
    latitude: 28.4770,
    longitude: -81.4683,
  },
  {
    nome: "Mario Quick Morning",
    regiao: "SuperNintendoWorld",
    tipo: "Economico",
    acesso: "Carrinho próximo à entrada",
    precoMedio: 9,
    destaque: "Café preto e biscoitos temáticos. Experimente o cookie de estrela.",
    latitude: 28.4769,
    longitude: -81.4684,
  },

  // TheWitcher
  {
    nome: "Kaer Morhen Café",
    regiao: "TheWitcher",
    tipo: "Tematico",
    acesso: "Próximo à entrada principal da área",
    precoMedio: 17,
    destaque: "Café inspirado no universo de The Witcher, com pães rústicos e hidromel quente. Experimente o pão doce com especiarias.",
    latitude: 28.4782,
    longitude: -81.4600,
  },
  {
    nome: "Geralt’s Breakfast",
    regiao: "TheWitcher",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da taverna temática",
    precoMedio: 20,
    destaque: "Pratos matinais robustos com ovos e linguiça. Experimente o combo com pão artesanal.",
    latitude: 28.4783,
    longitude: -81.4601,
  },
  {
    nome: "Sorcerer’s Bakery",
    regiao: "TheWitcher",
    tipo: "Conforto",
    acesso: "Próximo ao show de magia",
    precoMedio: 12,
    destaque: "Doces e bolos com especiarias. Experimente o muffin de maçã e canela.",
    latitude: 28.4784,
    longitude: -81.4602,
  },
  {
    nome: "Yennefer’s Fruit Stand",
    regiao: "TheWitcher",
    tipo: "Saudavel",
    acesso: "Carrinho ao lado da área principal",
    precoMedio: 9,
    destaque: "Frutas e bebidas naturais. Experimente o smoothie de frutas roxas.",
    latitude: 28.4781,
    longitude: -81.4603,
  },
  {
    nome: "Witcher Quick Café",
    regiao: "TheWitcher",
    tipo: "Economico",
    acesso: "Ponto rápido próximo ao portal",
    precoMedio: 8,
    destaque: "Café preto e biscoitos simples. Experimente o cookie de mel.",
    latitude: 28.4780,
    longitude: -81.4604,
  },

  // TheWizardingWorld
  {
    nome: "Leaky Cauldron Morning",
    regiao: "TheWizardingWorld",
    tipo: "Tematico",
    acesso: "Próximo à entrada do Beco Diagonal",
    precoMedio: 18,
    destaque: "Café temático com pratos britânicos. Experimente o pão de mel com chá inglês.",
    latitude: 28.4760,
    longitude: -81.4690,
  },
  {
    nome: "Diagon Alley Breakfast",
    regiao: "TheWizardingWorld",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da Gringotts Bank",
    precoMedio: 21,
    destaque: "Pratos britânicos com ovos e linguiça. Experimente o combo clássico de café da manhã.",
    latitude: 28.4762,
    longitude: -81.4692,
  },
  {
    nome: "Ollivander’s Bakery",
    regiao: "TheWizardingWorld",
    tipo: "Conforto",
    acesso: "Próximo à loja de varinhas",
    precoMedio: 12,
    destaque: "Doces mágicos e bolos especiais. Experimente o bolo de abóbora.",
    latitude: 28.4761,
    longitude: -81.4691,
  },
  {
    nome: "Magic Fruit Stand",
    regiao: "TheWizardingWorld",
    tipo: "Saudavel",
    acesso: "Carrinho próximo ao palco de feitiços",
    precoMedio: 9,
    destaque: "Frutas e sucos especiais. Experimente o suco de abóbora.",
    latitude: 28.4759,
    longitude: -81.4693,
  },
  {
    nome: "Quick Wizard Café",
    regiao: "TheWizardingWorld",
    tipo: "Economico",
    acesso: "Ponto rápido ao lado da entrada do Beco Diagonal",
    precoMedio: 8,
    destaque: "Café preto e bolos simples. Experimente o muffin de chocolate.",
    latitude: 28.4758,
    longitude: -81.4694,
  },
  // TheWizardingWorldHogsmeade
  {
    nome: "Three Broomsticks Breakfast",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Tematico",
    acesso: "Dentro do restaurante Três Vassouras",
    precoMedio: 19,
    destaque: "Café britânico completo com pratos típicos. Experimente o feijão com torradas e ovos.",
    latitude: 28.4732,
    longitude: -81.4702,
  },
  {
    nome: "Hogsmeade Morning Feast",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da loja Zonko's",
    precoMedio: 20,
    destaque: "Pratos robustos com bacon, ovos e salsichas. Experimente o combo especial com panquecas.",
    latitude: 28.4733,
    longitude: -81.4703,
  },
  {
    nome: "Honeydukes Bakery",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Conforto",
    acesso: "Próximo à loja Honeydukes",
    precoMedio: 12,
    destaque: "Doces mágicos e muffins especiais. Experimente o muffin de chocolate branco.",
    latitude: 28.4734,
    longitude: -81.4704,
  },
  {
    nome: "Butterbeer Fruit Cart",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Saudavel",
    acesso: "Carrinho próximo à entrada do castelo",
    precoMedio: 10,
    destaque: "Frutas frescas e sucos naturais. Experimente o suco de maçã com canela.",
    latitude: 28.4731,
    longitude: -81.4705,
  },
  {
    nome: "Quick Owl Café",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Economico",
    acesso: "Ponto rápido perto da entrada da área",
    precoMedio: 8,
    destaque: "Café preto e bolos simples. Experimente o bolo de abóbora.",
    latitude: 28.4730,
    longitude: -81.4706,
  },

  // ToonLagoon
  {
    nome: "Popeye’s Breakfast Spot",
    regiao: "ToonLagoon",
    tipo: "Tematico",
    acesso: "Próximo à atração Popeye & Bluto’s Bilge-Rat Barges",
    precoMedio: 16,
    destaque: "Café temático com pratos energéticos. Experimente o sanduíche de ovos com espinafre.",
    latitude: 28.4728,
    longitude: -81.4715,
  },
  {
    nome: "Cartoon Morning Diner",
    regiao: "ToonLagoon",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado do Dudley Do-Right’s Ripsaw Falls",
    precoMedio: 19,
    destaque: "Pratos clássicos com bacon e panquecas. Experimente o combo com ovos mexidos.",
    latitude: 28.4729,
    longitude: -81.4716,
  },
  {
    nome: "Toon Bakery",
    regiao: "ToonLagoon",
    tipo: "Conforto",
    acesso: "Próximo à loja Betty Boop",
    precoMedio: 12,
    destaque: "Cookies e muffins temáticos. Experimente o cookie do Popeye com amendoim.",
    latitude: 28.4727,
    longitude: -81.4717,
  },
  {
    nome: "Lagoon Fruit Cart",
    regiao: "ToonLagoon",
    tipo: "Saudavel",
    acesso: "Carrinho próximo ao ponto de observação da água",
    precoMedio: 10,
    destaque: "Smoothies, frutas e barras leves. Experimente o smoothie de manga.",
    latitude: 28.4726,
    longitude: -81.4718,
  },
  {
    nome: "Quick Toon Café",
    regiao: "ToonLagoon",
    tipo: "Economico",
    acesso: "Ponto rápido na saída da área",
    precoMedio: 8,
    destaque: "Café simples e pães. Experimente o pão doce de canela.",
    latitude: 28.4725,
    longitude: -81.4719,
  },

  // UniversalMonsters
  {
    nome: "Monster Café Morning",
    regiao: "UniversalMonsters",
    tipo: "Tematico",
    acesso: "Próximo à área clássica de monstros",
    precoMedio: 17,
    destaque: "Café temático com pratos inspirados em filmes clássicos. Experimente o bolo de chocolate do Drácula.",
    latitude: 28.4764,
    longitude: -81.4685,
  },
  {
    nome: "Classic Horror Breakfast",
    regiao: "UniversalMonsters",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado do teatro de shows",
    precoMedio: 20,
    destaque: "Pratos clássicos de café da manhã com estilo retrô. Experimente o combo com bacon e panquecas.",
    latitude: 28.4765,
    longitude: -81.4686,
  },
  {
    nome: "Mummy’s Bakery",
    regiao: "UniversalMonsters",
    tipo: "Conforto",
    acesso: "Perto da atração Revenge of the Mummy",
    precoMedio: 12,
    destaque: "Doces e cafés especiais. Experimente o pão de mel com especiarias.",
    latitude: 28.4763,
    longitude: -81.4684,
  },
  {
    nome: "Wolfman’s Fruit Cart",
    regiao: "UniversalMonsters",
    tipo: "Saudavel",
    acesso: "Carrinho próximo ao estande de fotos",
    precoMedio: 9,
    destaque: "Frutas e barras leves. Experimente a salada de frutas com mel.",
    latitude: 28.4762,
    longitude: -81.4683,
  },
  {
    nome: "Quick Monster Café",
    regiao: "UniversalMonsters",
    tipo: "Economico",
    acesso: "Ponto rápido na entrada da área",
    precoMedio: 8,
    destaque: "Café preto e bolos simples. Experimente o bolo de chocolate.",
    latitude: 28.4761,
    longitude: -81.4682,
  },

  // WorldExpo
  {
    nome: "Expo Start Café",
    regiao: "WorldExpo",
    tipo: "Tematico",
    acesso: "Próximo ao Men in Black: Alien Attack",
    precoMedio: 16,
    destaque: "Café com tema futurista. Experimente o donut galáctico com glacê azul.",
    latitude: 28.4775,
    longitude: -81.4671,
  },
  {
    nome: "Future Breakfast Hub",
    regiao: "WorldExpo",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado do simulador de MIB",
    precoMedio: 19,
    destaque: "Pratos clássicos com bacon, ovos e panquecas. Experimente o combo tradicional.",
    latitude: 28.4776,
    longitude: -81.4672,
  },
  {
    nome: "Cosmic Bakery",
    regiao: "WorldExpo",
    tipo: "Conforto",
    acesso: "Próximo ao palco futurista",
    precoMedio: 11,
    destaque: "Cookies, brownies e café expresso. Experimente o cookie de chocolate galáctico.",
    latitude: 28.4774,
    longitude: -81.4670,
  },
  {
    nome: "Galaxy Fruit Stand",
    regiao: "WorldExpo",
    tipo: "Saudavel",
    acesso: "Carrinho próximo à área Kids Zone",
    precoMedio: 9,
    destaque: "Smoothies, frutas e wraps leves. Experimente o smoothie de framboesa.",
    latitude: 28.4773,
    longitude: -81.4669,
  },
  {
    nome: "Quick Expo Café",
    regiao: "WorldExpo",
    tipo: "Economico",
    acesso: "Ponto rápido perto do MIB Shop",
    precoMedio: 8,
    destaque: "Café preto e bolos simples. Experimente o bolo de baunilha.",
    latitude: 28.4772,
    longitude: -81.4668,
  },
];



