export const jantaresUniversal = [
  // FogosEpicoUniverse
  {
    nome: "Epic Lagoon Grill",
    regiao: "FogosEpicoUniverse",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo ao lago central do Epic Universe, com visÃ£o privilegiada para o show noturno",
    precoMedio: 48,
    destaque: "Pratos grelhados e frutos do mar com vista para os fogos. Experimente o filÃ© com molho de vinho tinto.",
    latitude: 28.4701,
    longitude: -81.4601,
  },
  {
    nome: "Twilight Terrace",
    regiao: "FogosEpicoUniverse",
    tipo: "Tematico",
    acesso: "Deck principal para assistir ao espetÃ¡culo de fogos",
    precoMedio: 42,
    destaque: "CardÃ¡pio temÃ¡tico com iluminaÃ§Ã£o especial. Experimente o salmÃ£o ao molho de maracujÃ¡.",
    latitude: 28.4702,
    longitude: -81.4602,
  },
  {
    nome: "Lagoon Snacks",
    regiao: "FogosEpicoUniverse",
    tipo: "Economico",
    acesso: "Quiosque lateral do viewing area",
    precoMedio: 15,
    destaque: "Snacks rÃ¡pidos para o show. Experimente o wrap de frango grelhado.",
    latitude: 28.4703,
    longitude: -81.4603,
  },
  {
    nome: "Fireworks Greens",
    regiao: "FogosEpicoUniverse",
    tipo: "Saudavel",
    acesso: "Ãrea de refeiÃ§Ãµes leves prÃ³xima ao lago",
    precoMedio: 23,
    destaque: "Saladas e bowls ideais para um jantar leve. Experimente a salada de quinoa com frutas.",
    latitude: 28.4704,
    longitude: -81.4604,
  },
  {
    nome: "Epic Comfort Bites",
    regiao: "FogosEpicoUniverse",
    tipo: "Conforto",
    acesso: "Ao lado do deck panorÃ¢mico",
    precoMedio: 30,
    destaque: "Pratos reconfortantes para apreciar durante o show. Experimente a costelinha barbecue com purÃª.",
    latitude: 28.4705,
    longitude: -81.4605,
  },

  // FogosIslandsOfAdventure
  {
    nome: "Islands Lagoon Dining",
    regiao: "FogosIslandsOfAdventure",
    tipo: ["Classico", "Americano"],
    acesso: "Frente ao lago com vista para o show noturno",
    precoMedio: 45,
    destaque: "Pratos tradicionais americanos e carnes grelhadas. Experimente o hambÃºrguer gourmet com fritas rÃºsticas.",
    latitude: 28.4721,
    longitude: -81.4621,
  },
  {
    nome: "Adventure Lights CafÃ©",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Tematico",
    acesso: "Ãrea iluminada prÃ³xima ao viewing spot",
    precoMedio: 37,
    destaque: "Ambiente temÃ¡tico com decoraÃ§Ã£o de aventura. Experimente o frango grelhado com arroz selvagem.",
    latitude: 28.4722,
    longitude: -81.4622,
  },
  {
    nome: "Lagoon Snack Bar",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Economico",
    acesso: "Quiosque lateral prÃ³ximo ao show",
    precoMedio: 14,
    destaque: "Snacks, wraps e bebidas rÃ¡pidas. Experimente o wrap de peru com molho de mostarda.",
    latitude: 28.4723,
    longitude: -81.4623,
  },
  {
    nome: "Adventure Greens",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo Ã  Ã¡rea central do lago",
    precoMedio: 20,
    destaque: "Saladas frescas e bowls vegetarianos. Experimente a salada com avocado e mix de grÃ£os.",
    latitude: 28.4724,
    longitude: -81.4624,
  },
  {
    nome: "Island Comfort Grill",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Conforto",
    acesso: "Ãrea principal de alimentaÃ§Ã£o",
    precoMedio: 29,
    destaque: "Comidas confortÃ¡veis, massas e grelhados. Experimente o mac and cheese trufado.",
    latitude: 28.4725,
    longitude: -81.4625,
  },

  // FogosUniversalStudios
  {
    nome: "Universal Lagoon Grill",
    regiao: "FogosUniversalStudios",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo ao lago central do Universal Studios, com vista para o show noturno",
    precoMedio: 44,
    destaque: "Carnes grelhadas e frutos do mar em ambiente sofisticado. Experimente o filÃ© mignon com purÃª trufado.",
    latitude: 28.4800,
    longitude: -81.4710,
  },
  {
    nome: "Night Spark CafÃ©",
    regiao: "FogosUniversalStudios",
    tipo: "Tematico",
    acesso: "Ao lado da entrada para o viewing area do show de fogos",
    precoMedio: 39,
    destaque: "Ambiente imersivo com iluminaÃ§Ã£o especial para a noite. NÃ£o deixe de experimentar o camarÃ£o ao alho e Ã³leo.",
    latitude: 28.4801,
    longitude: -81.4711,
  },
  {
    nome: "Studio Snacks",
    regiao: "FogosUniversalStudios",
    tipo: "Economico",
    acesso: "Quiosque prÃ³ximo ao viewing area principal",
    precoMedio: 14,
    destaque: "Snacks e petiscos rÃ¡pidos para curtir os fogos. Experimente o wrap de frango grelhado.",
    latitude: 28.4802,
    longitude: -81.4712,
  },
  {
    nome: "Lagoon Greens",
    regiao: "FogosUniversalStudios",
    tipo: "Saudavel",
    acesso: "Ãrea externa perto do show principal",
    precoMedio: 23,
    destaque: "Saladas frescas e pratos leves para a noite. Experimente a salada com quinoa e abacate.",
    latitude: 28.4803,
    longitude: -81.4713,
  },
  {
    nome: "Lagoon Premium Dining",
    regiao: "FogosUniversalStudios",
    tipo: "Conforto",
    acesso: "Ãrea VIP de refeiÃ§Ãµes prÃ³xima ao lago principal",
    precoMedio: 50,
    destaque: "Menu premium com vista exclusiva para o show. Experimente o salmÃ£o grelhado com molho de maracujÃ¡.",
    latitude: 28.4804,
    longitude: -81.4714,
  },

  // Hollywood
  {
    nome: "Hollywood Grill",
    regiao: "Hollywood",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo ao Hollywood Boulevard",
    precoMedio: 41,
    destaque: "Pratos clÃ¡ssicos com ambiente inspirado na Era de Ouro de Hollywood. Experimente o hambÃºrguer com bacon defumado.",
    latitude: 28.4810,
    longitude: -81.4720,
  },
  {
    nome: "CineStar Diner",
    regiao: "Hollywood",
    tipo: "Tematico",
    acesso: "Ao lado do Cinema 4D",
    precoMedio: 34,
    destaque: "DecoraÃ§Ã£o de cinema com pratos temÃ¡ticos. Experimente o mac and cheese trufado.",
    latitude: 28.4811,
    longitude: -81.4721,
  },
  {
    nome: "Hollywood Snacks",
    regiao: "Hollywood",
    tipo: "Economico",
    acesso: "Perto da entrada do Hollywood Boulevard",
    precoMedio: 12,
    destaque: "Snacks rÃ¡pidos e acessÃ­veis para o jantar. Experimente o cachorro-quente com molho especial.",
    latitude: 28.4812,
    longitude: -81.4722,
  },
  {
    nome: "Star Greens",
    regiao: "Hollywood",
    tipo: "Saudavel",
    acesso: "Ao lado do Universal Theater",
    precoMedio: 22,
    destaque: "Saladas e wraps para refeiÃ§Ãµes leves. Experimente o wrap de frango Caesar.",
    latitude: 28.4813,
    longitude: -81.4723,
  },
  {
    nome: "Boulevard Bistro",
    regiao: "Hollywood",
    tipo: "Conforto",
    acesso: "No final do Hollywood Boulevard, prÃ³ximo Ã s lojas temÃ¡ticas",
    precoMedio: 27,
    destaque: "CulinÃ¡ria americana com pratos reconfortantes. Experimente a costela barbecue com batatas rÃºsticas.",
    latitude: 28.4814,
    longitude: -81.4724,
  },
  // HowToTrainYourDragon
  {
    nome: "Berk Viking Grill",
    regiao: "HowToTrainYourDragon",
    tipo: ["Classico", "Americano"],
    acesso: "No centro da vila de Berk, perto da atraÃ§Ã£o principal",
    precoMedio: 38,
    destaque: "Carnes grelhadas no estilo viking com acompanhamentos robustos. Experimente o prato de costela com batata assada.",
    latitude: 28.4820,
    longitude: -81.4730,
  },
  {
    nome: "Dragons Feast Hall",
    regiao: "HowToTrainYourDragon",
    tipo: "Tematico",
    acesso: "PrÃ³ximo ao show dos dragÃµes, com decoraÃ§Ã£o nÃ³rdica",
    precoMedio: 42,
    destaque: "RefeiÃ§Ãµes inspiradas em festins vikings com pratos de caÃ§a e peixe. Experimente o salmÃ£o com molho de ervas.",
    latitude: 28.4821,
    longitude: -81.4731,
  },
  {
    nome: "Hiccup's Quick Bites",
    regiao: "HowToTrainYourDragon",
    tipo: "Economico",
    acesso: "Ao lado da Ã¡rea de jogos do SoluÃ§o",
    precoMedio: 14,
    destaque: "Lanches rÃ¡pidos para quem estÃ¡ com pressa. Experimente o sanduÃ­che de frango com queijo.",
    latitude: 28.4822,
    longitude: -81.4732,
  },
  {
    nome: "Astridâ€™s Greens",
    regiao: "HowToTrainYourDragon",
    tipo: "Saudavel",
    acesso: "Perto da Ã¡rea de treinamento de dragÃµes",
    precoMedio: 21,
    destaque: "Bowls leves e wraps saudÃ¡veis com ingredientes frescos. Experimente a salada com grÃ£os e molho de iogurte.",
    latitude: 28.4823,
    longitude: -81.4733,
  },
  {
    nome: "Dragon Comfort Diner",
    regiao: "HowToTrainYourDragon",
    tipo: "Conforto",
    acesso: "Ao lado da loja de souvenirs de Berk",
    precoMedio: 27,
    destaque: "Pratos confortÃ¡veis para encerrar o dia. Experimente o ensopado de carne com legumes.",
    latitude: 28.4824,
    longitude: -81.4734,
  },

  // JurassicPark
  {
    nome: "Jurassic Grill",
    regiao: "JurassicPark",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da entrada do Jurassic River Adventure",
    precoMedio: 40,
    destaque: "Carnes e hambÃºrgueres com tema jurÃ¡ssico. Experimente o T-Rex Burger com bacon e cheddar.",
    latitude: 28.4830,
    longitude: -81.4740,
  },
  {
    nome: "Raptorâ€™s Feast",
    regiao: "JurassicPark",
    tipo: "Tematico",
    acesso: "Perto da Ã¡rea de exibiÃ§Ã£o dos velociraptors",
    precoMedio: 36,
    destaque: "Pratos temÃ¡ticos com carnes grelhadas e molhos especiais. Experimente o frango ao molho de manga picante.",
    latitude: 28.4831,
    longitude: -81.4741,
  },
  {
    nome: "Dino Snacks",
    regiao: "JurassicPark",
    tipo: "Economico",
    acesso: "Quiosque prÃ³ximo ao Jurassic Outfitters",
    precoMedio: 13,
    destaque: "Snacks rÃ¡pidos como wraps e nachos. Experimente o wrap de frango grelhado.",
    latitude: 28.4832,
    longitude: -81.4742,
  },
  {
    nome: "Jurassic Greens",
    regiao: "JurassicPark",
    tipo: "Saudavel",
    acesso: "Ãrea sombreada prÃ³xima Ã  Discovery Center",
    precoMedio: 20,
    destaque: "Saladas frescas e bowls leves para os fÃ£s de saÃºde. Experimente o bowl de quinoa com salmÃ£o grelhado.",
    latitude: 28.4833,
    longitude: -81.4743,
  },
  {
    nome: "Herbivore Comfort Grill",
    regiao: "JurassicPark",
    tipo: "Conforto",
    acesso: "Em frente ao portÃ£o principal de Jurassic Park",
    precoMedio: 29,
    destaque: "Massas e carnes ao estilo caseiro. Experimente o mac and cheese com costela desfiada.",
    latitude: 28.4834,
    longitude: -81.4744,
  },

  // LostContinent
  {
    nome: "Mythos Restaurant",
    regiao: "LostContinent",
    tipo: ["Classico", "Americano"],
    acesso: "No centro do Lost Continent, prÃ³ximo Ã  fonte principal",
    precoMedio: 44,
    destaque: "Restaurante premiado com culinÃ¡ria variada. Experimente o filÃ© de peixe ao molho cÃ­trico.",
    latitude: 28.4840,
    longitude: -81.4750,
  },
  {
    nome: "Poseidonâ€™s Table",
    regiao: "LostContinent",
    tipo: "Tematico",
    acesso: "Ao lado da atraÃ§Ã£o Poseidonâ€™s Fury",
    precoMedio: 38,
    destaque: "Ambiente temÃ¡tico inspirado na mitologia grega. Experimente o polvo grelhado com azeite de ervas.",
    latitude: 28.4841,
    longitude: -81.4751,
  },
  {
    nome: "Oracle Snacks",
    regiao: "LostContinent",
    tipo: "Economico",
    acesso: "Em frente Ã  entrada do The Eighth Voyage of Sindbad",
    precoMedio: 12,
    destaque: "Lanches rÃ¡pidos e petiscos leves. Experimente a pita com frango assado.",
    latitude: 28.4842,
    longitude: -81.4752,
  },
  {
    nome: "Olympus Greens",
    regiao: "LostContinent",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo ao Mythos Restaurant",
    precoMedio: 22,
    destaque: "Pratos leves com saladas e wraps mediterrÃ¢neos. Experimente a salada grega com queijo feta.",
    latitude: 28.4843,
    longitude: -81.4753,
  },
  {
    nome: "Lost Comfort Kitchen",
    regiao: "LostContinent",
    tipo: "Conforto",
    acesso: "Perto da saÃ­da do Lost Continent",
    precoMedio: 28,
    destaque: "Pratos robustos como carne assada e massas. Experimente o penne com molho de tomate rÃºstico.",
    latitude: 28.4844,
    longitude: -81.4754,
  },

  // MarvelSuperHeroIsland
  {
    nome: "Avengers Grill",
    regiao: "MarvelSuperHeroIsland",
    tipo: ["Classico", "Americano"],
    acesso: "Em frente Ã  atraÃ§Ã£o The Incredible Hulk Coaster",
    precoMedio: 39,
    destaque: "Comida clÃ¡ssica americana com ambiente de super-herÃ³is. Experimente o hambÃºrguer do Hulk com queijo cheddar.",
    latitude: 28.4850,
    longitude: -81.4760,
  },
  {
    nome: "Heroâ€™s Diner",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Tematico",
    acesso: "Ao lado da Spider-Man Store",
    precoMedio: 35,
    destaque: "Pratos inspirados nos herÃ³is da Marvel. Experimente o frango grelhado com batata rÃºstica.",
    latitude: 28.4851,
    longitude: -81.4761,
  },
  {
    nome: "Marvel Quick Eats",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Economico",
    acesso: "Perto da entrada do CafÃ© 4",
    precoMedio: 13,
    destaque: "Snacks rÃ¡pidos como sanduÃ­ches e wraps. Experimente o wrap de presunto com queijo.",
    latitude: 28.4852,
    longitude: -81.4762,
  },
  {
    nome: "Superhero Greens",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Saudavel",
    acesso: "Ãrea lateral da Marvel Super Hero Island",
    precoMedio: 20,
    destaque: "Bowls e saladas energÃ©ticas. Experimente a salada com frango grelhado e quinoa.",
    latitude: 28.4853,
    longitude: -81.4763,
  },
  {
    nome: "Hero Comfort Bites",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Conforto",
    acesso: "Ao lado do CafÃ© 4",
    precoMedio: 27,
    destaque: "Massas e pratos quentes inspirados nos herÃ³is. Experimente o mac and cheese com frango crocante.",
    latitude: 28.4854,
    longitude: -81.4764,
  },

  // MinionsLand
  {
    nome: "Minionâ€™s Banana Grill",
    regiao: "MinionsLand",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  entrada da Minion Mayhem",
    precoMedio: 36,
    destaque: "Pratos americanos com um toque divertido dos Minions. Experimente o cheeseburger com molho de banana especial.",
    latitude: 28.4860,
    longitude: -81.4770,
  },
  {
    nome: "Gruâ€™s Lab Kitchen",
    regiao: "MinionsLand",
    tipo: "Tematico",
    acesso: "Dentro do laboratÃ³rio do Gru, ao lado da atraÃ§Ã£o principal",
    precoMedio: 40,
    destaque: "Ambiente imersivo com pratos temÃ¡ticos. Experimente o frango grelhado com purÃª roxo.",
    latitude: 28.4861,
    longitude: -81.4771,
  },
  {
    nome: "Minion Bites",
    regiao: "MinionsLand",
    tipo: "Economico",
    acesso: "Quiosque ao lado da loja dos Minions",
    precoMedio: 12,
    destaque: "Lanches rÃ¡pidos para toda a famÃ­lia. Experimente o wrap de presunto com queijo cheddar.",
    latitude: 28.4862,
    longitude: -81.4772,
  },
  {
    nome: "Banana Greens",
    regiao: "MinionsLand",
    tipo: "Saudavel",
    acesso: "Perto da Ã¡rea de fotos com os Minions",
    precoMedio: 21,
    destaque: "Saladas tropicais e bowls leves. Experimente a salada com abacaxi e frango grelhado.",
    latitude: 28.4863,
    longitude: -81.4773,
  },
  {
    nome: "Minion Comfort CafÃ©",
    regiao: "MinionsLand",
    tipo: "Conforto",
    acesso: "PrÃ³ximo ao Minion CafÃ© oficial",
    precoMedio: 25,
    destaque: "Pratos confortÃ¡veis e sobremesas temÃ¡ticas. Experimente o mac and cheese com crocante de banana.",
    latitude: 28.4864,
    longitude: -81.4774,
  },

  // NewYork
  {
    nome: "Big Apple Grill",
    regiao: "NewYork",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  atraÃ§Ã£o The Mummy",
    precoMedio: 42,
    destaque: "Pratos tÃ­picos de Nova York, como steaks e burgers. Experimente o hambÃºrguer com bacon e cebolas caramelizadas.",
    latitude: 28.4870,
    longitude: -81.4780,
  },
  {
    nome: "Broadway Diner",
    regiao: "NewYork",
    tipo: "Tematico",
    acesso: "Ao lado da Ã¡rea de shows do New York Street",
    precoMedio: 38,
    destaque: "Ambiente com decoraÃ§Ã£o de teatro da Broadway. Experimente o frango ao molho de vinho.",
    latitude: 28.4871,
    longitude: -81.4781,
  },
  {
    nome: "NYC Quick Eats",
    regiao: "NewYork",
    tipo: "Economico",
    acesso: "Ao lado do cafÃ© da Ã¡rea de Nova York",
    precoMedio: 14,
    destaque: "Lanches rÃ¡pidos em estilo deli. Experimente o sanduÃ­che de pastrami.",
    latitude: 28.4872,
    longitude: -81.4782,
  },
  {
    nome: "Empire Greens",
    regiao: "NewYork",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo Ã  entrada do Race Through New York",
    precoMedio: 22,
    destaque: "Saladas frescas e opÃ§Ãµes leves. Experimente a salada de rÃºcula com parmesÃ£o.",
    latitude: 28.4873,
    longitude: -81.4783,
  },
  {
    nome: "Liberty Comfort Food",
    regiao: "NewYork",
    tipo: "Conforto",
    acesso: "Ãrea central da rua principal de Nova York",
    precoMedio: 28,
    destaque: "Comida caseira inspirada na cultura nova-iorquina. Experimente o macarrÃ£o com queijo e bacon.",
    latitude: 28.4874,
    longitude: -81.4784,
  },

  // ProductionCentral
  {
    nome: "Directorâ€™s Grill",
    regiao: "ProductionCentral",
    tipo: ["Classico", "Americano"],
    acesso: "No centro da Production Central",
    precoMedio: 40,
    destaque: "Pratos clÃ¡ssicos servidos em ambiente de estÃºdio. Experimente o filÃ© de frango grelhado com arroz.",
    latitude: 28.4880,
    longitude: -81.4790,
  },
  {
    nome: "Studio Diner",
    regiao: "ProductionCentral",
    tipo: "Tematico",
    acesso: "Perto do simulador Despicable Me",
    precoMedio: 37,
    destaque: "DecoraÃ§Ã£o de estÃºdio de cinema com pratos temÃ¡ticos. Experimente o hambÃºrguer de costela com molho barbecue.",
    latitude: 28.4881,
    longitude: -81.4791,
  },
  {
    nome: "Production Snacks",
    regiao: "ProductionCentral",
    tipo: "Economico",
    acesso: "Quiosque na Ã¡rea central da Production",
    precoMedio: 13,
    destaque: "Snacks e bebidas rÃ¡pidas para a noite. Experimente o wrap de frango Caesar.",
    latitude: 28.4882,
    longitude: -81.4792,
  },
  {
    nome: "Cine Greens",
    regiao: "ProductionCentral",
    tipo: "Saudavel",
    acesso: "Ãrea prÃ³xima ao teatro 4D",
    precoMedio: 20,
    destaque: "Saladas e pratos leves. Experimente o bowl de quinoa com frango grelhado.",
    latitude: 28.4883,
    longitude: -81.4793,
  },
  {
    nome: "Director Comfort Kitchen",
    regiao: "ProductionCentral",
    tipo: "Conforto",
    acesso: "Ao lado do cafÃ© principal de Production Central",
    precoMedio: 29,
    destaque: "Pratos quentes como massas e ensopados. Experimente o ensopado de carne com batata.",
    latitude: 28.4884,
    longitude: -81.4794,
  },

  // SanFrancisco
  {
    nome: "Pier 39 Grill",
    regiao: "SanFrancisco",
    tipo: ["Classico", "Americano"],
    acesso: "Ãrea do Pier, ao lado da atraÃ§Ã£o Fast & Furious",
    precoMedio: 41,
    destaque: "Pratos com frutos do mar e grelhados. Experimente o salmÃ£o ao molho de limÃ£o.",
    latitude: 28.4890,
    longitude: -81.4800,
  },
  {
    nome: "Bay Area Diner",
    regiao: "SanFrancisco",
    tipo: "Tematico",
    acesso: "PrÃ³ximo Ã  doca principal de San Francisco",
    precoMedio: 38,
    destaque: "Ambiente inspirado na costa oeste americana. Experimente o peixe empanado com batatas fritas.",
    latitude: 28.4891,
    longitude: -81.4801,
  },
  {
    nome: "SF Quick Bites",
    regiao: "SanFrancisco",
    tipo: "Economico",
    acesso: "Ao lado da entrada da Ã¡rea de San Francisco",
    precoMedio: 14,
    destaque: "Lanches rÃ¡pidos com sabor da costa. Experimente o wrap de camarÃ£o.",
    latitude: 28.4892,
    longitude: -81.4802,
  },
  {
    nome: "Golden Gate Greens",
    regiao: "SanFrancisco",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo Ã  Ã¡rea de visualizaÃ§Ã£o do lago",
    precoMedio: 22,
    destaque: "Saladas e pratos leves com frutos do mar. Experimente a salada de rÃºcula com salmÃ£o defumado.",
    latitude: 28.4893,
    longitude: -81.4803,
  },
  {
    nome: "Fishermanâ€™s Comfort House",
    regiao: "SanFrancisco",
    tipo: "Conforto",
    acesso: "Perto da Ã¡rea temÃ¡tica de barcos",
    precoMedio: 27,
    destaque: "Pratos confortÃ¡veis com sabor de mar. Experimente o ensopado de frutos do mar.",
    latitude: 28.4894,
    longitude: -81.4804,
  },
  // SeussLanding
  {
    nome: "Who-ville Grill",
    regiao: "SeussLanding",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atraÃ§Ã£o The Cat in the Hat",
    precoMedio: 35,
    destaque: "Pratos clÃ¡ssicos com toques divertidos do Dr. Seuss. Experimente o hambÃºrguer com molho de cheddar.",
    latitude: 28.4900,
    longitude: -81.4810,
  },
  {
    nome: "Grinchâ€™s Feast",
    regiao: "SeussLanding",
    tipo: "Tematico",
    acesso: "PrÃ³ximo Ã  Ã¡rea de fotos com o Grinch",
    precoMedio: 32,
    destaque: "Ambiente temÃ¡tico com pratos inspirados nas histÃ³rias. Experimente o frango grelhado com legumes coloridos.",
    latitude: 28.4901,
    longitude: -81.4811,
  },
  {
    nome: "Seuss Snacks",
    regiao: "SeussLanding",
    tipo: "Economico",
    acesso: "Quiosque central da Ã¡rea Seuss",
    precoMedio: 12,
    destaque: "Snacks rÃ¡pidos com estilo infantil. Experimente o wrap de queijo com presunto.",
    latitude: 28.4902,
    longitude: -81.4812,
  },
  {
    nome: "Green Eggs & Salad",
    regiao: "SeussLanding",
    tipo: "Saudavel",
    acesso: "Perto da saÃ­da da atraÃ§Ã£o One Fish Two Fish",
    precoMedio: 21,
    destaque: "OpÃ§Ãµes leves e criativas para crianÃ§as e adultos. Experimente a salada de frango com abacaxi.",
    latitude: 28.4903,
    longitude: -81.4813,
  },
  {
    nome: "Whoville Comfort CafÃ©",
    regiao: "SeussLanding",
    tipo: "Conforto",
    acesso: "Entre os quiosques de doces e o carrossel do Seuss",
    precoMedio: 24,
    destaque: "Pratos caseiros com toques criativos. Experimente o mac and cheese com ervas.",
    latitude: 28.4904,
    longitude: -81.4814,
  },

  // SuperNintendoWorld
  {
    nome: "Marioâ€™s Grill",
    regiao: "SuperNintendoWorld",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  entrada do Mario Kart: Bowserâ€™s Challenge",
    precoMedio: 39,
    destaque: "Pratos inspirados no universo Mario. Experimente o hambÃºrguer de cogumelo gigante.",
    latitude: 28.4910,
    longitude: -81.4820,
  },
  {
    nome: "Luigiâ€™s Pasta House",
    regiao: "SuperNintendoWorld",
    tipo: "Tematico",
    acesso: "Ao lado da loja oficial do Mario",
    precoMedio: 34,
    destaque: "Massas italianas e pratos especiais. Experimente o espaguete com molho de cogumelos.",
    latitude: 28.4911,
    longitude: -81.4821,
  },
  {
    nome: "Toadâ€™s Quick Bites",
    regiao: "SuperNintendoWorld",
    tipo: "Economico",
    acesso: "Quiosque prÃ³ximo ao Toadâ€™s CafÃ©",
    precoMedio: 13,
    destaque: "Lanches rÃ¡pidos inspirados no Toad. Experimente o sanduÃ­che de queijo com tomate.",
    latitude: 28.4912,
    longitude: -81.4822,
  },
  {
    nome: "Princess Peach Salad Bar",
    regiao: "SuperNintendoWorld",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo ao castelo da Peach",
    precoMedio: 22,
    destaque: "Saladas frescas e pratos leves. Experimente a salada de morango com nozes.",
    latitude: 28.4913,
    longitude: -81.4823,
  },
  {
    nome: "Bowserâ€™s Comfort Feast",
    regiao: "SuperNintendoWorld",
    tipo: "Conforto",
    acesso: "Dentro do Bowserâ€™s Castle",
    precoMedio: 26,
    destaque: "Pratos reconfortantes para toda a famÃ­lia. Experimente o strogonoff de carne.",
    latitude: 28.4914,
    longitude: -81.4824,
  },

  // TheWitcher
  {
    nome: "Kaer Morhen Grill",
    regiao: "TheWitcher",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  entrada do castelo de Kaer Morhen",
    precoMedio: 42,
    destaque: "Pratos robustos com inspiraÃ§Ã£o medieval. Experimente o cordeiro assado com ervas.",
    latitude: 28.4920,
    longitude: -81.4830,
  },
  {
    nome: "Geraltâ€™s Tavern",
    regiao: "TheWitcher",
    tipo: "Tematico",
    acesso: "Ao lado da atraÃ§Ã£o principal de The Witcher",
    precoMedio: 38,
    destaque: "Ambiente de taverna com pratos rÃºsticos. Experimente a carne de javali com purÃª de batatas.",
    latitude: 28.4921,
    longitude: -81.4831,
  },
  {
    nome: "Witcher Bites",
    regiao: "TheWitcher",
    tipo: "Economico",
    acesso: "Quiosque medieval prÃ³ximo Ã  saÃ­da da Ã¡rea",
    precoMedio: 14,
    destaque: "Petiscos simples com sabores fortes. Experimente o pÃ£o rÃºstico com queijo e alho.",
    latitude: 28.4922,
    longitude: -81.4832,
  },
  {
    nome: "Triss Herbal Greens",
    regiao: "TheWitcher",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo ao mercado medieval",
    precoMedio: 23,
    destaque: "Saladas e sopas leves com ingredientes naturais. Experimente a sopa de legumes com ervas.",
    latitude: 28.4923,
    longitude: -81.4833,
  },
  {
    nome: "Yenneferâ€™s Comfort Hall",
    regiao: "TheWitcher",
    tipo: "Conforto",
    acesso: "Dentro do salÃ£o principal de banquetes",
    precoMedio: 30,
    destaque: "Pratos aconchegantes e sobremesas rÃºsticas. Experimente o ensopado de carne com legumes assados.",
    latitude: 28.4924,
    longitude: -81.4834,
  },

  // TheWizardingWorld
  {
    nome: "Three Broomsticks Evening",
    regiao: "TheWizardingWorld",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da entrada da Ã¡rea Hogsmeade",
    precoMedio: 45,
    destaque: "Jantares clÃ¡ssicos com toque britÃ¢nico. Experimente o peixe com batatas fritas.",
    latitude: 28.4930,
    longitude: -81.4840,
  },
  {
    nome: "Leaky Cauldron",
    regiao: "TheWizardingWorld",
    tipo: "Tematico",
    acesso: "Na Ã¡rea principal do Beco Diagonal",
    precoMedio: 48,
    destaque: "Pratos tÃ­picos britÃ¢nicos em ambiente mÃ¡gico. Experimente o bangers and mash.",
    latitude: 28.4931,
    longitude: -81.4841,
  },
  {
    nome: "Wizard Snacks",
    regiao: "TheWizardingWorld",
    tipo: "Economico",
    acesso: "Quiosque do Beco Diagonal",
    precoMedio: 15,
    destaque: "Snacks como empadas e pÃ£es mÃ¡gicos. Experimente a empada de abÃ³bora.",
    latitude: 28.4932,
    longitude: -81.4842,
  },
  {
    nome: "Herbology Greens",
    regiao: "TheWizardingWorld",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo Ã  Ã¡rea de Herbologia",
    precoMedio: 22,
    destaque: "Saladas mÃ¡gicas com ervas frescas. Experimente a salada com molho de abÃ³bora.",
    latitude: 28.4933,
    longitude: -81.4843,
  },
  {
    nome: "Hogwarts Comfort Hall",
    regiao: "TheWizardingWorld",
    tipo: "Conforto",
    acesso: "Dentro do castelo de Hogwarts",
    precoMedio: 33,
    destaque: "Pratos aconchegantes e sobremesas. Experimente o ensopado de carne com pÃ£o quente.",
    latitude: 28.4934,
    longitude: -81.4844,
  },

  // TheWizardingWorldHogsmeade
  {
    nome: "Three Broomsticks Dinner",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: ["Classico", "Americano"],
    acesso: "No coraÃ§Ã£o de Hogsmeade, ao lado da estaÃ§Ã£o de trem",
    precoMedio: 46,
    destaque: "Jantares britÃ¢nicos como peixe com batatas e ensopados. Experimente o clÃ¡ssico fish & chips.",
    latitude: 28.4940,
    longitude: -81.4850,
  },
  {
    nome: "Hogsmeade Cauldron",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Tematico",
    acesso: "PrÃ³ximo Ã  entrada da Zonkoâ€™s Joke Shop",
    precoMedio: 41,
    destaque: "Ambiente temÃ¡tico com pratos de caldeirÃµes. Experimente o guisado de carne com legumes.",
    latitude: 28.4941,
    longitude: -81.4851,
  },
  {
    nome: "Butterbeer Bites",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Economico",
    acesso: "Quiosque ao lado do Owl Post",
    precoMedio: 14,
    destaque: "Snacks e bebidas de Butterbeer para a noite. Experimente o cookie de Butterbeer.",
    latitude: 28.4942,
    longitude: -81.4852,
  },
  {
    nome: "Hogsmeade Greens",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Saudavel",
    acesso: "Perto da Honeydukes",
    precoMedio: 23,
    destaque: "Saladas e bowls frescos para uma refeiÃ§Ã£o leve. Experimente a salada de frango com maÃ§Ã£ verde.",
    latitude: 28.4943,
    longitude: -81.4853,
  },
  {
    nome: "Great Hall Comfort",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Conforto",
    acesso: "Ao lado da entrada do Castelo de Hogwarts",
    precoMedio: 32,
    destaque: "RefeiÃ§Ãµes aconchegantes com pratos quentes e sobremesas. Experimente o ensopado de cordeiro.",
    latitude: 28.4944,
    longitude: -81.4854,
  },

  // ToonLagoon
  {
    nome: "Toon Lagoon Grill",
    regiao: "ToonLagoon",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  atraÃ§Ã£o Dudley Do-Rightâ€™s Ripsaw Falls",
    precoMedio: 36,
    destaque: "Pratos clÃ¡ssicos com hambÃºrgueres e grelhados. Experimente o cheeseburger com batatas rÃºsticas.",
    latitude: 28.4950,
    longitude: -81.4860,
  },
  {
    nome: "Popeyeâ€™s Tavern",
    regiao: "ToonLagoon",
    tipo: "Tematico",
    acesso: "Ao lado da atraÃ§Ã£o Popeye & Blutoâ€™s Bilge-Rat Barges",
    precoMedio: 29,
    destaque: "Ambiente inspirado em Popeye com pratos temÃ¡ticos. Experimente o frango assado com espinafre.",
    latitude: 28.4951,
    longitude: -81.4861,
  },
  {
    nome: "Lagoon Snacks",
    regiao: "ToonLagoon",
    tipo: "Economico",
    acesso: "Quiosque central da Ã¡rea Toon Lagoon",
    precoMedio: 12,
    destaque: "Snacks leves e rÃ¡pidos. Experimente o wrap de peru com queijo.",
    latitude: 28.4952,
    longitude: -81.4862,
  },
  {
    nome: "Toon Greens",
    regiao: "ToonLagoon",
    tipo: "Saudavel",
    acesso: "Entre a saÃ­da da Ripsaw Falls e os quiosques de souvenirs",
    precoMedio: 22,
    destaque: "Saladas e pratos leves com sucos naturais. Experimente a salada Caesar com frango grelhado.",
    latitude: 28.4953,
    longitude: -81.4863,
  },
  {
    nome: "Blutoâ€™s Comfort CafÃ©",
    regiao: "ToonLagoon",
    tipo: "Conforto",
    acesso: "Ao lado do Popeyeâ€™s Tavern",
    precoMedio: 26,
    destaque: "Pratos caseiros para refeiÃ§Ãµes rÃ¡pidas. Experimente o mac and cheese com presunto.",
    latitude: 28.4954,
    longitude: -81.4864,
  },

  // UniversalMonsters
  {
    nome: "Monsters Grill",
    regiao: "UniversalMonsters",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  atraÃ§Ã£o Universal Monsters Tribute",
    precoMedio: 40,
    destaque: "Carnes e hambÃºrgueres com tema de terror clÃ¡ssico. Experimente o hambÃºrguer do DrÃ¡cula.",
    latitude: 28.4960,
    longitude: -81.4870,
  },
  {
    nome: "Frankenstein Feast",
    regiao: "UniversalMonsters",
    tipo: "Tematico",
    acesso: "Ao lado do castelo de Frankenstein",
    precoMedio: 38,
    destaque: "Ambiente sombrio com pratos temÃ¡ticos. Experimente o ensopado de carne com batata.",
    latitude: 28.4961,
    longitude: -81.4871,
  },
  {
    nome: "Monster Snacks",
    regiao: "UniversalMonsters",
    tipo: "Economico",
    acesso: "Quiosque central da Ã¡rea dos monstros",
    precoMedio: 13,
    destaque: "Petiscos temÃ¡ticos para lanches rÃ¡pidos. Experimente o wrap de frango picante.",
    latitude: 28.4962,
    longitude: -81.4872,
  },
  {
    nome: "Brideâ€™s Greens",
    regiao: "UniversalMonsters",
    tipo: "Saudavel",
    acesso: "PrÃ³ximo Ã  saÃ­da da atraÃ§Ã£o dos monstros",
    precoMedio: 22,
    destaque: "Saladas com ingredientes frescos e criativos. Experimente a salada de quinoa com tomate seco.",
    latitude: 28.4963,
    longitude: -81.4873,
  },
  {
    nome: "Wolfman Comfort Tavern",
    regiao: "UniversalMonsters",
    tipo: "Conforto",
    acesso: "Ao lado da Frankenstein Feast",
    precoMedio: 28,
    destaque: "Pratos reconfortantes para jantares temÃ¡ticos. Experimente o guisado de carne com legumes.",
    latitude: 28.4964,
    longitude: -81.4874,
  },

  // WorldExpo
  {
    nome: "Expo Grill",
    regiao: "WorldExpo",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃ³ximo Ã  atraÃ§Ã£o Men in Black: Alien Attack",
    precoMedio: 37,
    destaque: "Pratos americanos clÃ¡ssicos com carnes grelhadas. Experimente o hambÃºrguer com queijo cheddar.",
    latitude: 28.4970,
    longitude: -81.4880,
  },
  {
    nome: "Alien Feast",
    regiao: "WorldExpo",
    tipo: "Tematico",
    acesso: "Ao lado da entrada do simulador Alien Encounter",
    precoMedio: 33,
    destaque: "Ambiente sci-fi com pratos diferenciados. Experimente o frango marinado com molho agridoce.",
    latitude: 28.4971,
    longitude: -81.4881,
  },
  {
    nome: "Expo Snacks",
    regiao: "WorldExpo",
    tipo: "Economico",
    acesso: "Quiosque central do World Expo",
    precoMedio: 12,
    destaque: "Lanches rÃ¡pidos e bebidas refrescantes. Experimente o wrap de atum com alface.",
    latitude: 28.4972,
    longitude: -81.4882,
  },
  {
    nome: "Intergalactic Greens",
    regiao: "WorldExpo",
    tipo: "Saudavel",
    acesso: "Perto da Ã¡rea de descanso principal",
    precoMedio: 21,
    destaque: "Saladas leves e wraps frescos para o fim do dia. Experimente a salada Caesar com frango grelhado.",
    latitude: 28.4973,
    longitude: -81.4883,
  },
  {
    nome: "Men in Black Comfort CafÃ©",
    regiao: "WorldExpo",
    tipo: "Conforto",
    acesso: "Ao lado da atraÃ§Ã£o principal",
    precoMedio: 25,
    destaque: "Comidas caseiras com toque sci-fi. Experimente o frango com molho de mostarda e mel.",
    latitude: 28.4974,
    longitude: -81.4884,
  },
];



