ï»¿export const jantaresUniversal = [
  // FogosEpicoUniverse
  {
    nome: "Epic Lagoon Grill",
    regiao: "FogosEpicoUniverse",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃƒÂ³ximo ao lago central do Epic Universe, com visÃƒÂ£o privilegiada para o show noturno",
    precoMedio: 48,
    destaque: "Pratos grelhados e frutos do mar com vista para os fogos. Experimente o filÃƒÂ© com molho de vinho tinto.",
    latitude: 28.4701,
    longitude: -81.4601,
  },
  {
    nome: "Twilight Terrace",
    regiao: "FogosEpicoUniverse",
    tipo: "Tematico",
    acesso: "Deck principal para assistir ao espetÃƒÂ¡culo de fogos",
    precoMedio: 42,
    destaque: "CardÃƒÂ¡pio temÃƒÂ¡tico com iluminaÃƒÂ§ÃƒÂ£o especial. Experimente o salmÃƒÂ£o ao molho de maracujÃƒÂ¡.",
    latitude: 28.4702,
    longitude: -81.4602,
  },
  {
    nome: "Lagoon Snacks",
    regiao: "FogosEpicoUniverse",
    tipo: "Economico",
    acesso: "Quiosque lateral do viewing area",
    precoMedio: 15,
    destaque: "Snacks rÃƒÂ¡pidos para o show. Experimente o wrap de frango grelhado.",
    latitude: 28.4703,
    longitude: -81.4603,
  },
  {
    nome: "Fireworks Greens",
    regiao: "FogosEpicoUniverse",
    tipo: "Saudavel",
    acesso: "ÃƒÂrea de refeiÃƒÂ§ÃƒÂµes leves prÃƒÂ³xima ao lago",
    precoMedio: 23,
    destaque: "Saladas e bowls ideais para um jantar leve. Experimente a salada de quinoa com frutas.",
    latitude: 28.4704,
    longitude: -81.4604,
  },
  {
    nome: "Epic Comfort Bites",
    regiao: "FogosEpicoUniverse",
    tipo: "Conforto",
    acesso: "Ao lado do deck panorÃƒÂ¢mico",
    precoMedio: 30,
    destaque: "Pratos reconfortantes para apreciar durante o show. Experimente a costelinha barbecue com purÃƒÂª.",
    latitude: 28.4705,
    longitude: -81.4605,
  },

  // FogosIslandsOfAdventure
  {
    nome: "Islands Lagoon Dining",
    regiao: "FogosIslandsOfAdventure",
    tipo: ["Classico", "Americano"],
    acesso: "Frente ao lago com vista para o show noturno",
    precoMedio: 45,
    destaque: "Pratos tradicionais americanos e carnes grelhadas. Experimente o hambÃƒÂºrguer gourmet com fritas rÃƒÂºsticas.",
    latitude: 28.4721,
    longitude: -81.4621,
  },
  {
    nome: "Adventure Lights CafÃƒÂ©",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Tematico",
    acesso: "ÃƒÂrea iluminada prÃƒÂ³xima ao viewing spot",
    precoMedio: 37,
    destaque: "Ambiente temÃƒÂ¡tico com decoraÃƒÂ§ÃƒÂ£o de aventura. Experimente o frango grelhado com arroz selvagem.",
    latitude: 28.4722,
    longitude: -81.4622,
  },
  {
    nome: "Lagoon Snack Bar",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Economico",
    acesso: "Quiosque lateral prÃƒÂ³ximo ao show",
    precoMedio: 14,
    destaque: "Snacks, wraps e bebidas rÃƒÂ¡pidas. Experimente o wrap de peru com molho de mostarda.",
    latitude: 28.4723,
    longitude: -81.4623,
  },
  {
    nome: "Adventure Greens",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Saudavel",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  ÃƒÂ¡rea central do lago",
    precoMedio: 20,
    destaque: "Saladas frescas e bowls vegetarianos. Experimente a salada com avocado e mix de grÃƒÂ£os.",
    latitude: 28.4724,
    longitude: -81.4624,
  },
  {
    nome: "Island Comfort Grill",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Conforto",
    acesso: "ÃƒÂrea principal de alimentaÃƒÂ§ÃƒÂ£o",
    precoMedio: 29,
    destaque: "Comidas confortÃƒÂ¡veis, massas e grelhados. Experimente o mac and cheese trufado.",
    latitude: 28.4725,
    longitude: -81.4625,
  },

  // FogosUniversalStudios
  {
    nome: "Universal Lagoon Grill",
    regiao: "FogosUniversalStudios",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃƒÂ³ximo ao lago central do Universal Studios, com vista para o show noturno",
    precoMedio: 44,
    destaque: "Carnes grelhadas e frutos do mar em ambiente sofisticado. Experimente o filÃƒÂ© mignon com purÃƒÂª trufado.",
    latitude: 28.4800,
    longitude: -81.4710,
  },
  {
    nome: "Night Spark CafÃƒÂ©",
    regiao: "FogosUniversalStudios",
    tipo: "Tematico",
    acesso: "Ao lado da entrada para o viewing area do show de fogos",
    precoMedio: 39,
    destaque: "Ambiente imersivo com iluminaÃƒÂ§ÃƒÂ£o especial para a noite. NÃƒÂ£o deixe de experimentar o camarÃƒÂ£o ao alho e ÃƒÂ³leo.",
    latitude: 28.4801,
    longitude: -81.4711,
  },
  {
    nome: "Studio Snacks",
    regiao: "FogosUniversalStudios",
    tipo: "Economico",
    acesso: "Quiosque prÃƒÂ³ximo ao viewing area principal",
    precoMedio: 14,
    destaque: "Snacks e petiscos rÃƒÂ¡pidos para curtir os fogos. Experimente o wrap de frango grelhado.",
    latitude: 28.4802,
    longitude: -81.4712,
  },
  {
    nome: "Lagoon Greens",
    regiao: "FogosUniversalStudios",
    tipo: "Saudavel",
    acesso: "ÃƒÂrea externa perto do show principal",
    precoMedio: 23,
    destaque: "Saladas frescas e pratos leves para a noite. Experimente a salada com quinoa e abacate.",
    latitude: 28.4803,
    longitude: -81.4713,
  },
  {
    nome: "Lagoon Premium Dining",
    regiao: "FogosUniversalStudios",
    tipo: "Conforto",
    acesso: "ÃƒÂrea VIP de refeiÃƒÂ§ÃƒÂµes prÃƒÂ³xima ao lago principal",
    precoMedio: 50,
    destaque: "Menu premium com vista exclusiva para o show. Experimente o salmÃƒÂ£o grelhado com molho de maracujÃƒÂ¡.",
    latitude: 28.4804,
    longitude: -81.4714,
  },

  // Hollywood
  {
    nome: "Hollywood Grill",
    regiao: "Hollywood",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃƒÂ³ximo ao Hollywood Boulevard",
    precoMedio: 41,
    destaque: "Pratos clÃƒÂ¡ssicos com ambiente inspirado na Era de Ouro de Hollywood. Experimente o hambÃƒÂºrguer com bacon defumado.",
    latitude: 28.4810,
    longitude: -81.4720,
  },
  {
    nome: "CineStar Diner",
    regiao: "Hollywood",
    tipo: "Tematico",
    acesso: "Ao lado do Cinema 4D",
    precoMedio: 34,
    destaque: "DecoraÃƒÂ§ÃƒÂ£o de cinema com pratos temÃƒÂ¡ticos. Experimente o mac and cheese trufado.",
    latitude: 28.4811,
    longitude: -81.4721,
  },
  {
    nome: "Hollywood Snacks",
    regiao: "Hollywood",
    tipo: "Economico",
    acesso: "Perto da entrada do Hollywood Boulevard",
    precoMedio: 12,
    destaque: "Snacks rÃƒÂ¡pidos e acessÃƒÂ­veis para o jantar. Experimente o cachorro-quente com molho especial.",
    latitude: 28.4812,
    longitude: -81.4722,
  },
  {
    nome: "Star Greens",
    regiao: "Hollywood",
    tipo: "Saudavel",
    acesso: "Ao lado do Universal Theater",
    precoMedio: 22,
    destaque: "Saladas e wraps para refeiÃƒÂ§ÃƒÂµes leves. Experimente o wrap de frango Caesar.",
    latitude: 28.4813,
    longitude: -81.4723,
  },
  {
    nome: "Boulevard Bistro",
    regiao: "Hollywood",
    tipo: "Conforto",
    acesso: "No final do Hollywood Boulevard, prÃƒÂ³ximo ÃƒÂ s lojas temÃƒÂ¡ticas",
    precoMedio: 27,
    destaque: "CulinÃƒÂ¡ria americana com pratos reconfortantes. Experimente a costela barbecue com batatas rÃƒÂºsticas.",
    latitude: 28.4814,
    longitude: -81.4724,
  },
  // HowToTrainYourDragon
  {
    nome: "Berk Viking Grill",
    regiao: "HowToTrainYourDragon",
    tipo: ["Classico", "Americano"],
    acesso: "No centro da vila de Berk, perto da atraÃƒÂ§ÃƒÂ£o principal",
    precoMedio: 38,
    destaque: "Carnes grelhadas no estilo viking com acompanhamentos robustos. Experimente o prato de costela com batata assada.",
    latitude: 28.4820,
    longitude: -81.4730,
  },
  {
    nome: "Dragons Feast Hall",
    regiao: "HowToTrainYourDragon",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ao show dos dragÃƒÂµes, com decoraÃƒÂ§ÃƒÂ£o nÃƒÂ³rdica",
    precoMedio: 42,
    destaque: "RefeiÃƒÂ§ÃƒÂµes inspiradas em festins vikings com pratos de caÃƒÂ§a e peixe. Experimente o salmÃƒÂ£o com molho de ervas.",
    latitude: 28.4821,
    longitude: -81.4731,
  },
  {
    nome: "Hiccup's Quick Bites",
    regiao: "HowToTrainYourDragon",
    tipo: "Economico",
    acesso: "Ao lado da ÃƒÂ¡rea de jogos do SoluÃƒÂ§o",
    precoMedio: 14,
    destaque: "Lanches rÃƒÂ¡pidos para quem estÃƒÂ¡ com pressa. Experimente o sanduÃƒÂ­che de frango com queijo.",
    latitude: 28.4822,
    longitude: -81.4732,
  },
  {
    nome: "AstridÃ¢â‚¬â„¢s Greens",
    regiao: "HowToTrainYourDragon",
    tipo: "Saudavel",
    acesso: "Perto da ÃƒÂ¡rea de treinamento de dragÃƒÂµes",
    precoMedio: 21,
    destaque: "Bowls leves e wraps saudÃƒÂ¡veis com ingredientes frescos. Experimente a salada com grÃƒÂ£os e molho de iogurte.",
    latitude: 28.4823,
    longitude: -81.4733,
  },
  {
    nome: "Dragon Comfort Diner",
    regiao: "HowToTrainYourDragon",
    tipo: "Conforto",
    acesso: "Ao lado da loja de souvenirs de Berk",
    precoMedio: 27,
    destaque: "Pratos confortÃƒÂ¡veis para encerrar o dia. Experimente o ensopado de carne com legumes.",
    latitude: 28.4824,
    longitude: -81.4734,
  },

  // JurassicPark
  {
    nome: "Jurassic Grill",
    regiao: "JurassicPark",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da entrada do Jurassic River Adventure",
    precoMedio: 40,
    destaque: "Carnes e hambÃƒÂºrgueres com tema jurÃƒÂ¡ssico. Experimente o T-Rex Burger com bacon e cheddar.",
    latitude: 28.4830,
    longitude: -81.4740,
  },
  {
    nome: "RaptorÃ¢â‚¬â„¢s Feast",
    regiao: "JurassicPark",
    tipo: "Tematico",
    acesso: "Perto da ÃƒÂ¡rea de exibiÃƒÂ§ÃƒÂ£o dos velociraptors",
    precoMedio: 36,
    destaque: "Pratos temÃƒÂ¡ticos com carnes grelhadas e molhos especiais. Experimente o frango ao molho de manga picante.",
    latitude: 28.4831,
    longitude: -81.4741,
  },
  {
    nome: "Dino Snacks",
    regiao: "JurassicPark",
    tipo: "Economico",
    acesso: "Quiosque prÃƒÂ³ximo ao Jurassic Outfitters",
    precoMedio: 13,
    destaque: "Snacks rÃƒÂ¡pidos como wraps e nachos. Experimente o wrap de frango grelhado.",
    latitude: 28.4832,
    longitude: -81.4742,
  },
  {
    nome: "Jurassic Greens",
    regiao: "JurassicPark",
    tipo: "Saudavel",
    acesso: "ÃƒÂrea sombreada prÃƒÂ³xima ÃƒÂ  Discovery Center",
    precoMedio: 20,
    destaque: "Saladas frescas e bowls leves para os fÃƒÂ£s de saÃƒÂºde. Experimente o bowl de quinoa com salmÃƒÂ£o grelhado.",
    latitude: 28.4833,
    longitude: -81.4743,
  },
  {
    nome: "Herbivore Comfort Grill",
    regiao: "JurassicPark",
    tipo: "Conforto",
    acesso: "Em frente ao portÃƒÂ£o principal de Jurassic Park",
    precoMedio: 29,
    destaque: "Massas e carnes ao estilo caseiro. Experimente o mac and cheese com costela desfiada.",
    latitude: 28.4834,
    longitude: -81.4744,
  },

  // LostContinent
  {
    nome: "Mythos Restaurant",
    regiao: "LostContinent",
    tipo: ["Classico", "Americano"],
    acesso: "No centro do Lost Continent, prÃƒÂ³ximo ÃƒÂ  fonte principal",
    precoMedio: 44,
    destaque: "Restaurante premiado com culinÃƒÂ¡ria variada. Experimente o filÃƒÂ© de peixe ao molho cÃƒÂ­trico.",
    latitude: 28.4840,
    longitude: -81.4750,
  },
  {
    nome: "PoseidonÃ¢â‚¬â„¢s Table",
    regiao: "LostContinent",
    tipo: "Tematico",
    acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o PoseidonÃ¢â‚¬â„¢s Fury",
    precoMedio: 38,
    destaque: "Ambiente temÃƒÂ¡tico inspirado na mitologia grega. Experimente o polvo grelhado com azeite de ervas.",
    latitude: 28.4841,
    longitude: -81.4751,
  },
  {
    nome: "Oracle Snacks",
    regiao: "LostContinent",
    tipo: "Economico",
    acesso: "Em frente ÃƒÂ  entrada do The Eighth Voyage of Sindbad",
    precoMedio: 12,
    destaque: "Lanches rÃƒÂ¡pidos e petiscos leves. Experimente a pita com frango assado.",
    latitude: 28.4842,
    longitude: -81.4752,
  },
  {
    nome: "Olympus Greens",
    regiao: "LostContinent",
    tipo: "Saudavel",
    acesso: "PrÃƒÂ³ximo ao Mythos Restaurant",
    precoMedio: 22,
    destaque: "Pratos leves com saladas e wraps mediterrÃƒÂ¢neos. Experimente a salada grega com queijo feta.",
    latitude: 28.4843,
    longitude: -81.4753,
  },
  {
    nome: "Lost Comfort Kitchen",
    regiao: "LostContinent",
    tipo: "Conforto",
    acesso: "Perto da saÃƒÂ­da do Lost Continent",
    precoMedio: 28,
    destaque: "Pratos robustos como carne assada e massas. Experimente o penne com molho de tomate rÃƒÂºstico.",
    latitude: 28.4844,
    longitude: -81.4754,
  },

  // MarvelSuperHeroIsland
  {
    nome: "Avengers Grill",
    regiao: "MarvelSuperHeroIsland",
    tipo: ["Classico", "Americano"],
    acesso: "Em frente ÃƒÂ  atraÃƒÂ§ÃƒÂ£o The Incredible Hulk Coaster",
    precoMedio: 39,
    destaque: "Comida clÃƒÂ¡ssica americana com ambiente de super-herÃƒÂ³is. Experimente o hambÃƒÂºrguer do Hulk com queijo cheddar.",
    latitude: 28.4850,
    longitude: -81.4760,
  },
  {
    nome: "HeroÃ¢â‚¬â„¢s Diner",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Tematico",
    acesso: "Ao lado da Spider-Man Store",
    precoMedio: 35,
    destaque: "Pratos inspirados nos herÃƒÂ³is da Marvel. Experimente o frango grelhado com batata rÃƒÂºstica.",
    latitude: 28.4851,
    longitude: -81.4761,
  },
  {
    nome: "Marvel Quick Eats",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Economico",
    acesso: "Perto da entrada do CafÃƒÂ© 4",
    precoMedio: 13,
    destaque: "Snacks rÃƒÂ¡pidos como sanduÃƒÂ­ches e wraps. Experimente o wrap de presunto com queijo.",
    latitude: 28.4852,
    longitude: -81.4762,
  },
  {
    nome: "Superhero Greens",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Saudavel",
    acesso: "ÃƒÂrea lateral da Marvel Super Hero Island",
    precoMedio: 20,
    destaque: "Bowls e saladas energÃƒÂ©ticas. Experimente a salada com frango grelhado e quinoa.",
    latitude: 28.4853,
    longitude: -81.4763,
  },
  {
    nome: "Hero Comfort Bites",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Conforto",
    acesso: "Ao lado do CafÃƒÂ© 4",
    precoMedio: 27,
    destaque: "Massas e pratos quentes inspirados nos herÃƒÂ³is. Experimente o mac and cheese com frango crocante.",
    latitude: 28.4854,
    longitude: -81.4764,
  },

  // MinionsLand
  {
    nome: "MinionÃ¢â‚¬â„¢s Banana Grill",
    regiao: "MinionsLand",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada da Minion Mayhem",
    precoMedio: 36,
    destaque: "Pratos americanos com um toque divertido dos Minions. Experimente o cheeseburger com molho de banana especial.",
    latitude: 28.4860,
    longitude: -81.4770,
  },
  {
    nome: "GruÃ¢â‚¬â„¢s Lab Kitchen",
    regiao: "MinionsLand",
    tipo: "Tematico",
    acesso: "Dentro do laboratÃƒÂ³rio do Gru, ao lado da atraÃƒÂ§ÃƒÂ£o principal",
    precoMedio: 40,
    destaque: "Ambiente imersivo com pratos temÃƒÂ¡ticos. Experimente o frango grelhado com purÃƒÂª roxo.",
    latitude: 28.4861,
    longitude: -81.4771,
  },
  {
    nome: "Minion Bites",
    regiao: "MinionsLand",
    tipo: "Economico",
    acesso: "Quiosque ao lado da loja dos Minions",
    precoMedio: 12,
    destaque: "Lanches rÃƒÂ¡pidos para toda a famÃƒÂ­lia. Experimente o wrap de presunto com queijo cheddar.",
    latitude: 28.4862,
    longitude: -81.4772,
  },
  {
    nome: "Banana Greens",
    regiao: "MinionsLand",
    tipo: "Saudavel",
    acesso: "Perto da ÃƒÂ¡rea de fotos com os Minions",
    precoMedio: 21,
    destaque: "Saladas tropicais e bowls leves. Experimente a salada com abacaxi e frango grelhado.",
    latitude: 28.4863,
    longitude: -81.4773,
  },
  {
    nome: "Minion Comfort CafÃƒÂ©",
    regiao: "MinionsLand",
    tipo: "Conforto",
    acesso: "PrÃƒÂ³ximo ao Minion CafÃƒÂ© oficial",
    precoMedio: 25,
    destaque: "Pratos confortÃƒÂ¡veis e sobremesas temÃƒÂ¡ticas. Experimente o mac and cheese com crocante de banana.",
    latitude: 28.4864,
    longitude: -81.4774,
  },

  // NewYork
  {
    nome: "Big Apple Grill",
    regiao: "NewYork",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃƒÂ³ximo ÃƒÂ  atraÃƒÂ§ÃƒÂ£o The Mummy",
    precoMedio: 42,
    destaque: "Pratos tÃƒÂ­picos de Nova York, como steaks e burgers. Experimente o hambÃƒÂºrguer com bacon e cebolas caramelizadas.",
    latitude: 28.4870,
    longitude: -81.4780,
  },
  {
    nome: "Broadway Diner",
    regiao: "NewYork",
    tipo: "Tematico",
    acesso: "Ao lado da ÃƒÂ¡rea de shows do New York Street",
    precoMedio: 38,
    destaque: "Ambiente com decoraÃƒÂ§ÃƒÂ£o de teatro da Broadway. Experimente o frango ao molho de vinho.",
    latitude: 28.4871,
    longitude: -81.4781,
  },
  {
    nome: "NYC Quick Eats",
    regiao: "NewYork",
    tipo: "Economico",
    acesso: "Ao lado do cafÃƒÂ© da ÃƒÂ¡rea de Nova York",
    precoMedio: 14,
    destaque: "Lanches rÃƒÂ¡pidos em estilo deli. Experimente o sanduÃƒÂ­che de pastrami.",
    latitude: 28.4872,
    longitude: -81.4782,
  },
  {
    nome: "Empire Greens",
    regiao: "NewYork",
    tipo: "Saudavel",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada do Race Through New York",
    precoMedio: 22,
    destaque: "Saladas frescas e opÃƒÂ§ÃƒÂµes leves. Experimente a salada de rÃƒÂºcula com parmesÃƒÂ£o.",
    latitude: 28.4873,
    longitude: -81.4783,
  },
  {
    nome: "Liberty Comfort Food",
    regiao: "NewYork",
    tipo: "Conforto",
    acesso: "ÃƒÂrea central da rua principal de Nova York",
    precoMedio: 28,
    destaque: "Comida caseira inspirada na cultura nova-iorquina. Experimente o macarrÃƒÂ£o com queijo e bacon.",
    latitude: 28.4874,
    longitude: -81.4784,
  },

  // ProductionCentral
  {
    nome: "DirectorÃ¢â‚¬â„¢s Grill",
    regiao: "ProductionCentral",
    tipo: ["Classico", "Americano"],
    acesso: "No centro da Production Central",
    precoMedio: 40,
    destaque: "Pratos clÃƒÂ¡ssicos servidos em ambiente de estÃƒÂºdio. Experimente o filÃƒÂ© de frango grelhado com arroz.",
    latitude: 28.4880,
    longitude: -81.4790,
  },
  {
    nome: "Studio Diner",
    regiao: "ProductionCentral",
    tipo: "Tematico",
    acesso: "Perto do simulador Despicable Me",
    precoMedio: 37,
    destaque: "DecoraÃƒÂ§ÃƒÂ£o de estÃƒÂºdio de cinema com pratos temÃƒÂ¡ticos. Experimente o hambÃƒÂºrguer de costela com molho barbecue.",
    latitude: 28.4881,
    longitude: -81.4791,
  },
  {
    nome: "Production Snacks",
    regiao: "ProductionCentral",
    tipo: "Economico",
    acesso: "Quiosque na ÃƒÂ¡rea central da Production",
    precoMedio: 13,
    destaque: "Snacks e bebidas rÃƒÂ¡pidas para a noite. Experimente o wrap de frango Caesar.",
    latitude: 28.4882,
    longitude: -81.4792,
  },
  {
    nome: "Cine Greens",
    regiao: "ProductionCentral",
    tipo: "Saudavel",
    acesso: "ÃƒÂrea prÃƒÂ³xima ao teatro 4D",
    precoMedio: 20,
    destaque: "Saladas e pratos leves. Experimente o bowl de quinoa com frango grelhado.",
    latitude: 28.4883,
    longitude: -81.4793,
  },
  {
    nome: "Director Comfort Kitchen",
    regiao: "ProductionCentral",
    tipo: "Conforto",
    acesso: "Ao lado do cafÃƒÂ© principal de Production Central",
    precoMedio: 29,
    destaque: "Pratos quentes como massas e ensopados. Experimente o ensopado de carne com batata.",
    latitude: 28.4884,
    longitude: -81.4794,
  },

  // SanFrancisco
  {
    nome: "Pier 39 Grill",
    regiao: "SanFrancisco",
    tipo: ["Classico", "Americano"],
    acesso: "ÃƒÂrea do Pier, ao lado da atraÃƒÂ§ÃƒÂ£o Fast & Furious",
    precoMedio: 41,
    destaque: "Pratos com frutos do mar e grelhados. Experimente o salmÃƒÂ£o ao molho de limÃƒÂ£o.",
    latitude: 28.4890,
    longitude: -81.4800,
  },
  {
    nome: "Bay Area Diner",
    regiao: "SanFrancisco",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  doca principal de San Francisco",
    precoMedio: 38,
    destaque: "Ambiente inspirado na costa oeste americana. Experimente o peixe empanado com batatas fritas.",
    latitude: 28.4891,
    longitude: -81.4801,
  },
  {
    nome: "SF Quick Bites",
    regiao: "SanFrancisco",
    tipo: "Economico",
    acesso: "Ao lado da entrada da ÃƒÂ¡rea de San Francisco",
    precoMedio: 14,
    destaque: "Lanches rÃƒÂ¡pidos com sabor da costa. Experimente o wrap de camarÃƒÂ£o.",
    latitude: 28.4892,
    longitude: -81.4802,
  },
  {
    nome: "Golden Gate Greens",
    regiao: "SanFrancisco",
    tipo: "Saudavel",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  ÃƒÂ¡rea de visualizaÃƒÂ§ÃƒÂ£o do lago",
    precoMedio: 22,
    destaque: "Saladas e pratos leves com frutos do mar. Experimente a salada de rÃƒÂºcula com salmÃƒÂ£o defumado.",
    latitude: 28.4893,
    longitude: -81.4803,
  },
  {
    nome: "FishermanÃ¢â‚¬â„¢s Comfort House",
    regiao: "SanFrancisco",
    tipo: "Conforto",
    acesso: "Perto da ÃƒÂ¡rea temÃƒÂ¡tica de barcos",
    precoMedio: 27,
    destaque: "Pratos confortÃƒÂ¡veis com sabor de mar. Experimente o ensopado de frutos do mar.",
    latitude: 28.4894,
    longitude: -81.4804,
  },
  // SeussLanding
  {
    nome: "Who-ville Grill",
    regiao: "SeussLanding",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o The Cat in the Hat",
    precoMedio: 35,
    destaque: "Pratos clÃƒÂ¡ssicos com toques divertidos do Dr. Seuss. Experimente o hambÃƒÂºrguer com molho de cheddar.",
    latitude: 28.4900,
    longitude: -81.4810,
  },
  {
    nome: "GrinchÃ¢â‚¬â„¢s Feast",
    regiao: "SeussLanding",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  ÃƒÂ¡rea de fotos com o Grinch",
    precoMedio: 32,
    destaque: "Ambiente temÃƒÂ¡tico com pratos inspirados nas histÃƒÂ³rias. Experimente o frango grelhado com legumes coloridos.",
    latitude: 28.4901,
    longitude: -81.4811,
  },
  {
    nome: "Seuss Snacks",
    regiao: "SeussLanding",
    tipo: "Economico",
    acesso: "Quiosque central da ÃƒÂ¡rea Seuss",
    precoMedio: 12,
    destaque: "Snacks rÃƒÂ¡pidos com estilo infantil. Experimente o wrap de queijo com presunto.",
    latitude: 28.4902,
    longitude: -81.4812,
  },
  {
    nome: "Green Eggs & Salad",
    regiao: "SeussLanding",
    tipo: "Saudavel",
    acesso: "Perto da saÃƒÂ­da da atraÃƒÂ§ÃƒÂ£o One Fish Two Fish",
    precoMedio: 21,
    destaque: "OpÃƒÂ§ÃƒÂµes leves e criativas para crianÃƒÂ§as e adultos. Experimente a salada de frango com abacaxi.",
    latitude: 28.4903,
    longitude: -81.4813,
  },
  {
    nome: "Whoville Comfort CafÃƒÂ©",
    regiao: "SeussLanding",
    tipo: "Conforto",
    acesso: "Entre os quiosques de doces e o carrossel do Seuss",
    precoMedio: 24,
    destaque: "Pratos caseiros com toques criativos. Experimente o mac and cheese com ervas.",
    latitude: 28.4904,
    longitude: -81.4814,
  },

  // SuperNintendoWorld
  {
    nome: "MarioÃ¢â‚¬â„¢s Grill",
    regiao: "SuperNintendoWorld",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada do Mario Kart: BowserÃ¢â‚¬â„¢s Challenge",
    precoMedio: 39,
    destaque: "Pratos inspirados no universo Mario. Experimente o hambÃƒÂºrguer de cogumelo gigante.",
    latitude: 28.4910,
    longitude: -81.4820,
  },
  {
    nome: "LuigiÃ¢â‚¬â„¢s Pasta House",
    regiao: "SuperNintendoWorld",
    tipo: "Tematico",
    acesso: "Ao lado da loja oficial do Mario",
    precoMedio: 34,
    destaque: "Massas italianas e pratos especiais. Experimente o espaguete com molho de cogumelos.",
    latitude: 28.4911,
    longitude: -81.4821,
  },
  {
    nome: "ToadÃ¢â‚¬â„¢s Quick Bites",
    regiao: "SuperNintendoWorld",
    tipo: "Economico",
    acesso: "Quiosque prÃƒÂ³ximo ao ToadÃ¢â‚¬â„¢s CafÃƒÂ©",
    precoMedio: 13,
    destaque: "Lanches rÃƒÂ¡pidos inspirados no Toad. Experimente o sanduÃƒÂ­che de queijo com tomate.",
    latitude: 28.4912,
    longitude: -81.4822,
  },
  {
    nome: "Princess Peach Salad Bar",
    regiao: "SuperNintendoWorld",
    tipo: "Saudavel",
    acesso: "PrÃƒÂ³ximo ao castelo da Peach",
    precoMedio: 22,
    destaque: "Saladas frescas e pratos leves. Experimente a salada de morango com nozes.",
    latitude: 28.4913,
    longitude: -81.4823,
  },
  {
    nome: "BowserÃ¢â‚¬â„¢s Comfort Feast",
    regiao: "SuperNintendoWorld",
    tipo: "Conforto",
    acesso: "Dentro do BowserÃ¢â‚¬â„¢s Castle",
    precoMedio: 26,
    destaque: "Pratos reconfortantes para toda a famÃƒÂ­lia. Experimente o strogonoff de carne.",
    latitude: 28.4914,
    longitude: -81.4824,
  },

  // TheWitcher
  {
    nome: "Kaer Morhen Grill",
    regiao: "TheWitcher",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada do castelo de Kaer Morhen",
    precoMedio: 42,
    destaque: "Pratos robustos com inspiraÃƒÂ§ÃƒÂ£o medieval. Experimente o cordeiro assado com ervas.",
    latitude: 28.4920,
    longitude: -81.4830,
  },
  {
    nome: "GeraltÃ¢â‚¬â„¢s Tavern",
    regiao: "TheWitcher",
    tipo: "Tematico",
    acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o principal de The Witcher",
    precoMedio: 38,
    destaque: "Ambiente de taverna com pratos rÃƒÂºsticos. Experimente a carne de javali com purÃƒÂª de batatas.",
    latitude: 28.4921,
    longitude: -81.4831,
  },
  {
    nome: "Witcher Bites",
    regiao: "TheWitcher",
    tipo: "Economico",
    acesso: "Quiosque medieval prÃƒÂ³ximo ÃƒÂ  saÃƒÂ­da da ÃƒÂ¡rea",
    precoMedio: 14,
    destaque: "Petiscos simples com sabores fortes. Experimente o pÃƒÂ£o rÃƒÂºstico com queijo e alho.",
    latitude: 28.4922,
    longitude: -81.4832,
  },
  {
    nome: "Triss Herbal Greens",
    regiao: "TheWitcher",
    tipo: "Saudavel",
    acesso: "PrÃƒÂ³ximo ao mercado medieval",
    precoMedio: 23,
    destaque: "Saladas e sopas leves com ingredientes naturais. Experimente a sopa de legumes com ervas.",
    latitude: 28.4923,
    longitude: -81.4833,
  },
  {
    nome: "YenneferÃ¢â‚¬â„¢s Comfort Hall",
    regiao: "TheWitcher",
    tipo: "Conforto",
    acesso: "Dentro do salÃƒÂ£o principal de banquetes",
    precoMedio: 30,
    destaque: "Pratos aconchegantes e sobremesas rÃƒÂºsticas. Experimente o ensopado de carne com legumes assados.",
    latitude: 28.4924,
    longitude: -81.4834,
  },

  // TheWizardingWorld
  {
    nome: "Three Broomsticks Evening",
    regiao: "TheWizardingWorld",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da entrada da ÃƒÂ¡rea Hogsmeade",
    precoMedio: 45,
    destaque: "Jantares clÃƒÂ¡ssicos com toque britÃƒÂ¢nico. Experimente o peixe com batatas fritas.",
    latitude: 28.4930,
    longitude: -81.4840,
  },
  {
    nome: "Leaky Cauldron",
    regiao: "TheWizardingWorld",
    tipo: "Tematico",
    acesso: "Na ÃƒÂ¡rea principal do Beco Diagonal",
    precoMedio: 48,
    destaque: "Pratos tÃƒÂ­picos britÃƒÂ¢nicos em ambiente mÃƒÂ¡gico. Experimente o bangers and mash.",
    latitude: 28.4931,
    longitude: -81.4841,
  },
  {
    nome: "Wizard Snacks",
    regiao: "TheWizardingWorld",
    tipo: "Economico",
    acesso: "Quiosque do Beco Diagonal",
    precoMedio: 15,
    destaque: "Snacks como empadas e pÃƒÂ£es mÃƒÂ¡gicos. Experimente a empada de abÃƒÂ³bora.",
    latitude: 28.4932,
    longitude: -81.4842,
  },
  {
    nome: "Herbology Greens",
    regiao: "TheWizardingWorld",
    tipo: "Saudavel",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  ÃƒÂ¡rea de Herbologia",
    precoMedio: 22,
    destaque: "Saladas mÃƒÂ¡gicas com ervas frescas. Experimente a salada com molho de abÃƒÂ³bora.",
    latitude: 28.4933,
    longitude: -81.4843,
  },
  {
    nome: "Hogwarts Comfort Hall",
    regiao: "TheWizardingWorld",
    tipo: "Conforto",
    acesso: "Dentro do castelo de Hogwarts",
    precoMedio: 33,
    destaque: "Pratos aconchegantes e sobremesas. Experimente o ensopado de carne com pÃƒÂ£o quente.",
    latitude: 28.4934,
    longitude: -81.4844,
  },

  // TheWizardingWorldHogsmeade
  {
    nome: "Three Broomsticks Dinner",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: ["Classico", "Americano"],
    acesso: "No coraÃƒÂ§ÃƒÂ£o de Hogsmeade, ao lado da estaÃƒÂ§ÃƒÂ£o de trem",
    precoMedio: 46,
    destaque: "Jantares britÃƒÂ¢nicos como peixe com batatas e ensopados. Experimente o clÃƒÂ¡ssico fish & chips.",
    latitude: 28.4940,
    longitude: -81.4850,
  },
  {
    nome: "Hogsmeade Cauldron",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Tematico",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  entrada da ZonkoÃ¢â‚¬â„¢s Joke Shop",
    precoMedio: 41,
    destaque: "Ambiente temÃƒÂ¡tico com pratos de caldeirÃƒÂµes. Experimente o guisado de carne com legumes.",
    latitude: 28.4941,
    longitude: -81.4851,
  },
  {
    nome: "Butterbeer Bites",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Economico",
    acesso: "Quiosque ao lado do Owl Post",
    precoMedio: 14,
    destaque: "Snacks e bebidas de Butterbeer para a noite. Experimente o cookie de Butterbeer.",
    latitude: 28.4942,
    longitude: -81.4852,
  },
  {
    nome: "Hogsmeade Greens",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Saudavel",
    acesso: "Perto da Honeydukes",
    precoMedio: 23,
    destaque: "Saladas e bowls frescos para uma refeiÃƒÂ§ÃƒÂ£o leve. Experimente a salada de frango com maÃƒÂ§ÃƒÂ£ verde.",
    latitude: 28.4943,
    longitude: -81.4853,
  },
  {
    nome: "Great Hall Comfort",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Conforto",
    acesso: "Ao lado da entrada do Castelo de Hogwarts",
    precoMedio: 32,
    destaque: "RefeiÃƒÂ§ÃƒÂµes aconchegantes com pratos quentes e sobremesas. Experimente o ensopado de cordeiro.",
    latitude: 28.4944,
    longitude: -81.4854,
  },

  // ToonLagoon
  {
    nome: "Toon Lagoon Grill",
    regiao: "ToonLagoon",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃƒÂ³ximo ÃƒÂ  atraÃƒÂ§ÃƒÂ£o Dudley Do-RightÃ¢â‚¬â„¢s Ripsaw Falls",
    precoMedio: 36,
    destaque: "Pratos clÃƒÂ¡ssicos com hambÃƒÂºrgueres e grelhados. Experimente o cheeseburger com batatas rÃƒÂºsticas.",
    latitude: 28.4950,
    longitude: -81.4860,
  },
  {
    nome: "PopeyeÃ¢â‚¬â„¢s Tavern",
    regiao: "ToonLagoon",
    tipo: "Tematico",
    acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o Popeye & BlutoÃ¢â‚¬â„¢s Bilge-Rat Barges",
    precoMedio: 29,
    destaque: "Ambiente inspirado em Popeye com pratos temÃƒÂ¡ticos. Experimente o frango assado com espinafre.",
    latitude: 28.4951,
    longitude: -81.4861,
  },
  {
    nome: "Lagoon Snacks",
    regiao: "ToonLagoon",
    tipo: "Economico",
    acesso: "Quiosque central da ÃƒÂ¡rea Toon Lagoon",
    precoMedio: 12,
    destaque: "Snacks leves e rÃƒÂ¡pidos. Experimente o wrap de peru com queijo.",
    latitude: 28.4952,
    longitude: -81.4862,
  },
  {
    nome: "Toon Greens",
    regiao: "ToonLagoon",
    tipo: "Saudavel",
    acesso: "Entre a saÃƒÂ­da da Ripsaw Falls e os quiosques de souvenirs",
    precoMedio: 22,
    destaque: "Saladas e pratos leves com sucos naturais. Experimente a salada Caesar com frango grelhado.",
    latitude: 28.4953,
    longitude: -81.4863,
  },
  {
    nome: "BlutoÃ¢â‚¬â„¢s Comfort CafÃƒÂ©",
    regiao: "ToonLagoon",
    tipo: "Conforto",
    acesso: "Ao lado do PopeyeÃ¢â‚¬â„¢s Tavern",
    precoMedio: 26,
    destaque: "Pratos caseiros para refeiÃƒÂ§ÃƒÂµes rÃƒÂ¡pidas. Experimente o mac and cheese com presunto.",
    latitude: 28.4954,
    longitude: -81.4864,
  },

  // UniversalMonsters
  {
    nome: "Monsters Grill",
    regiao: "UniversalMonsters",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃƒÂ³ximo ÃƒÂ  atraÃƒÂ§ÃƒÂ£o Universal Monsters Tribute",
    precoMedio: 40,
    destaque: "Carnes e hambÃƒÂºrgueres com tema de terror clÃƒÂ¡ssico. Experimente o hambÃƒÂºrguer do DrÃƒÂ¡cula.",
    latitude: 28.4960,
    longitude: -81.4870,
  },
  {
    nome: "Frankenstein Feast",
    regiao: "UniversalMonsters",
    tipo: "Tematico",
    acesso: "Ao lado do castelo de Frankenstein",
    precoMedio: 38,
    destaque: "Ambiente sombrio com pratos temÃƒÂ¡ticos. Experimente o ensopado de carne com batata.",
    latitude: 28.4961,
    longitude: -81.4871,
  },
  {
    nome: "Monster Snacks",
    regiao: "UniversalMonsters",
    tipo: "Economico",
    acesso: "Quiosque central da ÃƒÂ¡rea dos monstros",
    precoMedio: 13,
    destaque: "Petiscos temÃƒÂ¡ticos para lanches rÃƒÂ¡pidos. Experimente o wrap de frango picante.",
    latitude: 28.4962,
    longitude: -81.4872,
  },
  {
    nome: "BrideÃ¢â‚¬â„¢s Greens",
    regiao: "UniversalMonsters",
    tipo: "Saudavel",
    acesso: "PrÃƒÂ³ximo ÃƒÂ  saÃƒÂ­da da atraÃƒÂ§ÃƒÂ£o dos monstros",
    precoMedio: 22,
    destaque: "Saladas com ingredientes frescos e criativos. Experimente a salada de quinoa com tomate seco.",
    latitude: 28.4963,
    longitude: -81.4873,
  },
  {
    nome: "Wolfman Comfort Tavern",
    regiao: "UniversalMonsters",
    tipo: "Conforto",
    acesso: "Ao lado da Frankenstein Feast",
    precoMedio: 28,
    destaque: "Pratos reconfortantes para jantares temÃƒÂ¡ticos. Experimente o guisado de carne com legumes.",
    latitude: 28.4964,
    longitude: -81.4874,
  },

  // WorldExpo
  {
    nome: "Expo Grill",
    regiao: "WorldExpo",
    tipo: ["Classico", "Americano"],
    acesso: "PrÃƒÂ³ximo ÃƒÂ  atraÃƒÂ§ÃƒÂ£o Men in Black: Alien Attack",
    precoMedio: 37,
    destaque: "Pratos americanos clÃƒÂ¡ssicos com carnes grelhadas. Experimente o hambÃƒÂºrguer com queijo cheddar.",
    latitude: 28.4970,
    longitude: -81.4880,
  },
  {
    nome: "Alien Feast",
    regiao: "WorldExpo",
    tipo: "Tematico",
    acesso: "Ao lado da entrada do simulador Alien Encounter",
    precoMedio: 33,
    destaque: "Ambiente sci-fi com pratos diferenciados. Experimente o frango marinado com molho agridoce.",
    latitude: 28.4971,
    longitude: -81.4881,
  },
  {
    nome: "Expo Snacks",
    regiao: "WorldExpo",
    tipo: "Economico",
    acesso: "Quiosque central do World Expo",
    precoMedio: 12,
    destaque: "Lanches rÃƒÂ¡pidos e bebidas refrescantes. Experimente o wrap de atum com alface.",
    latitude: 28.4972,
    longitude: -81.4882,
  },
  {
    nome: "Intergalactic Greens",
    regiao: "WorldExpo",
    tipo: "Saudavel",
    acesso: "Perto da ÃƒÂ¡rea de descanso principal",
    precoMedio: 21,
    destaque: "Saladas leves e wraps frescos para o fim do dia. Experimente a salada Caesar com frango grelhado.",
    latitude: 28.4973,
    longitude: -81.4883,
  },
  {
    nome: "Men in Black Comfort CafÃƒÂ©",
    regiao: "WorldExpo",
    tipo: "Conforto",
    acesso: "Ao lado da atraÃƒÂ§ÃƒÂ£o principal",
    precoMedio: 25,
    destaque: "Comidas caseiras com toque sci-fi. Experimente o frango com molho de mostarda e mel.",
    latitude: 28.4974,
    longitude: -81.4884,
  },
];



