export const jantaresUniversal = [
  // FogosEpicoUniverse
  {
    nome: "Epic Lagoon Grill",
    regiao: "FogosEpicoUniverse",
    tipo: ["Classico", "Americano"],
    acesso: "Próximo ao lago central do Epic Universe, com visão privilegiada para o show noturno",
    precoMedio: 48,
    destaque: "Pratos grelhados e frutos do mar com vista para os fogos. Experimente o filé com molho de vinho tinto.",
    latitude: 28.4701,
    longitude: -81.4601,
  },
  {
    nome: "Twilight Terrace",
    regiao: "FogosEpicoUniverse",
    tipo: "Tematico",
    acesso: "Deck principal para assistir ao espetáculo de fogos",
    precoMedio: 42,
    destaque: "Cardápio temático com iluminação especial. Experimente o salmão ao molho de maracujá.",
    latitude: 28.4702,
    longitude: -81.4602,
  },
  {
    nome: "Lagoon Snacks",
    regiao: "FogosEpicoUniverse",
    tipo: "Economico",
    acesso: "Quiosque lateral do viewing area",
    precoMedio: 15,
    destaque: "Snacks rápidos para o show. Experimente o wrap de frango grelhado.",
    latitude: 28.4703,
    longitude: -81.4603,
  },
  {
    nome: "Fireworks Greens",
    regiao: "FogosEpicoUniverse",
    tipo: "Saudavel",
    acesso: "Área de refeições leves próxima ao lago",
    precoMedio: 23,
    destaque: "Saladas e bowls ideais para um jantar leve. Experimente a salada de quinoa com frutas.",
    latitude: 28.4704,
    longitude: -81.4604,
  },
  {
    nome: "Epic Comfort Bites",
    regiao: "FogosEpicoUniverse",
    tipo: "Conforto",
    acesso: "Ao lado do deck panorâmico",
    precoMedio: 30,
    destaque: "Pratos reconfortantes para apreciar durante o show. Experimente a costelinha barbecue com purê.",
    latitude: 28.4705,
    longitude: -81.4605,
  },

  // FogosIslandsOfAdventure
  {
    nome: "Islands Lagoon Dining",
    regiao: "FogosIslandsOfAdventure",
    tipo: ["Classico", "Americano"],
    acesso: "Frente ao lago com vista para o show noturno",
    precoMedio: 45,
    destaque: "Pratos tradicionais americanos e carnes grelhadas. Experimente o hambúrguer gourmet com fritas rústicas.",
    latitude: 28.4721,
    longitude: -81.4621,
  },
  {
    nome: "Adventure Lights Café",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Tematico",
    acesso: "Área iluminada próxima ao viewing spot",
    precoMedio: 37,
    destaque: "Ambiente temático com decoração de aventura. Experimente o frango grelhado com arroz selvagem.",
    latitude: 28.4722,
    longitude: -81.4622,
  },
  {
    nome: "Lagoon Snack Bar",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Economico",
    acesso: "Quiosque lateral próximo ao show",
    precoMedio: 14,
    destaque: "Snacks, wraps e bebidas rápidas. Experimente o wrap de peru com molho de mostarda.",
    latitude: 28.4723,
    longitude: -81.4623,
  },
  {
    nome: "Adventure Greens",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Saudavel",
    acesso: "Próximo à área central do lago",
    precoMedio: 20,
    destaque: "Saladas frescas e bowls vegetarianos. Experimente a salada com avocado e mix de grãos.",
    latitude: 28.4724,
    longitude: -81.4624,
  },
  {
    nome: "Island Comfort Grill",
    regiao: "FogosIslandsOfAdventure",
    tipo: "Conforto",
    acesso: "Área principal de alimentação",
    precoMedio: 29,
    destaque: "Comidas confortáveis, massas e grelhados. Experimente o mac and cheese trufado.",
    latitude: 28.4725,
    longitude: -81.4625,
  },

  // FogosUniversalStudios
  {
    nome: "Universal Lagoon Grill",
    regiao: "FogosUniversalStudios",
    tipo: ["Classico", "Americano"],
    acesso: "Próximo ao lago central do Universal Studios, com vista para o show noturno",
    precoMedio: 44,
    destaque: "Carnes grelhadas e frutos do mar em ambiente sofisticado. Experimente o filé mignon com purê trufado.",
    latitude: 28.4800,
    longitude: -81.4710,
  },
  {
    nome: "Night Spark Café",
    regiao: "FogosUniversalStudios",
    tipo: "Tematico",
    acesso: "Ao lado da entrada para o viewing area do show de fogos",
    precoMedio: 39,
    destaque: "Ambiente imersivo com iluminação especial para a noite. Não deixe de experimentar o camarão ao alho e óleo.",
    latitude: 28.4801,
    longitude: -81.4711,
  },
  {
    nome: "Studio Snacks",
    regiao: "FogosUniversalStudios",
    tipo: "Economico",
    acesso: "Quiosque próximo ao viewing area principal",
    precoMedio: 14,
    destaque: "Snacks e petiscos rápidos para curtir os fogos. Experimente o wrap de frango grelhado.",
    latitude: 28.4802,
    longitude: -81.4712,
  },
  {
    nome: "Lagoon Greens",
    regiao: "FogosUniversalStudios",
    tipo: "Saudavel",
    acesso: "Área externa perto do show principal",
    precoMedio: 23,
    destaque: "Saladas frescas e pratos leves para a noite. Experimente a salada com quinoa e abacate.",
    latitude: 28.4803,
    longitude: -81.4713,
  },
  {
    nome: "Lagoon Premium Dining",
    regiao: "FogosUniversalStudios",
    tipo: "Conforto",
    acesso: "Área VIP de refeições próxima ao lago principal",
    precoMedio: 50,
    destaque: "Menu premium com vista exclusiva para o show. Experimente o salmão grelhado com molho de maracujá.",
    latitude: 28.4804,
    longitude: -81.4714,
  },

  // Hollywood
  {
    nome: "Hollywood Grill",
    regiao: "Hollywood",
    tipo: ["Classico", "Americano"],
    acesso: "Próximo ao Hollywood Boulevard",
    precoMedio: 41,
    destaque: "Pratos clássicos com ambiente inspirado na Era de Ouro de Hollywood. Experimente o hambúrguer com bacon defumado.",
    latitude: 28.4810,
    longitude: -81.4720,
  },
  {
    nome: "CineStar Diner",
    regiao: "Hollywood",
    tipo: "Tematico",
    acesso: "Ao lado do Cinema 4D",
    precoMedio: 34,
    destaque: "Decoração de cinema com pratos temáticos. Experimente o mac and cheese trufado.",
    latitude: 28.4811,
    longitude: -81.4721,
  },
  {
    nome: "Hollywood Snacks",
    regiao: "Hollywood",
    tipo: "Economico",
    acesso: "Perto da entrada do Hollywood Boulevard",
    precoMedio: 12,
    destaque: "Snacks rápidos e acessíveis para o jantar. Experimente o cachorro-quente com molho especial.",
    latitude: 28.4812,
    longitude: -81.4722,
  },
  {
    nome: "Star Greens",
    regiao: "Hollywood",
    tipo: "Saudavel",
    acesso: "Ao lado do Universal Theater",
    precoMedio: 22,
    destaque: "Saladas e wraps para refeições leves. Experimente o wrap de frango Caesar.",
    latitude: 28.4813,
    longitude: -81.4723,
  },
  {
    nome: "Boulevard Bistro",
    regiao: "Hollywood",
    tipo: "Conforto",
    acesso: "No final do Hollywood Boulevard, próximo às lojas temáticas",
    precoMedio: 27,
    destaque: "Culinária americana com pratos reconfortantes. Experimente a costela barbecue com batatas rústicas.",
    latitude: 28.4814,
    longitude: -81.4724,
  },
  // HowToTrainYourDragon
  {
    nome: "Berk Viking Grill",
    regiao: "HowToTrainYourDragon",
    tipo: ["Classico", "Americano"],
    acesso: "No centro da vila de Berk, perto da atração principal",
    precoMedio: 38,
    destaque: "Carnes grelhadas no estilo viking com acompanhamentos robustos. Experimente o prato de costela com batata assada.",
    latitude: 28.4820,
    longitude: -81.4730,
  },
  {
    nome: "Dragons Feast Hall",
    regiao: "HowToTrainYourDragon",
    tipo: "Tematico",
    acesso: "Próximo ao show dos dragões, com decoração nórdica",
    precoMedio: 42,
    destaque: "Refeições inspiradas em festins vikings com pratos de caça e peixe. Experimente o salmão com molho de ervas.",
    latitude: 28.4821,
    longitude: -81.4731,
  },
  {
    nome: "Hiccup's Quick Bites",
    regiao: "HowToTrainYourDragon",
    tipo: "Economico",
    acesso: "Ao lado da área de jogos do Soluço",
    precoMedio: 14,
    destaque: "Lanches rápidos para quem está com pressa. Experimente o sanduíche de frango com queijo.",
    latitude: 28.4822,
    longitude: -81.4732,
  },
  {
    nome: "Astrid’s Greens",
    regiao: "HowToTrainYourDragon",
    tipo: "Saudavel",
    acesso: "Perto da área de treinamento de dragões",
    precoMedio: 21,
    destaque: "Bowls leves e wraps saudáveis com ingredientes frescos. Experimente a salada com grãos e molho de iogurte.",
    latitude: 28.4823,
    longitude: -81.4733,
  },
  {
    nome: "Dragon Comfort Diner",
    regiao: "HowToTrainYourDragon",
    tipo: "Conforto",
    acesso: "Ao lado da loja de souvenirs de Berk",
    precoMedio: 27,
    destaque: "Pratos confortáveis para encerrar o dia. Experimente o ensopado de carne com legumes.",
    latitude: 28.4824,
    longitude: -81.4734,
  },

  // JurassicPark
  {
    nome: "Jurassic Grill",
    regiao: "JurassicPark",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da entrada do Jurassic River Adventure",
    precoMedio: 40,
    destaque: "Carnes e hambúrgueres com tema jurássico. Experimente o T-Rex Burger com bacon e cheddar.",
    latitude: 28.4830,
    longitude: -81.4740,
  },
  {
    nome: "Raptor’s Feast",
    regiao: "JurassicPark",
    tipo: "Tematico",
    acesso: "Perto da área de exibição dos velociraptors",
    precoMedio: 36,
    destaque: "Pratos temáticos com carnes grelhadas e molhos especiais. Experimente o frango ao molho de manga picante.",
    latitude: 28.4831,
    longitude: -81.4741,
  },
  {
    nome: "Dino Snacks",
    regiao: "JurassicPark",
    tipo: "Economico",
    acesso: "Quiosque próximo ao Jurassic Outfitters",
    precoMedio: 13,
    destaque: "Snacks rápidos como wraps e nachos. Experimente o wrap de frango grelhado.",
    latitude: 28.4832,
    longitude: -81.4742,
  },
  {
    nome: "Jurassic Greens",
    regiao: "JurassicPark",
    tipo: "Saudavel",
    acesso: "Área sombreada próxima à Discovery Center",
    precoMedio: 20,
    destaque: "Saladas frescas e bowls leves para os fãs de saúde. Experimente o bowl de quinoa com salmão grelhado.",
    latitude: 28.4833,
    longitude: -81.4743,
  },
  {
    nome: "Herbivore Comfort Grill",
    regiao: "JurassicPark",
    tipo: "Conforto",
    acesso: "Em frente ao portão principal de Jurassic Park",
    precoMedio: 29,
    destaque: "Massas e carnes ao estilo caseiro. Experimente o mac and cheese com costela desfiada.",
    latitude: 28.4834,
    longitude: -81.4744,
  },

  // LostContinent
  {
    nome: "Mythos Restaurant",
    regiao: "LostContinent",
    tipo: ["Classico", "Americano"],
    acesso: "No centro do Lost Continent, próximo à fonte principal",
    precoMedio: 44,
    destaque: "Restaurante premiado com culinária variada. Experimente o filé de peixe ao molho cítrico.",
    latitude: 28.4840,
    longitude: -81.4750,
  },
  {
    nome: "Poseidon’s Table",
    regiao: "LostContinent",
    tipo: "Tematico",
    acesso: "Ao lado da atração Poseidon’s Fury",
    precoMedio: 38,
    destaque: "Ambiente temático inspirado na mitologia grega. Experimente o polvo grelhado com azeite de ervas.",
    latitude: 28.4841,
    longitude: -81.4751,
  },
  {
    nome: "Oracle Snacks",
    regiao: "LostContinent",
    tipo: "Economico",
    acesso: "Em frente à entrada do The Eighth Voyage of Sindbad",
    precoMedio: 12,
    destaque: "Lanches rápidos e petiscos leves. Experimente a pita com frango assado.",
    latitude: 28.4842,
    longitude: -81.4752,
  },
  {
    nome: "Olympus Greens",
    regiao: "LostContinent",
    tipo: "Saudavel",
    acesso: "Próximo ao Mythos Restaurant",
    precoMedio: 22,
    destaque: "Pratos leves com saladas e wraps mediterrâneos. Experimente a salada grega com queijo feta.",
    latitude: 28.4843,
    longitude: -81.4753,
  },
  {
    nome: "Lost Comfort Kitchen",
    regiao: "LostContinent",
    tipo: "Conforto",
    acesso: "Perto da saída do Lost Continent",
    precoMedio: 28,
    destaque: "Pratos robustos como carne assada e massas. Experimente o penne com molho de tomate rústico.",
    latitude: 28.4844,
    longitude: -81.4754,
  },

  // MarvelSuperHeroIsland
  {
    nome: "Avengers Grill",
    regiao: "MarvelSuperHeroIsland",
    tipo: ["Classico", "Americano"],
    acesso: "Em frente à atração The Incredible Hulk Coaster",
    precoMedio: 39,
    destaque: "Comida clássica americana com ambiente de super-heróis. Experimente o hambúrguer do Hulk com queijo cheddar.",
    latitude: 28.4850,
    longitude: -81.4760,
  },
  {
    nome: "Hero’s Diner",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Tematico",
    acesso: "Ao lado da Spider-Man Store",
    precoMedio: 35,
    destaque: "Pratos inspirados nos heróis da Marvel. Experimente o frango grelhado com batata rústica.",
    latitude: 28.4851,
    longitude: -81.4761,
  },
  {
    nome: "Marvel Quick Eats",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Economico",
    acesso: "Perto da entrada do Café 4",
    precoMedio: 13,
    destaque: "Snacks rápidos como sanduíches e wraps. Experimente o wrap de presunto com queijo.",
    latitude: 28.4852,
    longitude: -81.4762,
  },
  {
    nome: "Superhero Greens",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Saudavel",
    acesso: "Área lateral da Marvel Super Hero Island",
    precoMedio: 20,
    destaque: "Bowls e saladas energéticas. Experimente a salada com frango grelhado e quinoa.",
    latitude: 28.4853,
    longitude: -81.4763,
  },
  {
    nome: "Hero Comfort Bites",
    regiao: "MarvelSuperHeroIsland",
    tipo: "Conforto",
    acesso: "Ao lado do Café 4",
    precoMedio: 27,
    destaque: "Massas e pratos quentes inspirados nos heróis. Experimente o mac and cheese com frango crocante.",
    latitude: 28.4854,
    longitude: -81.4764,
  },

  // MinionsLand
  {
    nome: "Minion’s Banana Grill",
    regiao: "MinionsLand",
    tipo: ["Classico", "Americano"],
    acesso: "Próximo à entrada da Minion Mayhem",
    precoMedio: 36,
    destaque: "Pratos americanos com um toque divertido dos Minions. Experimente o cheeseburger com molho de banana especial.",
    latitude: 28.4860,
    longitude: -81.4770,
  },
  {
    nome: "Gru’s Lab Kitchen",
    regiao: "MinionsLand",
    tipo: "Tematico",
    acesso: "Dentro do laboratório do Gru, ao lado da atração principal",
    precoMedio: 40,
    destaque: "Ambiente imersivo com pratos temáticos. Experimente o frango grelhado com purê roxo.",
    latitude: 28.4861,
    longitude: -81.4771,
  },
  {
    nome: "Minion Bites",
    regiao: "MinionsLand",
    tipo: "Economico",
    acesso: "Quiosque ao lado da loja dos Minions",
    precoMedio: 12,
    destaque: "Lanches rápidos para toda a família. Experimente o wrap de presunto com queijo cheddar.",
    latitude: 28.4862,
    longitude: -81.4772,
  },
  {
    nome: "Banana Greens",
    regiao: "MinionsLand",
    tipo: "Saudavel",
    acesso: "Perto da área de fotos com os Minions",
    precoMedio: 21,
    destaque: "Saladas tropicais e bowls leves. Experimente a salada com abacaxi e frango grelhado.",
    latitude: 28.4863,
    longitude: -81.4773,
  },
  {
    nome: "Minion Comfort Café",
    regiao: "MinionsLand",
    tipo: "Conforto",
    acesso: "Próximo ao Minion Café oficial",
    precoMedio: 25,
    destaque: "Pratos confortáveis e sobremesas temáticas. Experimente o mac and cheese com crocante de banana.",
    latitude: 28.4864,
    longitude: -81.4774,
  },

  // NewYork
  {
    nome: "Big Apple Grill",
    regiao: "NewYork",
    tipo: ["Classico", "Americano"],
    acesso: "Próximo à atração The Mummy",
    precoMedio: 42,
    destaque: "Pratos típicos de Nova York, como steaks e burgers. Experimente o hambúrguer com bacon e cebolas caramelizadas.",
    latitude: 28.4870,
    longitude: -81.4780,
  },
  {
    nome: "Broadway Diner",
    regiao: "NewYork",
    tipo: "Tematico",
    acesso: "Ao lado da área de shows do New York Street",
    precoMedio: 38,
    destaque: "Ambiente com decoração de teatro da Broadway. Experimente o frango ao molho de vinho.",
    latitude: 28.4871,
    longitude: -81.4781,
  },
  {
    nome: "NYC Quick Eats",
    regiao: "NewYork",
    tipo: "Economico",
    acesso: "Ao lado do café da área de Nova York",
    precoMedio: 14,
    destaque: "Lanches rápidos em estilo deli. Experimente o sanduíche de pastrami.",
    latitude: 28.4872,
    longitude: -81.4782,
  },
  {
    nome: "Empire Greens",
    regiao: "NewYork",
    tipo: "Saudavel",
    acesso: "Próximo à entrada do Race Through New York",
    precoMedio: 22,
    destaque: "Saladas frescas e opções leves. Experimente a salada de rúcula com parmesão.",
    latitude: 28.4873,
    longitude: -81.4783,
  },
  {
    nome: "Liberty Comfort Food",
    regiao: "NewYork",
    tipo: "Conforto",
    acesso: "Área central da rua principal de Nova York",
    precoMedio: 28,
    destaque: "Comida caseira inspirada na cultura nova-iorquina. Experimente o macarrão com queijo e bacon.",
    latitude: 28.4874,
    longitude: -81.4784,
  },

  // ProductionCentral
  {
    nome: "Director’s Grill",
    regiao: "ProductionCentral",
    tipo: ["Classico", "Americano"],
    acesso: "No centro da Production Central",
    precoMedio: 40,
    destaque: "Pratos clássicos servidos em ambiente de estúdio. Experimente o filé de frango grelhado com arroz.",
    latitude: 28.4880,
    longitude: -81.4790,
  },
  {
    nome: "Studio Diner",
    regiao: "ProductionCentral",
    tipo: "Tematico",
    acesso: "Perto do simulador Despicable Me",
    precoMedio: 37,
    destaque: "Decoração de estúdio de cinema com pratos temáticos. Experimente o hambúrguer de costela com molho barbecue.",
    latitude: 28.4881,
    longitude: -81.4791,
  },
  {
    nome: "Production Snacks",
    regiao: "ProductionCentral",
    tipo: "Economico",
    acesso: "Quiosque na área central da Production",
    precoMedio: 13,
    destaque: "Snacks e bebidas rápidas para a noite. Experimente o wrap de frango Caesar.",
    latitude: 28.4882,
    longitude: -81.4792,
  },
  {
    nome: "Cine Greens",
    regiao: "ProductionCentral",
    tipo: "Saudavel",
    acesso: "Área próxima ao teatro 4D",
    precoMedio: 20,
    destaque: "Saladas e pratos leves. Experimente o bowl de quinoa com frango grelhado.",
    latitude: 28.4883,
    longitude: -81.4793,
  },
  {
    nome: "Director Comfort Kitchen",
    regiao: "ProductionCentral",
    tipo: "Conforto",
    acesso: "Ao lado do café principal de Production Central",
    precoMedio: 29,
    destaque: "Pratos quentes como massas e ensopados. Experimente o ensopado de carne com batata.",
    latitude: 28.4884,
    longitude: -81.4794,
  },

  // SanFrancisco
  {
    nome: "Pier 39 Grill",
    regiao: "SanFrancisco",
    tipo: ["Classico", "Americano"],
    acesso: "Área do Pier, ao lado da atração Fast & Furious",
    precoMedio: 41,
    destaque: "Pratos com frutos do mar e grelhados. Experimente o salmão ao molho de limão.",
    latitude: 28.4890,
    longitude: -81.4800,
  },
  {
    nome: "Bay Area Diner",
    regiao: "SanFrancisco",
    tipo: "Tematico",
    acesso: "Próximo à doca principal de San Francisco",
    precoMedio: 38,
    destaque: "Ambiente inspirado na costa oeste americana. Experimente o peixe empanado com batatas fritas.",
    latitude: 28.4891,
    longitude: -81.4801,
  },
  {
    nome: "SF Quick Bites",
    regiao: "SanFrancisco",
    tipo: "Economico",
    acesso: "Ao lado da entrada da área de San Francisco",
    precoMedio: 14,
    destaque: "Lanches rápidos com sabor da costa. Experimente o wrap de camarão.",
    latitude: 28.4892,
    longitude: -81.4802,
  },
  {
    nome: "Golden Gate Greens",
    regiao: "SanFrancisco",
    tipo: "Saudavel",
    acesso: "Próximo à área de visualização do lago",
    precoMedio: 22,
    destaque: "Saladas e pratos leves com frutos do mar. Experimente a salada de rúcula com salmão defumado.",
    latitude: 28.4893,
    longitude: -81.4803,
  },
  {
    nome: "Fisherman’s Comfort House",
    regiao: "SanFrancisco",
    tipo: "Conforto",
    acesso: "Perto da área temática de barcos",
    precoMedio: 27,
    destaque: "Pratos confortáveis com sabor de mar. Experimente o ensopado de frutos do mar.",
    latitude: 28.4894,
    longitude: -81.4804,
  },
  // SeussLanding
  {
    nome: "Who-ville Grill",
    regiao: "SeussLanding",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da atração The Cat in the Hat",
    precoMedio: 35,
    destaque: "Pratos clássicos com toques divertidos do Dr. Seuss. Experimente o hambúrguer com molho de cheddar.",
    latitude: 28.4900,
    longitude: -81.4810,
  },
  {
    nome: "Grinch’s Feast",
    regiao: "SeussLanding",
    tipo: "Tematico",
    acesso: "Próximo à área de fotos com o Grinch",
    precoMedio: 32,
    destaque: "Ambiente temático com pratos inspirados nas histórias. Experimente o frango grelhado com legumes coloridos.",
    latitude: 28.4901,
    longitude: -81.4811,
  },
  {
    nome: "Seuss Snacks",
    regiao: "SeussLanding",
    tipo: "Economico",
    acesso: "Quiosque central da área Seuss",
    precoMedio: 12,
    destaque: "Snacks rápidos com estilo infantil. Experimente o wrap de queijo com presunto.",
    latitude: 28.4902,
    longitude: -81.4812,
  },
  {
    nome: "Green Eggs & Salad",
    regiao: "SeussLanding",
    tipo: "Saudavel",
    acesso: "Perto da saída da atração One Fish Two Fish",
    precoMedio: 21,
    destaque: "Opções leves e criativas para crianças e adultos. Experimente a salada de frango com abacaxi.",
    latitude: 28.4903,
    longitude: -81.4813,
  },
  {
    nome: "Whoville Comfort Café",
    regiao: "SeussLanding",
    tipo: "Conforto",
    acesso: "Entre os quiosques de doces e o carrossel do Seuss",
    precoMedio: 24,
    destaque: "Pratos caseiros com toques criativos. Experimente o mac and cheese com ervas.",
    latitude: 28.4904,
    longitude: -81.4814,
  },

  // SuperNintendoWorld
  {
    nome: "Mario’s Grill",
    regiao: "SuperNintendoWorld",
    tipo: ["Classico", "Americano"],
    acesso: "Próximo à entrada do Mario Kart: Bowser’s Challenge",
    precoMedio: 39,
    destaque: "Pratos inspirados no universo Mario. Experimente o hambúrguer de cogumelo gigante.",
    latitude: 28.4910,
    longitude: -81.4820,
  },
  {
    nome: "Luigi’s Pasta House",
    regiao: "SuperNintendoWorld",
    tipo: "Tematico",
    acesso: "Ao lado da loja oficial do Mario",
    precoMedio: 34,
    destaque: "Massas italianas e pratos especiais. Experimente o espaguete com molho de cogumelos.",
    latitude: 28.4911,
    longitude: -81.4821,
  },
  {
    nome: "Toad’s Quick Bites",
    regiao: "SuperNintendoWorld",
    tipo: "Economico",
    acesso: "Quiosque próximo ao Toad’s Café",
    precoMedio: 13,
    destaque: "Lanches rápidos inspirados no Toad. Experimente o sanduíche de queijo com tomate.",
    latitude: 28.4912,
    longitude: -81.4822,
  },
  {
    nome: "Princess Peach Salad Bar",
    regiao: "SuperNintendoWorld",
    tipo: "Saudavel",
    acesso: "Próximo ao castelo da Peach",
    precoMedio: 22,
    destaque: "Saladas frescas e pratos leves. Experimente a salada de morango com nozes.",
    latitude: 28.4913,
    longitude: -81.4823,
  },
  {
    nome: "Bowser’s Comfort Feast",
    regiao: "SuperNintendoWorld",
    tipo: "Conforto",
    acesso: "Dentro do Bowser’s Castle",
    precoMedio: 26,
    destaque: "Pratos reconfortantes para toda a família. Experimente o strogonoff de carne.",
    latitude: 28.4914,
    longitude: -81.4824,
  },

  // TheWitcher
  {
    nome: "Kaer Morhen Grill",
    regiao: "TheWitcher",
    tipo: ["Classico", "Americano"],
    acesso: "Próximo à entrada do castelo de Kaer Morhen",
    precoMedio: 42,
    destaque: "Pratos robustos com inspiração medieval. Experimente o cordeiro assado com ervas.",
    latitude: 28.4920,
    longitude: -81.4830,
  },
  {
    nome: "Geralt’s Tavern",
    regiao: "TheWitcher",
    tipo: "Tematico",
    acesso: "Ao lado da atração principal de The Witcher",
    precoMedio: 38,
    destaque: "Ambiente de taverna com pratos rústicos. Experimente a carne de javali com purê de batatas.",
    latitude: 28.4921,
    longitude: -81.4831,
  },
  {
    nome: "Witcher Bites",
    regiao: "TheWitcher",
    tipo: "Economico",
    acesso: "Quiosque medieval próximo à saída da área",
    precoMedio: 14,
    destaque: "Petiscos simples com sabores fortes. Experimente o pão rústico com queijo e alho.",
    latitude: 28.4922,
    longitude: -81.4832,
  },
  {
    nome: "Triss Herbal Greens",
    regiao: "TheWitcher",
    tipo: "Saudavel",
    acesso: "Próximo ao mercado medieval",
    precoMedio: 23,
    destaque: "Saladas e sopas leves com ingredientes naturais. Experimente a sopa de legumes com ervas.",
    latitude: 28.4923,
    longitude: -81.4833,
  },
  {
    nome: "Yennefer’s Comfort Hall",
    regiao: "TheWitcher",
    tipo: "Conforto",
    acesso: "Dentro do salão principal de banquetes",
    precoMedio: 30,
    destaque: "Pratos aconchegantes e sobremesas rústicas. Experimente o ensopado de carne com legumes assados.",
    latitude: 28.4924,
    longitude: -81.4834,
  },

  // TheWizardingWorld
  {
    nome: "Three Broomsticks Evening",
    regiao: "TheWizardingWorld",
    tipo: ["Classico", "Americano"],
    acesso: "Ao lado da entrada da área Hogsmeade",
    precoMedio: 45,
    destaque: "Jantares clássicos com toque britânico. Experimente o peixe com batatas fritas.",
    latitude: 28.4930,
    longitude: -81.4840,
  },
  {
    nome: "Leaky Cauldron",
    regiao: "TheWizardingWorld",
    tipo: "Tematico",
    acesso: "Na área principal do Beco Diagonal",
    precoMedio: 48,
    destaque: "Pratos típicos britânicos em ambiente mágico. Experimente o bangers and mash.",
    latitude: 28.4931,
    longitude: -81.4841,
  },
  {
    nome: "Wizard Snacks",
    regiao: "TheWizardingWorld",
    tipo: "Economico",
    acesso: "Quiosque do Beco Diagonal",
    precoMedio: 15,
    destaque: "Snacks como empadas e pães mágicos. Experimente a empada de abóbora.",
    latitude: 28.4932,
    longitude: -81.4842,
  },
  {
    nome: "Herbology Greens",
    regiao: "TheWizardingWorld",
    tipo: "Saudavel",
    acesso: "Próximo à área de Herbologia",
    precoMedio: 22,
    destaque: "Saladas mágicas com ervas frescas. Experimente a salada com molho de abóbora.",
    latitude: 28.4933,
    longitude: -81.4843,
  },
  {
    nome: "Hogwarts Comfort Hall",
    regiao: "TheWizardingWorld",
    tipo: "Conforto",
    acesso: "Dentro do castelo de Hogwarts",
    precoMedio: 33,
    destaque: "Pratos aconchegantes e sobremesas. Experimente o ensopado de carne com pão quente.",
    latitude: 28.4934,
    longitude: -81.4844,
  },

  // TheWizardingWorldHogsmeade
  {
    nome: "Three Broomsticks Dinner",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: ["Classico", "Americano"],
    acesso: "No coração de Hogsmeade, ao lado da estação de trem",
    precoMedio: 46,
    destaque: "Jantares britânicos como peixe com batatas e ensopados. Experimente o clássico fish & chips.",
    latitude: 28.4940,
    longitude: -81.4850,
  },
  {
    nome: "Hogsmeade Cauldron",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Tematico",
    acesso: "Próximo à entrada da Zonko’s Joke Shop",
    precoMedio: 41,
    destaque: "Ambiente temático com pratos de caldeirões. Experimente o guisado de carne com legumes.",
    latitude: 28.4941,
    longitude: -81.4851,
  },
  {
    nome: "Butterbeer Bites",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Economico",
    acesso: "Quiosque ao lado do Owl Post",
    precoMedio: 14,
    destaque: "Snacks e bebidas de Butterbeer para a noite. Experimente o cookie de Butterbeer.",
    latitude: 28.4942,
    longitude: -81.4852,
  },
  {
    nome: "Hogsmeade Greens",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Saudavel",
    acesso: "Perto da Honeydukes",
    precoMedio: 23,
    destaque: "Saladas e bowls frescos para uma refeição leve. Experimente a salada de frango com maçã verde.",
    latitude: 28.4943,
    longitude: -81.4853,
  },
  {
    nome: "Great Hall Comfort",
    regiao: "TheWizardingWorldHogsmeade",
    tipo: "Conforto",
    acesso: "Ao lado da entrada do Castelo de Hogwarts",
    precoMedio: 32,
    destaque: "Refeições aconchegantes com pratos quentes e sobremesas. Experimente o ensopado de cordeiro.",
    latitude: 28.4944,
    longitude: -81.4854,
  },

  // ToonLagoon
  {
    nome: "Toon Lagoon Grill",
    regiao: "ToonLagoon",
    tipo: ["Classico", "Americano"],
    acesso: "Próximo à atração Dudley Do-Right’s Ripsaw Falls",
    precoMedio: 36,
    destaque: "Pratos clássicos com hambúrgueres e grelhados. Experimente o cheeseburger com batatas rústicas.",
    latitude: 28.4950,
    longitude: -81.4860,
  },
  {
    nome: "Popeye’s Tavern",
    regiao: "ToonLagoon",
    tipo: "Tematico",
    acesso: "Ao lado da atração Popeye & Bluto’s Bilge-Rat Barges",
    precoMedio: 29,
    destaque: "Ambiente inspirado em Popeye com pratos temáticos. Experimente o frango assado com espinafre.",
    latitude: 28.4951,
    longitude: -81.4861,
  },
  {
    nome: "Lagoon Snacks",
    regiao: "ToonLagoon",
    tipo: "Economico",
    acesso: "Quiosque central da área Toon Lagoon",
    precoMedio: 12,
    destaque: "Snacks leves e rápidos. Experimente o wrap de peru com queijo.",
    latitude: 28.4952,
    longitude: -81.4862,
  },
  {
    nome: "Toon Greens",
    regiao: "ToonLagoon",
    tipo: "Saudavel",
    acesso: "Entre a saída da Ripsaw Falls e os quiosques de souvenirs",
    precoMedio: 22,
    destaque: "Saladas e pratos leves com sucos naturais. Experimente a salada Caesar com frango grelhado.",
    latitude: 28.4953,
    longitude: -81.4863,
  },
  {
    nome: "Bluto’s Comfort Café",
    regiao: "ToonLagoon",
    tipo: "Conforto",
    acesso: "Ao lado do Popeye’s Tavern",
    precoMedio: 26,
    destaque: "Pratos caseiros para refeições rápidas. Experimente o mac and cheese com presunto.",
    latitude: 28.4954,
    longitude: -81.4864,
  },

  // UniversalMonsters
  {
    nome: "Monsters Grill",
    regiao: "UniversalMonsters",
    tipo: ["Classico", "Americano"],
    acesso: "Próximo à atração Universal Monsters Tribute",
    precoMedio: 40,
    destaque: "Carnes e hambúrgueres com tema de terror clássico. Experimente o hambúrguer do Drácula.",
    latitude: 28.4960,
    longitude: -81.4870,
  },
  {
    nome: "Frankenstein Feast",
    regiao: "UniversalMonsters",
    tipo: "Tematico",
    acesso: "Ao lado do castelo de Frankenstein",
    precoMedio: 38,
    destaque: "Ambiente sombrio com pratos temáticos. Experimente o ensopado de carne com batata.",
    latitude: 28.4961,
    longitude: -81.4871,
  },
  {
    nome: "Monster Snacks",
    regiao: "UniversalMonsters",
    tipo: "Economico",
    acesso: "Quiosque central da área dos monstros",
    precoMedio: 13,
    destaque: "Petiscos temáticos para lanches rápidos. Experimente o wrap de frango picante.",
    latitude: 28.4962,
    longitude: -81.4872,
  },
  {
    nome: "Bride’s Greens",
    regiao: "UniversalMonsters",
    tipo: "Saudavel",
    acesso: "Próximo à saída da atração dos monstros",
    precoMedio: 22,
    destaque: "Saladas com ingredientes frescos e criativos. Experimente a salada de quinoa com tomate seco.",
    latitude: 28.4963,
    longitude: -81.4873,
  },
  {
    nome: "Wolfman Comfort Tavern",
    regiao: "UniversalMonsters",
    tipo: "Conforto",
    acesso: "Ao lado da Frankenstein Feast",
    precoMedio: 28,
    destaque: "Pratos reconfortantes para jantares temáticos. Experimente o guisado de carne com legumes.",
    latitude: 28.4964,
    longitude: -81.4874,
  },

  // WorldExpo
  {
    nome: "Expo Grill",
    regiao: "WorldExpo",
    tipo: ["Classico", "Americano"],
    acesso: "Próximo à atração Men in Black: Alien Attack",
    precoMedio: 37,
    destaque: "Pratos americanos clássicos com carnes grelhadas. Experimente o hambúrguer com queijo cheddar.",
    latitude: 28.4970,
    longitude: -81.4880,
  },
  {
    nome: "Alien Feast",
    regiao: "WorldExpo",
    tipo: "Tematico",
    acesso: "Ao lado da entrada do simulador Alien Encounter",
    precoMedio: 33,
    destaque: "Ambiente sci-fi com pratos diferenciados. Experimente o frango marinado com molho agridoce.",
    latitude: 28.4971,
    longitude: -81.4881,
  },
  {
    nome: "Expo Snacks",
    regiao: "WorldExpo",
    tipo: "Economico",
    acesso: "Quiosque central do World Expo",
    precoMedio: 12,
    destaque: "Lanches rápidos e bebidas refrescantes. Experimente o wrap de atum com alface.",
    latitude: 28.4972,
    longitude: -81.4882,
  },
  {
    nome: "Intergalactic Greens",
    regiao: "WorldExpo",
    tipo: "Saudavel",
    acesso: "Perto da área de descanso principal",
    precoMedio: 21,
    destaque: "Saladas leves e wraps frescos para o fim do dia. Experimente a salada Caesar com frango grelhado.",
    latitude: 28.4973,
    longitude: -81.4883,
  },
  {
    nome: "Men in Black Comfort Café",
    regiao: "WorldExpo",
    tipo: "Conforto",
    acesso: "Ao lado da atração principal",
    precoMedio: 25,
    destaque: "Comidas caseiras com toque sci-fi. Experimente o frango com molho de mostarda e mel.",
    latitude: 28.4974,
    longitude: -81.4884,
  },
];



