const blocoChecklistDocumentos = {
  titulo: '✅ Checklist Final + Documentos para o Retorno',
  tipo: 'informativa',
  descricao: [
    '**Checklist de Preparação para o Retorno:**',
    '',
    'Revise cada item com atenção antes de sair para o aeroporto. Isso ajuda a evitar contratempos e esquecimentos no retorno.',
    '',
    'Itens essenciais:',
    'Celular carregado e com internet (chip ou eSIM)',
    'Passaporte e documentos de viagem em mãos',
    'Bagagens prontas e identificadas',
    'Verificar banheiros e armários do quarto',
    'Desconectar e guardar carregadores e eletrônicos',
    'Conferir compras e lembranças guardadas',
    'Checar se nada ficou embaixo da cama ou nos armários',
    'Tempo estimado até o aeroporto revisado',
    'Transporte para o aeroporto confirmado',
    'Check-out feito e chaves do quarto devolvidas',
    '',
    '**Documentos e Cuidados no Embarque:**',
    '',
    'No dia do voo de volta, alguns documentos e comprovantes podem ser solicitados pela companhia aérea ou pela imigração americana. Também é importante estar atento às regras da Receita Federal ao desembarcar no Brasil.',
    '',
    'Prepare tudo com antecedência e guarde os documentos mais importantes na bagagem de mão.',
    '',
    'Passaporte com visto válido (mesmo vencido, se aplicável) e carimbo de entrada nos EUA',
    'Comprovante de passagem aérea de retorno',
    'Confirmação do hotel onde ficou hospedado (impresso ou digital)',
    'Cartões utilizados na viagem (crédito/débito/multimoeda)',
    'Recibos de compras (especialmente eletrônicos ou itens de alto valor)',
    'Declaração de bens, se estiver trazendo mais de US$ 1.000 em eletrônicos ou produtos por pessoa',
    'Receita médica para medicamentos controlados ou em grandes quantidades',
    'Etiquetas de bagagem impressas ou digitais',
    'Aplicativo da Receita Federal: **e-DBV** (para declarar bens antes do embarque)',
  ].join('\n'),
};

export default blocoChecklistDocumentos;
