const blocoChecklistDocumentos = {
  titulo: 'âœ… Checklist Final + Documentos para o Retorno',
  tipo: 'informativa',
  descricao: [
    '**Checklist de PreparaÃ§Ã£o para o Retorno:**',
    '',
    'Revise cada item com atenÃ§Ã£o antes de sair para o aeroporto. Isso ajuda a evitar contratempos e esquecimentos no retorno.',
    '',
    'Itens essenciais:',
    'Celular carregado e com internet (chip ou eSIM)',
    'Passaporte e documentos de viagem em mÃ£os',
    'Bagagens prontas e identificadas',
    'Verificar banheiros e armÃ¡rios do quarto',
    'Desconectar e guardar carregadores e eletrÃ´nicos',
    'Conferir compras e lembranÃ§as guardadas',
    'Checar se nada ficou embaixo da cama ou nos armÃ¡rios',
    'Tempo estimado atÃ© o aeroporto revisado',
    'Transporte para o aeroporto confirmado',
    'Check-out feito e chaves do quarto devolvidas',
    '',
    '**Documentos e Cuidados no Embarque:**',
    '',
    'No dia do voo de volta, alguns documentos e comprovantes podem ser solicitados pela companhia aÃ©rea ou pela imigraÃ§Ã£o americana. TambÃ©m Ã© importante estar atento Ã s regras da Receita Federal ao desembarcar no Brasil.',
    '',
    'Prepare tudo com antecedÃªncia e guarde os documentos mais importantes na bagagem de mÃ£o.',
    '',
    'Passaporte com visto vÃ¡lido (mesmo vencido, se aplicÃ¡vel) e carimbo de entrada nos EUA',
    'Comprovante de passagem aÃ©rea de retorno',
    'ConfirmaÃ§Ã£o do hotel onde ficou hospedado (impresso ou digital)',
    'CartÃµes utilizados na viagem (crÃ©dito/dÃ©bito/multimoeda)',
    'Recibos de compras (especialmente eletrÃ´nicos ou itens de alto valor)',
    'DeclaraÃ§Ã£o de bens, se estiver trazendo mais de US$ 1.000 em eletrÃ´nicos ou produtos por pessoa',
    'Receita mÃ©dica para medicamentos controlados ou em grandes quantidades',
    'Etiquetas de bagagem impressas ou digitais',
    'Aplicativo da Receita Federal: **e-DBV** (para declarar bens antes do embarque)',
  ].join('\n'),
};

export default blocoChecklistDocumentos;
