ï»¿const blocoChecklistDocumentos = {
  titulo: 'Ã¢Å“â€¦ Checklist Final + Documentos para o Retorno',
  tipo: 'informativa',
  descricao: [
    '**Checklist de PreparaÃƒÂ§ÃƒÂ£o para o Retorno:**',
    '',
    'Revise cada item com atenÃƒÂ§ÃƒÂ£o antes de sair para o aeroporto. Isso ajuda a evitar contratempos e esquecimentos no retorno.',
    '',
    'Itens essenciais:',
    'Celular carregado e com internet (chip ou eSIM)',
    'Passaporte e documentos de viagem em mÃƒÂ£os',
    'Bagagens prontas e identificadas',
    'Verificar banheiros e armÃƒÂ¡rios do quarto',
    'Desconectar e guardar carregadores e eletrÃƒÂ´nicos',
    'Conferir compras e lembranÃƒÂ§as guardadas',
    'Checar se nada ficou embaixo da cama ou nos armÃƒÂ¡rios',
    'Tempo estimado atÃƒÂ© o aeroporto revisado',
    'Transporte para o aeroporto confirmado',
    'Check-out feito e chaves do quarto devolvidas',
    '',
    '**Documentos e Cuidados no Embarque:**',
    '',
    'No dia do voo de volta, alguns documentos e comprovantes podem ser solicitados pela companhia aÃƒÂ©rea ou pela imigraÃƒÂ§ÃƒÂ£o americana. TambÃƒÂ©m ÃƒÂ© importante estar atento ÃƒÂ s regras da Receita Federal ao desembarcar no Brasil.',
    '',
    'Prepare tudo com antecedÃƒÂªncia e guarde os documentos mais importantes na bagagem de mÃƒÂ£o.',
    '',
    'Passaporte com visto vÃƒÂ¡lido (mesmo vencido, se aplicÃƒÂ¡vel) e carimbo de entrada nos EUA',
    'Comprovante de passagem aÃƒÂ©rea de retorno',
    'ConfirmaÃƒÂ§ÃƒÂ£o do hotel onde ficou hospedado (impresso ou digital)',
    'CartÃƒÂµes utilizados na viagem (crÃƒÂ©dito/dÃƒÂ©bito/multimoeda)',
    'Recibos de compras (especialmente eletrÃƒÂ´nicos ou itens de alto valor)',
    'DeclaraÃƒÂ§ÃƒÂ£o de bens, se estiver trazendo mais de US$ 1.000 em eletrÃƒÂ´nicos ou produtos por pessoa',
    'Receita mÃƒÂ©dica para medicamentos controlados ou em grandes quantidades',
    'Etiquetas de bagagem impressas ou digitais',
    'Aplicativo da Receita Federal: **e-DBV** (para declarar bens antes do embarque)',
  ].join('\n'),
};

export default blocoChecklistDocumentos;
