ï»¿const blocoChecklistDocumentos = {
  titulo: 'Ã¢Å“â€¦ Checklist Final + Documentos para o Retorno',
  tipo: 'informativa',
  descricao: [
    'Checklist de PreparaÃƒÂ§ÃƒÂ£o para o Retorno:',
    'Revise cada item antes de sair para o aeroporto para evitar esquecimentos.',
    'Itens essenciais:',
    'Celular carregado e com internet (chip ou eSIM)',
    'Passaporte e documentos de viagem',
    'Bagagens prontas e identificadas',
    'Conferir banheiros, armÃƒÂ¡rios e embaixo da cama',
    'Guardar carregadores e eletrÃƒÂ´nicos',
    'Conferir compras e lembranÃƒÂ§as',
    'Revisar tempo atÃƒÂ© o aeroporto',
    'Transporte confirmado',
    'Check-out feito e chaves devolvidas',
    'Documentos e Cuidados no Embarque:',
    'Prepare documentos com antecedÃƒÂªncia e mantenha-os na bagagem de mÃƒÂ£o.',
    'Passaporte com visto vÃƒÂ¡lido e carimbo de entrada nos EUA',
    'Passagem aÃƒÂ©rea de retorno',
    'ConfirmaÃƒÂ§ÃƒÂ£o do hotel (impresso ou digital)',
    'CartÃƒÂµes usados na viagem',
    'Recibos de compras (especialmente itens de alto valor)',
    'DeclaraÃƒÂ§ÃƒÂ£o de bens se acima de US$ 1.000 por pessoa',
    'Receita mÃƒÂ©dica para medicamentos controlados',
    'Etiquetas de bagagem',
  ].join('\n'),
};

export default blocoChecklistDocumentos;
