const blocoChecklistDocumentos = {
  titulo: 'âœ… Checklist Final + Documentos para o Retorno',
  tipo: 'informativa',
  descricao: [
    'Checklist de PreparaÃ§Ã£o para o Retorno:',
    'Revise cada item antes de sair para o aeroporto para evitar esquecimentos.',
    'Itens essenciais:',
    'Celular carregado e com internet (chip ou eSIM)',
    'Passaporte e documentos de viagem',
    'Bagagens prontas e identificadas',
    'Conferir banheiros, armÃ¡rios e embaixo da cama',
    'Guardar carregadores e eletrÃ´nicos',
    'Conferir compras e lembranÃ§as',
    'Revisar tempo atÃ© o aeroporto',
    'Transporte confirmado',
    'Check-out feito e chaves devolvidas',
    'Documentos e Cuidados no Embarque:',
    'Prepare documentos com antecedÃªncia e mantenha-os na bagagem de mÃ£o.',
    'Passaporte com visto vÃ¡lido e carimbo de entrada nos EUA',
    'Passagem aÃ©rea de retorno',
    'ConfirmaÃ§Ã£o do hotel (impresso ou digital)',
    'CartÃµes usados na viagem',
    'Recibos de compras (especialmente itens de alto valor)',
    'DeclaraÃ§Ã£o de bens se acima de US$ 1.000 por pessoa',
    'Receita mÃ©dica para medicamentos controlados',
    'Etiquetas de bagagem',
  ].join('\n'),
};

export default blocoChecklistDocumentos;
